### PR TITLE
Add rage trade APY

### PR DESCRIPTION
**Pull request by 134dd3v**
Result

```
Nb of pools: 3
 

Sample pools: [
  {
    pool: '0x8478AB5064EbAC770DdCE77E7D31D969205F041E',
    chain: 'Arbitrum',
    project: 'rage-trade',
    symbol: 'DN-GMX-JUNIOR',
    tvlUsd: 6920523.318942,
    apy: 16.93895184172351
  },
  {
    pool: '0xf9305009FbA7E381b3337b5fA157936d73c2CF36',
    chain: 'Arbitrum',
    project: 'rage-trade',
    symbol: 'DN-GMX-SENIOR',
    tvlUsd: 3350303.168524,
    apy: 7.154412791605262
  },
  {
    pool: '0x1d42783E7eeacae12EbC315D1D2D0E3C6230a068',
    chain: 'Arbitrum',
    project: 'rage-trade',
    symbol: '80-20-TRICRYPTO',
    tvlUsd: 3228121.835681,
    apy: 9.907202408355479
  }
]
```

### CODE REVIEW

**Comment by llamatester** [comment]
The rage-trade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────────┬────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │      symbol       │     tvlUsd     │        apy         │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────────┼────────────────┼────────────────────┤
    │    0    │ '0x8478AB5064EbAC770DdCE77E7D31D969205F041E' │ 'Arbitrum' │ 'rage-trade' │  'DN-GMX-JUNIOR'  │ 6925650.249894 │ 16.934701355362357 │
    │    1    │ '0xf9305009FbA7E381b3337b5fA157936d73c2CF36' │ 'Arbitrum' │ 'rage-trade' │  'DN-GMX-SENIOR'  │ 3350303.550867 │ 7.154412740935621  │
    │    2    │ '0x1d42783E7eeacae12EbC315D1D2D0E3C6230a068' │ 'Arbitrum' │ 'rage-trade' │ '80-20-TRICRYPTO' │ 3227186.949728 │ 9.896267249683921  │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────────┴────────────────┴────────────────────┘

**Comment by slasher125** [comment]
gm & ty for adding!

- lets move the current symbol to `poolMeta`
- symbol should be the deposit token
- lets use `apyBase` and `apyReward` instead of `apy` where `apyBase` would be the sum of any base components (eg GMX trader pnl apy + aave borrow apy)
- pls add the underlying token and reward token arrays

**Comment by 134dd3v** [comment]
> symbol should be the deposit token

The vault has supports multiple deposit tokens, how can we mention this?

> pls add the underlying token and reward token arrays

The rewards are converted in underlying token itself. So whatever user deposited, later they get more of their assets, instead of receiving any other reward tokens. Do we still need to mention those internal tokens in reward token array (even though user will not get those tokens)?

**Comment by llamatester** [comment]
The rage-trade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.349 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────────┬────────────────┬─────────────────┬──────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │      symbol       │     tvlUsd     │    poolMeta     │                 underlyingTokens                 │        apy        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────────┼────────────────┼─────────────────┼──────────────────────────────────────────────────┼───────────────────┤
    │    0    │ '0x8478AB5064EbAC770DdCE77E7D31D969205F041E' │ 'Arbitrum' │ 'rage-trade' │      'USDC'       │ 6971609.510268 │ 'DN_GMX_JUNIOR' │ [ '0x2F546AD4eDD93B956C8999Be404cdCAFde3E89AE' ] │ 37.48323676837737 │
    │    1    │ '0xf9305009FbA7E381b3337b5fA157936d73c2CF36' │ 'Arbitrum' │ 'rage-trade' │      'USDC'       │ 3350919.697168 │ 'DN_GMX_SENIOR' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 7.175338401920093 │
    │    2    │ '0x1d42783E7eeacae12EbC315D1D2D0E3C6230a068' │ 'Arbitrum' │ 'rage-trade' │ '80-20-TRICRYPTO' │ 3217612.995808 │                 │ [ '0x8e0B8c8BB9db49a46697F3a5Bb8A308e744821D2' ] │ 7.345051318471695 │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────────┴────────────────┴─────────────────┴──────────────────────────────────────────────────┴───────────────────┘

**Comment by 134dd3v** [comment]
> in that case it makes no sense to use the rewardTokens field. but still recommended to split btw apyBase and apyReward cause its very interesting seeing the where the apy is coming from

I just tried doing that but some test cases started failing. Any suggestions on this?

```
Check if pool has a rewardApy then rewardTokens must also exist
      ✕ The pool 0x8478AB5064EbAC770DdCE77E7D31D969205F041E is expected to have a rewardTokens field (1 ms)
      ✕ The pool 0xf9305009FbA7E381b3337b5fA157936d73c2CF36 is expected to have a rewardTokens field
      ✕ The pool 0x1d42783E7eeacae12EbC315D1D2D0E3C6230a068 is expected to have a rewardTokens field
```

For now I've pushed without the `apyReward` but have kept the base and reward components in the intermediate `apys` object for reference.

**Comment by 134dd3v** [comment]
Can you pls check now once again?

**Comment by 134dd3v** [comment]
Also would the DN vaults show up in the new Delta Neutral section here https://defillama.com/yields/strategy? Or do we need to add any additional changes?

**Comment by llamatester** [comment]
The rage-trade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.321 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────────┬────────────────┬─────────────────┬──────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │      symbol       │     tvlUsd     │    poolMeta     │                 underlyingTokens                 │        apy        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────────┼────────────────┼─────────────────┼──────────────────────────────────────────────────┼───────────────────┤
    │    0    │ '0x8478AB5064EbAC770DdCE77E7D31D969205F041E' │ 'Arbitrum' │ 'rage-trade' │      'USDC'       │ 6968051.798781 │ 'DN_GMX_JUNIOR' │ [ '0x2F546AD4eDD93B956C8999Be404cdCAFde3E89AE' ] │ 37.15012696295547 │
    │    1    │ '0xf9305009FbA7E381b3337b5fA157936d73c2CF36' │ 'Arbitrum' │ 'rage-trade' │      'USDC'       │ 3351869.40743  │ 'DN_GMX_SENIOR' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 5.306363303029057 │
    │    2    │ '0x1d42783E7eeacae12EbC315D1D2D0E3C6230a068' │ 'Arbitrum' │ 'rage-trade' │ '80-20-TRICRYPTO' │ 3218097.261644 │                 │ [ '0x8e0B8c8BB9db49a46697F3a5Bb8A308e744821D2' ] │ 7.238280242712265 │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────────┴────────────────┴─────────────────┴──────────────────────────────────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
re DN-page: no further change required from your side. though we restrict which farm pools we display. basically single exposure, no IL farms only (so that would remove the tricrypto and the risk on sGLP vault)

**Pull request merged**
