### PR TITLE
Cat-in-a-Box stETH CDP yield

### PR DESCRIPTION
**Pull request by vloxley**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running cat-in-a-box adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.434 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬─────────┬───────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │    project     │ symbol  │      tvlUsd       │      apyBase       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼─────────┼───────────────────┼────────────────────┤
    │    0    │ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84-ethereum' │ 'Ethereum' │ 'cat-in-a-box' │ 'stETH' │ 6660782.620241299 │ 10.733175983226657 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴─────────┴───────────────────┴────────────────────┘
    }

**Comment by slasher125** [comment]
henlo, ty for adding, a few things:
- pool value: based on what we have already discussed we need to alter this one here, you could add a suffix of your project name to it
- data should come from on chain calls instead of centralised api
- can u provide some details on where the apyBase is coming from?

ty

**Comment by llamatester** [comment]
The cat-in-a-box adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.374 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────┬────────────┬────────────────┬─────────┬───────────────────┬───────────────────┐
    │ (index) │                                pool                                │   chain    │    project     │ symbol  │      tvlUsd       │      apyBase      │
    ├─────────┼────────────────────────────────────────────────────────────────────┼────────────┼────────────────┼─────────┼───────────────────┼───────────────────┤
    │    0    │ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84-ethereum-cat-in-a-box' │ 'Ethereum' │ 'cat-in-a-box' │ 'stETH' │ 7543119.308223448 │ 10.39391284635743 │
    └─────────┴────────────────────────────────────────────────────────────────────┴────────────┴────────────────┴─────────┴───────────────────┴───────────────────┘

**Comment by vloxley** [comment]
Hi there! 

All the infomation now comes from a decentralized source, I apologize for this.
We calculate the yield based on a point system that takes into account how much collateral and debt the user has in our cdp system. Consequently, loans with a good health are rewarded with more yield originating from users with a less healthy position. Below you can find an example of a user with the most optimal position in our system.

user_debt = 0
user_deposit = 1
user_points = user_debt - user_deposit
total points = (total_value_locked + user_deposit) - total_debt_locked
total_protocol_yield = (total_value_locked + user_deposit) * (lido_apr / 100)
protocol_fees = (total_protocol_yield / 100) + ((total_protocol_yield * total_debt_locked) / ((total_value_locked + user_deposit) * 4))
total_protocol_yield = total_protocol_yield - protocol_fees
apr = 100 / (user_deposit / (total_protocol_yield / (total_points / user_points)))

Please feel free to let us know if there are any questions.
Kind regards, Team Cat-in-a-Box

**Comment by slasher125** [comment]
hi sir.
- the current apy value is the optimistic case right? do you have an idea what the average and lower bound cases might look like?
- re api: i think this has been a misunderstanding. we no longer accept api calls for tvl/apy values inside yield adapters. sdk, subgraph etc can be used instead.

**Comment by llamatester** [comment]
The cat-in-a-box adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.374 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────┬────────────┬────────────────┬─────────┬────────────┬─────────┐
    │ (index) │                                pool                                │   chain    │    project     │ symbol  │   tvlUsd   │ apyBase │
    ├─────────┼────────────────────────────────────────────────────────────────────┼────────────┼────────────────┼─────────┼────────────┼─────────┤
    │    0    │ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84-ethereum-cat-in-a-box' │ 'Ethereum' │ 'cat-in-a-box' │ 'stETH' │ 7148973.21 │  8.29   │
    └─────────┴────────────────────────────────────────────────────────────────────┴────────────┴────────────────┴─────────┴────────────┴─────────┘

**Comment by vloxley** [comment]
Dear Slasher,

My apologies. Other than the value I pick up from lido everything should be decentralized by now. 

The calculation is not immediately about the most optimistic scenario but rather about a user who simply deposits without taking a loan. Even at fairly high amounts, this is perfectly reasonable. However, it is difficult to give an average because it depends heavily on the user's ltv. 

Thank you for your time ser.
Team Cat-in-a-Box

**Comment by slasher125** [comment]
ty for making the change sir

**Pull request merged**
