### PR TITLE
feat: velo v3 slipstream yields

### PR DESCRIPTION
**Pull request by ethzoomer**

### CODE REVIEW

**Comment by llamatester** [comment]
The velodrome-v3 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       228 passed, 228 total
    Snapshots:   0 total
    Time:        0.349 s
    Ran all test suites.
    
    Nb of pools: 32
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │    project     │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x478946BcD4a5a22b316470F5486fAfb928C0bA25' │ 'Optimism' │ 'velodrome-v3' │  'USDC-WETH'  │ 1505915.1784321973 │ 3962.2972848988356 │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x4200000000000000000000000000000000000006' ] │
    │    1    │ '0x2FA71491F8070FA644d97b4782dB5734854c0f6F' │ 'Optimism' │ 'velodrome-v3' │  'USDC-USDC'  │ 1087138.0214515952 │ 16.59780566694195  │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │
    │    2    │ '0x4DC22588Ade05C40338a9D95A6da9dCeE68Bcd60' │ 'Optimism' │ 'velodrome-v3' │   'WETH-OP'   │ 775696.0058402368  │ 591.4386207664348  │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x4200000000000000000000000000000000000006', '0x4200000000000000000000000000000000000042' ] │
    │    3    │ '0xbF30Ff33CF9C6b0c48702Ff17891293b002DfeA4' │ 'Optimism' │ 'velodrome-v3' │ 'wstETH-WETH' │ 676015.3586362601  │ 118.17912880437184 │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb', '0x4200000000000000000000000000000000000006' ] │
    │    4    │ '0x3C01ec09D15D5450FC702DC4353b17Cd2978d8a5' │ 'Optimism' │ 'velodrome-v3' │  'USDC-sUSD'  │ 587645.8902363761  │ 3396.0493480332316 │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x8c6f28f2F1A3C87F0f938b96d27520d9751ec8d9' ] │
    │    5    │ '0xeBD5311beA1948e1441333976EadCFE5fBda777C' │ 'Optimism' │ 'velodrome-v3' │   'USDC-OP'   │ 442366.25652690243 │ 614.2402303001455  │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x4200000000000000000000000000000000000042' ] │
    │    6    │ '0x84Ce89B4f6F67E523A81A82f9f2F14D84B726F6B' │ 'Optimism' │ 'velodrome-v3' │  'USDC-USDT'  │ 394470.3509778773  │ 56.441234800704386 │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58' ] │
    │    7    │ '0x319C0DD36284ac24A6b2beE73929f699b9f48c38' │ 'Optimism' │ 'velodrome-v3' │  'WETH-WBTC'  │ 349705.3892393527  │ 423.42223845815505 │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x4200000000000000000000000000000000000006', '0x68f180fcCe6836688e9084f035309E29Bf0A2095' ] │
    │    8    │ '0x1737275d53A5Ca5dAc582a493AA32C85ba2cFaD3' │ 'Optimism' │ 'velodrome-v3' │  'USDC-DAI'   │ 305298.9299291692  │ 69.14967633241545  │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1' ] │
    │    9    │ '0xF25bbc18a607bBe218c87BA1fF0E673d9B53dd58' │ 'Optimism' │ 'velodrome-v3' │  'USDC-SNX'   │ 170592.18393207903 │  4318.5874954366   │ [ '0x9560e827aF36c94D2Ac33a39bCE1Fe78631088Db' ] │ [ '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85', '0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, pls add poolMeta (see velodrome-v2), also url fields to the individual pools would be very helpful

**Comment by 0xngmi** [comment]
yes

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       536 passed, 536 total
    Snapshots:   0 total
    Time:        0.446 s
    Ran all test suites.
    
    Nb of pools: 76
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬────────────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │        project         │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │    poolMeta     │                                                                                                 url                                                                                                 │
    ├─────────┼──────────────────────────────────────────────┼────────┼────────────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x47cA96Ea59C13F72745928887f84C9F52C3D7348' │ 'Base' │ 'aerodrome-slipstream' │ 'cbETH-WETH'  │ 17821364.95669273  │ 11.445245183162745 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │  'CL1 - 0.05%'  │  'https://aerodrome.finance/deposit?token0=0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22&token1=0x4200000000000000000000000000000000000006&type=1&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'  │
    │    1    │ '0x0c1A09d5D0445047DA3Ab4994262b22404288A3B' │ 'Base' │ 'aerodrome-slipstream' │  'USDC-USD+'  │ 14399324.001226243 │ 50.14865263062098  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │  'CL1 - 0.01%'  │  'https://aerodrome.finance/deposit?token0=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&token1=0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376&type=1&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'  │
    │    2    │ '0xb2cc224c1c9feE385f8ad6a55b4d94E92359DC59' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USDC'  │ 14311029.86402668  │ 2577.4546603678255 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │ 'CL100 - 0.04%' │ 'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&type=100&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A' │
    │    3    │ '0x98c7A2338336d2d354663246F64676009c7bDa97' │ 'Base' │ 'aerodrome-slipstream' │ 'USDC-USDbC'  │ 11789659.958305176 │ 14.809868516685803 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │  'CL1 - 0.01%'  │  'https://aerodrome.finance/deposit?token0=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&token1=0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA&type=1&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'  │
    │    4    │ '0x861A2922bE165a5Bd41b1E482B49216b465e1B5F' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-wstETH' │ 10641333.521021914 │ 10.956613305477063 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │  'CL1 - 0.01%'  │  'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452&type=1&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'  │
    │    5    │ '0x2ae9DF02539887d4EbcE0230168a302d34784c82' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-bsdETH' │ 4910556.543749326  │ 13.53666234947104  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff' ] │  'CL1 - 0.3%'   │  'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff&type=1&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A'  │
    │    6    │ '0x82321f3BEB69f503380D6B233857d5C43562e2D0' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-AERO'  │ 3224745.277496624  │ 1232.336688579906  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ 'CL200 - 0.6%'  │ 'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0x940181a94A35A4569E4529A3CDfB74e38FD98631&type=200&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A' │
    │    7    │ '0x2092f4acbb18BB1649595DF59B9Cb601bBA1EBB7' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-RDNT'  │ 3049539.166115868  │ 2906.644269543098  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xd722E55C1d9D9fA0021A5215Cbb904b92B3dC5d4' ] │ 'CL200 - 0.3%'  │ 'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0xd722E55C1d9D9fA0021A5215Cbb904b92B3dC5d4&type=200&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A' │
    │    8    │ '0x4e829F8A5213c42535AB84AA40BD4aDCCE9cBa02' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-BRETT'  │ 2157388.704744478  │ 3134.2870524410555 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x532f27101965dd16442E59d40670FaF5eBB142E4' ] │ 'CL200 - 0.25%' │ 'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0x532f27101965dd16442E59d40670FaF5eBB142E4&type=200&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A' │
    │    9    │ '0x4D69971CCd4A636c403a3C1B00c85e99bB9B5606' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USD+'  │ 1980761.2364014206 │ 4398.452353133199  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │ 'CL100 - 0.04%' │ 'https://aerodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376&type=100&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A' │
    └─────────┴──────────────────────────────────────────────┴────────┴────────────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
@ethzoomer hey sir
i wasn't paying enough attention when reviewing this and the velodrome v3 adapter: for concentrated liquidity pools we usually assume a much wider range than whats being applied in this adapter (eg for uni v3 we use +/- 30% for non stable and 0.1% range for stable pools)

so we need to modify this and other adapter to use much wider and more realistic ranges for eg 'CL100' and 'CL200' eg the wide range in here: https://velodrome.finance/deposit?token0=0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85&token1=0x4200000000000000000000000000000000000006&type=100&factory=0xCc0bDDB707055e04e497aB22a59c2aF4391cd12F

i've temporarily disabled these pools from showing up on our ui until modified, can u apply these changes across both adapters?

**Pull request merged**
