### PR TITLE
Add Kinetix AMM V3

### PR DESCRIPTION
**Pull request by 0xrmvdao**

### CODE REVIEW

**Comment by llamatester** [comment]
The kinetix-amm-v3 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       179 passed, 179 total
    Snapshots:   0 total
    Time:        0.287 s
    Ran all test suites.
    
    Nb of pools: 25
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────────┬──────────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │     project      │      symbol      │       tvlUsd       │ apyReward │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────────┼──────────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x8f6e94375d93e60b805cde30388da55b9f97210b' │ 'Kava' │ 'kinetix-amm-v3' │  'axlUSDT-USDt'  │ 252193.23740200012 │   0.01    │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    1    │ '0x6c21797dc7445a38c1e219a0146de7c784c92422' │ 'Kava' │ 'kinetix-amm-v3' │  'USDt-axlUSDC'  │ 182424.83307588735 │   0.13    │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x919C1c267BC06a7039e03fcc2eF738525769109c', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │
    │    2    │ '0xb6427fb95bbbcdc422479a1ac0622df8341c98e0' │ 'Kava' │ 'kinetix-amm-v3' │   'USDt-WKAVA'   │ 116935.52274564112 │   26.62   │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x919C1c267BC06a7039e03fcc2eF738525769109c', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    3    │ '0x1e19e544c27350fab2726575f339f9d214dea57b' │ 'Kava' │ 'kinetix-amm-v3' │   'KAI-WKAVA'    │ 69797.24684410503  │   12.06   │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    4    │ '0xeb4eb392aba1e1abc1e0771fb257e8115f9c245a' │ 'Kava' │ 'kinetix-amm-v3' │    'KAI-USDt'    │ 36319.451591041674 │   17.78   │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    5    │ '0xe88e7dc65d58eb25a7de7b67fec2ca1237ae9c5f' │ 'Kava' │ 'kinetix-amm-v3' │  'WETH-axlETH'   │ 26083.061981690757 │   0.28    │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8', '0xb829b68f57CC546dA7E5806A929e53bE32a4625D' ] │
    │    6    │ '0xc5c777c835bb1237ad1831d1ac75910c06888ba0' │ 'Kava' │ 'kinetix-amm-v3' │   'ATOM-WKAVA'   │ 22467.07999960969  │   11.5    │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    7    │ '0x09a082d7fd3c5e7a5fb3607c69b47109971b17d5' │ 'Kava' │ 'kinetix-amm-v3' │ 'axlWBTC-axlETH' │ 22004.479641966325 │   1.06    │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad', '0xb829b68f57CC546dA7E5806A929e53bE32a4625D' ] │
    │    8    │ '0x229ba1db81c157426766ebc1135c4853f0af344f' │ 'Kava' │ 'kinetix-amm-v3' │   'ATOM-USDt'    │ 21338.889662679998 │   24.49   │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    9    │ '0x2203e0e80bfa6243614c2d34a65648877eea20a0' │ 'Kava' │ 'kinetix-amm-v3' │   'WETH-WKAVA'   │ 19893.962113109395 │   10.55   │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────────┴──────────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm @0xrmvdao
feeApr is from trading fees yes? we need to add that part to apyBase, any remaining farming rewards need to be added to apyReward

**Comment by llamatester** [comment]
The kinetix-amm-v3 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       179 passed, 179 total
    Snapshots:   0 total
    Time:        0.29 s
    Ran all test suites.
    
    Nb of pools: 25
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────────┬──────────────────┬────────────────────┬──────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │     project      │      symbol      │       tvlUsd       │       apyBase        │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────────┼──────────────────┼────────────────────┼──────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x8f6e94375d93e60b805cde30388da55b9f97210b' │ 'Kava' │ 'kinetix-amm-v3' │  'axlUSDT-USDt'  │ 255990.50812399999 │ 0.010000498649831435 │ 26.63617765453823  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    1    │ '0x6c21797dc7445a38c1e219a0146de7c784c92422' │ 'Kava' │ 'kinetix-amm-v3' │  'USDt-axlUSDC'  │   196272.549679    │ 0.13008430482186473  │ 27.29445259296157  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x919C1c267BC06a7039e03fcc2eF738525769109c', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │
    │    2    │ '0xb6427fb95bbbcdc422479a1ac0622df8341c98e0' │ 'Kava' │ 'kinetix-amm-v3' │   'USDt-WKAVA'   │ 89833.14424552635  │  22.02377505508537   │ 117.23465815400988 │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x919C1c267BC06a7039e03fcc2eF738525769109c', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    3    │ '0x1e19e544c27350fab2726575f339f9d214dea57b' │ 'Kava' │ 'kinetix-amm-v3' │   'KAI-WKAVA'    │ 70397.31079923952  │  21.173045552669322  │ 44.141199756978565 │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    4    │ '0xeb4eb392aba1e1abc1e0771fb257e8115f9c245a' │ 'Kava' │ 'kinetix-amm-v3' │    'KAI-USDt'    │ 39347.16218501562  │  19.752327091602773  │ 91.77820017986538  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    5    │ '0xe88e7dc65d58eb25a7de7b67fec2ca1237ae9c5f' │ 'Kava' │ 'kinetix-amm-v3' │  'WETH-axlETH'   │ 26277.989201154334 │ 0.31047967638468954  │ 19.27108096455261  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8', '0xb829b68f57CC546dA7E5806A929e53bE32a4625D' ] │
    │    6    │ '0x09a082d7fd3c5e7a5fb3607c69b47109971b17d5' │ 'Kava' │ 'kinetix-amm-v3' │ 'axlWBTC-axlETH' │ 23733.867521086555 │  0.8435281520410065  │ 35.560201168476404 │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x1a35EE4640b0A3B87705B0A4B45D227Ba60Ca2ad', '0xb829b68f57CC546dA7E5806A929e53bE32a4625D' ] │
    │    7    │ '0xc5c777c835bb1237ad1831d1ac75910c06888ba0' │ 'Kava' │ 'kinetix-amm-v3' │   'ATOM-WKAVA'   │ 20652.494602311708 │   7.43254310410828   │ 32.49493405520663  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    │    8    │ '0x229ba1db81c157426766ebc1135c4853f0af344f' │ 'Kava' │ 'kinetix-amm-v3' │   'ATOM-USDt'    │   20648.86900141   │  13.630029717194736  │ 36.82993361180398  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x15932E26f5BD4923d46a2b205191C4b5d5f43FE3', '0x919C1c267BC06a7039e03fcc2eF738525769109c' ] │
    │    9    │ '0x2203e0e80bfa6243614c2d34a65648877eea20a0' │ 'Kava' │ 'kinetix-amm-v3' │   'WETH-WKAVA'   │ 17161.27106772842  │  7.690639250558884   │ 38.92778535795887  │ [ '0x52369B1539EA8F4e1eadEEF18D85462Dcf9a3658' ] │ [ '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8', '0xc86c7C0eFbd6A49B35E8714C5f59D99De09A225b' ] │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────────┴──────────────────┴────────────────────┴──────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by 0xrmvdao** [comment]
Hi @slasher125, 
Yes, the feeApr is derived from trading fees. Farming rewards added to apyReward. I've sent the necessary update.

**Pull request merged**
