### PR TITLE
Arbidex quantum pools adapter

### PR DESCRIPTION
**Pull request by harleen-m**
Adapter for Arbidex' quantum v3 pools.

### CODE REVIEW

**Comment by llamatester** [comment]
The arbitrum-exchange-v3 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.322 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────────────┬────────────────────────────┬─────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │        project         │          poolMeta          │   symbol    │       tvlUsd       │     apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │                  url                   │    volumeUsd1d     │    volumeUsd7d     │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────────────┼────────────────────────────┼─────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x48d7e1a9d652ba5f5d80a8dc396df37993659f35' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.045%, stablePool=false' │ 'WETH-USDC' │ 1661546.1572368739 │ 22.46120156657922  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/quantumliquidity/' │  346531.428730966  │ 669932.6593367788  │
    │    1    │ '0x27629d01f673d9f68efa136c30865a5720dbf5c3' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.008%, stablePool=true'  │ 'USDT-USDC' │ 1461304.127312044  │ 12.30780508058049  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/quantumliquidity/' │ 15421.372204356783 │ 105371.04067781656 │
    │    2    │ '0xb7fa82d0493f6c51f03b1da41387d3eede594f6d' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.045%, stablePool=false' │ 'WBTC-WETH' │ 1446725.9593354417 │ 17.32410402482109  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://arbidex.fi/quantumliquidity/' │ 66759.04324841194  │ 224293.6860018893  │
    │    3    │ '0x814df4dd3b2bfc7a37504308d3332691cb57ef32' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.045%, stablePool=false' │ 'WBTC-USDC' │ 658009.8352008299  │ 51.46952170494481  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/quantumliquidity/' │  96532.6377346642  │ 216675.93731492915 │
    │    4    │ '0x06537920bde4960713e220bd9cb4844a1461101c' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.008%, stablePool=true'  │ 'DAI-USDC'  │  620081.841970555  │ 13.11037465898602  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/quantumliquidity/' │ 6247.105172046271  │ 18357.552513306746 │
    │    5    │ '0xbb304e41a3dcab1eebe4bf9975e39f91fabe69d0' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.045%, stablePool=false' │ 'WETH-ARB'  │ 163371.78819862794 │ 50.52998333408464  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'https://arbidex.fi/quantumliquidity/' │ 42927.29376234327  │ 76728.44315954631  │
    │    6    │ '0xafe48b65a14be5dba2693118b0901b322232c9f1' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.25%, stablePool=false'  │ 'ARB-USDC'  │ 141727.89073433873 │ 46.95198905774729  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/quantumliquidity/' │ 19608.52547717382  │ 38871.24166145116  │
    │    7    │ '0x3418f617c8ec5efbcf929fb2e33802c5a693f1c5' │ 'Arbitrum' │ 'arbitrum-exchange-v3' │ '0.25%, stablePool=false'  │ 'RDNT-WETH' │ 128949.89385953022 │ 129.01147445272738 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x3082cc23568ea640225c2467653db90e9250aaa0', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://arbidex.fi/quantumliquidity/' │ 7903.028373485986  │ 20750.00977881798  │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────────────┴────────────────────────────┴─────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
ty for adding. 
can u explain how the arb-usdc pool for example is earning weth? 

rewardtokens should only contain tokens which are paid out as incentives. so arx. not sure if that is the case for weth here too..

**Comment by harleen-m** [comment]
Yes, thank you for asking. The swap fees are being converted to WETH and the WETH is then redistributed among ARX stakers and LP stakers. The idea is that with rising volume WETH rewards would slowly replace (part of) ARX rewards.

**Comment by slasher125** [comment]
ic. i'd move the weth reward though into `apyBase` if that is really 100% based on swap fees.

**Comment by harleen-m** [comment]
Yeah, I'm not 100% sure where the WETH apy should be. It is based on swap fees, but only indirectly.

My understanding is that all the v3 pool swap fees go into one bucket and then every so often the tokens get converted to WETH and this WETH gets redistributed back among the v3 pools (and ARX single stakers) as "rewards". But the redistribution ratio is different than the ratio of swap fees collected. So some pools might get more back and others less.

Do I make sense? What do you think?

**Pull request merged**
