### PR TITLE
Add Rodeo adapter

### PR DESCRIPTION
**Pull request by voytenko-d**
Name (to be shown on DefiLlama): Rodeo

Twitter Link: https://twitter.com/Rodeo_Finance

List of audit links if any: https://docs.rodeofinance.xyz/core-concepts/security/smart-contract-audits

Website Link: https://www.rodeofinance.xyz

Logo (High resolution, preferably in .svg and .png, for application on both white and black backgrounds. Will be shown with rounded borders):
image
logo_rodeo

Current TVL: 10990 USD

Chain: Arbitrum

Short Description (to be shown on DefiLlama): Rodeo is creating a leverage hyperstructure on Arbitrum that lets users increase their positions in top-tier vaults and strategies

Category (full list at https://defillama.com/categories) *Please choose only one:  Yield

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using): Using Chainlink, Balancer, TWAP, Uniswap V2/V3

methodology (what is being counted as tvl, how is tvl being calculated): The result is calculated by subtracting borrow tvl from supply tvl

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running rodeo adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 10 passed, 11 total
    Snapshots:   0 total
    Time:        0.349 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────┬────────────────────┬───────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────┬──────────────────┬─────────────────┬───────────────────┬────────────────────┬─────┐
    │ (index) │                     pool                     │   chain    │ project │ symbol │       tvlUsd       │      apyBase      │ apyReward │                 underlyingTokens                 │                   rewardTokens                   │                 url                 │  apyBaseBorrow   │ apyRewardBorrow │  totalSupplyUsd   │   totalBorrowUsd   │ ltv │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────┼────────────────────┼───────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────┼──────────────────┼─────────────────┼───────────────────┼────────────────────┼─────┤
    │    0    │ '0x0032F5E1520a66C6E572e96A11fBF54aea26f9bE' │ 'Arbitrum' │ 'rodeo' │ 'USDC' │ 10990.784578102233 │ 14.17806843643898 │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://www.rodeofinance.xyz/farm' │ 14.9970276639936 │        0        │ 201266.5524985498 │ 190275.76792044757 │  0  │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────┴────────────────────┴───────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────┴──────────────────┴─────────────────┴───────────────────┴────────────────────┴─────┘
    }

**Comment by slasher125** [comment]
hi ty for adding. pls make sure the adapter name matches the slug from /protocols output

**Comment by slasher125** [comment]
@voytenko-d make sure to also provide an adapter for tvl. this one here is for the yield pages only. however, we can only list on yields if there is a tvl adapter in the first place.

**Comment by voytenko-d** [comment]
> hi ty for adding. pls make sure the adapter name matches the slug from /protocols output

Hi, yeah, this is my question which I sent to 'Discord', how can I add our project to the slug in order to appear here - https://api.llama.fi/protocols? I didn't find any documentation for that

**Comment by slasher125** [comment]
@voytenko-d yes that is the correct endpoint. you are not listed yet on tvl. u need to start here: https://github.com/DefiLlama/DefiLlama-Adapters#defillama-adapters

**Comment by llamatester** [comment]
The rodeo adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.349 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────┬───────────────────┬───────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────┬─────────────────┬─────────────────┬────────────────────┬───────────────────┬─────┐
    │ (index) │                     pool                     │   chain    │ project │ symbol │      tvlUsd       │      apyBase      │ apyReward │                 underlyingTokens                 │                   rewardTokens                   │                 url                 │  apyBaseBorrow  │ apyRewardBorrow │   totalSupplyUsd   │  totalBorrowUsd   │ ltv │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────┼───────────────────┼───────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼────────────────────┼───────────────────┼─────┤
    │    0    │ '0x0032F5E1520a66C6E572e96A11fBF54aea26f9bE' │ 'Arbitrum' │ 'rodeo' │ 'USDC' │ 28196.23792913265 │ 8.218569153020027 │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://www.rodeofinance.xyz/farm' │ 9.1644590083968 │        0        │ 273185.36637609935 │ 244989.1284469667 │  0  │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────┴───────────────────┴───────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────┴─────────────────┴─────────────────┴────────────────────┴───────────────────┴─────┘

**Comment by llamatester** [comment]
The rodeo adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.428 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────┬───────────────────┬──────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┬─────┐
    │ (index) │                     pool                     │   chain    │ project │ symbol │      tvlUsd       │     apyBase      │ apyReward │                 underlyingTokens                 │                   rewardTokens                   │                 url                 │  apyBaseBorrow  │ apyRewardBorrow │  totalSupplyUsd  │  totalBorrowUsd   │ ltv │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────┼───────────────────┼──────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼──────────────────┼───────────────────┼─────┤
    │    0    │ '0x0032F5E1520a66C6E572e96A11fBF54aea26f9bE' │ 'Arbitrum' │ 'rodeo' │ 'USDC' │ 49288.13678178209 │ 2.89679930927332 │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://www.rodeofinance.xyz/farm' │ 3.4900498166832 │        0        │ 289958.542961796 │ 240670.4061800139 │  0  │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────┴───────────────────┴──────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┴─────┘

**Pull request merged**
