### PR TITLE
Add Sommelier Adapter

### PR DESCRIPTION
**Pull request by sandbochs**
Introduces Sommelier Adapter for Yield dashboard.

 [Main TVL Link](https://defillama.com/protocol/sommelier)

### CODE REVIEW

**Comment by sandbochs** [comment]
Waiting on Sommelier team members to review this.

**Comment by sandbochs** [comment]
Somm team 👍 , ready for review

**Comment by llamatester** [comment]
The sommelier adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.326 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │   project   │    symbol     │       tvlUsd       │      apyBase       │     apyReward      │                   rewardTokens                   │                                                               underlyingTokens                                                               │                             url                             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────┤
    │    0    │ '0x7bad5df5e11151dc5ee1a648800057c5c934c0d5-ethereum' │ 'ethereum' │ 'sommelier' │ 'aave2-CLR-S' │  857113.035692914  │ 2.1107407236653524 │ 13.422903976220544 │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                                               [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ]                                               │   'https://app.sommelier.finance/strategies/AAVE/manage'    │
    │    1    │ '0x6b7f87279982d919bbf85182ddeab179b366d8f2-ethereum' │ 'ethereum' │ 'sommelier' │ 'ETHBTCTrend' │ 198563.60643386748 │ 0.273504187164749  │ 128.7053477181618  │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │  'https://app.sommelier.finance/strategies/ETH-BTC-Trend'   │
    │    2    │ '0x6e2dac3b9e9adc0cbbae2d0b9fd81952a8d33872-ethereum' │ 'ethereum' │ 'sommelier' │  'ETHBTCMom'  │  172103.883349346  │ 11.010404509448486 │ 79.74463143569933  │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │ 'https://app.sommelier.finance/strategies/ETH-BTC-Momentum' │
    │    3    │ '0x3f07a84ecdf494310d397d24c1c78b041d2fa622-ethereum' │ 'ethereum' │ 'sommelier' │  'SteadyETH'  │ 127803.7693051365  │      -0.0072       │ 119.10300529280313 │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ]                        │    'https://app.sommelier.finance/strategies/Steady-ETH'    │
    │    4    │ '0x4986fd36b6b16f49b43282ee2e24c5cf90ed166d-ethereum' │ 'ethereum' │ 'sommelier' │  'SteadyBTC'  │ 83585.40952391256  │      -0.4008       │ 186.48376692882883 │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ]                        │    'https://app.sommelier.finance/strategies/Steady-BTC'    │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
henlo, ty for adding. 1 request:
- what you are currently using as `symbol` i'd use as `poolMeta`. For symbol Lets use the underlying tokens eg BTC, ETH, ETH-BTC (for the trend and momentum pools). for aave I'd just go with USDC (i know not ideal cause it can run on any stablecoin market there...). Reason we require this is cause currently we derive meta data from the symbols (such as if a pool is exposed to 1 or more token, if it has IL or not etc.)

**Comment by slasher125** [comment]
also, can u pls explain the bonding mechanism to receive apyReward? Is it a fixed rate until lp token can't be withdrawn ?

**Comment by sandbochs** [comment]
> also, can u pls explain the bonding mechanism to receive apyReward? Is it a fixed rate until lp token can't be withdrawn ?

Hi @slasher125 thanks for looking. The bonding mechanism is not a fixed rate. It is dependent on how many people are bonded and for what bonding period (lockup time). As more people bond, they need to split the available reward tokens until the reward period is over.

**Comment by llamatester** [comment]
The sommelier adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.333 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────┬───────────┬───────────────┬───────────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │   project   │  symbol   │   poolMeta    │      tvlUsd       │       apyBase       │     apyReward      │                   rewardTokens                   │                                                               underlyingTokens                                                               │                             url                             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────┼───────────┼───────────────┼───────────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────┤
    │    0    │ '0x7bad5df5e11151dc5ee1a648800057c5c934c0d5-ethereum' │ 'ethereum' │ 'sommelier' │  'USDC'   │ 'aave2-CLR-S' │ 816043.3838470369 │ 2.1107407236653524  │ 10.596247078979088 │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                                               [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ]                                               │   'https://app.sommelier.finance/strategies/AAVE/manage'    │
    │    1    │ '0x6b7f87279982d919bbf85182ddeab179b366d8f2-ethereum' │ 'ethereum' │ 'sommelier' │ 'ETH-BTC' │ 'ETHBTCTrend' │ 212926.909871676  │ -76.66009845356876  │         0          │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │  'https://app.sommelier.finance/strategies/ETH-BTC-Trend'   │
    │    2    │ '0x6e2dac3b9e9adc0cbbae2d0b9fd81952a8d33872-ethereum' │ 'ethereum' │ 'sommelier' │ 'ETH-BTC' │  'ETHBTCMom'  │ 160441.682007607  │ -23.832746702853992 │         0          │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │ 'https://app.sommelier.finance/strategies/ETH-BTC-Momentum' │
    │    3    │ '0x3f07a84ecdf494310d397d24c1c78b041d2fa622-ethereum' │ 'ethereum' │ 'sommelier' │   'ETH'   │  'SteadyETH'  │ 157478.017154458  │       -0.0072       │         0          │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ]                        │    'https://app.sommelier.finance/strategies/Steady-ETH'    │
    │    4    │ '0x4986fd36b6b16f49b43282ee2e24c5cf90ed166d-ethereum' │ 'ethereum' │ 'sommelier' │   'BTC'   │  'SteadyBTC'  │ 121237.002955068  │       -0.4008       │         0          │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ]                        │    'https://app.sommelier.finance/strategies/Steady-BTC'    │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────┴───────────┴───────────────┴───────────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
oke ty. a few follow up question:

- if i don't bond I will only earn `apyBase`?
- the current `apyReward` values, are they based on the min bonding time?
- over what period is `apyBase` calculated?

**Comment by sandbochs** [comment]
@slasher125 thanks for the q's.
- Yes, you must bond to earn `apyReward`
- The `apyReward` value is based on the min bonding time
- `apyBase` is calculated on about a weekly basis. It is dependent on when the strategists accrue / rebalance. This is usually around 7-10 days.

For the v0.8.15 Cellars, management and performance splits are already deducted.
For v0.8.16 management fees are already deducted but performance splits are not. They must be manually claimed by the strategist. I can look into figuring what the outstanding fees are so I can deduct from the `apyBase` calc if necessary.

LMK.

**Comment by slasher125** [comment]
@sandbochs henlo ser and ty for detailed reply:
- yes pls lets deduct any performance splits so that we display net values
- that is min bonding time to receive the reward apr?

**Comment by sandbochs** [comment]
@slasher125 

I spoke with the team to figure out how to deduct perf splits and it looks like I was incorrect initially. All performance splits are baked into the shareValue for both v0.8.15 and v0.8.16 cellars. The current calc for `baseApy` is inclusive of this so there should not need to be a change.

No, that is not the min bonding time to receive the reward APR, I believe the min bonding time is currently set to 3 days. The other two options are 7 and 14 days.

**Pull request merged**
