### PR TITLE
Adding Fungify APY adapter

### PR DESCRIPTION
**Pull request by fungify**
APY yield adapter for Fungify (https://fungify.it/)

### CODE REVIEW

**Comment by fungify** [comment]
Please review this PR. We believe the 1 check filing is an issue in beforeTests.js and not something we can fix on our end. Thanks.

**Comment by slasher125** [comment]
use `require('@defillama/sdk5');` instead. also good to run the tests locally first

**Comment by llamatester** [comment]
The fungify adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       151 passed, 151 total
    Snapshots:   0 total
    Time:        0.309 s
    Ran all test suites.
    
    Nb of pools: 21
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬──────────────┬────────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────┬───────────────────┬──────┐
    │ (index) │                         pool                          │   chain    │  project  │    symbol    │       tvlUsd       │      apyBase      │                   rewardTokens                   │                 underlyingTokens                 │              url               │   apyBaseBorrow   │ ltv  │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────┼───────────────────┼──────┤
    │    0    │ '0x5f86f598e4fa983097fe6693a1b51f047d87b9cf-ethereum' │ 'ethereum' │ 'fungify' │   'fUSDC'    │ 701504.7195271169  │ 0.203203744460568 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'https://app.fungify.it/pools' │ 0.340758602835228 │ 0.85 │
    │    1    │ '0x70c4f75ebaf99e24d775c91867b1a844da6ef6fd-ethereum' │ 'ethereum' │ 'fungify' │    'fETH'    │ 561776.1132480516  │ 0.02394624836934  │                  [ 'ethereum' ]                  │                  [ 'ethereum' ]                  │ 'https://app.fungify.it/pools' │ 0.082715084770752 │ 0.85 │
    │    2    │ '0xbf1c1370cc5a96af40499502f8d5ec9403e0a18a-ethereum' │ 'ethereum' │ 'fungify' │   'fPUNKS'   │  441014.06064618   │ 0.024305583529044 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xb7F7F6C52F2e2fdb1963Eab30438024864c313F6' ] │ 'https://app.fungify.it/pools' │ 0.083333381292324 │ 0.65 │
    │    3    │ '0x2b142208e665525952786c6e77cba0cb2e694b41-ethereum' │ 'ethereum' │ 'fungify' │   'fsUSDe'   │ 255304.48028431382 │    3.6792e-10     │ [ '0x9D39A5DE30e57443BfF2A8307A4256c8797A3497' ] │ [ '0x9D39A5DE30e57443BfF2A8307A4256c8797A3497' ] │ 'https://app.fungify.it/pools' │ 0.00001026701784  │ 0.85 │
    │    4    │ '0xf0bb06816f081829726bd6d3d04c823ce3e96b69-ethereum' │ 'ethereum' │ 'fungify' │   'fUSDT'    │ 219941.44952263607 │ 0.034573389769044 │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ 'https://app.fungify.it/pools' │ 0.140556830945112 │ 0.85 │
    │    5    │ '0xa603cee4fd20c589b5aecbf07356b239cb11ee5a-ethereum' │ 'ethereum' │ 'fungify' │   'fBAYC'    │ 214039.86663715003 │ 0.078750086130972 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D' ] │ 'https://app.fungify.it/pools' │ 0.15000008203098  │ 0.65 │
    │    6    │ '0xe0b0a19f749c6054d6412591b799b04107fe69f3-ethereum' │ 'ethereum' │ 'fungify' │ 'fHONEYCOMB' │ 196228.35730409998 │ 0.000225199461636 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xCB0477d1Af5b8b05795D89D59F4667b59eAE9244' ] │ 'https://app.fungify.it/pools' │ 0.008021390405112 │ 0.45 │
    │    7    │ '0x0aeb0fbb880e0ab702dd981ae091d272a966b54b-ethereum' │ 'ethereum' │ 'fungify' │    'fPPG'    │  167222.43723592   │ 0.123047093478708 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8' ] │ 'https://app.fungify.it/pools' │ 0.18750016646154  │ 0.65 │
    │    8    │ '0xfb973b5cd8d18eb514aa19a35afde689f5ba04e3-ethereum' │ 'ethereum' │ 'fungify' │  'fwstETH'   │ 103590.66141269861 │    3.23244e-10    │ [ '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0' ] │ [ '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0' ] │ 'https://app.fungify.it/pools' │ 0.000009633937896 │ 0.85 │
    │    9    │ '0x3b37c50b237d12aefdc48d14f63dc3009ba35155-ethereum' │ 'ethereum' │ 'fungify' │   'fSAPS'    │ 101229.91104285001 │ 0.038996918264232 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0x364C828eE171616a39897688A831c2499aD972ec' ] │ 'https://app.fungify.it/pools' │  0.1055555618949  │ 0.45 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴──────────────┴────────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────┴───────────────────┴──────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
- apy needs to be scaled to %
- tvlUsd for lending projects needs to be available liquiidty (see readme)
- pls add totalSupplyUsd and tolalBorrowUsd to the adapter
- you return rewardTokens but no reward apr?

**Comment by 0xviktor1** [comment]
Suggest fixes are made. Also, removed rewardTokens since there is no reward apr.

**Comment by 0xviktor1** [comment]
This failed check is not something we get when running tests locally. There are no issues calling "symbol()" on that contract when we do it.

**Comment by llamatester** [comment]
The fungify adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       130 passed, 130 total
    Snapshots:   0 total
    Time:        0.309 s
    Ran all test suites.
    
    Nb of pools: 21
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬──────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────┬────────────────────┬──────┐
    │ (index) │                         pool                          │   chain    │  project  │    symbol    │       tvlUsd       │   totalBorrowUsd   │   totalSupplyUsd   │      apyBase       │                 underlyingTokens                 │              url               │   apyBaseBorrow    │ ltv  │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────┼────────────────────┼──────┤
    │    0    │ '0x70c4f75ebaf99e24d775c91867b1a844da6ef6fd-ethereum' │ 'ethereum' │ 'fungify' │    'fETH'    │ 327587.05057283357 │ 184072.26813792705 │ 511659.31871076056 │ 2.8311572398824003 │ [ '0x0000000000000000000000000000000000000000' ] │ 'https://app.fungify.it/pools' │  8.9938983126312   │ 0.85 │
    │    1    │ '0x2b142208e665525952786c6e77cba0cb2e694b41-ethereum' │ 'ethereum' │ 'fungify' │   'fsUSDe'   │ 256489.7277067782  │ 10.533972712770513 │ 256500.26167949097 │     3.6792e-8      │ [ '0x9D39A5DE30e57443BfF2A8307A4256c8797A3497' ] │ 'https://app.fungify.it/pools' │  0.0010267023096   │ 0.85 │
    │    2    │ '0xbf1c1370cc5a96af40499502f8d5ec9403e0a18a-ethereum' │ 'ethereum' │ 'fungify' │   'fPUNKS'   │ 255137.28013504023 │ 127568.72350708999 │ 382706.0036421302  │ 2.4305586093972003 │ [ '0xb7F7F6C52F2e2fdb1963Eab30438024864c313F6' ] │ 'https://app.fungify.it/pools' │   8.333338568634   │ 0.65 │
    │    3    │ '0x5f86f598e4fa983097fe6693a1b51f047d87b9cf-ethereum' │ 'ethereum' │ 'fungify' │   'fUSDC'    │ 210088.56661374733 │ 482940.7361301937  │ 693029.3027439411  │  21.2484979412136  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'https://app.fungify.it/pools' │  34.8453710321004  │ 0.85 │
    │    4    │ '0xe0b0a19f749c6054d6412591b799b04107fe69f3-ethereum' │ 'ethereum' │ 'fungify' │ 'fHONEYCOMB' │ 151789.05240905058 │ 5031.681316320001  │ 156820.73372537055 │  0.0225199461636   │ [ '0xCB0477d1Af5b8b05795D89D59F4667b59eAE9244' ] │ 'https://app.fungify.it/pools' │ 0.8021390405111999 │ 0.45 │
    │    5    │ '0xf0bb06816f081829726bd6d3d04c823ce3e96b69-ethereum' │ 'ethereum' │ 'fungify' │   'fUSDT'    │ 133800.2812637676  │ 85734.94186924663  │ 219535.22313301422 │  6.6759535206576   │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ 'https://app.fungify.it/pools' │  19.5315912902268  │ 0.85 │
    │    6    │ '0xfb973b5cd8d18eb514aa19a35afde689f5ba04e3-ethereum' │ 'ethereum' │ 'fungify' │  'fwstETH'   │ 95332.12611398518  │ 3.6738352448996423 │ 95335.79994923009  │     3.23244e-8     │ [ '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0' ] │ 'https://app.fungify.it/pools' │  0.0009633943152   │ 0.85 │
    │    7    │ '0xa603cee4fd20c589b5aecbf07356b239cb11ee5a-ethereum' │ 'ethereum' │ 'fungify' │   'fBAYC'    │  79015.6500557283  │ 118523.59814165998 │ 197539.24819738828 │  7.8750095783616   │ [ '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D' ] │ 'https://app.fungify.it/pools' │  15.0000091223724  │ 0.65 │
    │    8    │ '0x3b37c50b237d12aefdc48d14f63dc3009ba35155-ethereum' │ 'ethereum' │ 'fungify' │   'fSAPS'    │ 58905.55506162609  │ 46633.56979627001  │ 105539.1248578961  │ 4.2708902225220005 │ [ '0x364C828eE171616a39897688A831c2499aD972ec' ] │ 'https://app.fungify.it/pools' │  11.0465123424444  │ 0.45 │
    │    9    │ '0xa2ae3d05b1448bea9199afeb733de92b32c5d207-ethereum' │ 'ethereum' │ 'fungify' │  'fPANDORA'  │ 55596.46982860717  │ 7253.058417183308  │ 62849.528245790476 │  0.2915620887096   │ [ '0x9E9FbDE7C7a83c43913BddC8779158F1368F0413' ] │ 'https://app.fungify.it/pools' │ 2.8862337737879997 │ 0.75 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴──────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────┴────────────────────┴──────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
