### PR TITLE
Track yields for Matter Defi Core farms

### PR DESCRIPTION
**Pull request by Qwiddle**
Please let me know if there are any concerns. All tests pass successfully.

Thanks, team!

### CODE REVIEW

**Comment by llamatester** [comment]
The matter-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.559 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────┬─────────┬───────────────┬───────────────────┬──────────┬────────┐
    │ (index) │                  pool                  │  chain  │    project    │      symbol       │  tvlUsd  │  apy   │
    ├─────────┼────────────────────────────────────────┼─────────┼───────────────┼───────────────────┼──────────┼────────┤
    │    0    │ 'KT1UefQz7nP8BuuDk5Dd5LWo22N1ZPB7JB5o' │ 'tezos' │ 'matter-defi' │    'uUSD/WTZ'     │ 79434.64 │ 133.44 │
    │    1    │ 'KT1KgNVokovu4dSBFZXmFXgUni5TypwMBbRS' │ 'tezos' │ 'matter-defi' │    'WTZ/USDtz'    │  33442   │ 65.65  │
    │    2    │ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' │ 'tezos' │ 'matter-defi' │      'MTTR'       │ 27734.32 │ 71.08  │
    │    3    │ 'KT1QQvdg7TGZAH85HtgNvQuoekNRegvQPk8R' │ 'tezos' │ 'matter-defi' │    'MTTR/WTZ'     │ 26860.32 │ 201.29 │
    │    4    │ 'KT1WiDfeeRVpY2ao4ps4oJUgXi1wMWtD6sFa' │ 'tezos' │ 'matter-defi' │   'WETH.e/WTZ'    │ 25741.6  │ 92.46  │
    │    5    │ 'KT1GeH12st1t3sVnvUDxR8UKm6ouXxai1vnp' │ 'tezos' │ 'matter-defi' │   'WBTC.e/WTZ'    │ 22549.2  │ 111.02 │
    │    6    │ 'KT1M234AC3kz9uQ9vse8caidhKUMrZ3S2YjN' │ 'tezos' │ 'matter-defi' │ 'BTCtz (alt)/WTZ' │ 22341.28 │ 16.32  │
    │    7    │ 'KT1FHewqgFXCjTJbYvLMhWL335ZV1qupN1c2' │ 'tezos' │ 'matter-defi' │    'WTZ/tzBTC'    │ 22059.76 │ 114.52 │
    │    8    │ 'KT1VAbfwhE9DaZWdja4hg6CF77YPc1Ne9qvK' │ 'tezos' │ 'matter-defi' │   'USDC.e/WTZ'    │ 21739.6  │ 116.93 │
    │    9    │ 'KT1NN1NgmKFTW5FUWiyxVjUt3kH9bCiqgxLW' │ 'tezos' │ 'matter-defi' │    'kUSD/WTZ'     │ 17032.88 │ 168.16 │
    └─────────┴────────────────────────────────────────┴─────────┴───────────────┴───────────────────┴──────────┴────────┘

**Comment by 0xvrotend** [comment]
Hello, thank you for your PR. Please, change chain name to `'Tezos'`

**Comment by Qwiddle** [comment]
@0xvrotend thanks for reviewing! All of the above has been done ✔️

**Comment by llamatester** [comment]
The matter-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       63 passed, 63 total
    Snapshots:   0 total
    Time:        0.355 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────┬─────────┬───────────────┬───────────────────┬──────────┬───────────┬────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                  pool                  │  chain  │    project    │      symbol       │  tvlUsd  │ apyReward │                rewardTokens                │                                     underlyingTokens                                      │
    ├─────────┼────────────────────────────────────────┼─────────┼───────────────┼───────────────────┼──────────┼───────────┼────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ 'KT1UefQz7nP8BuuDk5Dd5LWo22N1ZPB7JB5o' │ 'Tezos' │ 'matter-defi' │    'uUSD/WTZ'     │  79143   │  134.63   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW:0' ]   │
    │    1    │ 'KT1KgNVokovu4dSBFZXmFXgUni5TypwMBbRS' │ 'Tezos' │ 'matter-defi' │    'WTZ/USDtz'    │ 33316.65 │   66.16   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │ [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9:null' ] │
    │    2    │ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' │ 'Tezos' │ 'matter-defi' │      'MTTR'       │ 27877.65 │   70.83   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │                        [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ]                         │
    │    3    │ 'KT1QQvdg7TGZAH85HtgNvQuoekNRegvQPk8R' │ 'Tezos' │ 'matter-defi' │    'MTTR/WTZ'     │ 27052.55 │  199.73   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY:0', 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0' ]   │
    │    4    │ 'KT1WiDfeeRVpY2ao4ps4oJUgXi1wMWtD6sFa' │ 'Tezos' │ 'matter-defi' │   'WETH.e/WTZ'    │ 26042.45 │   91.31   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY:0' ]   │
    │    5    │ 'KT1GeH12st1t3sVnvUDxR8UKm6ouXxai1vnp' │ 'Tezos' │ 'matter-defi' │   'WBTC.e/WTZ'    │ 22610.7  │  110.97   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY:1' ]   │
    │    6    │ 'KT1M234AC3kz9uQ9vse8caidhKUMrZ3S2YjN' │ 'Tezos' │ 'matter-defi' │ 'BTCtz (alt)/WTZ' │ 22462.7  │   16.27   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1T87QbpXEVgkwsNPzz8iRoah3SS3D1MDmh:0', 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0' ]   │
    │    7    │ 'KT1FHewqgFXCjTJbYvLMhWL335ZV1qupN1c2' │ 'Tezos' │ 'matter-defi' │    'WTZ/tzBTC'    │ 22179.65 │  114.02   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │ [ 'KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn:null', 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0' ] │
    │    8    │ 'KT1VAbfwhE9DaZWdja4hg6CF77YPc1Ne9qvK' │ 'Tezos' │ 'matter-defi' │   'USDC.e/WTZ'    │ 21781.9  │  116.99   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │  [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY:2' ]   │
    │    9    │ 'KT1NN1NgmKFTW5FUWiyxVjUt3kH9bCiqgxLW' │ 'Tezos' │ 'matter-defi' │    'kUSD/WTZ'     │ 16973.75 │  169.69   │ [ 'KT1K4jn23GonEmZot3pMGth7unnzZ6EaMVjY' ] │ [ 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn:0', 'KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV:null' ] │
    └─────────┴────────────────────────────────────────┴─────────┴───────────────┴───────────────────┴──────────┴───────────┴────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by 0xvrotend** [comment]
I don't know much about tezos, but are these the correct token address formats `KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn:null` or `KT1PnUZCp3u2KzWr93pn4D7HAJnm3rVrgn:0`?

**Comment by Qwiddle** [comment]
https://tzkt.io/KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY/tokens/1/
https://tzkt.io/KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY/tokens/0/

Examples here. We can see they are the same contract, though the specific token is identified with that ID. I can reformat the delimiter or remove if it's preferred.

**Comment by 0xvrotend** [comment]
Oh, okay. Thanks for explanation 👍

**Pull request merged**
