### PR TITLE
Added yield server for affine-defi

### PR DESCRIPTION
**Pull request by pchy10**

### CODE REVIEW

**Comment by llamatester** [comment]
The affine-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.443 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬──────────────────────┬───────────────────┬─────────────────────┬───────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │        symbol        │      tvlUsd       │         apy         │                            url                            │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼──────────────────────┼───────────────────┼─────────────────────┼───────────────────────────────────────────────────────────┤
    │    0    │ '0x829363736a5A9080e05549Db6d1271f070a7e224-polygon'  │ 'polygon'  │ 'affine-defi' │      'AlpSave'       │  2073921.599423   │ 1.5077615188819449  │      'https://app.affinedefi.com/basket?id=AlpSave'       │
    │    1    │ '0x78Bb94Feab383ccEd39766a7d6CF31dED177Ad0c-ethereum' │ 'ethereum' │ 'affine-defi' │     'EthAlpSave'     │   11085.805546    │ -1.7064365914644997 │     'https://app.affinedefi.com/basket?id=EthAlpSave'     │
    │    2    │ '0x61A18EE9d6d51F838c7e50dFD750629Fd141E944-ethereum' │ 'ethereum' │ 'affine-defi' │ 'EthSushiLpUsdcWeth' │   10100.105302    │          0          │ 'https://app.affinedefi.com/basket?id=EthSushiLpUsdcWeth' │
    │    3    │ '0x72D51B2233c5feA8a702FDd0E51B0adE95638f2c-ethereum' │ 'ethereum' │ 'affine-defi' │    'EthWethEarn'     │ 8932.055259727085 │ 1.3371241482675433  │    'https://app.affinedefi.com/basket?id=EthWethEarn'     │
    │    4    │ '0x1F9b1057cd93fb2d07d18810903B791b56acc2E1-polygon'  │ 'polygon'  │ 'affine-defi' │    'BtcEthVault'     │   5126.88457102   │          0          │    'https://app.affinedefi.com/basket?id=BtcEthVault'     │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴──────────────────────┴───────────────────┴─────────────────────┴───────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, ty for adding. 
- we no longer accept api adapters, so would need to call data from on chain or subgraph
- is the negative apy value correct?
- symbol should be what a user needs to deposit. if u want u can keep the pool name but needs to go into `poolMeta`

**Comment by maruf0011** [comment]
Thanks, 
Just to clarify, Do we need onchain data for TVL, Price, APY? or all the metadata should come from onchain data including the symbols, url, etc....

**Comment by slasher125** [comment]
the most important pieces are apy + tvl, meta data doesn't necessarily have to be read from on chain but if possible i'd go with that

**Comment by maruf0011** [comment]
Trying to get the price from 1d old block to calculate the APY. But ABI call always getting the latest price from the contract even block number is specified. 

Here is the snippet used, Not sure whats wrong. 

````
const price = await api.call({
    target: "0x829363736a5A9080e05549Db6d1271f070a7e224",
    abi: "function detailedPrice() returns (uint256, uint256)",
    block: 42600333,
  });
````

**Comment by slasher125** [comment]
just tried and works fine for me. don't forget to set `chain: 'polygon'` in the call object

**Comment by llamatester** [comment]
The affine-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.55 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬──────────────────────┬───────────────────┬────────────────────┬───────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │        symbol        │      tvlUsd       │        apy         │                            url                            │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼──────────────────────┼───────────────────┼────────────────────┼───────────────────────────────────────────────────────────┤
    │    0    │ '0x829363736a5A9080e05549Db6d1271f070a7e224-polygon'  │ 'polygon'  │ 'affine-defi' │      'AlpSave'       │  2073994.798795   │ 1.7204435584158295 │      'https://app.affinedefi.com/basket?id=AlpSave'       │
    │    1    │ '0x78Bb94Feab383ccEd39766a7d6CF31dED177Ad0c-ethereum' │ 'ethereum' │ 'affine-defi' │     'EthAlpSave'     │   11089.301749    │ 17.928578020761798 │     'https://app.affinedefi.com/basket?id=EthAlpSave'     │
    │    2    │ '0x61A18EE9d6d51F838c7e50dFD750629Fd141E944-ethereum' │ 'ethereum' │ 'affine-defi' │ 'EthSushiLpUsdcWeth' │   10102.051109    │         0          │ 'https://app.affinedefi.com/basket?id=EthSushiLpUsdcWeth' │
    │    3    │ '0x72D51B2233c5feA8a702FDd0E51B0adE95638f2c-ethereum' │ 'ethereum' │ 'affine-defi' │    'EthWethEarn'     │ 9194.940205847628 │ 1.255759028582526  │    'https://app.affinedefi.com/basket?id=EthWethEarn'     │
    │    4    │ '0x1F9b1057cd93fb2d07d18810903B791b56acc2E1-polygon'  │ 'polygon'  │ 'affine-defi' │    'BtcEthVault'     │   5160.72338602   │         0          │    'https://app.affinedefi.com/basket?id=BtcEthVault'     │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴──────────────────────┴───────────────────┴────────────────────┴───────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
pls update the symbol as mentioned above

**Comment by llamatester** [comment]
The affine-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.357 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬────────┬────────────────────┬───────────────────────┬───────────────────────┬──────────────────────────┬──────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │ symbol │       tvlUsd       │          apy          │        apyBase        │        apyBase7d         │       poolMeta       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼────────┼────────────────────┼───────────────────────┼───────────────────────┼──────────────────────────┼──────────────────────┤
    │    0    │ '0x78Bb94Feab383ccEd39766a7d6CF31dED177Ad0c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │ 19910400.985758238 │           0           │           0           │            0             │     'EthAlpSave'     │
    │    1    │ '0x61A18EE9d6d51F838c7e50dFD750629Fd141E944-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │ 18132491.18756496  │           0           │           0           │ -0.000001997411114285086 │ 'EthSushiLpUsdcWeth' │
    │    2    │ '0x829363736a5A9080e05549Db6d1271f070a7e224-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │   2074069.550006   │ -9.825284363884634e-7 │ -9.825284363884634e-7 │  -9.825284363884634e-7   │      'AlpSave'       │
    │    3    │ '0x72D51B2233c5feA8a702FDd0E51B0adE95638f2c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'ETH'  │ 9071.621891085873  │           0           │           0           │  -8.282759256239558e-7   │    'EthWethEarn'     │
    │    4    │ '0x1F9b1057cd93fb2d07d18810903B791b56acc2E1-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │   5034.47535949    │           0           │           0           │  -0.000587868701118488   │    'BtcEthVault'     │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴────────┴────────────────────┴───────────────────────┴───────────────────────┴──────────────────────────┴──────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The affine-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.399 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬────────┬───────────────────┬───────────────────┬───────────────────┬────────────────────┬──────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │ symbol │      tvlUsd       │        apy        │      apyBase      │     apyBase7d      │       poolMeta       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼────────┼───────────────────┼───────────────────┼───────────────────┼────────────────────┼──────────────────────┤
    │    0    │ '0x78Bb94Feab383ccEd39766a7d6CF31dED177Ad0c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │ 20076032.55319905 │ 7.407449632954921 │ 7.407449632954921 │ 3.918279901717781  │     'EthAlpSave'     │
    │    1    │ '0x61A18EE9d6d51F838c7e50dFD750629Fd141E944-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │ 18284112.64612495 │ 5.861929471226213 │ 5.861929471226213 │ 2.8167509832465507 │ 'EthSushiLpUsdcWeth' │
    │    2    │ '0x829363736a5A9080e05549Db6d1271f070a7e224-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │   2074127.31044   │ 3.929744552382708 │ 3.929744552382708 │ 2.5774460005924302 │      'AlpSave'       │
    │    3    │ '0x72D51B2233c5feA8a702FDd0E51B0adE95638f2c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'ETH'  │ 9147.204980269273 │ 2.138865730091477 │ 2.138865730091477 │ 2.047344419892992  │    'EthWethEarn'     │
    │    4    │ '0x684D1dbd30c67Fe7fF6D502A04e0E7076b4b9D46-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │        60         │         0         │         0         │         0          │    'PolygonDegen'    │
    │    5    │ '0x9d39ba71f30f44FB72e7b45151C27079C2cd8ECa-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │         0         │         0         │         0         │         0          │       'Degen'        │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴────────┴───────────────────┴───────────────────┴───────────────────┴────────────────────┴──────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by pchy10** [comment]
@slasher125 please take a look now.

**Comment by slasher125** [comment]
@pchy10 
- can remove `apy` given u have provided `apyBase`
- the usdc pools on ethereum seem to have wrong tvl? i can't find those on your ui

**Comment by llamatester** [comment]
The affine-defi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.356 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬────────┬──────────────────┬────────────────────┬────────────────────┬──────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │ symbol │      tvlUsd      │      apyBase       │     apyBase7d      │       poolMeta       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼────────┼──────────────────┼────────────────────┼────────────────────┼──────────────────────┤
    │    0    │ '0x829363736a5A9080e05549Db6d1271f070a7e224-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │  2074277.720009  │ 4.276712665908344  │ 2.4946379601412185 │      'AlpSave'       │
    │    1    │ '0x78Bb94Feab383ccEd39766a7d6CF31dED177Ad0c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │   11094.045559   │ 0.5572331474197334 │ 3.789868221828379  │     'EthAlpSave'     │
    │    2    │ '0x61A18EE9d6d51F838c7e50dFD750629Fd141E944-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │   10104.049536   │ 4.697166506046679  │ 2.5385087226772147 │ 'EthSushiLpUsdcWeth' │
    │    3    │ '0x72D51B2233c5feA8a702FDd0E51B0adE95638f2c-ethereum' │ 'ethereum' │ 'affine-defi' │ 'ETH'  │ 9196.21729961309 │ 2.1381125364495768 │ 2.0686195676263206 │    'EthWethEarn'     │
    │    4    │ '0x9d39ba71f30f44FB72e7b45151C27079C2cd8ECa-ethereum' │ 'ethereum' │ 'affine-defi' │ 'USDC' │       5000       │         0          │         0          │       'Degen'        │
    │    5    │ '0x684D1dbd30c67Fe7fF6D502A04e0E7076b4b9D46-polygon'  │ 'polygon'  │ 'affine-defi' │ 'USDC' │        60        │         0          │         0          │    'PolygonDegen'    │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴────────┴──────────────────┴────────────────────┴────────────────────┴──────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by pchy10** [comment]
@slasher125 Thanks, you were right. There was a typo in the code. Already fixed it in the last commit.

**Pull request merged**
