### PR TITLE
add teahouse-v3 adapter

### PR DESCRIPTION
**Pull request by daiwanwei**

### CODE REVIEW

**Comment by llamatester** [comment]
The teahouse-v3 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.387 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┬───────────────┬────────────────────┬─────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┬──────────┬───────────────┬─────────────────┬────────────────┬────────────────┬─────┐
    │ (index) │                     pool                     │   chain    │        symbol         │                                         url                                          │    project    │       tvlUsd       │ apyBase │ apyReward │                                        underlyingTokens                                        │ rewardTokens │ poolMeta │ apyBaseBorrow │ apyRewardBorrow │ totalSupplyUsd │ totalBorrowUsd │ ltv │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┼───────────────┼────────────────────┼─────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────┼──────────┼───────────────┼─────────────────┼────────────────┼────────────────┼─────┤
    │    0    │ '0x99c2901d2883F8D295A989544f118e31eC21823e' │ 'arbitrum' │ 'wstETH-WETH (0.01%)' │ 'https://vault.teahouse.finance/arbitrum/0x99c2901d2883F8D295A989544f118e31eC21823e' │ 'teahouse-v3' │ 92935.01442600564  │ 2.9445  │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.01%'  │       0       │        0        │       0        │       0        │  0  │
    │    1    │ '0xF31900132dFf544Cfe536e76C38a357FF08183D9' │ 'optimism' │  'USDC-sUSD (0.01%)'  │ 'https://vault.teahouse.finance/optimism/0xF31900132dFf544Cfe536e76C38a357FF08183D9' │ 'teahouse-v3' │ 27074.80804440134  │ 10.3198 │     0     │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607', '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' ] │      []      │ '0.01%'  │       0       │        0        │       0        │       0        │  0  │
    │    2    │ '0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876' │ 'arbitrum' │ 'USDC-USDC.e (0.01%)' │ 'https://vault.teahouse.finance/arbitrum/0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876' │ 'teahouse-v3' │ 19261.744167426117 │ 5.6935  │     0     │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.01%'  │       0       │        0        │       0        │       0        │  0  │
    │    3    │ '0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC' │ 'arbitrum' │ 'wstETH-WETH (0.30%)' │ 'https://vault.teahouse.finance/arbitrum/0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC' │ 'teahouse-v3' │ 4025.4739984942566 │ 0.9361  │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.30%'  │       0       │        0        │       0        │       0        │  0  │
    │    4    │ '0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05' │ 'arbitrum' │ 'USDs-USDC.e (0.05%)' │ 'https://vault.teahouse.finance/arbitrum/0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05' │ 'teahouse-v3' │ 3147.314372525416  │ 3.3996  │     0     │ [ '0xd74f5255d557944cf7dd0e45ff521520002d5748', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.05%'  │       0       │        0        │       0        │       0        │  0  │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┴───────────────┴────────────────────┴─────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┴──────────┴───────────────┴─────────────────┴────────────────┴────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
henloo,
- pls refactor and use on chain calls instead of api
- the fee tier can be removed from the symbol
- the borrow fields are only used for lending projects, u can remove them

**Comment by daiwanwei** [comment]
Ok, I will fix them.

**Comment by daiwanwei** [comment]
Hi, @slasher125
I have two duplicate addresses but different chains.
How can I pass the test? 
thanks.
chain: polygon, address: 0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05
chain: arbitrum, address: 0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05

**Comment by slasher125** [comment]
gm, can just use the chain as suffix to the pool address, so `0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05-polygon`

**Comment by daiwanwei** [comment]
gm!
I see, thanks!

**Comment by llamatester** [comment]
The teahouse-permissionless adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.321 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬──────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────┬────────────────────┬─────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┬──────────┬────────────────┬─────┐
    │ (index) │                         pool                          │   chain    │    symbol     │                                         url                                          │          project          │       tvlUsd       │       apyBase       │ apyReward │                                        underlyingTokens                                        │ rewardTokens │ poolMeta │ totalSupplyUsd │ ltv │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼──────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────┼────────────────────┼─────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────┼──────────┼────────────────┼─────┤
    │    0    │ '0x99c2901d2883F8D295A989544f118e31eC21823e-arbitrum' │ 'arbitrum' │ 'wstETH-WETH' │ 'https://vault.teahouse.finance/arbitrum/0x99c2901d2883F8D295A989544f118e31eC21823e' │ 'teahouse-permissionless' │ 92393.46991833393  │  3.93071988768696   │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.01%'  │       0        │  0  │
    │    1    │ '0xF31900132dFf544Cfe536e76C38a357FF08183D9-optimism' │ 'optimism' │  'USDC-sUSD'  │ 'https://vault.teahouse.finance/optimism/0xF31900132dFf544Cfe536e76C38a357FF08183D9' │ 'teahouse-permissionless' │ 27432.82027846475  │  7.256866464208224  │     0     │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607', '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' ] │      []      │ '0.01%'  │       0        │  0  │
    │    2    │ '0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876-arbitrum' │ 'arbitrum' │ 'USDC-USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876' │ 'teahouse-permissionless' │ 13841.383510112622 │  6.287940929038176  │     0     │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.01%'  │       0        │  0  │
    │    3    │ '0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05-polygon'  │ 'polygon'  │ 'USDC-agEUR'  │ 'https://vault.teahouse.finance/polygon/0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05'  │ 'teahouse-permissionless' │ 7180.608930060597  │ -12.889813971730607 │     0     │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174', '0xE0B52e49357Fd4DAf2c15e02058DCE6BC0057db4' ] │      []      │ '0.01%'  │       0        │  0  │
    │    4    │ '0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC-arbitrum' │ 'arbitrum' │ 'wstETH-WETH' │ 'https://vault.teahouse.finance/arbitrum/0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC' │ 'teahouse-permissionless' │ 3321.3530073276283 │ -3.6108607127294876 │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.30%'  │       0        │  0  │
    │    5    │ '0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05-arbitrum' │ 'arbitrum' │ 'USDs-USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05' │ 'teahouse-permissionless' │ 3155.327523632411  │   6.310471284468    │     0     │ [ '0xd74f5255d557944cf7dd0e45ff521520002d5748', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.05%'  │       0        │  0  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴──────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────┴────────────────────┴─────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┴──────────┴────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
a few smol things:
- any reason u have added totalSupplyUsd and ltv? we usually use these in the context of lending pools, better to remove if not required
- i see u are computing apr based on a 7day interval. u can keep this but set this value to `apyBase7d` and use a 1 day window for apyBase

**Comment by daiwanwei** [comment]
OK, I forgot to remove the fields.
Thank you for your reminding!

**Comment by llamatester** [comment]
The teahouse-permissionless adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.408 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬──────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────┬────────────────────┬─────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┬──────────┐
    │ (index) │                         pool                          │   chain    │    symbol     │                                         url                                          │          project          │       tvlUsd       │       apyBase       │ apyReward │                                        underlyingTokens                                        │ rewardTokens │ poolMeta │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼──────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────┼────────────────────┼─────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────┼──────────┤
    │    0    │ '0x99c2901d2883F8D295A989544f118e31eC21823e-arbitrum' │ 'arbitrum' │ 'wstETH-WETH' │ 'https://vault.teahouse.finance/arbitrum/0x99c2901d2883F8D295A989544f118e31eC21823e' │ 'teahouse-permissionless' │ 92496.40144139764  │ 23.398976524945102  │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.01%'  │
    │    1    │ '0xF31900132dFf544Cfe536e76C38a357FF08183D9-optimism' │ 'optimism' │  'USDC-sUSD'  │ 'https://vault.teahouse.finance/optimism/0xF31900132dFf544Cfe536e76C38a357FF08183D9' │ 'teahouse-permissionless' │    27441.51494     │  7.259336561017441  │     0     │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607', '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' ] │      []      │ '0.01%'  │
    │    2    │ '0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876-arbitrum' │ 'arbitrum' │ 'USDC-USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0xB9Fe0EC178163a66f2BAf8eD97E057964cCaE876' │ 'teahouse-permissionless' │    13845.785065    │  7.656127127459568  │     0     │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.01%'  │
    │    3    │ '0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05-polygon'  │ 'polygon'  │ 'USDC-agEUR'  │ 'https://vault.teahouse.finance/polygon/0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05'  │ 'teahouse-permissionless' │    7186.894526     │  25.98877777731682  │     0     │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174', '0xE0B52e49357Fd4DAf2c15e02058DCE6BC0057db4' ] │      []      │ '0.01%'  │
    │    4    │ '0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC-arbitrum' │ 'arbitrum' │ 'wstETH-WETH' │ 'https://vault.teahouse.finance/arbitrum/0xB38e48B8Bc33CD65551BdaC8d954801D56625eeC' │ 'teahouse-permissionless' │ 3323.6076335429525 │          0          │     0     │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │      []      │ '0.30%'  │
    │    5    │ '0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05-arbitrum' │ 'arbitrum' │ 'USDs-USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0x1546B2aE60a2aDe3F8F1a9276c198e8f52212c05' │ 'teahouse-permissionless' │ 3181.322302985303  │ -16.296053452087392 │     0     │ [ '0xd74f5255d557944cf7dd0e45ff521520002d5748', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │      []      │ '0.05%'  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴──────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────┴────────────────────┴─────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
