### PR TITLE
Add symbiosis-finance protocol

### PR DESCRIPTION
**Pull request by allush**
Updated defillama-sdk version to support BOBA BNB chain

### CODE REVIEW

**Comment by slasher125** [comment]
tests are failing cause there is a second package.lock in the project root. could u pls update that one too?

Also, I'll need to double check if some older adapters won't break from the upgrade (last time i tried to bump the version i ran into some issues and had to revert)

**Comment by llamatester** [comment]
The symbiosis-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       52 passed, 52 total
    Snapshots:   0 total
    Time:        0.326 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────────────────────────┬─────────────┬─────────────────────┬──────────┬────────────────────┬─────────────┬──────────────────────────────────────────────────┐
    │ (index) │                                   pool                                   │    chain    │       project       │  symbol  │       tvlUsd       │   apyBase   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────────────────────────────────┼─────────────┼─────────────────────┼──────────┼────────────────────┼─────────────┼──────────────────────────────────────────────────┤
    │    0    │ 'symbiosis-finance-0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664-avalanche' │ 'Avalanche' │ 'symbiosis-finance' │ 'USDC.e' │   133797.124814    │ 7.20031257  │ [ '0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664' ] │
    │    1    │   'symbiosis-finance-0x66a2a913e447d6b4bf33efbec43aaef87890fbbc-boba'    │   'Boba'    │ 'symbiosis-finance' │  'USDC'  │    128563.44305    │ 0.99912395  │ [ '0x66a2A913e447d6b4BF33EFbec43aAeF87890FBbc' ] │
    │    2    │  'symbiosis-finance-0x2791bca1f2de4661ed88a30c99a7a9449aa84174-polygon'  │  'Polygon'  │ 'symbiosis-finance' │  'USDC'  │   111374.234945    │ 8.64994601  │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174' ] │
    │    3    │    'symbiosis-finance-0xe9e7cea3dedca5984780bafc599bd69add087d56-bsc'    │  'Binance'  │ 'symbiosis-finance' │  'BUSD'  │ 94798.42408322229  │ 10.17132333 │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    4    │   'symbiosis-finance-0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b-telos'   │   'Telos'   │ 'symbiosis-finance' │  'USDC'  │    94623.514336    │ 0.95024552  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │
    │    5    │ 'symbiosis-finance-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48-ethereum'  │ 'Ethereum'  │ 'symbiosis-finance' │  'USDC'  │    88414.750688    │ 10.88594931 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │
    │    6    │ 'symbiosis-finance-0x9f98f9f312d23d078061962837042b8918e6aff2-boba_bnb'  │ 'Boba_Bnb'  │ 'symbiosis-finance' │  'USDC'  │ 13597.320396845103 │ 4.72338711  │ [ '0x9F98f9F312D23d078061962837042b8918e6aff2' ] │
    │    7    │ 'symbiosis-finance-0x126969743a6d300bab08f303f104f0f7dbafbe20-boba_avax' │ 'Boba_Avax' │ 'symbiosis-finance' │ 'USDC.e' │    9743.619569     │ 6.59153485  │ [ '0x126969743a6d300bab08F303f104f0f7DBAfbe20' ] │
    └─────────┴──────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────────────┴──────────┴────────────────────┴─────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by allush** [comment]
@slasher125 Hi, I fixed the problems you mentioned. :)

**Comment by slasher125** [comment]
ty. i haven't figured out yet what requires fixing when upgrading to sdk `3.0.9`

can u pls revert that particular change and use the "old" abi structure?
otherwise I can't merge this PR until I've upgraded older adapters which might take a while...

**Comment by allush** [comment]
> ty. i haven't figured out yet what requires fixing when upgrading to sdk `3.0.9`
> 
> can u pls revert that particular change and use the "old" abi structure? otherwise I can't merge this PR until I've upgraded older adapters which might take a while...

I am sorry, what is old ABI stricture?
If you tell about old version of SDK than I cannot use it because it does not have two chains: Boba BNB and Boba Avax

**Comment by llamatester** [comment]
The symbiosis-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       52 passed, 52 total
    Snapshots:   0 total
    Time:        0.476 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────────────────────────┬─────────────┬─────────────────────┬──────────┬────────────────────┬─────────────┬──────────────────────────────────────────────────┐
    │ (index) │                                   pool                                   │    chain    │       project       │  symbol  │       tvlUsd       │   apyBase   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────────────────────────────────┼─────────────┼─────────────────────┼──────────┼────────────────────┼─────────────┼──────────────────────────────────────────────────┤
    │    0    │ 'symbiosis-finance-0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664-avalanche' │ 'Avalanche' │ 'symbiosis-finance' │ 'USDC.e' │   133797.124814    │ 7.15348824  │ [ '0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664' ] │
    │    1    │   'symbiosis-finance-0x66a2a913e447d6b4bf33efbec43aaef87890fbbc-boba'    │   'Boba'    │ 'symbiosis-finance' │  'USDC'  │    128563.44305    │ 0.99262655  │ [ '0x66a2A913e447d6b4BF33EFbec43aAeF87890FBbc' ] │
    │    2    │  'symbiosis-finance-0x2791bca1f2de4661ed88a30c99a7a9449aa84174-polygon'  │  'Polygon'  │ 'symbiosis-finance' │  'USDC'  │   111374.234945    │ 8.59369458  │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174' ] │
    │    3    │   'symbiosis-finance-0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b-telos'   │   'Telos'   │ 'symbiosis-finance' │  'USDC'  │    94623.514336    │ 0.94406598  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │
    │    4    │    'symbiosis-finance-0xe9e7cea3dedca5984780bafc599bd69add087d56-bsc'    │  'Binance'  │ 'symbiosis-finance' │  'BUSD'  │  94143.9229574944  │ 10.16652089 │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    5    │ 'symbiosis-finance-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48-ethereum'  │ 'Ethereum'  │ 'symbiosis-finance' │  'USDC'  │    89068.800072    │ 10.74580727 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │
    │    6    │ 'symbiosis-finance-0x9f98f9f312d23d078061962837042b8918e6aff2-boba_bnb'  │ 'Boba_Bnb'  │ 'symbiosis-finance' │  'USDC'  │ 13597.320396845103 │ 4.69267047  │ [ '0x9F98f9F312D23d078061962837042b8918e6aff2' ] │
    │    7    │ 'symbiosis-finance-0x126969743a6d300bab08f303f104f0f7dbafbe20-boba_avax' │ 'Boba_Avax' │ 'symbiosis-finance' │ 'USDC.e' │    9743.619569     │ 6.54866947  │ [ '0x126969743a6d300bab08F303f104f0f7DBAfbe20' ] │
    └─────────┴──────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────────────┴──────────┴────────────────────┴─────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by allush** [comment]
@slasher125 may be this solution will be ok. I have added new sdk as a separate package. It should not brokes any dependencies and will allow to work symbiosis adapter.

**Pull request merged**
