### PR TITLE
[iziswap] add adapter for izumi liquidity pools

### PR DESCRIPTION
**Pull request by LpcAries**
hi, we adds the adapter to list our liquidity pools for yield

### CODE REVIEW

**Comment by slasher125** [comment]
gm sir. we are moving away from centralised api calls (see readme data sources). pls refactor to on chain calls or subgraph calls if possible

**Comment by llamatester** [comment]
The iziswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.339 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────┬──────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │  project  │    symbol    │       tvlUsd       │     apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────┼──────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x4b118acdec0dab9a04481f97750f0afd8b05d7a8' │ 'Binance' │ 'iziswap' │ 'WBNB-aBNBc' │ 281610.8024608233  │ 44.19010900580318  │ [ '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747', '0xf307910A4c7bbc79691fD374889b36d8531B08e3' ] │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xE85aFCcDaFBE7F2B096f268e31ccE3da8dA2990A' ] │
    │    1    │ '0xa39dd789d77a8d8ae17ddf1b3a8f569a31d6dd41' │ 'Binance' │ 'iziswap' │  'USDT-BNB'  │ 187765.95681789226 │ 48.418216451666375 │                        [ '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747' ]                        │ [ '0x55d398326f99059fF775485246999027B3197955', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    │    2    │ '0x29038f8adfa0325ae8df92b3a1491e2eed281d23' │ 'Binance' │ 'iziswap' │  'iUSD-iZi'  │ 142571.44272548813 │ 30.943386536581276 │                        [ '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747' ]                        │ [ '0x0A3BB08b3a15A19b4De82F8AcFc862606FB69A2D', '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747' ] │
    │    3    │ '0x277ae32cede584784425fcb50710611c13c31521' │ 'Binance' │ 'iziswap' │ 'FEVR-BUSD'  │ 73865.60643434853  │ 568.5924012870407  │ [ '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747', '0x82030CDBD9e4B7c5bb0b811A61DA6360D69449cc' ] │ [ '0x82030CDBD9e4B7c5bb0b811A61DA6360D69449cc', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    4    │ '0xc9d1dca243eaceb62b1e6e354015e53c10f2c59b' │ 'Binance' │ 'iziswap' │  'WBNB-GRI'  │ 2278.6608685040123 │ 0.4335758715211103 │ [ '0x60D01EC2D5E98Ac51C8B4cF84DfCCE98D527c747', '0xD767713e787Cb351e4daFb777DD93d54f5381D29' ] │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xD767713e787Cb351e4daFb777DD93d54f5381D29' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────┴──────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by LpcAries** [comment]
We are trying to migrate data to the chain, but it takes time. Can you use this version of code just for now pls?

**Comment by LpcAries** [comment]
thx

**Pull request merged**
