### PR TITLE
add debt ceiling and totalBorrowUsd

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The makerdao adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       184 passed, 184 total
    Snapshots:   0 total
    Time:        0.577 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────────────────────┬────────────┬──────────┬────────────┬────────────┬─────┬────────────────────┬────────────────────┬────────────────┬────────────────────┬────────────────────┐
    │ (index) │                                 pool                                 │  project   │  symbol  │   chain    │  poolMeta  │ apy │       tvlUsd       │   apyBaseBorrow    │ totalSupplyUsd │   totalBorrowUsd   │   debtCeilingUsd   │
    ├─────────┼──────────────────────────────────────────────────────────────────────┼────────────┼──────────┼────────────┼────────────┼─────┼────────────────────┼────────────────────┼────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x4554482d43000000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-C'   │  0  │ 1154339657.0028083 │ 0.500000000006509  │       0        │ 313553427.27418107 │ 411646698.9791721  │
    │    1    │ '0x4554482d41000000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-A'   │  0  │ 881488714.4086728  │ 1.500000000015499  │       0        │ 196597640.36092234 │ 350558569.7324488  │
    │    2    │ '0x574254432d410000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-A'  │  0  │ 694657729.2869717  │ 1.9999999999966873 │       0        │  51046990.8898197  │ 126919542.64375526 │
    │    3    │ '0x5753544554482d42000000000000000000000000000000000000000000000000' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-B' │  0  │ 425650113.8130633  │         0          │       0        │ 120323824.96121524 │ 149543457.82150096 │
    │    4    │ '0x555344432d410000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'USDC'  │ 'ethereum' │  'USDC-A'  │  0  │ 227565552.92485264 │         0          │       0        │ 228250192.38026515 │         0          │
    │    5    │ '0x5753544554482d41000000000000000000000000000000000000000000000000' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-A' │  0  │ 221894021.92193505 │ 1.500000000015499  │       0        │ 52414897.20308339  │ 87260831.14663719  │
    │    6    │ '0x574254432d430000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-C'  │  0  │ 159560812.5936257  │ 0.7499999999908489 │       0        │ 55794569.56800095  │ 164462953.02967158 │
    │    7    │ '0x4554482d42000000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-B'   │  0  │ 147182790.58180055 │ 3.000000000006898  │       0        │ 47700393.41412063  │ 71921920.81576702  │
    │    8    │ '0x4d415449432d4100000000000000000000000000000000000000000000000000' │ 'makerdao' │ 'MATIC'  │ 'ethereum' │ 'MATIC-A'  │  0  │ 119801813.97227475 │ 3.000000000006898  │       0        │  14270191.402011   │ 18911403.30048648  │
    │    9    │ '0x4d414e412d410000000000000000000000000000000000000000000000000000' │ 'makerdao' │  'MANA'  │ 'ethereum' │  'MANA-A'  │  0  │  46223554.3477991  │ 4.499999999989465  │       0        │  15175400.504782   │ 16167149.937257662 │
    └─────────┴──────────────────────────────────────────────────────────────────────┴────────────┴──────────┴────────────┴────────────┴─────┴────────────────────┴────────────────────┴────────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
any reason u changed the pool values? pls lets use the one we currently have in master, otherwise I'd need to manually run update comands on the db for maker

**Comment by dtmkeng** [comment]
> any reason u changed the pool values? pls lets use the one we currently have in master, otherwise I'd need to manually run update comands on the db for maker

oh sorry 1 sec

**Comment by llamatester** [comment]
The makerdao adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       184 passed, 184 total
    Snapshots:   0 total
    Time:        0.44 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────────┬────────────┬─────┬────────────────────┬────────────────────┬────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │  project   │  symbol  │   chain    │  poolMeta  │ apy │       tvlUsd       │   apyBaseBorrow    │ totalSupplyUsd │   totalBorrowUsd   │   debtCeilingUsd   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────────┼────────────┼─────┼────────────────────┼────────────────────┼────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xF04a5cC80B1E94C69B48f5ee68a08CD2F09A7c3E' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-C'   │  0  │ 1150483194.522668  │ 0.500000000006509  │       0        │ 313553427.27418107 │ 411646698.9791721  │
    │    1    │ '0x2F0b23f53734252Bda2277357e97e1517d6B042A' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-A'   │  0  │ 878543802.8887736  │ 1.500000000015499  │       0        │ 196597640.36092234 │ 350558569.7324488  │
    │    2    │ '0xBF72Da2Bd84c5170618Fbe5914B0ECA9638d5eb5' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-A'  │  0  │ 694177187.3258086  │ 1.9999999999966873 │       0        │  51046990.8898197  │ 126919542.64375526 │
    │    3    │ '0x248cCBf4864221fC0E840F29BB042ad5bFC89B5c' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-B' │  0  │ 425375078.99359477 │         0          │       0        │ 120323824.96121524 │ 149543457.82150096 │
    │    4    │ '0xA191e578a6736167326d05c119CE0c90849E84B7' │ 'makerdao' │  'USDC'  │ 'ethereum' │  'USDC-A'  │  0  │ 227565552.92485264 │         0          │       0        │ 228250192.38026515 │         0          │
    │    5    │ '0x10CD5fbe1b404B7E19Ef964B63939907bdaf42E2' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-A' │  0  │ 221750644.5791834  │ 1.500000000015499  │       0        │ 52414897.20308339  │ 87260831.14663719  │
    │    6    │ '0x7f62f9592b823331E012D3c5DdF2A7714CfB9de2' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-C'  │  0  │ 159450433.53560063 │ 0.7499999999908489 │       0        │ 55794569.56800095  │ 164462953.02967158 │
    │    7    │ '0x08638eF1A205bE6762A8b935F5da9b700Cf7322c' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-B'   │  0  │ 146691076.63421357 │ 3.000000000006898  │       0        │ 47700393.41412063  │ 71921920.81576702  │
    │    8    │ '0x885f16e177d45fC9e7C87e1DA9fd47A9cfcE8E13' │ 'makerdao' │ 'MATIC'  │ 'ethereum' │ 'MATIC-A'  │  0  │ 119426180.5899391  │ 3.000000000006898  │       0        │  14270191.402011   │ 18911403.30048648  │
    │    9    │ '0xA6EA3b9C04b8a38Ff5e224E7c3D6937ca44C0ef9' │ 'makerdao' │  'MANA'  │ 'ethereum' │  'MANA-A'  │  0  │ 46171947.907595664 │ 4.499999999989465  │       0        │  15175400.504782   │ 16167149.937257662 │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────────┴────────────┴─────┴────────────────────┴────────────────────┴────────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
one final thing that i'm just seeing now: totalSupplyUsd should be the same as tvlUsd? i think thats what u have done for the other cdp's and which makes most sense

**Comment by llamatester** [comment]
The makerdao adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       184 passed, 184 total
    Snapshots:   0 total
    Time:        0.643 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────────┬────────────┬─────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │  project   │  symbol  │   chain    │  poolMeta  │ apy │       tvlUsd       │   apyBaseBorrow    │   totalSupplyUsd   │   totalBorrowUsd   │   debtCeilingUsd   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────────┼────────────┼─────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xF04a5cC80B1E94C69B48f5ee68a08CD2F09A7c3E' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-C'   │  0  │ 1147010078.2135158 │ 0.500000000006509  │ 1147010078.2135158 │ 313553427.27418107 │ 411646698.9791721  │
    │    1    │ '0x2F0b23f53734252Bda2277357e97e1517d6B042A' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-A'   │  0  │ 875891626.1124029  │ 1.500000000015499  │ 875891626.1124029  │ 196597640.36092234 │ 350558569.7324488  │
    │    2    │ '0xBF72Da2Bd84c5170618Fbe5914B0ECA9638d5eb5' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-A'  │  0  │ 691431233.2620199  │ 1.9999999999966873 │ 691431233.2620199  │  51046990.8898197  │ 126919542.64375526 │
    │    3    │ '0x248cCBf4864221fC0E840F29BB042ad5bFC89B5c' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-B' │  0  │  424804252.009792  │         0          │  424804252.009792  │ 120323824.96121524 │ 149543457.82150096 │
    │    4    │ '0xA191e578a6736167326d05c119CE0c90849E84B7' │ 'makerdao' │  'USDC'  │ 'ethereum' │  'USDC-A'  │  0  │ 226896255.83456367 │         0          │ 226896255.83456367 │ 228250192.38026515 │         0          │
    │    5    │ '0x10CD5fbe1b404B7E19Ef964B63939907bdaf42E2' │ 'makerdao' │ 'wstETH' │ 'ethereum' │ 'WSTETH-A' │  0  │ 221453068.96215165 │ 1.500000000015499  │ 221453068.96215165 │ 52414897.20308339  │ 87260831.14663719  │
    │    6    │ '0x7f62f9592b823331E012D3c5DdF2A7714CfB9de2' │ 'makerdao' │  'WBTC'  │ 'ethereum' │  'WBTC-C'  │  0  │ 158819696.06117183 │ 0.7499999999908489 │ 158819696.06117183 │ 55794569.56800095  │ 164462953.02967158 │
    │    7    │ '0x08638eF1A205bE6762A8b935F5da9b700Cf7322c' │ 'makerdao' │  'WETH'  │ 'ethereum' │  'ETH-B'   │  0  │ 146248240.81262925 │ 3.000000000006898  │ 146248240.81262925 │ 47700393.41412063  │ 71921920.81576702  │
    │    8    │ '0x885f16e177d45fC9e7C87e1DA9fd47A9cfcE8E13' │ 'makerdao' │ 'MATIC'  │ 'ethereum' │ 'MATIC-A'  │  0  │ 118788734.15735413 │ 3.000000000006898  │ 118788734.15735413 │  14270191.402011   │ 18911403.30048648  │
    │    9    │ '0xA6EA3b9C04b8a38Ff5e224E7c3D6937ca44C0ef9' │ 'makerdao' │  'MANA'  │ 'ethereum' │  'MANA-A'  │  0  │ 45947478.45617842  │ 4.499999999989465  │ 45947478.45617842  │  15175400.504782   │ 16167149.937257662 │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────────┴────────────┴─────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┘

**Pull request merged**
