### PR TITLE
add canto-lending

### PR DESCRIPTION
**Pull request by sbbutler**
i noticed in the canto-lending llama adapter note token was included as blacklisted token... i kept it here because borrowing note from lending pool is only way to acquire note... but it the tvl of that pool looks weirdddd because it contains the entire supply

### CODE REVIEW

**Comment by llamatester** [comment]
The canto-lending adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.495 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────┬─────────┬─────────────────┬───────────────┬────────────────────────┬───────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬─────────────────┬────────────────────────┬────────────────────┬─────┐
    │ (index) │                        pool                        │  chain  │     project     │    symbol     │         tvlUsd         │        apyBase        │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │   apyBaseBorrow    │ apyRewardBorrow │     totalSupplyUsd     │   totalBorrowUsd   │ ltv │
    ├─────────┼────────────────────────────────────────────────────┼─────────┼─────────────────┼───────────────┼────────────────────────┼───────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼─────────────────┼────────────────────────┼────────────────────┼─────┤
    │    0    │ '0xee602429ef7ece0a13e4ffe8dbc16e101049504c-canto' │ 'Canto' │ 'canto-lending' │    'cNOTE'    │ 1.1845530728977448e+59 │           0           │         0          │ [ '0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │ 1.1845530728977448e+59 │ 36983666.90758206  │ 0.8 │
    │    1    │ '0xf0cd6b5ce8a01d1b81f1d8b76643866c5816b49f-canto' │ 'Canto' │ 'canto-lending' │ 'cNOTE/USDT'  │    36988424.9776765    │           0           │ 16.05764295069235  │ [ '0x35DB1f3a6A6F07f82C76fCC415dB6cFB1a7df833' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │    36988424.9776765    │         0          │  0  │
    │    2    │ '0xd6a97e43fc885a83e97d599796458a331e580800-canto' │ 'Canto' │ 'canto-lending' │ 'cNOTE/USDC'  │   36382802.38971335    │           0           │ 16.32493602988452  │ [ '0x9571997a66D63958e1B3De9647C22bD6b9e7228c' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │   36382802.38971335    │         0          │  0  │
    │    3    │ '0xde59f060d7ee2b612e7360e6c1b97c4d8289ca2e-canto' │ 'Canto' │ 'canto-lending' │    'cUSDC'    │   32513065.848838482   │ 0.0006259196952000001 │ 1.3666679502455643 │ [ '0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │  0.2501681216976   │        0        │   32594617.52358788    │  81551.6747493949  │ 0.8 │
    │    4    │ '0x6b46ba92d7e94ffa658698764f5b8dfd537315a9-canto' │ 'Canto' │ 'canto-lending' │    'cUSDT'    │   17204247.397526395   │    0.0334094738688    │ 2.5419155434650254 │ [ '0xd567B3d7B8FE3C79a1AD8dA978812cfC4Fa05e75' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │ 1.8277100781048001 │        0        │   17524586.619143475   │ 320339.22161708144 │ 0.8 │
    │    5    │ '0x3c96dcfd875253a37acb3d2b102b6f328349b16b-canto' │ 'Canto' │ 'canto-lending' │ 'cCANTO/NOTE' │   14716431.099380149   │           0           │ 322.87552197353983 │ [ '0x1D20635535307208919f0b67c3B2065965A85aA9' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │   14716431.099380149   │         0          │  0  │
    │    6    │ '0xb49a395b39a0b410675406bee7bd06330cb503e3-canto' │ 'Canto' │ 'canto-lending' │ 'cCANTO/ETH'  │    8987832.39141138    │           0           │ 264.3337773710892  │ [ '0x216400ba362d8FCE640085755e47075109718C8B' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │    8987832.39141138    │         0          │  0  │
    │    7    │ '0xc0d6574b2fe71eed8cd305df0da2323237322557-canto' │ 'Canto' │ 'canto-lending' │ 'cCANTO/ATOM' │    8077113.32105788    │           0           │ 294.13821398371033 │ [ '0x30838619C55B787BafC3A4cD9aEa851C1cfB7b19' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │    8077113.32105788    │         0          │  0  │
    │    8    │ '0xb65ec550ff356eca6150f733ba9b954b2e0ca488-canto' │ 'Canto' │ 'canto-lending' │   'cCANTO'    │   13855.285187186935   │           0           │         0          │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │   13855.285187186935   │         0          │  0  │
    │    9    │ '0x830b9849e7d79b92408a86a557e7baaacbec6030-canto' │ 'Canto' │ 'canto-lending' │    'cETH'     │   3725.5972987826935   │           0           │         0          │ [ '0x5FD55A1B9FC24967C4dB09C513C3BA0DFa7FF687' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │         0          │        0        │   3725.5972987826935   │         0          │  0  │
    └─────────┴────────────────────────────────────────────────────┴─────────┴─────────────────┴───────────────┴────────────────────────┴───────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴─────────────────┴────────────────────────┴────────────────────┴─────┘

**Comment by slasher125** [comment]
henlo siiir, ty for adding 💪

re the note pool: weird, values are so large it will be flagged as an outlier anyways on server side and not included.

re the symbols: can you please remove the c in the stings eg instead of cUSDC -> USDC. reason is that for out new strategy page a route might look like: lend ETH -> borrow USDC -> farm with USDC. but with a symbol like cUSDC it would be weird cause you it would do ETH -> cUSDC -> farm with usdc...but we don't borrow cUSDC but real USDC. hope that kinda explains it. so, the short version: lets use the underlying deposit token symbol instead of the c-asset symbol :)

**Comment by llamatester** [comment]
The canto-lending adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.289 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────┬─────────┬─────────────────┬────────────────────┬────────────────────────┬─────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────┬─────────────────┬────────────────────────┬───────────────────┬─────┐
    │ (index) │                        pool                        │  chain  │     project     │       symbol       │         tvlUsd         │   apyBase   │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │    apyBaseBorrow     │ apyRewardBorrow │     totalSupplyUsd     │  totalBorrowUsd   │ ltv │
    ├─────────┼────────────────────────────────────────────────────┼─────────┼─────────────────┼────────────────────┼────────────────────────┼─────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────┼─────────────────┼────────────────────────┼───────────────────┼─────┤
    │    0    │ '0xee602429ef7ece0a13e4ffe8dbc16e101049504c-canto' │ 'Canto' │ 'canto-lending' │       'NOTE'       │ 1.1683421804045204e+59 │      0      │         0          │ [ '0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │ 1.1683421804045204e+59 │ 27357318.28747182 │ 0.8 │
    │    1    │ '0xf0cd6b5ce8a01d1b81f1d8b76643866c5816b49f-canto' │ 'Canto' │ 'canto-lending' │  'sAMM-NOTE/USDT'  │   28916220.538489074   │      0      │ 14.366750905327933 │ [ '0x35DB1f3a6A6F07f82C76fCC415dB6cFB1a7df833' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │   28916220.538489074   │         0         │  0  │
    │    2    │ '0xde59f060d7ee2b612e7360e6c1b97c4d8289ca2e-canto' │ 'Canto' │ 'canto-lending' │       'USDC'       │   28600397.251705892   │ 1.808064e-7 │ 1.089358461611199  │ [ '0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │ 0.004253884732800001 │        0        │   28601614.085704267   │  1216.833998376   │ 0.8 │
    │    3    │ '0xd6a97e43fc885a83e97d599796458a331e580800-canto' │ 'Canto' │ 'canto-lending' │  'sAMM-NOTE/USDC'  │   21302409.17928724    │      0      │ 19.50165045200301  │ [ '0x9571997a66D63958e1B3De9647C22bD6b9e7228c' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │   21302409.17928724    │         0         │  0  │
    │    4    │ '0x6b46ba92d7e94ffa658698764f5b8dfd537315a9-canto' │ 'Canto' │ 'canto-lending' │       'USDT'       │   16735470.826715639   │  1.0512e-8  │ 1.861739273768454  │ [ '0xd567B3d7B8FE3C79a1AD8dA978812cfC4Fa05e75' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │   0.0010494303048    │        0        │   16735646.47800145    │   175.65128581    │ 0.8 │
    │    5    │ '0x3c96dcfd875253a37acb3d2b102b6f328349b16b-canto' │ 'Canto' │ 'canto-lending' │ 'vAMM-NOTE/WCANTO' │    4809347.83569843    │      0      │ 691.0411170784772  │ [ '0x1D20635535307208919f0b67c3B2065965A85aA9' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │    4809347.83569843    │         0         │  0  │
    │    6    │ '0xb49a395b39a0b410675406bee7bd06330cb503e3-canto' │ 'Canto' │ 'canto-lending' │ 'vAMM-ETH/WCANTO'  │    4429389.53314475    │      0      │ 375.1597230194872  │ [ '0x216400ba362d8FCE640085755e47075109718C8B' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │    4429389.53314475    │         0         │  0  │
    │    7    │ '0xc0d6574b2fe71eed8cd305df0da2323237322557-canto' │ 'Canto' │ 'canto-lending' │ 'vAMM-WCANTO/ATOM' │   1744729.6855973944   │      0      │  952.427510185353  │ [ '0x30838619C55B787BafC3A4cD9aEa851C1cfB7b19' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │   1744729.6855973944   │         0         │  0  │
    │    8    │ '0xb65ec550ff356eca6150f733ba9b954b2e0ca488-canto' │ 'Canto' │ 'canto-lending' │      'WCANTO'      │   9690.985057831613    │      0      │         0          │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │   9690.985057831613    │         0         │  0  │
    │    9    │ '0x830b9849e7d79b92408a86a557e7baaacbec6030-canto' │ 'Canto' │ 'canto-lending' │       'ETH'        │   2913.0197741928077   │      0      │         0          │ [ '0x5FD55A1B9FC24967C4dB09C513C3BA0DFa7FF687' ] │ [ '0x826551890Dc65655a0Aceca109aB11AbDbD7a07B' ] │          0           │        0        │   2913.0197741928077   │         0         │  0  │
    └─────────┴────────────────────────────────────────────────────┴─────────┴─────────────────┴────────────────────┴────────────────────────┴─────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────┴─────────────────┴────────────────────────┴───────────────────┴─────┘

**Comment by sbbutler** [comment]
henlooo 
i don think ive ever used the underlying deposit token symbol when exporting... should i change in the other adapters too?
:salute~1:

**Comment by slasher125** [comment]
> henlooo i don think ive ever used the underlying deposit token symbol when exporting... should i change in the other adapters too? :salute~1:

no problem, i made that change a while ago for the other adapters

**Comment by sbbutler** [comment]
ohh watdahale... u did!
mebe ill jus update the stargate adaptor i think that one still shows lp token symbol

**Comment by slasher125** [comment]
no need :)
basically, i only changed it for lending protocols. for anything else is fine

**Comment by sbbutler** [comment]
okieeee  :llamacosy:

**Pull request merged**
