### PR TITLE
Polytrade yield server

### PR DESCRIPTION
**Pull request by rohitpoly**

### CODE REVIEW

**Comment by rohitpoly** [comment]
@slasher125

**Comment by slasher125** [comment]
did u actually run the tests locally? cause that would show you whats wrong. pls fix that stuff first before u ping me unless you do not know how to fix it. 

anyways, briefly scanned the code:
you can't just call .output at the end of an await call. u need to wrap the await in () and call .output or destructure the object

eg: 
```
  const { output: tvl } = await sdk.api.abi.call({
    target: '0xfE624A12b1732d19680A7a2a2efBe21f1C0F3F19',
    abi: abis.getBalance,
    chain,
  });
```
or 
```
  const tvl = (
    await sdk.api.abi.call({
      target: '0xfE624A12b1732d19680A7a2a2efBe21f1C0F3F19',
      abi: abis.getBalance,
      chain,
    })
  ).output;
```

**Comment by rohitpoly** [comment]
@slasher125 check now

**Comment by llamatester** [comment]
The polytrade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.366 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬────────┬──────────────┬─────┐
    │ (index) │                         pool                         │   chain   │   project   │ symbol │    tvlUsd    │ apy │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼────────┼──────────────┼─────┤
    │    0    │ '0xE544a0Ca5F4a01f137AE5448027471D6a9eC9661-polygon' │ 'Polygon' │ 'polytrade' │ 'USDC' │ 17913.135546 │  6  │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴────────┴──────────────┴─────┘

**Comment by rohitpoly** [comment]
@slasher125 check now

**Comment by llamatester** [comment]
The polytrade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.335 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬────────┬──────────────┬───────┐
    │ (index) │                         pool                         │   chain   │   project   │ symbol │    tvlUsd    │  apy  │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼────────┼──────────────┼───────┤
    │    0    │ '0xE544a0Ca5F4a01f137AE5448027471D6a9eC9661-polygon' │ 'Polygon' │ 'polytrade' │ 'USDC' │ 17913.171616 │ 9.827 │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴────────┴──────────────┴───────┘

**Comment by slasher125** [comment]
hi, looking gud now. couple of remaining q's:
- the apy, can we split it into base and reward? if so lets do that as its giving a better understanding of where yield is coming from
- are there any locking periods in order to receive the TRADE rewards?

**Comment by rohitpoly** [comment]
@slasher125 

1. I have split into base and rewards
2. there is no lock in period

**Comment by llamatester** [comment]
Error while running polytrade adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.351 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬────────┬──────────────┬─────────┬────────────────────┐
    │ (index) │                         pool                         │   chain   │   project   │ symbol │    tvlUsd    │ apyBase │     apyReward      │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼────────┼──────────────┼─────────┼────────────────────┤
    │    0    │ '0xE544a0Ca5F4a01f137AE5448027471D6a9eC9661-polygon' │ 'Polygon' │ 'polytrade' │ 'USDC' │ 17913.600575 │    6    │ 3.7655000000000003 │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴────────┴──────────────┴─────────┴────────────────────┘
    }

**Comment by llamatester** [comment]
The polytrade adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.335 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬────────┬──────────────┬─────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                         │   chain   │   project   │ symbol │    tvlUsd    │ apyBase │     apyReward      │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼────────┼──────────────┼─────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xE544a0Ca5F4a01f137AE5448027471D6a9eC9661-polygon' │ 'Polygon' │ 'polytrade' │ 'USDC' │ 17913.603088 │    6    │ 3.7655000000000003 │ [ '0x692ac1e363ae34b6b489148152b12e2785a3d8d6' ] │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴────────┴──────────────┴─────────┴────────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
