### PR TITLE
add myso adaptor

### PR DESCRIPTION
**Pull request by kolima**
add myso adaptor

### CODE REVIEW

**Comment by llamatester** [comment]
The myso adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.318 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬─────────────┬───────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬───────────────┬─────────────────────┬────────────┐
    │ (index) │                     pool                     │   chain    │ project │   symbol    │      tvlUsd       │ apyBase │                                        underlyingTokens                                        │   totalSupplyUsd   │   totalBorrowUsd   │ apyBaseBorrow │         ltv         │ borrowable │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼─────────────┼───────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼───────────────┼─────────────────────┼────────────┤
    │    0    │ '0x331c54fd17a54dcddb0215b9f02390cef7c7ee8f' │ 'Ethereum' │ 'myso'  │ 'USDC-RPL'  │ 7506.498029029999 │  7.926  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 7506.498029029999  │         0          │     7.93      │ 0.14400000000000002 │    true    │
    │    1    │ '0x9e29ce780ea28ba83053b78473c19544f75c1113' │ 'Ethereum' │ 'myso'  │ 'WETH-rETH' │ 4846.381415021913 │ 3.9149  │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xae78736Cd615f374D3085123A210448E74Fc6393' ] │ 10122.306003149386 │ 5275.924588127473  │     3.91      │        0.943        │   false    │
    │    2    │ '0x15315dfc9e2cc4f7f5456323ab7010a1a74a337d' │ 'Ethereum' │ 'myso'  │ 'rETH-RPL'  │ 1745.643492407546 │ 0.0405  │ [ '0xae78736Cd615f374D3085123A210448E74Fc6393', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 175210.86204069192 │ 173465.21854828438 │     0.05      │ 0.39799999999999996 │    true    │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴─────────────┴───────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴───────────────┴─────────────────────┴────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi and ty for adding.

- do u guys have some docs available? 
- the `USDC-RPL` pool, do i need to provide both assets or just one?
- these are fixed rates? if so pls add the `poolMeta` and set it to the duration
- fyi: we currently do not display anything with tvlUsd < 10k. given all three pools are below that value it would only show up on the UI once above that. Note: i'll likely change this for lending protocols soon tm

**Comment by kolima** [comment]
@slasher125 Hi!

- Documentation: [https://myso-finance.gitbook.io/documentation](https://myso-finance.gitbook.io/documentation)
- Just one, USDC. There's a USDC-RPL pool, where RPL is the collateral currency and USDC is the loan currency then LPs can add USDC and borrowers can borrow USDC by pledging RPL and LPs add just single-sided liquidity. Our pools are open-ended, so LPs can continuously add or remove liquidity
- yeah, fixed rate and it already have added to PR
- Okay, we expect more liquidity in the near time

**Comment by llamatester** [comment]
The myso adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.524 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬─────────────┬────────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬───────────────┬─────────────────────┬────────────┐
    │ (index) │                     pool                     │   chain    │ project │   symbol    │       tvlUsd       │ apyBase │                                        underlyingTokens                                        │                                          poolMeta                                           │   totalSupplyUsd   │   totalBorrowUsd   │ apyBaseBorrow │         ltv         │ borrowable │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼─────────────┼────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼───────────────┼─────────────────────┼────────────┤
    │    0    │ '0xea9134ad24795549580c7c542134a670d0d19433' │ 'Ethereum' │ 'myso'  │ 'DAI-gOHM'  │  9628.22173948835  │ 7.9999  │ [ '0x6B175474E89094C44Da98b954EedeAC495271d0F', '0x0ab87046fBb341D058F17CBC4c1133F25a20a52f' ] │ 'Fixed interest rates for borrowers. Loans have a fixed tenor 40 days. Pool is open-ended'  │  9628.22173948835  │         0          │     7.99      │ 0.49700000000000005 │    true    │
    │    1    │ '0x331c54fd17a54dcddb0215b9f02390cef7c7ee8f' │ 'Ethereum' │ 'myso'  │ 'USDC-RPL'  │ 7521.496027089999  │  7.926  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 'Fixed interest rates for borrowers. Loans have a fixed tenor 180 days. Pool is open-ended' │ 7521.496027089999  │         0          │     7.93      │        0.146        │    true    │
    │    2    │ '0x9e29ce780ea28ba83053b78473c19544f75c1113' │ 'Ethereum' │ 'myso'  │ 'WETH-rETH' │ 4885.490258179838  │ 3.9149  │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xae78736Cd615f374D3085123A210448E74Fc6393' ] │ 'Fixed interest rates for borrowers. Loans have a fixed tenor 90 days. Pool is open-ended'  │  10192.530511944   │ 5307.040253764162  │     3.91      │        0.945        │   false    │
    │    3    │ '0x15315dfc9e2cc4f7f5456323ab7010a1a74a337d' │ 'Ethereum' │ 'myso'  │ 'rETH-RPL'  │ 1755.9387228118712 │ 0.0405  │ [ '0xae78736Cd615f374D3085123A210448E74Fc6393', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 'Fixed interest rates for borrowers. Loans have a fixed tenor 90 days. Pool is open-ended'  │ 172851.04729866545 │ 171095.10857585358 │     0.05      │        0.405        │    true    │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴─────────────┴────────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴───────────────┴─────────────────────┴────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ty. 
- we only display the LP token. so instead of `DAI-gOHM` we'd use `DAI` instead. 
- lets shorten the poolMeta field, something like: `Fixed interest for borrowers, 40day loan tenor`

**Comment by llamatester** [comment]
The myso adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.339 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────┬───────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────┬────────────────────┬───────────────────┬───────────────┬─────────────────────┬────────────┐
    │ (index) │                     pool                     │   chain    │ project │ symbol │      tvlUsd       │ apyBase │                                        underlyingTokens                                        │                      poolMeta                      │   totalSupplyUsd   │  totalBorrowUsd   │ apyBaseBorrow │         ltv         │ borrowable │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────┼───────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼────────────────────┼───────────────────┼───────────────┼─────────────────────┼────────────┤
    │    0    │ '0xea9134ad24795549580c7c542134a670d0d19433' │ 'Ethereum' │ 'myso'  │ 'DAI'  │  9516.407936352   │ 7.9999  │ [ '0x6B175474E89094C44Da98b954EedeAC495271d0F', '0x0ab87046fBb341D058F17CBC4c1133F25a20a52f' ] │ 'Fixed interest for borrowers, 40days loan tenor'  │   9725.413088352   │    209.005152     │     7.99      │        0.488        │    true    │
    │    1    │ '0x331c54fd17a54dcddb0215b9f02390cef7c7ee8f' │ 'Ethereum' │ 'myso'  │ 'USDC' │ 7506.498029029999 │  7.926  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 'Fixed interest for borrowers, 180days loan tenor' │ 7506.498029029999  │         0         │     7.93      │ 0.14800000000000002 │    true    │
    │    2    │ '0x9e29ce780ea28ba83053b78473c19544f75c1113' │ 'Ethereum' │ 'myso'  │ 'WETH' │ 4857.700772623616 │ 3.9149  │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xae78736Cd615f374D3085123A210448E74Fc6393' ] │ 'Fixed interest for borrowers, 90days loan tenor'  │ 10126.661975900943 │ 5268.961203277327 │     3.91      │        0.946        │   false    │
    │    3    │ '0x15315dfc9e2cc4f7f5456323ab7010a1a74a337d' │ 'Ethereum' │ 'myso'  │ 'rETH' │ 1743.33951947432  │ 0.0405  │ [ '0xae78736Cd615f374D3085123A210448E74Fc6393', '0xD33526068D116cE69F19A9ee46F0bd304F21A51f' ] │ 'Fixed interest for borrowers, 90days loan tenor'  │ 170513.0571789807  │ 168769.7176595064 │     0.05      │        0.408        │    true    │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────┴───────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────┴────────────────────┴───────────────────┴───────────────┴─────────────────────┴────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by kolima** [comment]
> * DAI

Done

**Comment by kolima** [comment]
> ty.
> 
> * we only display the LP token. so instead of `DAI-gOHM` we'd use `DAI` instead.
> * lets shorten the poolMeta field, something like: `Fixed interest for borrowers, 40day loan tenor`

Done

**Pull request merged**
