### PR TITLE
Add Origin Ether (OETH)

### PR DESCRIPTION
**Pull request by shahthepro**
Adds OETH yield adapter

### CODE REVIEW

**Comment by slasher125** [comment]
gm, ty for adding.pls make use of onchain calls/subgraph for at least the tvl data. ty

**Comment by shahthepro** [comment]
> gm, ty for adding.pls make use of onchain calls/subgraph for at least the tvl data. ty

Hello, our contracts return the TVL denominated in ETH and we don't have a ETH/USD price oracle in the contract. That's the reason I used API calls

**Comment by slasher125** [comment]
no problem, for eth usd price u can just use our price api

**Comment by shahthepro** [comment]
@slasher125 Have made that change, PTAL

**Comment by slasher125** [comment]
ran this locally, working fine

**Pull request merged**
