### PR TITLE
Feature/0vix setup

### PR DESCRIPTION
**Pull request by chaoticgoodpanda**
0vix protocol supply and borrow apys and tvl in USD setups

### CODE REVIEW

**Comment by vrtnd** [comment]
Hi, tnaks for the PR.
The tests do not pass `reason: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.6)`

**Comment by chaoticgoodpanda** [comment]
Right -- so I used the provider in your `env.js` file, `process.env.ALCHEMY_CONNECTION_POLYGON`. Please check our `Providers.ts` file for reference. Would this not work? Noticed `brince-finance` is doing this in their files.

**Comment by chaoticgoodpanda** [comment]
Swapped in the Polygon public rpc as `provider`, should work.

**Comment by llamatester** [comment]
Error while running 0vix adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       6 failed, 27 passed, 33 total
    Snapshots:   0 total
    Time:        0.469 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────┬───────────┬──────────────────────────────────────────────────────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │ symbol  │   chain   │                               apy                                │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────┼───────────┼──────────────────────────────────────────────────────────────────┼────────────────────┤
    │    0    │ '0xEBb865Bf286e6eA8aBf5ac97e1b56A76530F3fBe' │ '0vix'  │ 'USDC'  │ 'polygon' │ { supplyApy: 1.7331359924353862, borrowApy: 4.7435733202695785 } │ 360609.4565907478  │
    │    1    │ '0xE554E874c9c60E45F1Debd479389C76230ae25A8' │ '0vix'  │ 'MATIC' │ 'polygon' │  { supplyApy: 3.138867549138391, borrowApy: 6.412745693571487 }  │ 360609.4565907478  │
    │    2    │ '0xb2D9646A1394bf784E376612136B3686e74A325F' │ '0vix'  │ 'WETH'  │ 'polygon' │ { supplyApy: 0.12897765735904176, borrowApy: 1.277414926044762 } │ 356139.77174260543 │
    │    3    │ '0x3B9128Ddd834cE06A60B0eC31CCfB11582d8ee18' │ '0vix'  │ 'WBTC'  │ 'polygon' │ { supplyApy: 3.3020078709183442, borrowApy: 6.579887540175866 }  │ 173537.87755627235 │
    │    4    │ '0x1372c34acC14F1E8644C72Dad82E3a21C211729f' │ '0vix'  │ 'USDT'  │ 'polygon' │ { supplyApy: 3.8082979200040556, borrowApy: 7.0741906455683345 } │ 83184.01531526656  │
    │    5    │ '0x2175110F2936bf630a278660E9B6E4EFa358490A' │ '0vix'  │  'DAI'  │ 'polygon' │  { supplyApy: 7.123988859168984, borrowApy: 9.718463633239693 }  │ 39829.90435017748  │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────┴───────────┴──────────────────────────────────────────────────────────────────┴────────────────────┘
    }

**Comment by vrtnd** [comment]
Is it lending market? If yes then get `supplyApy` and store it as `apyBase`.
And please pass underlyingTokens array if possible

**Comment by chaoticgoodpanda** [comment]
OK, passes all tests now, split out supplyAPY and put it in `apyBase` key per your request, and put borrowAPY in `apy` key. Also added `underlyingTokens` array.

**Comment by chaoticgoodpanda** [comment]
Fair enough. Have removed `borrowAPY` with latest commit. Passes all tests.

**Comment by llamatester** [comment]
Error while running 0vix adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 39 passed, 40 total
    Snapshots:   0 total
    Time:        0.556 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────┬───────────┬──────────────────────────────────────────────────┬─────────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │ symbol  │   chain   │                 underlyingTokens                 │       apyBase       │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────┼───────────┼──────────────────────────────────────────────────┼─────────────────────┼────────────────────┤
    │    0    │ '0xEBb865Bf286e6eA8aBf5ac97e1b56A76530F3fBe' │ '0vix'  │ 'USDC'  │ 'polygon' │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 1.7331751731215483  │ 360611.2293902669  │
    │    1    │ '0xE554E874c9c60E45F1Debd479389C76230ae25A8' │ '0vix'  │ 'MATIC' │ 'polygon' │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 3.1423978183107826  │ 360611.2293902669  │
    │    2    │ '0xb2D9646A1394bf784E376612136B3686e74A325F' │ '0vix'  │ 'WETH'  │ 'polygon' │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 0.12897976078813933 │ 354634.3978955556  │
    │    3    │ '0x3B9128Ddd834cE06A60B0eC31CCfB11582d8ee18' │ '0vix'  │ 'WBTC'  │ 'polygon' │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ 3.3020078709183442  │ 172479.34185042005 │
    │    4    │ '0x1372c34acC14F1E8644C72Dad82E3a21C211729f' │ '0vix'  │ 'USDT'  │ 'polygon' │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │  3.833435956406106  │  82904.3684779558  │
    │    5    │ '0x2175110F2936bf630a278660E9B6E4EFa358490A' │ '0vix'  │  'DAI'  │ 'polygon' │ [ '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │  7.123988859168984  │ 39832.926667842774 │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────┴───────────┴──────────────────────────────────────────────────┴─────────────────────┴────────────────────┘
    }

**Comment by vrtnd** [comment]
Add link to the page with pools please 
https://github.com/DefiLlama/yield-server#adapter-module-structure

**Comment by chaoticgoodpanda** [comment]
Done. Added url to pools.

**Comment by llamatester** [comment]
The 0vix adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       40 passed, 40 total
    Snapshots:   0 total
    Time:        0.39 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────┬───────────┬──────────────────────────────────────────────────┬─────────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │ symbol  │   chain   │                 underlyingTokens                 │       apyBase       │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────┼───────────┼──────────────────────────────────────────────────┼─────────────────────┼────────────────────┤
    │    0    │ '0xEBb865Bf286e6eA8aBf5ac97e1b56A76530F3fBe' │ '0vix'  │ 'USDC'  │ 'polygon' │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 1.7341133769678718  │ 360487.4477658202  │
    │    1    │ '0xE554E874c9c60E45F1Debd479389C76230ae25A8' │ '0vix'  │ 'MATIC' │ 'polygon' │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 3.1423978183107826  │ 360487.4477658202  │
    │    2    │ '0xb2D9646A1394bf784E376612136B3686e74A325F' │ '0vix'  │ 'WETH'  │ 'polygon' │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 0.12897976078813933 │ 355945.81739497045 │
    │    3    │ '0x3B9128Ddd834cE06A60B0eC31CCfB11582d8ee18' │ '0vix'  │ 'WBTC'  │ 'polygon' │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ 3.3020078709183442  │ 172463.80588764118 │
    │    4    │ '0x1372c34acC14F1E8644C72Dad82E3a21C211729f' │ '0vix'  │ 'USDT'  │ 'polygon' │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ 3.8239166936013813  │ 82913.48913340548  │
    │    5    │ '0x2175110F2936bf630a278660E9B6E4EFa358490A' │ '0vix'  │  'DAI'  │ 'polygon' │ [ '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │  7.123988859168984  │ 39822.200567215965 │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────┴───────────┴──────────────────────────────────────────────────┴─────────────────────┴────────────────────┘

**Comment by chaoticgoodpanda** [comment]
Great, thanks!

**Comment by chaoticgoodpanda** [comment]
Yes, it’s because I replaced our RPC provider with yours in the env.js file. Do you need us to provide our own provider? I had assumed that you would leverage yours. Please advise with thanks!

From: vrotend ***@***.***>
Date: Wednesday, August 10, 2022 at 8:22 PM
To: DefiLlama/yield-server ***@***.***>
Cc: Michael Lwin ***@***.***>, Author ***@***.***>
Subject: Re: [DefiLlama/yield-server] Feature/0vix setup (PR #191)

Hi, tnaks for the PR.
The tests do not pass reason: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.6)

**Pull request merged**
