### PR TITLE
add venus onchain adaptor

### PR DESCRIPTION
**Pull request by sbbutler**

### CODE REVIEW

**Comment by slasher125** [comment]
gm @sbbutler ty for refactoring to onchain 😎. one thing, have u noticed the new borrow related fields that were recently added? these specifically:
```
    // borrow fields
    apyBaseBorrow: Number(market.borrowApy) * -1,
    apyRewardBorrow: Number(market.borrowVenusApy),
    totalSupplyUsd: Number(market.totalSupplyUsd),
    totalBorrowUsd: Number(market.totalBorrowsUsd),
    ltv: Number(market.collateralFactor) / 1e18,
```

we'll need them cause we are working on something new...would appreciate if you could add those and then we can merge

**Comment by sbbutler** [comment]
ayyeee! yeah i saw u added those yesterday in the original venus adaptor.
sweet sweet ill add em

**Comment by llamatester** [comment]
The venus adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       165 passed, 165 total
    Snapshots:   0 total
    Time:        0.391 s
    Ran all test suites.
    
    Nb of pools: 23
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────┬─────────┬────────────────────┬─────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────┐
    │ (index) │                         pool                         │   chain   │ project │ symbol  │       tvlUsd       │       apyBase       │      apyReward      │                 underlyingTokens                 │                   rewardTokens                   │   apyBaseBorrow    │  apyRewardBorrow   │   totalSupplyUsd   │   totalBorrowUsd   │ ltv │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────┼─────────┼────────────────────┼─────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────┤
    │    0    │ '0x882c173bc7ff3b7786ca16dfed3dfffb9ee7847b-binance' │ 'Binance' │ 'venus' │ 'vBTC'  │ 211213025.4251059  │    0.3911893632     │ 0.49886133916639447 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.4890684084928   │ 2.5393328464315705 │ 262851096.49730384 │ 51638071.07219795  │ 0.8 │
    │    1    │ '0xa07c5b74c9b40447a954e1466938b865b6bbea36-binance' │ 'Binance' │ 'venus' │ 'vBNB'  │ 109390357.43074714 │ 1.1170157676047998  │ 0.7898120065704882  │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  4.0933160793504   │ 2.315419550951413  │ 166022102.61322173 │  56631745.1824746  │ 0.8 │
    │    2    │ '0xfd5840cd36d94d7229439859c0112a4185bc0255-binance' │ 'Binance' │ 'venus' │ 'vUSDT' │  76253101.0011498  │ 1.1776691288016001  │ 0.34996360781342195 │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.5578518860944   │ 0.6840967015908715 │ 156118911.45301068 │ 79865810.45186087  │ 0.8 │
    │    3    │ '0x95c78222b3d6e262426483d42cfa53685a67ab9d-binance' │ 'Binance' │ 'venus' │ 'vBUSD' │ 69309093.25655764  │   1.0500629810832   │ 0.40750036567563164 │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 2.4153018917903997 │ 0.8435806034559467 │ 134075799.93066737 │ 64766706.674109735 │ 0.8 │
    │    4    │ '0xf508fcd89b8bd15579dc79a6827cb4686a3592c8-binance' │ 'Binance' │ 'venus' │ 'vETH'  │ 55766960.656551525 │   1.0850983712208   │ 0.7909964017080747  │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 4.1455090717920005 │ 2.417537685938946  │ 82886755.05782714  │ 27119794.40127562  │ 0.8 │
    │    5    │ '0xeca88125a5adbe82614ffc12d0db554e2e2867c8-binance' │ 'Binance' │ 'venus' │ 'vUSDC' │ 37611474.21173519  │ 1.2217610000880001  │ 0.6957289767687366  │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.6052948231984   │ 1.3352212011212565 │ 78530490.06777392  │ 40919015.856038734 │ 0.8 │
    │    6    │ '0x2ff3d0f6990a40261c66e1ff2017acbc282eb6d0-binance' │ 'Binance' │ 'venus' │ 'vSXP'  │ 17167641.752418652 │ 0.12229284575520001 │ 0.24077214143343123 │ [ '0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.8146599882784   │ 4.433238616203363  │ 18153574.470775966 │ 985932.7183573135  │ 0.5 │
    │    7    │ '0x08ceb3f4a7ed3500ca0982bcd0fc7816688084c3-binance' │ 'Binance' │ 'venus' │ 'vTUSD' │ 9155781.923465565  │   0.6456921806304   │ 0.2855864513612426  │ [ '0x14016E85a25aeb13065688cAFB43044C2ef86784' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.0088743449536   │ 0.7108121321544919 │ 15304910.226540184 │  6149128.30307462  │ 0.8 │
    │    8    │ '0x972207a639cc1b374b893cc33fa251b55ceb7c07-binance' │ 'Binance' │ 'venus' │ 'vBETH' │ 6848671.250115378  │   1.1373156642528   │ 1.2140524720875454  │ [ '0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 4.617864085694399  │ 3.9435519842520805 │ 9894887.680879211  │ 3046216.4307638337 │ 0.6 │
    │    9    │ '0xb248a295732e0225acd3337607cc01068e3b9c10-binance' │ 'Binance' │ 'venus' │ 'vXRP'  │ 6107626.495622192  │   0.4626484422912   │ 0.5635452555265795  │ [ '0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 4.110411275064001  │ 4.005465156575229  │ 7107627.667377428  │ 1000001.1717552361 │ 0.6 │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────┴─────────┴────────────────────┴─────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────┘

**Comment by sbbutler** [comment]
i noticed that the pools this adaptor outputs is different than the original venus adaptor...
this adaptor filters for supply rate which removes the CAN pool also the vluna and xvs pool... the xvs pool is present in the original adaptor... this adaptor includes vUST which is not present in the original adaptor

are there certain criteria i should be using to determine which pools to include/exclude?

**Comment by sbbutler** [comment]
the vluna pool has 0 supplyrate n 0 xvs incentives (venusSpeed = 0)
the xvs pool has 0 supplyrate n 0 xvs incentives (venusSpeed = 0)
the vcan pool has a smol supply rate n 0 xvs incentives (venusSpeed = 0)... this pool cannot be found on the venus front end n no price info can be found on coingecko
by choosing to filter by supplyrate these three pools are omitted because no yield or in vcans case tiny yield / no support

the vust pool has a smol supplyrate n 0 xvs incentives (venusSpeed = 0)
this pool is accepted because the supplyrate meets the minimum threshold

**Comment by slasher125** [comment]
> are there certain criteria i should be using to determine which pools to include/exclude?

we don't apply any filters on the adapter level but only on server side (u can take a look into `/src/handlers/triggerAdaptor.js` if u want to see the details (eg we remove smol pools with tvl < $1k) and apy needs to be >= 0

as for the differences btw master and this PR: 
- i just checked, the luna pool is basically 0 tvl too in the master branch (totally ok if not in your version)
- CAN i couldn't even find (same as for luna, we can ignore that one)
- XVS: is `}).filter((pool) => pool.supplyRate > 100000000);` removing it? if so, i'd remove that filter.

**Comment by slasher125** [comment]
oh, and really important: we need to keep the `pool` value as we have in master. u probably checked out the readme which says to add `...-chain` (we basically do this for new adaptors, but try to avoid changing pool values from existing ones)

So lets remove the chain suffix, and please i'd appreciate if u could double check that the pool values exactly map to the current ones from master. ty 🙏

**Comment by llamatester** [comment]
The venus adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       179 passed, 179 total
    Snapshots:   0 total
    Time:        0.375 s
    Ran all test suites.
    
    Nb of pools: 25
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────┬─────────┬────────────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────┐
    │ (index) │                     pool                     │   chain   │ project │ symbol  │       tvlUsd       │       apyBase       │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │   apyBaseBorrow    │  apyRewardBorrow   │   totalSupplyUsd   │   totalBorrowUsd   │ ltv │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────┼─────────┼────────────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────┤
    │    0    │ '0x882c173bc7ff3b7786ca16dfed3dfffb9ee7847b' │ 'Binance' │ 'venus' │ 'vBTC'  │  204688125.933143  │ 0.40184656440480004 │ 0.515203128466255  │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.5227455220864   │ 2.587507768087518  │ 255576378.95559594 │ 50888253.02245296  │ 0.8 │
    │    1    │ '0xa07c5b74c9b40447a954e1466938b865b6bbea36' │ 'Binance' │ 'venus' │ 'vBNB'  │ 110992756.00962175 │   1.0937291994144   │ 0.7858999578897463 │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │   4.05042442092    │ 2.328348467357995  │ 167545180.11880672 │ 56552424.109184965 │ 0.8 │
    │    2    │ '0xfd5840cd36d94d7229439859c0112a4185bc0255' │ 'Binance' │ 'venus' │ 'vUSDT' │ 70539833.29018867  │ 1.2793593680495998  │ 0.3630651124737354 │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 2.6659992579983998 │ 0.6809175045098658 │ 151113562.31995082 │ 80573729.02976215  │ 0.8 │
    │    3    │ '0x95c78222b3d6e262426483d42cfa53685a67ab9d' │ 'Binance' │ 'venus' │ 'vBUSD' │ 64600081.14345259  │ 1.1248231151519998  │ 0.4246772978217668 │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 2.4998034542111998 │ 0.8494213753800112 │ 129190005.63817687 │ 64589924.49472428  │ 0.8 │
    │    4    │ '0xf508fcd89b8bd15579dc79a6827cb4686a3592c8' │ 'Binance' │ 'venus' │ 'vETH'  │ 59047292.052193925 │   0.9192628220832   │ 0.7792047779615897 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  3.8156028300432   │ 2.587408850979993  │ 84492391.29697073  │ 25445099.244776797 │ 0.8 │
    │    5    │ '0xeca88125a5adbe82614ffc12d0db554e2e2867c8' │ 'Binance' │ 'venus' │ 'vUSDC' │  36879574.0796921  │   1.2644536737168   │ 0.6990717047307125 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.6504231041008   │ 1.318792654982224  │ 78481309.03986996  │ 41601734.96017786  │ 0.8 │
    │    6    │ '0x2ff3d0f6990a40261c66e1ff2017acbc282eb6d0' │ 'Binance' │ 'venus' │ 'vSXP'  │ 17749150.784840524 │   0.101727241488    │ 0.235662270097235  │ [ '0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.7051058017216   │ 5.013338477735097  │ 18624640.24550485  │ 875489.4606643228  │ 0.5 │
    │    7    │ '0x08ceb3f4a7ed3500ca0982bcd0fc7816688084c3' │ 'Binance' │ 'venus' │ 'vTUSD' │ 9123013.078239735  │   0.6507278690832   │ 0.2870566736169317 │ [ '0x14016E85a25aeb13065688cAFB43044C2ef86784' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  2.0166926344416   │ 0.7117015965209447 │ 15290099.145568566 │  6167086.06732883  │ 0.8 │
    │    8    │ '0xb248a295732e0225acd3337607cc01068e3b9c10' │ 'Binance' │ 'venus' │ 'vXRP'  │ 6774978.441945045  │ 0.44862076486079994 │ 0.5118408434675902 │ [ '0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │  4.0678395262272   │ 3.712866764213156  │ 7858290.719338979  │ 1083312.2773939334 │ 0.6 │
    │    9    │ '0x972207a639cc1b374b893cc33fa251b55ceb7c07' │ 'Binance' │ 'venus' │ 'vBETH' │ 6534311.685610209  │ 1.2783323372400002  │ 1.2435672388322974 │ [ '0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B' ] │ [ '0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63' ] │ 4.8957871009103995 │ 3.8101143279682086 │ 9700377.087231055  │ 3166065.401620846  │ 0.6 │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────┴─────────┴────────────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────┘

**Comment by sbbutler** [comment]
> we don't apply any filters on the adapter level but only on server side (u can take a look into `/src/handlers/triggerAdaptor.js` if u want to see the details (eg we remove smol pools with tvl < $1k) and apy needs to be >= 0

this is cool thanks fer pointing me here, since i didnt see the vcan pool in the original adaptor i thought the filtering was happening from the venus api endpoint... sweet to see how its done on ur end

ive double n triple checked the pool values and they r same wit originals now : )

**Pull request merged**
