### PR TITLE
feat:add derify-protocol

### PR DESCRIPTION
**Pull request by Austin929**

### CODE REVIEW

**Comment by llamatester** [comment]
The derify-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.322 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────────────┬────────┬────────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain   │      project      │ symbol │     tvlUsd     │        apy        │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────────────┼────────┼────────────────┼───────────────────┤
    │    0    │ '0x75777494496f6250DdB9A1B96a6203e219d3698f' │ 'Binance' │ 'derify-protocol' │ 'BUSD' │ 44675.26948642 │ 6754.023285540001 │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────────────┴────────┴────────────────┴───────────────────┘

**Comment by slasher125** [comment]
gm sir. we no longer except api adapters (see readme). pls refactor to on chain calls/subgraphs

**Comment by Austin929** [comment]
hi,apy update apyBase?

**Comment by Austin929** [comment]
Can you provide me with an example, thanks

**Comment by Austin929** [comment]
Currently subgraphs do not support BNB

**Comment by Austin929** [comment]
Can you provide me a basic example

**Comment by Austin929** [comment]
We currently do not have the on-chain APY data, can we use api at the beginning, we will work on the on-chain APY data, and provide it in the near future.

**Comment by slasher125** [comment]
as a minimum we need to pull tvl from chain. also, why is the apy so high, pls provide a link to that pool in here.
another thing: make sure to only include lower bound apy values, we do not display any boosted rewards!

**Comment by Austin929** [comment]
We have just finished the APY calculation from on-chain data. Since we use the trading fee of last day to calculate apy of the current day, we need to scan all the blocks of the last day to obtain the trading fee, and this will take some time. I am wondering if you can cache the APY of the current day since scanning all the blocks of the last day takes quite a while.

**Comment by slasher125** [comment]
how long does it take to run it?

**Comment by slasher125** [comment]
closing this for now, feel free to reopen.

**Pull request closed without merging**
