### PR TITLE
fix: arrakis vaults APY calculation

### PR DESCRIPTION
**Pull request by wei3erHase**
this PR replaces the `averageApr` queried for the `apr` of the last snapshot took to the pool

### CODE REVIEW

**Comment by slasher125** [comment]
ty for this. smol ting `?.apr` should fix it, some of those queries return an empty snapshots array

**Comment by slasher125** [comment]
Q: the snapshot from the latest startTimestamp is giving the apr from that timestamp up until now?

**Comment by wei3erHase** [comment]
> smol ting ?.apr should fix it
hmmm dunno if it's best to bring a `null` value, or fetch the `averageApr` when no snapshot is fetched, wdyt?

> Q: the snapshot from the latest startTimestamp is giving the apr from that timestamp up until now?
not until now, snapshots have a `startTimestamp` and `endTimestamp` and they are taken in certain periods, i'm choosing the last one as it's supposed to be the most updated one

**Comment by llamatester** [comment]
The arrakis-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       1348 passed, 1348 total
    Snapshots:   0 total
    Time:        0.653 s
    Ran all test suites.
    
    Nb of pools: 224
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────┬────────────────┬────────────────────┬──────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │      project      │     symbol     │       tvlUsd       │         apy          │                                         url                                          │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────┼────────────────┼────────────────────┼──────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xabddafb225e10b90d798bb8a886238fb835e2053' │ 'Ethereum' │ 'arrakis-finance' │   'DAI-USDC'   │ 234041672.4361121  │ 0.23912665174137224  │  'https://beta.arrakis.finance/vaults/1/0xabddafb225e10b90d798bb8a886238fb835e2053'  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    1    │ '0x50379f632ca68d36e50cfbc8f78fe16bd1499d1e' │ 'Ethereum' │ 'arrakis-finance' │   'DAI-USDC'   │ 200923300.38898206 │ 0.12628003373005192  │  'https://beta.arrakis.finance/vaults/1/0x50379f632ca68d36e50cfbc8f78fe16bd1499d1e'  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    2    │ '0xedecb43233549c51cc3268b5de840239787ad56c' │ 'Ethereum' │ 'arrakis-finance' │  'agEUR-USDC'  │ 3710928.345148163  │  0.4756253485989863  │  'https://beta.arrakis.finance/vaults/1/0xedecb43233549c51cc3268b5de840239787ad56c'  │ [ '0x1a7e4e63778b4f12a199c062f3efdd288afcbce8', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    3    │ '0xb1cfdc7370550f5e421e1bf0bf3cadfadf3c4141' │ 'Ethereum' │ 'arrakis-finance' │   'DAI-FRAX'   │ 3253895.016873612  │ 0.046579722936264924 │  'https://beta.arrakis.finance/vaults/1/0xb1cfdc7370550f5e421e1bf0bf3cadfadf3c4141'  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f', '0x853d955acef822db058eb8505911ed77f175b99e' ] │
    │    4    │ '0xa199569af06cb68960869fe376c9b41f68d8e2d1' │ 'Polygon'  │ 'arrakis-finance' │ 'USDC-miMATIC' │ 2726340.693429563  │  1.4253617577550928  │ 'https://beta.arrakis.finance/vaults/137/0xa199569af06cb68960869fe376c9b41f68d8e2d1' │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174', '0xa3fa99a148fa48d14ed51d610c367c61876997f1' ] │
    │    5    │ '0x3d1556e84783672f2a3bd187a592520291442539' │ 'Ethereum' │ 'arrakis-finance' │   'DAI-FEI'    │  2671751.0386383   │  2.7147592888059457  │  'https://beta.arrakis.finance/vaults/1/0x3d1556e84783672f2a3bd187a592520291442539'  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f', '0x956f47f50a910163d8bf957cf5846d573e7f87ca' ] │
    │    6    │ '0x70535c46ce04181adf749f34b65b6365164d6b6e' │ 'Optimism' │ 'arrakis-finance' │  'WETH-LYRA'   │ 1635228.0481417384 │  0.6825648924243001  │ 'https://beta.arrakis.finance/vaults/10/0x70535c46ce04181adf749f34b65b6365164d6b6e'  │ [ '0x4200000000000000000000000000000000000006', '0x50c5725949a6f0c72e6c4a641f24049a917db0cb' ] │
    │    7    │ '0xac6705bc7f6a35eb194bdb89066049d6f1b0b1b5' │ 'Optimism' │ 'arrakis-finance' │ 'THALES-WETH'  │ 1299479.5076071355 │  0.9801253776750656  │ 'https://beta.arrakis.finance/vaults/10/0xac6705bc7f6a35eb194bdb89066049d6f1b0b1b5'  │ [ '0x217d47011b23bb961eb6d93ca9945b7501a5bb11', '0x4200000000000000000000000000000000000006' ] │
    │    8    │ '0x092a51b356930d907570efec1fc94f3c591b7239' │ 'Ethereum' │ 'arrakis-finance' │   'PAR-USDC'   │ 1079993.1312072908 │  1.6089218662623193  │  'https://beta.arrakis.finance/vaults/1/0x092a51b356930d907570efec1fc94f3c591b7239'  │ [ '0x68037790a0229e9ce6eaa8a99ea92964106c4703', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    9    │ '0xdcf0cb36e8e9d0607242e2e7babea5ba3395628f' │ 'Ethereum' │ 'arrakis-finance' │   'OGN-WETH'   │ 929900.1916941932  │          0           │  'https://beta.arrakis.finance/vaults/1/0xdcf0cb36e8e9d0607242e2e7babea5ba3395628f'  │ [ '0x8207c1ffc5b6804f6024322ccf34f29c3541ae26', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────┴────────────────┴────────────────────┴──────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Pull request merged**
