### PR TITLE
Change source of APY for HedgeFarm Alpha #2

### PR DESCRIPTION
**Pull request by tudorhedged**

### CODE REVIEW

**Comment by llamatester** [comment]
The hedgefarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.411 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬─────────────┬─────────┬───────────────┬────────────────────┬───────────────────┐
    │ (index) │                     pool                     │    chain    │   project   │ symbol  │    tvlUsd     │        apy         │     poolMeta      │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼─────────────┼─────────┼───────────────┼────────────────────┼───────────────────┤
    │    0    │ '0xdE4133f0CFA1a61Ba94EC64b6fEde4acC1fE929E' │ 'Avalanche' │ 'hedgefarm' │ 'USDC'  │ 289274.905011 │        7.53        │ '28 Days Lock-up' │
    │    1    │ '0x3C390b91Fc2f248E75Cd271e2dAbF7DcC955B1A3' │ 'Avalanche' │ 'hedgefarm' │ 'BTC.B' │ 33756.3421107 │ 1.5007438340408972 │                   │
    └─────────┴──────────────────────────────────────────────┴─────────────┴─────────────┴─────────┴───────────────┴────────────────────┴───────────────────┘

**Comment by llamatester** [comment]
The hedgefarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.456 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬─────────────┬─────────┬───────────────┬────────────────────┬───────────────────┐
    │ (index) │                     pool                     │    chain    │   project   │ symbol  │    tvlUsd     │        apy         │     poolMeta      │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼─────────────┼─────────┼───────────────┼────────────────────┼───────────────────┤
    │    0    │ '0xdE4133f0CFA1a61Ba94EC64b6fEde4acC1fE929E' │ 'Avalanche' │ 'hedgefarm' │ 'USDC'  │ 289274.905011 │        7.53        │ '28 Days Lock-up' │
    │    1    │ '0x3C390b91Fc2f248E75Cd271e2dAbF7DcC955B1A3' │ 'Avalanche' │ 'hedgefarm' │ 'BTC.B' │ 33756.3421107 │ 1.5007438340408972 │                   │
    └─────────┴──────────────────────────────────────────────┴─────────────┴─────────────┴─────────┴───────────────┴────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
gm. what does this change mean actually?

if the apy is based on inception date use -> `apyBaseInception`. `apy` should be based on a 1day performance window.
also, pls make sure that we display net values (after fees)
ty

**Comment by tudorhedged** [comment]
gm! this change actually displays the 1day performance window net values (after fees). let me know if I can be of any further help.

**Pull request merged**
