### PR TITLE
0vix mai maticx

### PR DESCRIPTION
**Pull request by chaoticgoodpanda**
Added VIX premining rewards APRs, as seen on 0vix.com. Values match those displayed on 0vix.com. Added the premining rewards contract and the rewards APRs.

### CODE REVIEW

**Comment by llamatester** [comment]
The 0vix adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       52 passed, 52 total
    Snapshots:   0 total
    Time:        0.402 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────────────────────────┬───────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │           symbol            │   chain   │         apy         │     apyReward      │                   rewardTokens                   │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────────────────────────┼───────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┤
    │    0    │ '0xEBb865Bf286e6eA8aBf5ac97e1b56A76530F3fBe' │ '0vix'  │    '0VIX USD Coin (PoS)'    │ 'polygon' │ 0.16502850607207353 │ 13.956845754723378 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 1397163.8250283496 │
    │    1    │ '0x1372c34acC14F1E8644C72Dad82E3a21C211729f' │ '0vix'  │   '0VIX (PoS) Tether USD'   │ 'polygon' │ 0.7957487878510694  │ 17.96974210257464  │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 1085157.4768680797 │
    │    2    │ '0x2175110F2936bf630a278660E9B6E4EFa358490A' │ '0vix'  │ '0VIX (PoS) Dai Stablecoin' │ 'polygon' │  0.657385403882893  │ 18.943618490100256 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 1029370.3924722988 │
    │    3    │ '0xb2D9646A1394bf784E376612136B3686e74A325F' │ '0vix'  │    '0VIX Wrapped Ether'     │ 'polygon' │ 0.6877221942292566  │ 21.19195061331091  │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 920160.6947758656  │
    │    4    │ '0xC57E5e261d49Af3026446de3eC381172f17bB799' │ '0vix'  │         '0VIX MAI'          │ 'polygon' │ 0.25805216441154855 │ 24.227506686993014 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 804870.2762496371  │
    │    5    │ '0x3B9128Ddd834cE06A60B0eC31CCfB11582d8ee18' │ '0vix'  │  '0VIX (PoS) Wrapped BTC'   │ 'polygon' │  1.289651940396408  │ 28.589204638737343 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 682075.6382140901  │
    │    6    │ '0xE554E874c9c60E45F1Debd479389C76230ae25A8' │ '0vix'  │        '0VIX MATIC'         │ 'polygon' │ 2.3323793701893525  │ 32.067087056074215 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 608100.1360024146  │
    │    7    │ '0xAAcc5108419Ae55Bc3588E759E28016d06ce5F40' │ '0vix'  │        '0VIX MaticX'        │ 'polygon' │ 0.7528029258915936  │ 37.61669505667362  │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 518386.84846239514 │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────────────────────────┴───────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
henlo sir, ty for making the changes. a few things:
- please revert the change in `beforeTests.js`
- we are working on some new features specifically for lending protocols, so it would be great if you could
add these additional fields:
```
totalSupplyUsd
totalBorrowUsd
apyBaseBorrow
apyRewardBorrow (if available)
ltv (loan to value/collateral factor) (if available)
```

pls lmk if unclear :)
ty

**Comment by chaoticgoodpanda** [comment]
Hi ser,

Thanks for your message. So with regards to `beforeTests.js`, I only changed it because the origin file (with the updated API) did not sync with my local git repo. See issue here: https://github.com/DefiLlama/yield-server/issues/324. Unsure if it's because you all put it in `.gitignore` or something.

Can add the other fields, however! Will generate a new PR.

**Comment by chaoticgoodpanda** [comment]
Also, I want to add these new fields you've requested, but I get this error when running tests. :) Maybe you want to update the test suite?

Screen Shot 2022-09-21 at 1 41 33 PM

**Comment by llamatester** [comment]
The 0vix adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       52 passed, 52 total
    Snapshots:   0 total
    Time:        0.453 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────────────────────────┬───────────┬─────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │           symbol            │   chain   │         apy         │   apyBaseBorrow    │     apyReward      │                   rewardTokens                   │   totalSupplyUsd   │   totalBorrowUsd   │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────────────────────────┼───────────┼─────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xEBb865Bf286e6eA8aBf5ac97e1b56A76530F3fBe' │ '0vix'  │    '0VIX USD Coin (PoS)'    │ 'polygon' │ 0.17410287017403103 │ 1.7780847329815996 │ 13.881935866228254 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 1231119.170277366  │ 173584.04892128214 │ 1404703.2191986481 │
    │    1    │ '0x2175110F2936bf630a278660E9B6E4EFa358490A' │ '0vix'  │ '0VIX (PoS) Dai Stablecoin' │ 'polygon' │ 0.5866503616477114  │ 3.2847115673775296 │ 18.212260628169467 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 850744.4075296005  │ 219962.87028294892 │ 1070707.2778125494 │
    │    2    │ '0x1372c34acC14F1E8644C72Dad82E3a21C211729f' │ '0vix'  │   '0VIX (PoS) Tether USD'   │ 'polygon' │ 0.8652754766743875  │ 4.0002965870318485 │ 18.67197772660569  │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 794911.5786135632  │ 249434.14016985535 │ 1044345.7187834185 │
    │    3    │ '0xb2D9646A1394bf784E376612136B3686e74A325F' │ '0vix'  │    '0VIX Wrapped Ether'     │ 'polygon' │ 0.5667643624340579  │ 3.2278241056751478 │ 21.023658499527293 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 739568.2122681214  │ 187958.26940672347 │ 927526.4816748449  │
    │    4    │ '0xC57E5e261d49Af3026446de3eC381172f17bB799' │ '0vix'  │         '0VIX MAI'          │ 'polygon' │ 0.35975377801487074 │ 2.5646571742306223 │ 21.821517920976078 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 743076.6520898142  │ 150536.71021691596 │ 893613.3623067301  │
    │    5    │ '0x3B9128Ddd834cE06A60B0eC31CCfB11582d8ee18' │ '0vix'  │  '0VIX (PoS) Wrapped BTC'   │ 'polygon' │ 1.1672760443032448  │ 4.657515596937278  │ 28.759758560760563 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 497022.7114927537  │ 181008.01532306682 │ 678030.7268158206  │
    │    6    │ '0xE554E874c9c60E45F1Debd479389C76230ae25A8' │ '0vix'  │        '0VIX MATIC'         │ 'polygon' │  2.998752566142393  │ 7.534057112399961  │ 31.748360260163018 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 388467.0136410245  │ 225737.93553451056 │  614204.949175535  │
    │    7    │ '0xAAcc5108419Ae55Bc3588E759E28016d06ce5F40' │ '0vix'  │        '0VIX MaticX'        │ 'polygon' │ 1.1497641591462715  │ 4.621852222032596  │ 31.830512422762524 │ [ '0x108ADA79428ea427E6A2175D3AB678abA2947a4a' ] │ 449973.27210761746 │ 162646.4602110877  │ 612619.7323187052  │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────────────────────────┴───────────┴─────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┘

**Comment by chaoticgoodpanda** [comment]
Just curious -- I can't see the new stats on Defi-Llama yet (e.g. `apybaseBorrow`, `apyReward`.) When might they Go-Live? Thanks!

Screen Shot 2022-09-22 at 10 48 35 AM

**Comment by chaoticgoodpanda** [comment]
Thanks for merging! Just a question -- why are our pools named "oUSDC" instead of "USDC" for all pools (https://defillama.com/yields?project=0vix)? We find this to be a bit inaccurate, since the yields earned are on USDC and not the oTokens, since the oTokens only serve as the user's receipt token.

Screen Shot 2022-09-23 at 6 33 57 PM

For example, for `aave`, they also have e.g. "aUSDC" tokens but you list them properly, i.e. as "USDC" (https://defillama.com/yields?project=aave-v2):

Screen Shot 2022-09-23 at 6 36 39 PM

Make you please drop the "o" from our pools and call them "USDC", "USDT", "MATIC" etc., as you do for `aave`? Thanks very much.

**Pull request merged**
