### PR TITLE
update fractal addresses, add camelot and chronos pools

### PR DESCRIPTION
**Pull request by adamxyzxyz**
unsure of whether to list the chronos and camelot pool under the fractal-protocol project name, or under their respective names.

if they need to be listed for chronos and camelot, how can I do that so that the symbol USDC-USDF appears on defi llama?

thanks

### CODE REVIEW

**Comment by llamatester** [comment]
The fractal-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.384 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────────┬─────────────┬────────────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain    │      project       │   symbol    │       tvlUsd       │        apy        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────────┼─────────────┼────────────────────┼───────────────────┤
    │    0    │ '0x3EAa4b3e8967c02cE1304C1EB35e8C5409838DFC' │ 'Ethereum' │ 'fractal-protocol' │   'USDC'    │ 3465723.2507586046 │         8         │
    │    1    │ '0x468B6e0f89fa727A47d9512021050797B4875D6d' │ 'Arbitrum' │ 'fractal-protocol' │ 'USDF-USDC' │ 116787.21775105425 │       21.52       │
    │    2    │ '0xf011B036934b58A619D2822d90ecd726126Efdf2' │ 'Arbitrum' │ 'fractal-protocol' │ 'USDF-USDC' │ 89757.09420695322  │ 62.29437810849126 │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────────┴─────────────┴────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
yeah these pools shouldn't be part of this adapter but should show up for the respective camelot and chronos adapters. i'll take a look and see why they aren't there

**Comment by slasher125** [comment]
we use coingeckos token list, but the amount of tokens is currently limited to top 1k by mcap, so if usdf is outside that range then it won't be searchable but the pools will be listed and visible

**Comment by adamxyzxyz** [comment]
I see, so what is the next step?

**Comment by slasher125** [comment]
have checked:
- the camelot pool is in the /pools api response, but doesn't show up on UI cause we filter out anything with 0 apyBase.
- have fixed the usdf pool for chronos so that will show up after next ui refresh

closing this

**Comment by adamxyzxyz** [comment]
@slasher125 I don't see the USDF pool for Chronos still

**Pull request closed without merging**
