### PR TITLE
Added lender APY adapter for Fringe Finance.

### PR DESCRIPTION
**Pull request by bondedcto**

### CODE REVIEW

**Comment by slasher125** [comment]
henlo,
a couple of requests:
- pls make use of on chain calls, we are moving away from centralised api's (see readme)
- i'd be great if you'd add the new lending protocol fields (see readme) so your project will show up under the new borrow specific pages

**Comment by bondedcto** [comment]
Thanks slasher125.

We're looking into onchain queries and the borrow-specific pages.

Question. Regarding the current API-based lender pull request, even though
we're looking into onchain, is DeFillama's intention to deploy the
API-based lender pull request in the meantime?

**Comment by slasher125** [comment]
well, we could. problem is if i merge now then u guys have less incentive making a change to on-chain calls/subgraphs right?  😄

Problem is that the majority of adapter failures are coming from centralised apis being down or having related issues.

**Comment by llamatester** [comment]
The fringe adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.436 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────┬──────────────┬─────────────────┬─────────────────┬──────────────────────────────────────────────────┬─────────────┐
    │ (index) │                     pool                     │   chain    │ project  │ symbol │    tvlUsd    │     apyBase     │       apy       │                 underlyingTokens                 │  poolMeta   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────┼──────────────┼─────────────────┼─────────────────┼──────────────────────────────────────────────────┼─────────────┤
    │    0    │ '0x9fD0928A09E8661945767E75576C912023bA384D' │ 'Ethereum' │ 'fringe' │ 'USDC' │ 20146.128898 │ 8.5846510075977 │ 8.5846510075977 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V1 market' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────┴──────────────┴─────────────────┴─────────────────┴──────────────────────────────────────────────────┴─────────────┘

**Comment by slasher125** [comment]
also, please remove the `apy` field. we calculate this server side

**Comment by bondedcto** [comment]
ok. I get it.
we're gonna do the direct contract calls as per DFL's preference. 

Meanwhile, I've removed the apy and submitted an updated PR. (We currently have pretty good lender APY atm and would love for that to be visible on DFL if it can go in before we finish the direct contract calls.)

**Comment by llamatester** [comment]
The fringe adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.337 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────┬──────────────┬─────────────────┬──────────────────────────────────────────────────┬─────────────┐
    │ (index) │                     pool                     │   chain    │ project  │ symbol │    tvlUsd    │     apyBase     │                 underlyingTokens                 │  poolMeta   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────┼──────────────┼─────────────────┼──────────────────────────────────────────────────┼─────────────┤
    │    0    │ '0x9fD0928A09E8661945767E75576C912023bA384D' │ 'Ethereum' │ 'fringe' │ 'USDC' │ 20146.128898 │ 8.5846510075977 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V1 market' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────┴──────────────┴─────────────────┴──────────────────────────────────────────────────┴─────────────┘

**Comment by slasher125** [comment]
k, i'll add it. pls update it to on chain in the meantime. its really mostly to the benefit of users and my own sanity when managing potential future bugs xD

**Comment by bondedcto** [comment]
The requested update for onchain calls are now included in
https://github.com/DefiLlama/yield-server/pull/496
Any residual sanity issues you may have will be due to other factors. 👌

**Pull request merged**
