### PR TITLE
GammaSwap: Add Rewards APY Calculations

### PR DESCRIPTION
**Pull request by 0xDanr**
-Adding logic to include rewards APY for incentivized pools in arbitrum
-Updated subgraph query urls

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207534839154415

### CODE REVIEW

**Comment by llamatester** [comment]
The gammaswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       291 passed, 291 total
    Snapshots:   0 total
    Time:        0.326 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬────────────────────────────┬────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │           symbol           │   tvlUsd   │       apyBase       │   apyBaseBorrow    │                   rewardTokens                   │     apyReward      │                                        underlyingTokens                                        │                                     url                                     │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼────────────────────────────┼────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │ 'Arbitrum' │ 'gammaswap' │        'weETH-USDC'        │ 1855767.95 │  4.291740455258018  │ 14.009447336281609 │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 106.20280867213862 │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │
    │    1    │ '0xcd4257699b48d4791e77116d0e6a3bd48ad9567f' │   'Base'   │ 'gammaswap' │        'WETH-USDC'         │ 1457649.96 │ 115.66218425732329  │ 121.44963457318153 │                        []                        │         0          │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │ 'https://app.gammaswap.com/earn/0xcd4257699b48d4791e77116d0e6a3bd48ad9567f' │
    │    2    │ '0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │ 'Arbitrum' │ 'gammaswap' │        'WETH-USDC'         │ 695453.08  │  1.287743742106819  │ 1.6366434909686665 │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 419.79532047712127 │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │
    │    3    │ '0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-weETH'        │ 393065.85  │ 3.4548863568995225  │ 12.65646704094942  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 86.79056009087037  │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe' ] │ 'https://app.gammaswap.com/earn/0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │
    │    4    │ '0x76597006bedf45fe441165811b2e79a35d045a7e' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-ezETH-27JUN2024' │ 306409.12  │ 1.1040422705940556  │ 2.1875899053355528 │                        []                        │         0          │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0x8EA5040d423410f1fdc363379Af88e1DB5eA1C34' ] │ 'https://app.gammaswap.com/earn/0x76597006bedf45fe441165811b2e79a35d045a7e' │
    │    5    │ '0xd7cfe0e2dd5773249442b055834207bc52849b1d' │ 'Arbitrum' │ 'gammaswap' │       'PENDLE-USDC'        │ 279950.91  │  5.975616118622335  │ 6.312956638519958  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │  559.329140562665  │ [ '0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/0xd7cfe0e2dd5773249442b055834207bc52849b1d' │
    │    6    │ '0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │ 'Arbitrum' │ 'gammaswap' │       'WETH-USDC.e'        │ 195967.57  │ 12.125546859885981  │ 19.708717985824688 │                        []                        │         0          │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://app.gammaswap.com/earn/0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │
    │    7    │ '0x679fc242cea26358026dae06bf7613384d0877bf' │   'Base'   │ 'gammaswap' │        'weETH-USDC'        │ 119209.49  │ 27.367887345278902  │ 50.19200024334608  │                        []                        │         0          │ [ '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │ 'https://app.gammaswap.com/earn/0x679fc242cea26358026dae06bf7613384d0877bf' │
    │    8    │ '0xc714a975042546c76fe2ef804d32adb2539292d8' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-USDC'         │  76522.24  │ 0.6496191912232409  │ 1.2200281031384457 │                        []                        │         0          │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/0xc714a975042546c76fe2ef804d32adb2539292d8' │
    │    9    │ '0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-weETH-26SEP2024' │  71548.71  │ 0.12054228724028633 │ 0.7889223139666985 │                        []                        │         0          │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xb8b0a120F6A68Dd06209619F62429fB1a8e92feC' ] │ 'https://app.gammaswap.com/earn/0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴────────────────────────────┴────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for the update
are the rewards veARB? if so then we need to remove these, we don't display vested rewards on our end

**Comment by llamatester** [comment]
The gammaswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       291 passed, 291 total
    Snapshots:   0 total
    Time:        0.343 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬────────────────────────────┬────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │           symbol           │   tvlUsd   │       apyBase       │   apyBaseBorrow    │                   rewardTokens                   │     apyReward      │                                        underlyingTokens                                        │                                         url                                          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼────────────────────────────┼────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │ 'Arbitrum' │ 'gammaswap' │        'weETH-USDC'        │ 1782095.14 │  4.121752916272043  │ 14.838128843592818 │ [ '0xA159463aB4B3aF3865bC9DC0FD28d943f2C048Ce' ] │ 108.20239845492631 │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │
    │    1    │ '0xcd4257699b48d4791e77116d0e6a3bd48ad9567f' │   'Base'   │ 'gammaswap' │        'WETH-USDC'         │ 1541003.51 │ 102.41399707693724  │ 107.54091417402915 │                        []                        │         0          │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │   'https://app.gammaswap.com/earn/base/0xcd4257699b48d4791e77116d0e6a3bd48ad9567f'   │
    │    2    │ '0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │ 'Arbitrum' │ 'gammaswap' │        'WETH-USDC'         │ 685850.67  │  4.545097195111237  │ 6.575958287840251  │ [ '0xA159463aB4B3aF3865bC9DC0FD28d943f2C048Ce' ] │ 394.1314476439404  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │
    │    3    │ '0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-weETH'        │ 400464.51  │  3.206145740806306  │ 12.57065950337144  │ [ '0xA159463aB4B3aF3865bC9DC0FD28d943f2C048Ce' ] │ 79.16883122812565  │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │
    │    4    │ '0x76597006bedf45fe441165811b2e79a35d045a7e' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-ezETH-27JUN2024' │ 288267.96  │  1.202539406360261  │ 2.1897654965723006 │                        []                        │         0          │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0x8EA5040d423410f1fdc363379Af88e1DB5eA1C34' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x76597006bedf45fe441165811b2e79a35d045a7e' │
    │    5    │ '0xd7cfe0e2dd5773249442b055834207bc52849b1d' │ 'Arbitrum' │ 'gammaswap' │       'PENDLE-USDC'        │ 272739.51  │ 10.900319208965128  │ 12.693057891958093 │ [ '0xA159463aB4B3aF3865bC9DC0FD28d943f2C048Ce' ] │  559.603977161638  │ [ '0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xd7cfe0e2dd5773249442b055834207bc52849b1d' │
    │    6    │ '0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │ 'Arbitrum' │ 'gammaswap' │       'WETH-USDC.e'        │ 191076.55  │ 12.819985259071377  │ 19.798165398984786 │                        []                        │         0          │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │
    │    7    │ '0x679fc242cea26358026dae06bf7613384d0877bf' │   'Base'   │ 'gammaswap' │        'weETH-USDC'        │ 116707.66  │ 27.235199615320465  │ 49.928489480130445 │                        []                        │         0          │ [ '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │   'https://app.gammaswap.com/earn/base/0x679fc242cea26358026dae06bf7613384d0877bf'   │
    │    8    │ '0xc714a975042546c76fe2ef804d32adb2539292d8' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-USDC'         │  75266.61  │ 1.5060327094174704  │ 1.6168521771952205 │                        []                        │         0          │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xc714a975042546c76fe2ef804d32adb2539292d8' │
    │    9    │ '0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-weETH-26SEP2024' │  71548.71  │ 0.10085950975491692 │ 0.757384721595986  │                        []                        │         0          │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xb8b0a120F6A68Dd06209619F62429fB1a8e92feC' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴────────────────────────────┴────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by 0xDanr** [comment]
Hi @slasher125 the rewards are escrowed ARB. So users have to vest the escrow ARB for 180 days to get the ARB reward. I changed the reward token to the escrow ARB token (different address from ARB). The escrow ARB token is an ERC20 token too.

Ok, I see the issues with the URL. I just updated it.

**Comment by llamatester** [comment]
The gammaswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       250 passed, 250 total
    Snapshots:   0 total
    Time:        0.312 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬────────────────────────────┬────────────┬─────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │           symbol           │   tvlUsd   │       apyBase       │   apyBaseBorrow    │                                        underlyingTokens                                        │                                         url                                          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼────────────────────────────┼────────────┼─────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │ 'Arbitrum' │ 'gammaswap' │        'weETH-USDC'        │ 1782095.14 │  4.057336619372147  │ 14.606224855912908 │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xd63c125b169bc5655f9fdefb47c7d33e622416c7' │
    │    1    │ '0xcd4257699b48d4791e77116d0e6a3bd48ad9567f' │   'Base'   │ 'gammaswap' │        'WETH-USDC'         │ 1538043.48 │ 102.19891936633965  │ 107.31512851579508 │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │   'https://app.gammaswap.com/earn/base/0xcd4257699b48d4791e77116d0e6a3bd48ad9567f'   │
    │    2    │ '0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │ 'Arbitrum' │ 'gammaswap' │        'WETH-USDC'         │ 685850.67  │  4.325117521195916  │ 6.544889274490336  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x04d24dbdd9ea6e8af5b5eb0126797da27498df1d' │
    │    3    │ '0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-weETH'        │ 400464.51  │ 3.1947821167943236  │ 12.526104991342448 │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x0817596ee3a3a11c892eaa0989e9e6f7a22c1fed' │
    │    4    │ '0x76597006bedf45fe441165811b2e79a35d045a7e' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-ezETH-27JUN2024' │ 288267.96  │ 1.2019232142533107  │  2.18959218875598  │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0x8EA5040d423410f1fdc363379Af88e1DB5eA1C34' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x76597006bedf45fe441165811b2e79a35d045a7e' │
    │    5    │ '0xd7cfe0e2dd5773249442b055834207bc52849b1d' │ 'Arbitrum' │ 'gammaswap' │       'PENDLE-USDC'        │ 272484.42  │  10.88003097414401  │ 12.681976073144183 │ [ '0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xd7cfe0e2dd5773249442b055834207bc52849b1d' │
    │    6    │ '0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │ 'Arbitrum' │ 'gammaswap' │       'WETH-USDC.e'        │ 191076.55  │ 12.812765714036026  │ 19.796378368948417 │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x63c531ffed7e17f8adca4ed490837838f6fa1b66' │
    │    7    │ '0x679fc242cea26358026dae06bf7613384d0877bf' │   'Base'   │ 'gammaswap' │        'weETH-USDC'        │ 116707.66  │ 27.235610100379485  │ 49.92924215778726  │ [ '0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │   'https://app.gammaswap.com/earn/base/0x679fc242cea26358026dae06bf7613384d0877bf'   │
    │    8    │ '0xc714a975042546c76fe2ef804d32adb2539292d8' │ 'Arbitrum' │ 'gammaswap' │        'WBTC-USDC'         │  75266.61  │ 1.4876361029870662  │ 1.597101880289977  │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://app.gammaswap.com/earn/arbitrum/0xc714a975042546c76fe2ef804d32adb2539292d8' │
    │    9    │ '0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │ 'Arbitrum' │ 'gammaswap' │ 'weETH-PT-weETH-26SEP2024' │  71548.71  │ 0.10080021617502495 │ 0.757241053102724  │ [ '0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe', '0xb8b0a120F6A68Dd06209619F62429fB1a8e92feC' ] │ 'https://app.gammaswap.com/earn/arbitrum/0x3018829a446de49aca6ca631fdaa67bac02d8dcd' │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴────────────────────────────┴────────────┴─────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by 0xDanr** [comment]
@slasher125 I disabled the apyRewards calculation after talking to 0xngmi. The logic is still there, I just turned going through it off with a false boolean in the if statement that calculates it. I want to keep it there because, given your requirements, we will most likely offer liquid incentives in the near future and will use the same logic.

Thank you

**Pull request merged**
