### PR TITLE
Adding hatom lending

### PR DESCRIPTION
**Pull request by amilcarrey**
I add 4 money markets for now, `USDT, USDC, WETH and BTC`. I'm apologise in advance for the amount of queries.

### CODE REVIEW

**Comment by slasher125** [comment]
ty for adding. what are the requirements to receive booster apy? we only display lower bound values, so if it requires additional lockups etc, then we need to remove that part

**Comment by amilcarrey** [comment]
@slasher125 the only requirement is have the 10% of your collateral staked in 'htm'.

**Comment by slasher125** [comment]
alright, lets remove the booster part then

**Comment by llamatester** [comment]
The hatom-lending adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.274 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬────────┬──────────────┬─────────────────┬────────┬────────────────────┬───────────┬────────────────────┬──────────────┐
    │ (index) │  pool  │    chain     │     project     │ symbol │       tvlUsd       │  apyBase  │     apyReward      │ rewardTokens │
    ├─────────┼────────┼──────────────┼─────────────────┼────────┼────────────────────┼───────────┼────────────────────┼──────────────┤
    │    0    │ 'WBTC' │ 'MultiversX' │ 'hatom-lending' │ 'WBTC' │ 3830230.0273334626 │ 0.112495  │ 2.2315043245615964 │  [ 'USDC' ]  │
    │    1    │ 'WETH' │ 'MultiversX' │ 'hatom-lending' │ 'WETH' │ 2551769.1262073545 │ 0.221855  │ 3.147400743477092  │  [ 'USDC' ]  │
    │    2    │ 'USDC' │ 'MultiversX' │ 'hatom-lending' │ 'USDC' │ 425010.2966507436  │ 28.880747 │ 3.421816171850339  │  [ 'USDC' ]  │
    │    3    │ 'USDT' │ 'MultiversX' │ 'hatom-lending' │ 'USDT' │ 259189.24614442544 │ 28.473557 │ 5.5653732163783545 │  [ 'USDC' ]  │
    └─────────┴────────┴──────────────┴─────────────────┴────────┴────────────────────┴───────────┴────────────────────┴──────────────┘

**Pull request merged**
