### PR TITLE
Add Tranchess qETH yield server

### PR DESCRIPTION
**Pull request by bill-clippy**

### CODE REVIEW

**Comment by llamatester** [comment]
The tranchess-ether adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────────┬────────┬──────────┬─────┐
    │ (index) │                         pool                          │   chain    │      project      │ symbol │  tvlUsd  │ apy │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────────┼────────┼──────────┼─────┤
    │    0    │ '0x93ef1ea305d11a9b2a3ebb9bb4fcc34695292e7d-ethereum' │ 'Ethereum' │ 'tranchess-ether' │ 'QETH' │ 10652833 │ 4.1 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────────┴────────┴──────────┴─────┘

**Comment by slasher125** [comment]
ty for adding. 
- pls remove the api call and use the on chain code instead
- no need to round apy
- tvl should be coming from on chain too

**Comment by bill-clippy** [comment]
@slasher125 Thanks for the suggestions. May I ask how should we calculate usd tvl using only on chain data?

**Comment by bill-clippy** [comment]
@slasher125 I've made the changes, but looks like the UTs failed. Any insight what could have caused the problem? The tests passed on my local machines.

**Comment by llamatester** [comment]
The tranchess-ether adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.39 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────────┬────────┬────────────────────┬───────────────────┐
    │ (index) │                         pool                          │   chain    │      project      │ symbol │       tvlUsd       │        apy        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────────┼────────┼────────────────────┼───────────────────┤
    │    0    │ '0x93ef1ea305d11a9b2a3ebb9bb4fcc34695292e7d-ethereum' │ 'Ethereum' │ 'tranchess-ether' │ 'QETH' │ 10002273.548104351 │ 4.095700605424367 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────────┴────────┴────────────────────┴───────────────────┘

**Pull request merged**
