### PR TITLE
add base configs

### PR DESCRIPTION
**Pull request by LeeRyanj**

### CODE REVIEW

**Comment by slasher125** [comment]
@LeeRyanj new route returns a 403

**Comment by LeeRyanj** [comment]
> @LeeRyanj new route returns a 403

how to fix it

**Comment by LeeRyanj** [comment]
> > @LeeRyanj new route returns a 403
> 
> how to fix it

**Comment by LeeRyanj** [comment]
> @LeeRyanj new route returns a 403

@slasher125 how to fix it

**Comment by llamatester** [comment]
The kiloex adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       184 passed, 184 total
    Snapshots:   0 total
    Time:        0.336 s
    Ran all test suites.
    
    Nb of pools: 30
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────┬──────────────────────────────────────────────┬─────────┬────────────────────┬─────────┬──────────────────────────────────────────────────┐
    │ (index) │   chain    │ project  │                     pool                     │ symbol  │       tvlUsd       │ apyBase │                 underlyingTokens                 │
    ├─────────┼────────────┼──────────┼──────────────────────────────────────────────┼─────────┼────────────────────┼─────────┼──────────────────────────────────────────────────┤
    │    0    │  'op_bnb'  │ 'kiloex' │ '0x9e5aac1ba1a2e6aed6b32689dfcf62a509ca96f3' │ 'USDT'  │ 11010869.351775317 │  0.73   │ [ '0x9e5aac1ba1a2e6aed6b32689dfcf62a509ca96f3' ] │
    │    1    │  'manta'   │ 'kiloex' │ '0x95cef13441be50d20ca4558cc0a27b601ac544e5' │ 'MANTA' │ 8161590.198502012  │   0.1   │ [ '0x95cef13441be50d20ca4558cc0a27b601ac544e5' ] │
    │    2    │  'manta'   │ 'kiloex' │ '0xf417f5a458ec102b90352f697d6e2ac3a3d2851f' │ 'USDT'  │ 4520433.649861508  │   0.2   │ [ '0xf417f5a458ec102b90352f697d6e2ac3a3d2851f' ] │
    │    3    │   'bsc'    │ 'kiloex' │ '0x55d398326f99059ff775485246999027b3197955' │ 'USDT'  │ 1194853.8825721417 │  2.77   │ [ '0x55d398326f99059ff775485246999027b3197955' ] │
    │    4    │  'op_bnb'  │ 'kiloex' │ '0x7c6b91d9be155a6db01f749217d76ff02a7227f2' │ 'BTCB'  │ 712930.0382027033  │  0.44   │ [ '0x7c6b91d9be155a6db01f749217d76ff02a7227f2' ] │
    │    5    │  'op_bnb'  │ 'kiloex' │ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb' │ 'FDUSD' │ 552202.7962081823  │  0.68   │ [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb' ] │
    │    6    │   'base'   │ 'kiloex' │ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' │ 'USDC'  │ 405247.0096458252  │  15.04  │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │
    │    7    │  'op_bnb'  │ 'kiloex' │ '0x4200000000000000000000000000000000000006' │ 'WBNB'  │ 360937.3138071596  │  0.44   │ [ '0x4200000000000000000000000000000000000006' ] │
    │    8    │ 'bsquared' │ 'kiloex' │ '0x681202351a488040fa4fdcc24188afb582c9dd62' │ 'USDT'  │ 283521.63421775756 │  19.46  │ [ '0x681202351a488040fa4fdcc24188afb582c9dd62' ] │
    │    9    │  'taiko'   │ 'kiloex' │ '0x07d83526730c7438048d55a4fc0b850e2aab6f0b' │ 'USDC'  │ 194023.4099065477  │  7.46   │ [ '0x07d83526730c7438048d55a4fc0b850e2aab6f0b' ] │
    └─────────┴────────────┴──────────┴──────────────────────────────────────────────┴─────────┴────────────────────┴─────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request closed without merging**
