### PR TITLE
Add R Savings Rate (Raft) from Base

### PR DESCRIPTION
**Pull request by iamvukasin**

### CODE REVIEW

**Comment by llamatester** [comment]
The raft adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.454 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────┬────────────┬──────────────────┬─────┬──────────┐
    │ (index) │                     pool                     │ project │ symbol │   chain    │     poolMeta     │ apy │  tvlUsd  │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────┼────────────┼──────────────────┼─────┼──────────┤
    │    0    │ '0x2ba26baE6dF1153e29813d7f926143f9c94402f3' │ 'raft'  │  'R'   │ 'ethereum' │ 'R Savings Rate' │  7  │ 10838925 │
    │    1    │ '0xA5b3FEe253f9DE67201dC8572Bd2CbB4a81c1bEc' │ 'raft'  │  'R'   │   'base'   │ 'R Savings Rate' │  7  │    12    │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────┴────────────┴──────────────────┴─────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The raft adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.51 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────┬────────────┬──────────────────┬─────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │ symbol │   chain    │     poolMeta     │       apy       │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────┼────────────┼──────────────────┼─────────────────┼────────────────────┤
    │    0    │ '0x2ba26baE6dF1153e29813d7f926143f9c94402f3' │ 'raft'  │  'R'   │ 'ethereum' │ 'R Savings Rate' │ 7.9999999977888 │ 10877354.012824563 │
    │    1    │ '0xA5b3FEe253f9DE67201dC8572Bd2CbB4a81c1bEc' │ 'raft'  │  'R'   │   'base'   │ 'R Savings Rate' │ 7.9999999977888 │ 519.8021359513197  │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────┴────────────┴──────────────────┴─────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The raft adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.56 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────┬────────────┬──────────────────┬─────────────────┬────────────────────┐
    │ (index) │                     pool                     │ project │ symbol │   chain    │     poolMeta     │       apy       │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────┼────────────┼──────────────────┼─────────────────┼────────────────────┤
    │    0    │ '0x2ba26baE6dF1153e29813d7f926143f9c94402f3' │ 'raft'  │  'R'   │ 'ethereum' │ 'R Savings Rate' │ 7.9999999977888 │ 12445765.53526657  │
    │    1    │ '0xA5b3FEe253f9DE67201dC8572Bd2CbB4a81c1bEc' │ 'raft'  │  'R'   │   'base'   │ 'R Savings Rate' │ 7.9999999977888 │ 1523.6242406441627 │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────┴────────────┴──────────────────┴─────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by 0xngmi** [comment]
instead of using ethers with your hardcoded rpcs, why not keep using our sdk like the adapter was doing before?

**Comment by iamvukasin** [comment]
I wanted to use that, but it fails with a cryptic error for Base. It's a bit hard to debug it since the error message is not that helpful for me (`call` cannot be found for `undefined`).

**Comment by llamatester** [comment]
Error while running raft adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       9 failed, 5 passed, 14 total
    Snapshots:   0 total
    Time:        0.347 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────┐
    │ (index) │    0     │
    ├─────────┼──────────┤
    │    0    │ [Object] │
    │    1    │ [Object] │
    └─────────┴──────────┘
    }

**Comment by llamatester** [comment]
The raft adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.348 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬─────────┬────────┬────────────┬──────────────────┬─────────────────┬───────────────────┐
    │ (index) │                         pool                          │ project │ symbol │   chain    │     poolMeta     │       apy       │      tvlUsd       │
    ├─────────┼───────────────────────────────────────────────────────┼─────────┼────────┼────────────┼──────────────────┼─────────────────┼───────────────────┤
    │    0    │ '0x2ba26bae6df1153e29813d7f926143f9c94402f3-ethereum' │ 'raft'  │  'R'   │ 'Ethereum' │ 'R Savings Rate' │ 7.9999999977888 │ 7210793.979311508 │
    │    1    │   '0xa5b3fee253f9de67201dc8572bd2cbb4a81c1bec-base'   │ 'raft'  │  'R'   │   'Base'   │ 'R Savings Rate' │ 7.9999999977888 │ 23855.84408235174 │
    └─────────┴───────────────────────────────────────────────────────┴─────────┴────────┴────────────┴──────────────────┴─────────────────┴───────────────────┘

**Comment by iamvukasin** [comment]
@0xngmi I realized I had to use SDK v4 for Base support. Updated the PR as requested.

**Comment by llamatester** [comment]
The raft adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.318 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬─────────┬────────┬────────────┬──────────────────┬─────────────────┬───────────────────┐
    │ (index) │                         pool                          │ project │ symbol │   chain    │     poolMeta     │       apy       │      tvlUsd       │
    ├─────────┼───────────────────────────────────────────────────────┼─────────┼────────┼────────────┼──────────────────┼─────────────────┼───────────────────┤
    │    0    │ '0x2ba26bae6df1153e29813d7f926143f9c94402f3-ethereum' │ 'raft'  │  'R'   │ 'Ethereum' │ 'R Savings Rate' │ 7.9999999977888 │ 7121451.818336875 │
    │    1    │   '0xa5b3fee253f9de67201dc8572bd2cbb4a81c1bec-base'   │ 'raft'  │  'R'   │   'Base'   │ 'R Savings Rate' │ 7.9999999977888 │ 23863.94847258222 │
    └─────────┴───────────────────────────────────────────────────────┴─────────┴────────┴────────────┴──────────────────┴─────────────────┴───────────────────┘

**Pull request merged**
