### PR TITLE
Add Yama Finance Lending Adapter

### PR DESCRIPTION
**Pull request by zero-goliath**

### CODE REVIEW

**Comment by 0xngmi** [comment]
how is apy calculated? can you calculate it from on-chain data rather than pulling it from an api?

**Comment by llamatester** [comment]
The yama-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.32 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬────────┬────────────────────┬───────┬─────────┬──────────────────────────────────────────────────┬───────────────┐
    │ (index) │                         pool                          │   chain    │    project     │ symbol │       tvlUsd       │  apy  │ apyBase │                 underlyingTokens                 │   poolMeta    │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼────────┼────────────────────┼───────┼─────────┼──────────────────────────────────────────────────┼───────────────┤
    │    0    │ '0x3296EE4Fa62D0D78B1999617886E969a22653383-arbitrum' │ 'Arbitrum' │ 'yama-finance' │ 'USDT' │ 1369647.6053060573 │ 21.07 │  21.07  │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │ 'USDT PSM LP' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴────────┴────────────────────┴───────┴─────────┴──────────────────────────────────────────────────┴───────────────┘

**Comment by zero-goliath** [comment]
> how is apy calculated? can you calculate it from on-chain data rather than pulling it from an api?

It is calculated by averaging the historical APY of approximately the past week.

Here is a sample code snippet that would calculate it on-chain. However, it reverts because the simulated call is too far into the past. Even calculating historical APY for a day doesn't work. This might have to do with the fact that about 4 blocks/second are produced on Arbitrum.

```js
const sdk = require('@defillama/sdk');
const utils = require('../utils');
const abiLockup = require('./abiLockup');

const main = async () => {
    const latestBlock = await sdk.api.util.getLatestBlock('arbitrum');

    const BLOCKS_IN_WEEK = 2419200;
    const WEEKS_IN_YEAR = 52;

    console.log(latestBlock.number);
    console.log(latestBlock.timestamp);

    const oldBlockHeight = latestBlock.number - BLOCKS_IN_WEEK;
    console.log(oldBlockHeight);

    const valueOld = (
        await sdk.api.abi.call({
            target: '0x3296EE4Fa62D0D78B1999617886E969a22653383',
            abi: abiLockup.find((m) => m.name === 'value'),
            chain: 'arbitrum',
            block: oldBlockHeight
        })
    ).output / (10 ** 18);

    const totalSupply = (
        await sdk.api.abi.call({
            target: '0x3296EE4Fa62D0D78B1999617886E969a22653383',
            abi: abiLockup.find((m) => m.name === 'totalSupply'),
            chain: 'arbitrum'
        })
    ).output / (10 ** 18);

    const value = (
        await sdk.api.abi.call({
            target: '0x3296EE4Fa62D0D78B1999617886E969a22653383',
            abi: abiLockup.find((m) => m.name === 'value'),
            chain: 'arbitrum'
        })
    ).output / (10 ** 18);

    console.log(value);
    console.log(valueOld);

    const apy = (((value / valueOld) ** WEEKS_IN_YEAR) - 1) * 100;

    return [{
        pool: '0x3296EE4Fa62D0D78B1999617886E969a22653383-arbitrum',
        chain: utils.formatChain('arbitrum'),
        project: 'yama-finance',
        symbol: utils.formatSymbol('USDT'),
        tvlUsd: totalSupply * value,
        apy: apy,
        apyBase: apy,
        underlyingTokens: ['0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'],
        poolMeta: 'USDT PSM LP'
    }]
};

module.exports = {
    timetravel: false,
    apy: main,
    url: 'https://yama.finance/app/lend',
}
```

**Comment by 0xngmi** [comment]
are there no archive nodes in arbitrum?

**Comment by zero-goliath** [comment]
> are there no archive nodes in arbitrum?

All the public nodes are full nodes, so I can't do it solely from this PR (because this is a public repo).

However, if you guys set the ARBITRUM_RPC environment variable to Alchemy or another archive node, the code works. Let me know if that's a viable option and I can commit the new code to our branch.

**Comment by slasher125** [comment]
@zero-goliath hey, ty for adding.
i'll set the env variable so we can use that, pls change the code to on chain calls. also, i just compared the output from the api vs on chain and nbs are different:
- api: 
``` 
{
    pool: '0x3296EE4Fa62D0D78B1999617886E969a22653383-arbitrum',
    chain: 'Arbitrum',
    project: 'yama-finance',
    symbol: 'USDT',
    tvlUsd: 1408637.7316416577,
    apy: 21.07,
    apyBase: 21.07,
    underlyingTokens: [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ],
    poolMeta: 'USDT PSM LP'
  }
```

vs on chain:
```
  {
    pool: '0x3296EE4Fa62D0D78B1999617886E969a22653383-arbitrum',
    chain: 'Arbitrum',
    project: 'yama-finance',
    symbol: 'USDT',
    tvlUsd: 1408637.7316416577,
    apy: 14.646638550392987,
    apyBase: 14.646638550392987,
    underlyingTokens: [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ],
    poolMeta: 'USDT PSM LP'
  }
```

also, u can remove the `apy` field, apyBase is sufficient

**Comment by zero-goliath** [comment]
@slasher125 Thanks for getting back, I just pushed the commit. the deviation is due to differing time periods during which APY was calculated. API price was calculated specifically between March 31st and April 6th, whereas the new algorithm calculates it for the 24 hours preceding the current time.

**Comment by slasher125** [comment]
hmm, blockOld is from 7days ago, not 24h. btw, lets should change the window to 24h, so apyBase 24h and also add apyBase7d for 7day lookback.

**Comment by zero-goliath** [comment]
> hmm, blockOld is from 7days ago, not 24h. btw, lets should change the window to 24h, so apyBase 24h and also add apyBase7d for 7day lookback.

@slasher125 noted, fixed in the latest commit

**Pull request merged**
