### PR TITLE
Added Clave ZK Pool for indexing

### PR DESCRIPTION
**Pull request by asgarovf**
## What is Clave?

Clave is an easy-to-use, non-custodial smart wallet powered by Account Abstraction and the hardware-level security elements (e.g., Secure Enclave, Android Trustzone, etc.) to simplify the onchain experience for the next billions. By empowering users with a user-friendly and secure bridge to seamlessly integrate their assets into everyday life, Clave delivers a comprehensive fintech solution, ensuring a holistic financial experience for all.

## Pool Details

Staking Address: `0x9248F1Ee8cBD029F3D22A92EB270333a39846fB2`
Staking Token: `ZK`
Current APR: `6.29%`

### CODE REVIEW

**Comment by llamatester** [comment]
The clave adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.253 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬─────────┬────────┬────────────────────┬───────────────────┐
    │ (index) │    pool    │    chain     │ project │ symbol │       tvlUsd       │      apyBase      │
    ├─────────┼────────────┼──────────────┼─────────┼────────┼────────────────────┼───────────────────┤
    │    0    │ 'clave-zk' │ 'zkSync Era' │ 'clave' │  'ZK'  │ 1012567.0299429264 │ 6.292104435159334 │
    └─────────┴────────────┴──────────────┴─────────┴────────┴────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
gm, pls use apyReward instead of apyBase (apyBase = protocol earnings/real yield)

**Comment by llamatester** [comment]
The clave adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.255 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬─────────┬────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │    pool    │    chain     │ project │ symbol │       tvlUsd       │     apyReward      │                   rewardTokens                   │
    ├─────────┼────────────┼──────────────┼─────────┼────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ 'clave-zk' │ 'zkSync Era' │ 'clave' │  'ZK'  │ 1084617.0309920774 │ 6.1656999050468055 │ [ '0x5a7d6b2f92c77fad6ccabd7ee0624e64907eaf3e' ] │
    └─────────┴────────────┴──────────────┴─────────┴────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Comment by aalimsahin** [comment]
@slasher125 thanks for the feedback. I updated the PR.

**Pull request merged**
