### PR TITLE
IPOR liquidity mining power up from contracts

### PR DESCRIPTION
**Pull request by kris-ipor**
Hi,
we modified our liquidity mining rewards, so to avoid future changes related to rewards, i'm reading it now from contract.
Also i have removed code related to additional airdrop for our liquidity providers, because it's finished.

### CODE REVIEW

**Comment by llamatester** [comment]
The ipor-derivatives adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.304 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────────┬──────────┬────────────────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │      project       │  symbol  │       tvlUsd       │      apyBase      │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────────┼──────────┼────────────────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x8537b194bff354c4738e9f3c81d67e3371dadaf8-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'DAI'   │ 1184658.5677495706 │    4.61977176     │ 1.092275804793692  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    1    │ '0x7c0e72f431fd69560d951e4c04a4de3657621a88-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDC'  │ 1109806.1089540399 │    4.77687192     │ 0.9824967476910008 │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    2    │ '0x9bd2177027edee300dc9f1fb88f24db6e5e1edc6-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDT'  │ 1012420.2272550233 │    5.52198228     │ 0.8473362332792427 │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    3    │ '0xc40431b6c510aeb45fbb5e21e40d49f12b0c1f0c-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'stETH'  │ 869003.7608508369  │    5.20387764     │ 1.134106086899915  │ [ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    4    │ '0x485cac13e6492ccf4d47764b0e4e07b5272b0167-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDC'  │ 788454.2309290146  │    8.28126684     │ 0.8725272946047586 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    5    │ '0xbda4b3e17a9b0ecb811e68c6f08907156cba503c-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │ 'wstETH' │ 711998.1285883904  │     9.255375      │  1.17719215376703  │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    6    │ '0xac5b04988bc71bee96f8d93040777db3ef166125-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'weETH'  │ 564921.1394365197  │    3.90754248     │ 0.8864999559613438 │ [ '0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    7    │ '0x4a319901c17748a637c2e0c4902f071fa1fd79bc-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDM'  │ 139772.6369246974  │ 7.510875226072358 │  1.0094255065981   │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    8    │ '0x9ac5092e027f0d9f24b4a1065c70973f3afda4cb-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDM'  │ 0.9220273760340782 │ 4.903384591802205 │        NaN         │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────────┴──────────┴────────────────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The ipor-derivatives adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.294 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────────┬──────────┬────────────────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │      project       │  symbol  │       tvlUsd       │      apyBase      │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────────┼──────────┼────────────────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x8537b194bff354c4738e9f3c81d67e3371dadaf8-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'DAI'   │ 1184155.7927161031 │    4.61912796     │ 1.092739588723071  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    1    │ '0x7c0e72f431fd69560d951e4c04a4de3657621a88-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDC'  │ 1109971.5159266626 │    4.77653304     │ 0.9707990376771984 │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    2    │ '0x9bd2177027edee300dc9f1fb88f24db6e5e1edc6-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDT'  │ 1012985.6494491067 │    5.52181968     │ 0.8468632876189914 │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    3    │ '0xc40431b6c510aeb45fbb5e21e40d49f12b0c1f0c-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'stETH'  │ 866931.4456204664  │    5.20375656     │ 1.1368170570802372 │ [ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    4    │ '0x485cac13e6492ccf4d47764b0e4e07b5272b0167-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDC'  │ 788571.8541176072  │    8.28128928     │ 0.8723971486428025 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    5    │ '0xbda4b3e17a9b0ecb811e68c6f08907156cba503c-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │ 'wstETH' │ 711647.7552817522  │    9.25535472     │ 1.177771733627073  │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    6    │ '0xac5b04988bc71bee96f8d93040777db3ef166125-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'weETH'  │ 564921.1394365197  │    3.90754248     │ 0.8864999559613438 │ [ '0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    7    │ '0x4a319901c17748a637c2e0c4902f071fa1fd79bc-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDM'  │ 139772.6369246974  │ 7.510875226072358 │  1.0094255065981   │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    8    │ '0x9ac5092e027f0d9f24b4a1065c70973f3afda4cb-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDM'  │ 0.9220273760340782 │ 4.903384591802205 │        NaN         │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────────┴──────────┴────────────────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
- we only display unboosted yields
- pls change the urls too, they seem to be broken

**Comment by kris-ipor** [comment]
ok, new url added

**Comment by llamatester** [comment]
The ipor-derivatives adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.292 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────────┬──────────┬────────────────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │      project       │  symbol  │       tvlUsd       │      apyBase      │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────────┼──────────┼────────────────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x8537b194bff354c4738e9f3c81d67e3371dadaf8-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'DAI'   │ 1183911.8353913855 │    4.61196444     │ 1.115643522364312  │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    1    │ '0x7c0e72f431fd69560d951e4c04a4de3657621a88-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDC'  │ 1108753.6123292383 │    4.77262932     │ 0.992031403905899  │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    2    │ '0x9bd2177027edee300dc9f1fb88f24db6e5e1edc6-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDT'  │ 1012007.3107516207 │    5.54467644     │ 0.8572721575696586 │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    3    │ '0xc40431b6c510aeb45fbb5e21e40d49f12b0c1f0c-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'stETH'  │ 865834.1950935816  │    5.22325128     │ 1.1619112988068283 │ [ '0xae7ab96520de3a18e5e111b5eaab095312d7fe84' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    4    │ '0x485cac13e6492ccf4d47764b0e4e07b5272b0167-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDC'  │ 787707.8541119427  │    8.28153792     │ 0.8914759487413134 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    5    │ '0xbda4b3e17a9b0ecb811e68c6f08907156cba503c-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │ 'wstETH' │ 709695.3436421973  │    9.30867456     │ 1.2055228171922898 │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    6    │ '0xac5b04988bc71bee96f8d93040777db3ef166125-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │ 'weETH'  │ 559438.6721191054  │    3.96683292     │ 0.9119950585401158 │ [ '0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    │    7    │ '0x4a319901c17748a637c2e0c4902f071fa1fd79bc-arbitrum' │ 'Arbitrum' │ 'ipor-derivatives' │  'USDM'  │ 139769.05787672172 │ 7.510234043916317 │ 1.0303972531614116 │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │
    │    8    │ '0x9ac5092e027f0d9f24b4a1065c70973f3afda4cb-ethereum' │ 'Ethereum' │ 'ipor-derivatives' │  'USDM'  │  0.92200376640428  │ 4.90263229691362  │        NaN         │ [ '0x59d9356e565ab3a36dd77763fc0d87feaf85508c' ] │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────────┴──────────┴────────────────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
what i meant are the specific pool urls like; https://app.ipor.io/zap/ethereum/dai

lets remove the url from the export and add url fields to the pool objects instead

**Comment by kris-ipor** [comment]
ok, understand now, i will change it

**Comment by kris-ipor** [comment]
ok, i have added urls for each pool, for USDM on ethereum url is not working, because this pool is paused on our side and as i see is filtered out on your side, because of low tvl

**Pull request merged**
