### PR TITLE
Add Stride yield adapter

### PR DESCRIPTION
**Pull request by srph**

### CODE REVIEW

**Comment by llamatester** [comment]
The stride adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.347 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────┬──────────┬──────────┬────────┬─────────────┬─────────────┬─────────────┐
    │ (index) │       pool       │  chain   │ project  │ symbol │  poolMeta   │   tvlUsd    │     apy     │
    ├─────────┼──────────────────┼──────────┼──────────┼────────┼─────────────┼─────────────┼─────────────┤
    │    0    │ '803-30074-STRD' │ 'Stride' │ 'stride' │ 'STRD' │ '14 day(s)' │ 7414123.064 │ 27.55379066 │
    │    1    │ '833-29900-STRD' │ 'Stride' │ 'stride' │ 'STRD' │ '14 day(s)' │ 1834149.154 │ 66.83056267 │
    │    2    │ '806-29683-OSMO' │ 'Stride' │ 'stride' │ 'OSMO' │ '14 day(s)' │ 416198.5425 │ 90.46682363 │
    │    3    │ '810-30104-STRD' │ 'Stride' │ 'stride' │ 'STRD' │ '14 day(s)' │ 413113.9152 │ 17.89193269 │
    │    4    │ '817-29965-STRD' │ 'Stride' │ 'stride' │ 'STRD' │ '14 day(s)' │ 195531.0234 │ 31.34469862 │
    └─────────┴──────────────────┴──────────┴──────────┴────────┴─────────────┴─────────────┴─────────────┘

**Comment by slasher125** [comment]
hi, q: what is the difference btw the pool index 0, 1? both are stride liquid staking and have the same 14days period?

**Comment by srph** [comment]
@slasher125 Pool index 0 ([here](https://app.osmosis.zone/pool/803)) is ATOM/stATOM, while Pool index 1 ([here](https://app.osmosis.zone/pool/833)) is stOSMO/OSMO.

**Comment by slasher125** [comment]
ok, but in that case the symbols are wrong yes? cause right now all i see is STRD or OSMO

**Comment by srph** [comment]
Ahh, gotcha - good catch. I see what you mean now.

Given the pool lets you lock up stATOM/ATOM, should `symbol` include both of these including the incentives (STRD)? (e.g., `ATOM-stATOM-STRD`) or just `ATOM`?

**Comment by slasher125** [comment]
the incentives are not part of the symbol. symbol is just the deposit token(s) basically (best to take a look at the UI if unclear)
if you have incentives, please split out the apy into underlying components, `apyBase` and/or `apyReward`. u can then remove the apy field (we calculate sums server side)

**Comment by srph** [comment]
Thanks @slasher125 - we'll try to include those in the future.

I just updated the pool symbol values - let me know if I got it right this time.

**Comment by llamatester** [comment]
Error while running stride adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 28 passed, 29 total
    Snapshots:   0 total
    Time:        0.353 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────┬──────────┬──────────┬─────────────────┬─────────────┬─────────────┬─────────────┐
    │ (index) │       pool       │  chain   │ project  │     symbol      │  poolMeta   │   tvlUsd    │     apy     │
    ├─────────┼──────────────────┼──────────┼──────────┼─────────────────┼─────────────┼─────────────┼─────────────┤
    │    0    │ '803-30074-STRD' │ 'Stride' │ 'stride' │  'STATOM-ATOM'  │ '14 day(s)' │ 7753902.64  │ 28.16998713 │
    │    1    │ '806-29683-OSMO' │ 'Stride' │ 'stride' │   'STRD-OSMO'   │ '14 day(s)' │ 437992.2125 │ 87.5152535  │
    │    2    │ '810-30104-STRD' │ 'Stride' │ 'stride' │ 'STSTARS-STARS' │ '14 day(s)' │ 411865.8338 │ 17.53606362 │
    │    3    │ '810-30104-STRD' │ 'Stride' │ 'stride' │ 'STSTARS-STARS' │ '14 day(s)' │ 405510.8146 │ 19.48904175 │
    │    4    │ '817-29965-STRD' │ 'Stride' │ 'stride' │  'STJUNO-JUNO'  │ '14 day(s)' │ 196379.3807 │ 33.36950258 │
    └─────────┴──────────────────┴──────────┴──────────┴─────────────────┴─────────────┴─────────────┴─────────────┘
    }

**Comment by slasher125** [comment]
best to run the local tests to catch errors like the current one. you can test via `npm run test --adapter=stride`
the test fails cause pool values must be unique. also index2,3 have identical symbols and metadata. whats the difference btw these two pools?

**Comment by srph** [comment]
We should only have 4 pools now - something probably changed from our data source. Should be fixed now.

```tsx
Test Suites: 1 passed, 1 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        0.453 s, estimated 1 s
Ran all test suites.

Nb of pools: 4


Sample pools: [
  {
    pool: '803-30074-STRD',
    chain: 'Stride',
    project: 'stride',
    symbol: 'STATOM-ATOM',
    poolMeta: '14 day(s)',
    tvlUsd: 7788348.365,
    apy: 28.61822113
  },
  {
    pool: '806-29683-OSMO',
    chain: 'Stride',
    project: 'stride',
    symbol: 'STRD-OSMO',
    poolMeta: '14 day(s)',
    tvlUsd: 444135.3183,
    apy: 86.13505254
  },
  {
    pool: '810-30104-STRD',
    chain: 'Stride',
    project: 'stride',
    symbol: 'STSTARS-STARS',
    poolMeta: '14 day(s)',
    tvlUsd: 411439.6387,
    apy: 19.60052972
  },
  {
    pool: '817-29965-STRD',
    chain: 'Stride',
    project: 'stride',
    symbol: 'STJUNO-JUNO',
    poolMeta: '14 day(s)',
    tvlUsd: 192431.2689,
    apy: 34.74969421
  }
]
```

**Comment by llamatester** [comment]
The stride adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       24 passed, 24 total
    Snapshots:   0 total
    Time:        0.49 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────┬──────────┬──────────┬─────────────────┬─────────────┬─────────────┬─────────────┐
    │ (index) │       pool       │  chain   │ project  │     symbol      │  poolMeta   │   tvlUsd    │     apy     │
    ├─────────┼──────────────────┼──────────┼──────────┼─────────────────┼─────────────┼─────────────┼─────────────┤
    │    0    │ '803-30074-STRD' │ 'Stride' │ 'stride' │  'STATOM-ATOM'  │ '14 day(s)' │ 7749466.533 │ 28.73143064 │
    │    1    │ '806-29683-OSMO' │ 'Stride' │ 'stride' │   'STRD-OSMO'   │ '14 day(s)' │ 444047.3332 │ 85.55796709 │
    │    2    │ '810-30104-STRD' │ 'Stride' │ 'stride' │ 'STSTARS-STARS' │ '14 day(s)' │ 422620.2508 │ 19.0618343  │
    │    3    │ '817-29965-STRD' │ 'Stride' │ 'stride' │  'STJUNO-JUNO'  │ '14 day(s)' │ 193100.3702 │ 34.59270944 │
    └─────────┴──────────────────┴──────────┴──────────┴─────────────────┴─────────────┴─────────────┴─────────────┘

**Comment by slasher125** [comment]
cool, tests are passing. was just checking the apy values, they seem to be sufficiently different compared to the UI:

Screenshot 2022-12-01

**Comment by slasher125** [comment]
got it. ty for explaining

**Pull request merged**
