### PR TITLE
GoGoPool add ggAVAX yields for the GoGoPool LST protocol 

### PR DESCRIPTION
**Pull request by ThomasPiXX**
add yields for the ggAVAX LST using the official API

### CODE REVIEW

**Comment by llamatester** [comment]
The wombat-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       781 passed, 781 total
    Snapshots:   0 total
    Time:        0.523 s
    Ran all test suites.
    
    Nb of pools: 111
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────────────┬────────────┬────────────────────┬──────────────┬───────────────────────┬───────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │      project      │   chain    │       tvlUsd       │    symbol    │       apyReward       │        apyBase        │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────────────┼────────────┼────────────────────┼──────────────┼───────────────────────┼───────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xa393d61fe1532257b69b753af7d1efb0e22f1a6e' │ 'wombat-exchange' │   'bsc'    │ 3103995.611678274  │   'LP-HAY'   │   7.530968843972929   │           0           │ [ '0x0782b6d8c4551b9760e74c0545a9bcd90bdc41e5' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    1    │ '0xa649be04619a8f3b3475498e1ac15c90c9661c1a' │ 'wombat-exchange' │   'bsc'    │ 2053128.6964975554 │  'LP-BUSD'   │  1.2065885957631688   │           0           │ [ '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    2    │ '0x975693afe5bb69088a716e3a7f9bff77ec51d57f' │ 'wombat-exchange' │   'bsc'    │ 1635165.5244089786 │  'LP-wBETH'  │ 0.0004822451573460147 │  1.0776475624971384   │ [ '0xa2e3356610840701bdf5611a53974510ae27e2e1' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    3    │ '0x4447de210475bfa08e5d42271a73d7624c8a5ac6' │ 'wombat-exchange' │   'bsc'    │ 1575973.9226017904 │   'LP-ETH'   │ 0.0001324628393955329 │  1.1191214138415246   │ [ '0x2170ed0880ac9a755fd29b2688956bd959f933f8' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    4    │ '0xb4beb0fdf0163a39d39b175942e7973da2c336fb' │ 'wombat-exchange' │ 'arbitrum' │ 875858.3998585212  │ 'LP-PENDLE'  │  3.7827523458533694   │ 0.006992623982991101  │ [ '0x0c880f6761f1af8d9aa9c466984b80dab9a8c9e8' ] │ [ '0x7b5eb3940021ec0e8e463d5dbb4b7b09a89ddf96' ] │
    │    5    │ '0xaa0811aff60fbe2d7d7d0a18f26e584b8c148ee8' │ 'wombat-exchange' │   'bsc'    │ 738452.3676622481  │  'LP-SnBNB'  │  0.5693834939061568   │ 0.000296392921277533  │ [ '0xb0b84d294e0c75a6abe60171b70edeb2efd14a1b' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    6    │ '0x5ad0b68c8544d475ee73ffd4c8dfe7e273b01266' │ 'wombat-exchange' │ 'arbitrum' │ 638706.4496389024  │ 'LP-mPendle' │  10.535524704279425   │  0.00829301847698432  │ [ '0xb688ba096b7bb75d7841e47163cd12d18b36a5bf' ] │ [ '0x7b5eb3940021ec0e8e463d5dbb4b7b09a89ddf96' ] │
    │    7    │ '0xa6ef6c45ebfdbc13f6d032fbdfec9b389c1603e5' │ 'wombat-exchange' │   'bsc'    │ 500720.5745872088  │   'LP-HAY'   │  1533.7386320554397   │           0           │ [ '0x0782b6d8c4551b9760e74c0545a9bcd90bdc41e5' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    8    │ '0x681124f5bdd9acda19d1721063254189903cd685' │ 'wombat-exchange' │   'bsc'    │ 493873.0719292685  │  'LP-USDC'   │   8.407983776774037   │           0           │ [ '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    │    9    │ '0x5d38a3b0f04f6c6026c24ffa78ccdf421f91df38' │ 'wombat-exchange' │   'bsc'    │ 362736.0872820141  │  'LP-WBNB'   │  1.7354696271394183   │ 0.0006038741929124335 │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │ [ '0xAD6742A35fB341A9Cc6ad674738Dd8da98b94Fb1' ] │
    └─────────┴──────────────────────────────────────────────┴───────────────────┴────────────┴────────────────────┴──────────────┴───────────────────────┴───────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm
- revert all changes except the adapter itself
- data should be fetched from on chain, specifically the tvl, and the apy too if possible to query via contracts

**Comment by ThomasPiXX** [comment]
gm

I've reverted the changes and pulled the original repository.

The Wombat Exchange is the current version on the yield-server repository. There is a branch with the new Wombat Exchange GGPool project that will be pulled for a future project.

Currently, the master branch only contains the GoGoPool adapters.

If there are any changes that haven't been reverted correctly, please point them out.

**Comment by ThomasPiXX** [comment]
Also,


we are using the same approach as Lido for the GgPool adapter

**Comment by slasher125** [comment]
hi, all i can do rn is repeat that i mentioned above:
1. there are still unnecessary changes in this PR. the idea is to only push the code for this adapter, nothing else
2. pls refactor to using on chain calls wherever possible (at minimum for tvl)

**Pull request closed without merging**
