### PR TITLE
chore: contrax-finance adapter

### PR DESCRIPTION
**Pull request by abdulrafay-contrax**

### CODE REVIEW

**Comment by llamatester** [comment]
The contrax-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       84 passed, 84 total
    Snapshots:   0 total
    Time:        0.464 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬────────────┬───────────────────────────────────────────────────────┬───────────────────┬──────────────┬────────────────────┬────────────────────┐
    │ (index) │   chain    │                         pool                          │      project      │    symbol    │      apyBase       │       tvlUsd       │
    ├─────────┼────────────┼───────────────────────────────────────────────────────┼───────────────────┼──────────────┼────────────────────┼────────────────────┤
    │    0    │ 'Arbitrum' │ '0xfd3573bebdc8bf323c65edf2408fd9a8412a8694-arbitrum' │ 'contrax-finance' │    'ETH'     │ 4.759280046764483  │ 5941.109910046746  │
    │    1    │ 'Arbitrum' │ '0x1dda3b8a728a62a30f79d1e2a10e3d6b85ef4c5d-arbitrum' │ 'contrax-finance' │    'USDC'    │ 5.987513000580905  │ 1123.043459166271  │
    │    2    │ 'Arbitrum' │ '0x286d24b99b5cb6fe081f0e6bd44ecbfcc1171a56-arbitrum' │ 'contrax-finance' │ 'WETH-RDPX'  │ 26.62913183179186  │ 371.1269932877195  │
    │    3    │ 'Arbitrum' │ '0x3f9012f9bf3172c26b1b7246b8bc62148842b013-arbitrum' │ 'contrax-finance' │ 'WETH-MAGIC' │ 13.982964356799693 │ 324.90150698769236 │
    │    4    │ 'Arbitrum' │ '0x5cc3543656efa30144965c6c538f4d8379f83138-arbitrum' │ 'contrax-finance' │    'USDT'    │ 4.312477496224465  │ 121.51208069949965 │
    │    5    │ 'Arbitrum' │ '0x8cdf8d10ea6cd3492e67c4250481a695c2a75c4a-arbitrum' │ 'contrax-finance' │    'GMX'     │ 1.4123649794249138 │ 108.3652354057931  │
    │    6    │ 'Arbitrum' │ '0xf8bdcf1cf4134b2864cdbe685a8128f90ed0e16e-arbitrum' │ 'contrax-finance' │ 'WETH-USDT'  │ 20.29820269843532  │ 96.84260269581799  │
    │    7    │ 'Arbitrum' │ '0x46910a4aba500b71f213150a0e99201fd5c8fcec-arbitrum' │ 'contrax-finance' │ 'WETH-USDC'  │ 8.251140210803115  │ 94.59189382700339  │
    │    8    │ 'Arbitrum' │ '0xb58004e106409b00b854abbf8ccb8618673d9346-arbitrum' │ 'contrax-finance' │  'WETH-DAI'  │ 4.2659554018863375 │ 92.55563815281063  │
    │    9    │ 'Arbitrum' │ '0xdf9d86bc4765a9c64e85323a9408dbee0115d22e-arbitrum' │ 'contrax-finance' │ 'WETH-WBTC'  │ 0.7276534342653445 │  55.0712359086454  │
    └─────────┴────────────┴───────────────────────────────────────────────────────┴───────────────────┴──────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, we no longer accept api based adapters, need to be refactored to on chain calls or subgraph

**Comment by abdulrafay-contrax** [comment]
> er accept api based adapters, need to be refactored to on chain calls or subgraph

@slasher125 We are aggregating different pools, like hop-finance(which uses apis) and sushiswap. so these apys come from their apis etc, Is there a way to get the apys from defillama other adapters.

**Comment by abdulrafay-contrax** [comment]
@slasher125 Can you give me an example of it, maybe in code, Thanks

**Comment by slasher125** [comment]
`https://yields.llama.fi/pools` contains all our apy data per pool. u can then filter to the required project + pool (by symbol; if not sufficient, we have a mapping from `pool` field to address on `https://yields.llama.fi/distinctId` where `config_id` = `pool` from /pools response)

**Comment by slasher125** [comment]
closing this for now. feel free to reopen once ready

**Pull request closed without merging**
