### PR TITLE
UmamiFinance: fix staking infos and add GLP vaults

### PR DESCRIPTION
**Pull request by Clonescody**
- Fix staking pools labels 
- Add staking pools details
- Add liquid and boosted GLP vaults + details
- Organize constants
- Boosted vault TVL is calculated using `liquidVault.balanceOf(timelockVault) * liquidVault.pps() * underlyingTokenPrice`

[Umami Docs](https://umami-dao.gitbook.io/umami-dao/overview/welcome-to-umami)

### CODE REVIEW

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       88 passed, 88 total
    Snapshots:   0 total
    Time:        0.357 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬───────┬────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │  apy  │   symbol   │                   rewardTokens                   │                 underlyingTokens                 │                  url                   │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼───────┼────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 5411481.831821624  │ 2.77  │  'mUMAMI'  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 2898503.6794662317 │ 2.81  │ 'cmUMAMI'  │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │   999765.956576    │ 31.88 │ 'glpUSDC'  │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 503952.16927824623 │ 35.22 │ 'glpWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │  484515.12438095   │ 37.71 │ 'glpWBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0xdca4e88c00a8800ebcebad63abdbaaaa755557f9' │ 299326.3131488319  │ 5.72  │ 'glpUSDCb' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0xf2ad33e12a9780f1e42d878a29a3e0756008c838' │ 186633.3379002631  │ 4.78  │ 'glpWETHb' │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x83c19ec75d649aec7c99e2c6663ca055569da7c0' │ 153627.9873539198  │ 6.12  │ 'glpWBTCb' │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 38902.60726685781  │ 13.3  │ 'glpLINK'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ 'https://umami.finance/vaults/glplink' │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 31160.415448894833 │ 10.23 │  'glpUNI'  │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ 'https://umami.finance/vaults/glpuni'  │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴───────┴────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       88 passed, 88 total
    Snapshots:   0 total
    Time:        0.335 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬───────┬─────────┬────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │  apy  │ apyBase │   symbol   │                   rewardTokens                   │                 underlyingTokens                 │                  url                   │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼───────┼─────────┼────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 5415483.681591657  │ 2.77  │  2.77   │  'mUMAMI'  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 2900617.8324053027 │ 2.81  │  2.81   │ 'cmUMAMI'  │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 999750.7402715811  │ 9.79  │  9.79   │ 'glpUSDC'  │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 502846.9909006362  │ 13.3  │  13.3   │ 'glpWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │ 486060.42269904003 │ 15.33 │  15.33  │ 'glpWBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0xdca4e88c00a8800ebcebad63abdbaaaa755557f9' │ 291771.7835408621  │ 12.12 │  12.12  │ 'glpUSDCb' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0xf2ad33e12a9780f1e42d878a29a3e0756008c838' │ 186224.57398828765 │ 15.19 │  15.19  │ 'glpWETHb' │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x83c19ec75d649aec7c99e2c6663ca055569da7c0' │ 154118.51593095373 │ 17.53 │  17.53  │ 'glpWBTCb' │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 39001.61229819112  │ 5.59  │  5.59   │ 'glpLINK'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ 'https://umami.finance/vaults/glplink' │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 31322.036798325145 │  6.5  │   6.5   │  'glpUNI'  │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ 'https://umami.finance/vaults/glpuni'  │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴───────┴─────────┴────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
henlo, ty for updating. 
- remove `apy` field but keep `apyBase`
- to confirm, apy values need to be unboosted

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       88 passed, 88 total
    Snapshots:   0 total
    Time:        0.427 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │   symbol   │                   rewardTokens                   │                 underlyingTokens                 │                  url                   │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │  5317214.80507402  │  3.51   │  'mUMAMI'  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 2848158.0261314083 │  3.57   │ 'cmUMAMI'  │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 998531.5884116217  │  10.18  │ 'glpUSDC'  │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 506176.1208818087  │  12.43  │ 'glpWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │ 486501.79589075997 │  14.33  │ 'glpWBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0xdca4e88c00a8800ebcebad63abdbaaaa755557f9' │ 306479.30348510493 │  12.46  │ 'glpUSDCb' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0xf2ad33e12a9780f1e42d878a29a3e0756008c838' │ 187500.08134183838 │  14.32  │ 'glpWETHb' │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x83c19ec75d649aec7c99e2c6663ca055569da7c0' │ 154262.91332871534 │  16.54  │ 'glpWBTCb' │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 38555.10705565015  │  5.16   │ 'glpLINK'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ 'https://umami.finance/vaults/glplink' │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 31854.788841492653 │  6.04   │  'glpUNI'  │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ 'https://umami.finance/vaults/glpuni'  │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by Clonescody** [comment]
Gm ser, updated for the APY, as for the boosted part not sure I follow ? 

In our case the timelocked/boosted vaults are a timelocked version of our liquid GLP vaults that allows us to manage TVL more properly, so the "boost" part doesn't come from any extra yield or incentives, it's a pricePerShare of a pricePerShare basically ( timelock vault holds GLP vault receipt token ). 

Hope that helps, lmk if it still needs changes @slasher125

**Comment by slasher125** [comment]
oke, what i meant was that the apy values shown here in the adapter are from the liquid vaults, instead of the timelocked vaults. but seems like thats the case

**Comment by Clonescody** [comment]
Sounds good will do

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       53 passed, 53 total
    Snapshots:   0 total
    Time:        0.411 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  symbol   │                   rewardTokens                   │                 underlyingTokens                 │                  url                   │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │  5498797.49329481  │  3.36   │ 'mUMAMI'  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 2945163.9397413777 │  3.42   │ 'cmUMAMI' │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │    'https://umami.finance/marinate'    │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 999356.9347381619  │  10.18  │ 'glpUSDC' │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://umami.finance/vaults/glpusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │  507699.957782662  │  12.43  │ 'glpWETH' │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/glpweth' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │   487712.0716842   │  14.33  │ 'glpWBTC' │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/glpwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 38845.313443323175 │  5.16   │ 'glpLINK' │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ 'https://umami.finance/vaults/glplink' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 32012.136810279913 │  6.04   │ 'glpUNI'  │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │ 'https://umami.finance/vaults/glpuni'  │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────┴────────────┴─────────────────┘

**Comment by Clonescody** [comment]
@slasher125 ready whenever

**Comment by 0xdapper** [comment]
Cant we even list the locked, we just add it to the pool name that it is locked?

**Pull request merged**
