### PR TITLE
add mm-finance-polygon

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The mm-finance-polygon adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.367 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬──────────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │       project        │    symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼──────────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x384c1b95027B73a98FE31Ea5B4B7b031b9ddD724' │ 'Polygon' │ 'mm-finance-polygon' │  'USDC-USDT'  │ 188220720.80631033 │ 10.013517138386291 │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    1    │ '0x1aEc8fF1C39c34338327A32bBb35011432614172' │ 'Polygon' │ 'mm-finance-polygon' │  'WBTC-USDC'  │ 108368923.72239162 │ 34.783983246370006 │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    2    │ '0x8C26252B14F9b071585B81b240C4ae2176E8cD3C' │ 'Polygon' │ 'mm-finance-polygon' │  'USDC-WETH'  │ 95029500.57801339  │ 39.66665934535022  │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    3    │ '0xb965c131f1C48d89B1760860b782D2aCDF87273b' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-USDC' │ 67088162.320619784 │ 56.187301854715564 │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    4    │ '0xa789324E64268C5385eA7678435Fa83532705B0F' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-USDT' │ 33746860.04449401  │ 55.84968234402944  │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    5    │ '0xD15EB8710E28C23993968e671807d572189CC86e' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-MMF'  │ 13640675.41457573  │ 1105.3713141385715 │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    6    │ '0x8AB47799cB0d49aEB9E3a47c369813a3a3236790' │ 'Polygon' │ 'mm-finance-polygon' │  'MMF-USDC'   │ 5132533.393449863  │ 734.4331810870352  │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    7    │ '0xd6a88114DCC01f72D1B311aD6adF860724ff35d3' │ 'Polygon' │ 'mm-finance-polygon' │   'MMF-MMO'   │ 2140782.231628621  │ 880.4031469186693  │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481', '0x859a50979fdB2A2fD8Ba1AdCC66977C6f6b1CD5B' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴──────────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by vrtnd** [comment]
Hi, thanks for the PR. MM finance also have subgraph https://api.thegraph.com/subgraphs/name/polymmfinance/exchang for fee apy calculation

**Comment by llamatester** [comment]
The mm-finance-polygon adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.316 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬──────────────────────┬───────────────┬────────────────────┬─────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │       project        │    symbol     │       tvlUsd       │       apyBase       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼──────────────────────┼───────────────┼────────────────────┼─────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x384c1b95027B73a98FE31Ea5B4B7b031b9ddD724' │ 'Polygon' │ 'mm-finance-polygon' │  'USDC-USDT'  │ 188995373.47343922 │ 0.15602173732500263 │ 6.8133401279000205 │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    1    │ '0x8C26252B14F9b071585B81b240C4ae2176E8cD3C' │ 'Polygon' │ 'mm-finance-polygon' │  'USDC-WETH'  │ 101906953.86323163 │  5.237313717983369  │ 31.589840370516587 │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    2    │ '0x1aEc8fF1C39c34338327A32bBb35011432614172' │ 'Polygon' │ 'mm-finance-polygon' │  'WBTC-USDC'  │ 100081279.73699336 │  2.109468785975268  │ 16.08304976537562  │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    3    │ '0xb965c131f1C48d89B1760860b782D2aCDF87273b' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-USDC' │ 73677747.41457571  │  8.964746945141824  │ 52.43196788421181  │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    4    │ '0xa789324E64268C5385eA7678435Fa83532705B0F' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-USDT' │ 34239971.108840406 │  7.316500257366827  │ 47.00974184458227  │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    5    │ '0xD15EB8710E28C23993968e671807d572189CC86e' │ 'Polygon' │ 'mm-finance-polygon' │ 'WMATIC-MMF'  │ 12125008.393308675 │          0          │ 1194.7628697170578 │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    6    │ '0x8AB47799cB0d49aEB9E3a47c369813a3a3236790' │ 'Polygon' │ 'mm-finance-polygon' │  'MMF-USDC'   │ 4217327.656152204  │ 192.36204389556863  │ 1144.999156215278  │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    │    7    │ '0xd6a88114DCC01f72D1B311aD6adF860724ff35d3' │ 'Polygon' │ 'mm-finance-polygon' │   'MMF-MMO'   │ 2070605.8545689196 │  33.18410088576721  │ 777.3629148400379  │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481', '0x859a50979fdB2A2fD8Ba1AdCC66977C6f6b1CD5B' ] │ [ '0x22a31bD4cB694433B6de19e0aCC2899E553e9481' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴──────────────────────┴───────────────┴────────────────────┴─────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by dtmkeng** [comment]
@vrtnd done

**Pull request merged**
