### PR TITLE
feat: add nftx pools to apy server

### PR DESCRIPTION
**Pull request by quagliero**

### CODE REVIEW

**Comment by vrtnd** [comment]
Hi, thanks for PR.
Please use `module.exports` syntax for exports

**Comment by quagliero** [comment]
> Hi, thanks for PR.
> Please use `module.exports` syntax for exports

Aha of course. Was on javascript autopilot!

**Comment by llamatester** [comment]
The nftx adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       1774 passed, 1774 total
    Snapshots:   0 total
    Time:        0.769 s
    Ran all test suites.
    
    Nb of pools: 253
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project │  symbol  │        apy         │       tvlUsd       │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x5f2f947544cb7d4fd5c62215f59ad8dab348358e' │ 'ethereum' │ 'nftx'  │ 'FELLAZ' │ 218.67317178998098 │ 26636389.30136202  │ [ '0x5f2f947544cb7d4fd5c62215f59ad8dab348358e' ] │ [ '0x5f2f947544cb7d4fd5c62215f59ad8dab348358e' ] │
    │    1    │ '0x269616d549d7e8eaa82dfb17028d0b212d11232a' │ 'ethereum' │ 'nftx'  │  'PUNK'  │ 7.158137759542038  │ 17829461.69732273  │ [ '0x269616d549d7e8eaa82dfb17028d0b212d11232a' ] │ [ '0x269616d549d7e8eaa82dfb17028d0b212d11232a' ] │
    │    2    │ '0x98efed71928ae7d0c2b993de013af788ff1c4376' │ 'ethereum' │ 'nftx'  │  'MAXI'  │ 121651.60686586157 │ 4024248.588561003  │ [ '0x98efed71928ae7d0c2b993de013af788ff1c4376' ] │ [ '0x98efed71928ae7d0c2b993de013af788ff1c4376' ] │
    │    3    │ '0xb987a6197043ee356658f787504004e4591b7a81' │ 'ethereum' │ 'nftx'  │  'BORD'  │ 1.5778408352657758 │ 3184453.4587548347 │ [ '0xb987a6197043ee356658f787504004e4591b7a81' ] │ [ '0xb987a6197043ee356658f787504004e4591b7a81' ] │
    │    4    │ '0x227c7df69d3ed1ae7574a1a7685fded90292eb48' │ 'ethereum' │ 'nftx'  │ 'MILADY' │ 95.17844666474973  │ 2074877.7348390715 │ [ '0x227c7df69d3ed1ae7574a1a7685fded90292eb48' ] │ [ '0x227c7df69d3ed1ae7574a1a7685fded90292eb48' ] │
    │    5    │ '0x8d137e3337eb1b58a222fef2b2cc7c423903d9cf' │ 'ethereum' │ 'nftx'  │  'SQGL'  │ 39.775699869781135 │ 1314961.8420642987 │ [ '0x8d137e3337eb1b58a222fef2b2cc7c423903d9cf' ] │ [ '0x8d137e3337eb1b58a222fef2b2cc7c423903d9cf' ] │
    │    6    │ '0x05ec119d78d197ceee5ffb78e0e6aa4a9a1b416a' │ 'ethereum' │ 'nftx'  │ 'PIDGIE' │ 16.134606818090425 │ 1227136.837257968  │ [ '0x05ec119d78d197ceee5ffb78e0e6aa4a9a1b416a' ] │ [ '0x05ec119d78d197ceee5ffb78e0e6aa4a9a1b416a' ] │
    │    7    │ '0x87931e7ad81914e7898d07c68f145fc0a553d8fb' │ 'ethereum' │ 'nftx'  │ 'WIZARD' │ 22.375026632852226 │  977084.235703912  │ [ '0x87931e7ad81914e7898d07c68f145fc0a553d8fb' ] │ [ '0x87931e7ad81914e7898d07c68f145fc0a553d8fb' ] │
    │    8    │ '0x2f131c4dad4be81683abb966b4de05a549144443' │ 'ethereum' │ 'nftx'  │ 'DOODLE' │ 898.9318336618637  │ 942586.1311839352  │ [ '0x2f131c4dad4be81683abb966b4de05a549144443' ] │ [ '0x2f131c4dad4be81683abb966b4de05a549144443' ] │
    │    9    │ '0x641927e970222b10b2e8cdbc96b1b4f427316f16' │ 'ethereum' │ 'nftx'  │  'MEEB'  │ 16.798889099261128 │ 822241.9075229366  │ [ '0x641927e970222b10b2e8cdbc96b1b4f427316f16' ] │ [ '0x641927e970222b10b2e8cdbc96b1b4f427316f16' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴──────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by vrtnd** [comment]
Hi, thanks for the PR. 
tvlUsd looks wrong (FELLAZ for example)
Screenshot 20221

**Comment by quagliero** [comment]
> Hi, thanks for the PR. tvlUsd looks wrong (FELLAZ for example) Screenshot 20221

Yeah, just noticed that. I've filtered out pools that have fewer than 2 items in.

**Comment by vrtnd** [comment]
Also smth wrong with MAXI, BORD
Screenshot 2022-08-09 at 20 13 23

**Comment by quagliero** [comment]
@vrtnd I'll skim through and see what's up. BORD is because that pool has 498904 items in at at a spot price of 0.0007 ETH. (Someone taking advantage of ERC1155).

Maxi is illiquid so I'll see if we can do any more checks further up stream.

**Comment by slasher125** [comment]
henlo, couple of questions @quagliero :)
today one of our users reported large differences in values comparing your UI vs ours. Obviously small differences are normal given we update our data "only" on an hourly basis. 

Q1: Why is the tvl for PUNKS (among others) much lower compared to the adapter output:
```
 {
    pool: '0x269616d549d7e8eaa82dfb17028d0b212d11232a',
    chain: 'Ethereum',
    project: 'nftx',
    symbol: 'PUNK',
    apy: 3.521586456973891,
    tvlUsd: 14660859.542950042,
    rewardTokens: [ '0x269616d549d7e8eaa82dfb17028d0b212d11232a' ],
    underlyingTokens: [ '0x269616d549d7e8eaa82dfb17028d0b212d11232a' ]
  },
```

whereas on your UI:
Screenshot 2022-08-20 at 21 37 34

Q2: From scanning the docs it seems to me that an LP can only earn either the inventory apr or liquidity apr, but not both at the same time, is that correct? If so, we can't just sum up the values but we will need to display these as separate pools altogether (or just decide to show pools with inventory or liquidity apr). Can you confirm this pls?

Ty :)

**Comment by quagliero** [comment]
Hi @slasher125 

Q1: the difference here is the nftx app uses the liquidity pool reserves and for the defilama feed it’s ‘holdings * spotPrice x2’. (Was unsure which was best as the former is amount of vtoken/eth, the latter is the amount of NFT value)

I’m happy to make a change so it uses the same calcs as the nftx yield app, will just need to throw in a web3 call to get the reserves :)

2. Users can achieve the combined APR by providing both liquidity and inventory. Although we have discussed internally about showing these as 2 separate pools on defilama so I’ll have a PR in soon that splits these up. :)

**Comment by quagliero** [comment]
@slasher125 see https://github.com/DefiLlama/yield-server/pull/259 :)

**Pull request merged**
