### PR TITLE
add blueprint

### PR DESCRIPTION
**Pull request by ruvlol**

### CODE REVIEW

**Comment by slasher125** [comment]
hi, ty for adding.
why are u commenting out the sdk code blocks?

**Comment by ruvlol** [comment]
The commented part was cloned from existing Merkl integration. Basically our thing is Merkl copy but with only Blueprint pools tracked.

**Comment by slasher125** [comment]
k, if the sdk call works, then lets use that instead of the api

**Comment by slasher125** [comment]
@ruvlol gm, are u still working on this?

**Comment by slasher125** [comment]
closing this, feel free to reopen using the sdk instead

**Pull request closed without merging**
