### PR TITLE
add pembrock-finance

### PR DESCRIPTION
**Pull request by feedkeek**
Test Suites: 1 passed, 1 total                                                                              
Tests:       84 passed, 84 total                                                                            
Snapshots:   0 total
Time:        9.368 s, estimated 11 s
Ran all test suites.
Nb of pools: 16

### CODE REVIEW

**Comment by llamatester** [comment]
The pembrock-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       84 passed, 84 total
    Snapshots:   0 total
    Time:        0.377 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────────┬────────┬────────────────────┬──────────────┬───────────────┬───────────┬────────────────────┐
    │ (index) │                                  pool                                  │ chain  │      project       │    symbol    │   poolMeta    │    apy    │       tvlUsd       │
    ├─────────┼────────────────────────────────────────────────────────────────────────┼────────┼────────────────────┼──────────────┼───────────────┼───────────┼────────────────────┤
    │    0    │ 'dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'USDT'    │ 'Ref-Finance' │     9     │  488777.371146064  │
    │    1    │                          'wrap.near-lending'                           │ 'NEAR' │ 'pembrock-finance' │   'wNEAR'    │ 'Ref-Finance' │   8.33    │ 374042.0902244747  │
    │    2    │                            'aurora-lending'                            │ 'NEAR' │ 'pembrock-finance' │    'ETH'     │ 'Ref-Finance' │   4.91    │ 360357.38234498363 │
    │    3    │                     'token.pembrock.near-lending'                      │ 'NEAR' │ 'pembrock-finance' │    'PEM'     │ 'Ref-Finance' │    6.2    │ 348054.0817489041  │
    │    4    │ '2260fac5e5542a773aa44fbcfedf7c193bc2c599.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'WBTC'    │ 'Ref-Finance' │    3.7    │  320024.64819327   │
    │    5    │                         'ref-pool-79-farming'                          │ 'NEAR' │ 'pembrock-finance' │ 'REF-wNEAR'  │ 'Ref-Finance' │  131.82   │     305875.33      │
    │    6    │                          'ref-pool-4-farming'                          │ 'NEAR' │ 'pembrock-finance' │ 'USDT-wNEAR' │ 'Ref-Finance' │   62.03   │     290337.02      │
    │    7    │                        'ref-pool-3448-farming'                         │ 'NEAR' │ 'pembrock-finance' │  'PEM-USN'   │ 'Ref-Finance' │ 119306.39 │     127443.14      │
    │    8    │ 'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'USDC'    │ 'Ref-Finance' │   8.85    │  97575.534029974   │
    │    9    │                  'token.v2.ref-finance.near-lending'                   │ 'NEAR' │ 'pembrock-finance' │    'REF'     │ 'Ref-Finance' │   21.63   │ 72683.35934291335  │
    └─────────┴────────────────────────────────────────────────────────────────────────┴────────┴────────────────────┴──────────────┴───────────────┴───────────┴────────────────────┘

**Comment by slasher125** [comment]
ty for adding:
- for the farming pools, lets default to unleveraged apy values
- to also list you on our strategy page, you'd need to add the following fields for the lending pools:  `apyBaseBorrow`, `apyRewardBorrow`, `totalSupplyUsd`, `totalBorrowUsd`, `ltv`

**Comment by llamatester** [comment]
The pembrock-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       84 passed, 84 total
    Snapshots:   0 total
    Time:        0.377 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────────┬────────┬────────────────────┬──────────────┬───────────────┬────────┬────────────────────┐
    │ (index) │                                  pool                                  │ chain  │      project       │    symbol    │   poolMeta    │  apy   │       tvlUsd       │
    ├─────────┼────────────────────────────────────────────────────────────────────────┼────────┼────────────────────┼──────────────┼───────────────┼────────┼────────────────────┤
    │    0    │ 'dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'USDT'    │ 'Ref-Finance' │  9.86  │ 438212.68321285176 │
    │    1    │                            'aurora-lending'                            │ 'NEAR' │ 'pembrock-finance' │    'ETH'     │ 'Ref-Finance' │  5.11  │ 350119.2250799025  │
    │    2    │                     'token.pembrock.near-lending'                      │ 'NEAR' │ 'pembrock-finance' │    'PEM'     │ 'Ref-Finance' │  6.27  │ 348554.3428421125  │
    │    3    │                          'wrap.near-lending'                           │ 'NEAR' │ 'pembrock-finance' │   'wNEAR'    │ 'Ref-Finance' │  9.07  │  348106.704721916  │
    │    4    │                         'ref-pool-79-farming'                          │ 'NEAR' │ 'pembrock-finance' │ 'REF-wNEAR'  │ 'Ref-Finance' │ 38.62  │     297775.86      │
    │    5    │ '2260fac5e5542a773aa44fbcfedf7c193bc2c599.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'WBTC'    │ 'Ref-Finance' │  4.08  │   294148.9149888   │
    │    6    │                          'ref-pool-4-farming'                          │ 'NEAR' │ 'pembrock-finance' │ 'USDT-wNEAR' │ 'Ref-Finance' │  20.9  │     265802.52      │
    │    7    │                        'ref-pool-3448-farming'                         │ 'NEAR' │ 'pembrock-finance' │  'PEM-USN'   │ 'Ref-Finance' │ 745.43 │     136362.88      │
    │    8    │ 'a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near-lending' │ 'NEAR' │ 'pembrock-finance' │    'USDC'    │ 'Ref-Finance' │   9    │ 96782.99302101562  │
    │    9    │                  'token.v2.ref-finance.near-lending'                   │ 'NEAR' │ 'pembrock-finance' │    'REF'     │ 'Ref-Finance' │ 22.04  │ 69895.22824631089  │
    └─────────┴────────────────────────────────────────────────────────────────────────┴────────┴────────────────────┴──────────────┴───────────────┴────────┴────────────────────┘

**Comment by slasher125** [comment]
do u want to add it like this or should i wait for the borrow related fields?
also, it would be great if u'd split up the apy into `apyBase` and `apyReward` components, where apyBase is from trading fees and apyReward from yield farming

**Comment by feedkeek** [comment]
add like this

**Pull request merged**
