### PR TITLE
Added the farms for the Andromeada pool

### PR DESCRIPTION
**Pull request by andromedafi**
Hello,

We are a fork of velodrome v1, launching this Sunday. The APR logic is a copy-paste of the existing code for velodrome taken from here: https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/velodrome-v1/index.ts

Looking forward!

### CODE REVIEW

**Comment by slasher125** [comment]
hi, ty for adding. pls refactor to on chain calls instead.

**Comment by andromedafi** [comment]
Hey @slasher125 

Feedback taken, we used the velodrome-v2 APR code and ported it for our contracts. Please find the updated PR.

**Comment by andromedafi** [comment]
Hey @slasher125

Feedback taken, we used the velodrome-v2 APR code and ported it for our contracts. Please find the updated PR.

**Comment by llamatester** [comment]
The andromeada adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.347 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────┬──────────────┬────────────────────┬───────────┬──────────────┬───────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │   project    │    symbol    │       tvlUsd       │ apyReward │ rewardTokens │                                            url                                            │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────┼──────────────┼────────────────────┼───────────┼──────────────┼───────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xCFb9c209744170bb9844A1D0A9Ab21CC7f17872B' │ 'base' │ 'andromeada' │ 'WETH-ANDRE' │ 21825.80532638985  │     0     │      []      │ 'https://andromeada.com/liquidity/manage?pair=0xCFb9c209744170bb9844A1D0A9Ab21CC7f17872B' │
    │    1    │ '0x950b10c8326d2b566E8c6A786A5D4ab59e514088' │ 'base' │ 'andromeada' │ 'DAI-USDBC'  │ 2232.1594900251284 │     0     │      []      │ 'https://andromeada.com/liquidity/manage?pair=0x950b10c8326d2b566E8c6A786A5D4ab59e514088' │
    │    2    │ '0xF9329F111C7AB3675E026D5e317d03BbEF6b5aF2' │ 'base' │ 'andromeada' │ 'CBETH-WETH' │ 419.19915214182527 │     0     │      []      │ 'https://andromeada.com/liquidity/manage?pair=0xF9329F111C7AB3675E026D5e317d03BbEF6b5aF2' │
    │    3    │ '0xF37f5aBF57415bfC7855719bBb2F9fa41C54627F' │ 'base' │ 'andromeada' │ 'WETH-USDBC' │ 196.67195413946513 │     0     │      []      │ 'https://andromeada.com/liquidity/manage?pair=0xF37f5aBF57415bfC7855719bBb2F9fa41C54627F' │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────┴──────────────┴────────────────────┴───────────┴──────────────┴───────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
apyReward is 0?

**Comment by andromedafi** [comment]
Emissions had not started yet. It is now. You can have a look :)

**Comment by llamatester** [comment]
The andromeada adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.418 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────┬──────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │   project    │    symbol    │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                            url                                            │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────┼──────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xCFb9c209744170bb9844A1D0A9Ab21CC7f17872B' │ 'base' │ 'andromeada' │ 'WETH-ANDRE' │ 21426.785551347806 │ 32.87026285285851  │ [ '0xFA7D088f6B1bbf7b1C8c3aC265Bb797264FD360B' ] │ 'https://andromeada.com/liquidity/manage?pair=0xCFb9c209744170bb9844A1D0A9Ab21CC7f17872B' │
    │    1    │ '0xF37f5aBF57415bfC7855719bBb2F9fa41C54627F' │ 'base' │ 'andromeada' │ 'WETH-USDBC' │ 2430.860762215343  │ 25.946359280512187 │ [ '0xFA7D088f6B1bbf7b1C8c3aC265Bb797264FD360B' ] │ 'https://andromeada.com/liquidity/manage?pair=0xF37f5aBF57415bfC7855719bBb2F9fa41C54627F' │
    │    2    │ '0xF9329F111C7AB3675E026D5e317d03BbEF6b5aF2' │ 'base' │ 'andromeada' │ 'CBETH-WETH' │  465.071067309946  │ 271.23590836195694 │ [ '0xFA7D088f6B1bbf7b1C8c3aC265Bb797264FD360B' ] │ 'https://andromeada.com/liquidity/manage?pair=0xF9329F111C7AB3675E026D5e317d03BbEF6b5aF2' │
    │    3    │ '0x950b10c8326d2b566E8c6A786A5D4ab59e514088' │ 'base' │ 'andromeada' │ 'DAI-USDBC'  │ 333.3709828915023  │ 378.3891816275214  │ [ '0xFA7D088f6B1bbf7b1C8c3aC265Bb797264FD360B' ] │ 'https://andromeada.com/liquidity/manage?pair=0x950b10c8326d2b566E8c6A786A5D4ab59e514088' │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────┴──────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
to confirm, apy values don't include bribe rewards correct? keep in mind to scale to % accordingly

**Comment by andromedafi** [comment]
Yes APY values don't contain bribes. Bribes go to stakers. This contains only the LP rewards

**Pull request closed without merging**
