### PR TITLE
Create veplus yeild

### PR DESCRIPTION
**Pull request by jameveplus**

### CODE REVIEW

**Comment by llamatester** [comment]
The veplus adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.519 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬──────────┬─────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │ project  │   symbol    │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼──────────┼─────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x2d571922bda512cbbf6ceb4b664549ea8fac76c0' │ 'Binance' │ 'veplus' │  'GPT-LOC'  │  4855997.8816658   │ 26.971171635320644 │ [ '0x08cd9d2eec70c37a64b60d941dc540c45691763b', '0xf6963eb1bddcec69cb61d7cbecd40bcbbf4cb8aa' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    1    │ '0x12a55a1b3f7e8b22b997360b1241920b46a36cbd' │ 'Binance' │ 'veplus' │  'TED-LOC'  │ 1803705.996796554  │ 17.855799393748065 │ [ '0xd0287ea401d1e64beffbeb56c77a98cc256ce57c', '0xf6963eb1bddcec69cb61d7cbecd40bcbbf4cb8aa' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    2    │ '0xa82bca78be5fa9a4115805b3163ce6850f3e5664' │ 'Binance' │ 'veplus' │  'GPT-TED'  │ 1128573.1600394368 │ 33.53147410213037  │ [ '0x08cd9d2eec70c37a64b60d941dc540c45691763b', '0xd0287ea401d1e64beffbeb56c77a98cc256ce57c' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    3    │ '0xcb369dbd43de4a5f1d4341cf6621076a6ce668cd' │ 'Binance' │ 'veplus' │ 'VEP-USDT'  │ 64271.40843815536  │ 1578.375444330608  │ [ '0x1e32b79d8203ac691499fbfbb02c07a9c9850dd7', '0x55d398326f99059ff775485246999027b3197955' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    4    │ '0x3f4ba39bd3efffba163e972e12275141ccc59e67' │ 'Binance' │ 'veplus' │ 'USDT-WBNB' │ 15168.096081483309 │ 264.51141544969977 │ [ '0x55d398326f99059ff775485246999027b3197955', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    5    │ '0x904cd34e12f33ebfdf8ea7b3503aeb98fcfdd43c' │ 'Binance' │ 'veplus' │ 'USDT-SRG'  │ 11653.475868485935 │ 688.5537482967087  │ [ '0x55d398326f99059ff775485246999027b3197955', '0xc0ff232d16b415fe7a0d3842d31280778a9400ef' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    6    │ '0xeea9bd88ddda3d259248fc85f16b2cd3e6b29799' │ 'Binance' │ 'veplus' │ 'WBNB-BUSD' │ 9445.185286665164  │ 212.09700521506988 │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    7    │ '0xbd73aafc1f6bbe9eb8de1b5c63249b95f2253df2' │ 'Binance' │ 'veplus' │ 'USDT-SCE'  │ 9276.170857929032  │ 862.5681713219577  │ [ '0x55d398326f99059ff775485246999027b3197955', '0xc94898c7d5e9f3e62a98995985f9a957b592140b' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    8    │ '0x8c53f73d5aa0f52fb31bd558c3621a4c7261b2a3' │ 'Binance' │ 'veplus' │ 'USDT-BUSD' │ 3936.2615568612346 │  203.520914009826  │ [ '0x55d398326f99059ff775485246999027b3197955', '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    │    9    │ '0xf8d40b498471cfa062068f534948354f19201996' │ 'Binance' │ 'veplus' │ 'USDT-USDC' │ 3715.8429714579706 │ 215.8711881185671  │ [ '0x55d398326f99059ff775485246999027b3197955', '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d' ] │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴──────────┴─────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ty for adding. we have many on chain examples of solidly forks (eg equalizer-ezchange, copy paste and smol changes should be enough), best to use that instead of the centralised api calls for apr values.

**Comment by jameveplus** [comment]
Hi @slasher125, I can't get VEP token infor by defillama api, how can I get it?

**Comment by jameveplus** [comment]
@slasher125 I updated calculating APR from onchain data, could you help me to review agian?
Thanks

**Comment by slasher125** [comment]
pls remove the change on excalibur adapter

**Comment by jameveplus** [comment]
Have some mistake, I updated and run tests locally
Help me to review, thanks

**Comment by llamatester** [comment]
The veplus adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       102 passed, 102 total
    Snapshots:   0 total
    Time:        0.479 s
    Ran all test suites.
    
    Nb of pools: 14
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬──────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │ project  │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼───────────┼──────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x3F4Ba39bD3EFFFBa163E972E12275141cCc59E67' │ 'Binance' │ 'veplus' │  'USDT-WBNB'  │ 16942.52118530129  │ 236.3379841218919  │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0x55d398326f99059fF775485246999027B3197955', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    │    1    │ '0xeeA9Bd88Ddda3d259248fc85F16B2cd3E6B29799' │ 'Binance' │ 'veplus' │  'WBNB-BUSD'  │ 8659.417607162828  │ 231.20259809685214 │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    2    │ '0x5A4eE63E246175132729641e1Ee2BF34829ed375' │ 'Binance' │ 'veplus' │  'USDC-WBNB'  │ 8279.595595630297  │ 242.01498844125223 │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    │    3    │ '0x7CfDa822A47154470BfC57040Caf51d05F1a0cd5' │ 'Binance' │ 'veplus' │  'USDC-BUSD'  │ 5183.873409668155  │ 154.48090972017087 │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    4    │ '0xf8d40B498471CFA062068f534948354f19201996' │ 'Binance' │ 'veplus' │  'USDT-USDC'  │ 5182.281916365263  │  154.528351240569  │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0x55d398326f99059fF775485246999027B3197955', '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │
    │    5    │ '0x8c53F73d5aa0F52fB31bd558C3621a4c7261B2A3' │ 'Binance' │ 'veplus' │  'USDT-BUSD'  │ 3937.019078083166  │ 203.40502911396462 │ [ '0x1e32B79d8203AC691499fBFbB02c07A9C9850Dd7' ] │ [ '0x55d398326f99059fF775485246999027B3197955', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    6    │ '0xdD4e4b8fB97b16c0dFb7301B621Cd979f44900aC' │ 'Binance' │ 'veplus' │  'USDT-XVS'   │ 10.785673378106669 │         0          │                        []                        │ [ '0x55d398326f99059fF775485246999027B3197955', '0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63' ] │
    │    7    │ '0x3b1bbe6B99F726181679dd099Cd66d3497E35074' │ 'Binance' │ 'veplus' │ 'USDT-ALPACA' │ 10.736667641101594 │         0          │                        []                        │ [ '0x55d398326f99059fF775485246999027B3197955', '0x8F0528cE5eF7B51152A59745bEfDD91D97091d2F' ] │
    │    8    │ '0x9692Ebd41A8f0C4C8edFaB7e37cbe1ef79e8c1fa' │ 'Binance' │ 'veplus' │  'USDT-HOOK'  │ 2.171562414028455  │         0          │                        []                        │ [ '0x55d398326f99059fF775485246999027B3197955', '0xa260E12d2B924cb899AE80BB58123ac3fEE1E2F0' ] │
    │    9    │ '0xE69312742A4718033cADbf323AE2dab7C4bb62D9' │ 'Binance' │ 'veplus' │  'MBOX-USDT'  │ 2.0396325349054036 │         0          │                        []                        │ [ '0x3203c9E46cA618C8C1cE5dC67e7e9D75f5da2377', '0x55d398326f99059fF775485246999027B3197955' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴──────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
