### PR TITLE
add fvm.exchange

### PR DESCRIPTION
**Pull request by oxSaturn**
Add yield for https://defillama.com/protocol/fvm-exchange.

FVM exchange is a dex forked from solidly, but it rewards LPs with option to buy token instead of liquid ones, those oToken can be redeemed to liquid ones at a certain discount, which is the profit LPs can take.

### CODE REVIEW

**Comment by llamatester** [comment]
The fvm-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       319 passed, 319 total
    Snapshots:   0 total
    Time:        0.435 s
    Ran all test suites.
    
    Nb of pools: 45
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain   │    project     │     symbol     │       tvlUsd       │     apyReward      │                                                                         rewardTokens                                                                          │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼──────────┼────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0E8f117a563Be78Eb5A391A066d0d43Dd187a9E0' │ 'Fantom' │ 'fvm-exchange' │   'FVM-WFTM'   │ 480957.9225308097  │ 300.2820873039386  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x07BB65fAaC502d4996532F834A1B7ba5dC32Ff96', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    1    │ '0x1a35C7357BC8D0eB9342d73D4f13c4a6f64AC1d6' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-USDC'   │ 375597.0754843853  │ 9.745452156502346  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    2    │ '0x3ACffB18eF4ae1dd1E048ca6d3f364e8A0B62fA5' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-WFTM' │ 364369.96146713325 │ 17.05015595255424  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    3    │ '0xDb0f33978B5366191C42Bb9A7B7d886Cb714dF65' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-USDC' │ 324041.46605478553 │ 8.679911514606694  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    4    │ '0x40c1AA3fD0951a1C1AD960Ae0E88a63E95766fa4' │ 'Fantom' │ 'fvm-exchange' │  'MCLB-FBOMB'  │ 250914.1614574247  │ 24.835253237712493 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x5DeB27e51dbeEF691Ba1175A2E563870499c2AcB', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    5    │ '0xB4A46699427F6C40072706067b7DF62823d69466' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-FBOMB'  │ 174155.43143389723 │ 7.440929501033948  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    6    │ '0x74975f880D6dF7AD4Dd4C0016d49dbE9cF9d65E0' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-DEUS'   │ 170479.80583278125 │ 94.99789600128908  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44' ] │
    │    7    │ '0xebd8Bf837EC2448608E34Fa450e28d79dAb84b9f' │ 'Fantom' │ 'fvm-exchange' │ 'WFTM-SCREAM'  │ 154973.47359802783 │ 21.203610806056584 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xe0654C8e6fd4D733349ac7E09f6f23DA256bF475' ] │
    │    8    │ '0xAC8909fB68C33fFBf977E55b07b5Fe85552Ef97d' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-SFTMX'  │ 135734.2392519858  │ 7.721432004934979  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xd7028092c830b5C8FcE061Af2E593413EbbC1fc1' ] │
    │    9    │ '0x8a662B2C75b01C6B215ed5A8506b7B884a8E4a56' │ 'Fantom' │ 'fvm-exchange' │ 'WFTM-AXLLQDR' │ 112378.6201403399  │ 39.32246276299309  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x4b6B3d425F82248996D77EcC3F3df1E500aaC1db' ] │
    └─────────┴──────────────────────────────────────────────┴──────────┴────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The fvm-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       319 passed, 319 total
    Snapshots:   0 total
    Time:        0.434 s
    Ran all test suites.
    
    Nb of pools: 45
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain   │    project     │     symbol     │       tvlUsd       │     apyReward      │                                                                         rewardTokens                                                                          │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼──────────┼────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0E8f117a563Be78Eb5A391A066d0d43Dd187a9E0' │ 'Fantom' │ 'fvm-exchange' │   'FVM-WFTM'   │ 479082.35126293614 │ 260.79627088654195 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x07BB65fAaC502d4996532F834A1B7ba5dC32Ff96', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    1    │ '0x1a35C7357BC8D0eB9342d73D4f13c4a6f64AC1d6' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-USDC'   │ 374133.3908774231  │ 9.793198420139348  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    2    │ '0x3ACffB18eF4ae1dd1E048ca6d3f364e8A0B62fA5' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-WFTM' │ 362769.0391041967  │ 17.048310041897512 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    3    │ '0xDb0f33978B5366191C42Bb9A7B7d886Cb714dF65' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-USDC' │ 324199.34318533115 │ 8.684215335238598  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    4    │ '0x40c1AA3fD0951a1C1AD960Ae0E88a63E95766fa4' │ 'Fantom' │ 'fvm-exchange' │  'MCLB-FBOMB'  │ 249901.1517021812  │ 24.960445736549516 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x5DeB27e51dbeEF691Ba1175A2E563870499c2AcB', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    5    │ '0xB4A46699427F6C40072706067b7DF62823d69466' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-FBOMB'  │ 173359.14964912576 │ 7.482457752699821  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    6    │ '0x74975f880D6dF7AD4Dd4C0016d49dbE9cF9d65E0' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-DEUS'   │ 169463.54465442777 │ 95.66156260154706  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44' ] │
    │    7    │ '0xebd8Bf837EC2448608E34Fa450e28d79dAb84b9f' │ 'Fantom' │ 'fvm-exchange' │ 'WFTM-SCREAM'  │ 155259.0485783428  │ 21.185421022756433 │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xe0654C8e6fd4D733349ac7E09f6f23DA256bF475' ] │
    │    8    │ '0xAC8909fB68C33fFBf977E55b07b5Fe85552Ef97d' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-SFTMX'  │ 134567.55130486685 │ 7.796034332399484  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xd7028092c830b5C8FcE061Af2E593413EbbC1fc1' ] │
    │    9    │ '0x8a662B2C75b01C6B215ed5A8506b7B884a8E4a56' │ 'Fantom' │ 'fvm-exchange' │ 'WFTM-AXLLQDR' │ 111401.98636232616 │ 39.70619751318731  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x4b6B3d425F82248996D77EcC3F3df1E500aaC1db' ] │
    └─────────┴──────────────────────────────────────────────┴──────────┴────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hm, but rn the adapter outputs 260 apr, which is upper bound?
others seem high too, like axlusdx-wtfm with 17, whereas lower bound on your ui is 8

**Comment by oxSaturn** [comment]
> hm, but rn the adapter outputs 260 apr, which is upper bound? others seem high too, like axlusdx-wtfm with 17, whereas lower bound on your ui is 8

Let me take the below image for example:

image

The upper would be 263%+183%=446% while lower is 263%+39%.

Yeah, we did notice some discrepancies between here and our UI. Still investigate why our UI is lower in some cases.

Will let you know once we figure out what's going on. cc @t0rbik

**Comment by llamatester** [comment]
The fvm-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       319 passed, 319 total
    Snapshots:   0 total
    Time:        0.6 s
    Ran all test suites.
    
    Nb of pools: 45
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain   │    project     │     symbol     │       tvlUsd       │     apyReward      │                                                                         rewardTokens                                                                          │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼──────────┼────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0E8f117a563Be78Eb5A391A066d0d43Dd187a9E0' │ 'Fantom' │ 'fvm-exchange' │   'FVM-WFTM'   │ 475973.1416245379  │ 261.8427884208242  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x07BB65fAaC502d4996532F834A1B7ba5dC32Ff96', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    1    │ '0x1a35C7357BC8D0eB9342d73D4f13c4a6f64AC1d6' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-USDC'   │  374345.433227591  │ 5.954832135826536  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    2    │ '0x3ACffB18eF4ae1dd1E048ca6d3f364e8A0B62fA5' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-WFTM' │ 362691.2363693334  │ 7.414182424523842  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    3    │ '0xDb0f33978B5366191C42Bb9A7B7d886Cb714dF65' │ 'Fantom' │ 'fvm-exchange' │ 'AXLUSDC-USDC' │ 324484.3562627223  │ 8.559472112803155  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x1B6382DBDEa11d97f24495C9A90b7c88469134a4', '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf' ] │
    │    4    │ '0x40c1AA3fD0951a1C1AD960Ae0E88a63E95766fa4' │ 'Fantom' │ 'fvm-exchange' │  'MCLB-FBOMB'  │ 254928.1084548995  │ 24.13797879415582  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x5DeB27e51dbeEF691Ba1175A2E563870499c2AcB', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    5    │ '0xB4A46699427F6C40072706067b7DF62823d69466' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-FBOMB'  │ 174673.06534066552 │  7.32593617107788  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74ccbe53F77b08632ce0CB91D3A545bF6B8E0979' ] │
    │    6    │ '0x74975f880D6dF7AD4Dd4C0016d49dbE9cF9d65E0' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-DEUS'   │ 169357.4651042525  │ 60.28407509811849  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xDE5ed76E7c05eC5e4572CfC88d1ACEA165109E44' ] │
    │    7    │ '0xebd8Bf837EC2448608E34Fa450e28d79dAb84b9f' │ 'Fantom' │ 'fvm-exchange' │ 'WFTM-SCREAM'  │ 152346.16097882297 │ 21.29906484398573  │         [ '0x21ada0d2ac28c3a5fa3cd2ee30882da8812279b6', '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D' ]          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xe0654C8e6fd4D733349ac7E09f6f23DA256bF475' ] │
    │    8    │ '0xAC8909fB68C33fFBf977E55b07b5Fe85552Ef97d' │ 'Fantom' │ 'fvm-exchange' │  'WFTM-SFTMX'  │ 134444.27906236675 │ 2.5457491275412245 │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xd7028092c830b5C8FcE061Af2E593413EbbC1fc1' ] │
    │    9    │ '0xF8eed2665FD11a8431fc41b2582fD5E72a1606f0' │ 'Fantom' │ 'fvm-exchange' │   'WFTM-MPX'   │ 105694.88472202493 │ 91.36609081751872  │ [ '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44', '0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D', ... 1 more item ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x66eEd5FF1701E6ed8470DC391F05e27B1d0657eb' ] │
    └─────────┴──────────────────────────────────────────────┴──────────┴────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by oxSaturn** [comment]
@slasher125 Hi, I've updated the code to keep the apr consistent with our site. Let me know if you have any further concern.

**Comment by oxSaturn** [comment]
@slasher125 Any idea how long it will take to show data on the page here https://defillama.com/protocol/fvm-exchange? Or do I miss something else?

**Comment by oxSaturn** [comment]
> @slasher125 Any idea how long it will take to show data on the page here https://defillama.com/protocol/fvm-exchange? Or do I miss something else?

Oh, see it now, awesome!

**Pull request merged**
