### PR TITLE
feat: velo aero slipstream yields

### PR DESCRIPTION
**Pull request by ethzoomer**

### CODE REVIEW

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       522 passed, 522 total
    Snapshots:   0 total
    Time:        0.388 s
    Ran all test suites.
    
    Nb of pools: 74
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬────────────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │        project         │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────┼────────────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x47cA96Ea59C13F72745928887f84C9F52C3D7348' │ 'Base' │ 'aerodrome-slipstream' │ 'cbETH-WETH'  │ 14603876.395022463 │ 13.277042973876297 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │
    │    1    │ '0x0c1A09d5D0445047DA3Ab4994262b22404288A3B' │ 'Base' │ 'aerodrome-slipstream' │  'USDC-USD+'  │ 13624609.75615877  │  46.2318144422097  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │
    │    2    │ '0x861A2922bE165a5Bd41b1E482B49216b465e1B5F' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-wstETH' │ 13197951.475023238 │ 22.733624064369764 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │
    │    3    │ '0x98c7A2338336d2d354663246F64676009c7bDa97' │ 'Base' │ 'aerodrome-slipstream' │ 'USDC-USDbC'  │ 12046099.59746327  │ 16.096224438094588 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    │    4    │ '0xb2cc224c1c9feE385f8ad6a55b4d94E92359DC59' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USDC'  │ 11928714.566818286 │ 3784.6335324414326 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │
    │    5    │ '0x2ae9DF02539887d4EbcE0230168a302d34784c82' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-bsdETH' │  4633240.15071504  │ 13.04692200723984  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff' ] │
    │    6    │ '0xE846373C1a92B167b4E9cd5d8E4d6B1Db9E90EC7' │ 'Base' │ 'aerodrome-slipstream' │  'EURC-USDC'  │ 2909027.2489480926 │ 30.254644474164742 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x60a3E35Cc302bFA44Cb288Bc5a4F316Fdb1adb42', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │
    │    7    │ '0x82321f3BEB69f503380D6B233857d5C43562e2D0' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-AERO'  │ 2695544.476540841  │ 1548.2367366611122 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │
    │    8    │ '0x4e829F8A5213c42535AB84AA40BD4aDCCE9cBa02' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-BRETT'  │ 2094560.592833242  │ 3701.305888011907  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x532f27101965dd16442E59d40670FaF5eBB142E4' ] │
    │    9    │ '0x2092f4acbb18BB1649595DF59B9Cb601bBA1EBB7' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-RDNT'  │ 2060024.8419030258 │ 2925.7940922344224 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xd722E55C1d9D9fA0021A5215Cbb904b92B3dC5d4' ] │
    └─────────┴──────────────────────────────────────────────┴────────┴────────────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi @ethzoomer pls only add 1 adapter per PR

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       529 passed, 529 total
    Snapshots:   0 total
    Time:        0.42 s
    Ran all test suites.
    
    Nb of pools: 75
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬────────────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │        project         │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────┼────────────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0c1A09d5D0445047DA3Ab4994262b22404288A3B' │ 'Base' │ 'aerodrome-slipstream' │  'USDC-USD+'  │ 14121793.459642103 │ 42.073057795006896 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │
    │    1    │ '0x47cA96Ea59C13F72745928887f84C9F52C3D7348' │ 'Base' │ 'aerodrome-slipstream' │ 'cbETH-WETH'  │ 14002944.525487697 │ 12.946733400757141 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │
    │    2    │ '0x861A2922bE165a5Bd41b1E482B49216b465e1B5F' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-wstETH' │ 13157113.877988106 │ 20.68769805680694  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │
    │    3    │ '0x98c7A2338336d2d354663246F64676009c7bDa97' │ 'Base' │ 'aerodrome-slipstream' │ 'USDC-USDbC'  │ 12063744.759102803 │ 15.353453809164746 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    │    4    │ '0xb2cc224c1c9feE385f8ad6a55b4d94E92359DC59' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USDC'  │ 11171144.223341968 │ 6083.573150957321  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │
    │    5    │ '0x2ae9DF02539887d4EbcE0230168a302d34784c82' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-bsdETH' │ 4546824.449674918  │ 12.739404496462402 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff' ] │
    │    6    │ '0x82321f3BEB69f503380D6B233857d5C43562e2D0' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-AERO'  │ 2821545.7865064116 │ 1086.9908992172452 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │
    │    7    │ '0x2092f4acbb18BB1649595DF59B9Cb601bBA1EBB7' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-RDNT'  │ 2372197.092435385  │ 2650.0544132232767 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xd722E55C1d9D9fA0021A5215Cbb904b92B3dC5d4' ] │
    │    8    │ '0x4e829F8A5213c42535AB84AA40BD4aDCCE9cBa02' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-BRETT'  │ 1975018.2941785175 │ 4641.561379136294  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x532f27101965dd16442E59d40670FaF5eBB142E4' ] │
    │    9    │ '0x4D69971CCd4A636c403a3C1B00c85e99bB9B5606' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USD+'  │ 1970156.6002695311 │ 4616.395108026016  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │
    └─────────┴──────────────────────────────────────────────┴────────┴────────────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The aerodrome-slipstream adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       536 passed, 536 total
    Snapshots:   0 total
    Time:        0.394 s
    Ran all test suites.
    
    Nb of pools: 76
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬────────────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │        project         │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼────────┼────────────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0c1A09d5D0445047DA3Ab4994262b22404288A3B' │ 'Base' │ 'aerodrome-slipstream' │  'USDC-USD+'  │ 14034201.031574212 │ 50.99225176722655  │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │
    │    1    │ '0x861A2922bE165a5Bd41b1E482B49216b465e1B5F' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-wstETH' │ 12782555.651825726 │ 25.542202063181403 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │
    │    2    │ '0x47cA96Ea59C13F72745928887f84C9F52C3D7348' │ 'Base' │ 'aerodrome-slipstream' │ 'cbETH-WETH'  │ 12488053.973777115 │ 17.140834328439205 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │
    │    3    │ '0xb2cc224c1c9feE385f8ad6a55b4d94E92359DC59' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USDC'  │ 12335396.47963725  │ 3891.9883730696015 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' ] │
    │    4    │ '0x98c7A2338336d2d354663246F64676009c7bDa97' │ 'Base' │ 'aerodrome-slipstream' │ 'USDC-USDbC'  │ 11895456.727513958 │ 13.324356985460357 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    │    5    │ '0x2ae9DF02539887d4EbcE0230168a302d34784c82' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-bsdETH' │ 4459070.561717118  │ 13.503753293590085 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xCb327b99fF831bF8223cCEd12B1338FF3aA322Ff' ] │
    │    6    │ '0x82321f3BEB69f503380D6B233857d5C43562e2D0' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-AERO'  │  2618516.84545504  │ 1138.8186698444615 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │
    │    7    │ '0x2092f4acbb18BB1649595DF59B9Cb601bBA1EBB7' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-RDNT'  │ 2452590.0676182793 │ 3151.1269820022935 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xd722E55C1d9D9fA0021A5215Cbb904b92B3dC5d4' ] │
    │    8    │ '0x4D69971CCd4A636c403a3C1B00c85e99bB9B5606' │ 'Base' │ 'aerodrome-slipstream' │  'WETH-USD+'  │ 1972028.583289512  │ 3152.1519356683716 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376' ] │
    │    9    │ '0x4e829F8A5213c42535AB84AA40BD4aDCCE9cBa02' │ 'Base' │ 'aerodrome-slipstream' │ 'WETH-BRETT'  │ 1779605.5522660613 │ 3738.8169886974806 │ [ '0x940181a94A35A4569E4529A3CDfB74e38FD98631' ] │ [ '0x4200000000000000000000000000000000000006', '0x532f27101965dd16442E59d40670FaF5eBB142E4' ] │
    └─────────┴──────────────────────────────────────────────┴────────┴────────────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
