### PR TITLE
Aqua Patina APY adapter

### PR DESCRIPTION
**Pull request by sponnet**
aqua patina APY calculation

### CODE REVIEW

**Comment by llamatester** [comment]
The aqua-patina adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.276 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬─────────┬───────────┬──────┐
    │ (index) │                     pool                     │   chain    │    project    │ symbol  │  tvlUsd   │ apy  │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼─────────┼───────────┼──────┤
    │    0    │ '0xAaAaAAaBC6CBc3A1FD3a0fe0FDec43251C6562F5' │ 'Ethereum' │ 'aqua-patina' │ 'APETH' │ 939694.29 │ 8.07 │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴─────────┴───────────┴──────┘

**Comment by slasher125** [comment]
gm, how is the apy calculated?

**Comment by sponnet** [comment]
TVL versus contract's ETH balance - averaged out over 7 days. We are updating our api backend to reflect this value on a rolling basis. I will ping you here when that is deployed (should be done tomorrow hopefully) Please wait with merging this PR until that is done. 
Currently at DevCon so updates are a bit slower than usual. Thx.

**Comment by sponnet** [comment]
hey @slasher125 - the API endpoint now returns the 10-day moving average APY, which is calculated and updated daily from onchain data. If you need more details let me know. This PR is ready to be merged from our side. Thanks !

**Comment by llamatester** [comment]
The aqua-patina adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.278 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬─────────┬────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │ symbol  │   tvlUsd   │        apy        │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼─────────┼────────────┼───────────────────┤
    │    0    │ '0xAaAaAAaBC6CBc3A1FD3a0fe0FDec43251C6562F5' │ 'Ethereum' │ 'aqua-patina' │ 'APETH' │ 1005416.64 │ 8.008956132833893 │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴─────────┴────────────┴───────────────────┘

**Pull request merged**
