### PR TITLE
add kagla-finance

### PR DESCRIPTION
**Pull request by wolfwarrier14**

### CODE REVIEW

**Comment by llamatester** [comment]
The kagla-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.386 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────────────┬─────────────────┬────────────────────┬───────────────────────┬──────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project     │     symbol      │       tvlUsd       │        apyBase        │      apyReward       │                                                                       underlyingTokens                                                                        │                   rewardTokens                   │                                     url                                      │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────────────┼─────────────────┼────────────────────┼───────────────────────┼──────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' │ 'astar' │ 'kagla-finance' │   'USDT+3KGL'   │ 569228.5209624791  │  0.0436924926740363   │ 0.11252014426094892  │ [ '0xfFFfffFF000000000000000000000001000007C0', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' ] │ 'https://kagla.finance/app/pools/0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' │
    │    1    │ '0xeB97BC7C4ca99Fa8078fF879905338517821B9F5' │ 'astar' │ 'kagla-finance' │     '3Pool'     │ 412745.2037455562  │ 0.0037739842604396223 │ 0.009459445854836046 │         [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ]          │ [ '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ] │ 'https://kagla.finance/app/pools/0xeB97BC7C4ca99Fa8078fF879905338517821B9F5' │
    │    2    │ '0x327d5322242B5558bebA1dfb9C02A9Da63551D67' │ 'astar' │ 'kagla-finance' │  'ASTR/nASTR'   │ 321948.9089364329  │ 0.003642914818823728  │ 0.009130100889503945 │                                [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xE511ED88575C57767BAfb72BfD10775413E3F2b0' ]                                 │ [ '0x847f0Fd7e3A234E7321D01fF2347E4501eA89cF1' ] │ 'https://kagla.finance/app/pools/0x327d5322242B5558bebA1dfb9C02A9Da63551D67' │
    │    3    │ '0xED29Ca5c39E35793F63f4485873ABBB52Cb29308' │ 'astar' │ 'kagla-finance' │ 'Starlay 3Pool' │ 52477.82184181686  │ 0.011021429683833128  │ 0.027762481055752408 │         [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ]          │ [ '0x60811F3d54e860cDf01D72ED422a700e9cf010a9' ] │ 'https://kagla.finance/app/pools/0xED29Ca5c39E35793F63f4485873ABBB52Cb29308' │
    │    4    │ '0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' │ 'astar' │ 'kagla-finance' │   'aUSD+3KGL'   │ 19717.560332373698 │ 0.015682248155784784  │ 0.03962868241034245  │ [ '0xfFFFFfFF00000000000000010000000000000001', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' ] │ 'https://kagla.finance/app/pools/0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' │
    │    5    │ '0x4fD9011F0867e7e8AF7608Ad1BB969Da8b0aBa9B' │ 'astar' │ 'kagla-finance' │   'LAY/muLAY'   │ 11877.372253797412 │  0.07722361502736996  │ 0.20335079490576113  │                                [ '0xc4335B1b76fA6d52877b3046ECA68F6E708a27dd', '0xDDF2ad1d9bFA208228166311FC22e76Ea7a4C44D' ]                                 │ [ '0x5c71534Db6e54322943AD429209D97Fa25bBFcd2' ] │ 'https://kagla.finance/app/pools/0x4fD9011F0867e7e8AF7608Ad1BB969Da8b0aBa9B' │
    │    6    │ '0x247f10E06536dD774f11FA5F8309C21b6647FC9a' │ 'astar' │ 'kagla-finance' │   'BUSD+3KGL'   │  11020.8612365758  │ 0.001779634915878514  │ 0.004454531281177898 │ [ '0x4Bf769b05E832FCdc9053fFFBC78Ca889aCb5E1E', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0x11baa439EFf75B80a72b889e171d6E95FB39ee11' ] │ 'https://kagla.finance/app/pools/0x247f10E06536dD774f11FA5F8309C21b6647FC9a' │
    │    7    │ '0x60B26Fd3251Bc15045e3f94a2C30751a022dFCC3' │ 'astar' │ 'kagla-finance' │   'BAI+3KGL'    │ 3029.1447795635067 │ 0.009090340594690938  │ 0.022867950514217306 │ [ '0x733ebcC6DF85f8266349DEFD0980f8Ced9B45f35', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0x00D41391B0d455fDAD49Bc6Fb8F590DB844403B6' ] │ 'https://kagla.finance/app/pools/0x60B26Fd3251Bc15045e3f94a2C30751a022dFCC3' │
    │    8    │ '0x578AA1be6D258677e80c9067711861dd981a663E' │ 'astar' │ 'kagla-finance' │   'KGL/muKGL'   │ 2582.940990883507  │ 0.007352240952366307  │ 0.018473547962898795 │                                [ '0x257f1a047948f73158DaDd03eB84b34498bCDc60', '0x5eaAe8435B178d4677904430BAc5079e73aFa56e' ]                                 │ [ '0xb91E7aBCbF38d0CAc1f99b062b75AE0c18e169d1' ] │ 'https://kagla.finance/app/pools/0x578AA1be6D258677e80c9067711861dd981a663E' │
    │    9    │ '0xbb70f16f2a115aF2Faf3b8abFEfaf61969909a21' │ 'astar' │ 'kagla-finance' │   'oUSD+3KGL'   │ 1253.7578129990325 │  0.17053823671361967  │  0.4767614781207996  │ [ '0x29F6e49c6E3397C3A84F715885F9F233A441165C', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xea84bedb14577e22B545FF7B07548A48b3B08D84' ] │ 'https://kagla.finance/app/pools/0xbb70f16f2a115aF2Faf3b8abFEfaf61969909a21' │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────────────┴─────────────────┴────────────────────┴───────────────────────┴──────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, ty for adding:
- apy values need to be in %
- not sure why u are adding both min and max reward apr. we only display min values + these needs to be apyReward. So use the current value for apyBase * 100 as apyReward instead

**Comment by llamatester** [comment]
The kagla-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.457 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬─────────────────┬─────────────────┬────────────────────┬─────────────────────┬─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project     │     symbol      │       tvlUsd       │       apyBase       │      apyReward      │                                                                       underlyingTokens                                                                        │                   rewardTokens                   │                                     url                                      │
    ├─────────┼──────────────────────────────────────────────┼─────────┼─────────────────┼─────────────────┼────────────────────┼─────────────────────┼─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' │ 'astar' │ 'kagla-finance' │   'USDT+3KGL'   │ 569228.5633992545  │ 4.3289031587965265  │ 4.3289031587965265  │ [ '0xfFFfffFF000000000000000000000001000007C0', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' ] │ 'https://kagla.finance/app/pools/0xDc1C5bAbB4dad3117Fd46d542f3b356D171417fA' │
    │    1    │ '0xeB97BC7C4ca99Fa8078fF879905338517821B9F5' │ 'astar' │ 'kagla-finance' │     '3Pool'     │ 412556.7954595966  │ 0.3739744026978853  │ 0.3739744026978853  │         [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ]          │ [ '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ] │ 'https://kagla.finance/app/pools/0xeB97BC7C4ca99Fa8078fF879905338517821B9F5' │
    │    2    │ '0x327d5322242B5558bebA1dfb9C02A9Da63551D67' │ 'astar' │ 'kagla-finance' │  'ASTR/nASTR'   │  318487.266997068  │ 0.3642914818823728  │ 0.3642914818823728  │                                [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xE511ED88575C57767BAfb72BfD10775413E3F2b0' ]                                 │ [ '0x847f0Fd7e3A234E7321D01fF2347E4501eA89cF1' ] │ 'https://kagla.finance/app/pools/0x327d5322242B5558bebA1dfb9C02A9Da63551D67' │
    │    3    │ '0xED29Ca5c39E35793F63f4485873ABBB52Cb29308' │ 'astar' │ 'kagla-finance' │ 'Starlay 3Pool' │ 52478.290095710065 │ 1.0921011882325748  │ 1.0921011882325748  │         [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ]          │ [ '0x60811F3d54e860cDf01D72ED422a700e9cf010a9' ] │ 'https://kagla.finance/app/pools/0xED29Ca5c39E35793F63f4485873ABBB52Cb29308' │
    │    4    │ '0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' │ 'astar' │ 'kagla-finance' │   'aUSD+3KGL'   │ 19717.561425324522 │ 1.5539205813755785  │ 1.5539205813755785  │ [ '0xfFFFFfFF00000000000000010000000000000001', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' ] │ 'https://kagla.finance/app/pools/0xe12332a6118832CBAfC1913Ec5D8C3a05E6Fd880' │
    │    5    │ '0x4fD9011F0867e7e8AF7608Ad1BB969Da8b0aBa9B' │ 'astar' │ 'kagla-finance' │   'LAY/muLAY'   │ 11756.069400164817 │  7.723058383234083  │  7.723058383234083  │                                [ '0xc4335B1b76fA6d52877b3046ECA68F6E708a27dd', '0xDDF2ad1d9bFA208228166311FC22e76Ea7a4C44D' ]                                 │ [ '0x5c71534Db6e54322943AD429209D97Fa25bBFcd2' ] │ 'https://kagla.finance/app/pools/0x4fD9011F0867e7e8AF7608Ad1BB969Da8b0aBa9B' │
    │    6    │ '0x247f10E06536dD774f11FA5F8309C21b6647FC9a' │ 'astar' │ 'kagla-finance' │   'BUSD+3KGL'   │ 11020.890431017442 │ 0.17634989070964835 │ 0.17634989070964835 │ [ '0x4Bf769b05E832FCdc9053fFFBC78Ca889aCb5E1E', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0x11baa439EFf75B80a72b889e171d6E95FB39ee11' ] │ 'https://kagla.finance/app/pools/0x247f10E06536dD774f11FA5F8309C21b6647FC9a' │
    │    7    │ '0x60B26Fd3251Bc15045e3f94a2C30751a022dFCC3' │ 'astar' │ 'kagla-finance' │   'BAI+3KGL'    │ 3029.2033486860673 │ 0.9007494878757072  │ 0.9007494878757072  │ [ '0x733ebcC6DF85f8266349DEFD0980f8Ced9B45f35', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0x00D41391B0d455fDAD49Bc6Fb8F590DB844403B6' ] │ 'https://kagla.finance/app/pools/0x60B26Fd3251Bc15045e3f94a2C30751a022dFCC3' │
    │    8    │ '0x578AA1be6D258677e80c9067711861dd981a663E' │ 'astar' │ 'kagla-finance' │   'KGL/muKGL'   │ 2552.906793315094  │ 0.7352240952366307  │ 0.7352240952366307  │                                [ '0x257f1a047948f73158DaDd03eB84b34498bCDc60', '0x5eaAe8435B178d4677904430BAc5079e73aFa56e' ]                                 │ [ '0xb91E7aBCbF38d0CAc1f99b062b75AE0c18e169d1' ] │ 'https://kagla.finance/app/pools/0x578AA1be6D258677e80c9067711861dd981a663E' │
    │    9    │ '0xbb70f16f2a115aF2Faf3b8abFEfaf61969909a21' │ 'astar' │ 'kagla-finance' │   'oUSD+3KGL'   │ 1253.757829368633  │ 16.888083797214783  │ 16.888083797214783  │ [ '0x29F6e49c6E3397C3A84F715885F9F233A441165C', '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', ... 1 more item ] │ [ '0xea84bedb14577e22B545FF7B07548A48b3B08D84' ] │ 'https://kagla.finance/app/pools/0xbb70f16f2a115aF2Faf3b8abFEfaf61969909a21' │
    └─────────┴──────────────────────────────────────────────┴─────────┴─────────────────┴─────────────────┴────────────────────┴─────────────────────┴─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
don't forget to drop apyBase, given all apy is coming from incentives

**Pull request merged**
