### PR TITLE
Add holdstation-defutures

### PR DESCRIPTION
**Pull request by holdstation**

### CODE REVIEW

**Comment by llamatester** [comment]
The holdstation-defutures adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.33 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────┬──────────────┬─────────────────────────┬────────┬───────────────┬───────┬──────────────────────────────────────────────────┐
    │ (index) │                          pool                           │    chain     │         project         │ symbol │    tvlUsd     │  apy  │                 underlyingTokens                 │
    ├─────────┼─────────────────────────────────────────────────────────┼──────────────┼─────────────────────────┼────────┼───────────────┼───────┼──────────────────────────────────────────────────┤
    │    0    │ '0xaf08a9d918f16332f22cf8dc9abe9d9e14ddcbc2-zksync_era' │ 'ZKSYNC-ERA' │ 'holdstation-defutures' │ 'USDC' │ 686034.591303 │ 13.46 │ [ '0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4' ] │
    └─────────┴─────────────────────────────────────────────────────────┴──────────────┴─────────────────────────┴────────┴───────────────┴───────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hey, how is the apy calculated? make sure its computed over a 24h window

**Comment by holdstation** [comment]
APY is calculated based on the average 7 days trading fees on our exchange: Holdstation DeFutures, with the TVL of our USDC Vault. And yes, it is computed over a 24h window, updated daily.

**Comment by slasher125** [comment]
hmm, is it 24h or 7days? confused now,

anything over 7days goes into `apyBase7d`, `apyBase` should be over 24h

**Comment by llamatester** [comment]
The holdstation-defutures adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.317 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────┬──────────────┬─────────────────────────┬────────┬───────────────┬───────────┬─────────┬──────────────────────────────────────────────────┐
    │ (index) │                          pool                           │    chain     │         project         │ symbol │    tvlUsd     │ apyBase7d │ apyBase │                 underlyingTokens                 │
    ├─────────┼─────────────────────────────────────────────────────────┼──────────────┼─────────────────────────┼────────┼───────────────┼───────────┼─────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xaf08a9d918f16332f22cf8dc9abe9d9e14ddcbc2-zksync_era' │ 'ZKSYNC-ERA' │ 'holdstation-defutures' │ 'USDC' │ 743080.545154 │   20.62   │  10.41  │ [ '0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4' ] │
    └─────────┴─────────────────────────────────────────────────────────┴──────────────┴─────────────────────────┴────────┴───────────────┴───────────┴─────────┴──────────────────────────────────────────────────┘

**Comment by holdstation** [comment]
We have updated both 24h and 7d.

**Comment by holdstation** [comment]
Hi @slasher125 

Can you check it once more times, does it have any problems with these updated values?
We already added `apy7d` and `apyBase` (24h) on the latest commit.

**Comment by slasher125** [comment]
hey, i was on holiday. 

one other thing: i'm sure u have read the readme, do you guys have a subgraph or anything else from which we can pull data to calculate apr values directly in the adapter?

**Comment by holdstation** [comment]
Hi @slasher125 
There is no other way of obtaining that data on-chain, which is why we have to use the API. We asked about this issue on your Discord, and an admin said it's okay to use our API.

**Pull request merged**
