### PR TITLE
Flat Money: Add adaptor

### PR DESCRIPTION
**Pull request by D-Ig**
This is for [UNIT](https://flat.money/flatcoin) to be displayed at `Yield` section.

### CODE REVIEW

**Review by D-Ig — COMMENTED** [review]
dat PR number 😎

**Comment by D-Ig** [comment]
> pls change the import to `const sdk = require('@defillama/sdk');` (without the 5 suffix)

u sure? there is no single occurrence of `const sdk = require('@defillama/sdk');` in this entire repo

**Comment by D-Ig** [comment]
> pls change the import to `const sdk = require('@defillama/sdk');` (without the 5 suffix)

fyi tests pass for me locally:

image

**Comment by slasher125** [comment]
yes, i'm sure (i just refactored it)

**Comment by llamatester** [comment]
The flat-money adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.26 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────┬────────┬──────────────┬────────┬────────────────────┬─────────┬───────────┬──────────────┬──────────────────────────────────────────────────┐
    │ (index) │                       pool                        │ chain  │   project    │ symbol │       tvlUsd       │ apyBase │ apyReward │ rewardTokens │                 underlyingTokens                 │
    ├─────────┼───────────────────────────────────────────────────┼────────┼──────────────┼────────┼────────────────────┼─────────┼───────────┼──────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xb95fb324b8a2faf8ec4f76e3df46c718402736e2-base' │ 'Base' │ 'flat-money' │ 'UNIT' │ 3450059.5028091255 │  14.46  │   null    │      []      │ [ '0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c' ] │
    └─────────┴───────────────────────────────────────────────────┴────────┴──────────────┴────────┴────────────────────┴─────────┴───────────┴──────────────┴──────────────────────────────────────────────────┘

**Comment by D-Ig** [comment]
> yes, i'm sure (i just refactored it)

done

**Pull request merged**
