### PR TITLE
Feat: Added Wise Lending Adapter

### PR DESCRIPTION
**Pull request by byyyyyyyyy**

### CODE REVIEW

**Comment by llamatester** [comment]
The apeswap-amm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       270 passed, 270 total
    Snapshots:   0 total
    Time:        0.479 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────────┬───────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │    project    │    symbol     │       tvlUsd       │       apyBase       │      apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────────┼───────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x6Cf8654e85AB489cA7e70189046D507ebA233613' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WETH' │ 258059.54743346013 │          0          │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    1    │ '0x5b13B583D4317aB15186Ed660A1E4C65C10da659' │ 'Polygon' │ 'apeswap-amm' │  'USDC-DAI'   │ 118462.96801059802 │ 0.10216061895919823 │         NaN         │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    2    │ '0xd32f3139A214034A0f9777c87eE0a064c1FF6AE2' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-DAI'  │ 98389.67181238822  │ 1.6931794149412827  │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    3    │ '0xe82635a105c520fd58e597181cBf754961d51E3e' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WBTC' │ 94731.12819851462  │ 0.30077588650817366 │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    4    │ '0x65D43B64E3B31965Cd5EA367D4c2b94c03084797' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-USDT' │ 94705.53147217276  │ 0.6311021349830722  │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    5    │ '0xa4dfe1fdca0c341c1ba26550ec5128c89964f0db' │  'Telos'  │ 'apeswap-amm' │ 'TLOS-STLOS'  │ 64026.735963960185 │                     │  875.8488813168618  │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e', '0xB4B01216a5Bc8F1C8A33CD990A1239030E60C905' ] │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │
    │    6    │ '0x1E1aFE9D9c5f290d8F6996dDB190bd111908A43D' │ 'Binance' │ 'apeswap-amm' │  'BTCB-WBNB'  │ 49349.153217907355 │ 0.23604010949317605 │ 0.03701907912932945 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    7    │ '0xcBf71C04148e5C463223F07A64a50f2Df46B6cdc' │ 'Polygon' │ 'apeswap-amm' │  'ABR-USDC'   │ 37042.86934980125  │ 0.6543949339888497  │         NaN         │ [ '0x04429fbb948BBD09327763214b45e505A5293346', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    8    │ '0xA0C3Ef24414ED9C9B456740128d8E63D016A9e11' │ 'Binance' │ 'apeswap-amm' │  'ETH-WBNB'   │ 33356.13053061878  │ 0.2759872207022783  │ 0.10455775773976729 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    9    │ '0x0359001070cF696D5993E0697335157a6f7dB289' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-BNB'  │  33043.8866316488  │ 1.1236805330149144  │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────────┴───────────────┴────────────────────┴─────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi ty for adding, pls revert the change on apeswap-amm

**Comment by llamatester** [comment]
The apeswap-amm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       270 passed, 270 total
    Snapshots:   0 total
    Time:        0.329 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────────┬───────────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │    project    │    symbol     │       tvlUsd       │       apyBase       │      apyReward       │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────────┼───────────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x6Cf8654e85AB489cA7e70189046D507ebA233613' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WETH' │ 258202.68189669368 │          0          │         NaN          │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    1    │ '0x5b13B583D4317aB15186Ed660A1E4C65C10da659' │ 'Polygon' │ 'apeswap-amm' │  'USDC-DAI'   │ 118567.31766684569 │ 0.1021342893654215  │         NaN          │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    2    │ '0xd32f3139A214034A0f9777c87eE0a064c1FF6AE2' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-DAI'  │ 98406.84236513867  │ 1.7013947547178967  │         NaN          │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    3    │ '0xe82635a105c520fd58e597181cBf754961d51E3e' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WBTC' │ 94775.38279465858  │ 0.30191897832258974 │         NaN          │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    4    │ '0x65D43B64E3B31965Cd5EA367D4c2b94c03084797' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-USDT' │ 94726.05202575395  │ 0.6322145958269322  │         NaN          │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    5    │ '0xa4dfe1fdca0c341c1ba26550ec5128c89964f0db' │  'Telos'  │ 'apeswap-amm' │ 'TLOS-STLOS'  │ 64026.735963960185 │                     │  875.8488813168618   │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e', '0xB4B01216a5Bc8F1C8A33CD990A1239030E60C905' ] │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │
    │    6    │ '0x1E1aFE9D9c5f290d8F6996dDB190bd111908A43D' │ 'Binance' │ 'apeswap-amm' │  'BTCB-WBNB'  │ 49590.882496371305 │ 0.23501113379948013 │ 0.036815633820599575 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    7    │ '0xcBf71C04148e5C463223F07A64a50f2Df46B6cdc' │ 'Polygon' │ 'apeswap-amm' │  'ABR-USDC'   │ 36634.72072962401  │  0.68636818283804   │         NaN          │ [ '0x04429fbb948BBD09327763214b45e505A5293346', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    8    │ '0xA0C3Ef24414ED9C9B456740128d8E63D016A9e11' │ 'Binance' │ 'apeswap-amm' │  'ETH-WBNB'   │ 33382.08507908904  │ 0.2757726408256793  │ 0.10441124359892953  │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    9    │ '0x0359001070cF696D5993E0697335157a6f7dB289' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-BNB'  │ 33047.908302354575 │  1.123740493158192  │         NaN          │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────────┴───────────────┴────────────────────┴─────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
best to copy paste whats in master, and save without formatting, otherwise the tests won't display our projects output

**Comment by llamatester** [comment]
The apeswap-amm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       270 passed, 270 total
    Snapshots:   0 total
    Time:        0.373 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────────┬───────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │    project    │    symbol     │       tvlUsd       │       apyBase       │      apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────────┼───────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x6Cf8654e85AB489cA7e70189046D507ebA233613' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WETH' │ 257236.25642463763 │          0          │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    1    │ '0x5b13B583D4317aB15186Ed660A1E4C65C10da659' │ 'Polygon' │ 'apeswap-amm' │  'USDC-DAI'   │ 118685.88498451254 │ 0.10203225710831319 │         NaN         │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    2    │ '0xd32f3139A214034A0f9777c87eE0a064c1FF6AE2' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-DAI'  │  98059.3103045835  │ 1.7188925849432435  │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    3    │ '0x65D43B64E3B31965Cd5EA367D4c2b94c03084797' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-USDT' │ 94413.73051352326  │  0.63726432854334   │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    4    │ '0xe82635a105c520fd58e597181cBf754961d51E3e' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-WBTC' │ 94406.64594866752  │ 0.30481670921312265 │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    5    │ '0xa4dfe1fdca0c341c1ba26550ec5128c89964f0db' │  'Telos'  │ 'apeswap-amm' │ 'TLOS-STLOS'  │ 64026.735963960185 │                     │  875.8488813168618  │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e', '0xB4B01216a5Bc8F1C8A33CD990A1239030E60C905' ] │ [ '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │
    │    6    │ '0x1E1aFE9D9c5f290d8F6996dDB190bd111908A43D' │ 'Binance' │ 'apeswap-amm' │  'BTCB-WBNB'  │ 49303.23494264943  │ 0.23832850493140295 │ 0.03703286039876424 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    7    │ '0xcBf71C04148e5C463223F07A64a50f2Df46B6cdc' │ 'Polygon' │ 'apeswap-amm' │  'ABR-USDC'   │ 36473.677036928486 │ 0.6924845592085168  │         NaN         │ [ '0x04429fbb948BBD09327763214b45e505A5293346', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    │    8    │ '0xA0C3Ef24414ED9C9B456740128d8E63D016A9e11' │ 'Binance' │ 'apeswap-amm' │  'ETH-WBNB'   │ 33403.55791560962  │ 0.38760759353254226 │ 0.10435098574196865 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x603c7f932ED1fc6575303D8Fb018fDCBb0f39a95' ] │
    │    9    │ '0x0359001070cF696D5993E0697335157a6f7dB289' │ 'Polygon' │ 'apeswap-amm' │ 'WMATIC-BNB'  │ 32962.87608679785  │ 1.1266451288009212  │         NaN         │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xA649325Aa7C5093d12D6F98EB4378deAe68CE23F' ] │ [ '0x5d47baba0d66083c52009271faf3f50dcc01023c' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────────┴───────────────┴────────────────────┴─────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request closed without merging**
