### PR TITLE
yeti-finance adapter

### PR DESCRIPTION
**Pull request by 0xAces**
Yeti Finance Yield Adapter

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running yeti-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 99 passed, 100 total
    Snapshots:   0 total
    Time:        0.632 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬──────────────────────────┬─────────────┬────────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │           pool           │    chain    │    project     │   symbol    │       tvlUsd       │        apy         │                 underlyingTokens                 │
    ├─────────┼──────────────────────────┼─────────────┼────────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │    'Yeti aUSDC Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDC'   │ 27959964.230827767 │ 1.9357410039630276 │ [ '0x625E7708f30cA75bfd92586e17077590C60eb4cD' ] │
    │    1    │   'Yeti qiUSDCn Vault'   │ 'Avalanche' │ 'yeti-finance' │  'qiUSDCn'  │ 11471233.619078204 │ 2.7057702575018183 │ [ '0xB715808a78F6041E46d61Cb123C9B4A27056AE9C' ] │
    │    2    │    'Yeti aUSDT Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDT'   │ 8784515.685951948  │ 4.512263947612958  │ [ '0x6ab707Aca953eDAeFBc4fD23bA73294241490620' ] │
    │    3    │    'Yeti qiETH Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiETH'   │ 836904.2103354412  │ 0.9791673874764739 │ [ '0x334AD834Cd4481BB02d09615E7c11a00579A7909' ] │
    │    4    │    'Yeti sAVAX Vault'    │ 'Avalanche' │ 'yeti-finance' │   'sAVAX'   │ 626977.7321038523  │        5.76        │ [ '0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE' ] │
    │    5    │    'Yeti sJOE Vault'     │ 'Avalanche' │ 'yeti-finance' │   'sJOE'    │ 619511.8283213031  │ 17.57687164443656  │ [ '0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd' ] │
    │    6    │   'Yeti qiUSDC Vault'    │ 'Avalanche' │ 'yeti-finance' │  'qiUSDC'   │ 545252.9946922159  │ 1.7870743889473937 │ [ '0xBEb5d47A3f720Ec0a390d04b4d41ED7d9688bC7F' ] │
    │    7    │    'Yeti qiDAI Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiDAI'   │ 494417.9367377979  │  3.86691911099522  │ [ '0x835866d37AFB8CB8F8334dCCdaf66cf01832Ff5D' ] │
    │    8    │ 'Yeti AVAXUSDCJLP Vault' │ 'Avalanche' │ 'yeti-finance' │ 'AVAX-USDC' │ 108312.41471417627 │ 6.488201009994161  │ [ '0xf4003F4efBE8691B60249E6afbD307aBE7758adb' ] │
    │    9    │    'Yeti aDAI Vault'     │ 'Avalanche' │ 'yeti-finance' │   'aDAI'    │ 77600.57881962588  │  2.81085687214917  │ [ '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE' ] │
    └─────────┴──────────────────────────┴─────────────┴────────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    }

**Comment by 0xAces** [comment]
Could you advice on this failed test?

**Comment by llamatester** [comment]
Error while running yeti-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 99 passed, 100 total
    Snapshots:   0 total
    Time:        0.57 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬──────────────────────────┬─────────────┬────────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │           pool           │    chain    │    project     │   symbol    │       tvlUsd       │        apy         │                 underlyingTokens                 │
    ├─────────┼──────────────────────────┼─────────────┼────────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │    'Yeti-aUSDC-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDC'   │ 27960468.143448725 │ 1.9357410039630276 │ [ '0x625E7708f30cA75bfd92586e17077590C60eb4cD' ] │
    │    1    │   'Yeti-qiUSDCn-Vault'   │ 'Avalanche' │ 'yeti-finance' │  'qiUSDCn'  │ 11411333.14638542  │ 2.7057702575018183 │ [ '0xB715808a78F6041E46d61Cb123C9B4A27056AE9C' ] │
    │    2    │    'Yeti-aUSDT-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDT'   │ 8785042.189627852  │ 4.512263947612958  │ [ '0x6ab707Aca953eDAeFBc4fD23bA73294241490620' ] │
    │    3    │    'Yeti-qiETH-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiETH'   │  826081.705327009  │ 0.9791673874764739 │ [ '0x334AD834Cd4481BB02d09615E7c11a00579A7909' ] │
    │    4    │    'Yeti-sAVAX-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'sAVAX'   │ 628136.8731360848  │        5.76        │ [ '0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE' ] │
    │    5    │    'Yeti-sJOE-Vault'     │ 'Avalanche' │ 'yeti-finance' │   'sJOE'    │   605244.8867964   │ 17.57687164443656  │ [ '0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd' ] │
    │    6    │   'Yeti-qiUSDC-Vault'    │ 'Avalanche' │ 'yeti-finance' │  'qiUSDC'   │ 545268.0547818929  │ 1.7870743889473937 │ [ '0xBEb5d47A3f720Ec0a390d04b4d41ED7d9688bC7F' ] │
    │    7    │    'Yeti-qiDAI-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiDAI'   │ 494442.0211345909  │  3.86691911099522  │ [ '0x835866d37AFB8CB8F8334dCCdaf66cf01832Ff5D' ] │
    │    8    │ 'Yeti-AVAXUSDCJLP-Vault' │ 'Avalanche' │ 'yeti-finance' │ 'AVAX-USDC' │ 108273.15744661627 │ 6.488201009994161  │ [ '0xf4003F4efBE8691B60249E6afbD307aBE7758adb' ] │
    │    9    │    'Yeti-aDAI-Vault'     │ 'Avalanche' │ 'yeti-finance' │   'aDAI'    │ 77602.97037716661  │  2.81085687214917  │ [ '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE' ] │
    └─────────┴──────────────────────────┴─────────────┴────────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    }

**Comment by vrtnd** [comment]
Please add link to pools page 
```js
module.exports = {
...,
url: 'your_link'
}
```

**Comment by llamatester** [comment]
The yeti-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       100 passed, 100 total
    Snapshots:   0 total
    Time:        0.419 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬──────────────────────────┬─────────────┬────────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │           pool           │    chain    │    project     │   symbol    │       tvlUsd       │        apy         │                 underlyingTokens                 │
    ├─────────┼──────────────────────────┼─────────────┼────────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │    'Yeti-aUSDC-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDC'   │ 27965289.738534138 │ 1.926857461603433  │ [ '0x625E7708f30cA75bfd92586e17077590C60eb4cD' ] │
    │    1    │   'Yeti-qiUSDCn-Vault'   │ 'Avalanche' │ 'yeti-finance' │  'qiUSDCn'  │ 11413397.041519592 │ 2.8062972538369735 │ [ '0xB715808a78F6041E46d61Cb123C9B4A27056AE9C' ] │
    │    2    │    'Yeti-aUSDT-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'aUSDT'   │ 8785313.933460578  │ 3.8540084034538507 │ [ '0x6ab707Aca953eDAeFBc4fD23bA73294241490620' ] │
    │    3    │    'Yeti-qiETH-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiETH'   │ 828691.4446297914  │ 1.0262906922763004 │ [ '0x334AD834Cd4481BB02d09615E7c11a00579A7909' ] │
    │    4    │    'Yeti-sAVAX-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'sAVAX'   │ 624751.5488970045  │        5.76        │ [ '0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE' ] │
    │    5    │    'Yeti-sJOE-Vault'     │ 'Avalanche' │ 'yeti-finance' │   'sJOE'    │ 588797.4490507308  │ 19.01394458540454  │ [ '0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd' ] │
    │    6    │   'Yeti-qiUSDC-Vault'    │ 'Avalanche' │ 'yeti-finance' │  'qiUSDC'   │  545363.146867401  │ 1.7286552328868807 │ [ '0xBEb5d47A3f720Ec0a390d04b4d41ED7d9688bC7F' ] │
    │    7    │    'Yeti-qiDAI-Vault'    │ 'Avalanche' │ 'yeti-finance' │   'qiDAI'   │ 494457.10156627756 │ 3.8992991717231895 │ [ '0x835866d37AFB8CB8F8334dCCdaf66cf01832Ff5D' ] │
    │    8    │ 'Yeti-AVAXUSDCJLP-Vault' │ 'Avalanche' │ 'yeti-finance' │ 'AVAX-USDC' │ 107973.26721148666 │ 5.124319650576812  │ [ '0xf4003F4efBE8691B60249E6afbD307aBE7758adb' ] │
    │    9    │    'Yeti-aDAI-Vault'     │ 'Avalanche' │ 'yeti-finance' │   'aDAI'    │ 77604.22701409804  │ 2.8220801358402525 │ [ '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE' ] │
    └─────────┴──────────────────────────┴─────────────┴────────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
