### PR TITLE
feat: add pony-finance adaptor

### PR DESCRIPTION
**Pull request by brettkolodny**
Add [Pony Finance](https://ponyfinance.xyz/) adaptor

### CODE REVIEW

**Comment by vrtnd** [comment]
Failed tests

**Comment by llamatester** [comment]
Error while running pony-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.334 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬────────┬────────────┬─────────┐
    │ (index) │                     pool                     │   chain    │    project     │ symbol │   tvlUsd   │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼────────┼────────────┼─────────┤
    │    0    │ '0x0d97fee619d955509e54b046c9992b6e9f5b0630' │ 'Ethereum' │ 'pony-finance' │ 'PONY' │ 1062430.93 │ 0.07036 │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴────────┴────────────┴─────────┘
    }

**Comment by vrtnd** [comment]
1) Please add link to the pools page (`url` field) https://github.com/DefiLlama/yield-server#adapter-module-structure
2) Convert apyBase to % value (*100)

**Comment by brettkolodny** [comment]
> 1. Please add link to the pools page (`url` field) https://github.com/DefiLlama/yield-server#adapter-module-structure
> 2. Convert apyBase to % value (*100)

For 1 would something like this page https://www.scalara.xyz/indices/pony be acceptable? Pony is backed by stablecoin vaults across several different chains so there isn't a single URL outside of this one that would list all of them. The vaults can be found on the data section of the page.

**Comment by vrtnd** [comment]
> > 1. Please add link to the pools page (`url` field) https://github.com/DefiLlama/yield-server#adapter-module-structure
> > 2. Convert apyBase to % value (*100)
> 
> For 1 would something like this page https://www.scalara.xyz/indices/pony be acceptable? Pony is backed by stablecoin vaults across several different chains so there isn't a single URL outside of this one that would list all of them. The vaults can be found on the data section of the page.

I can't find data section, do u mind send me the link

**Comment by vrtnd** [comment]
or u mean this?
Screenshot 2022-08-16 at 16 45 45

**Comment by brettkolodny** [comment]
Yeah that's the page I was talking about

**Comment by vrtnd** [comment]
It's good, use this link then

**Comment by llamatester** [comment]
The pony-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.321 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬────────┬────────────┬─────────┐
    │ (index) │                     pool                     │   chain    │    project     │ symbol │   tvlUsd   │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼────────┼────────────┼─────────┤
    │    0    │ '0x0d97fee619d955509e54b046c9992b6e9f5b0630' │ 'Ethereum' │ 'pony-finance' │ 'PONY' │ 1062814.49 │ 5.4101  │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴────────┴────────────┴─────────┘

**Pull request merged**
