### PR TITLE
Add IPOR Fusion vaults

### PR DESCRIPTION
**Pull request by rav-ipor**

### CODE REVIEW

**Comment by llamatester** [comment]
The ipor-fusion adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.311 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬───────────────────────────────────────────────┬────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │                    symbol                     │   tvlUsd   │      apyBase       │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │                                            poolMeta                                            │                                        url                                         │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼───────────────────────────────────────────────┼────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x20e934c725b6703f0ac696f1689008057db9ac44' │ 'ethereum' │ 'ipor-fusion' │  'DAI (IPOR DAI Lending Optimizer Ethereum)'  │ 1131237.2  │ 5.354093054786544  │     0     │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │  'DAI on ethereum chain under management by vault named: IPOR DAI Lending Optimizer Ethereum'  │ 'https://app.ipor.info/fusion/ethereum/0x20e934c725b6703f0ac696f1689008057db9ac44' │
    │    1    │ '0x43ee0243ea8cf02f7087d8b16c8d2007cc9c7ca2' │ 'ethereum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Ethereum)' │ 1068683.66 │ 11.929489484755212 │ 6.810686  │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'USDC on ethereum chain under management by vault named: IPOR USDC Lending Optimizer Ethereum' │ 'https://app.ipor.info/fusion/ethereum/0x43ee0243ea8cf02f7087d8b16c8d2007cc9c7ca2' │
    │    2    │ '0xabab980f0ecb232d52f422c6b68d25c3d0c18e3e' │ 'ethereum' │ 'ipor-fusion' │ 'USDT (IPOR USDT Lending Optimizer Ethereum)' │ 971610.18  │ 21.50146307121011  │ 22.71483  │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ 'USDT on ethereum chain under management by vault named: IPOR USDT Lending Optimizer Ethereum' │ 'https://app.ipor.info/fusion/ethereum/0xabab980f0ecb232d52f422c6b68d25c3d0c18e3e' │
    │    3    │ '0xa91267a25939b2b0f046013fbf9597008f7f014b' │ 'arbitrum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Arbitrum)' │ 756217.53  │ 11.732971061214549 │     0     │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'USDC on arbitrum chain under management by vault named: IPOR USDC Lending Optimizer Arbitrum' │ 'https://app.ipor.info/fusion/arbitrum/0xa91267a25939b2b0f046013fbf9597008f7f014b' │
    │    4    │ '0x45aa96f0b3188d47a1dafdbefce1db6b37f58216' │   'base'   │ 'ipor-fusion' │   'USDC (IPOR USDC Lending Optimizer Base)'   │  23102.57  │ 13.711611844727795 │     0     │ [ '0xbd4e5C2f8dE5065993d29A9794E2B7cEfc41437A' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │     'USDC on base chain under management by vault named: IPOR USDC Lending Optimizer Base'     │   'https://app.ipor.info/fusion/base/0x45aa96f0b3188d47a1dafdbefce1db6b37f58216'   │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴───────────────────────────────────────────────┴────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
gm,

- symbol should only be the collateral, pls remove stuff like `(IPOR DAI Lending Optimizer Ethereum)`
- poolMeta is way to long, and i think not necessary in this case given there is just 1 pool of each asset anyways

**Comment by llamatester** [comment]
The ipor-fusion adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.32 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬───────────────────────────────────────────────┬────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │                    symbol                     │   tvlUsd   │      apyBase       │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │                                            poolMeta                                            │          url          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼───────────────────────────────────────────────┼────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────┤
    │    0    │ '0x20e934c725b6703f0ac696f1689008057db9ac44' │ 'ethereum' │ 'ipor-fusion' │  'DAI (IPOR DAI Lending Optimizer Ethereum)'  │ 1131294.15 │ 5.354093054786544  │     0     │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │  'DAI on ethereum chain under management by vault named: IPOR DAI Lending Optimizer Ethereum'  │ 'https://app.ipor.io' │
    │    1    │ '0x43ee0243ea8cf02f7087d8b16c8d2007cc9c7ca2' │ 'ethereum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Ethereum)' │ 1068942.87 │ 20.67415766343586  │  6.46873  │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'USDC on ethereum chain under management by vault named: IPOR USDC Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    2    │ '0xabab980f0ecb232d52f422c6b68d25c3d0c18e3e' │ 'ethereum' │ 'ipor-fusion' │ 'USDT (IPOR USDT Lending Optimizer Ethereum)' │ 971855.74  │ 9.554755667095558  │ 21.573585 │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ 'USDT on ethereum chain under management by vault named: IPOR USDT Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    3    │ '0xa91267a25939b2b0f046013fbf9597008f7f014b' │ 'arbitrum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Arbitrum)' │ 756320.31  │ 11.122625143604887 │     0     │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'USDC on arbitrum chain under management by vault named: IPOR USDC Lending Optimizer Arbitrum' │ 'https://app.ipor.io' │
    │    4    │ '0x45aa96f0b3188d47a1dafdbefce1db6b37f58216' │   'base'   │ 'ipor-fusion' │   'USDC (IPOR USDC Lending Optimizer Base)'   │  34052.24  │ 16.297099930871376 │     0     │ [ '0xbd4e5C2f8dE5065993d29A9794E2B7cEfc41437A' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │     'USDC on base chain under management by vault named: IPOR USDC Lending Optimizer Base'     │ 'https://app.ipor.io' │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴───────────────────────────────────────────────┴────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────┘

**Comment by llamatester** [comment]
The ipor-fusion adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.317 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬───────────────────────────────────────────────┬────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────────┬───────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │                    symbol                     │   tvlUsd   │      apyBase       │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │                       poolMeta                        │          url          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼───────────────────────────────────────────────┼────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────────┼───────────────────────┤
    │    0    │ '0x20e934c725b6703f0ac696f1689008057db9ac44' │ 'ethereum' │ 'ipor-fusion' │  'DAI (IPOR DAI Lending Optimizer Ethereum)'  │ 1131296.16 │ 5.354093054786544  │     0     │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │  'DAI in vault: IPOR DAI Lending Optimizer Ethereum'  │ 'https://app.ipor.io' │
    │    1    │ '0x43ee0243ea8cf02f7087d8b16c8d2007cc9c7ca2' │ 'ethereum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Ethereum)' │ 1068950.06 │ 19.878835058804665 │  6.46873  │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'USDC in vault: IPOR USDC Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    2    │ '0xabab980f0ecb232d52f422c6b68d25c3d0c18e3e' │ 'ethereum' │ 'ipor-fusion' │ 'USDT (IPOR USDT Lending Optimizer Ethereum)' │ 971858.78  │ 9.554720928876623  │ 21.573585 │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ 'USDT in vault: IPOR USDT Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    3    │ '0xa91267a25939b2b0f046013fbf9597008f7f014b' │ 'arbitrum' │ 'ipor-fusion' │ 'USDC (IPOR USDC Lending Optimizer Arbitrum)' │ 756323.05  │ 10.84205779699661  │     0     │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'USDC in vault: IPOR USDC Lending Optimizer Arbitrum' │ 'https://app.ipor.io' │
    │    4    │ '0x45aa96f0b3188d47a1dafdbefce1db6b37f58216' │   'base'   │ 'ipor-fusion' │   'USDC (IPOR USDC Lending Optimizer Base)'   │  34052.42  │ 17.154741249319343 │     0     │ [ '0xbd4e5C2f8dE5065993d29A9794E2B7cEfc41437A' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │   'USDC in vault: IPOR USDC Lending Optimizer Base'   │ 'https://app.ipor.io' │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴───────────────────────────────────────────────┴────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────────┴───────────────────────┘

**Comment by slasher125** [comment]
gm,
u really need to remove the meta data from the symbol field.
the ui automatically combines symbol and poolMeta, otherwise we see it doubled and it messes up with other server side processing

**Comment by llamatester** [comment]
The ipor-fusion adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.305 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬────────┬────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────┬───────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │ symbol │   tvlUsd   │      apyBase       │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │                poolMeta                │          url          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼────────┼────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────┼───────────────────────┤
    │    0    │ '0x20e934c725b6703f0ac696f1689008057db9ac44' │ 'ethereum' │ 'ipor-fusion' │ 'DAI'  │ 1131907.57 │ 5.354093054786544  │     0     │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │ 'IPOR DAI Lending Optimizer Ethereum'  │ 'https://app.ipor.io' │
    │    1    │ '0x43ee0243ea8cf02f7087d8b16c8d2007cc9c7ca2' │ 'ethereum' │ 'ipor-fusion' │ 'USDC' │ 1070256.83 │ 10.982515501738405 │ 6.866706  │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'IPOR USDC Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    2    │ '0xabab980f0ecb232d52f422c6b68d25c3d0c18e3e' │ 'ethereum' │ 'ipor-fusion' │ 'USDT' │ 972540.67  │ 11.560399901207417 │ 35.691495 │ [ '0x1e4746dc744503b53b4a082cb3607b169a289090' ] │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ 'IPOR USDT Lending Optimizer Ethereum' │ 'https://app.ipor.io' │
    │    3    │ '0xa91267a25939b2b0f046013fbf9597008f7f014b' │ 'arbitrum' │ 'ipor-fusion' │ 'USDC' │ 666352.35  │  16.2096208075996  │     0     │ [ '0x34229b3f16fbcdfa8d8d9d17c0852f9496f4c7bb' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'IPOR USDC Lending Optimizer Arbitrum' │ 'https://app.ipor.io' │
    │    4    │ '0x45aa96f0b3188d47a1dafdbefce1db6b37f58216' │   'base'   │ 'ipor-fusion' │ 'USDC' │  80533.29  │ 11.997475859351507 │     0     │ [ '0xbd4e5C2f8dE5065993d29A9794E2B7cEfc41437A' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │   'IPOR USDC Lending Optimizer Base'   │ 'https://app.ipor.io' │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴────────┴────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────┴───────────────────────┘

**Comment by rav-ipor** [comment]
gm,
Ahh ok, I didn't know that `Pool` column is a combination of `symbol` and `poolMeta`.
I changed it to show only the underlying token symbol in `symbol` and vault name in  `poolMeta`.

**Pull request merged**
