### PR TITLE
Arbidex classic pools adapter

### PR DESCRIPTION
**Pull request by harleen-m**
Adapter for Arbidex' classic v2 pools.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running arbitrum-exchange-v2 adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       18 failed, 214 passed, 232 total
    Snapshots:   0 total
    Time:        0.469 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────────────┬────────────────┬────────────────────┬───────────────────────┬───────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │        project         │     symbol     │       tvlUsd       │        apyBase        │       apyBase7d       │     apyReward      │                                        underlyingTokens                                        │                                                       url                                                       │    volumeUsd1d     │    volumeUsd7d     │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────────┼───────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xd082d6e0af69f74f283b90c3cda9c35615bce367' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USDT-USDC'   │   5205329.068007   │  0.05124419980695984  │  0.03481816403830001  │ 0.9131422316148864 │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 14616.050565585028 │ 69707.69283199962  │
    │    1    │ '0x10a12127867d3885ac64b51cc91a67c907ee51db' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WBTC-WETH'   │ 3977383.2520992914 │  0.0609338841308331   │  0.09269741204456336  │ 4.684537099012406  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://arbidex.fi/add/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/' │ 13279.858094648458 │ 141805.05160730518 │
    │    2    │ '0x4c42fa9ecc3a17229edf0fd6a8eec3f11d7e00d3' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WETH-USDC'   │ 2634116.1640295424 │  0.5886943253402136   │  0.8870078512823047   │ 7.073415992765907  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 84969.27331786975  │ 898646.8148783967  │
    │    3    │ '0xa6a6090749b9e3010802c5bff3845aa6a4ac321b' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WBTC-USDC'   │  1685525.0972785   │  0.49360823050725045  │  0.6453791857492592   │ 11.054240267044294 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 45588.44168455899  │ 418385.6980159767  │
    │    4    │ '0xece52b1fc32d2b4f22eb45238210b470a64bfdd5' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USD+-USDC'   │   813075.803089    │  0.06474696202278586  │  0.04441342046338967  │ 14.592049650996445 │ [ '0xe80772eaf6e2e18b651f160bc9158b2a5cafca65', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xe80772eaf6e2e18b651f160bc9158b2a5cafca65/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 2884.6130489999778 │ 13889.029811999993 │
    │    5    │ '0x62fddfc2d4b35adec79c6082ca2894eab01ac0db' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'WETH-ARX'   │ 789318.2802328069  │  1.3254155694031484   │  1.4659342661522463   │ 401.7745712609862  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xd5954c3084a1ccd70b4da011e67760b8e78aee84' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0xd5954c3084a1ccd70b4da011e67760b8e78aee84/' │ 57324.64316904545  │ 445034.12072832044 │
    │    6    │ '0xe8c060d40d7bc96fcd5b758bd1437c8653400b0e' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USD+-DAI+'   │ 783575.7735373955  │           0           │           0           │ 15.141410555787528 │ [ '0xe80772eaf6e2e18b651f160bc9158b2a5cafca65', '0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8' ] │ 'https://arbidex.fi/add/0xe80772eaf6e2e18b651f160bc9158b2a5cafca65/0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8/' │         0          │         0          │
    │    7    │ '0xee5e74dc56594d070e0827ec270f974a68ebaf22' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'DAI-DAI-'   │ 737415.0481604901  │ 0.014659210136089442  │ 0.0026815429511850273 │ 15.745126594259657 │ [ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', '0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8' ] │ 'https://arbidex.fi/add/0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8/' │ 592.3245012876241  │ 760.5423555740499  │
    │    8    │ '0xa6efae0c9293b4ee340de31022900ba747eaa92d' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'ARX-USDC'   │  695591.034789427  │  1.1892343473419436   │   1.603521051717818   │ 407.0594613652693  │ [ '0xd5954c3084a1ccd70b4da011e67760b8e78aee84', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xd5954c3084a1ccd70b4da011e67760b8e78aee84/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 45327.16439861432  │ 428998.0260273181  │
    │    9    │ '0x00cabe722790e27ca6154e8fc34281384aa7052c' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │ 'WETH-SFRXETH' │ 692411.2746549137  │ 0.0014614230941590977 │  0.02124352292380442  │ 8.750718059608072  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x95ab45875cffdba1e5f451b950bc2e42c0053f39' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0x95ab45875cffdba1e5f451b950bc2e42c0053f39/' │ 55.44689465407282  │ 5657.405686858576  │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────────────┴────────────────┴────────────────────┴───────────────────────┴───────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by slasher125** [comment]
henlo ty for adding. pls add the rewardTokens field, thats breaking the tests rn

**Comment by llamatester** [comment]
The arbitrum-exchange-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       277 passed, 277 total
    Snapshots:   0 total
    Time:        0.692 s
    Ran all test suites.
    
    Nb of pools: 39
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────────────┬────────────────┬────────────────────┬───────────────────────┬───────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │        project         │     symbol     │       tvlUsd       │        apyBase        │       apyBase7d       │     apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │                                                       url                                                       │    volumeUsd1d     │    volumeUsd7d     │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────────┼───────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xd082d6e0af69f74f283b90c3cda9c35615bce367' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USDT-USDC'   │ 5206590.348712983  │ 0.012561484641053207  │  0.02483229339567897  │ 0.8635861547316073 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 3583.698887540493  │ 49727.530434750486 │
    │    1    │ '0x10a12127867d3885ac64b51cc91a67c907ee51db' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WBTC-WETH'   │ 3920825.834565617  │ 0.049129040489040356  │  0.09501596506546724  │ 4.491147753432059  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://arbidex.fi/add/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/' │ 10554.871845306829 │ 143285.01943264157 │
    │    2    │ '0x4c42fa9ecc3a17229edf0fd6a8eec3f11d7e00d3' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WETH-USDC'   │ 2267828.5071986765 │  0.5290850080339338   │  0.9264768921279747   │ 7.764700056733647  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │  65746.5240520984  │ 808111.8104725592  │
    │    3    │ '0xa6a6090749b9e3010802c5bff3845aa6a4ac321b' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'WBTC-USDC'   │ 1670801.5840381742 │  0.32869079362998077  │   0.537549058736902   │ 10.539257507733735 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 30091.895816752687 │ 345437.62262917124 │
    │    4    │ '0xece52b1fc32d2b4f22eb45238210b470a64bfdd5' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USD+-USDC'   │ 862662.7953885687  │  0.20536780893680504  │  0.06853580157095926  │ 13.032709340365548 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xe80772eaf6e2e18b651f160bc9158b2a5cafca65', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xe80772eaf6e2e18b651f160bc9158b2a5cafca65/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 9707.570856999984  │ 22739.72544899999  │
    │    5    │ '0xe8c060d40d7bc96fcd5b758bd1437c8653400b0e' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │  'USD+-DAI+'   │ 783462.0479490061  │           0           │           0           │ 14.350195392972278 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xe80772eaf6e2e18b651f160bc9158b2a5cafca65', '0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8' ] │ 'https://arbidex.fi/add/0xe80772eaf6e2e18b651f160bc9158b2a5cafca65/0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8/' │         0          │         0          │
    │    6    │ '0x62fddfc2d4b35adec79c6082ca2894eab01ac0db' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'WETH-ARX'   │ 754269.6980965035  │   1.011508209823734   │  1.5942706586579745   │ 397.3770765636758  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xd5954c3084a1ccd70b4da011e67760b8e78aee84' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0xd5954c3084a1ccd70b4da011e67760b8e78aee84/' │ 41805.47901621275  │ 462503.8647654094  │
    │    7    │ '0xee5e74dc56594d070e0827ec270f974a68ebaf22' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'DAI-DAI-'   │ 737210.4319566801  │ 0.0012599144753538875 │ 0.0022685097366491654 │ 14.91017152979853  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', '0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8' ] │ 'https://arbidex.fi/add/0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8/' │ 50.894361348170605 │ 643.2188626357947  │
    │    8    │ '0xa6efae0c9293b4ee340de31022900ba747eaa92d' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │   'ARX-USDC'   │ 678339.3496657597  │    1.0008734244245    │   1.682281889896225   │ 394.5455974786711  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0xd5954c3084a1ccd70b4da011e67760b8e78aee84', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://arbidex.fi/add/0xd5954c3084a1ccd70b4da011e67760b8e78aee84/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8/' │ 37201.743990238756 │ 438906.9242871888  │
    │    9    │ '0x00cabe722790e27ca6154e8fc34281384aa7052c' │ 'Arbitrum' │ 'arbitrum-exchange-v2' │ 'WETH-SFRXETH' │ 665597.7259888365  │  0.1447781762518948   │  0.04265546043639391  │ 8.634143792323226  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xD5954c3084a1cCd70B4dA011E67760B8e78aeE84' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x95ab45875cffdba1e5f451b950bc2e42c0053f39' ] │ 'https://arbidex.fi/add/0x82af49447d8a07e3bd95bd0d56f35241523fbab1/0x95ab45875cffdba1e5f451b950bc2e42c0053f39/' │ 5280.220541702583  │ 10919.760564411758 │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────────────┴────────────────┴────────────────────┴───────────────────────┴───────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by harleen-m** [comment]
> henlo ty for adding. pls add the rewardTokens field, thats breaking the tests rn

Thank you, I totally missed locally that the tests were failing. Apologies.

**Comment by slasher125** [comment]
the apybase values are in % yes?

**Pull request merged**
