### PR TITLE
Add yields for Archly

### PR DESCRIPTION
**Pull request by tec05**

### CODE REVIEW

**Comment by llamatester** [comment]
The archly-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.484 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬──────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project      │    symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │                                   url                                    │
    ├─────────┼──────────────────────────────────────────────┼─────────┼──────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x63a813a1732935c2467cdd4726182ae04cdf45d2' │ 'Telos' │ 'archly-finance' │ 'STLOS-WTLOS' │ 19755.149957734797 │ 12.282518045918106 │ [ '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x63a813a1732935c2467cdd4726182ae04cdf45d2' │
    │    1    │ '0xee5284d137d7fe97bae8328dcec54c10d4eca081' │ 'Telos' │ 'archly-finance' │  'USDC-USDT'  │ 5884.753016092477  │ 9.285016856034673  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xee5284d137d7fe97bae8328dcec54c10d4eca081' │
    │    2    │ '0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │ 'Telos' │ 'archly-finance' │  'Arc-WTLOS'  │ 2183.4700457616623 │ 133.2251392955997  │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │
    │    3    │ '0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │ 'Telos' │ 'archly-finance' │  'USDC-Arc'   │ 1351.2764219834191 │ 112.63666739063146 │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │
    │    4    │ '0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │ 'Telos' │ 'archly-finance' │  'Arc-STLOS'  │ 1040.6468750578174 │ 209.04987764408577 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │
    │    5    │ '0x309c5c0285d8051f7d4921b108526c173ef43507' │ 'Telos' │ 'archly-finance' │  'Arc-USDT'   │ 931.8340292095187  │ 165.48302674280572 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x309c5c0285d8051f7d4921b108526c173ef43507' │
    │    6    │ '0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │ 'Telos' │ 'archly-finance' │  'MATIC-Arc'  │ 536.8737984067131  │ 240.79029893217373 │ [ '0x332730a4f6e03d9c55829435f10360e13cfa41ff', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │
    │    7    │ '0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │ 'Telos' │ 'archly-finance' │  'Y365-USDC'  │ 317.71904661791154 │ 373.14562572110856 │ [ '0x72397e7a188efa8e9bbba5cbeb4a4bc92752a59a', '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │
    └─────────┴──────────────────────────────────────────────┴─────────┴──────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi ser. ty for adding. 1 q: from the code i can see u also having swap fee apr. 
they way we use `apyBase` and `apyReward`: `apyBase` = from trading fees. `apyReward` = from incentives.

also, what are the requirements for receiving the bribe apr?

**Comment by tec05** [comment]
Thanks for responding. The APY reward is Arc emissions received for providing liquidity to Archly. In order to receive bribes, the user has to lock Arc tokens up for veArc and vote for a pool to receive the fees from trading.

**Comment by tec05** [comment]
Also, this code was taken from the 3xcalibur project in this repo that is also a Solidly fork that is reporting yields.

**Comment by llamatester** [comment]
The archly-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.339 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬──────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project      │    symbol     │       tvlUsd       │      apyBase       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │                                   url                                    │
    ├─────────┼──────────────────────────────────────────────┼─────────┼──────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x63a813a1732935c2467cdd4726182ae04cdf45d2' │ 'Telos' │ 'archly-finance' │ 'STLOS-WTLOS' │ 19755.149957734797 │ 1.3638087889067285 │ 12.26706851465551  │ [ '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x63a813a1732935c2467cdd4726182ae04cdf45d2' │
    │    1    │ '0xee5284d137d7fe97bae8328dcec54c10d4eca081' │ 'Telos' │ 'archly-finance' │  'USDC-USDT'  │ 5882.552594408957  │ 4.174649753946526  │  9.27680649867618  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xee5284d137d7fe97bae8328dcec54c10d4eca081' │
    │    2    │ '0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │ 'Telos' │ 'archly-finance' │  'Arc-WTLOS'  │ 2209.1538458154337 │ 7.115484584512962  │ 131.51062451548628 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │
    │    3    │ '0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │ 'Telos' │ 'archly-finance' │  'USDC-Arc'   │ 1356.6932557371397 │ 2.969193578493751  │ 112.0458318696576  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │
    │    4    │ '0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │ 'Telos' │ 'archly-finance' │  'Arc-STLOS'  │ 1040.6468750578174 │ 0.2963884295363058 │ 208.78692483522113 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │
    │    5    │ '0x309c5c0285d8051f7d4921b108526c173ef43507' │ 'Telos' │ 'archly-finance' │  'Arc-USDT'   │ 931.8340292095187  │ 3.437655730740338  │ 165.27487437652917 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x309c5c0285d8051f7d4921b108526c173ef43507' │
    │    6    │ '0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │ 'Telos' │ 'archly-finance' │  'MATIC-Arc'  │ 536.8737984067131  │ 1.3017144431431986 │ 240.4874215224133  │ [ '0x332730a4f6e03d9c55829435f10360e13cfa41ff', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │
    │    7    │ '0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │ 'Telos' │ 'archly-finance' │  'Y365-USDC'  │ 319.63353594346665 │ 0.7140438141977606 │ 370.44406943095333 │ [ '0x72397e7a188efa8e9bbba5cbeb4a4bc92752a59a', '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │
    └─────────┴──────────────────────────────────────────────┴─────────┴──────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ok. on our page we do not show yields (neither base nor reward) if it requires additional locks. given that `apyReward` is only available for `veArc` holders, I suggest to remove that column altogether.

**Comment by llamatester** [comment]
The archly-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.33 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬──────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project      │    symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │                                   url                                    │
    ├─────────┼──────────────────────────────────────────────┼─────────┼──────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x63a813a1732935c2467cdd4726182ae04cdf45d2' │ 'Telos' │ 'archly-finance' │ 'STLOS-WTLOS' │ 19755.149957734797 │ 12.26706851465551  │ [ '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x63a813a1732935c2467cdd4726182ae04cdf45d2' │
    │    1    │ '0xee5284d137d7fe97bae8328dcec54c10d4eca081' │ 'Telos' │ 'archly-finance' │  'USDC-USDT'  │ 5882.552594408957  │  9.27680649867618  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xee5284d137d7fe97bae8328dcec54c10d4eca081' │
    │    2    │ '0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │ 'Telos' │ 'archly-finance' │  'Arc-WTLOS'  │ 2196.1413080238567 │ 132.28984895120416 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │
    │    3    │ '0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │ 'Telos' │ 'archly-finance' │  'USDC-Arc'   │ 1356.6932557371397 │ 112.0458318696576  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │
    │    4    │ '0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │ 'Telos' │ 'archly-finance' │  'Arc-STLOS'  │ 1045.3056622123465 │ 207.85638951084786 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │
    │    5    │ '0x309c5c0285d8051f7d4921b108526c173ef43507' │ 'Telos' │ 'archly-finance' │  'Arc-USDT'   │ 931.8340292095187  │ 165.27487437652917 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x309c5c0285d8051f7d4921b108526c173ef43507' │
    │    6    │ '0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │ 'Telos' │ 'archly-finance' │  'MATIC-Arc'  │ 536.8737984067131  │ 240.4874215224133  │ [ '0x332730a4f6e03d9c55829435f10360e13cfa41ff', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │
    │    7    │ '0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │ 'Telos' │ 'archly-finance' │  'Y365-USDC'  │ 319.63353594346665 │ 370.44406943095333 │ [ '0x72397e7a188efa8e9bbba5cbeb4a4bc92752a59a', '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │
    └─────────┴──────────────────────────────────────────────┴─────────┴──────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by tec05** [comment]
Okay. Removed apyBase as it requires locking Arc to obtain trading fees. The apyReward is available to anyone who provides liquidity (no locking necessary).

**Comment by llamatester** [comment]
The archly-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.487 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬──────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │     project      │    symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │                                   url                                    │
    ├─────────┼──────────────────────────────────────────────┼─────────┼──────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x63a813a1732935c2467cdd4726182ae04cdf45d2' │ 'Telos' │ 'archly-finance' │ 'STLOS-WTLOS' │ 19755.149957734797 │ 12.26706851465551  │ [ '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x63a813a1732935c2467cdd4726182ae04cdf45d2' │
    │    1    │ '0xee5284d137d7fe97bae8328dcec54c10d4eca081' │ 'Telos' │ 'archly-finance' │  'USDC-USDT'  │ 5882.552594408957  │  9.27680649867618  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xee5284d137d7fe97bae8328dcec54c10d4eca081' │
    │    2    │ '0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │ 'Telos' │ 'archly-finance' │  'ARC-WTLOS'  │ 2196.1413080238567 │ 132.28984895120416 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xd102ce6a4db07d247fcc28f366a623df0938ca9e' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x34480a4c917cadbe41cb805f3e3badb93bd9068c' │
    │    3    │ '0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │ 'Telos' │ 'archly-finance' │  'USDC-ARC'   │ 1356.6932557371397 │ 112.0458318696576  │ [ '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xeab0f20cb5536f07135f9d32c93fc77911317ab6' │
    │    4    │ '0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │ 'Telos' │ 'archly-finance' │  'ARC-STLOS'  │ 1045.3056622123465 │ 207.85638951084786 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xb4b01216a5bc8f1c8a33cd990a1239030e60c905' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0xe2c0aa8a0e6ec89bea2bc8d1b63cef72ce50decb' │
    │    5    │ '0x309c5c0285d8051f7d4921b108526c173ef43507' │ 'Telos' │ 'archly-finance' │  'ARC-USDT'   │ 931.8340292095187  │ 165.27487437652917 │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5', '0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x309c5c0285d8051f7d4921b108526c173ef43507' │
    │    6    │ '0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │ 'Telos' │ 'archly-finance' │  'MATIC-ARC'  │ 536.8737984067131  │ 240.4874215224133  │ [ '0x332730a4f6e03d9c55829435f10360e13cfa41ff', '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x55f4585fbbdd5515ce65c38d3a4a2720b70f31b6' │
    │    7    │ '0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │ 'Telos' │ 'archly-finance' │  'Y365-USDC'  │ 319.63353594346665 │ 370.44406943095333 │ [ '0x72397e7a188efa8e9bbba5cbeb4a4bc92752a59a', '0x818ec0a7fe18ff94269904fced6ae3dae6d6dc0b' ] │ [ '0xa84df7afbcbcc1106834a5fed9453bd1219b1fb5' ] │ 'https://archly.fi/liquidity/0x6a20b223bad590cb8ea427fdb09f9dc78d73627f' │
    └─────────┴──────────────────────────────────────────────┴─────────┴──────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
