### PR TITLE
Update Clearpool API endpoint

### PR DESCRIPTION
**Pull request by zolotokrylin**
Clearpool is deprecating the old API endpoint soon.
Please review and merge updates with a new API endpoint.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running clearpool adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       20 failed, 124 passed, 144 total
    Snapshots:   0 total
    Time:        0.416 s
    Ran all test suites.
    
    Nb of pools: 20
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────┬────────┬────────────────────┬───────────────────┬──────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │   project   │ symbol │       tvlUsd       │      apyBase      │      apyReward       │                   rewardTokens                   │                 underlyingTokens                 │                 poolMeta                  │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────┼────────┼────────────────────┼───────────────────┼──────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────┤
    │    0    │ '0x4a90c14335e81829d7cb0002605f555b8a784106-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │ 3268250.413946001  │ '8.9975239019568' │ '1.0635815274525227' │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      'USDC (Portofino Technologies)'      │
    │    1    │ '0xa75dd592826fa9c679ec03beefb1777ba1a373a0-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │ 2138819.1990479995 │ '8.0080054240032' │ '0.650585692216188'  │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'USDC (Fasanara Investments Master Fund)' │
    │    2    │ '0x1a1d778776542c2efed161ba1fbcfe6e09ba99fb-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDT' │ 1929532.3460010001 │ '7.8974793599472' │ '0.9492654222355521' │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'USDT (Fasanara Investments Master Fund)' │
    │    3    │ '0x3aeb3a8f0851249682a6a836525cdeee5aa2a153-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │ 361058.81746200006 │ '9.5031998429472' │ '0.5830029734881667' │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │              'USDC (Auros)'               │
    │    4    │ '0xcb288b6d30738db7e3998159d192615769794b5b-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │   231808.802166    │       '0.0'       │        '0.0'         │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │            'USDC (Wintermute)'            │
    │    5    │ '0x68f311351e7196d71f8e6372e4a1d2e725669bf2-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │ 119230.64771399996 │ '9.4725955393776' │ '0.9093027456223562' │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │            'USDC (Alphanonce)'            │
    │    6    │ '0xb254554636a3ff52e8b2d0f06203921c137e10d5-polygon'  │ 'Polygon'  │ 'clearpool' │ 'USDC' │    28591.292073    │       '0.0'       │        '0.0'         │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │              'USDC (Auros)'               │
    │    7    │ '0x7b7e4ab1ecf7a69c1f15b186f9af11bb53e764cb-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │    3740.502727     │       '0.0'       │        '0.0'         │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │           'USDC (Amber Group)'            │
    │    8    │ '0x3f6e10b1ee2882c8278b3e471230e143414ccaa9-polygon'  │ 'Polygon'  │ 'clearpool' │ 'USDC' │ 2462.5721129999997 │ '0.000058436208'  │        '0.0'         │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │         'USDC (Parallel Capital)'         │
    │    9    │ '0xe3d20a721522874d32548b4097d1afc6f024e45b-ethereum' │ 'Ethereum' │ 'clearpool' │ 'USDC' │    1316.439743     │ '0.0000000126144' │        '0.0'         │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │             'USDC (Folkvang)'             │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────┴────────┴────────────────────┴───────────────────┴──────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by slasher125** [comment]
gm, test is failing. there is a pool with nan apy. either we fix that, or you can drop it by using:
`.filter(p => utils.keepFinite(p)`

**Comment by slasher125** [comment]
still failing sir

**Comment by power-f-GOD** [comment]
@slasher125 , can you help here: https://github.com/DefiLlama/yield-server/actions/runs/5714898090/job/15483119892?pr=899#step:4:70 ?

**Comment by power-f-GOD** [comment]
> @slasher125 , can you help here: https://github.com/DefiLlama/yield-server/actions/runs/5714898090/job/15483119892?pr=899#step:4:70 ?

Ok. Don't worry. I found the issue.🤲🏼

Fixing...

**Comment by slasher125** [comment]
best to run the tests offline. once ready feel free to ping me

**Comment by llamatester** [comment]
The clearpool adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       165 passed, 165 total
    Snapshots:   0 total
    Time:        0.454 s
    Ran all test suites.
    
    Nb of pools: 23
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────┬─────────────────┬─────────────┬────────┬────────────────────┬────────────────────┬──────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────┐
    │ (index) │                            pool                            │      chain      │   project   │ symbol │       tvlUsd       │        apy         │     apyBase      │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │                 poolMeta                  │
    ├─────────┼────────────────────────────────────────────────────────────┼─────────────────┼─────────────┼────────┼────────────────────┼────────────────────┼──────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────┤
    │    0    │   '0x4a90c14335e81829d7cb0002605f555b8a784106-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │ 2081259.5608870005 │ 10.06624434685509  │ 8.6822023285728  │ 1.3840420182822906 │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │      'USDC (Portofino Technologies)'      │
    │    1    │   '0x1a1d778776542c2efed161ba1fbcfe6e09ba99fb-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDT' │ 886660.8134880001  │ 8.978867835786744  │ 7.5901081036176  │ 1.388759732169145  │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ 'USDT (Fasanara Investments Master Fund)' │
    │    2    │   '0x3aeb3a8f0851249682a6a836525cdeee5aa2a153-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │ 357164.27951200004 │ 10.038399180782916 │ 9.3989637444672  │ 0.6394354363157161 │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │              'USDC (Auros)'               │
    │    3    │   '0xa75dd592826fa9c679ec03beefb1777ba1a373a0-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │ 315773.2739289999  │ 14.895856490608484 │ 13.6509516657072 │ 1.2449048249012828 │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ 'USDC (Fasanara Investments Master Fund)' │
    │    4    │   '0xcb288b6d30738db7e3998159d192615769794b5b-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │   231808.802166    │         0          │        0         │         0          │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │            'USDC (Wintermute)'            │
    │    5    │   '0x68f311351e7196d71f8e6372e4a1d2e725669bf2-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │ 105835.93171300006 │ 10.475587382229842 │ 9.2747715516576  │ 1.2008158305722412 │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │            'USDC (Alphanonce)'            │
    │    6    │    '0xb254554636a3ff52e8b2d0f06203921c137e10d5-polygon'    │    'Polygon'    │ 'clearpool' │ 'USDC' │    28579.661328    │         0          │        0         │         0          │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │              'USDC (Auros)'               │
    │    7    │ '0x6beb2006a2c8b2dc90d924b8b19be084bc5a5eba-polygon zkevm' │ 'Polygon zkEVM' │ 'clearpool' │ 'USDT' │    16646.783327    │  8.5628052476352   │ 8.5628052476352  │         0          │ [ '0xc3630b805F10E91c2de084Ac26C66bCD91F3D3fE' ] │ [ '0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035', '0x1E4a5963aBFD975d8c9021ce480b42188849D41d' ] │      'USDT (Portofino Technologies)'      │
    │    8    │ '0xfa42f010aac1acbb10018c7bf1588446e7e11bfb-polygon zkevm' │ 'Polygon zkEVM' │ 'clearpool' │ 'USDC' │ 6710.350687000006  │  7.6166420462064   │ 7.6166420462064  │         0          │ [ '0xc3630b805F10E91c2de084Ac26C66bCD91F3D3fE' ] │ [ '0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035', '0x1E4a5963aBFD975d8c9021ce480b42188849D41d' ] │ 'USDC (Fasanara Investments Master Fund)' │
    │    9    │   '0x7b7e4ab1ecf7a69c1f15b186f9af11bb53e764cb-ethereum'    │   'Ethereum'    │ 'clearpool' │ 'USDC' │    3740.502727     │         0          │        0         │         0          │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │           'USDC (Amber Group)'            │
    └─────────┴────────────────────────────────────────────────────────────┴─────────────────┴─────────────┴────────┴────────────────────┴────────────────────┴──────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
