### PR TITLE
YEL FINANCE - Move calculations to YEL FINANCE API calls + Base chain support   

### PR DESCRIPTION
**Pull request by able1f**

### CODE REVIEW

**Comment by llamatester** [comment]
The yeltoken adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.279 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬─────────┬────────────┬────────────────────────────────────────────────────┬─────────┬────────────────────┬────────────────────┐
    │ (index) │  chain  │  project   │                        pool                        │ symbol  │      apyBase       │       tvlUsd       │
    ├─────────┼─────────┼────────────┼────────────────────────────────────────────────────┼─────────┼────────────────────┼────────────────────┤
    │    0    │ 'Blast' │ 'yeltoken' │ '81457-0x7d2f5881F0C4B840fcFA2c49F4052d1A004eAf0d' │  'YEL'  │  16.4844887007222  │ 120590.64974053451 │
    │    1    │ 'Blast' │ 'yeltoken' │ '81457-0x795a85CD543D0E2d29F7e11e33a20a38A4b5121e' │ 'WETH'  │ 15.579245869130077 │ 13578.697888716986 │
    │    2    │ 'Base'  │ 'yeltoken' │ '8453-0x516712404013200B499Cd8fAE4575E5d48F6Ba65'  │  'YEL'  │  638.773408142945  │ 11161.84335731634  │
    │    3    │ 'Base'  │ 'yeltoken' │ '8453-0xE7349C94BDE0D13599Ed496342857bb231FeF02B'  │ 'USDC'  │ 51.59759846609617  │ 10205.615466999998 │
    │    4    │ 'Base'  │ 'yeltoken' │ '8453-0x0540f15374eCF13aAB3c0a76b643333CE0D00579'  │ 'WETH'  │ 63.00468110003115  │ 8976.741666494725  │
    │    5    │ 'Blast' │ 'yeltoken' │ '81457-0x07BF0Bc908Ef4badF8ec0fB1f77A8dBFe33c33c0' │ 'BLAST' │ 19.668987937588756 │ 969.7429172761867  │
    └─────────┴─────────┴────────────┴────────────────────────────────────────────────────┴─────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
why change to using an api? i don't like that part, using the sdk is much more robust.

**Comment by 0x61626c653166** [comment]
We have calculated all required metrics on our side for displaying it on our front-end side and using API lets avoid any mismatch in values between DeFiLama dashboards and our dashboard. It ensures in data consistency between platforms.

**Comment by slasher125** [comment]
what you guys use on your UI is up to you. on our side we prefer sdk for the above mentioned reason + transparency. so please revert that change. also, make sure to resolve the conflicts, we have renamed the project to `yel-finance`

**Comment by able1f** [comment]
Sorry, I am not clear about rules of your platform for deploying yield adaptor. 

I have analyzed the ways of implementation of another projects that you approved and moved to production - there is allowed using of platform API and I have gone by this way also. 

Can you explain why you reject our approach in comparison with another projects ?

I have no concerns to move code in another implementation way, but I want to be clear in platform requirements

**Comment by slasher125** [comment]
see readme: https://github.com/DefiLlama/yield-server?tab=readme-ov-file#data-sources

+ given this project already uses on chain calls in makes just no sense moving it to centralised api instead. hence why i'm asking u to revert to using our sdk and just adding the base calls to it

**Comment by able1f** [comment]
Okay, got it 

I will update the code 

Thanks

**Comment by llamatester** [comment]
The yel-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.29 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬─────────┬───────────────┬────────────────────────────────────────────────────┬─────────┬────────────────────┬────────────────────┐
    │ (index) │  chain  │    project    │                        pool                        │ symbol  │      apyBase       │       tvlUsd       │
    ├─────────┼─────────┼───────────────┼────────────────────────────────────────────────────┼─────────┼────────────────────┼────────────────────┤
    │    0    │ 'Blast' │ 'yel-finance' │ '81457-0x7d2f5881F0C4B840fcFA2c49F4052d1A004eAf0d' │  'YEL'  │ 16.30350968784405  │ 132468.08473768752 │
    │    1    │ 'Blast' │ 'yel-finance' │ '81457-0x795a85CD543D0E2d29F7e11e33a20a38A4b5121e' │ 'WETH'  │ 15.41318441396847  │ 13683.90831814067  │
    │    2    │ 'Base'  │ 'yel-finance' │ '8453-0x516712404013200B499Cd8fAE4575E5d48F6Ba65'  │  'YEL'  │ 618.7322353245429  │ 11377.796450528775 │
    │    3    │ 'Base'  │ 'yel-finance' │ '8453-0xE7349C94BDE0D13599Ed496342857bb231FeF02B'  │ 'USDC'  │ 49.978890935755274 │  10216.082813937   │
    │    4    │ 'Base'  │ 'yel-finance' │ '8453-0x0540f15374eCF13aAB3c0a76b643333CE0D00579'  │ 'WETH'  │ 61.023902484651074 │ 9145.418020115378  │
    │    5    │ 'Blast' │ 'yel-finance' │ '81457-0x07BF0Bc908Ef4badF8ec0fB1f77A8dBFe33c33c0' │ 'BLAST' │ 19.42934160096259  │ 982.2539257286434  │
    └─────────┴─────────┴───────────────┴────────────────────────────────────────────────────┴─────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by able1f** [comment]
I have updated the code according to your comments

**Pull request merged**
