### PR TITLE
Fix InsureDAO displaying APY

### PR DESCRIPTION
**Pull request by hirorylabo**
I have changed the calculation method to the same APY calculation shown on the site. 
and changed the Code formatting.

### CODE REVIEW

**Comment by llamatester** [comment]
The insuredao adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       18 passed, 18 total
    Snapshots:   0 total
    Time:        0.311 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬──────────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │    symbol    │      tvlUsd       │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼──────────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xf57882cf186db61691873d33e3511a40c3c7e4da' │ 'Ethereum' │ 'insuredao' │ 'INSURE-ETH' │ 91595.29367297959 │ 435.17009499318533 │ [ '0xd83AE04c9eD29d6D3E6Bf720C71bc7BeB424393E' ] │ [ '0x1b459aec393d604ae6468ae3f7d7422efa2af1ca' ] │
    │    1    │ '0xA12ab76a82D118e33682AcB242180B4cc0d19E29' │ 'Ethereum' │ 'insuredao' │  'vlINSURE'  │ 55669.92549436966 │ 490.80881437073475 │ [ '0xd83AE04c9eD29d6D3E6Bf720C71bc7BeB424393E' ] │ [ '0xd83AE04c9eD29d6D3E6Bf720C71bc7BeB424393E' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴──────────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
gm sir. can u give me a brief explanation of what the apr range on the insuraedao UI is standing for? i couldn't figure it out.

**Comment by hirorylabo** [comment]
gm!
It's a system similar to curve's ve tokenomics.
Token Staker can boost their reward up to 2.5x by staking INSURE token to the gauge system.
The change is to reflect this method.(previous APY calculation was based on normalized calculation, which didn't incude boost assumption.

**Comment by slasher125** [comment]
in insuredao's case, boosted funds are locked for a given duration? if so, for how long?

**Comment by slasher125** [comment]
we basically display rewards for the least amount of "locking time", ideally none

**Comment by slasher125** [comment]
ty sir. to sum up:
for now, we only collect un-boosted apy's for the yields page (see the curve pools for example) with the simple reasoning that not everyone is going to boost rewards by vote locking gov tokens. 
ideally, in the future, we'd display a range of apy values, from no boost up to max boost...

> we don't show reward for locks.
To add more information, we are changing the apy metrics because most of token miners are boosting their mining, thereby this metrics is more natural.

some users won't though and showing just the max value on our page would be misleading. so I'm actually for showing the unboosted apy values in insuradao's case.

**Comment by hirorylabo** [comment]
OK. Thank you. 
Then, we will stick to the current APY method, which is based on normaized calcuation (just divide the tortal reward/liquidity in a pool), as this is the simplest and non-biased version of APY calculation. Please let me know if the range APY showing becomes available.

**Pull request closed without merging**
