### PR TITLE
Ottopia adaptor

### PR DESCRIPTION
**Pull request by abtheo**
Hey, thanks for taking the time to review ♥

### CODE REVIEW

**Comment by glebskr** [comment]
Hello, thanks for your PR
There is an infinite loop (maybe) when running tests
Screenshot 2022-08-01 at 12 15 31

**Comment by abtheo** [comment]
> Hello, thanks for your PR There is an infinite loop (maybe) when running tests Screenshot 2022-08-01 at 12 15 31

Thanks for the suggestions! I have fixed this issue and ensured the test suite is passing.
image

**Comment by llamatester** [comment]
The ottopia adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       15 passed, 15 total
    Snapshots:   0 total
    Time:        0.301 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────────────┬───────────────────┬───────────┬─────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │      tvlUsd       │        apy        │  project  │ symbol  │   chain   │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼───────────────────┼───────────────────┼───────────┼─────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xF2A8705D327534E334d09BC28e5C97b5c356Aa01' │ 387989.921450361  │ 98.00554240891803 │ 'ottopia' │ 'CLAM+' │ 'Polygon' │ [ '0xF2A8705D327534E334d09BC28e5C97b5c356Aa01' ] │ [ '0xF2A8705D327534E334d09BC28e5C97b5c356Aa01' ] │
    │    1    │ '0x845EB7730a8D37e8D190Fb8bb9c582038331B48a' │ 195030.0713752205 │ 98.00554240891803 │ 'ottopia' │ 'PEARL' │ 'Polygon' │ [ '0x236eec6359fb44cce8f97e99387aa7f8cd5cde1f' ] │ [ '0x845EB7730a8D37e8D190Fb8bb9c582038331B48a' ] │
    └─────────┴──────────────────────────────────────────────┴───────────────────┴───────────────────┴───────────┴─────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by glebskr** [comment]
Apy for both pools should be the same?

**Comment by abtheo** [comment]
> Apy for both pools should be the same?

Yes, the value of reward payouts is split proportionally between each pool. The primary difference is the reward token. 🙂

**Pull request merged**
