### PR TITLE
add muuu finance

### PR DESCRIPTION
**Pull request by minions514**

### CODE REVIEW

**Comment by llamatester** [comment]
The muuu-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       74 passed, 74 total
    Snapshots:   0 total
    Time:        0.35 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────────────┬──────────────────────┬────────────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │    project     │        symbol        │       tvlUsd       │       apyBase       │     apyReward      │                                                               underlyingTokens                                                               │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────────────┼──────────────────────┼────────────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xd44e0Ed145904c1905129a767F2D6de2e68A23FC' │ 'astar' │ 'muuu-finance' │ 'lDAI-lUSDC-lceUSDT' │ 33930.39128219422  │ 1.0784451981488141  │ 12.691367068892422 │ [ '0x4dd9c468A44F3FEF662c35c1E9a6108B70415C2c', '0xC404E12D3466acCB625c67dbAb2E1a8a457DEf3c', '0x430D50963d9635bBef5a2fF27BD0bDDc26ed691F' ] │ [ '0x48611e9B924474F2a13b1C18E38B082099CBEF58' ] │
    │    1    │ '0x8ce5a2189c6fC5C0709aAF2Bde528d2ac7FECDdE' │ 'astar' │ 'muuu-finance' │     'aUSD-3KGL'      │  19702.9946419734  │  1.53447218610272   │ 13.050878302178281 │                        [ '0xfFFFFfFF00000000000000010000000000000001', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xe2AcA2Be2b06313b22964786E7CA34d8c878e062' ] │
    │    2    │ '0x4af9ABbdffe5C76cAf9F8999f68F6f7564e3d0Ea' │ 'astar' │ 'muuu-finance' │     'BUSD-3KGL'      │ 10510.153071972692 │ 0.17415630683275118 │ 4.3545679074723065 │                        [ '0x4Bf769b05E832FCdc9053fFFBC78Ca889aCb5E1E', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x8B23ca8D0cE64e570781428a5BAb241911077934' ] │
    │    3    │ '0x4Ab1099D84C52cE4a36Ee1FC4DF756c60fa0B348' │ 'astar' │ 'muuu-finance' │     'USDT-3KGL'      │ 9094.190484637116  │  4.274062466014117  │ 48.51513374009686  │                        [ '0xfFFfffFF000000000000000000000001000007C0', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x2d173425E66112B8D6D5FB67a6355363B1bc4039' ] │
    │    4    │ '0xBa5534fd7b9A11bb6127eB6920fD9DBf0e67b5bf' │ 'astar' │ 'muuu-finance' │     'LAY-muLAY'      │ 6557.343172346571  │  7.651731509710236  │ 89.47704906881269  │                        [ '0xc4335B1b76fA6d52877b3046ECA68F6E708a27dd', '0xDDF2ad1d9bFA208228166311FC22e76Ea7a4C44D' ]                        │ [ '0xd997D637C1a3C3273c91A4C5b6C417395aF0948a' ] │
    │    5    │ '0x0125F9A29a985344E0f4159A6D55A2800cf46Ded' │ 'astar' │ 'muuu-finance' │  'DAI-USDC-ceUSDT'   │ 4041.318918705347  │ 0.3693185196157467  │ 3.3916920468926692 │ [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ] │ [ '0xA4A8163D0C9C41a918E4218b70e7B0BE4ac81983' ] │
    │    6    │ '0x4C565C34c4ecB07Ad168ded84C8DED8aEC1246A5' │ 'astar' │ 'muuu-finance' │     'KGL-muKGL'      │ 2497.369756482773  │ 0.7352240952366307  │ 6.856526243988914  │                        [ '0x257f1a047948f73158DaDd03eB84b34498bCDc60', '0x5eaAe8435B178d4677904430BAc5079e73aFa56e' ]                        │ [ '0x51d6a5eE71FB3e398704E2cD9F38241eBB687794' ] │
    │    7    │ '0xb8ff8F2e849978CFaB2f39E1dcE72C2e5a6afbB6' │ 'astar' │ 'muuu-finance' │      'BAI-3KGL'      │ 2069.3034861910896 │  0.889508445588838  │ 8.327541267093519  │                        [ '0x733ebcC6DF85f8266349DEFD0980f8Ced9B45f35', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xfe1Facac14b67685851FB5186B08d17108BC960b' ] │
    │    8    │ '0xc6650c2730dE47cB76e90Bbdcc29976172Bf4128' │ 'astar' │ 'muuu-finance' │     'oUSD-3KGL'      │  1251.9116261783   │  16.66305039138496  │  203.248490438417  │                        [ '0x29F6e49c6E3397C3A84F715885F9F233A441165C', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x3EFED791e5a946D3d581D96Ee7FeaF796794412c' ] │
    │    9    │ '0x5fD86978Ee4df3E006448433Ec4Aa51D461bEdc8' │ 'astar' │ 'muuu-finance' │     'ASTR-nASTR'     │ 26.78971817581757  │ 0.36077776978813425 │ 3.1942671301762315 │                        [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xE511ED88575C57767BAfb72BfD10775413E3F2b0' ]                        │ [ '0x8B70B9A1e178006132044f121972f6A0d38EF5c6' ] │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────────────┴──────────────────────┴────────────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by wolfwarrier14** [comment]
Should I remove apyReward Field?

**Comment by slasher125** [comment]
keep it but change apyReward to their unboosted lower bounds

**Comment by wolfwarrier14** [comment]
You mean I need to make same to apyBase?

**Comment by llamatester** [comment]
The muuu-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       74 passed, 74 total
    Snapshots:   0 total
    Time:        0.341 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────────────┬──────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │    project     │        symbol        │       tvlUsd       │       apyBase       │      apyReward      │                                                               underlyingTokens                                                               │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────────────┼──────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xd44e0Ed145904c1905129a767F2D6de2e68A23FC' │ 'astar' │ 'muuu-finance' │ 'lDAI-lUSDC-lceUSDT' │  33930.4744356876  │ 1.0784425421876742  │ 1.0784425421876742  │ [ '0x4dd9c468A44F3FEF662c35c1E9a6108B70415C2c', '0xC404E12D3466acCB625c67dbAb2E1a8a457DEf3c', '0x430D50963d9635bBef5a2fF27BD0bDDc26ed691F' ] │ [ '0x48611e9B924474F2a13b1C18E38B082099CBEF58' ] │
    │    1    │ '0x8ce5a2189c6fC5C0709aAF2Bde528d2ac7FECDdE' │ 'astar' │ 'muuu-finance' │     'aUSD-3KGL'      │ 19702.99466367482  │  1.534472184400748  │  1.534472184400748  │                        [ '0xfFFFFfFF00000000000000010000000000000001', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xe2AcA2Be2b06313b22964786E7CA34d8c878e062' ] │
    │    2    │ '0x4af9ABbdffe5C76cAf9F8999f68F6f7564e3d0Ea' │ 'astar' │ 'muuu-finance' │     'BUSD-3KGL'      │ 10510.153361401732 │ 0.17415630203292398 │ 0.17415630203292398 │                        [ '0x4Bf769b05E832FCdc9053fFFBC78Ca889aCb5E1E', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x8B23ca8D0cE64e570781428a5BAb241911077934' ] │
    │    3    │ '0x4Ab1099D84C52cE4a36Ee1FC4DF756c60fa0B348' │ 'astar' │ 'muuu-finance' │     'USDT-3KGL'      │ 9094.191243374988  │  4.274062102544529  │  4.274062102544529  │                        [ '0xfFFfffFF000000000000000000000001000007C0', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x2d173425E66112B8D6D5FB67a6355363B1bc4039' ] │
    │    4    │ '0xBa5534fd7b9A11bb6127eB6920fD9DBf0e67b5bf' │ 'astar' │ 'muuu-finance' │     'LAY-muLAY'      │ 6567.855709290251  │  7.651731509710236  │  7.651731509710236  │                        [ '0xc4335B1b76fA6d52877b3046ECA68F6E708a27dd', '0xDDF2ad1d9bFA208228166311FC22e76Ea7a4C44D' ]                        │ [ '0xd997D637C1a3C3273c91A4C5b6C417395aF0948a' ] │
    │    5    │ '0x0125F9A29a985344E0f4159A6D55A2800cf46Ded' │ 'astar' │ 'muuu-finance' │  'DAI-USDC-ceUSDT'   │ 4041.319066022791  │ 0.3693185061303339  │ 0.3693185061303339  │ [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ] │ [ '0xA4A8163D0C9C41a918E4218b70e7B0BE4ac81983' ] │
    │    6    │ '0x4C565C34c4ecB07Ad168ded84C8DED8aEC1246A5' │ 'astar' │ 'muuu-finance' │     'KGL-muKGL'      │ 2503.373049166626  │ 0.7352240952366307  │ 0.7352240952366307  │                        [ '0x257f1a047948f73158DaDd03eB84b34498bCDc60', '0x5eaAe8435B178d4677904430BAc5079e73aFa56e' ]                        │ [ '0x51d6a5eE71FB3e398704E2cD9F38241eBB687794' ] │
    │    7    │ '0xb8ff8F2e849978CFaB2f39E1dcE72C2e5a6afbB6' │ 'astar' │ 'muuu-finance' │      'BAI-3KGL'      │ 2069.3034987517976 │ 0.8895084401674413  │ 0.8895084401674413  │                        [ '0x733ebcC6DF85f8266349DEFD0980f8Ced9B45f35', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xfe1Facac14b67685851FB5186B08d17108BC960b' ] │
    │    8    │ '0xc6650c2730dE47cB76e90Bbdcc29976172Bf4128' │ 'astar' │ 'muuu-finance' │     'oUSD-3KGL'      │ 1251.9116283270082 │ 16.663050360722444  │ 16.663050360722444  │                        [ '0x29F6e49c6E3397C3A84F715885F9F233A441165C', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x3EFED791e5a946D3d581D96Ee7FeaF796794412c' ] │
    │    9    │ '0x5fD86978Ee4df3E006448433Ec4Aa51D461bEdc8' │ 'astar' │ 'muuu-finance' │     'ASTR-nASTR'     │ 26.703433977350407 │ 0.36077776978813425 │ 0.36077776978813425 │                        [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xE511ED88575C57767BAfb72BfD10775413E3F2b0' ]                        │ [ '0x8B70B9A1e178006132044f121972f6A0d38EF5c6' ] │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────────────┴──────────────────────┴────────────────────┴─────────────────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ok i think i managed to confuse myself. 
can u confirm that the `base kagla vAPR` = fees? if so, use that part in apyBase.
In apyReward pls revert the changes (sry i misunderstood) to what u had before but remove the base kagla vAPR component. 

apyBase = fees
apyRewards = any extra tokens (kgl, muuu, etc)

**Comment by llamatester** [comment]
The muuu-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       74 passed, 74 total
    Snapshots:   0 total
    Time:        0.378 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────────────┬──────────────────────┬────────────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │    project     │        symbol        │       tvlUsd       │       apyBase       │     apyReward      │                                                               underlyingTokens                                                               │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────────────┼──────────────────────┼────────────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xd44e0Ed145904c1905129a767F2D6de2e68A23FC' │ 'astar' │ 'muuu-finance' │ 'lDAI-lUSDC-lceUSDT' │ 33930.51053179729  │ 1.0707436809331172  │ 11.450332260698183 │ [ '0x4dd9c468A44F3FEF662c35c1E9a6108B70415C2c', '0xC404E12D3466acCB625c67dbAb2E1a8a457DEf3c', '0x430D50963d9635bBef5a2fF27BD0bDDc26ed691F' ] │ [ '0x48611e9B924474F2a13b1C18E38B082099CBEF58' ] │
    │    1    │ '0x8ce5a2189c6fC5C0709aAF2Bde528d2ac7FECDdE' │ 'astar' │ 'muuu-finance' │     'aUSD-3KGL'      │ 19702.994663912108 │ 1.5234970082278254  │ 11.30505876775838  │                        [ '0xfFFFFfFF00000000000000010000000000000001', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xe2AcA2Be2b06313b22964786E7CA34d8c878e062' ] │
    │    2    │ '0x4af9ABbdffe5C76cAf9F8999f68F6f7564e3d0Ea' │ 'astar' │ 'muuu-finance' │     'BUSD-3KGL'      │ 10510.153422998757 │ 0.17291827432650564 │ 4.155064204226311  │                        [ '0x4Bf769b05E832FCdc9053fFFBC78Ca889aCb5E1E', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x8B23ca8D0cE64e570781428a5BAb241911077934' ] │
    │    3    │ '0x4Ab1099D84C52cE4a36Ee1FC4DF756c60fa0B348' │ 'astar' │ 'muuu-finance' │     'USDT-3KGL'      │  9094.19124585044  │  4.243121549832973  │ 42.38209751259787  │                        [ '0xfFFfffFF000000000000000000000001000007C0', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x2d173425E66112B8D6D5FB67a6355363B1bc4039' ] │
    │    4    │ '0xBa5534fd7b9A11bb6127eB6920fD9DBf0e67b5bf' │ 'astar' │ 'muuu-finance' │     'LAY-muLAY'      │ 6541.331769924658  │  7.638016218563548  │ 76.41711056020092  │                        [ '0xc4335B1b76fA6d52877b3046ECA68F6E708a27dd', '0xDDF2ad1d9bFA208228166311FC22e76Ea7a4C44D' ]                        │ [ '0xd997D637C1a3C3273c91A4C5b6C417395aF0948a' ] │
    │    5    │ '0x0125F9A29a985344E0f4159A6D55A2800cf46Ded' │ 'astar' │ 'muuu-finance' │  'DAI-USDC-ceUSDT'   │ 4041.319067633589  │ 0.3666908024575921  │ 2.9987656853117883 │ [ '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', '0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98', '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283' ] │ [ '0xA4A8163D0C9C41a918E4218b70e7B0BE4ac81983' ] │
    │    6    │ '0x4C565C34c4ecB07Ad168ded84C8DED8aEC1246A5' │ 'astar' │ 'muuu-finance' │     'KGL-muKGL'      │ 2491.3664637989204 │ 0.7352240952366307  │ 6.067958496840786  │                        [ '0x257f1a047948f73158DaDd03eB84b34498bCDc60', '0x5eaAe8435B178d4677904430BAc5079e73aFa56e' ]                        │ [ '0x51d6a5eE71FB3e398704E2cD9F38241eBB687794' ] │
    │    7    │ '0xb8ff8F2e849978CFaB2f39E1dcE72C2e5a6afbB6' │ 'astar' │ 'muuu-finance' │      'BAI-3KGL'      │ 2069.3034988891386 │ 0.8831646928888714  │ 7.344571346427409  │                        [ '0x733ebcC6DF85f8266349DEFD0980f8Ced9B45f35', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0xfe1Facac14b67685851FB5186B08d17108BC960b' ] │
    │    8    │ '0xc6650c2730dE47cB76e90Bbdcc29976172Bf4128' │ 'astar' │ 'muuu-finance' │     'oUSD-3KGL'      │ 1251.9116283505027 │  16.53621627073132  │ 161.96475166828267 │                        [ '0x29F6e49c6E3397C3A84F715885F9F233A441165C', '0x18BDb86E835E9952cFaA844EB923E470E832Ad58' ]                        │ [ '0x3EFED791e5a946D3d581D96Ee7FeaF796794412c' ] │
    │    9    │ '0x5fD86978Ee4df3E006448433Ec4Aa51D461bEdc8' │ 'astar' │ 'muuu-finance' │     'ASTR-nASTR'     │ 26.515087929879417 │  0.360151590876745  │ 2.8410821743668935 │                        [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xE511ED88575C57767BAfb72BfD10775413E3F2b0' ]                        │ [ '0x8B70B9A1e178006132044f121972f6A0d38EF5c6' ] │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────────────┴──────────────────────┴────────────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
