### PR TITLE
Tidied up a bit for Fringe V2 - multi-chain, multiple lending pools.

### PR DESCRIPTION
**Pull request by brainspacer**

### CODE REVIEW

**Comment by llamatester** [comment]
The fringe adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       418 passed, 418 total
    Snapshots:   0 total
    Time:        0.382 s
    Ran all test suites.
    
    Nb of pools: 69
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬──────────┬────────────────────┬─────────┬───────────────┬────────────────────┬──────────────────────────────────────────────────┬─────────────────────┬────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │  symbol  │       tvlUsd       │ apyBase │ apyBaseBorrow │   totalSupplyUsd   │                 underlyingTokens                 │      poolMeta       │ totalBorrowUsd │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼──────────┼────────────────────┼─────────┼───────────────┼────────────────────┼──────────────────────────────────────────────────┼─────────────────────┼────────────────┤
    │    0    │ '0x65c98cba99b3b8c17791e15b44b4bd88e184159f' │ 'optimism' │ 'fringe' │  'USDC'  │  1462.89385529394  │    0    │       0       │  1514.85443929394  │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Fringe V2 markets' │   51.960584    │
    │    1    │ '0x5c59341de108a5a7d903e1a7384b42c488749e96' │ 'optimism' │ 'fringe' │  'WBTC'  │ 472.10314913999997 │    0    │       0       │ 472.10314913999997 │ [ '0x68f180fcce6836688e9084f035309e29bf0a2095' ] │ 'Fringe V2 markets' │       0        │
    │    2    │ '0x255ca4713bc1d673551f3a4eca46b6380c984cf7' │ 'optimism' │ 'fringe' │   'OP'   │       459.99       │    0    │       0       │       459.99       │ [ '0x4200000000000000000000000000000000000042' ] │ 'Fringe V2 markets' │       0        │
    │    3    │ '0x38198d37cb0caa439d08c3606095c9682bb1dd6c' │ 'ethereum' │ 'fringe' │  'USDC'  │   29.47202542383   │    0    │       0       │      29.99043      │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'Fringe V2 markets' │ 0.51840457617  │
    │    4    │ '0x31bf1b14784d1875043fc79e428af14eae696916' │   'era'    │ 'fringe' │  'WBTC'  │    27.51242619     │    0    │       0       │    27.51242619     │ [ '0xbbeb516fb02a01611cbbe0453fe3c580d7281011' ] │ 'Fringe V2 markets' │       0        │
    │    5    │ '0x41ddd7b64cadee12916a5c38e7d4defb3263a018' │   'era'    │ 'fringe' │  'WETH'  │ 22.993005000000007 │    0    │       0       │ 22.993005000000007 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91' ] │ 'Fringe V2 markets' │       0        │
    │    6    │ '0x18126fef4cd8700db1ae6f8fd1a8c9f5159e06f2' │ 'polygon'  │ 'fringe' │ 'wstETH' │ 21.43738838751218  │    0    │       0       │ 21.43738838751218  │ [ '0x03b54a6e9a984069379fae1a4fc4dbae93b3bccd' ] │ 'Fringe V2 markets' │       0        │
    │    7    │ '0x03131545c6eb9d5179b59c98967b0121a2ee2d9d' │   'era'    │ 'fringe' │  'USDC'  │  21.097849638342   │    0    │       0       │  21.097849638342   │ [ '0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4' ] │ 'Fringe V2 markets' │       0        │
    │    8    │ '0x6ccfa052239bc9838b070df112cb1713b1ed2bdc' │   'era'    │ 'fringe' │  'USDT'  │  21.093588303144   │    0    │       0       │  21.093588303144   │ [ '0x493257fd37edb34451f62edf8d2a0c418852ba4c' ] │ 'Fringe V2 markets' │       0        │
    │    9    │ '0x4b4e6022710f478da8dbc1ac2660b04826e78ca9' │ 'optimism' │ 'fringe' │  'LDO'   │       20.942       │    0    │       0       │       20.942       │ [ '0xfdb794692724153d1488ccdbe0c56c252596735f' ] │ 'Fringe V2 markets' │       0        │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴──────────┴────────────────────┴─────────┴───────────────┴────────────────────┴──────────────────────────────────────────────────┴─────────────────────┴────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, any reason you swapped sdk for web3? if you import `require('@defillama/sdk4')` u can access the newer chains

**Comment by brainspacer** [comment]
We used web3 because the SDK fails the RPC calls. We're trying now again
with the SDK and using .env to declare the custom RPCs, but it is failing.
Not yet sure if the yield adapter is correctly picking up the custom RPC
(specifically having issues with Eth RPCs, and we've tried many in .env)

We note, that the TVL adapters can use web3.

Is there any plan for the yield adapter environment to support web3?

**Comment by slasher125** [comment]
if u run locally, make sure to run it from within /src/adaptors

**Comment by slasher125** [comment]
think best to open up a new pr, closing this one

**Pull request closed without merging**
