### PR TITLE
Umami Finance : Add GM vaults adaptor

### PR DESCRIPTION
**Pull request by Clonescody**
Add adaptor for Umami GM vaults 

Our logic to calculate APR is to use the weighted APR of the underlying GMX GM Markets held in our GMI contract.
The buffer held in our GmiAggregateVault is also deducted in order to have the closest-to-reality APR from GM Markets.

Apr for GM market is calculated using the same methodology as GMX v2 integration & front-end.

Umami's vaults page : https://umami.finance/vaults 
GM vaults documentation : https://umami-dao.gitbook.io/umami-dao/gm-vaults/overview 
GM vaults audit with Guardian : https://umami-dao.gitbook.io/umami-dao/gm-vaults/security

Would be nice if the audit could be added to the protocol page as well 🙏 

Misc : 
- Make a clear naming distinction between GLP and GM vaults (hence the "new" old files)
- Even out ABI imports as js files
- Fix underlyingToken price fetch erroring in GLP vaults

### CODE REVIEW

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.257 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬───────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┬───────────────────┬───────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │      apyBase      │  symbol   │                                          rewardTokens                                          │                 underlyingTokens                 │                   url                    │   chain    │     project     │        apy        │     apyReward     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼───────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┼───────────────────┼───────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │  1659546.25874089  │       14.98       │ 'mUMAMI'  │                        [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    1    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 1270414.2710709448 │       44.23       │ 'glpUSDC' │                        [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ]                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    2    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 1244192.4015932076 │       -7.12       │ 'glpWETH' │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    3    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1183683.2385547913 │       16.15       │ 'cmUMAMI' │                        [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    4    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 828548.1951016269  │ 9.625000563814872 │ 'gmUSDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │ 9.625000563814872 │ 39.89927287429108 │
    │    5    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 702693.0076433152  │ 9.625000563814872 │ 'gmWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │ 9.625000563814872 │ 49.07181741585727 │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │  623064.15015039   │       17.5        │ 'glpWBTC' │                        [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ]                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    7    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 91512.05196889401  │       13.34       │ 'glpLINK' │                        [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ]                        │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │  'https://umami.finance/vaults/glplink'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    8    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 37553.478884037824 │       23.65       │ 'glpUNI'  │                        [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ]                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴───────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┴───────────────────┴───────────────────┘

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.294 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬───────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┬───────────────────┬───────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │      apyBase      │  symbol   │                                          rewardTokens                                          │                 underlyingTokens                 │                   url                    │   chain    │     project     │        apy        │     apyReward     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼───────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┼───────────────────┼───────────────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 1659501.6872659312 │       14.98       │ 'mUMAMI'  │                        [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    1    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │   1269103.043758   │       44.23       │ 'glpUSDC' │                        [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ]                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    2    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 1243360.8763356432 │       -7.12       │ 'glpWETH' │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    3    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1183683.2385547913 │       16.15       │ 'cmUMAMI' │                        [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    4    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 827341.5314777652  │ 9.07385867593704  │ 'gmUSDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │ 9.07385867593704  │ 39.9574699996691  │
    │    5    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │  702255.237138053  │ 8.497630420757124 │ 'gmWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │ 8.497630420757124 │ 49.10240771005262 │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │  622564.16529546   │       17.5        │ 'glpWBTC' │                        [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ]                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    7    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 91672.21960820993  │       13.34       │ 'glpLINK' │                        [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ]                        │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │  'https://umami.finance/vaults/glplink'  │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    │    8    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 37491.36636694981  │       23.65       │ 'glpUNI'  │                        [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ]                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │                   │                   │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴───────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┴───────────────────┴───────────────────┘

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       67 passed, 67 total
    Snapshots:   0 total
    Time:        0.267 s
    Ran all test suites.
    
    Nb of pools: 9
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┬──────┬───────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  symbol   │                                          rewardTokens                                          │                 underlyingTokens                 │                   url                    │   chain    │     project     │ apy  │ apyReward │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┼──────┼───────────┤
    │    0    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 1659501.6872659312 │  14.98  │ 'mUMAMI'  │                        [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    1    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │   1269184.407802   │  44.23  │ 'glpUSDC' │                        [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ]                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    2    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 1242332.5787993078 │  -7.12  │ 'glpWETH' │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    3    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1183683.2385547913 │  16.15  │ 'cmUMAMI' │                        [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    4    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 827357.7867954699  │  9.08   │ 'gmUSDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │ 9.08 │   39.96   │
    │    5    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 701617.7430537512  │   8.5   │ 'gmWETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │ 8.5  │   49.15   │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │   622441.5310485   │  17.5   │ 'glpWBTC' │                        [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ]                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    7    │ '0xe0a21a475f8da0ee7fa5af8c1809d8ac5257607d' │ 91464.24771519305  │  13.34  │ 'glpLINK' │                        [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ]                        │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │  'https://umami.finance/vaults/glplink'  │ 'Arbitrum' │ 'umami-finance' │      │           │
    │    8    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 37493.62639812194  │  23.65  │ 'glpUNI'  │                        [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ]                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │      │           │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┴──────┴───────────┘

**Comment by Define101** [comment]
I added the audit already slasher

**Comment by slasher125** [comment]
> I added the audit already slasher
ty

**Pull request merged**
