### PR TITLE
BabyDoge APR Update base on Block

### PR DESCRIPTION
**Pull request by itdev-1210**

### CODE REVIEW

**Comment by llamatester** [comment]
The babydogeswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       1250 passed, 1250 total
    Snapshots:   0 total
    Time:        0.76 s
    Ran all test suites.
    
    Nb of pools: 178
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬────────────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │    project     │     symbol      │       tvlUsd       │                   rewardTokens                   │     apyReward      │       apyBase        │                                        underlyingTokens                                        │               poolMeta               │
    ├─────────┼──────────────────────────────────────────────┼───────────┼────────────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┤
    │    0    │ '0xcecd3e7eadae1ad0c94f53bf6a2af188df1a90d0' │ 'Binance' │ 'babydogeswap' │   'BabyDoge'    │ 4457209.702157369  │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 6.431345187853582  │          0           │                        [ '0xc748673057861a797275cd8a068abb95a902e8de' ]                        │   'Stake BabyDoge, Earn BabyDoge'    │
    │    1    │ '0x3fdbaf9ee8ad48d2bd9204210234afb4ad651fb0' │ 'Binance' │ 'babydogeswap' │   'USDT-BUSD'   │ 4108939.0975094778 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 11.16233791310234  │ 0.015028104513879844 │ [ '0x55d398326f99059ff775485246999027b3197955', '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │   'Stake USDT-BUSD, Earn BabyDoge'   │
    │    2    │ '0x9ccb41a29811608e633a030f9ad6a2aee34fcd10' │ 'Binance' │ 'babydogeswap' │ 'WBNB-BabyDoge' │ 3011730.4161871974 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 76.14454206167525  │ 0.17714531783558657  │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 'Stake WBNB-BabyDoge, Earn BabyDoge' │
    │    3    │ '0x332404fd2ddf1f1ff35a7eee95375cc1323fb2df' │ 'Binance' │ 'babydogeswap' │   'WBNB-BUSD'   │ 2437786.4141048994 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 23.450233344643433 │  1.6340566466785447  │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │   'Stake WBNB-BUSD, Earn BabyDoge'   │
    │    4    │ '0xf0ab4371857487c41f042bc63ee7c96091a9e99c' │ 'Binance' │ 'babydogeswap' │   'USDT-WBNB'   │ 1807981.1245349885 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 25.295246495392337 │  1.2068714654326453  │ [ '0x55d398326f99059ff775485246999027b3197955', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │   'Stake USDT-WBNB, Earn BabyDoge'   │
    │    5    │ '0x12afe3f3bdc7dc171cc1db8dd47917bda3f813a0' │ 'Binance' │ 'babydogeswap' │   'BTCB-WBNB'   │ 1548488.5782472258 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 14.80972068992422  │  0.2620138807302839  │ [ '0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │   'Stake BTCB-WBNB, Earn BabyDoge'   │
    │    6    │ '0x4aa6f6778d48f2c30b712a7ce47b073afada806b' │ 'Binance' │ 'babydogeswap' │   'ETH-WBNB'    │ 1504558.5217657958 │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 19.052668111294853 │  0.5810454973339778  │ [ '0x2170ed0880ac9a755fd29b2688956bd959f933f8', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │   'Stake ETH-WBNB, Earn BabyDoge'    │
    │    7    │ '0xe5174533d8b07228183184a7ac95963b2078e2ce' │ 'Binance' │ 'babydogeswap' │   'USDT-DOGE'   │ 517867.4993083692  │ [ '0xc748673057861a797275cd8a068abb95a902e8de' ] │ 30.752025488617996 │  3.5267726540588837  │ [ '0x55d398326f99059ff775485246999027b3197955', '0xba2ae424d960c26247dd6c32edc70b295c744c43' ] │   'Stake USDT-DOGE, Earn BabyDoge'   │
    │    8    │ '0x4066589193db01c82b3ad3f24894d40a457fb4c8' │ 'Binance' │ 'babydogeswap' │   'GVR-WBNB'    │ 108636.5766077704  │ [ '0xafb64e73def6faa8b6ef9a6fb7312d5c4c15ebdb' ] │ 136.35270274471287 │  3.499404264399942   │ [ '0xafb64e73def6faa8b6ef9a6fb7312d5c4c15ebdb', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │      'Stake GVR-WBNB, Earn GVR'      │
    │    9    │ '0x7e67e0135bc412bf1cd0580b9f275c5b9e5923be' │ 'Binance' │ 'babydogeswap' │     'FLOKI'     │ 90074.60897154789  │ [ '0xfb5b838b6cfeedc2873ab27866079ac55363d37e' ] │ 0.6117221547193191 │          0           │                        [ '0xfb5b838b6cfeedc2873ab27866079ac55363d37e' ]                        │      'Stake FLOKI, Earn FLOKI'       │
    └─────────┴──────────────────────────────────────────────┴───────────┴────────────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, can u briefly describe on a high level what this change does? ty

**Comment by itdev-1210** [comment]
Before, we are calc based on Date.now() for calc average 7 days volume.
We found some issue from there, so we are updating that from based on block number.

**Comment by itdev-1210** [comment]
@slasher125 
This is the last update from us.

**Pull request merged**
