### PR TITLE
add adapter for spice finance

### PR DESCRIPTION
**Pull request by 0xm00neth**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running spice-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.432 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬─────────┬──────────────────┬────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol  │      tvlUsd      │        apy         │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼─────────┼──────────────────┼────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'SPICE' │ 537515.331167347 │ 15.012782058868934 │
    └─────────┴────────────────────────┴────────────┴─────────────────┴─────────┴──────────────────┴────────────────────┘
    }

**Comment by slasher125** [comment]
@0xm00neth henlo. is this space trade? pls make sure that the project name matches the slug from the the protocols api response. (see readme)

**Comment by 0xm00neth** [comment]
@slasher125 No, this is not space trade.
What should I do to include our slug to the protocols api response?

**Comment by slasher125** [comment]
are u guys listed on TVL page already? if not then u need to be listed there first before we can add u on yields.

**Comment by llamatester** [comment]
The spice-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.334 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬─────────┬────────────────────┬────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol  │       tvlUsd       │        apy         │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼─────────┼────────────────────┼────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'SPICE' │ 521702.85475130845 │ 15.026948581006803 │
    └─────────┴────────────────────────┴────────────┴─────────────────┴─────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
@0xm00neth works now. one thing though, the deposit token is WETH yes, not SPICE? maybe i'm looking at the wrong place but if its eth then pls update the symbol

**Comment by 0xm00neth** [comment]
@slasher125 I've updated symbol to `WETH`

**Comment by llamatester** [comment]
The spice-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.334 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬────────┬────────────────────┬────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol │       tvlUsd       │        apy         │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼────────┼────────────────────┼────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'WETH' │ 519207.79133916047 │ 15.171500000689447 │
    └─────────┴────────────────────────┴────────────┴─────────────────┴────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
ty, can u give me a brief explanation how the thing works? what happens to my weth after i deposit? eg what am I exposed to?

**Comment by 0xm00neth** [comment]
deposited weth is invested in other nft protocols like nftfi, arcade and x2y2

**Pull request merged**
