### PR TITLE
Added Pearl pools

### PR DESCRIPTION
**Pull request by SeaZarrgh**

### CODE REVIEW

**Comment by llamatester** [comment]
The pearlfi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.438 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────┬────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │  project  │     symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────┼────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xf6A72Bd46F53Cd5103812ea1f4B5CF38099aB797' │ 'Polygon' │ 'pearlfi' │  'USDC-USDR'   │ 13102314.37889986  │ 29.523405307193286 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    1    │ '0x6ab291A9BB3C20F0017f2E93A6d1196842D09bF4' │ 'Polygon' │ 'pearlfi' │   'DAI-USDR'   │  8375290.96930828  │ 27.423625520899986 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    2    │ '0x6B3aA71C74042e113Bd0b055224d70a131334761' │ 'Polygon' │ 'pearlfi' │  'WETH-USDR'   │ 1872697.3514234086 │ 34.506794327479675 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    3    │ '0x413dEd0698B0947105bEb3c81786Dcf718AA24D1' │ 'Polygon' │ 'pearlfi' │  'WBTC-USDR'   │ 1703816.3788515264 │ 37.87167966501415  │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    4    │ '0x5f9fEcbeCCaa14767cE5e067641002673cE3E946' │ 'Polygon' │ 'pearlfi' │ 'WMATIC-USDR'  │ 1349883.180743704  │ 51.061871802251346 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    5    │ '0x10E1b58B3C93890D04D539b5f39Aa4Df27A362b2' │ 'Polygon' │ 'pearlfi' │  'WUSDR-USDR'  │ 923254.1380402549  │ 26.836201614904187 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0xAF0D9D65fC54de245cdA37af3d18cbEc860A4D4b', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    6    │ '0x733eEEf37De013283da29cE9EB4758dC59CaFc87' │ 'Polygon' │ 'pearlfi' │ 'STMATIC-USDR' │ 847791.0127970506  │ 61.94774708271862  │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    7    │ '0x74ee7376Ac31628a66b2Bb0eb2D14b549AB37275' │ 'Polygon' │ 'pearlfi' │  'PEARL-USDR'  │ 642030.8815672174  │ 283.9432836604785  │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    8    │ '0x8C1C63c20bCF4a27c985340b36df86d1a6fA840e' │ 'Polygon' │ 'pearlfi' │   'MAI-USDR'   │ 227322.4927711577  │  39.4682346038191  │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0xa3Fa99A148fA48D14Ed51d610c367C61876997F1', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    │    9    │ '0x16e9D19221DF563CfB15628953B5c51E4a2Be30c' │ 'Polygon' │ 'pearlfi' │  'TNGBL-USDR'  │ 164254.09327197055 │ 1567.8060574002566 │ [ '0x7238390d5f6F64e67c3211C343A410E2A3DEc142' ] │ [ '0x49e6A20f1BBdfEeC2a8222E052000BbB14EE6007', '0xb5DFABd7fF7F83BAB83995E72A52B97ABb7bcf63' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────┴────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
gm, ty for adding. pls confirm rewards are lower bound and unboosted

**Comment by SeaZarrgh** [comment]
Confirmed, it's the bare minimum based on current deposits and emissions.

**Comment by SeaZarrgh** [comment]
@slasher125 Why did we get that little tag that says "Project has no token and might airdrop one to depositors in the future"? We actually do have a token (`PEARL` deployed at `0x7238390d5f6F64e67c3211C343A410E2A3DEc142` on Polygon) and we already had an airdrop. Do we need another PR to fix that?

**Comment by 0xngmi** [comment]
just fixed, will be live on website soonish

**Pull request merged**
