### PR TITLE
Add Stella Lend 

### PR DESCRIPTION
**Pull request by arintrongs**

### CODE REVIEW

**Comment by llamatester** [comment]
The stella adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       51 passed, 51 total
    Snapshots:   0 total
    Time:        0.443 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬──────────┬────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │ project  │  symbol  │       tvlUsd       │       apyBase       │                 underlyingTokens                 │              poolMeta               │                                             url                                              │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼──────────┼────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xab416e57ec74e87295b8a1507745a954b0bb9f02-arbitrum' │ 'Arbitrum' │ 'stella' │  'ARB'   │  290874.689914039  │ 0.8669379395652139  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │  'Lend ARB and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0xab416e57ec74e87295b8a1507745a954b0bb9f02?action=deposit' │ 5.921355443749451  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    1    │ '0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa-arbitrum' │ 'Arbitrum' │ 'stella' │ 'USDC.e' │ 161419.99217242558 │ 3.9105431611480848  │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'Lend USDC.e and earn shared yield' │ 'https://app.stellaxyz.io/lending/0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa?action=deposit' │ 10.670130789819547 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    2    │ '0x5ecb93b3ef882bf42fee65541942d50a7dab4b33-arbitrum' │ 'Arbitrum' │ 'stella' │  'ETH'   │ 151478.95592386412 │  1.108920815245113  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'Lend ETH and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0x5ecb93b3ef882bf42fee65541942d50a7dab4b33?action=deposit' │ 11.370374307551485 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    3    │ '0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6-arbitrum' │ 'Arbitrum' │ 'stella' │  'USDT'  │   100338.394648    │  0.696649613286907  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │  'Lend USDT and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6?action=deposit' │                    │                                                  │
    │    4    │ '0x8e57143d14bae132210cfeec58d0c48875f7d415-arbitrum' │ 'Arbitrum' │ 'stella' │  'WBTC'  │   45873.63777548   │ 0.03769733025924207 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'Lend WBTC and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0x8e57143d14bae132210cfeec58d0c48875f7d415?action=deposit' │                    │                                                  │
    │    5    │ '0xdab9de68df2fde5db2da81f50265a4a21f8298e2-arbitrum' │ 'Arbitrum' │ 'stella' │  'GMX'   │ 24222.31199343571  │ 0.05728636164915863 │ [ '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a' ] │  'Lend GMX and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0xdab9de68df2fde5db2da81f50265a4a21f8298e2?action=deposit' │ 14.221371015600772 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    6    │ '0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853-arbitrum' │ 'Arbitrum' │ 'stella' │  'RDNT'  │ 23013.884746135653 │ 0.7365881240480501  │ [ '0x3082cc23568ea640225c2467653db90e9250aaa0' ] │  'Lend RDNT and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853?action=deposit' │ 14.968115531739052 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴──────────┴────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Comment by llamatester** [comment]
The stella adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       51 passed, 51 total
    Snapshots:   0 total
    Time:        0.323 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬──────────┬────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │ project  │  symbol  │       tvlUsd       │       apyBase       │                 underlyingTokens                 │              poolMeta               │                                             url                                              │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼──────────┼────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xab416e57ec74e87295b8a1507745a954b0bb9f02-arbitrum' │ 'Arbitrum' │ 'stella' │  'ARB'   │  290874.689914039  │ 0.8669379395652139  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │  'Lend ARB and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0xab416e57ec74e87295b8a1507745a954b0bb9f02?action=deposit' │ 5.921355443749451  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    1    │ '0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa-arbitrum' │ 'Arbitrum' │ 'stella' │ 'USDC.e' │ 161419.99217242558 │ 3.9105431611480848  │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'Lend USDC.e and earn shared yield' │ 'https://app.stellaxyz.io/lending/0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa?action=deposit' │ 10.670130789819547 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    2    │ '0x5ecb93b3ef882bf42fee65541942d50a7dab4b33-arbitrum' │ 'Arbitrum' │ 'stella' │  'ETH'   │ 151478.95592386412 │  1.108920815245113  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'Lend ETH and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0x5ecb93b3ef882bf42fee65541942d50a7dab4b33?action=deposit' │ 11.370374307551485 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    3    │ '0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6-arbitrum' │ 'Arbitrum' │ 'stella' │  'USDT'  │   100338.394648    │  0.696649613286907  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │  'Lend USDT and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6?action=deposit' │                    │                                                  │
    │    4    │ '0x8e57143d14bae132210cfeec58d0c48875f7d415-arbitrum' │ 'Arbitrum' │ 'stella' │  'WBTC'  │   45873.63777548   │ 0.03769733025924207 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'Lend WBTC and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0x8e57143d14bae132210cfeec58d0c48875f7d415?action=deposit' │                    │                                                  │
    │    5    │ '0xdab9de68df2fde5db2da81f50265a4a21f8298e2-arbitrum' │ 'Arbitrum' │ 'stella' │  'GMX'   │ 24222.31199343571  │ 0.05728636164915863 │ [ '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a' ] │  'Lend GMX and earn shared yield'   │ 'https://app.stellaxyz.io/lending/0xdab9de68df2fde5db2da81f50265a4a21f8298e2?action=deposit' │ 14.221371015600772 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    6    │ '0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853-arbitrum' │ 'Arbitrum' │ 'stella' │  'RDNT'  │ 23013.884746135653 │ 0.7365881240480501  │ [ '0x3082cc23568ea640225c2467653db90e9250aaa0' ] │  'Lend RDNT and earn shared yield'  │ 'https://app.stellaxyz.io/lending/0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853?action=deposit' │ 14.968115531739052 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴──────────┴────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
gm, ty for adding!

- imo u can remove `poolMeta` in your case,we usually reserve this field for things such as fee tiers, lock up periods (if any). but in your case its not really relevant as its self explanatory.
- tvlUsd for lending pools should be available liquidity, so totalSupply - totalBorrowed
- please add the additional lending fields to the adapter, that way we can also display your pools on our borrow aggregator: 
```  // optional lending protocol specific fields:
  apyBaseBorrow?: number;
  apyRewardBorrow?: number;
  totalSupplyUsd?: number;
  totalBorrowUsd?: number;
  ltv?: number; // btw [0, 1]```

**Comment by llamatester** [comment]
The stella adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       51 passed, 51 total
    Snapshots:   0 total
    Time:        0.343 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │ project  │  symbol  │       tvlUsd       │   totalSupplyUsd   │   totalBorrowUsd   │       apyBase       │                 underlyingTokens                 │                                             url                                              │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa-arbitrum' │ 'Arbitrum' │ 'stella' │ 'USDC.e' │ 87397.19869988087  │ 206036.24115311212 │ 118639.04245323125 │  4.10623847389203   │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://app.stellaxyz.io/lending/0x3251f402cc06b33e742f08e1adbe0d2e4c1ea2fa?action=deposit' │  8.97906245246879  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    1    │ '0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6-arbitrum' │ 'Arbitrum' │ 'stella' │  'USDT'  │    70645.510103    │   100359.675333    │    29714.16523     │ 1.7909561619111043  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │ 'https://app.stellaxyz.io/lending/0x36569fbc5a9d4c59d71e81d46db24256a09d1ad6?action=deposit' │                    │                                                  │
    │    2    │ '0x5ecb93b3ef882bf42fee65541942d50a7dab4b33-arbitrum' │ 'Arbitrum' │ 'stella' │  'ETH'   │ 67491.20819149665  │ 164493.09889668596 │  97001.8907051893  │  1.562990142088461  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://app.stellaxyz.io/lending/0x5ecb93b3ef882bf42fee65541942d50a7dab4b33?action=deposit' │ 11.24674706230479  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    3    │ '0x8e57143d14bae132210cfeec58d0c48875f7d415-arbitrum' │ 'Arbitrum' │ 'stella' │  'WBTC'  │    36508.354448    │    45902.669896    │    9394.315448     │ 0.03246597979321749 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://app.stellaxyz.io/lending/0x8e57143d14bae132210cfeec58d0c48875f7d415?action=deposit' │                    │                                                  │
    │    4    │ '0xdab9de68df2fde5db2da81f50265a4a21f8298e2-arbitrum' │ 'Arbitrum' │ 'stella' │  'GMX'   │ 13364.865599562401 │ 13995.999623016707 │ 631.1340234543056  │ 0.20135431837829543 │ [ '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a' ] │ 'https://app.stellaxyz.io/lending/0xdab9de68df2fde5db2da81f50265a4a21f8298e2?action=deposit' │ 26.43630075187099  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    5    │ '0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853-arbitrum' │ 'Arbitrum' │ 'stella' │  'RDNT'  │ 5082.293593615384  │ 24635.961933146977 │ 19553.668339531592 │ 1.8714047373669158  │ [ '0x3082cc23568ea640225c2467653db90e9250aaa0' ] │ 'https://app.stellaxyz.io/lending/0xc1e2c1f9c4fe278d0db0d3d8eff359f8b235f853?action=deposit' │ 15.018794734347882 │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    │    6    │ '0xab416e57ec74e87295b8a1507745a954b0bb9f02-arbitrum' │ 'Arbitrum' │ 'stella' │  'ARB'   │  2.80499972650736  │ 212885.8817320083  │ 212883.0767322818  │ 1.9684129171763605  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'https://app.stellaxyz.io/lending/0xab416e57ec74e87295b8a1507745a954b0bb9f02?action=deposit' │ 8.690159543386745  │ [ '0xc9cbf102c73fb77ec14f8b4c8bd88e050a6b2646' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
