### PR TITLE
add swop adapter

### PR DESCRIPTION
**Pull request by vladislavpetushkov**

### CODE REVIEW

**Comment by llamatester** [comment]
The swop adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       424 passed, 424 total
    Snapshots:   0 total
    Time:        0.349 s
    Ran all test suites.
    
    Nb of pools: 60
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────┬─────────┬─────────┬──────────────┬───────────┬─────────┬───────────┬────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────┐
    │ (index) │                    pool                     │  chain  │ project │    symbol    │  tvlUsd   │ apyBase │ apyReward │                    rewardTokens                    │                                          underlyingTokens                                          │                                url                                 │
    ├─────────┼─────────────────────────────────────────────┼─────────┼─────────┼──────────────┼───────────┼─────────┼───────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────┤
    │    0    │ '3phangombkrvel2qnujarqvja71wjw9qiqg-waves' │ 'Waves' │ 'swop'  │ 'WAVES-XTN'  │ 436301.12 │  6.53   │   19.17   │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'WAVES', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ]                     │ 'https://swop.fi/pool?address=3PHaNgomBkrvEL2QnuJarQVJa71wjw9qiqG' │
    │    1    │ '3pnvfwopwcd9cggxkpywey94oq5xcaexbmq-waves' │ 'Waves' │ 'swop'  │ 'EGG-WAVES'  │ 76899.01  │   2.2   │   10.1    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS', 'WAVES' ]                     │ 'https://swop.fi/pool?address=3PNVFWopwCD9CgGXkpYWEY94oQ5XCAEXBmQ' │
    │    2    │ '3p27s9v36kw2mcjwrz37axtx8iwkd7hxw6w-waves' │ 'Waves' │ 'swop'  │  'SWOP-XTN'  │ 38860.48  │  7.24   │   13.19   │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P27S9V36kw2McjWRZ37AxTx8iwkd7HXw6W' │
    │    3    │ '3plp9krdrbwavsfhgjveaszuubquz3m6mfe-waves' │ 'Waves' │ 'swop'  │  'SURF-XTN'  │ 37245.37  │  0.37   │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'At8D6NFFpheCbvKVnjVoeLL84Eo8NZn6ovManxfLaFWL', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PLp9KrdrbWAvSFHGJVEaszUubquz3M6mfe' │
    │    4    │ '3pk7xe5biedryxhlumqx5ey9riuqqvuths2-waves' │ 'Waves' │ 'swop'  │ 'WAVES-EURN' │  23673.3  │  1.25   │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'WAVES', 'DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t' ]                     │ 'https://swop.fi/pool?address=3PK7Xe5BiedRyxHLuMQx5ey9riUQqvUths2' │
    │    5    │ '3p6dldjtp2eysq9mfdju6beuevrqd2svvbh-waves' │ 'Waves' │ 'swop'  │  'WEST-XTN'  │ 19919.25  │  18.32  │   0.04    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ '4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P6DLdJTP2EySq9MFdJu6beUevrQd2sVVBh' │
    │    6    │ '3pki4g3vx2k42zsmnnrmvgddh7jzrauhy7r-waves' │ 'Waves' │ 'swop'  │   'WX-XTN'   │ 16117.72  │  1.21   │   0.15    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PKi4G3VX2k42ZSmNNrmvgdDH7JzRaUhY7R' │
    │    7    │ '3ph8np6jwuoikvkhl2qmdpfehbr4uv5vwsq-waves' │ 'Waves' │ 'swop'  │ 'SWOP-WAVES' │ 14495.96  │  11.29  │   14.78   │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT', 'WAVES' ]                     │ 'https://swop.fi/pool?address=3PH8Np6jwuoikvkHL2qmdpFEHBR4UV5vwSq' │
    │    8    │ '3pbhyewmerr1cekrtnbpj2bgyistfprqfee-waves' │ 'Waves' │ 'swop'  │ 'PUZZLE-XTN' │ 12067.48  │  1.42   │   13.19   │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'HEB8Qaw9xrWpWs8tHsiATYGBWDBtP2S7kcPALrMu43AS', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PBHyEwmERR1CEkrTNbPj2bgyisTfPRqfee' │
    │    9    │ '3p8bovwtklfvtob8lxp8azlowvwc8rdzlqq-waves' │ 'Waves' │ 'swop'  │  'ENNO-XTN'  │ 10059.95  │  2.01   │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ '7LMV3s1J4dKpMQZqge5sKYoFkZRLojnnU49aerqos4yg', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P8bovWtkLFVToB8LxP8AZLoWVwC8rDZLQQ' │
    └─────────┴─────────────────────────────────────────────┴─────────┴─────────┴──────────────┴───────────┴─────────┴───────────┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, just to make sure, we do not display apy components which require extra tokens (eg veSWOP)

**Comment by vladislavpetushkov** [comment]
> hi, just to make sure, we do not display apy components which require extra tokens (eg veSWOP)

Do you mean with boosting?

**Comment by llamatester** [comment]
The swop adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       424 passed, 424 total
    Snapshots:   0 total
    Time:        0.358 s
    Ran all test suites.
    
    Nb of pools: 60
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────┬─────────┬─────────┬──────────────┬───────────┬─────────┬───────────┬────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────┐
    │ (index) │                    pool                     │  chain  │ project │    symbol    │  tvlUsd   │ apyBase │ apyReward │                    rewardTokens                    │                                          underlyingTokens                                          │                                url                                 │
    ├─────────┼─────────────────────────────────────────────┼─────────┼─────────┼──────────────┼───────────┼─────────┼───────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────┤
    │    0    │ '3phangombkrvel2qnujarqvja71wjw9qiqg-waves' │ 'Waves' │ 'swop'  │ 'WAVES-XTN'  │ 430893.34 │  6.29   │   6.38    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'WAVES', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ]                     │ 'https://swop.fi/pool?address=3PHaNgomBkrvEL2QnuJarQVJa71wjw9qiqG' │
    │    1    │ '3pnvfwopwcd9cggxkpywey94oq5xcaexbmq-waves' │ 'Waves' │ 'swop'  │ 'EGG-WAVES'  │  76396.7  │  1.38   │   3.35    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS', 'WAVES' ]                     │ 'https://swop.fi/pool?address=3PNVFWopwCD9CgGXkpYWEY94oQ5XCAEXBmQ' │
    │    2    │ '3p27s9v36kw2mcjwrz37axtx8iwkd7hxw6w-waves' │ 'Waves' │ 'swop'  │  'SWOP-XTN'  │ 38421.03  │  0.72   │   4.38    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P27S9V36kw2McjWRZ37AxTx8iwkd7HXw6W' │
    │    3    │ '3plp9krdrbwavsfhgjveaszuubquz3m6mfe-waves' │ 'Waves' │ 'swop'  │  'SURF-XTN'  │ 37064.05  │  0.26   │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'At8D6NFFpheCbvKVnjVoeLL84Eo8NZn6ovManxfLaFWL', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PLp9KrdrbWAvSFHGJVEaszUubquz3M6mfe' │
    │    4    │ '3pk7xe5biedryxhlumqx5ey9riuqqvuths2-waves' │ 'Waves' │ 'swop'  │ 'WAVES-EURN' │ 23437.62  │  0.84   │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'WAVES', 'DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t' ]                     │ 'https://swop.fi/pool?address=3PK7Xe5BiedRyxHLuMQx5ey9riUQqvUths2' │
    │    5    │ '3p6dldjtp2eysq9mfdju6beuevrqd2svvbh-waves' │ 'Waves' │ 'swop'  │  'WEST-XTN'  │ 19619.96  │  2.99   │   0.01    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ '4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P6DLdJTP2EySq9MFdJu6beUevrQd2sVVBh' │
    │    6    │ '3pki4g3vx2k42zsmnnrmvgddh7jzrauhy7r-waves' │ 'Waves' │ 'swop'  │   'WX-XTN'   │ 15904.14  │  0.45   │   0.05    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PKi4G3VX2k42ZSmNNrmvgdDH7JzRaUhY7R' │
    │    7    │ '3ph8np6jwuoikvkhl2qmdpfehbr4uv5vwsq-waves' │ 'Waves' │ 'swop'  │ 'SWOP-WAVES' │ 14275.78  │  1.15   │   4.93    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │                    [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT', 'WAVES' ]                     │ 'https://swop.fi/pool?address=3PH8Np6jwuoikvkHL2qmdpFEHBR4UV5vwSq' │
    │    8    │ '3pbhyewmerr1cekrtnbpj2bgyistfprqfee-waves' │ 'Waves' │ 'swop'  │ 'PUZZLE-XTN' │ 11872.36  │  0.99   │    4.4    │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ 'HEB8Qaw9xrWpWs8tHsiATYGBWDBtP2S7kcPALrMu43AS', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3PBHyEwmERR1CEkrTNbPj2bgyisTfPRqfee' │
    │    9    │ '3p8bovwtklfvtob8lxp8azlowvwc8rdzlqq-waves' │ 'Waves' │ 'swop'  │  'ENNO-XTN'  │  9969.94  │    0    │     0     │ [ 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT' ] │ [ '7LMV3s1J4dKpMQZqge5sKYoFkZRLojnnU49aerqos4yg', 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p' ] │ 'https://swop.fi/pool?address=3P8bovWtkLFVToB8LxP8AZLoWVwC8rDZLQQ' │
    └─────────┴─────────────────────────────────────────────┴─────────┴─────────┴──────────────┴───────────┴─────────┴───────────┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by vladislavpetushkov** [comment]
change reward apy to min(to get this apy no need to lock or boost)

**Pull request merged**
