### PR TITLE
add static reward APY for WiseLending

### PR DESCRIPTION
**Pull request by vm06007**
add static reward APY for WiseLending

### CODE REVIEW

**Comment by llamatester** [comment]
The wise-lending-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.274 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────┬────────────┬───────────────────┬──────────┬─────────────┬────────────────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                                 pool                                  │   chain    │      project      │  symbol  │  poolMeta   │       tvlUsd       │      apyBase       │ apyReward │                                          rewardTokens                                          │                 underlyingTokens                 │            url             │   apyBaseBorrow    │   totalSupplyUsd   │   totalBorrowUsd   │
    ├─────────┼───────────────────────────────────────────────────────────────────────┼────────────┼───────────────────┼──────────┼─────────────┼────────────────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8-wise-lending-v2-arbitrum' │ 'Arbitrum' │ 'wise-lending-v2' │  'WETH'  │ 'aArbWETH'  │ 21307.351011999017 │  3.61221072408104  │     3     │ [ '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8', '0x4A56DCd67E66102E6a877dE8BF2E903Df5E18978' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ 'https://wiselending.com/' │ 4.549530390492677  │ 164604.23289113538 │ 143297.24311882406 │
    │    1    │ '0x5979D7b546E38E414F7E9822514be443A4800529-wise-lending-v2-arbitrum' │ 'Arbitrum' │ 'wise-lending-v2' │ 'wstETH' │  'wstETH'   │ 12369.446274525462 │ 0.0179224326838959 │ undefined │ [ '0x5979D7b546E38E414F7E9822514be443A4800529', '0x4A56DCd67E66102E6a877dE8BF2E903Df5E18978' ] │ [ '0x5979D7b546E38E414F7E9822514be443A4800529' ] │ 'https://wiselending.com/' │ 0.2301129055840109 │ 16479.80703278148  │ 4110.360758256019  │
    │    2    │ '0x724dc807b04555b71ed48a6896b6F41593b8C637-wise-lending-v2-arbitrum' │ 'Arbitrum' │ 'wise-lending-v2' │  'USDC'  │ 'aArbUSDCn' │ 6631.002789805048  │  8.72442311198489  │     8     │ [ '0x724dc807b04555b71ed48a6896b6F41593b8C637', '0x4A56DCd67E66102E6a877dE8BF2E903Df5E18978' ] │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │ 'https://wiselending.com/' │ 10.26045284491001  │ 48079.303816019696 │ 41451.017062285115 │
    │    3    │ '0x6ab707Aca953eDAeFBc4fD23bA73294241490620-wise-lending-v2-arbitrum' │ 'Arbitrum' │ 'wise-lending-v2' │  'USDT'  │ 'aArbUSDT'  │ 2197.100216050176  │ 8.158948827191615  │     8     │ [ '0x6ab707Aca953eDAeFBc4fD23bA73294241490620', '0x4A56DCd67E66102E6a877dE8BF2E903Df5E18978' ] │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │ 'https://wiselending.com/' │ 9.633775486387718  │ 14954.650340260872 │ 12758.494883880025 │
    │    4    │ '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE-wise-lending-v2-arbitrum' │ 'Arbitrum' │ 'wise-lending-v2' │  'DAI'   │  'aArbDAI'  │ 2060.008281179124  │ 8.773499802995543  │     8     │ [ '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE', '0x4A56DCd67E66102E6a877dE8BF2E903Df5E18978' ] │ [ '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1' ] │ 'https://wiselending.com/' │ 10.19764437921425  │ 14870.847412597279 │ 12811.722928036268 │
    │    5    │ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2-wise-lending-v2-ethereum' │ 'Ethereum' │ 'wise-lending-v2' │  'WETH'  │   'WETH'    │ 262.36979924975316 │         0          │     3     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x78190e4c7C7B2c2C3b0562F1f155a1FC2F5160CA' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ 'https://wiselending.com/' │ 1.2276216283700796 │ 452.22944315941095 │ 189.85964390965776 │
    └─────────┴───────────────────────────────────────────────────────────────────────┴────────────┴───────────────────┴──────────┴─────────────┴────────────────────┴────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────────────┴────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
how are the reward rates constants?

**Comment by vm06007** [comment]
> how are the reward rates constants?

static APY from internal Points System integrated in WiseLending (https://app.wiselending.com/points)

**Comment by slasher125** [comment]
> static APY from internal Points System integrated in WiseLending (https://app.wiselending.com/points)

we aren't displaying points on our end

**Pull request closed without merging**
