### PR TITLE
Securo Finance but not working. Please have a look

### PR DESCRIPTION
**Pull request by AdityaPune**
The APRs and TVLs aren't being properly fetched. Could you have a look please.

### CODE REVIEW

**Comment by llamatester** [comment]
The securo-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       23 passed, 23 total
    Snapshots:   0 total
    Time:        0.507 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────────┬────────┬────────┬─────┐
    │ (index) │                     pool                     │    chain    │     project      │ symbol │ tvlUsd │ apy │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────────┼────────┼────────┼─────┤
    │    0    │ '0x8FD52c2156a0475e35E0FEf37Fa396611062c9b6' │    'bsc'    │ 'securo-finance' │ 'USDT' │  NaN   │ NaN │
    │    1    │ '0x72eB6E3f163E8CFD1Ebdd7B2f4ffB60b6e420448' │  'aurora'   │ 'securo-finance' │ 'USDT' │  NaN   │ NaN │
    │    2    │ '0xF9258759bADb75a9eAb16933ADd056c9F4E489b6' │  'polygon'  │ 'securo-finance' │ 'USDT' │  NaN   │ NaN │
    │    3    │ '0x5aCBd5b82edDae114EC0703c86d163bD0107367c' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │  NaN   │ NaN │
    │    4    │ '0xe76367024ca3AEeC875A03BB395f54D7c6A82eb0' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │  NaN   │ NaN │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────────┴────────┴────────┴─────┘

**Comment by glebskr** [comment]
Hello, thanks for your PR.
Made a quick draft.
Try something like this:



    const tvls = await Promise.all(Object.keys(config).map(async (chain) => {
      const vaults = Object.values(config[chain].vaults);
      const balances = (
        await sdk.api.abi.multiCall({
          abi: abiLci.getAllPoolInUSD,
          calls: vaults.map((i) => ({ target: i })),
          chain,
        })
      ).output.map(({ output }) => output / 1e18);
      return balances;
    }))

**Comment by llamatester** [comment]
The securo-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       23 passed, 23 total
    Snapshots:   0 total
    Time:        0.369 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────────┬────────┬──────────────────────┬──────────────────────┐
    │ (index) │                     pool                     │    chain    │     project      │ symbol │        tvlUsd        │         apy          │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────────┼────────┼──────────────────────┼──────────────────────┤
    │    0    │ '0x8FD52c2156a0475e35E0FEf37Fa396611062c9b6' │    'bsc'    │ 'securo-finance' │ 'USDT' │ 0.014954747296773204 │ 0.022927209051711393 │
    │    1    │ '0x72eB6E3f163E8CFD1Ebdd7B2f4ffB60b6e420448' │  'aurora'   │ 'securo-finance' │ 'USDT' │          0           │   0.0143739559161    │
    │    2    │ '0xF9258759bADb75a9eAb16933ADd056c9F4E489b6' │  'polygon'  │ 'securo-finance' │ 'USDT' │          0           │ 0.020180694075632225 │
    │    3    │ '0x5aCBd5b82edDae114EC0703c86d163bD0107367c' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │         NaN          │         NaN          │
    │    4    │ '0xe76367024ca3AEeC875A03BB395f54D7c6A82eb0' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │         NaN          │         NaN          │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────────┴────────┴──────────────────────┴──────────────────────┘

**Comment by glebskr** [comment]
1) 'bsc' => 'Binance', aurora => Aurora, polygon => Polygon
2) Apy and tvl should be number, but u have NaN
3) Your pools will not be visible on UI because we have tvl filter >$10k

**Comment by AdityaPune** [comment]
1. Okay I'll try to fix the NaN thing. 
2. Understood the TVL filter. For now just wanted to have the code ready, once the protocol is properly launched we can have it displayed with a better TVL

**Comment by glebskr** [comment]
And also apy numbers should be in %

**Comment by AdityaPune** [comment]
Yes, fixing that too

**Comment by llamatester** [comment]
The securo-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       23 passed, 23 total
    Snapshots:   0 total
    Time:        0.454 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────────┬────────┬──────────────────────┬────────────────────┐
    │ (index) │                     pool                     │    chain    │     project      │ symbol │        tvlUsd        │        apy         │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────────┼────────┼──────────────────────┼────────────────────┤
    │    0    │ '0x8FD52c2156a0475e35E0FEf37Fa396611062c9b6' │  'Binance'  │ 'securo-finance' │ 'USDT' │ 0.01495268226399361  │ 2.253292385598482  │
    │    1    │ '0x5aCBd5b82edDae114EC0703c86d163bD0107367c' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │ 0.005413932912584268 │ 0.9957771171571705 │
    │    2    │ '0x72eB6E3f163E8CFD1Ebdd7B2f4ffB60b6e420448' │  'Aurora'   │ 'securo-finance' │ 'USDT' │          0           │ 1.4491537246152708 │
    │    3    │ '0xF9258759bADb75a9eAb16933ADd056c9F4E489b6' │  'Polygon'  │ 'securo-finance' │ 'USDT' │          0           │ 1.9930676135146763 │
    │    4    │ '0xe76367024ca3AEeC875A03BB395f54D7c6A82eb0' │ 'Avalanche' │ 'securo-finance' │ 'USDT' │          0           │ 3.069956229152604  │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────────┴────────┴──────────────────────┴────────────────────┘

**Pull request merged**
