### PR TITLE
animeswap ANI yield

### PR DESCRIPTION
**Pull request by xiaozzz**

### CODE REVIEW

**Comment by llamatester** [comment]
The animeswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.311 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────────────┬─────────┬─────────────┬────────┬───────────────────┬───────────────────┐
    │ (index) │                                    pool                                    │  chain  │   project   │ symbol │      tvlUsd       │        apy        │
    ├─────────┼────────────────────────────────────────────────────────────────────────────┼─────────┼─────────────┼────────┼───────────────────┼───────────────────┤
    │    0    │ '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-aptos' │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 244079.4522269757 │ 90.35000543685837 │
    └─────────┴────────────────────────────────────────────────────────────────────────────┴─────────┴─────────────┴────────┴───────────────────┴───────────────────┘

**Comment by slasher125** [comment]
hi, ty for adding. would u mind adding the other 2 pools too?

**Comment by xiaozzz** [comment]
> hi, ty for adding. would u mind adding the other 2 pools too?
> 
> edit: also, is the above the "holder" pool? if so, then the tvl is wrong?

hi, i have added `Holder Pool` and `Stake ANI`, and fix the tvl. The former pool is auto-compound, but the latter one is not. Am i right? 
btw, the third pool `APT-ANI` is not a compound pool, so i do not show it in this adapter. is it suitable for showing apy for a non-autocompound pool like that?

**Comment by llamatester** [comment]
The animeswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.339 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────────┬────────┬────────────────────┬───────────────────┐
    │ (index) │                                         pool                                          │  chain  │   project   │ symbol │       tvlUsd       │        apy        │
    ├─────────┼───────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────────┼────────┼────────────────────┼───────────────────┤
    │    0    │  '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-StakeANI-aptos'  │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 245707.14265952513 │ 90.06442524129325 │
    │    1    │ '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-HolderPool-aptos' │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 113914.61909786054 │ 90.06442524129325 │
    └─────────┴───────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────────┴────────┴────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
to distinguish btw the two:
- use `poolMeta` where for one pool it would be `Holder Pool` and for the other `Stake ANI`
- apy for the `Stake ANI` pool should in this case be just the APR like on the UI ~64%

**Comment by xiaozzz** [comment]
> to distinguish btw the two:
> 
> * use `poolMeta` where for one pool it would be `Holder Pool` and for the other `Stake ANI`
> * apy for the `Stake ANI` pool should in this case be just the APR like on the UI ~64%

done

**Comment by llamatester** [comment]
The animeswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.393 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────────┬────────┬────────────────────┬───────────────────┬─────────────────────────────────────────────────────────────────────────┐
    │ (index) │                                         pool                                          │  chain  │   project   │ symbol │       tvlUsd       │        apy        │                                poolMeta                                 │
    ├─────────┼───────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────────┼────────┼────────────────────┼───────────────────┼─────────────────────────────────────────────────────────────────────────┤
    │    0    │  '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-StakeANI-aptos'  │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 245267.81555910112 │ 64.28216805286932 │                               'Stake ANI'                               │
    │    1    │ '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-HolderPool-aptos' │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 113739.9760017192  │ 90.07647208540952 │ 'Holder Pool. Auto-Compound. Lock 30 days or 20% unstaking fee penalty' │
    └─────────┴───────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────────┴────────┴────────────────────┴───────────────────┴─────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hey, we are just changing a few things regarding locks/vests etc...for the compound pool, can u please update the apy in such way that we assume an early exit penalty. basically i wanna see the minimum yield i can achieve here

**Comment by xiaozzz** [comment]
> hey, we are just changing a few things regarding locks/vests etc...for the compound pool, can u please update the apy in such way that we assume an early exit penalty. basically i wanna see the minimum yield i can achieve here

sry, i dont quiet understand what you mean. can you show some example document link or other project adapter? i have already added the compound pool meta `Lock 30 days or 20% unstaking fee penalty`. Should i add this value to some fields?

**Comment by slasher125** [comment]
so, on the compound pool if i exit lets say after 5days I'll pay an exit fee of 20%. What I'm asking to change is to update the apy value for the compound pool by accounting for the 20% exit penalty. eg i guess whats happening under the hood is if i stake 100 UNI, and after 5days I've earned 5 UNI (just making up the nb here), then I decide to unstake I will only receive my 100 UNI + 5 * 0.8 right? (or whatever the underlying contract does, you guys know best; could u explain how/ on what part the exit penalty is applied to? )

What we are trying to change currently is that we want to display the minimum yield a user can achieve. not some upper limit. 

One problem I see in regards to the compound pool is that the rate changes depending on when i unstake so its hard to generalise...eg its different if I exit early after 1 day or 5days...so actually it might make most sense to remove this pool altogether...

oh, and something else:
- apy -> should be `apyReward` cause the the apy is coming from incentives

**Comment by llamatester** [comment]
The animeswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.323 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────────┬────────┬───────────────────┬───────────────────┬──────────────────────────────────────────────────────────────────────────────────────────┬─────────────┐
    │ (index) │                                        pool                                         │  chain  │   project   │ symbol │      tvlUsd       │     apyReward     │                                       rewardTokens                                       │  poolMeta   │
    ├─────────┼─────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────────┼────────┼───────────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────────────────────┼─────────────┤
    │    0    │ '0x8615f5671592532631e56c76ca09d332fae1cd03d463bc379eec1007973966ef-StakeANI-aptos' │ 'Aptos' │ 'animeswap' │ 'ANI'  │ 249504.1846469309 │ 64.08251504689397 │ [ '0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c::AnimeCoin::ANI' ] │ 'Stake ANI' │
    └─────────┴─────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────────┴────────┴───────────────────┴───────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴─────────────┘

**Comment by slasher125** [comment]
would be cool if you'd include all non-farm pools too :) but merged this one for now

**Comment by xiaozzz** [comment]
> would be cool if you'd include all non-farm pools too :) but merged this one for now

ok. other pools are hard to calculate by aptos api, needing a lot of specific api calls. i am still working for a general method to calculate them with clean code.

**Pull request merged**
