### PR TITLE
add goose-finance

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The goose-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       88 passed, 88 total
    Snapshots:   0 total
    Time:        0.423 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────────────┬─────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │     project     │   symbol    │       tvlUsd       │        apy         │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────────────┼─────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x1B96B92314C44b159149f7E0303511fB2Fc4774f' │ 'Binance' │ 'goose-finance' │ 'WBNB-BUSD' │ 247426.64605096317 │ 3.1449429653393417 │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    1    │ '0x19e7cbECDD23A16DfA5573dF54d98F7CaAE03019' │ 'Binance' │ 'goose-finance' │ 'BUSD-EGG'  │ 147604.77398141273 │ 63.26158719230629  │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56', '0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    2    │ '0xd1B59D11316E87C3a0A069E80F590BA35cD8D8D3' │ 'Binance' │ 'goose-finance' │ 'WBNB-EGG'  │ 97451.46166707957  │ 95.81910952886416  │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    3    │ '0x3aB77e40340AB084c3e23Be8e5A6f7afed9D41DC' │ 'Binance' │ 'goose-finance' │ 'DAI-BUSD'  │ 97229.15576223566  │ 6.402546099142156  │ [ '0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    4    │ '0xc15fa3E22c912A276550F3E5FE3b0Deb87B55aCd' │ 'Binance' │ 'goose-finance' │ 'USDT-BUSD' │ 92207.19771890272  │ 6.751253344084331  │ [ '0x55d398326f99059fF775485246999027B3197955', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    5    │ '0x7561EEe90e24F3b348E1087A005F78B4c8453524' │ 'Binance' │ 'goose-finance' │ 'BTCB-WBNB' │ 63209.034988810694 │ 14.77274930851068  │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    6    │ '0xbCD62661A6b1DEd703585d3aF7d7649Ef4dcDB5c' │ 'Binance' │ 'goose-finance' │ 'DOT-WBNB'  │ 29292.62451635685  │ 31.87734944682637  │ [ '0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    7    │ '0x70D8929d04b60Af4fb9B58713eBcf18765aDE422' │ 'Binance' │ 'goose-finance' │ 'ETH-WBNB'  │ 20730.612148531265 │ 45.043109254674704 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    8    │ '0x680Dd100E4b394Bda26A59dD5c119A391e747d18' │ 'Binance' │ 'goose-finance' │ 'USDC-BUSD' │ 20180.10086442053  │ 30.847920737895805 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    9    │ '0x9fE5e1DbE102d4Dfa52176F5667E714aee63c776' │ 'Binance' │ 'goose-finance' │ 'TYPH-BUSD' │ 14564.079569018413 │ 21.37155832602826  │ [ '0x4090e535F2e251F5F88518998B18b54d26B3b07c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────────────┴─────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by vrtnd** [comment]
Hi, please change apy to apyReward

**Comment by llamatester** [comment]
The goose-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       88 passed, 88 total
    Snapshots:   0 total
    Time:        0.432 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────────────┬─────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │     project     │   symbol    │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────────────┼─────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x1B96B92314C44b159149f7E0303511fB2Fc4774f' │ 'Binance' │ 'goose-finance' │ 'WBNB-BUSD' │ 245219.32515378052 │ 3.1293878254841396 │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    1    │ '0x19e7cbECDD23A16DfA5573dF54d98F7CaAE03019' │ 'Binance' │ 'goose-finance' │ 'BUSD-EGG'  │ 146771.88682537636 │ 62.74114646677681  │ [ '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56', '0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    2    │ '0x3aB77e40340AB084c3e23Be8e5A6f7afed9D41DC' │ 'Binance' │ 'goose-finance' │ 'DAI-BUSD'  │ 97072.72905732025  │ 6.324217960383459  │ [ '0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    3    │ '0xd1B59D11316E87C3a0A069E80F590BA35cD8D8D3' │ 'Binance' │ 'goose-finance' │ 'WBNB-EGG'  │ 95898.08858461966  │ 96.02523454250608  │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xF952Fc3ca7325Cc27D15885d37117676d25BfdA6' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    4    │ '0xc15fa3E22c912A276550F3E5FE3b0Deb87B55aCd' │ 'Binance' │ 'goose-finance' │ 'USDT-BUSD' │  92241.1370025404  │ 6.655480586181785  │ [ '0x55d398326f99059fF775485246999027B3197955', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    5    │ '0x7561EEe90e24F3b348E1087A005F78B4c8453524' │ 'Binance' │ 'goose-finance' │ 'BTCB-WBNB' │ 62130.03675610112  │ 14.82155319602615  │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    6    │ '0xbCD62661A6b1DEd703585d3aF7d7649Ef4dcDB5c' │ 'Binance' │ 'goose-finance' │ 'DOT-WBNB'  │ 28647.680155652688 │ 32.144440312382855 │ [ '0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    7    │ '0x680Dd100E4b394Bda26A59dD5c119A391e747d18' │ 'Binance' │ 'goose-finance' │ 'USDC-BUSD' │ 20147.481282476983 │ 30.470761479335962 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    8    │ '0x70D8929d04b60Af4fb9B58713eBcf18765aDE422' │ 'Binance' │ 'goose-finance' │ 'ETH-WBNB'  │ 20137.575833782874 │ 45.72862456000132  │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    │    9    │ '0x9fE5e1DbE102d4Dfa52176F5667E714aee63c776' │ 'Binance' │ 'goose-finance' │ 'TYPH-BUSD' │ 14266.52469208409  │ 21.51571983429065  │ [ '0x4090e535F2e251F5F88518998B18b54d26B3b07c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xf952fc3ca7325cc27d15885d37117676d25bfda6' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────────────┴─────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by dtmkeng** [comment]
done !

**Pull request merged**
