### PR TITLE
pendle

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running pendle adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       14 failed, 5 passed, 19 total
    Snapshots:   0 total
    Time:        0.388 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────┬──────────┬──────────┬──────────┐
    │ (index) │    0     │    1     │    2     │    3     │
    ├─────────┼──────────┼──────────┼──────────┼──────────┤
    │    0    │ [Object] │ [Object] │ [Object] │ [Object] │
    │    1    │ [Object] │ [Object] │ [Object] │ [Object] │
    │    2    │ [Object] │ [Object] │ [Object] │ [Object] │
    └─────────┴──────────┴──────────┴──────────┴──────────┘
    }

**Comment by llamatester** [comment]
Error while running pendle adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       10 failed, 4 passed, 14 total
    Snapshots:   0 total
    Time:        0.386 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────┬──────────┬──────────┬──────────┐
    │ (index) │    0     │    1     │    2     │    3     │
    ├─────────┼──────────┼──────────┼──────────┼──────────┤
    │    0    │ [Object] │ [Object] │ [Object] │ [Object] │
    │    1    │ [Object] │ [Object] │ [Object] │ [Object] │
    └─────────┴──────────┴──────────┴──────────┴──────────┘
    }

**Comment by llamatester** [comment]
Error while running pendle adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       10 failed, 4 passed, 14 total
    Snapshots:   0 total
    Time:        0.352 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────┬──────────┬──────────┬──────────┐
    │ (index) │    0     │    1     │    2     │    3     │
    ├─────────┼──────────┼──────────┼──────────┼──────────┤
    │    0    │ [Object] │ [Object] │ [Object] │ [Object] │
    │    1    │ [Object] │ [Object] │ [Object] │ [Object] │
    └─────────┴──────────┴──────────┴──────────┴──────────┘
    }

**Comment by slasher125** [comment]
henlo wayne :) from glancing at the code:
- i guess the tests fail cause u need to flatten the output from `Promise.all`
- pls remove the `main()` call

**Comment by llamatester** [comment]
Error while running pendle adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 55 passed, 56 total
    Snapshots:   0 total
    Time:        0.376 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬───────────────────────────────────────┬───────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │                symbol                 │      tvlUsd       │      apyBase       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │                        poolMeta                         │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼───────────────────────────────────────┼───────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────┤
    │    0    │ '0x9ec4c502d989f04ffa9312c9d6e3f872ec91a0f9' │ 'Ethereum' │ 'pendle' │                'STETH'                │ 812941.0937097423 │ 5.067264706493519  │ 34.11998418461974  │ [ '0x808507121b80c02388fad14726482e061b8da827' ] │ [ '0xb3b61d1587c05eadec579b616c45939f19435703', '0xcbc72d92b2dc8187414f6734718563898740c0bc' ] │           'stETH -> for liquidity provision'            │
    │    1    │ '0xb3b61d1587c05eadec579b616c45939f19435703' │ 'Ethereum' │ 'pendle' │         'PT-STETH-29JUN2023'          │ 812941.0937097423 │ 4.846466794299054  │                    │                                                  │                        [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0' ]                        │          'PT-stETH-29JUN2023 -> for buying PT'          │
    │    2    │ '0x7b246b8dbc2a640bf2d8221890cee8327fc23917' │ 'Ethereum' │ 'pendle' │              'FRAX-USDC'              │ 643788.2773657986 │ 3.0447086495302313 │ 34.074149006126724 │ [ '0x808507121b80c02388fad14726482e061b8da827' ] │ [ '0x5fe30ac5cb1abb0e44cdffb2916c254aeb368650', '0xd393d1ddd6b8811a86d925f5e14014282581bc04' ] │         'FRAX-USDC -> for liquidity provision'          │
    │    3    │ '0x5fe30ac5cb1abb0e44cdffb2916c254aeb368650' │ 'Ethereum' │ 'pendle' │ 'PT-FRAXUSDC-CURVELPCONVEX-30MAR2023' │ 643788.2773657986 │  2.95867897162021  │                    │                                                  │                        [ '0x3175df0976dfa876431c2e9ee6bc45b65d3473cc' ]                        │ 'PT-FRAXUSDC_CurveLP Convex-30MAR2023 -> for buying PT' │
    │    4    │ '0x54e28e62ea9e8d755dc6e74674eabe2abfdb004e' │ 'Ethereum' │ 'pendle' │                'STETH'                │ 638937.7537413174 │ 4.900277047944368  │ 59.17015909297726  │ [ '0x808507121b80c02388fad14726482e061b8da827' ] │ [ '0xcf44e8402a99db82d2acccc4d9354657be2121db', '0xcbc72d92b2dc8187414f6734718563898740c0bc' ] │           'stETH -> for liquidity provision'            │
    │    5    │ '0xcf44e8402a99db82d2acccc4d9354657be2121db' │ 'Ethereum' │ 'pendle' │         'PT-STETH-30MAR2023'          │ 638937.7537413174 │ 4.756996619623277  │                    │                                                  │                        [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0' ]                        │          'PT-stETH-30MAR2023 -> for buying PT'          │
    │    6    │ '0x44474d98d1484c26e8d296a43a721998731cf775' │ 'Ethereum' │ 'pendle' │                'LOOKS'                │ 133084.5045239602 │ 46.26262985597334  │ 50.21425751999058  │ [ '0x808507121b80c02388fad14726482e061b8da827' ] │ [ '0x293811f161fbfea8f417e222b226bb821548ba63', '0x35c16314d6ee4753289e5cc15a5c5e1dd4ead345' ] │           'LOOKS -> for liquidity provision'            │
    │    7    │ '0x293811f161fbfea8f417e222b226bb821548ba63' │ 'Ethereum' │ 'pendle' │      'PT-LOOKSSTAKING-30MAR2023'      │ 133084.5045239602 │ 42.65223120696624  │                    │                                                  │                        [ '0xf4d2888d29d722226fafa5d9b24f9164c092421e' ]                        │      'PT-LOOKS Staking-30MAR2023 -> for buying PT'      │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴───────────────────────────────────────┴───────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────┘
    }

**Pull request merged**
