### PR TITLE
Add sideshift adaptor

### PR DESCRIPTION
**Pull request by abrkn**
Adds an adaptor for SideShift.ai's svXAI pool:

```
$ node src/adaptors/test.js src/adaptors/sideshift/index.js
==== Testing src/adaptors/sideshift/index.js ====

Nb of pools: 1
 

Sample pools: [
  {
    pool: '0x3808708e761b988d23ae011ed0e12674fb66bd62',
    chain: 'Ethereum',
    project: 'sideshift',
    symbol: 'svXAI',
    tvlUsd: 4501533.25044498,
    apy: 27.38
  }
]

Runtime: 0.68 sec
```

### CODE REVIEW

**Comment by glebskr** [comment]
U need to add adapter for your project here as well (https://github.com/DefiLlama/DefiLlama-Adapters)

**Comment by abrkn** [comment]
> U need to add adapter for your project here as well ([DefiLlama/DefiLlama-Adapters](https://github.com/DefiLlama/DefiLlama-Adapters))

Done, @glebskr. See https://github.com/DefiLlama/DefiLlama-Adapters/pull/3216

**Comment by glebskr** [comment]
Thank you.
Another small edit, please add apyBase and underlyingToken, and maybe apyReward+rewardToken (if the reward is given in another token, if not, you can not add these fields)
The new fields are also described in the readme https://github.com/DefiLlama/yield-server#adaptors

**Comment by 0xHarbs** [comment]
Hey @glebskr
Our vault's APY is variable so we're not sure how we would use apyBase?

**Pull request merged**
