### PR TITLE
Added asymetrix-protocol adaptor

### PR DESCRIPTION
**Pull request by smak0v**

### CODE REVIEW

**Comment by llamatester** [comment]
The asymetrix-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────────────┬────────┬───────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────┐
    │ (index) │                     pool                     │   chain    │       project        │ symbol │      tvlUsd       │      apyBase      │                   rewardTokens                   │                 underlyingTokens                 │             url             │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────────────┼────────┼───────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────┤
    │    0    │ '0x82D24dD5041A3Eb942ccA68B319F1fDa9EB0c604' │ 'Ethereum' │ 'asymetrix-protocol' │ 'ASX'  │ 978157.9428187247 │ 388.0673502459697 │ [ '0x67d85A291fcDC862A78812a3C26d55e28FFB2701' ] │ [ '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84' ] │ 'https://app.asymetrix.io/' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────────────┴────────┴───────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────┘

**Comment by slasher125** [comment]
hi, ty for adding:
- use apyReward instead of apyBase
- do users still receive the full stETH yield? if so, then you can add the stETH yield as apyBase

**Comment by smak0v** [comment]
> 

Hi!

1) Ok, I will update it.
2) Yes, users receive all stETH rewards in most cases. But in some cases admin can set up fee that will be charged from the generated yield once per week. All stETH yield is distributed randomly between N users (it depends on distribution array length) using their TWABs (time weighted average balances). And we can't guarantee that every user will receive stable APY because not everyone can receive yielded stETH.

**Comment by llamatester** [comment]
The asymetrix-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.454 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────────────┬────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────┐
    │ (index) │                     pool                     │   chain    │       project        │ symbol │      tvlUsd       │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │             url             │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────────────┼────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────┤
    │    0    │ '0x82D24dD5041A3Eb942ccA68B319F1fDa9EB0c604' │ 'Ethereum' │ 'asymetrix-protocol' │ 'ASX'  │ 975327.4469470977 │ 1.0724854749921326 │ [ '0x67d85A291fcDC862A78812a3C26d55e28FFB2701' ] │ [ '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84' ] │ 'https://app.asymetrix.io/' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────────────┴────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────┘

**Comment by slasher125** [comment]
ok, any reason why the rewrad APY is now just 1%?
also, we actually no longer accept direct api calls. pls refactor to on chain/subgraph calls instead. ty

**Comment by smak0v** [comment]
> 

APY is equal to 1% because in docs you said: "Fee based APY values should be calculated over a 24h window". Now we are calculating an APY for 24 hours window (1 day).

**Comment by smak0v** [comment]
Do you support API call to the https://api.llama.fi/tvl/protocol/ to calculate TVL?

**Comment by slasher125** [comment]
> APY is equal to 1% because in docs you said: "Fee based APY values should be calculated over a 24h window". Now we are calculating an APY for 24 hours window (1 day).
to confirm, the window means to take the 24h fees/rewards * 365 / tvl. We do not show 1day apy values, but a proper yearly values based on a 1day lookback. makes sense?

>Do you support API call to the https://api.llama.fi/tvl/protocol/ to calculate TVL?
if its one pool, then well is ok. the more important part here is the apy component, can u refactor to on chain?

**Comment by smak0v** [comment]
Yes, I can refactor it using on chain calls.

**Comment by llamatester** [comment]
The asymetrix-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.377 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────────────┬────────┬────────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────┐
    │ (index) │                     pool                     │   chain    │       project        │ symbol │       tvlUsd       │     apyReward     │                   rewardTokens                   │                 underlyingTokens                 │             url             │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────────────┼────────┼────────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────┤
    │    0    │ '0x82D24dD5041A3Eb942ccA68B319F1fDa9EB0c604' │ 'Ethereum' │ 'asymetrix-protocol' │ 'ASX'  │ 1139908.4091738209 │ 334.7007401991875 │ [ '0x67d85A291fcDC862A78812a3C26d55e28FFB2701' ] │ [ '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84' ] │ 'https://app.asymetrix.io/' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────────────┴────────┴────────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────┘

**Comment by smak0v** [comment]
@slasher125 Update APY calculation using on-chain calls.

APY is equal to 334%, it is a proper value, not just 1%.

**Comment by smak0v** [comment]
@slasher125 Fixed

Deposit token is stETH, right. I thought that protocol token should be shown)

**Comment by llamatester** [comment]
The asymetrix-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.333 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────────────┬─────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────┐
    │ (index) │                     pool                     │   chain    │       project        │ symbol  │       tvlUsd       │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │             url             │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────────────┼─────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────┤
    │    0    │ '0x82D24dD5041A3Eb942ccA68B319F1fDa9EB0c604' │ 'Ethereum' │ 'asymetrix-protocol' │ 'STETH' │ 1137871.7904091077 │ 335.18184218889814 │ [ '0x67d85A291fcDC862A78812a3C26d55e28FFB2701' ] │ [ '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84' ] │ 'https://app.asymetrix.io/' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────────────┴─────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────┘

**Comment by slasher125** [comment]
final q: are there any lockup periods on deposit token and/or asx rewards?

**Comment by smak0v** [comment]
no, we don't have lockups

**Pull request merged**
