### PR TITLE
Added APY Yield  for BakerFi

### PR DESCRIPTION
**Pull request by chefkenji**

### CODE REVIEW

**Comment by chefkenji** [comment]
Running bakerfi Test
    ✓ Check if link to the pool's page exist
    ✓ Check for unique pool ids (1 ms)
    ✓ Check project field is constant in all pools and if folder name and project field in pool objects matches the information in /protocols slug
    Check for allowed field names
      ✓ Expects pool id 0x37327c99bbc522e677a97d01021db20227faf60a-base to contain only allowed keys: pool,chain,project,symbol,apy,apyBase,apyReward,underlyingTokens,rewardTokens,poolMeta,url,apyBaseBorrow,apyRewardBorrow,totalSupplyUsd,totalBorrowUsd,ltv,borrowable,borrowFactor,debtCeilingUsd,mintedCoin,apyBase7d,apyRewardFake,apyRewardBorrowFake,il7d,volumeUsd1d,volumeUsd7d,apyBaseInception,tvlUsd and has: pool,chain,project,symbol,apyReward,rewardTokens,underlyingTokens,poolMeta,tvlUsd,apyBase (1 ms)
    Check apy data types
      ✓ Expects pool with id 0x37327c99bbc522e677a97d01021db20227faf60a-base to have at least one number apy field
    Check tvl data type
      ✓ tvlUsd field of pool with id 0x37327c99bbc522e677a97d01021db20227faf60a-base should be number
    Check tokens data types
      ✓ rewardTokens field of pool with id 0x37327c99bbc522e677a97d01021db20227faf60a-base should be an Array of strings (1 ms)
      ✓ underlyingTokens field of pool with id 0x37327c99bbc522e677a97d01021db20227faf60a-base should be an Array of strings
    Check other fields data types
      ✓ Expect other fields of pool with id 0x37327c99bbc522e677a97d01021db20227faf60a-base to match thier data types
    Check if pool has a rewardApy then rewardTokens must also exist
      ✓ The pool 0x37327c99bbc522e677a97d01021db20227faf60a-base is expected to have a rewardTokens field
    Check if pool id already used by other project
      ✓ Expect duplicate ids array to be empty

Test Suites: 1 passed, 1 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        0.179 s, estimated 1 s
Ran all test suites.

Nb of pools: 1


Sample pools: [
  {
    pool: '0x37327c99bbc522e677a97d01021db20227faf60a-base',
    chain: 'base',
    project: 'bakerfi',
    symbol: 'ETH',
    apyReward: 0,
    rewardTokens: [ '0x4200000000000000000000000000000000000006' ],
    underlyingTokens: [ '0x4200000000000000000000000000000000000006' ],
    poolMeta: 'wstETH/ETH Recursive Staking',
    tvlUsd: 46079,
    apyBase: '5.6858437455555556'
  }
]

**Comment by slasher125** [comment]
the api is not working

**Comment by chefkenji** [comment]
The API is working , you can try yourself 
https://api-v1.bakerfi.xyz/api/vaults/cly4i95530008kl5eesquxqyc/yield

When i run the adapter everything is fine.

```
npm run test --adapter=bakerfi
```

**Comment by chefkenji** [comment]
The API is working , you can try yourself
https://api-v1.bakerfi.xyz/api/vaults/cly4i95530008kl5eesquxqyc/yield

When i run the adapter everything is fine.

npm run test --adapter=bakerfi

**Comment by chefkenji** [comment]
> the api is not working

The API is working , you can try yourself
https://api-v1.bakerfi.xyz/api/vaults/cly4i95530008kl5eesquxqyc/yield

When i run the adapter everything is fine.

npm run test --adapter=bakerfi

**Pull request merged**
