### PR TITLE
Integrating strkfarm to defillama yield server

### PR DESCRIPTION
**Pull request by 0x-minato**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running STRKFarm adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        0.281 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┬───────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │      apyBase       │                       url                       │   poolMeta    │  Values   │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┼───────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'STRKFarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66694.61621374378 │ 15.654694902330135 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │           │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'STRKFarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.44247812391 │ 22.35890434111072  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │           │
    │    2    │               │            │            │        │                                                                          │                   │                    │                                                 │               │ undefined │
    │    3    │               │            │            │        │                                                                          │                   │                    │                                                 │               │ undefined │
    │    4    │               │            │            │        │                                                                          │                   │                    │                                                 │               │ undefined │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┴───────────┘
    TypeError: Jest: Got error running globalTeardown - /home/runner/work/yield-server/yield-server/src/adaptors/afterTests.js, reason: Cannot read properties of undefined (reading 'tvlUsd')
        at /home/runner/work/yield-server/yield-server/src/adaptors/afterTests.js:9:30
        at Array.some (<anonymous>)
        at module.exports (/home/runner/work/yield-server/yield-server/src/adaptors/afterTests.js:9:18)
        at /home/runner/work/yield-server/yield-server/node_modules/@jest/core/build/runGlobalHook.js:125:19
        at ScriptTransformer.requireAndTranspileModule (/home/runner/work/yield-server/yield-server/node_modules/@jest/transform/build/ScriptTransformer.js:905:24)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at runGlobalHook (/home/runner/work/yield-server/yield-server/node_modules/@jest/core/build/runGlobalHook.js:116:9)
        at runJest (/home/runner/work/yield-server/yield-server/node_modules/@jest/core/build/runJest.js:411:5)
        at _run10000 (/home/runner/work/yield-server/yield-server/node_modules/@jest/core/build/cli/index.js:339:7)
        at runCLI (/home/runner/work/yield-server/yield-server/node_modules/@jest/core/build/cli/index.js:190:3)
        at Object.run (/home/runner/work/yield-server/yield-server/node_modules/jest-cli/build/cli/index.js:155:37)
    }

**Comment by llamatester** [comment]
Error while running STRKFarm adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 33 passed, 34 total
    Snapshots:   0 total
    Time:        0.295 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────────────────────────────────────┬─────────────────────────┐
    │ (index) │       pool        │   chain    │  project   │ symbol │                             underlyingTokens                             │       tvlUsd       │      apyBase       │                         url                         │        poolMeta         │
    ├─────────┼───────────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────────────────────────────────────┼─────────────────────────┤
    │    0    │   'strk_sensei'   │ 'Starknet' │ 'STRKFarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66694.61621374378  │ 15.654694902330135 │   'https://app.strkfarm.xyz/strategy/strk_sensei'   │      'STRK Sensei'      │
    │    1    │   'usdc_sensei'   │ 'Starknet' │ 'STRKFarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.44247812391  │ 22.35890434111072  │   'https://app.strkfarm.xyz/strategy/usdc_sensei'   │      'USDC Sensei'      │
    │    2    │ 'auto_token_strk' │ 'Starknet' │ 'STRKFarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 8688.082660755781  │ 9.593038705910084  │ 'https://app.strkfarm.xyz/strategy/auto_token_strk' │ 'Auto Compounding STRK' │
    │    3    │   'eth_sensei'    │ 'Starknet' │ 'STRKFarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │  6098.81098575054  │ 24.86737177219387  │   'https://app.strkfarm.xyz/strategy/eth_sensei'    │      'ETH Sensei'       │
    │    4    │ 'auto_token_usdc' │ 'Starknet' │ 'STRKFarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 2671.7283534176713 │ 9.593038705910084  │ 'https://app.strkfarm.xyz/strategy/auto_token_usdc' │ 'Auto Compounding USDC' │
    └─────────┴───────────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────────────────────────────────────┴─────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
Error while running STRKFarm adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 15 passed, 16 total
    Snapshots:   0 total
    Time:        0.309 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │      apyBase       │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'STRKFarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66779.15128206904 │ 15.654694902330135 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'STRKFarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.6167078354  │ 22.35890434111072  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘
    }

**Comment by llamatester** [comment]
Error while running STRKFarm adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 15 passed, 16 total
    Snapshots:   0 total
    Time:        0.284 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │      apyBase       │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66779.15128206904 │ 15.654694902330135 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.6167078354  │ 22.35890434111072  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘
    }

**Comment by llamatester** [comment]
Error while running STRKFarm adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 21 passed, 22 total
    Snapshots:   0 total
    Time:        0.301 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │       tvlUsd       │      apyBase       │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66519.12418947007  │ 15.654694902330135 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.912239611986 │ 22.35890434111072  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 12990.13755963751  │ 24.86737177219387  │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘
    }

**Comment by llamatester** [comment]
The strkfarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.26 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │       tvlUsd       │      apyBase       │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 66519.12418947007  │ 15.654694902330135 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 59142.912239611986 │ 22.35890434111072  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 12990.13755963751  │ 24.86737177219387  │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘

**Comment by slasher125** [comment]
gm, checked ur ui, seems like the apy comes from both fees and rewards so you should use the `apy` field instead of `apyBase`. also, pls revert the package changes

**Comment by llamatester** [comment]
The strkfarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.266 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │        apy         │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 69188.38748837443 │ 22.57106347437712  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    1    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 68158.65169724451 │ 15.62492033538485  │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 23872.13827718802 │ 25.029280352081074 │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘

**Comment by llamatester** [comment]
The strkfarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.271 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │        apy         │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 69188.38748837443 │ 22.57106347437712  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    1    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 68158.65169724451 │ 15.62492033538485  │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 23872.13827718802 │ 25.029280352081074 │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘

**Comment by slasher125** [comment]
same for package-lock sir

**Comment by llamatester** [comment]
The strkfarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.261 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │        apy         │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 69188.38748837443 │ 22.57106347437712  │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    1    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 68158.65169724451 │ 15.62492033538485  │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 23872.13827718802 │ 25.029280352081074 │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘

**Comment by llamatester** [comment]
The strkfarm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       22 passed, 22 total
    Snapshots:   0 total
    Time:        0.263 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────┬────────────┬────────────┬────────┬──────────────────────────────────────────────────────────────────────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────┬───────────────┐
    │ (index) │     pool      │   chain    │  project   │ symbol │                             underlyingTokens                             │      tvlUsd       │        apy         │                       url                       │   poolMeta    │
    ├─────────┼───────────────┼────────────┼────────────┼────────┼──────────────────────────────────────────────────────────────────────────┼───────────────────┼────────────────────┼─────────────────────────────────────────────────┼───────────────┤
    │    0    │ 'strk_sensei' │ 'Starknet' │ 'strkfarm' │ 'STRK' │ [ '0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d' ]  │ 69785.52404906916 │ 15.631292178190947 │ 'https://app.strkfarm.xyz/strategy/strk_sensei' │ 'STRK Sensei' │
    │    1    │ 'usdc_sensei' │ 'Starknet' │ 'strkfarm' │ 'USDC' │ [ '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8' ] │ 69573.27082821014 │ 22.907179285066693 │ 'https://app.strkfarm.xyz/strategy/usdc_sensei' │ 'USDC Sensei' │
    │    2    │ 'eth_sensei'  │ 'Starknet' │ 'strkfarm' │ 'ETH'  │ [ '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7' ] │ 26396.8882325311  │ 25.351891596661467 │ 'https://app.strkfarm.xyz/strategy/eth_sensei'  │ 'ETH Sensei'  │
    └─────────┴───────────────┴────────────┴────────────┴────────┴──────────────────────────────────────────────────────────────────────────┴───────────────────┴────────────────────┴─────────────────────────────────────────────────┴───────────────┘

**Comment by 0x-minato** [comment]
> same for package-lock sir

should be fixed now ser, thanks

**Pull request merged**
