### PR TITLE
fix error

### PR DESCRIPTION
**Pull request by huangwenchao2000**

### CODE REVIEW

**Comment by llamatester** [comment]
The deri-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.427 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────────────────┬────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │       tvlUsd       │ symbol │        apy         │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────────────────┼────────┼────────────────────┤
    │    0    │ '0xde3447eb47ecdf9b5f90e7a6960a14663916cee8-arbitrum' │ 'Arbitrum' │ 'deri-protocol' │ 842748.1646645878  │ 'ETH'  │ 11.01682996201925  │
    │    1    │ '0x243681b8cd79e3823ff574e07b2378b8ab292c1e-binance'  │ 'Binance'  │ 'deri-protocol' │ 149161.20329048525 │ 'BNB'  │ 22.770990509778226 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────────────────┴────────┴────────────────────┘

**Comment by slasher125** [comment]
ty for adding. a few tings:
- use `apyBase` and `apyReward` instead of `apy`
- remove the yarn file
- instead of calling via api, fetch tvl data via on chain calls or subgraph

**Comment by huangwenchao2000** [comment]
Does tvl have to call the data on the chain? I see your example, it can be called by api

**Comment by llamatester** [comment]
The deri-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.309 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────────────────┬────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │       tvlUsd       │ symbol │      apyBase       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────────────────┼────────┼────────────────────┤
    │    0    │ '0xde3447eb47ecdf9b5f90e7a6960a14663916cee8-arbitrum' │ 'Arbitrum' │ 'deri-protocol' │ 1385444.4639087426 │ 'USDC' │ 25.616887411598523 │
    │    1    │   '0x243681b8cd79e3823ff574e07b2378b8ab292c1e-bsc'    │ 'Binance'  │ 'deri-protocol' │ 420941.15190115495 │ 'BUSD' │ 22.24365434808986  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────────────────┴────────┴────────────────────┘

**Comment by slasher125** [comment]
yeah the example is very old when we started out...
re apy: we can't just add up base + reward and set it to apyBase...apyBase = fees, apyReward = from deri incentives.
when I deposit into the usdc pool on arbitrum, am i also exposed to non stable pools?

**Comment by huangwenchao2000** [comment]
Sorry, I made a mistake with the name, and revised the title. 
What do you mean by 'exposed to non-stable pool'?  I want to clarify that we only have one Main pool on Arbitrum and its settlement token is USDC.

**Comment by llamatester** [comment]
Error while running deri-protocol adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       2 failed, 12 passed, 14 total
    Snapshots:   0 total
    Time:        0.352 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────────────────┬────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │       tvlUsd       │ symbol │     apyReward      │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────────────────┼────────┼────────────────────┤
    │    0    │ '0xde3447eb47ecdf9b5f90e7a6960a14663916cee8-arbitrum' │ 'Arbitrum' │ 'deri-protocol' │ 1385444.4639087426 │ 'USDC' │ 25.616887411598523 │
    │    1    │   '0x243681b8cd79e3823ff574e07b2378b8ab292c1e-bsc'    │ 'Binance'  │ 'deri-protocol' │ 420941.15190115495 │ 'BUSD' │ 22.24365434808986  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────────────────┴────────┴────────────────────┘
    }

**Comment by slasher125** [comment]
deri

but then what are these different pools?

**Comment by llamatester** [comment]
The deri-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.316 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────────────────┬────────┬────────────────────┬──────────────┐
    │ (index) │                         pool                          │   chain    │     project     │       tvlUsd       │ symbol │     apyReward      │ rewardTokens │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────────────────┼────────┼────────────────────┼──────────────┤
    │    0    │ '0xde3447eb47ecdf9b5f90e7a6960a14663916cee8-arbitrum' │ 'Arbitrum' │ 'deri-protocol' │ 1385444.4639087426 │ 'USDC' │ 25.616887411598523 │  [ 'Deri' ]  │
    │    1    │   '0x243681b8cd79e3823ff574e07b2378b8ab292c1e-bsc'    │ 'Binance'  │ 'deri-protocol' │ 420941.15190115495 │ 'BUSD' │ 22.24365434808986  │  [ 'Deri' ]  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────────────────┴────────┴────────────────────┴──────────────┘

**Comment by huangwenchao2000** [comment]
These are not separate pools but rather one pool, where liquidity providers can add liquidity by selecting either USDC or ETH. The incentive rate varies depending on the base token chosen.

USDC serves as the settlement token. For instance, if A deposits 1000 USDC into the pool, their APY will be 25.01% + 0.6%. On the other hand, if B deposits 1 ETH (valued at 1500 USDC at the time of deposit), their APY will be 10.52% + 0.07%.

The total value locked (TVL) in the pool is 2500, considering A's deposit of 1000 USDC and B's deposit of 1 ETH. If the price of ETH rises to 2000 USDC, the TVL in the pool will increase to 3000 USDC.

**Comment by slasher125** [comment]
- if this is one pool of different assets, on depositing usdc, can i be at risk to any of the other assets?
(asking cause i need to set single/multi exposure server side)

**Comment by huangwenchao2000** [comment]
nope, you do not at risk to any of the other assets.

**Comment by huangwenchao2000** [comment]
nope, you do not at risk to any of the other assets.

**Comment by llamatester** [comment]
The deri-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.408 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────────────────┬────────┬────────────────────┬──────────────┐
    │ (index) │                         pool                          │   chain    │     project     │       tvlUsd       │ symbol │     apyReward      │ rewardTokens │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────────────────┼────────┼────────────────────┼──────────────┤
    │    0    │ '0xde3447eb47ecdf9b5f90e7a6960a14663916cee8-arbitrum' │ 'Arbitrum' │ 'deri-protocol' │ 1385469.4639087424 │ 'USDC' │ 22.55119169790038  │  [ 'Deri' ]  │
    │    1    │   '0x243681b8cd79e3823ff574e07b2378b8ab292c1e-bsc'    │ 'Binance'  │ 'deri-protocol' │ 420941.15190115495 │ 'BUSD' │ 20.583014312569436 │  [ 'Deri' ]  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────────────────┴────────┴────────────────────┴──────────────┘

**Pull request merged**
