### PR TITLE
add velocimeter on base chain

### PR DESCRIPTION
**Pull request by oxSaturn**
`bvm` price is not available on coins api yet https://[coins.llama.fi/prices/current/base:0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a](https://coins.llama.fi/prices/current/base:0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a), thus the apr will show 0 at the moment.

### CODE REVIEW

**Comment by llamatester** [comment]
The velocimeter-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.361 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────────┬───────────────────┬────────────────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │     project      │      symbol       │       tvlUsd       │ apyReward │ rewardTokens │                                        underlyingTokens                                        │                                         url                                         │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────────┼───────────────────┼────────────────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │ 'Base' │ 'velocimeter-v2' │   'WETH-USDBC'    │ 191611.0476947418  │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │
    │    1    │ '0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │ 'Base' │ 'velocimeter-v2' │  'WETH-AXLUSDC'   │ 175639.19631916384 │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │
    │    2    │ '0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │ 'Base' │ 'velocimeter-v2' │   'CBETH-WETH'    │ 29333.622373363432 │     0     │      []      │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │
    │    3    │ '0x59d286411E41BB0c754dC01d692C4A54Db314832' │ 'Base' │ 'velocimeter-v2' │ 'AXLUSDT-AXLUSDC' │ 25783.009383426546 │     0     │      []      │ [ '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x59d286411E41BB0c754dC01d692C4A54Db314832' │
    │    4    │ '0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │ 'Base' │ 'velocimeter-v2' │    'DAI-USDBC'    │ 15681.644549359724 │     0     │      []      │ [ '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │
    │    5    │ '0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │ 'Base' │ 'velocimeter-v2' │  'USDBC-AXLUSDC'  │   4278.097068608   │     0     │      []      │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │
    │    6    │ '0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │ 'Base' │ 'velocimeter-v2' │    'BALD-WETH'    │ 3636.4338938475007 │     0     │      []      │ [ '0x27D2DECb4bFC9C76F0309b8E88dec3a601Fe25a8', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │
    │    7    │ '0x996D7243cF87e7e5F50EC97884605FF02beFE366' │ 'Base' │ 'velocimeter-v2' │   'ERN-AXLUSDC'   │ 2303.209937503976  │     0     │      []      │ [ '0xa334884bF6b0A066d553D19e507315E839409e62', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x996D7243cF87e7e5F50EC97884605FF02beFE366' │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────────┴───────────────────┴────────────────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The velocimeter-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       74 passed, 74 total
    Snapshots:   0 total
    Time:        0.448 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────────┬───────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │     project      │      symbol       │       tvlUsd       │     apyReward      │                                                                         rewardTokens                                                                          │                                        underlyingTokens                                        │                                         url                                         │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────────┼───────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │ 'Base' │ 'velocimeter-v2' │   'WETH-USDBC'    │ 185300.9063585702  │ 24.621795145865324 │         [ '0x4200000000000000000000000000000000000006', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x4200000000000000000000000000000000000006', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │
    │    1    │ '0x53713F956A4DA3F08B55A390B20657eDF9E0897B' │ 'Base' │ 'velocimeter-v2' │    'WETH-BVM'     │ 165621.0145502704  │ 859.3733696234577  │                                [ '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]                                 │ [ '0x4200000000000000000000000000000000000006', '0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a' ] │ 'https://base.velocimeter.xyz/liquidity/0x53713F956A4DA3F08B55A390B20657eDF9E0897B' │
    │    2    │ '0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │ 'Base' │ 'velocimeter-v2' │  'WETH-AXLUSDC'   │ 73306.87828075589  │ 59.70342828354783  │         [ '0x4200000000000000000000000000000000000006', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x4200000000000000000000000000000000000006', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │
    │    3    │ '0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │ 'Base' │ 'velocimeter-v2' │   'CBETH-WETH'    │  35090.4171492625  │ 22.275182909477426 │         [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22', '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │
    │    4    │ '0x59d286411E41BB0c754dC01d692C4A54Db314832' │ 'Base' │ 'velocimeter-v2' │ 'AXLUSDT-AXLUSDC' │ 30532.890316734527 │ 30.132275150128685 │         [ '0x7f5373ae26c3e8ffc4c77b7255df7ec1a9af52a6', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x59d286411E41BB0c754dC01d692C4A54Db314832' │
    │    5    │ '0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │ 'Base' │ 'velocimeter-v2' │    'DAI-USDBC'    │ 25596.231960331446 │ 19.825020725495897 │         [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │
    │    6    │ '0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │ 'Base' │ 'velocimeter-v2' │    'BALD-WETH'    │ 4731.5830951808275 │ 479.94171784386754 │ [ '0x27d2decb4bfc9c76f0309b8e88dec3a601fe25a8', '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e', ... 1 more item ] │ [ '0x27D2DECb4bFC9C76F0309b8E88dec3a601Fe25a8', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │
    │    7    │ '0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │ 'Base' │ 'velocimeter-v2' │  'USDBC-AXLUSDC'  │ 4268.993964342584  │ 34.53337145297844  │         [ '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │
    │    8    │ '0x996D7243cF87e7e5F50EC97884605FF02beFE366' │ 'Base' │ 'velocimeter-v2' │   'ERN-AXLUSDC'   │ 534.9852112095195  │ 2.1019275105543183 │         [ '0xa334884bf6b0a066d553d19e507315e839409e62', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0xa334884bF6b0A066d553D19e507315E839409e62', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x996D7243cF87e7e5F50EC97884605FF02beFE366' │
    │    9    │ '0xb0ac7feA3bfBF7EB3C196B9a702f836aE0969BDf' │ 'Base' │ 'velocimeter-v2' │    'BVM-USDBC'    │ 10.526919066563787 │ 34.36212501689852  │                                [ '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca' ]                                 │ [ '0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0xb0ac7feA3bfBF7EB3C196B9a702f836aE0969BDf' │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────────┴───────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by oxSaturn** [comment]
@slasher125 Ser, the price is available, so this PR is ready to review.

**Comment by llamatester** [comment]
The velocimeter-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.343 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────┬──────────────────┬───────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │ chain  │     project      │      symbol       │       tvlUsd       │     apyReward      │                                                                         rewardTokens                                                                          │                                        underlyingTokens                                        │                                         url                                         │
    ├─────────┼──────────────────────────────────────────────┼────────┼──────────────────┼───────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │ 'Base' │ 'velocimeter-v2' │   'WETH-USDBC'    │ 185252.0713939509  │ 24.979089885420215 │         [ '0x4200000000000000000000000000000000000006', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x4200000000000000000000000000000000000006', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x6546ecac3F80E041006eDc3Da891adcE567B40B8' │
    │    1    │ '0x53713F956A4DA3F08B55A390B20657eDF9E0897B' │ 'Base' │ 'velocimeter-v2' │    'WETH-BVM'     │ 169603.20362554962 │ 840.1977383353877  │                                [ '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]                                 │ [ '0x4200000000000000000000000000000000000006', '0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a' ] │ 'https://base.velocimeter.xyz/liquidity/0x53713F956A4DA3F08B55A390B20657eDF9E0897B' │
    │    2    │ '0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │ 'Base' │ 'velocimeter-v2' │  'WETH-AXLUSDC'   │ 126633.8101912843  │ 35.05393263356663  │         [ '0x4200000000000000000000000000000000000006', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x4200000000000000000000000000000000000006', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x1c2f16EB9E2C18a87037194c5EA00F569953A1cc' │
    │    3    │ '0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │ 'Base' │ 'velocimeter-v2' │   'CBETH-WETH'    │ 35028.382733794955 │ 22.632480241741003 │         [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22', '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0x291CDd70257c17bC719D11531ec01C33C34A4d8b' │
    │    4    │ '0x59d286411E41BB0c754dC01d692C4A54Db314832' │ 'Base' │ 'velocimeter-v2' │ 'AXLUSDT-AXLUSDC' │ 30528.839807940552 │ 30.565532644506632 │         [ '0x7f5373ae26c3e8ffc4c77b7255df7ec1a9af52a6', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x7f5373AE26c3E8FfC4c77b7255DF7eC1A9aF52a6', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x59d286411E41BB0c754dC01d692C4A54Db314832' │
    │    5    │ '0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │ 'Base' │ 'velocimeter-v2' │    'DAI-USDBC'    │  25620.2450014832  │ 20.08856131855021  │         [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb', '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb', '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ 'https://base.velocimeter.xyz/liquidity/0x110D58483e45B78A040Fe052943a2Ff4885d8Cf5' │
    │    6    │ '0x9409d3513507217DE7135679D658e5BEec201c18' │ 'Base' │ 'velocimeter-v2' │   'WETH-BASED'    │ 4308.3285529597615 │ 480.3785122278124  │         [ '0x4200000000000000000000000000000000000006', '0xba5e6fa2f33f3955f0cef50c63dcc84861eab663', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0x4200000000000000000000000000000000000006', '0xBa5E6fa2f33f3955f0cef50c63dCC84861eAb663' ] │ 'https://base.velocimeter.xyz/liquidity/0x9409d3513507217DE7135679D658e5BEec201c18' │
    │    7    │ '0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │ 'Base' │ 'velocimeter-v2' │    'BALD-WETH'    │ 4307.340825302572  │  534.722134766999  │ [ '0x27d2decb4bfc9c76f0309b8e88dec3a601fe25a8', '0x4200000000000000000000000000000000000006', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e', ... 1 more item ] │ [ '0x27D2DECb4bFC9C76F0309b8E88dec3a601Fe25a8', '0x4200000000000000000000000000000000000006' ] │ 'https://base.velocimeter.xyz/liquidity/0xdD7bdaAC886507B7EB3af97932CE424342fe97a2' │
    │    8    │ '0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │ 'Base' │ 'velocimeter-v2' │  'USDBC-AXLUSDC'  │ 4273.197215098568  │  34.990811162031   │         [ '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0xC3b9505056432389e7b9D6e7Cf14Ce48371e6b47' │
    │    9    │ '0x996D7243cF87e7e5F50EC97884605FF02beFE366' │ 'Base' │ 'velocimeter-v2' │   'ERN-AXLUSDC'   │ 535.2580998048867  │ 2.1307803815774604 │         [ '0xa334884bf6b0a066d553d19e507315e839409e62', '0xeb466342c4d449bc9f53a865d5cb90586f405215', '0x762eb51d2e779eeec9b239ffb0b2ec8262848f3e' ]          │ [ '0xa334884bF6b0A066d553D19e507315E839409e62', '0xEB466342C4d449BC9f53A865D5Cb90586f405215' ] │ 'https://base.velocimeter.xyz/liquidity/0x996D7243cF87e7e5F50EC97884605FF02beFE366' │
    └─────────┴──────────────────────────────────────────────┴────────┴──────────────────┴───────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by oxSaturn** [comment]
The deploy action failed https://github.com/DefiLlama/yield-server/actions/runs/5864074752, does it matter?

**Pull request merged**
