### PR TITLE
STRX Finance Yield

### PR DESCRIPTION
**Pull request by strxfinance**

### CODE REVIEW

**Comment by slasher125** [comment]
hi, we no longer accept centralised api's (see readme, data sources section). please make use of subgraph and/or on chain calls instead

**Comment by llamatester** [comment]
The strx-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.329 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────┬────────┬────────────────┬────────┬───────────────────┬───────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                 pool                 │ chain  │    project     │ symbol │      tvlUsd       │        apy        │                                                   poolMeta                                                    │
    ├─────────┼──────────────────────────────────────┼────────┼────────────────┼────────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ 'TGrdCu9fu8csFmQptVE25fDzFmPU9epamH' │ 'Tron' │ 'strx-finance' │ 'TRX'  │ 11357.41819330803 │ 32.79362465836489 │ 'Staking Pool produces APY by lending Tron resources (energy/bandwidth) and taking part in block production.' │
    └─────────┴──────────────────────────────────────┴────────┴────────────────┴────────┴───────────────────┴───────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
2 things:
- I'd remove the poolMeta in this case. we usually use it if there are multiple pools of the same asset but you want to distinguish btw them. not necessary in this case
- pls use `apyBase` instead of `apy` field

**Comment by strxfinance** [comment]
Ok

**Comment by strxfinance** [comment]
I'm hoping now that everything is clear, this commit can be merged.

How frequently does the api server get calls or requests from the defillama yield-server in case of a centralised server?

**Pull request merged**
