### PR TITLE
add Hedge yield adapter

### PR DESCRIPTION
**Pull request by Haoqian-Zheng**
Hedge listing: https://defillama.com/protocol/hedge

### CODE REVIEW

**Comment by slasher125** [comment]
gm, ty for the contribution! was just checking out the hedge UI, can you please point me to where i can find this pool on the frontend?
```
  {
    pool: 'CeMzAfeA6oBfzN2RcZoSDNT8Xmr6dJSZzurDDkQZG1Q1',
    chain: 'Solana',
    project: 'hedge',
    symbol: 'USDC (cUSDC Vault)',
    tvlUsd: 3580124.449442,
    apyBase: 65.84905842508807,
    apyReward: 0,
    rewardTokens: [],
    underlyingTokens: [ 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' ]
  }
```

ty

**Comment by Haoqian-Zheng** [comment]
gm! 

this is our cUSDC vault from https://www.hedge.so/borrow which leverages your USDC yield from Solend by 21x. The UI isn't optimized to make it easier for the user to understand yet, but we are working on it.

**Comment by slasher125** [comment]
I see, thanks for explaining. On our yields dashboard we currently do not display any borrow-related pools. so in that sense i'd prefer removing the cUSDC vault until we rollout general support for borrow pools.

While browsing your UI, i also found these, would u mind including them into the adapter?

Screenshot 2022-07-23 at 12 16 21

**Comment by slasher125** [comment]
Also, please remove the package-lock.json from the PR.

**Comment by Haoqian-Zheng** [comment]
cleaned up the commit history.

I removed the cUSDC vault. For the other pools in your screenshot, just clarifying that these are not pools ran by us, but by Orca, Saber, Solend, respectively. 
I'm still very happy to add them, this should only require a change on our side, so you should be good to merge this PR in if it looks good to you!

**Comment by llamatester** [comment]
The hedge adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.385 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────┬──────────┬─────────┬────────────────────────┬───────────────────┬─────────┬───────────────────┬────────────────────────────────────────────────────┬────────────────────────────────────────────────────┐
    │ (index) │                      pool                      │  chain   │ project │         symbol         │      tvlUsd       │ apyBase │     apyReward     │                    rewardTokens                    │                  underlyingTokens                  │
    ├─────────┼────────────────────────────────────────────────┼──────────┼─────────┼────────────────────────┼───────────────────┼─────────┼───────────────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┤
    │    0    │ '4HWyRz6JpMLnMzJhtNyodrXbn32B8zK7WtNu5jVYnsJN' │ 'Solana' │ 'hedge' │ 'USH (Stability Pool)' │ 4653381.338113756 │    0    │ 30.91413420740111 │ [ '5PmpMzWjraf3kSsGEKtqdUsCoLhptg4yriZ17LKKdBBy' ] │ [ '9iLH8T7zoWhY7sBmj1WK9ENbWdS1nL8n9wAxaeRitTa6' ] │
    └─────────┴────────────────────────────────────────────────┴──────────┴─────────┴────────────────────────┴───────────────────┴─────────┴───────────────────┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
> cleaned up the commit history.
> 
> I removed the cUSDC vault. For the other pools in your screenshot, just clarifying that these are not pools ran by us, but by Orca, Saber, Solend, respectively. I'm still very happy to add them, this should only require a change on our side, so you should be good to merge this PR in if it looks good to you!

ty for making the changes!. i see, lets keep it as is then. we are already listing solend, and we gonna add the other projects separately so that we have more coverage for your project/token

**Pull request merged**
