### PR TITLE
Adding Liquid Bold adapter

### PR DESCRIPTION
**Pull request by LiquidBolt**
Hello,

Our apy comes from arbitrage transactions, we have a scraper that updates our api and regenerates the json file every 5 minutes.

The information are the same on our website (except apr/apy are calculated on 7 days):
https://app.liquidbolt.finance/info?chainId=250

Thanks, have a nice day!

### CODE REVIEW

**Comment by slasher125** [comment]
hi & ty for adding this. we don't allow pure api adapters anymore. so we need to move this to on subgraph/ on chain calls, at least for the tvl values. lmk if unclear

**Comment by LiquidBolt** [comment]
Hi, thank you for the reply.
I understand, I will calculate the lps tvl using chain calls 👍

**Comment by llamatester** [comment]
The liquid-bolt adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       130 passed, 130 total
    Snapshots:   0 total
    Time:        0.363 s
    Ran all test suites.
    
    Nb of pools: 18
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬──────────────┬──────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │    symbol    │  tvlUsd  │      apyBase       │                                        underlyingTokens                                        │                                          rewardTokens                                          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼──────────────┼──────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x030F2727A46872B5AeaBD4AbF7e8efFAa7EDF294' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-FTM'  │ 15369.7  │ 1435.8574289438143 │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    1    │ '0xB28BD33Bd6f714B9A764bba80628fCc2C6B28a02' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-ETH'  │ 5082.97  │ 2295.1829057595673 │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    2    │ '0x060a99bE45a5CDB93B3b5E98468d027cf4f624fA' │ 'Arbitrum' │ 'liquid-bolt' │  'GMX-ETH'   │ 3611.89  │         0          │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a' ] │
    │    3    │ '0xCa3320b0Bda841De9Cc86B07f699eE6Dd7C583E4' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-USDC' │ 1528.38  │ 3850.2439855790135 │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    4    │ '0x6b493C83a69558bc50b861f8874d8188F5fEE6b7' │  'Fantom'  │ 'liquid-bolt' │  'FTM-WETH'  │  1523.3  │ 3.682442348902426  │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │
    │    5    │ '0xb3227A582891480001b6D926Fce7d4c0177FC9B2' │  'Fantom'  │ 'liquid-bolt' │  'FTM-USDC'  │ 1379.62  │ 16.53514033781307  │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    6    │ '0x9891Dc7220d69302Dc581308cD5D26559867049c' │ 'Binance'  │ 'liquid-bolt' │  'BNB-BUSD'  │ 0.575252 │         0          │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    7    │ '0x7eC6445E5abbC2D25621a79c4141cee9b7afcEB5' │ 'Binance'  │ 'liquid-bolt' │  'ETH-BNB'   │ 0.305971 │         0          │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    │    8    │ '0x5CaFf0F367B5A4e098f8c0904f913Bcc413c2f10' │ 'Binance'  │ 'liquid-bolt' │  'ETH-BUSD'  │ 0.280645 │         0          │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    9    │ '0x9ddF080B7500812f343E7aC44F08AB05bD29A374' │ 'Binance'  │ 'liquid-bolt' │  'BTC-BNB'   │ 0.211393 │         0          │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴──────────────┴──────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The liquid-bolt adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       130 passed, 130 total
    Snapshots:   0 total
    Time:        0.346 s
    Ran all test suites.
    
    Nb of pools: 18
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────┬──────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │    project    │    symbol    │       tvlUsd       │      apyBase       │                                        underlyingTokens                                        │                                          rewardTokens                                          │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────┼──────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x030F2727A46872B5AeaBD4AbF7e8efFAa7EDF294' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-FTM'  │ 15366.979541667846 │ 1435.8574289438143 │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    1    │ '0xB28BD33Bd6f714B9A764bba80628fCc2C6B28a02' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-ETH'  │ 5083.850736327344  │ 2295.1829057595673 │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    2    │ '0x060a99bE45a5CDB93B3b5E98468d027cf4f624fA' │ 'Arbitrum' │ 'liquid-bolt' │  'GMX-ETH'   │ 3614.8758986913926 │         0          │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a' ] │
    │    3    │ '0x6b493C83a69558bc50b861f8874d8188F5fEE6b7' │  'Fantom'  │ 'liquid-bolt' │  'FTM-WETH'  │ 1530.7353873504449 │ 3.682442348902426  │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │
    │    4    │ '0xCa3320b0Bda841De9Cc86B07f699eE6Dd7C583E4' │  'Fantom'  │ 'liquid-bolt' │ 'TREEB-USDC' │ 1525.3608505594968 │ 3850.2439855790135 │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0xc60D7067dfBc6f2caf30523a064f416A5Af52963' ] │
    │    5    │ '0xb3227A582891480001b6D926Fce7d4c0177FC9B2' │  'Fantom'  │ 'liquid-bolt' │  'FTM-USDC'  │ 1383.4339204003836 │ 16.53514033781307  │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │
    │    6    │ '0x7eC6445E5abbC2D25621a79c4141cee9b7afcEB5' │ 'Binance'  │ 'liquid-bolt' │  'ETH-BNB'   │     0.6515745      │         0          │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    │    7    │ '0x5CaFf0F367B5A4e098f8c0904f913Bcc413c2f10' │ 'Binance'  │ 'liquid-bolt' │  'ETH-BUSD'  │ 0.6162803656540354 │         0          │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    8    │ '0x9891Dc7220d69302Dc581308cD5D26559867049c' │ 'Binance'  │ 'liquid-bolt' │  'BNB-BUSD'  │ 0.5766464037479198 │         0          │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56' ] │
    │    9    │ '0x9ddF080B7500812f343E7aC44F08AB05bD29A374' │ 'Binance'  │ 'liquid-bolt' │  'BTC-BNB'   │ 0.4625041544408951 │         0          │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────┴──────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by LiquidBolt** [comment]
Hi,

We are  using lps tvl from chain calls now.
Apy are very big because we've made almost +1% in the last 24h, but it's not always like that.
We can use 7d apy instead if you prefer, it would be smoother.

Thank you

**Comment by slasher125** [comment]
feel free to add `apyBase7d` using a 7day window and lets leave the current apyBase (1day) as is

**Pull request merged**
