### PR TITLE
Add Cellana finance reward pool

### PR DESCRIPTION
**Pull request by Centure2222**

### CODE REVIEW

**Comment by slasher125** [comment]
hi, ty for adding.
u need to remove apyBase as you are already counting as apyReward

**Comment by llamatester** [comment]
The cellana-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.256 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────┬─────────┬───────────────────┬─────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │            pool             │  chain  │      project      │   symbol    │       tvlUsd       │      apyBase       │     apyReward      │                               rewardTokens                               │
    ├─────────┼─────────────────────────────┼─────────┼───────────────────┼─────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ 'cellana-finance-AMAPT-APT' │ 'Aptos' │ 'cellana-finance' │ 'AMAPT-APT' │ 1070001.2872774291 │ 39.90370121592782  │ 39.90370121592782  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    1    │ 'cellana-finance-USDC-USDT' │ 'Aptos' │ 'cellana-finance' │ 'USDC-USDT' │ 824889.4281999391  │ 51.59746706245723  │ 51.59746706245723  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    2    │ 'cellana-finance-USDC-APT'  │ 'Aptos' │ 'cellana-finance' │ 'USDC-APT'  │ 454849.04761687724 │  96.4084937592553  │  96.4084937592553  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    3    │ 'cellana-finance-CELL-APT'  │ 'Aptos' │ 'cellana-finance' │ 'CELL-APT'  │ 439870.3856049904  │ 217.02823818719193 │ 217.02823818719193 │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    └─────────┴─────────────────────────────┴─────────┴───────────────────┴─────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────────────────────────────┘

**Comment by Centure2222** [comment]
> hi, ty for adding. u need to remove apyBase as you are already counting as apyReward

hi slasher125, I have deleted apybase, thank you sir

**Comment by llamatester** [comment]
The cellana-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.259 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────┬─────────┬───────────────────┬─────────────┬────────────────────┬─────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │            pool             │  chain  │      project      │   symbol    │       tvlUsd       │ apyBase │     apyReward      │                               rewardTokens                               │
    ├─────────┼─────────────────────────────┼─────────┼───────────────────┼─────────────┼────────────────────┼─────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │ 'cellana-finance-AMAPT-APT' │ 'Aptos' │ 'cellana-finance' │ 'AMAPT-APT' │ 1146818.8208224527 │    0    │ 38.91539159604384  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    1    │ 'cellana-finance-USDC-USDT' │ 'Aptos' │ 'cellana-finance' │ 'USDC-USDT' │ 897387.4594272389  │    0    │ 49.57501571720392  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    2    │ 'cellana-finance-USDC-APT'  │ 'Aptos' │ 'cellana-finance' │ 'USDC-APT'  │ 473711.9696782813  │    0    │ 96.75801838914279  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    3    │ 'cellana-finance-CELL-APT'  │ 'Aptos' │ 'cellana-finance' │ 'CELL-APT'  │ 464305.7878624002  │    0    │ 214.90949711603454 │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    └─────────┴─────────────────────────────┴─────────┴───────────────────┴─────────────┴────────────────────┴─────────┴────────────────────┴──────────────────────────────────────────────────────────────────────────┘

**Pull request merged**
