### PR TITLE
feat: add cronos lyf pool

### PR DESCRIPTION
**Pull request by singlefinance**
We have updated the Single Finance cronos farming pool data to the yield server adapter.

### CODE REVIEW

**Comment by slasher125** [comment]
re farming apr:
- make sure to use unboosted values (leverage = 1)
- instead of using apy, why not use apyBase and apyReward?
- also, apyReward (the farm incentives) seem to be missing.

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       267 passed, 267 total
    Snapshots:   0 total
    Time:        0.456 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────┬────────────┬──────────────────┬────────────┬───────────────┬────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬─────┐
    │ (index) │                            pool                             │   chain    │     project      │   symbol   │   poolMeta    │       tvlUsd       │         apy         │                                        underlyingTokens                                        │   apyBaseBorrow    │   totalSupplyUsd   │   totalBorrowUsd   │       apyBase       │      apyReward      │                   rewardTokens                   │ ltv │
    ├─────────┼─────────────────────────────────────────────────────────────┼────────────┼──────────────────┼────────────┼───────────────┼────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼─────┤
    │    0    │ '0xbf62c67eA509E86F07c8c69d0286C0636C50270b-farming-cronos' │  'Cronos'  │ 'single-finance' │ 'VVS-CRO'  │ 'VVS Finance' │ 2089668.0769826148 │ 0.30852072431089006 │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ] │                    │                    │                    │                     │                     │                                                  │     │
    │    1    │        '0x88a73F172D84eC36D974ab756c18D52Eff1369b1'         │  'Cronos'  │ 'single-finance' │   'USDC'   │               │ 606486.7254632738  │                     │                        [ '0xc21223249ca28397b4b6541dffaecc539bff0c59' ]                        │  4.4942106801888   │ 782272.2822463473  │ 175785.55678307347 │ 0.8281185753482732  │ 0.3053082494110303  │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    2    │        '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24'         │  'Cronos'  │ 'single-finance' │   'CRO'    │               │ 423917.9853791802  │                     │                        [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ]                        │ 20.919989126376002 │ 1610908.412035326  │ 1186990.4266561458 │ 12.640133876795373  │ 0.30832304934616295 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    3    │        '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db'         │  'Cronos'  │ 'single-finance' │   'MMF'    │               │ 224066.0107345324  │                     │                        [ '0x97749c9b61f878a880dfe312d2594ae07aed7656' ]                        │         0          │ 224066.0107345324  │         0          │          0          │ 0.08459851452934482 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    4    │ '0xe61Db569E231B3f5530168Aa2C9D50246525b6d6-farming-cronos' │  'Cronos'  │ 'single-finance' │ 'CRO-USDC' │ 'VVS Finance' │ 187649.6459885451  │ 0.08654658959983408 │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                    │                     │                     │                                                  │     │
    │    5    │        '0x1E16725dBce0F9CDA53c92cEF72cE455a1ea6FFf'         │ 'Arbitrum' │ 'single-finance' │   'WETH'   │               │ 76372.75483527835  │                     │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │   0.68615666136    │ 116324.17519444936 │  39951.420359171   │ 0.19324104550769552 │          0          │                        []                        │  0  │
    │    6    │        '0x467dff5b14b4dd40a52be338b75c9b58ead4add0'         │  'Cronos'  │ 'single-finance' │   'USDT'   │               │ 66417.91579237061  │                     │                        [ '0x66e428c3f67a68878562e79a0234c1f83c208770' ]                        │   1.592354911248   │ 72163.53638916984  │ 5745.620596799235  │ 0.10396157754015338 │ 0.6618096199227367  │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    7    │ '0x6ae624714f221964aff3AB8D8276a7ec142a759f-farming-cronos' │  'Cronos'  │ 'single-finance' │ 'VVS-FUL'  │ 'VVS Finance' │ 40561.86370229518  │ 0.7784236749458939  │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x83aFB1C32E5637ACd0a452D87c3249f4a9F0013A' ] │                    │                    │                    │                     │                     │                                                  │     │
    │    8    │ '0xa68466208F1A3Eb21650320D2520ee8eBA5ba623-farming-cronos' │  'Cronos'  │ 'single-finance' │ 'CRO-USDC' │  'MMFinance'  │ 40541.945023270266 │ 0.07325694596626496 │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                    │                     │                     │                                                  │     │
    │    9    │ '0xd0BE1AaBA78b7b4eb4C09719317529108a0d5C54-farming-cronos' │  'Cronos'  │ 'single-finance' │ 'CRO-BCRO' │ 'VVS Finance' │ 40330.57043371624  │ 0.10496993582664321 │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ] │                    │                    │                    │                     │                     │                                                  │     │
    └─────────┴─────────────────────────────────────────────────────────────┴────────────┴──────────────────┴────────────┴───────────────┴────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by singlefinance** [comment]
@slasher125 
Thank you for the suggestion, we have updated the apy calculation using unboosted values.
If unboosted values are used, we would like to use apy instead of apyBase and apyReward because we are not giving rewards ($SINGLE) to unboosted position (leverage = 1), hence the apyReward is always 0 in this case.

**Comment by slasher125** [comment]
> @slasher125 Thank you for the suggestion, we have updated the apy calculation using unboosted values. If unboosted values are used, we would like to use apy instead of apyBase and apyReward because we are not giving rewards ($SINGLE) to unboosted position (leverage = 1), hence the apyReward is always 0 in this case.

if the apy component doesn't come from incentives then we use `apyBase`. we calculate apy for u server side, but in the adapter it should be as specific as possible! so in your case, if lev = 1 means no rewards, and the remaining apr does not contain any form of incentives,  then `apyBase` is what u need to use

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       267 passed, 267 total
    Snapshots:   0 total
    Time:        0.62 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────┬──────────┬──────────────────┬────────────┬───────────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬─────┐
    │ (index) │                            pool                             │  chain   │     project      │   symbol   │   poolMeta    │       tvlUsd       │       apyBase       │      apyReward       │                                        underlyingTokens                                        │   apyBaseBorrow    │   totalSupplyUsd   │   totalBorrowUsd   │                   rewardTokens                   │ ltv │
    ├─────────┼─────────────────────────────────────────────────────────────┼──────────┼──────────────────┼────────────┼───────────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼─────┤
    │    0    │ '0xbf62c67eA509E86F07c8c69d0286C0636C50270b-farming-cronos' │ 'Cronos' │ 'single-finance' │ 'VVS-CRO'  │ 'VVS Finance' │  2219305.43861202  │ 0.30326368040685114 │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ] │                    │                    │                    │                                                  │     │
    │    1    │        '0x88a73F172D84eC36D974ab756c18D52Eff1369b1'         │ 'Cronos' │ 'single-finance' │   'USDC'   │               │ 592069.0584159805  │ 0.7340542669987353  │ 0.29934995656649094  │                        [ '0xc21223249ca28397b4b6541dffaecc539bff0c59' ]                        │  4.2312739916016   │ 750941.8259606883  │ 158872.7675447078  │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    2    │        '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24'         │ 'Cronos' │ 'single-finance' │   'CRO'    │               │ 444382.4995997662  │ 12.720169566293348  │ 0.27420215677037757  │                        [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ]                        │  20.9812195721952  │ 1704881.6351641114 │ 1260499.1355643452 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    3    │        '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db'         │ 'Cronos' │ 'single-finance' │   'MMF'    │               │ 229840.36713872704 │          0          │ 0.025874727088994152 │                        [ '0x97749c9b61f878a880dfe312d2594ae07aed7656' ]                        │         0          │ 229840.36713872704 │         0          │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    4    │ '0xe61Db569E231B3f5530168Aa2C9D50246525b6d6-farming-cronos' │ 'Cronos' │ 'single-finance' │ 'CRO-USDC' │ 'VVS Finance' │ 169693.43991852077 │ 0.0898583387592744  │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                    │                                                  │     │
    │    5    │        '0x467dff5b14b4dd40a52be338b75c9b58ead4add0'         │ 'Cronos' │ 'single-finance' │   'USDT'   │               │    64858.213563    │ 0.10179398372840388 │  0.6384568103986535  │                        [ '0x66e428c3f67a68878562e79a0234c1f83c208770' ]                        │ 1.5756631524287998 │    70405.096183    │     5546.88262     │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    6    │ '0xd0BE1AaBA78b7b4eb4C09719317529108a0d5C54-farming-cronos' │ 'Cronos' │ 'single-finance' │ 'CRO-BCRO' │ 'VVS Finance' │ 43311.346779150896 │ 0.07628278057768038 │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ] │                    │                    │                    │                                                  │     │
    │    7    │ '0x6ae624714f221964aff3AB8D8276a7ec142a759f-farming-cronos' │ 'Cronos' │ 'single-finance' │ 'VVS-FUL'  │ 'VVS Finance' │ 42928.59645443717  │  0.775376800048222  │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x83aFB1C32E5637ACd0a452D87c3249f4a9F0013A' ] │                    │                    │                    │                                                  │     │
    │    8    │ '0xa68466208F1A3Eb21650320D2520ee8eBA5ba623-farming-cronos' │ 'Cronos' │ 'single-finance' │ 'CRO-USDC' │  'MMFinance'  │ 41849.101518841846 │ 0.07336505410285425 │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                    │                                                  │     │
    │    9    │        '0x9f379739d3b3B2b44dECAc9864404B2B2952eE70'         │ 'Cronos' │ 'single-finance' │   'bCRO'   │               │ 31801.936699211128 │ 3.2838586429672065  │ 0.22584012281089855  │                        [ '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ]                        │  10.960575495984   │ 50111.27816322839  │ 18309.34146401726  │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    └─────────┴─────────────────────────────────────────────────────────────┴──────────┴──────────────────┴────────────┴───────────────┴────────────────────┴─────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by singlefinance** [comment]
Thanks for your comment. The adapter is updated to use `apyBase` and `apyReward`.

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       465 passed, 465 total
    Snapshots:   0 total
    Time:        0.516 s
    Ran all test suites.
    
    Nb of pools: 74
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────┬────────────┬──────────────────┬───────────────┬───────────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬─────┐
    │ (index) │                                 pool                                  │   chain    │     project      │    symbol     │   poolMeta    │       tvlUsd       │       apyBase       │      apyReward       │                                        underlyingTokens                                        │   apyBaseBorrow    │  totalSupplyUsd   │   totalBorrowUsd   │                   rewardTokens                   │ ltv │
    ├─────────┼───────────────────────────────────────────────────────────────────────┼────────────┼──────────────────┼───────────────┼───────────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼─────┤
    │    0    │    '0xbf62c67eA509E86F07c8c69d0286C0636C50270b-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │   'VVS-CRO'   │ 'VVS Finance' │ 2216139.072315542  │ 0.3031410382502209  │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ] │                    │                   │                    │                                                  │     │
    │    1    │             '0x88a73F172D84eC36D974ab756c18D52Eff1369b1'              │  'Cronos'  │ 'single-finance' │    'USDC'     │               │ 591412.9044723725  │ 0.7362970035694931  │  0.2988482454617869  │                        [ '0xc21223249ca28397b4b6541dffaecc539bff0c59' ]                        │  4.2377261342112   │ 750417.3006804718 │ 159004.39620809938 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    2    │             '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24'              │  'Cronos'  │ 'single-finance' │     'CRO'     │               │ 444781.7318851636  │ 12.720169566293348  │  0.2733058496005658  │                        [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ]                        │  20.9812195721952  │ 1706413.297171845 │ 1261631.5652866815 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    3    │             '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db'              │  'Cronos'  │ 'single-finance' │     'MMF'     │               │ 230050.1027279699  │          0          │ 0.025789784171913584 │                        [ '0x97749c9b61f878a880dfe312d2594ae07aed7656' ]                        │         0          │ 230050.1027279699 │         0          │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    4    │    '0xe61Db569E231B3f5530168Aa2C9D50246525b6d6-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-USDC'   │ 'VVS Finance' │ 169722.05352411442 │ 0.09004567071400071 │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                   │                    │                                                  │     │
    │    5    │ '0x84652bb2539513BAf36e225c930Fdd8eaa63CE27-camelot-farming-arbitrum' │ 'Arbitrum' │ 'single-finance' │ 'WETH-USDC.e' │   'Camelot'   │ 122037.09193944758 │ 0.4377468034204812  │          0           │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │                    │                   │                    │                                                  │     │
    │    6    │             '0x467dff5b14b4dd40a52be338b75c9b58ead4add0'              │  'Cronos'  │ 'single-finance' │    'USDT'     │               │ 64850.62515201312  │ 0.10179398372840388 │  0.637016078223333   │                        [ '0x66e428c3f67a68878562e79a0234c1f83c208770' ]                        │ 1.5756631524287998 │ 70396.85878674658 │  5546.23363473346  │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    7    │    '0xd0BE1AaBA78b7b4eb4C09719317529108a0d5C54-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-BCRO'   │ 'VVS Finance' │ 43372.19377431521  │ 0.07610943682303757 │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ] │                    │                   │                    │                                                  │     │
    │    8    │    '0x6ae624714f221964aff3AB8D8276a7ec142a759f-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │   'VVS-FUL'   │ 'VVS Finance' │ 42790.40435850544  │ 0.7761173599552196  │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x83aFB1C32E5637ACd0a452D87c3249f4a9F0013A' ] │                    │                   │                    │                                                  │     │
    │    9    │    '0xa68466208F1A3Eb21650320D2520ee8eBA5ba623-mmf-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-USDC'   │  'MMFinance'  │ 41863.99656019326  │ 0.07332387238119774 │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                   │                    │                                                  │     │
    └─────────┴───────────────────────────────────────────────────────────────────────┴────────────┴──────────────────┴───────────────┴───────────────┴────────────────────┴─────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by singlefinance** [comment]
We have also added the lyf pools on Fantom chain and Arbitrum Chain.

**Comment by slasher125** [comment]
apyBase needs to be in percent, so multiply by 100

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       465 passed, 465 total
    Snapshots:   0 total
    Time:        0.511 s
    Ran all test suites.
    
    Nb of pools: 74
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────┬────────────┬──────────────────┬───────────────┬───────────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬───────────────────┬──────────────────────────────────────────────────┬─────┐
    │ (index) │                                 pool                                  │   chain    │     project      │    symbol     │   poolMeta    │       tvlUsd       │       apyBase       │      apyReward       │                                        underlyingTokens                                        │   apyBaseBorrow    │   totalSupplyUsd   │  totalBorrowUsd   │                   rewardTokens                   │ ltv │
    ├─────────┼───────────────────────────────────────────────────────────────────────┼────────────┼──────────────────┼───────────────┼───────────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼───────────────────┼──────────────────────────────────────────────────┼─────┤
    │    0    │    '0xbf62c67eA509E86F07c8c69d0286C0636C50270b-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │   'VVS-CRO'   │ 'VVS Finance' │ 2221887.854964601  │  32.0949798180042   │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ] │                    │                    │                   │                                                  │     │
    │    1    │             '0x88a73F172D84eC36D974ab756c18D52Eff1369b1'              │  'Cronos'  │ 'single-finance' │    'USDC'     │               │ 591788.7478312793  │ 0.7362970035694931  │ 0.29962066596479614  │                        [ '0xc21223249ca28397b4b6541dffaecc539bff0c59' ]                        │  4.2377261342112   │ 750894.1914563354  │ 159105.4436250561 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    2    │             '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24'              │  'Cronos'  │ 'single-finance' │     'CRO'     │               │ 446026.2780314889  │ 12.720111535123724  │ 0.27342027232437127  │                        [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ]                        │  20.9810957965488  │ 1711194.512023124  │ 1265168.233991635 │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    3    │             '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db'              │  'Cronos'  │ 'single-finance' │     'MMF'     │               │ 230723.85128063054 │          0          │ 0.025797321026623687 │                        [ '0x97749c9b61f878a880dfe312d2594ae07aed7656' ]                        │         0          │ 230723.85128063054 │         0         │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    4    │    '0xe61Db569E231B3f5530168Aa2C9D50246525b6d6-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-USDC'   │ 'VVS Finance' │ 169881.4751368269  │  8.713802506780933  │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                   │                                                  │     │
    │    5    │ '0x84652bb2539513BAf36e225c930Fdd8eaa63CE27-camelot-farming-arbitrum' │ 'Arbitrum' │ 'single-finance' │ 'WETH-USDC.e' │   'Camelot'   │ 122204.86391386243 │  46.46891989824702  │          0           │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │                    │                    │                   │                                                  │     │
    │    6    │             '0x467dff5b14b4dd40a52be338b75c9b58ead4add0'              │  'Cronos'  │ 'single-finance' │    'USDT'     │               │    64858.213563    │ 0.10179398372840388 │  0.6389936464529469  │                        [ '0x66e428c3f67a68878562e79a0234c1f83c208770' ]                        │ 1.5756631524287998 │    70405.096183    │    5546.88262     │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    7    │    '0xd0BE1AaBA78b7b4eb4C09719317529108a0d5C54-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-BCRO'   │ 'VVS Finance' │  43429.6098816502  │  6.926405405261016  │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ] │                    │                    │                   │                                                  │     │
    │    8    │    '0x6ae624714f221964aff3AB8D8276a7ec142a759f-vvs-farming-cronos'    │  'Cronos'  │ 'single-finance' │   'VVS-FUL'   │ 'VVS Finance' │ 42716.23455003296  │  104.325830525194   │          0           │ [ '0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03', '0x83aFB1C32E5637ACd0a452D87c3249f4a9F0013A' ] │                    │                    │                   │                                                  │     │
    │    9    │    '0xa68466208F1A3Eb21650320D2520ee8eBA5ba623-mmf-farming-cronos'    │  'Cronos'  │ 'single-finance' │  'CRO-USDC'   │  'MMFinance'  │ 41891.42666797198  │ 6.7334470208261346  │          0           │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59' ] │                    │                    │                   │                                                  │     │
    └─────────┴───────────────────────────────────────────────────────────────────────┴────────────┴──────────────────┴───────────────┴───────────────┴────────────────────┴─────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴───────────────────┴──────────────────────────────────────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by singlefinance** [comment]
Fixed the apyBase calculation and unit.

**Pull request merged**
