### PR TITLE
Change pool name and fetch new number from new data structure

### PR DESCRIPTION
**Pull request by molefund**
Dear DefiLlama, 
we have changed pool name and fetch new numbers from new data structure. Please help to review and help to merge. Thank you very much :)

### CODE REVIEW

**Comment by slasher125** [comment]
changing existing pool values introduces a bit of workload on our side cause I'd have to update the data base entries overwriting the current pool values with the new ones here. Otherwise the history on the charts would get truncated. lmk if really neceassary, if yes I'll make the changes

**Comment by molefund** [comment]
Dear Slasher,

Thank you for your promote reply. Sorry to bring the inconvenience workload to you. In this change, we change not only the pool name, but also the new fetched data structure. The critical code as following: 

 >>>>  const fundPools = response.funds.map((p) => ({   

We get the data from "response.funds" . And the old data structure can't be fetched data now. 

Could you please help to update the data base entries for the new changed pool by any chance? I am sorry to bring you the inconvenience. I'd be very appreciate for your hard work :)

Best regards,
Mole 


> changing existing pool values introduces a bit of workload on our side cause I'd have to update the data base entries overwriting the current pool values with the new ones here. Otherwise the history on the charts would get truncated. lmk if really neceassary, if yes I'll make the changes

**Comment by slasher125** [comment]
ah yeah i thought of just leaving the `pool: `${p.key}-fund-pool` as is but changing the rest...no worries though, i will make the change.

**Comment by molefund** [comment]
> ah yeah i thought of just leaving the `pool: `${p.key}-fund-pool` as is but changing the rest...no worries though, i will make the change.

Dear Slasher,

That's great! It really nice. Thank you so much  O(∩_∩)O~

**Pull request merged**
