### PR TITLE
Feat/quasar vaults adaptor

### PR DESCRIPTION
**Pull request by magiodev**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running quasar-vaults adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.284 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬──────────┬──────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │  symbol  │      tvlUsd      │        apy         │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼──────────┼──────────────────┼────────────────────┤
    │    0    │ '0x4f3Cc6359364004b245ad5bE36E6ad4e805dC961' │ 'Ethereum' │ 'mellow' │ 'wstETH' │ 2647508.76788085 │ 2.9734285714285713 │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴──────────┴──────────────────┴────────────────────┘
    }

**Comment by llamatester** [comment]
The quasar-vaults adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.267 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────────┬──────────┬──────────────────┬───────┐
    │ (index) │                     pool                     │   chain    │     project     │  symbol  │      tvlUsd      │  apy  │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────────┼──────────┼──────────────────┼───────┤
    │    0    │ '0x4f3Cc6359364004b245ad5bE36E6ad4e805dC961' │ 'Ethereum' │ 'quasar-vaults' │ 'wstETH' │ 2675721.74382475 │ 2.977 │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────────┴──────────┴──────────────────┴───────┘

**Comment by slasher125** [comment]
gm,

- symbol should be urLRT
- poolMeta = mellow
- pls confirm that the token can be swapped back to eg steth without lockups, otherwise that info needs to be put into poolMeta
- data should be fetched from on chain calls using our sdk. at minimum to fetch the tvl values. you can use our price api for calculating the $ value

**Comment by magiodev** [comment]
> gm,
> 
> * symbol should be urLRT
> * poolMeta = mellow
> * pls confirm that the token can be swapped back to eg steth without lockups, otherwise that info needs to be put into poolMeta
> * data should be fetched from on chain calls using our sdk. at minimum to fetch the tvl values. you can use our price api for calculating the $ value

Ok I will add the pooLMeta property. In case of lockup, could it be a free string like: `mellow, N days lockup` ?

Also, yes, the token can be redeemed, not really swapped. I mean, it could be swapped on Uniswap, but the protocol allows for redemption with a 1-7 days batched lockup period. I will add the information on the poolMeta accordingly.

From the Mellow docs: https://docs.mellow.finance/mellow-lrt-lst-primitive/user-tutorials/withdrawal-guide
```
Step 8: Lockup Period
After requesting withdrawal, you will not receive any points for the withdrawn LRT. The points earned are displayed in your dashboard. Withdrawals are processed by risk curators within 1-7 days in batches.
```

**Comment by slasher125** [comment]
yes pls add that info to poolMeta

**Comment by slasher125** [comment]
> > yes pls add that info to poolMeta
> 
> thanks, may you also please point me to some prod code example about the price api? or any doc?

just search the repo for `https://coins.llama.fi/prices/current/` there a ton of examples. docs here: https://defillama.com/docs/api

**Comment by llamatester** [comment]
Error while running quasar-vaults adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.301 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────┬────────────┬──────────┬─────────┬────────────────────┬───────────────────┐
    │ (index) │                                                                                                            poolMeta                                                                                                            │                     pool                     │   chain    │ project  │ symbol  │       tvlUsd       │        apy        │
    ├─────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────┼──────────┼─────────┼────────────────────┼───────────────────┤
    │    0    │ 'Lockup Period: After requesting withdrawal, you will not receive any points for the withdrawn LRT. The points earned are displayed in your dashboard. Withdrawals are processed by risk curators within 1-7 days in batches.' │ '0x4f3Cc6359364004b245ad5bE36E6ad4e805dC961' │ 'Ethereum' │ 'mellow' │ 'urLRT' │ 2275735.9234908805 │ 3.194428571428572 │
    └─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────┴────────────┴──────────┴─────────┴────────────────────┴───────────────────┘
    }

**Comment by slasher125** [comment]
sir, we do not list list points on our end. 
yield either has to come from fees or token rewards which are liquid and can be sold

**Comment by llamatester** [comment]
The quasar-vaults adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.266 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────┬────────────┬─────────────────┬─────────┬───────────────────┬───────────────────┐
    │ (index) │                                                     poolMeta                                                     │                     pool                     │   chain    │     project     │ symbol  │      tvlUsd       │        apy        │
    ├─────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────┼─────────────────┼─────────┼───────────────────┼───────────────────┤
    │    0    │ 'Mellow Finance Protocol. Lockup Period: Withdrawals are processed by risk curators within 1-7 days in batches.' │ '0x4f3Cc6359364004b245ad5bE36E6ad4e805dC961' │ 'Ethereum' │ 'quasar-vaults' │ 'urLRT' │ 2272310.699610652 │ 3.111714285714286 │
    └─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────┴────────────┴─────────────────┴─────────┴───────────────────┴───────────────────┘

**Comment by magiodev** [comment]
> > > sir, we do not list list points on our end. yield either has to come from fees or token rewards which are liquid and can be sold
> > 
> > sure, removed the string about points and left only the lockup period information
> 
> what i meant with that is that we do not count apy from points on our site, meaning if it contains points we need to remove these

Oh I see. The given APY is just the stETH staking rewards. No points are part of the APY.

**Pull request merged**
