### PR TITLE
add kokoa-finance cdp

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by llamatester** [comment]
The kokoa-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       117 passed, 117 total
    Snapshots:   0 total
    Time:        0.348 s
    Ran all test suites.
    
    Nb of pools: 19
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────────┬─────────┬──────────┬─────────┬───────────┬──────────────────┬────────────────────┬───────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬─────┬────────────┬───────┐
    │ (index) │                     pool                     │     project     │ symbol  │  chain   │ apyBase │ apyReward │     poolMeta     │       tvlUsd       │ apyBaseBorrow │   totalSupplyUsd   │                   rewardTokens                   │   totalBorrowUsd   │ ltv │ mintedCoin │  apy  │
    ├─────────┼──────────────────────────────────────────────┼─────────────────┼─────────┼──────────┼─────────┼───────────┼──────────────────┼────────────────────┼───────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼─────┼────────────┼───────┤
    │    0    │ '0x5096dB80B21Ef45230C9E423C373f1FC9C0198dd' │ 'kokoa-finance' │ 'WEMIX' │ 'Klaytn' │  1.62   │   0.88    │     'WEMIX'      │ 45355549.49950044  │       7       │ 45355549.49950044  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 16032430.605091017 │ 60  │   'KSD'    │       │
    │    1    │ '0x5e6215dfb33b1fb71e48000a47ed2ebb86d5bf3d' │ 'kokoa-finance' │  'KSD'  │ 'Klaytn' │         │           │                  │ 6968812.355066319  │               │                    │                                                  │                    │     │            │ 16.53 │
    │    2    │ '0x9eaeFb09fe4aABFbE6b1ca316a3c36aFC83A393F' │ 'kokoa-finance' │ 'oXRP'  │ 'Klaytn' │  2.48   │   0.88    │      'KXRP'      │ 698450.5311262973  │      10       │ 698450.5311262973  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 274263.7607509718  │ 60  │   'KSD'    │       │
    │    3    │ '0xceE8FAF64bB97a73bb51E115Aa89C17FfA8dD167' │ 'kokoa-finance' │ 'oUSDT' │ 'Klaytn' │  7.14   │   0.88    │     'KUSDT'      │   353850.322643    │      10       │   353850.322643    │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 287661.5322497471  │ 90  │   'KSD'    │       │
    │    4    │ '0xFe41102f325dEaa9F303fDd9484Eb5911a7BA557' │ 'kokoa-finance' │ 'oORC'  │ 'Klaytn' │  5.16   │   0.88    │      'KORC'      │ 348390.9194302937  │      10       │ 348390.9194302937  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 144518.86256708042 │ 60  │   'KSD'    │       │
    │    5    │ '0x029e2A1B2bb91B66bd25027E1C211E5628dbcb93' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │  9.92   │   0.88    │ 'KSLPKETHKUSDT'  │ 90805.02393756983  │     7.84      │ 90805.02393756983  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 56574.85624494353  │ 75  │   'KSD'    │       │
    │    6    │ '0x2E9269B718cc816De6A9E3C27E5bdb0F6A01b0ac' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │  4.36   │   0.88    │ 'KSLPKUSDTKUSDC' │ 62672.77927976107  │      10       │ 62672.77927976107  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 49768.61186565665  │ 90  │   'KSD'    │       │
    │    7    │ '0x16D0e1fBD024c600Ca0380A4C5D57Ee7a2eCBf9c' │ 'kokoa-finance' │ 'oWBTC' │ 'Klaytn' │    0    │   0.88    │     'KWBTC'      │ 56266.94750398059  │      10       │ 56266.94750398059  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 14319.583326241083 │ 60  │   'KSD'    │       │
    │    8    │ '0x34d21b1e550D73cee41151c77F3c73359527a396' │ 'kokoa-finance' │ 'oETH'  │ 'Klaytn' │  4.76   │   0.88    │      'KETH'      │ 52049.66095969355  │      10       │ 52049.66095969355  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 19809.018446979488 │ 60  │   'KSD'    │       │
    │    9    │ '0xc320066b25B731A11767834839Fe57f9b2186f84' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │  2.77   │   0.88    │ 'KSLPKUSDTKDAI'  │ 30412.570486958797 │      10       │ 30412.570486958797 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 25667.66504301806  │ 90  │   'KSD'    │       │
    └─────────┴──────────────────────────────────────────────┴─────────────────┴─────────┴──────────┴─────────┴───────────┴──────────────────┴────────────────────┴───────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴─────┴────────────┴───────┘

**Comment by 0xngmi** [comment]
how is it that stuff like oUSDT has apyBase? where is the apy coming from?

**Comment by dtmkeng** [comment]
> how is it that stuff like oUSDT has apyBase? where is the apy coming from?

seems like a web show reward apr
image
```
{
address: "0xceE8FAF64bB97a73bb51E115Aa89C17FfA8dD167",
collateralType: "0x4b55534454000000000000000000000000000000000000000000000000000000",
gateway: "0xaEE24956F6CCC58deaC3C49DDb65a5c72D8bdd30",
issuedKsdPoolAddress: "0x103D21101BA2Dd3993293387C4DaD178B3116B49",
collateralPrice: "1.00000000",
yieldApr: "7.14",
maxLtvPercent: "80.00",
liqLtvPercent: "90.00",
liqPenaltyPercent: "2.00",
stabilityFeeApr: "10.00",
rewardApr: "0.85",
netApr: "-9.15",
position: {
ltvPercent: "0",
borrowed: null,
collateral: null,
kokoaReward: null,
ksdRefund: null
},
maxMultiple: null,
totalCollateralAmount: "353850.322643",
totalBorrowedAmount: "288459.700240312005963561"
}
```

**Comment by slasher125** [comment]
a few things:
- generally, lets display ltv not! as %, eg instead of 60 we use 0.6
- `apyBase` shouldn't exist for cdp's on kokoa
- `apyReward` should be -> `apyRewardBorrow` given this is coming from borrow/cdp activity
- lets remove `poolMeta` content for all pools except the LP positions eg:
Screenshot 2022-11-01 at 11 04 04

in which case: symbol: `oUSDT-KDAI` and poolMeta: Klayswap LP

**Comment by dtmkeng** [comment]
sorry, i can not find debtCeilingUsd

**Comment by llamatester** [comment]
The kokoa-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       117 passed, 117 total
    Snapshots:   0 total
    Time:        0.407 s
    Ran all test suites.
    
    Nb of pools: 19
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────────┬─────────┬──────────┬───────┬────────────────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬──────┬────────────┐
    │ (index) │                     pool                     │     project     │ symbol  │  chain   │  apy  │       tvlUsd       │ apyRewardBorrow │   totalSupplyUsd   │                   rewardTokens                   │   totalBorrowUsd   │ ltv  │ mintedCoin │
    ├─────────┼──────────────────────────────────────────────┼─────────────────┼─────────┼──────────┼───────┼────────────────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼──────┼────────────┤
    │    0    │ '0x5096dB80B21Ef45230C9E423C373f1FC9C0198dd' │ 'kokoa-finance' │ 'WEMIX' │ 'Klaytn' │   0   │ 46266064.09237128  │      0.75       │ 46266064.09237128  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 15808811.408101276 │ 0.6  │   'KSD'    │
    │    1    │ '0x5e6215dfb33b1fb71e48000a47ed2ebb86d5bf3d' │ 'kokoa-finance' │  'KSD'  │ 'Klaytn' │ 14.92 │  8155516.2521045   │                 │                    │                                                  │                    │      │            │
    │    2    │ '0x9eaeFb09fe4aABFbE6b1ca316a3c36aFC83A393F' │ 'kokoa-finance' │ 'oXRP'  │ 'Klaytn' │   0   │ 709981.9457386455  │      0.75       │ 709981.9457386455  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 266771.0199543726  │ 0.6  │   'KSD'    │
    │    3    │ '0xceE8FAF64bB97a73bb51E115Aa89C17FfA8dD167' │ 'kokoa-finance' │ 'oUSDT' │ 'Klaytn' │   0   │   353850.322643    │      0.75       │   353850.322643    │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │  283640.334218809  │ 0.9  │   'KSD'    │
    │    4    │ '0xFe41102f325dEaa9F303fDd9484Eb5911a7BA557' │ 'kokoa-finance' │ 'oORC'  │ 'Klaytn' │   0   │ 335150.06729676854 │      0.75       │ 335150.06729676854 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 142312.9285846062  │ 0.6  │   'KSD'    │
    │    5    │ '0x029e2A1B2bb91B66bd25027E1C211E5628dbcb93' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 91005.82357351514  │      0.75       │ 91005.82357351514  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 55780.30296994326  │ 0.75 │   'KSD'    │
    │    6    │ '0x2E9269B718cc816De6A9E3C27E5bdb0F6A01b0ac' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 62672.77927976107  │      0.75       │ 62672.77927976107  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 49072.81891046447  │ 0.9  │   'KSD'    │
    │    7    │ '0x16D0e1fBD024c600Ca0380A4C5D57Ee7a2eCBf9c' │ 'kokoa-finance' │ 'oWBTC' │ 'Klaytn' │   0   │ 56958.296496678464 │      0.75       │ 56958.296496678464 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 14119.920378580686 │ 0.6  │   'KSD'    │
    │    8    │ '0x34d21b1e550D73cee41151c77F3c73359527a396' │ 'kokoa-finance' │ 'oETH'  │ 'Klaytn' │   0   │ 52888.06663600555  │      0.75       │ 52888.06663600555  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 19532.103542301058 │ 0.6  │   'KSD'    │
    │    9    │ '0xc320066b25B731A11767834839Fe57f9b2186f84' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 30412.570486958797 │      0.75       │ 30412.570486958797 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 25309.771992165774 │ 0.9  │   'KSD'    │
    └─────────┴──────────────────────────────────────────────┴─────────────────┴─────────┴──────────┴───────┴────────────────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴──────┴────────────┘

**Comment by slasher125** [comment]
> sorry, i can not find debtCeilingUsd

i contacted them, lets see

**Comment by dtmkeng** [comment]
> 

oke

**Comment by slasher125** [comment]
seems like the `apyBaseBorrow` is no longer in here now hmm. will need to add that back.

**Comment by llamatester** [comment]
The kokoa-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       117 passed, 117 total
    Snapshots:   0 total
    Time:        0.439 s
    Ran all test suites.
    
    Nb of pools: 19
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────────┬─────────┬──────────┬───────┬────────────────────┬─────────────────┬───────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────┬──────┬────────────┐
    │ (index) │                     pool                     │     project     │ symbol  │  chain   │  apy  │       tvlUsd       │ apyRewardBorrow │ apyBaseBorrow │   totalSupplyUsd   │                   rewardTokens                   │   totalBorrowUsd   │ ltv  │ mintedCoin │
    ├─────────┼──────────────────────────────────────────────┼─────────────────┼─────────┼──────────┼───────┼────────────────────┼─────────────────┼───────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────┼──────┼────────────┤
    │    0    │ '0x5096dB80B21Ef45230C9E423C373f1FC9C0198dd' │ 'kokoa-finance' │ 'WEMIX' │ 'Klaytn' │   0   │ 46266064.09237128  │      0.75       │     5.49      │ 46266064.09237128  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 15795915.418128965 │ 0.6  │   'KSD'    │
    │    1    │ '0x5e6215dfb33b1fb71e48000a47ed2ebb86d5bf3d' │ 'kokoa-finance' │  'KSD'  │ 'Klaytn' │ 14.92 │  8139617.6321045   │                 │               │                    │                                                  │                    │      │            │
    │    2    │ '0x9eaeFb09fe4aABFbE6b1ca316a3c36aFC83A393F' │ 'kokoa-finance' │ 'oXRP'  │ 'Klaytn' │   0   │ 709981.9457386455  │      0.75       │     7.67      │ 709981.9457386455  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 266553.4023037204  │ 0.6  │   'KSD'    │
    │    3    │ '0xceE8FAF64bB97a73bb51E115Aa89C17FfA8dD167' │ 'kokoa-finance' │ 'oUSDT' │ 'Klaytn' │   0   │   353850.322643    │      0.75       │     6.06      │   353850.322643    │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 283408.95547619497 │ 0.9  │   'KSD'    │
    │    4    │ '0xFe41102f325dEaa9F303fDd9484Eb5911a7BA557' │ 'kokoa-finance' │ 'oORC'  │ 'Klaytn' │   0   │ 335150.06729676854 │      0.75       │     4.98      │ 335150.06729676854 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 142196.8372446199  │ 0.6  │   'KSD'    │
    │    5    │ '0x029e2A1B2bb91B66bd25027E1C211E5628dbcb93' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 91005.82357351514  │      0.75       │     -0.22     │ 91005.82357351514  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 55734.80035692681  │ 0.75 │   'KSD'    │
    │    6    │ '0x2E9269B718cc816De6A9E3C27E5bdb0F6A01b0ac' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 62672.77927976107  │      0.75       │     5.88      │ 62672.77927976107  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │  49032.7879072318  │ 0.9  │   'KSD'    │
    │    7    │ '0x16D0e1fBD024c600Ca0380A4C5D57Ee7a2eCBf9c' │ 'kokoa-finance' │ 'oWBTC' │ 'Klaytn' │   0   │ 57082.22492621314  │      0.75       │      10       │ 57082.22492621314  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 14108.402096344826 │ 0.6  │   'KSD'    │
    │    8    │ '0x34d21b1e550D73cee41151c77F3c73359527a396' │ 'kokoa-finance' │ 'oETH'  │ 'Klaytn' │   0   │ 53203.29815377932  │      0.75       │     6.03      │ 53203.29815377932  │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 19516.170288059657 │ 0.6  │   'KSD'    │
    │    9    │ '0xc320066b25B731A11767834839Fe57f9b2186f84' │ 'kokoa-finance' │ 'KSLP'  │ 'Klaytn' │   0   │ 30412.570486958797 │      0.75       │      10       │ 30412.570486958797 │ [ '0xb15183d0d4d5e86ba702ce9bb7b633376e7db29f' ] │ 25289.125622404845 │ 0.9  │   'KSD'    │
    └─────────┴──────────────────────────────────────────────┴─────────────────┴─────────┴──────────┴───────┴────────────────────┴─────────────────┴───────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────┴──────┴────────────┘

**Pull request merged**
