### PR TITLE
Add rhino.fi yield adaptor

### PR DESCRIPTION
**Pull request by Matko95**
Added rhino.fi yields to DeFiLlama Yields Dashboard. rhino.fi is a DeFi aggregator that aggregates yield across multiple chains.

### CODE REVIEW

**Comment by llamatester** [comment]
The rhino.fi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       54 passed, 54 total
    Snapshots:   0 total
    Time:        0.482 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────┬────────────┬────────────┬────────────────────┬────────────────────┬───────────────────┬────────────────────────────────────────────────┐
    │ (index) │                              pool                              │   chain    │  project   │       tvlUsd       │      apyBase       │      symbol       │                      url                       │
    ├─────────┼────────────────────────────────────────────────────────────────┼────────────┼────────────┼────────────────────┼────────────────────┼───────────────────┼────────────────────────────────────────────────┤
    │    0    │ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 10587435773.619482 │ 4.916734426492164  │     'WSTETH'      │      'https://app.rhino.fi/invest/WSTETH'      │
    │    1    │ '0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 237192564.5181568  │ 1.7639780566834615 │      'CUSDT'      │      'https://app.rhino.fi/invest/CUSDT'       │
    │    2    │ '0x9ee91f9f426fa633d227f7a9b000e28b9dfd8599-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 91607354.15163656  │        4.21        │     'STMATIC'     │     'https://app.rhino.fi/invest/STMATIC'      │
    │    3    │ '0x7c07f7abe10ce8e33dc6c5ad68fe033085256a84-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │      19736577      │ 6.431913908748049  │      'ICETH'      │      'https://app.rhino.fi/invest/ICETH'       │
    │    4    │ '0x3b27f92c0e212c671ea351827edf93db27cc0c65-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 17684911.820746116 │ 2.5682880933211916 │     'YVUSDT'      │      'https://app.rhino.fi/invest/YVUSDT'      │
    │    5    │ '0x1c480521100c962f7da106839a5a504b5a7457a1-polygon-rhino.fi'  │ 'Polygon'  │ 'rhino.fi' │     6167055.88     │ 6.202629273925631  │ 'mooStargateUSDT' │ 'https://app.rhino.fi/invest/mooStargateUSDT'  │
    │    6    │ '0xd496ea90a454ea49e30a8fd9e053c186d4fc897d-arbitrum-rhino.fi' │ 'Arbitrum' │ 'rhino.fi' │     1022508.62     │ 4.056272404099581  │ 'mooStargateUSDC' │ 'https://app.rhino.fi/invest/mooStargateUSDC'  │
    │    7    │ '0x341c05c0e9b33c0e38d64de76516b2ce970bb3be-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │       885797       │ 4.347652503568831  │      'DSETH'      │      'https://app.rhino.fi/invest/DSETH'       │
    │    8    │ '0x6b7f87279982d919bbf85182ddeab179b366d8f2-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │   140644.325684    │ 1.624749493741278  │   'ETHBTCTREND'   │  'https://app.rhino.fi/strategy/ETHBTCTREND'   │
    │    9    │ '0x6e2dac3b9e9adc0cbbae2d0b9fd81952a8d33872-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │    80138.896659    │ 13.962751741799945 │ 'ETHBTCMOMENTUM'  │ 'https://app.rhino.fi/strategy/ETHBTCMOMENTUM' │
    └─────────┴────────────────────────────────────────────────────────────────┴────────────┴────────────┴────────────────────┴────────────────────┴───────────────────┴────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
henlo, ty for adding.
- we no longer accept api adapters, pls refactor using on chain calls/subgraph
- tvl seems wrong,needs to be in usd

**Comment by slasher125** [comment]
yes, that is an ok compromise

**Comment by llamatester** [comment]
The rhino.fi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       44 passed, 44 total
    Snapshots:   0 total
    Time:        0.331 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────────┬────────────┬────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────────────────────────────────┐
    │ (index) │                              pool                              │   chain    │  project   │       tvlUsd       │      apyBase       │      symbol       │                      url                      │
    ├─────────┼────────────────────────────────────────────────────────────────┼────────────┼────────────┼────────────────────┼────────────────────┼───────────────────┼───────────────────────────────────────────────┤
    │    0    │ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 1393853.8941880981 │ 4.0288405256609705 │     'WSTETH'      │     'https://app.rhino.fi/invest/WSTETH'      │
    │    1    │ '0x3b27f92c0e212c671ea351827edf93db27cc0c65-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 656820.6588716945  │ 2.3500235351810117 │     'YVUSDT'      │     'https://app.rhino.fi/invest/YVUSDT'      │
    │    2    │ '0x7c07f7abe10ce8e33dc6c5ad68fe033085256a84-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 336779.4105828108  │ 4.046499942780419  │      'ICETH'      │      'https://app.rhino.fi/invest/ICETH'      │
    │    3    │ '0x9ee91f9f426fa633d227f7a9b000e28b9dfd8599-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 330983.2809146466  │        4.21        │     'STMATIC'     │     'https://app.rhino.fi/invest/STMATIC'     │
    │    4    │ '0x1c480521100c962f7da106839a5a504b5a7457a1-polygon-rhino.fi'  │ 'Polygon'  │ 'rhino.fi' │ 315425.21302545496 │ 6.133201589995907  │ 'mooStargateUSDT' │ 'https://app.rhino.fi/invest/mooStargateUSDT' │
    │    5    │ '0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 192962.68019365464 │ 1.923122438846815  │      'CUSDT'      │      'https://app.rhino.fi/invest/CUSDT'      │
    │    6    │ '0x341c05c0e9b33c0e38d64de76516b2ce970bb3be-ethereum-rhino.fi' │ 'Ethereum' │ 'rhino.fi' │ 36427.399999999994 │ 3.8883975304579717 │      'DSETH'      │      'https://app.rhino.fi/invest/DSETH'      │
    │    7    │ '0xd496ea90a454ea49e30a8fd9e053c186d4fc897d-arbitrum-rhino.fi' │ 'Arbitrum' │ 'rhino.fi' │ 2838.4903118836974 │ 3.8627011396000555 │ 'mooStargateUSDC' │ 'https://app.rhino.fi/invest/mooStargateUSDC' │
    └─────────┴────────────────────────────────────────────────────────────────┴────────────┴────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
