### PR TITLE
add Steer pools yield

### PR DESCRIPTION
**Pull request by MustafaBrandon**

### CODE REVIEW

**Comment by llamatester** [comment]
The steer-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       202 passed, 202 total
    Snapshots:   0 total
    Time:        0.405 s
    Ran all test suites.
    
    Nb of pools: 33
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────┬──────────────┬────────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project      │    symbol    │       tvlUsd       │ apyBase │                                        underlyingTokens                                        │         poolMeta         │                                         url                                          │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────┼──────────────┼────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x01476fcca94502267008119b83cea234dc3fa7d7-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'WETH-USDC'  │ 4460.940376576756  │  0.84   │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x5/vault/0x01476fcca94502267008119b83cea234dc3fa7d7' │
    │    1    │ '0x4bdf9b746c3263a066c43aadb982443051593c27-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'RDPX-WETH'  │ 37.40022590756597  │  0.18   │ [ '0x32eb7902d4134bf98a28b963d26de779af92a212', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x5/vault/0x4bdf9b746c3263a066c43aadb982443051593c27' │
    │    2    │ '0x5173819b99ad82ae6457f4e783152c509ccc9043-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │  'WETH-ARB'  │ 7006.198628357005  │  2.84   │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x4/vault/0x5173819b99ad82ae6457f4e783152c509ccc9043' │
    │    3    │ '0x53148ff4f38d2b7c3cc7f1549b9ca4dd660211b8-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'RDNT-WETH'  │ 67.65557546949503  │    0    │ [ '0x3082cc23568ea640225c2467653db90e9250aaa0', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x2/vault/0x53148ff4f38d2b7c3cc7f1549b9ca4dd660211b8' │
    │    4    │ '0x5dbad371890c3a89f634e377c1e8df987f61fb64-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'USDT-USDC'  │         0          │    0    │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x3/vault/0x5dbad371890c3a89f634e377c1e8df987f61fb64' │
    │    5    │ '0x731d2d33fcca3f6bfe85411c94f3cfcdf95e998a-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │  'WETH-ARB'  │ 127.70939610691025 │  1.65   │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'MultiPositionUniswapV3' │ 'https://app.steer.finance/app/0x4/vault/0x731d2d33fcca3f6bfe85411c94f3cfcdf95e998a' │
    │    6    │ '0xd11c84643229fc5ee0745f61f6277a7e8a746e9b-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'MAGIC-WETH' │ 46.139209180519366 │  0.71   │ [ '0x539bde0d7dbd336b79148aa742883198bbf60342', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │   'MultiPositionSushi'   │ 'https://app.steer.finance/app/0x4/vault/0xd11c84643229fc5ee0745f61f6277a7e8a746e9b' │
    │    7    │ '0xd622ec0d2ed483f65202208c33c816e7ce6f613d-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'WETH-USDC'  │ 120.65657453775285 │  0.64   │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'MultiPositionUniswapV3' │ 'https://app.steer.finance/app/0x2/vault/0xd622ec0d2ed483f65202208c33c816e7ce6f613d' │
    │    8    │ '0xe320e58432391ac1de6beee19b0c5c96426d84fc-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'WBTC-WETH'  │ 121.31896354600782 │    0    │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'MultiPositionUniswapV3' │ 'https://app.steer.finance/app/0x2/vault/0xe320e58432391ac1de6beee19b0c5c96426d84fc' │
    │    9    │ '0xfe9fd82c9e53c00cf729893f889c02c0a128b1d4-arbitrum' │ 'Arbitrum' │ 'steer-protocol' │ 'USDT-USDC'  │   120.353071087    │  0.02   │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'MultiPositionUniswapV3' │ 'https://app.steer.finance/app/0x3/vault/0xfe9fd82c9e53c00cf729893f889c02c0a128b1d4' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────┴──────────────┴────────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding.
- i just checked the weth-usdc pool on https://app.steer.finance/app/0x5/vault/0x01476fcca94502267008119b83cea234dc3fa7d7 and tvl seems to be around 10k usd. and apy values is also very different

**Comment by MustafaBrandon** [comment]
Hey @slasher125 thanks for your time,
the lower apy referenced some deprecated subgraph code dapp side and has been removed
if the values are reading 0, try connecting a wallet and switching to the right network

were the values you were seeing null or just completely different?

**Comment by slasher125** [comment]
they are different. for example: 
steer


vs

```
  {
    pool: '0x01476fcca94502267008119b83cea234dc3fa7d7-arbitrum',
    chain: 'Arbitrum',
    project: 'steer-protocol',
    symbol: 'WETH-USDC',
    tvlUsd: 10052.550528117843,
    apyBase: 1.13,
    underlyingTokens: [
      '0x82af49447d8a07e3bd95bd0d56f35241523fbab1',
      '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8'
    ],
    poolMeta: 'MultiPositionSushi',
    url: 'https://app.steer.finance/app/0x5/vault/0x01476fcca94502267008119b83cea234dc3fa7d7'
  },```

**Comment by MustafaBrandon** [comment]
@slasher125 the dapp is updated to show apys now determined from the past week's worth of data, instead of averaged lifetime returns, they should all sync now

**Pull request merged**
