### PR TITLE
Add DSF.Finance Adapter

### PR DESCRIPTION
**Pull request by dsf-cto**
This Pull Request adds an adapter for DSF.Finance in the src/adaptors/dsf.finance directory. The adapter provides APY and TVL data for the DSF.Finance protocol. It fetches information via the DSF API and conforms to the required format for yield data adapters.

Project: DSF.Finance
Chain: Ethereum
TVL and APY data are fetched from https://api2.dsf.finance/api/total-apy-tvl.
Project URL: https://dsf.finance/
Adapter tested locally, all tests passed successfully.
This addition will allow DefiLlama users to see yield information for DSF.Finance.

Thank you for reviewing this PR.

### CODE REVIEW

**Comment by llamatester** [comment]
The dsf.finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.264 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────────┬────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │     symbol      │ tvlUsd │    apy    │ rewardTokens │                                                               underlyingTokens                                                               │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────────┼────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x22586ea4fdaa9ef012581109b336f0124530ae69-ethereum' │ 'Ethereum' │ 'dsf.finance' │ 'USDT-USDC-DAI' │ 574323 │ 14.574831 │     null     │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7', '0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0x6B175474e89094C44Da98b954EedeAC495271d0F' ] │ 'https://app.dsf.finance/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────────┴────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by slasher125** [comment]
gm,
- how is the yield generated, whats the strategy?
- pls fetch data from on chain calls

**Comment by dsf-cto** [comment]
Hello, thank you for your feedback!

Yield Generation: Currently, we derive our APY data from DefiLlama's API and adjust it by subtracting 15% to account for our fee structure. In the future, we plan to implement additional strategies, such as crvUSD. Given this planned expansion, we found that aggregating yield data through our own API would be a scalable solution for managing multiple strategies in one place.

On-Chain Data Fetching: Regarding TVL, we agree with fetching this data directly from smart contracts on Ethereum, and we will make the necessary adjustments to implement on-chain calls for TVL.

Thank you again for the suggestions! We’ll proceed with these updates and keep you informed.

**Comment by llamatester** [comment]
The dsf.finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.257 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────────┬──────────────────┬────────────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │     symbol      │      tvlUsd      │        apy         │ rewardTokens │                                                               underlyingTokens                                                               │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────────┼──────────────────┼────────────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x22586ea4fdaa9ef012581109b336f0124530ae69-ethereum' │ 'Ethereum' │ 'dsf.finance' │ 'USDT-USDC-DAI' │ 574409.225859752 │ 13.834939999999998 │     null     │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7', '0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0x6B175474e89094C44Da98b954EedeAC495271d0F' ] │ 'https://app.dsf.finance/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────────┴──────────────────┴────────────────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by dsf-cto** [comment]
> gm,
> 
> * how is the yield generated, whats the strategy?
> * pls fetch data from on chain calls

Good morning Sir,

We have fulfilled your requirements regarding the DSF.Finance adapter for DefiLlama. The yield is now calculated using your API (https://yields.llama.fi/chart/8a20c472-142c-4442-b724-40f2183c073e) for the stablecoin strategy of the 3crv-MIM pool (Curve Finance and Convex Finance), as you recommended. DSF.Finance operates on the Ethereum network.

On-Chain Data Fetching
Following your requirements, we have implemented on-chain calls to retrieve TVL data directly from the DSF smart contract.

We appreciate your guidance and attention to detail. Please let us know if any further adjustments are needed.

Thank you for considering our request.

**Comment by llamatester** [comment]
The dsf.finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.262 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────────┬───────────────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │     symbol      │      tvlUsd       │    apy    │ rewardTokens │                                                               underlyingTokens                                                               │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────────┼───────────────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x22586ea4fdaa9ef012581109b336f0124530ae69-ethereum' │ 'Ethereum' │ 'dsf.finance' │ 'USDT-USDC-DAI' │ 587277.5025185519 │ 17.771596 │     null     │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7', '0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0x6B175474e89094C44Da98b954EedeAC495271d0F' ] │ 'https://app.dsf.finance/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────────┴───────────────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by slasher125** [comment]
so you guys are just depositing funds into convex mim-3rcv?
pls add that info to poolMeta
are funds locked for a certain duration?

**Comment by dsf-cto** [comment]
Yes Sir, the strategy currently involves depositing funds into the Convex MIM-3CRV pool to optimize yields for stablecoins. We will update the adapter to include this information in the poolMeta field.

**Additional Information:**

- poolMeta: The poolMeta field will explicitly mention that funds are deposited into the Convex MIM-3CRV pool.

- Fund Locking: No, funds are not locked for a specific duration. Users can withdraw their funds at any time without restrictions.

- Future Plans: In the future, we plan to expand the strategy by adding liquidity pools such as crvUSD, further diversifying the yield generation approach.

- DeFi Accessibility: Our platform focuses on democratizing DeFi through one-click solutions, simplifying access for both advanced and novice users, making secure and efficient yield strategies more accessible.

We will make these updates to the adapter and submit them shortly. Please let us know if any additional changes are required.

Thank you!

**Comment by llamatester** [comment]
The dsf.finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.247 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────────┬───────────────────┬────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │     symbol      │      tvlUsd       │    apy     │ rewardTokens │                                                               underlyingTokens                                                               │        poolMeta        │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────────┼───────────────────┼────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────┼────────────────────────────┤
    │    0    │ '0x22586ea4fdaa9ef012581109b336f0124530ae69-ethereum' │ 'Ethereum' │ 'dsf.finance' │ 'USDT-USDC-DAI' │ 587453.9253108519 │ 20.5460045 │     null     │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7', '0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0x6B175474e89094C44Da98b954EedeAC495271d0F' ] │ 'Convex MIM-3CRV pool' │ 'https://app.dsf.finance/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────────┴───────────────────┴────────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────┴────────────────────────────┘

**Pull request merged**
