### PR TITLE
Add xToken adaptor

### PR DESCRIPTION
**Pull request by buidler1337**

### CODE REVIEW

**Comment by llamatester** [comment]
The xtoken adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       375 passed, 375 total
    Snapshots:   0 total
    Time:        0.635 s
    Ran all test suites.
    
    Nb of pools: 53
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬────────────────────┬────────────────────┬─────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │ project  │       symbol       │       tvlUsd       │ apy │                                          rewardTokens                                          │                                        underlyingTokens                                        │                                               url                                                │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼────────────────────┼────────────────────┼─────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x6148a1BD2BE586E981115F9C0b16a09bBc271e2c-ethereum' │ 'Ethereum' │ 'xtoken' │  '20SML025<>USDC'  │    8040925603.4    │  0  │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0x0e84296da31b6c475afc1a991db05e79633e67b0', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x6148a1BD2BE586E981115F9C0b16a09bBc271e2c'  │
    │    1    │ '0x23031B28fC9fb87328c3Bc8713A5E00794154037-optimism' │ 'Optimism' │ 'xtoken' │    'USDC<>SUSD'    │ 2096314.6282314006 │ 14  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607', '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0x23031B28fC9fb87328c3Bc8713A5E00794154037' │
    │    2    │ '0xAA4927d5fe9E05BF69853431E86EE1722Da9910F-optimism' │ 'Optimism' │ 'xtoken' │   'WSTETH<>DAI'    │ 1265057.0550991874 │ 24  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb', '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0xAA4927d5fe9E05BF69853431E86EE1722Da9910F' │
    │    3    │ '0xd10240E6c39Fea0907fdfb3a91f2B6c7c8BD4516-optimism' │ 'Optimism' │ 'xtoken' │     'WETH<>OP'     │ 1094546.594628779  │ 28  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x4200000000000000000000000000000000000006', '0x4200000000000000000000000000000000000042' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0xd10240E6c39Fea0907fdfb3a91f2B6c7c8BD4516' │
    │    4    │ '0x9C2e1b372DB3671665d501838F30dFe3f259357C-ethereum' │ 'Ethereum' │ 'xtoken' │  '20SML025<>USDC'  │ 278295.0658991599  │ 23  │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0x0e84296da31b6c475afc1a991db05e79633e67b0', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x9C2e1b372DB3671665d501838F30dFe3f259357C'  │
    │    5    │ '0xeF408658Deb43f16926b8F81d2838F884762af50-ethereum' │ 'Ethereum' │ 'xtoken' │  'USDC<>18SML711'  │ 146564.6734577678  │  0  │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xfa08049ed4f27145767f2b7da08464fc0a7fad5d' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0xeF408658Deb43f16926b8F81d2838F884762af50'  │
    │    6    │ '0xc8b1039928a98d7a272F6942d86814Ed9D8f9f17-ethereum' │ 'Ethereum' │ 'xtoken' │   'KNIGHT<>WETH'   │ 142290.42738535578 │ 19  │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0xc8b1039928a98d7a272F6942d86814Ed9D8f9f17'  │
    │    7    │ '0x9b36d76a7ae6C9AaAED5FB2248670612363f036e-optimism' │ 'Optimism' │ 'xtoken' │     'OP<>USDC'     │ 56520.64340837695  │  0  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x4200000000000000000000000000000000000042', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0x9b36d76a7ae6C9AaAED5FB2248670612363f036e' │
    │    8    │ '0x1B19801D5634815c187b9E613de7101eEb7c1370-ethereum' │ 'Ethereum' │ 'xtoken' │  'FY-RETH<>RETH'   │ 38424.91810099972  │  0  │ [ '0xb1f1f47061a7be15c69f378cb3f69423bd58f2f8', '0xb8dfbe158d699e306a5c338f3cdb722ac3b7fb2d' ] │ [ '0x4588ef44721aef888f34e69caaf437733b437756', '0xae78736cd615f374d3085123a210448e74fc6393' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x1B19801D5634815c187b9E613de7101eEb7c1370'  │
    │    9    │ '0x3f96C580436dD59404Ba612bf6D8079Dc10f6f7E-arbitrum' │ 'Arbitrum' │ 'xtoken' │ 'FSGLP-907A<>USDC' │ 26582.272969413003 │ 161 │                        [ '0xc628534100180582e43271448098cb2c185795bd' ]                        │ [ '0x5028c667d1c9da0a9090f16e1607f60b7717fc6a', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://app.xtokenterminal.io/mining/pools/arbitrum/0x3f96C580436dD59404Ba612bf6D8079Dc10f6f7E' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴────────────────────┴────────────────────┴─────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding:
- in symbol, replace `<>` with `-`
- the first pool `'20SML025<>USDC'` tvl doesn't seem to be right
- any reason the apy is rounded? if possible better to not round so we get more precision
- for pools which require vesting, add `poolMeta: '8 Weeks vesting'` etc
- if the apy is coming from rewards only, use `apyReward` instead and remove the `apy` field

**Comment by buidler1337** [comment]
> hi, ty for adding:
> 
> * in symbol, replace `<>` with `-`
> * the first pool `'20SML025<>USDC'` tvl doesn't seem to be right
> * any reason the apy is rounded? if possible better to not round so we get more precision
> * for pools which require vesting, add `poolMeta: '8 Weeks vesting'` etc
> * if the apy is coming from rewards only, use `apyReward` instead and remove the `apy` field

hi @slasher125, thank you for the clear review! 🙏  We just pushed fixes for all the checkpoints you mentioned.

**Comment by llamatester** [comment]
The xtoken adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       347 passed, 347 total
    Snapshots:   0 total
    Time:        0.517 s
    Ran all test suites.
    
    Nb of pools: 49
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬───────────────────┬────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                         pool                          │   chain    │ project  │      symbol       │       tvlUsd       │      apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │                                               url                                                │     poolMeta      │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼───────────────────┼────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────┤
    │    0    │ '0x23031B28fC9fb87328c3Bc8713A5E00794154037-optimism' │ 'Optimism' │ 'xtoken' │    'USDC-SUSD'    │ 2124552.963879588  │ 15.465819089637227  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x7f5c764cbc14f9669b88837ca1490cca17c31607', '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0x23031B28fC9fb87328c3Bc8713A5E00794154037' │                   │
    │    1    │ '0xAA4927d5fe9E05BF69853431E86EE1722Da9910F-optimism' │ 'Optimism' │ 'xtoken' │   'WSTETH-DAI'    │ 1268935.675748477  │ 25.893620720973168  │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb', '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0xAA4927d5fe9E05BF69853431E86EE1722Da9910F' │                   │
    │    2    │ '0xd10240E6c39Fea0907fdfb3a91f2B6c7c8BD4516-optimism' │ 'Optimism' │ 'xtoken' │     'WETH-OP'     │  1125629.7656211   │  29.1907275280553   │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x4200000000000000000000000000000000000006', '0x4200000000000000000000000000000000000042' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0xd10240E6c39Fea0907fdfb3a91f2B6c7c8BD4516' │                   │
    │    3    │ '0x9C2e1b372DB3671665d501838F30dFe3f259357C-ethereum' │ 'Ethereum' │ 'xtoken' │  '20SML025-USDC'  │ 277974.23354862526 │  23.0736272756766   │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0x0e84296da31b6c475afc1a991db05e79633e67b0', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x9C2e1b372DB3671665d501838F30dFe3f259357C'  │ '8 weeks vesting' │
    │    4    │ '0xeF408658Deb43f16926b8F81d2838F884762af50-ethereum' │ 'Ethereum' │ 'xtoken' │  'USDC-18SML711'  │ 146395.7076534168  │          0          │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xfa08049ed4f27145767f2b7da08464fc0a7fad5d' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0xeF408658Deb43f16926b8F81d2838F884762af50'  │ '8 weeks vesting' │
    │    5    │ '0xc8b1039928a98d7a272F6942d86814Ed9D8f9f17-ethereum' │ 'Ethereum' │ 'xtoken' │   'KNIGHT-WETH'   │ 142636.35529867373 │ 18.970290062559545  │                        [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc' ]                        │ [ '0x3541a5c1b04adaba0b83f161747815cd7b1516bc', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0xc8b1039928a98d7a272F6942d86814Ed9D8f9f17'  │ '8 weeks vesting' │
    │    6    │ '0x9b36d76a7ae6C9AaAED5FB2248670612363f036e-optimism' │ 'Optimism' │ 'xtoken' │     'OP-USDC'     │ 57944.65995980413  │          0          │                        [ '0x4200000000000000000000000000000000000042' ]                        │ [ '0x4200000000000000000000000000000000000042', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'https://app.xtokenterminal.io/mining/pools/optimism/0x9b36d76a7ae6C9AaAED5FB2248670612363f036e' │                   │
    │    7    │ '0x1B19801D5634815c187b9E613de7101eEb7c1370-ethereum' │ 'Ethereum' │ 'xtoken' │  'FY-RETH-RETH'   │ 38669.18205072728  │ 0.05145231435472956 │ [ '0xb1f1f47061a7be15c69f378cb3f69423bd58f2f8', '0xb8dfbe158d699e306a5c338f3cdb722ac3b7fb2d' ] │ [ '0x4588ef44721aef888f34e69caaf437733b437756', '0xae78736cd615f374d3085123a210448e74fc6393' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x1B19801D5634815c187b9E613de7101eEb7c1370'  │ '6 weeks vesting' │
    │    8    │ '0x3f96C580436dD59404Ba612bf6D8079Dc10f6f7E-arbitrum' │ 'Arbitrum' │ 'xtoken' │ 'FSGLP-907A-USDC' │ 26542.333445983644 │ 151.55264033104083  │                        [ '0xc628534100180582e43271448098cb2c185795bd' ]                        │ [ '0x5028c667d1c9da0a9090f16e1607f60b7717fc6a', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ 'https://app.xtokenterminal.io/mining/pools/arbitrum/0x3f96C580436dD59404Ba612bf6D8079Dc10f6f7E' │                   │
    │    9    │ '0x3baA43d7aB0dFE3bcC77DEBfF8Fa0DF33aBEDB87-ethereum' │ 'Ethereum' │ 'xtoken' │  'FY-RETH-RETH'   │ 21217.376225991655 │  947.2029199193038  │ [ '0xb1f1f47061a7be15c69f378cb3f69423bd58f2f8', '0xb8dfbe158d699e306a5c338f3cdb722ac3b7fb2d' ] │ [ '0x4588ef44721aef888f34e69caaf437733b437756', '0xae78736cd615f374d3085123a210448e74fc6393' ] │ 'https://app.xtokenterminal.io/mining/pools/mainnet/0x3baA43d7aB0dFE3bcC77DEBfF8Fa0DF33aBEDB87'  │                   │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴───────────────────┴────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
