### PR TITLE
feat: connext yield adapter

### PR DESCRIPTION
**Pull request by rhlsthrm**
Add Connext pool yields.

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running connext adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 59 passed, 60 total
    Snapshots:   0 total
    Time:        0.294 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬─────────────────┬─────────────────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬───────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │  project  │     symbol      │       apyBase       │ apyReward │ rewardTokens │                                        underlyingTokens                                        │       tvlUsd       │                          url                          │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼─────────────────┼─────────────────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼───────────────────────────────────────────────────────┤
    │    0    │ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1-arbitrum' │ 'Arbitrum' │ 'connext' │ 'WETH-nextWETH' │ 26.447322945904794  │     0     │      []      │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0x2983bf5c334743Aa6657AD70A55041d720d225dB' ] │ 2947069.983993066  │ 'https://bridge.connext.network/pool/ETH-on-arbitrum' │
    │    1    │   '0x2170Ed0880ac9A755fd29B2688956BD959F933F8-bsc'    │ 'Binance'  │ 'connext' │ 'WETH-nextWETH' │  5.231812967285121  │     0     │      []      │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xA9CB51C666D2AF451d87442Be50747B31BB7d805' ] │ 2230971.839839347  │ 'https://bridge.connext.network/pool/ETH-on-binance'  │
    │    2    │  '0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1-gnosis'  │  'Gnosis'  │ 'connext' │ 'WETH-nextWETH' │ 0.28818293589705224 │     0     │      []      │ [ '0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1', '0x538E2dDbfDf476D24cCb1477A518A82C9EA81326' ] │ 2183770.6503985412 │  'https://bridge.connext.network/pool/ETH-on-gnosis'  │
    │    3    │ '0x4200000000000000000000000000000000000006-optimism' │ 'Optimism' │ 'connext' │ 'WETH-nextWETH' │ 0.5019855579631471  │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xbAD5B3c68F855EaEcE68203312Fd88AD3D365e50' ] │ 829359.0091009096  │ 'https://bridge.connext.network/pool/ETH-on-optimism' │
    │    4    │ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619-polygon'  │ 'Polygon'  │ 'connext' │ 'WETH-nextWETH' │  2.598841411322028  │     0     │      []      │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619', '0x4b8BaC8Dd1CAA52E32C07755c17eFadeD6A0bbD0' ] │  374039.225518536  │ 'https://bridge.connext.network/pool/ETH-on-polygon'  │
    │    5    │  '0x420000000000000000000000000000000000000a-metis'   │  'Metis'   │ 'connext' │ 'WETH-nextWETH' │  3.922526264466475  │     0     │      []      │ [ '0x420000000000000000000000000000000000000a', '0x3883B5Bdd61BA1b687de69eE50c9738D5ec501E9' ] │ 339196.97555992304 │  'https://bridge.connext.network/pool/ETH-on-metis'   │
    │    6    │   '0x4200000000000000000000000000000000000006-base'   │   'Base'   │ 'connext' │ 'WETH-nextWETH' │ 15.134383517575056  │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xE08D4907b2C7aa5458aC86596b6D17B1feA03F7E' ] │ 170696.42666978596 │   'https://bridge.connext.network/pool/ETH-on-base'   │
    │    7    │  '0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f-linea'   │  'Linea'   │ 'connext' │ 'WETH-nextWETH' │ 1.2369840077530059  │     0     │      []      │ [ '0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f', '0x0573AD07cA4f74757e5B2417Bf225BEbeBcF66D9' ] │ 116013.87112691235 │  'https://bridge.connext.network/pool/ETH-on-linea'   │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴─────────────────┴─────────────────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴───────────────────────────────────────────────────────┘
    }

**Comment by llamatester** [comment]
The connext adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.264 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬─────────────────┬────────────────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬───────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │  project  │     symbol      │      apyBase       │ apyReward │ rewardTokens │                                        underlyingTokens                                        │       tvlUsd       │                          url                          │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼─────────────────┼────────────────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼───────────────────────────────────────────────────────┤
    │    0    │ '0x2983bf5c334743Aa6657AD70A55041d720d225dB-arbitrum' │ 'Arbitrum' │ 'connext' │ 'WETH-nextWETH' │ 26.099650523461836 │     0     │      []      │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0x2983bf5c334743Aa6657AD70A55041d720d225dB' ] │ 2934958.9352605995 │ 'https://bridge.connext.network/pool/ETH-on-arbitrum' │
    │    1    │   '0xA9CB51C666D2AF451d87442Be50747B31BB7d805-bsc'    │ 'Binance'  │ 'connext' │ 'WETH-nextWETH' │ 4.746208655634954  │     0     │      []      │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xA9CB51C666D2AF451d87442Be50747B31BB7d805' ] │ 2221796.2290003058 │ 'https://bridge.connext.network/pool/ETH-on-binance'  │
    │    2    │  '0x538E2dDbfDf476D24cCb1477A518A82C9EA81326-gnosis'  │  'Gnosis'  │ 'connext' │ 'WETH-nextWETH' │ 0.2338725450437451 │     0     │      []      │ [ '0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1', '0x538E2dDbfDf476D24cCb1477A518A82C9EA81326' ] │ 2174788.426743797  │  'https://bridge.connext.network/pool/ETH-on-gnosis'  │
    │    3    │ '0xbAD5B3c68F855EaEcE68203312Fd88AD3D365e50-optimism' │ 'Optimism' │ 'connext' │ 'WETH-nextWETH' │ 0.4907891179570134 │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xbAD5B3c68F855EaEcE68203312Fd88AD3D365e50' ] │ 825947.7372303234  │ 'https://bridge.connext.network/pool/ETH-on-optimism' │
    │    4    │ '0x4b8BaC8Dd1CAA52E32C07755c17eFadeD6A0bbD0-polygon'  │ 'Polygon'  │ 'connext' │ 'WETH-nextWETH' │ 2.4739217444568196 │     0     │      []      │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619', '0x4b8BaC8Dd1CAA52E32C07755c17eFadeD6A0bbD0' ] │ 372500.50818429806 │ 'https://bridge.connext.network/pool/ETH-on-polygon'  │
    │    5    │  '0x3883B5Bdd61BA1b687de69eE50c9738D5ec501E9-metis'   │  'Metis'   │ 'connext' │ 'WETH-nextWETH' │ 3.922526264466475  │     0     │      []      │ [ '0x420000000000000000000000000000000000000a', '0x3883B5Bdd61BA1b687de69eE50c9738D5ec501E9' ] │ 337801.8019827409  │  'https://bridge.connext.network/pool/ETH-on-metis'   │
    │    6    │   '0xE08D4907b2C7aa5458aC86596b6D17B1feA03F7E-base'   │   'Base'   │ 'connext' │ 'WETH-nextWETH' │ 12.529795867544635 │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xE08D4907b2C7aa5458aC86596b6D17B1feA03F7E' ] │ 169994.5281563719  │   'https://bridge.connext.network/pool/ETH-on-base'   │
    │    7    │  '0x0573AD07cA4f74757e5B2417Bf225BEbeBcF66D9-linea'   │  'Linea'   │ 'connext' │ 'WETH-nextWETH' │ 1.2395397956479481 │     0     │      []      │ [ '0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f', '0x0573AD07cA4f74757e5B2417Bf225BEbeBcF66D9' ] │ 115536.75148039272 │  'https://bridge.connext.network/pool/ETH-on-linea'   │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴─────────────────┴────────────────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴───────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hey sir, ty for adding. pls fetch as much data as possible from on chain calls or subgraphs instead of a centralised api

**Comment by rhlsthrm** [comment]
@slasher125 I looked at Hop adapters for reference (since our pools work similarly), and it uses centralized APIs to fetch the data as well.

**Comment by llamatester** [comment]
The connext adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.276 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬─────────────────┬────────────────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬───────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │  project  │     symbol      │      apyBase       │ apyReward │ rewardTokens │                                        underlyingTokens                                        │       tvlUsd       │                          url                          │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼─────────────────┼────────────────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼───────────────────────────────────────────────────────┤
    │    0    │ '0x2983bf5c334743Aa6657AD70A55041d720d225dB-arbitrum' │ 'Arbitrum' │ 'connext' │ 'WETH-nextWETH' │ 26.283426225600603 │     0     │      []      │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0x2983bf5c334743Aa6657AD70A55041d720d225dB' ] │ 2932616.2297180956 │ 'https://bridge.connext.network/pool/ETH-on-arbitrum' │
    │    1    │   '0xA9CB51C666D2AF451d87442Be50747B31BB7d805-bsc'    │ 'Binance'  │ 'connext' │ 'WETH-nextWETH' │ 3.942856935286998  │     0     │      []      │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8', '0xA9CB51C666D2AF451d87442Be50747B31BB7d805' ] │ 2219955.727987759  │ 'https://bridge.connext.network/pool/ETH-on-binance'  │
    │    2    │  '0x538E2dDbfDf476D24cCb1477A518A82C9EA81326-gnosis'  │  'Gnosis'  │ 'connext' │ 'WETH-nextWETH' │ 0.3041264926991083 │     0     │      []      │ [ '0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1', '0x538E2dDbfDf476D24cCb1477A518A82C9EA81326' ] │ 2172929.3630913454 │  'https://bridge.connext.network/pool/ETH-on-gnosis'  │
    │    3    │ '0xbAD5B3c68F855EaEcE68203312Fd88AD3D365e50-optimism' │ 'Optimism' │ 'connext' │ 'WETH-nextWETH' │ 0.6595823733916761 │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xbAD5B3c68F855EaEcE68203312Fd88AD3D365e50' ] │ 825282.4871879723  │ 'https://bridge.connext.network/pool/ETH-on-optimism' │
    │    4    │ '0x4b8BaC8Dd1CAA52E32C07755c17eFadeD6A0bbD0-polygon'  │ 'Polygon'  │ 'connext' │ 'WETH-nextWETH' │ 2.471977277235249  │     0     │      []      │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619', '0x4b8BaC8Dd1CAA52E32C07755c17eFadeD6A0bbD0' ] │ 372189.4692405415  │ 'https://bridge.connext.network/pool/ETH-on-polygon'  │
    │    5    │  '0x3883B5Bdd61BA1b687de69eE50c9738D5ec501E9-metis'   │  'Metis'   │ 'connext' │ 'WETH-nextWETH' │ 3.5514679653003256 │     0     │      []      │ [ '0x420000000000000000000000000000000000000a', '0x3883B5Bdd61BA1b687de69eE50c9738D5ec501E9' ] │ 337515.82965625083 │  'https://bridge.connext.network/pool/ETH-on-metis'   │
    │    6    │   '0xE08D4907b2C7aa5458aC86596b6D17B1feA03F7E-base'   │   'Base'   │ 'connext' │ 'WETH-nextWETH' │ 10.587958254111939 │     0     │      []      │ [ '0x4200000000000000000000000000000000000006', '0xE08D4907b2C7aa5458aC86596b6D17B1feA03F7E' ] │ 169851.01283896278 │   'https://bridge.connext.network/pool/ETH-on-base'   │
    │    7    │  '0x0573AD07cA4f74757e5B2417Bf225BEbeBcF66D9-linea'   │  'Linea'   │ 'connext' │ 'WETH-nextWETH' │ 1.2274446083631485 │     0     │      []      │ [ '0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f', '0x0573AD07cA4f74757e5B2417Bf225BEbeBcF66D9' ] │ 115439.2704472072  │  'https://bridge.connext.network/pool/ETH-on-linea'   │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴─────────────────┴────────────────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴───────────────────────────────────────────────────────┘

**Comment by rhlsthrm** [comment]
I totally understand. However this requires some changes on the subgraph side which will need to be slotted in. Can you please add the adapter now, and we will update it as soon as possible? We need this adapter urgently because we want to advertise the yield opportunities to help increase liquidity and balance the pools out.

**Pull request merged**
