### PR TITLE
OneRing APY adapter

### PR DESCRIPTION
**Pull request by lucasfernandes**
The adapter has been added to display the APY for LP USDC/DOLA staking farm pool within the OneRing Protocol on Optimism

### CODE REVIEW

**Comment by llamatester** [comment]
The onering-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.373 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬────────────────────────────┬───────────┬───────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │           symbol           │  tvlUsd   │        apyBase        │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼────────────────────────────┼───────────┼───────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x33ff52D1c4b6973CD5AF41ad53Dd92D99D31D3c3' │ 'optimism' │ 'onering-v2' │ 'StableV2 AMM - USDC/DOLA' │ 8391.5722 │ 152236073235477360000 │ [ '0x4200000000000000000000000000000000000042' ] │ [ '0xB720FBC32d60BB6dcc955Be86b98D8fD3c4bA645' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴────────────────────────────┴───────────┴───────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The onering-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.323 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬────────────────────────────┬───────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │           symbol           │  tvlUsd   │      apyBase      │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼────────────────────────────┼───────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x33ff52D1c4b6973CD5AF41ad53Dd92D99D31D3c3' │ 'optimism' │ 'onering-v2' │ 'StableV2 AMM - USDC/DOLA' │ 8391.5722 │ 150.0612721892563 │ [ '0x4200000000000000000000000000000000000042' ] │ [ '0xB720FBC32d60BB6dcc955Be86b98D8fD3c4bA645' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴────────────────────────────┴───────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, ty for adding:
- keep in mind we don't show pools below $10k
- symbol should be just USDC/DOLA, u can keep `StableV2 AMM` but put it under `poolMeta`
- reward rate should be pulled from contracts, not from centralised api
- same goes for tvl (rn u read from our api, but once u extend to multiple pools that won't work anymore, so better to fetch from chain)

**Comment by lucasfernandes** [comment]
Hey, gm! Thanks for the tips.
Will update the symbol as you suggested.
The reward rate was supposed to be in the event emission, but I forgot to add it, so I create an api in our dapp to serve it cuz the subgraph wouldn't solve it. Is there another way I can do it?
Got you about the tvl, need to think how to get this without use your api and my api =/
Any thoughts?

**Comment by lucasfernandes** [comment]
I could fetch from the contract directly but I will need to use a node rpc, is there a way this be hidden like an .env file?

**Comment by llamatester** [comment]
The onering-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.407 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │   symbol    │       tvlUsd       │      apyBase       │                   rewardTokens                   │                 underlyingTokens                 │    poolMeta    │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────┤
    │    0    │ '0x33ff52D1c4b6973CD5AF41ad53Dd92D99D31D3c3' │ 'optimism' │ 'onering-v2' │ 'USDC/DOLA' │ 10252.647565110145 │ 125.49197578763882 │ [ '0x4200000000000000000000000000000000000042' ] │ [ '0xB720FBC32d60BB6dcc955Be86b98D8fD3c4bA645' ] │ 'StableV2 AMM' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────┘

**Comment by llamatester** [comment]
The onering-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.319 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │   symbol    │       tvlUsd       │      apyBase       │                   rewardTokens                   │                 underlyingTokens                 │    poolMeta    │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────┤
    │    0    │ '0x33ff52D1c4b6973CD5AF41ad53Dd92D99D31D3c3' │ 'optimism' │ 'onering-v2' │ 'USDC/DOLA' │ 10252.647565110145 │ 125.49197578763882 │ [ '0x4200000000000000000000000000000000000042' ] │ [ '0xB720FBC32d60BB6dcc955Be86b98D8fD3c4bA645' ] │ 'StableV2 AMM' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────┘

**Comment by lucasfernandes** [comment]
Okay, just updated and the code is now pulling from on-chain contracts using your api. 
We're aware that it will be displayed only with min of 10k.

**Comment by llamatester** [comment]
The onering-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.328 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬─────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │   symbol    │       tvlUsd       │      apyBase       │                   rewardTokens                   │                 underlyingTokens                 │    poolMeta    │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼─────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────┤
    │    0    │ '0x33ff52D1c4b6973CD5AF41ad53Dd92D99D31D3c3' │ 'optimism' │ 'onering-v2' │ 'USDC/DOLA' │ 10253.516738346889 │ 126.37127661322785 │ [ '0x4200000000000000000000000000000000000042' ] │ [ '0xB720FBC32d60BB6dcc955Be86b98D8fD3c4bA645' ] │ 'StableV2 AMM' │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴─────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────┘

**Comment by lucasfernandes** [comment]
> gm, ty for adding:
> 
> - keep in mind we don't show pools below $10k
> 
> - symbol should be just USDC/DOLA, u can keep `StableV2 AMM` but put it under `poolMeta`
> 
> - reward rate should be pulled from contracts, not from centralised api
> 
> - same goes for tvl (rn u read from our api, but once u extend to multiple pools that won't work anymore, so better to fetch from chain)

Okay, just updated and the code is now pulling from on-chain contracts using your api.
Our TVL is now higher than 10k =D

**Pull request merged**
