### PR TITLE
3xcalibur yield adaptor

### PR DESCRIPTION
**Pull request by leez8**

### CODE REVIEW

**Comment by slasher125** [comment]
henlo & ty for adding
one thing:
pls refactor to on chain/subgraph calls instead of using the centralised api call. We are moving away from api adapters (see readme data sources)

**Comment by leez8** [comment]
@slasher125 understood. refactored

**Comment by llamatester** [comment]
The 3xcalibur adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.365 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │     symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │                                                                               url                                                                               │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x6345ccf4b1d4411789cd11411f146bfe3de14e8a' │ 'Arbitrum' │ '3xcalibur' │   'DAI-USDC'   │   984589.198336    │ 6.542209083837113  │ [ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0xda10009cbd5d07dd0cecc66161fc93d7c9000da1&asset1=0xff970a61a04b1ca14834a43f5de4533ebddb5cc8&stable=true'  │
    │    1    │ '0x2cc6ac1454490afa83333fabc84345fad751285b' │ 'Arbitrum' │ '3xcalibur' │  'XCAL-USDC'   │   684031.945778    │ 113.9889460954667  │ [ '0xd2568accd10a4c98e87c44e9920360031ad89fcb', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0xd2568accd10a4c98e87c44e9920360031ad89fcb&asset1=0xff970a61a04b1ca14834a43f5de4533ebddb5cc8&stable=false' │
    │    2    │ '0x3c94d5abcf49a2980d55721c35093210699c1493' │ 'Arbitrum' │ '3xcalibur' │  'WETH-USDC'   │   444359.688056    │ 19.535607124054792 │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&asset1=0xff970a61a04b1ca14834a43f5de4533ebddb5cc8&stable=false' │
    │    3    │ '0x06e83fb652bf899ff387fef1a446730018c4447f' │ 'Arbitrum' │ '3xcalibur' │ 'gmdUSDC-USDC' │   379484.052836    │ 15.992269061530989 │ [ '0x4a723de8af2be96292da3f824a96bfa053d4af66', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x4a723de8af2be96292da3f824a96bfa053d4af66&asset1=0xff970a61a04b1ca14834a43f5de4533ebddb5cc8&stable=true'  │
    │    4    │ '0x92176126ad10a9d850397d60ca6c70f45083c9bb' │ 'Arbitrum' │ '3xcalibur' │   'WETH-GMX'   │ 358780.87737389264 │ 33.21686515513123  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&asset1=0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a&stable=false' │
    │    5    │ '0xc8018bb68c50c5b259bfe5333ff204f3f71989cc' │ 'Arbitrum' │ '3xcalibur' │ 'WETH-gmdETH'  │ 246895.08993359798 │ 11.750383281108737 │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xc5182e92bf001bae7049c4496cad96662db1a186' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&asset1=0xc5182e92bf001bae7049c4496cad96662db1a186&stable=true'  │
    │    6    │ '0xf50c56b7515e516467442c7910818bca876e15b8' │ 'Arbitrum' │ '3xcalibur' │   'GMD-WETH'   │ 185527.13993919664 │ 103.36713766641515 │ [ '0x4945970efeec98d393b4b979b9be265a3ae28a8b', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x4945970efeec98d393b4b979b9be265a3ae28a8b&asset1=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&stable=false' │
    │    7    │ '0xfbd914e4f9ccec9749910f0968f3efbfcef7215b' │ 'Arbitrum' │ '3xcalibur' │   'DPX-WETH'   │ 173253.35106677777 │ 64.05613270935791  │ [ '0x6c2c06790b3e3e3c38e12ee22f8183b37a13ee55', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x6c2c06790b3e3e3c38e12ee22f8183b37a13ee55&asset1=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&stable=false' │
    │    8    │ '0xaae3e817cf669be16ab22c801c92021f1eb5852d' │ 'Arbitrum' │ '3xcalibur' │  'RDPX-WETH'   │ 172604.23812389275 │ 64.36163093046812  │ [ '0x32eb7902d4134bf98a28b963d26de779af92a212', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x32eb7902d4134bf98a28b963d26de779af92a212&asset1=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&stable=false' │
    │    9    │ '0x2ec0f6943911afad0f51b0dd3c5d36fdc34b29e0' │ 'Arbitrum' │ '3xcalibur' │  'JONES-WETH'  │ 167148.69497921717 │ 85.07441558412775  │ [ '0x10393c20975cf177a3513071bc110f7962cd67da', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xd2568acCD10A4C98e87c44E9920360031ad89fCB' ] │ 'https://app.3xcalibur.com/swap/liquidity/add?asset0=0x10393c20975cf177a3513071bc110f7962cd67da&asset1=0x82af49447d8a07e3bd95bd0d56f35241523fbab1&stable=false' │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
looking gud. one q: where can i see that yield data on the your UI?

**Comment by leez8** [comment]
@slasher125 here:
https://app.3xcalibur.com/swap/liquidity/add

**Pull request merged**
