### PR TITLE
feat: primex-finance arbitrum contracts

### PR DESCRIPTION
**Pull request by TbIKoBKa**

### CODE REVIEW

**Comment by llamatester** [comment]
The primex-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.285 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────┬──────────┬────────────────────┬──────────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┬───────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project      │  symbol  │       tvlUsd       │       apyBase        │     apyReward     │                   rewardTokens                   │                 underlyingTokens                 │                                                       url                                                        │   apyBaseBorrow   │  apyRewardBorrow  │   totalSupplyUsd   │   totalBorrowUsd   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────┼──────────┼────────────────────┼──────────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────┼───────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x0e28a9d0bed228981fec47b203611422717f9593-polygon'  │ 'Polygon'  │ 'primex-finance' │  'WETH'  │ 131006.78111590174 │ 0.011381646203778573 │ 914.2083180392906 │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 'https://app.primex.finance/#/bucket-details/0x0e28A9D0BEd228981feC47b203611422717f9593?network=polygon_mainnet' │ 2.317769507764167 │ 5944.11239654179  │ 131825.25989488556 │ 818.4787789838183  │
    │    1    │ '0x12c125181eb7c944eaefcb2ae881475870f0aff3-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'USDC.E' │ 86765.28972210603  │  0.7047873951528505  │ 84.54636763537968 │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 'https://app.primex.finance/#/bucket-details/0x12c125181Eb7c944EaEfcB2AE881475870f0Aff3?network=polygon_mainnet' │ 5.41970524775186  │ 353.9523830869908 │ 104076.7066161694  │ 17311.416894063368 │
    │    2    │ '0xc1c334ae711db9b83d03ec7c3a413d38b01826c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDT'  │    4000.662248     │          0           │        48         │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │  'https://app.primex.finance/#/bucket-details/0xC1C334AE711db9b83D03eC7C3a413D38b01826c5?network=arbitrum_one'   │         0         │         0         │    4000.662248     │         0          │
    │    3    │ '0x2fa0ba6d651b2306fbcb22797db0409bcf795f69-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDC'  │     2524.16675     │          0           │       46.5        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │  'https://app.primex.finance/#/bucket-details/0x2Fa0BA6d651B2306FBcB22797Db0409BcF795F69?network=arbitrum_one'   │         0         │         0         │     2524.16675     │         0          │
    │    4    │ '0x653a3bc43bd7b44ab875f56cc0db54865a48cb2b-arbitrum' │ 'Arbitrum' │ 'primex-finance' │ 'USDC.E' │        2500        │          0           │       46.5        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │  'https://app.primex.finance/#/bucket-details/0x653a3Bc43BD7B44Ab875F56cC0db54865a48CB2B?network=arbitrum_one'   │         0         │         0         │        2500        │         0          │
    │    5    │ '0x018b221753ef25da38e672e0d3747bd626ae2e71-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WETH'  │      1049.57       │          0           │       30.5        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │  'https://app.primex.finance/#/bucket-details/0x018b221753Ef25Da38e672e0D3747bD626ae2e71?network=arbitrum_one'   │         0         │         0         │      1049.57       │         0          │
    │    6    │ '0x9ab05967a764838f9c804c1e58b94524f2789808-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WBTC'  │ 659.1037038000001  │          0           │       8.25        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f' ] │  'https://app.primex.finance/#/bucket-details/0x9ab05967a764838f9C804C1e58b94524F2789808?network=arbitrum_one'   │         0         │         0         │ 659.1037038000001  │         0          │
    │    7    │ '0x76e7759445bb8028f725e8e795dadee8b209f6ac-polygon'  │ 'Polygon'  │ 'primex-finance' │  'USDT'  │         0          │          0           │        27         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ 'https://app.primex.finance/#/bucket-details/0x76e7759445BB8028f725e8E795DadeE8b209f6Ac?network=polygon_mainnet' │         0         │         0         │         0          │         0          │
    │    8    │ '0x6dd0028ba6945ee5b859d3c7fe89bcdec57b67af-polygon'  │ 'Polygon'  │ 'primex-finance' │  'WBTC'  │         0          │          0           │         8         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6' ] │ 'https://app.primex.finance/#/bucket-details/0x6dd0028bA6945Ee5B859D3C7fe89bCdec57B67Af?network=polygon_mainnet' │         0         │         0         │         0          │         0          │
    │    9    │ '0xefd28d2b9ba8c6860f71b0334efc1e9fb07552c0-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'WMATIC' │         0          │          0           │        28         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270' ] │ 'https://app.primex.finance/#/bucket-details/0xEFD28D2B9ba8c6860f71B0334eFc1e9fB07552C0?network=polygon_mainnet' │         0         │         0         │         0          │         0          │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────┴──────────┴────────────────────┴──────────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────┴───────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by christianlantin** [comment]
Done

**Review by christianlantin — APPROVED** [review]

**Comment by llamatester** [comment]
The primex-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.286 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────┬──────────┬────────────────────┬──────────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project      │  symbol  │       tvlUsd       │       apyBase        │     apyReward     │                   rewardTokens                   │                 underlyingTokens                 │                                                       url                                                        │   apyBaseBorrow    │  apyRewardBorrow   │   totalSupplyUsd   │   totalBorrowUsd   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────┼──────────┼────────────────────┼──────────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x0e28a9d0bed228981fec47b203611422717f9593-polygon'  │ 'Polygon'  │ 'primex-finance' │  'WETH'  │ 127612.86165698041 │ 0.027864324934090412 │ 698.3730848096501 │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 'https://app.primex.finance/#/bucket-details/0x0e28A9D0BEd228981feC47b203611422717f9593?network=polygon_mainnet' │ 2.6576629466816604 │ 2834.0826550485067 │ 129330.01361863966 │ 1717.1519616592466 │
    │    1    │ '0x12c125181eb7c944eaefcb2ae881475870f0aff3-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'USDC.E' │    86622.123509    │  0.6679593111829085  │ 86.07443281473802 │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 'https://app.primex.finance/#/bucket-details/0x12c125181Eb7c944EaEfcB2AE881475870f0Aff3?network=polygon_mainnet' │ 5.274384129164433  │ 366.3866766592188  │   103355.781308    │    16733.657799    │
    │    2    │ '0x018b221753ef25da38e672e0d3747bd626ae2e71-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WETH'  │     5156.8452      │          0           │         0         │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │  'https://app.primex.finance/#/bucket-details/0x018b221753Ef25Da38e672e0D3747bD626ae2e71?network=arbitrum_one'   │         0          │         0          │     5156.8452      │         0          │
    │    3    │ '0xcecbd4544081e700f5c2e5b148c07e94fed2b5c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'ARB'   │ 5130.833765061792  │          0           │         0         │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x912CE59144191C1204E64559FE8253a0e49E6548' ] │  'https://app.primex.finance/#/bucket-details/0xcecBd4544081e700F5c2e5b148C07E94feD2B5C5?network=arbitrum_one'   │         0          │         0          │ 5130.833765061792  │         0          │
    │    4    │ '0x653a3bc43bd7b44ab875f56cc0db54865a48cb2b-arbitrum' │ 'Arbitrum' │ 'primex-finance' │ 'USDC.E' │ 5127.628494414001  │ 0.03824951306807822  │ 664.7833468103706 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │  'https://app.primex.finance/#/bucket-details/0x653a3Bc43BD7B44Ab875F56cC0db54865a48CB2B?network=arbitrum_one'   │ 1.2790106044923366 │ 16233.93962075848  │   5328.034696794   │    200.40620238    │
    │    5    │ '0xc1c334ae711db9b83d03ec7c3a413d38b01826c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDT'  │   5038.214104924   │ 0.049568956911905104 │ 306.7258955376833 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │  'https://app.primex.finance/#/bucket-details/0xC1C334AE711db9b83D03eC7C3a413D38b01826c5?network=arbitrum_one'   │ 1.6231142059701442 │ 10704.49139724638  │   5239.809513939   │ 201.59540901499997 │
    │    6    │ '0x76e7759445bb8028f725e8e795dadee8b209f6ac-polygon'  │ 'Polygon'  │ 'primex-finance' │  'USDT'  │ 5026.5339033909995 │          0           │         0         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ 'https://app.primex.finance/#/bucket-details/0x76e7759445BB8028f725e8E795DadeE8b209f6Ac?network=polygon_mainnet' │         0          │         0          │ 5026.5339033909995 │         0          │
    │    7    │ '0x2fa0ba6d651b2306fbcb22797db0409bcf795f69-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDC'  │    4830.689575     │ 0.04255352498856446  │ 277.0031882772281 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │  'https://app.primex.finance/#/bucket-details/0x2Fa0BA6d651B2306FBcB22797Db0409BcF795F69?network=arbitrum_one'   │ 1.346625217583819  │ 6073.052499999999  │    5030.696082     │     200.006507     │
    │    8    │ '0xefd28d2b9ba8c6860f71b0334efc1e9fb07552c0-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'WMATIC' │ 1676.4203209394325 │          0           │        28         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270' ] │ 'https://app.primex.finance/#/bucket-details/0xEFD28D2B9ba8c6860f71B0334eFc1e9fB07552C0?network=polygon_mainnet' │         0          │         0          │ 1676.4203209394325 │         0          │
    │    9    │ '0x9ab05967a764838f9c804c1e58b94524f2789808-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WBTC'  │    681.29017884    │          0           │       8.25        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f' ] │  'https://app.primex.finance/#/bucket-details/0x9ab05967a764838f9C804C1e58b94524F2789808?network=arbitrum_one'   │         0          │         0          │    681.29017884    │         0          │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────┴──────────┴────────────────────┴──────────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding.
i'm looking at ur ui but having a hard time finding the apy nbs reported by the adapter. i'm probably blind lol, can u point me to the location. feel free to share a screenshot here, lets take the weth pool on polygon for example

**Comment by TbIKoBKa** [comment]
@slasher125 gm
we show daily rewards for **lenders** on buckets page (it is about _apyReward_) and daily rewards for **traders** of trading page (it is about apyRewardBorrow) and we recalculate them in proportion to the tokens in the buckets
image
image

**Comment by llamatester** [comment]
The primex-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.282 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────┬──────────┬────────────────────┬───────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project      │  symbol  │       tvlUsd       │        apyBase        │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │                                                       url                                                        │    apyBaseBorrow    │  apyRewardBorrow   │   totalSupplyUsd   │   totalBorrowUsd   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────┼──────────┼────────────────────┼───────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x0e28a9d0bed228981fec47b203611422717f9593-polygon'  │ 'Polygon'  │ 'primex-finance' │  'WETH'  │ 138135.42748680635 │ 0.011685585356779882  │ 618.7999039679164  │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 'https://app.primex.finance/#/bucket-details/0x0e28A9D0BEd228981feC47b203611422717f9593?network=polygon_mainnet' │ 2.3248140814506435  │ 335.0175128441496  │ 139019.00077087365 │ 883.5732840672975  │
    │    1    │ '0x12c125181eb7c944eaefcb2ae881475870f0aff3-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'USDC.E' │  59640.960592213   │  1.2694666943252386   │ 96.76089729555852  │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 'https://app.primex.finance/#/bucket-details/0x12c125181Eb7c944EaEfcB2AE881475870f0Aff3?network=polygon_mainnet' │  7.311329640947006  │ 163.07080684033025 │  76803.802622547   │  17162.842030334   │
    │    2    │ '0xcecbd4544081e700f5c2e5b148c07e94fed2b5c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'ARB'   │ 9762.381909910928  │ 0.0010440630906494164 │ 115.42477020743664 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x912CE59144191C1204E64559FE8253a0e49E6548' ] │  'https://app.primex.finance/#/bucket-details/0xcecBd4544081e700F5c2e5b148C07E94feD2B5C5?network=arbitrum_one'   │ 2.0533896815287944  │ 5822.743732398838  │  9768.65314496802  │ 6.271235057092379  │
    │    3    │ '0x76e7759445bb8028f725e8e795dadee8b209f6ac-polygon'  │ 'Polygon'  │ 'primex-finance' │  'USDT'  │ 7426.787978609999  │ 0.0016238694340753312 │ 209.43107665036868 │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ 'https://app.primex.finance/#/bucket-details/0x76e7759445BB8028f725e8E795DadeE8b209f6Ac?network=polygon_mainnet' │ 0.33720266728267667 │ 1061.7666287850752 │ 7471.835307936999  │ 45.04732932699999  │
    │    4    │ '0x653a3bc43bd7b44ab875f56cc0db54865a48cb2b-arbitrum' │ 'Arbitrum' │ 'primex-finance' │ 'USDC.E' │ 7406.977168590999  │ 0.0024116551787578544 │ 110.82234065294116 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │  'https://app.primex.finance/#/bucket-details/0x653a3Bc43BD7B44Ab875F56cC0db54865a48CB2B?network=arbitrum_one'   │  0.361049673987357  │ 584.2878922186688  │ 7469.459002004999  │ 62.48183341399999  │
    │    5    │ '0x018b221753ef25da38e672e0d3747bd626ae2e71-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WETH'  │ 6555.965899184271  │  0.2678981528764224   │ 221.92058129995277 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │  'https://app.primex.finance/#/bucket-details/0x018b221753Ef25Da38e672e0D3747bD626ae2e71?network=arbitrum_one'   │  5.217021149501866  │ 158.31061248992933 │ 7017.5207353885235 │ 461.55483620425275 │
    │    6    │ '0xc1c334ae711db9b83d03ec7c3a413d38b01826c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDT'  │ 5273.598822491999  │ 0.0003235113414268298 │ 130.18834171274182 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │  'https://app.primex.finance/#/bucket-details/0xC1C334AE711db9b83D03eC7C3a413D38b01826c5?network=arbitrum_one'   │ 0.1856720000732892  │ 3171.142968197307  │ 5285.111676844999  │ 11.512854352999998 │
    │    7    │ '0x2fa0ba6d651b2306fbcb22797db0409bcf795f69-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDC'  │   4934.665530795   │ 0.061305177506798536  │ 192.02724470426472 │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │  'https://app.primex.finance/#/bucket-details/0x2Fa0BA6d651B2306FBcB22797Db0409BcF795F69?network=arbitrum_one'   │ 1.6078805844665922  │ 146.63020380339887 │   5183.623466021   │ 248.95793522599996 │
    │    8    │ '0xefd28d2b9ba8c6860f71b0334efc1e9fb07552c0-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'WMATIC' │ 3837.925916543273  │           0           │         28         │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270' ] │ 'https://app.primex.finance/#/bucket-details/0xEFD28D2B9ba8c6860f71B0334eFc1e9fB07552C0?network=polygon_mainnet' │          0          │         0          │ 3837.925916543273  │         0          │
    │    9    │ '0x9ab05967a764838f9c804c1e58b94524f2789808-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WBTC'  │   1065.55387788    │           0           │        8.25        │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f' ] │  'https://app.primex.finance/#/bucket-details/0x9ab05967a764838f9C804C1e58b94524F2789808?network=arbitrum_one'   │          0          │         0          │   1065.55387788    │         0          │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────┴──────────┴────────────────────┴───────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
oke, ty for details.
one thing though, we do not include pre mined rewards, only token rewards which can be traded. hence, pls remove apyReward at this stage. we can add it back later once its tradeable

**Comment by llamatester** [comment]
The primex-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.292 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────┬──────────┬────────────────────┬───────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬─────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project      │  symbol  │       tvlUsd       │        apyBase        │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │                                                       url                                                        │    apyBaseBorrow    │ apyRewardBorrow │   totalSupplyUsd   │   totalBorrowUsd   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────┼──────────┼────────────────────┼───────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼─────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x0e28a9d0bed228981fec47b203611422717f9593-polygon'  │ 'Polygon'  │ 'primex-finance' │  'WETH'  │ 138131.66869966386 │ 0.011685585356779882  │     0     │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 'https://app.primex.finance/#/bucket-details/0x0e28A9D0BEd228981feC47b203611422717f9593?network=polygon_mainnet' │ 2.3248140814506435  │        0        │ 139015.21926991278 │ 883.5505702489316  │
    │    1    │ '0x12c125181eb7c944eaefcb2ae881475870f0aff3-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'USDC.E' │ 55981.81844341595  │  1.3959983003863474   │     0     │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 'https://app.primex.finance/#/bucket-details/0x12c125181Eb7c944EaEfcB2AE881475870f0Aff3?network=polygon_mainnet' │  7.675265776904316  │        0        │ 73115.69637410855  │  17133.8779306926  │
    │    2    │ '0xcecbd4544081e700f5c2e5b148c07e94fed2b5c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'ARB'   │ 9753.215354126976  │ 0.0010440630906494164 │     0     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x912CE59144191C1204E64559FE8253a0e49E6548' ] │  'https://app.primex.finance/#/bucket-details/0xcecBd4544081e700F5c2e5b148C07E94feD2B5C5?network=arbitrum_one'   │ 2.0533896815287944  │        0        │ 9759.480709039351  │ 6.265354912374699  │
    │    3    │ '0x76e7759445bb8028f725e8e795dadee8b209f6ac-polygon'  │ 'Polygon'  │ 'primex-finance' │  'USDT'  │     7419.36861     │ 0.0016238694340753312 │     0     │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0xc2132D05D31c914a87C6611C10748AEb04B58e8F' ] │ 'https://app.primex.finance/#/bucket-details/0x76e7759445BB8028f725e8E795DadeE8b209f6Ac?network=polygon_mainnet' │ 0.33720266728267667 │        0        │    7464.370947     │     45.002337      │
    │    4    │ '0x653a3bc43bd7b44ab875f56cc0db54865a48cb2b-arbitrum' │ 'Arbitrum' │ 'primex-finance' │ 'USDC.E' │ 7393.532136108153  │ 0.0024116551787578544 │     0     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │  'https://app.primex.finance/#/bucket-details/0x653a3Bc43BD7B44Ab875F56cC0db54865a48CB2B?network=arbitrum_one'   │  0.361049673987357  │        0        │  7455.90056843466  │ 62.368432326507005 │
    │    5    │ '0x018b221753ef25da38e672e0d3747bd626ae2e71-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WETH'  │ 6557.244386865292  │  0.2678981528764224   │     0     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │  'https://app.primex.finance/#/bucket-details/0x018b221753Ef25Da38e672e0D3747bD626ae2e71?network=arbitrum_one'   │  5.217021149501866  │        0        │ 7018.890768782576  │ 461.6463819172845  │
    │    6    │ '0xc1c334ae711db9b83d03ec7c3a413d38b01826c5-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDT'  │    5268.330492     │ 0.0003235113414268298 │     0     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │  'https://app.primex.finance/#/bucket-details/0xC1C334AE711db9b83D03eC7C3a413D38b01826c5?network=arbitrum_one'   │ 0.1856720000732892  │        0        │    5279.831846     │     11.501354      │
    │    7    │ '0x2fa0ba6d651b2306fbcb22797db0409bcf795f69-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'USDC'  │ 4928.498431315455  │ 0.061305177506798536  │     0     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0xaf88d065e77c8cC2239327C5EDb3A432268e5831' ] │  'https://app.primex.finance/#/bucket-details/0x2Fa0BA6d651B2306FBcB22797Db0409BcF795F69?network=arbitrum_one'   │ 1.6078805844665922  │        0        │ 5177.145491234469  │  248.647059919014  │
    │    8    │ '0xefd28d2b9ba8c6860f71b0334efc1e9fb07552c0-polygon'  │ 'Polygon'  │ 'primex-finance' │ 'WMATIC' │ 3847.934612963322  │           0           │     7     │ [ '0xDc6D1bd104E1efa4A1bf0BBCf6E0BD093614E31A' ] │ [ '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270' ] │ 'https://app.primex.finance/#/bucket-details/0xEFD28D2B9ba8c6860f71B0334eFc1e9fB07552C0?network=polygon_mainnet' │          0          │        0        │ 3847.934612963322  │         0          │
    │    9    │ '0x9ab05967a764838f9c804c1e58b94524f2789808-arbitrum' │ 'Arbitrum' │ 'primex-finance' │  'WBTC'  │   1065.80914928    │           0           │     7     │ [ '0xA533f744B179F2431f5395978e391107DC76e103' ] │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f' ] │  'https://app.primex.finance/#/bucket-details/0x9ab05967a764838f9C804C1e58b94524F2789808?network=arbitrum_one'   │          0          │        0        │   1065.80914928    │         0          │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────┴──────────┴────────────────────┴───────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴─────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by TbIKoBKa** [comment]
@slasher125 i left apyReward for buckets in mining phase. Rewards are in stablecoins. We have a banner about it on buckets page
image

**Pull request merged**
