### PR TITLE
Add Single Finance

### PR DESCRIPTION
**Pull request by singlefinance**

### CODE REVIEW

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.477 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬──────────────────┬──────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain   │     project      │                    symbol                    │       tvlUsd       │   apyBaseBorrow    │   totalSupplyUsd   │   totalBorrowUsd   │        apyBase         │      apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼──────────┼──────────────────┼──────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24' │ 'Cronos' │ 'single-finance' │ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' │ 911280.8859802601  │  21.880091529936   │ 2604832.5486907368 │ 1693551.6627104767 │   11.664916286351104   │ 0.9681597806623442  │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23', '0x67dcb6522ed9ad638859557b68fd13abf8214b9d' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    1    │ '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db' │ 'Cronos' │ 'single-finance' │ '0x97749c9b61f878a880dfe312d2594ae07aed7656' │  583014.553289356  │   0.049952897856   │ 584474.3631083008  │ 1459.809818944897  │ 0.00010230700097340471 │ 0.16465624369808698 │ [ '0x97749c9b61f878a880dfe312d2594ae07aed7656', '0xce3f7754b2d4983fd8bab257f226c3d07cd1711a' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    2    │ '0x88a73F172D84eC36D974ab756c18D52Eff1369b1' │ 'Cronos' │ 'single-finance' │ '0xc21223249ca28397b4b6541dffaecc539bff0c59' │ 479946.79694500007 │   9.92851837884    │   953082.306467    │   473135.509522    │   4.041600969275361    │ 1.2725516793817508  │ [ '0xc21223249ca28397b4b6541dffaecc539bff0c59', '0xfc82d8b05396f5f25534ee516568a05b85903761' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    3    │ '0x9f379739d3b3B2b44dECAc9864404B2B2952eE70' │ 'Cronos' │ 'single-finance' │ '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' │ 78660.24161527763  │ 7.625086103491199  │ 105466.65160077781 │ 26806.40998550018  │   1.5892129744640775   │ 0.5773213497515645  │ [ '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f', '0xf925a6e26704a23d2a3326eca76b8e734365b325' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    4    │ '0x467dff5b14b4dd40a52be338b75c9b58ead4add0' │ 'Cronos' │ 'single-finance' │ '0x66e428c3f67a68878562e79a0234c1f83c208770' │ 67962.71213300001  │  2.5476161162256   │    77883.662303    │     9920.95017     │   0.266106046776378    │ 3.1141206528627605  │ [ '0x66e428c3f67a68878562e79a0234c1f83c208770', '0xb8693c1b2d03aa099afaab3a688d78307ed1acab' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    5    │ '0xEe14e11819F8D38E3881006c5C77e6ea10e84528' │ 'Cronos' │ 'single-finance' │ '0x2d03bece6747adc00e1a131bba1469c15fd11e03' │ 29623.16027611075  │ 29.473668152049598 │ 357025.3205435839  │ 327402.16026747314 │   22.163102996791313   │ 0.3409598125923909  │ [ '0x2d03bece6747adc00e1a131bba1469c15fd11e03', '0x5a96544af21d22c66c0b9a738ec4563235212497' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    6    │ '0xA59543d47a090D2acf80647a40F705b67eC7edfc' │ 'Cronos' │ 'single-finance' │ '0x47a9d630dc5b28f75d3af3be3aaa982512cd89aa' │ 27357.928186701458 │   12.22827960204   │ 46182.239385402434 │ 18824.311198700976 │    4.08717580281644    │ 0.4495071660140837  │ [ '0x47a9d630dc5b28f75d3af3be3aaa982512cd89aa', '0xcd819e34cf62dd4f04d4c3a3691d6c3927a54b82' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    7    │ '0xd8eA6CCDd5973069E0d1E16c988f497EbD346DFD' │ 'Cronos' │ 'single-finance' │ '0x00d7699b71290094ccb1a5884cd835bd65a78c17' │  23597.6703616327  │  2.0916465751008   │ 25366.257975403147 │ 1768.5876137704472 │  0.11958379464288663   │          0          │ [ '0x00d7699b71290094ccb1a5884cd835bd65a78c17', '0xdc6c8b6d126f871066121311b13074463ca03fb1' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │
    │    8    │ '0x2741b846171d93b57713e8a61fD2825a55Fc55a7' │ 'Fantom' │ 'single-finance' │ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' │ 11324.143759359144 │  12.991289116968   │ 18185.178948864843 │ 6861.035189505699  │   4.019186584423548    │          0          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83', '0x2e521e22b36a0fdb18f16db4c1254dd6f5cada7f' ] │                        []                        │
    │    9    │ '0xFbb0160a2CA6AD6b53564c03D96605C7493a2585' │ 'Fantom' │ 'single-finance' │ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75' │    9817.751921     │  10.1965475669328  │    35423.861669    │    25606.109748    │   6.043864250633589    │          0          │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0xe1abc6189c2137e7ab4f674c4f17147e30ff91b2' ] │                        []                        │
    └─────────┴──────────────────────────────────────────────┴──────────┴──────────────────┴──────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi sir. symbol should cant be addresses, so pls use `USDC` etc.

**Comment by llamatester** [comment]
The single-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.356 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬──────────────────┬─────────┬────────────────────┬──────────────────────┬────────────────────┬────────────────────┬───────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────┐
    │ (index) │                     pool                     │  chain   │     project      │ symbol  │       tvlUsd       │    apyBaseBorrow     │   totalSupplyUsd   │   totalBorrowUsd   │        apyBase        │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │ ltv │
    ├─────────┼──────────────────────────────────────────────┼──────────┼──────────────────┼─────────┼────────────────────┼──────────────────────┼────────────────────┼────────────────────┼───────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────┤
    │    0    │ '0x081c9fc3049Cc473c5F1CDAaEF2b23588b5d1a24' │ 'Cronos' │ 'single-finance' │  'CRO'  │ 754711.4102347242  │   22.5981839826288   │ 2302727.464941577  │ 1548016.0547068529 │  12.457196415485177   │ 1.0462980262799788 │ [ '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    1    │ '0x88a73F172D84eC36D974ab756c18D52Eff1369b1' │ 'Cronos' │ 'single-finance' │ 'USDC'  │ 557551.3836334171  │   8.0684332691616    │ 934582.0148070286  │ 377030.6311736115  │  2.6690842330402336   │ 1.2397562537454614 │ [ '0xc21223249ca28397b4b6541dffaecc539bff0c59' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    2    │ '0x14ae2e848b2cfac47a5e0c63ffd74fd671a5c3db' │ 'Cronos' │ 'single-finance' │  'MMF'  │ 532741.8435889339  │ 0.043088286441599996 │ 533892.0686128776  │ 1150.2250239436669 │ 0.0000761206377439789 │ 0.1722010766679527 │ [ '0x97749c9b61f878a880dfe312d2594ae07aed7656' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    3    │ '0x9f379739d3b3B2b44dECAc9864404B2B2952eE70' │ 'Cronos' │ 'single-finance' │ 'bCRO'  │  71396.9145875704  │  7.594009992979201   │ 95595.30451804122  │ 24198.389930470817 │  1.5762856660735265   │ 0.6084617514200404 │ [ '0xebaceb7f193955b946cc5dd8f8724a80671a1f2f' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    4    │ '0x467dff5b14b4dd40a52be338b75c9b58ead4add0' │ 'Cronos' │ 'single-finance' │ 'USDT'  │ 69388.37497391799  │    2.164256581536    │  77808.354374751   │ 8419.979400832999  │  0.19204694283140236  │ 2.977839971951649  │ [ '0x66e428c3f67a68878562e79a0234c1f83c208770' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    5    │ '0xEe14e11819F8D38E3881006c5C77e6ea10e84528' │ 'Cronos' │ 'single-finance' │  'VVS'  │ 33408.04835252039  │   14.9713424781552   │ 326593.00660972245 │ 293184.95825720206 │  11.020705621848004   │ 0.3560865079265636 │ [ '0x2d03bece6747adc00e1a131bba1469c15fd11e03' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    6    │ '0xA59543d47a090D2acf80647a40F705b67eC7edfc' │ 'Cronos' │ 'single-finance' │ 'ARGO'  │ 24876.99298941368  │  11.339385126969601  │ 39993.84772818598  │ 15116.854738772303 │  3.5145652387400106   │ 0.4958657248103895 │ [ '0x47a9d630dc5b28f75d3af3be3aaa982512cd89aa' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    7    │ '0xd8eA6CCDd5973069E0d1E16c988f497EbD346DFD' │ 'Cronos' │ 'single-finance' │ 'VERSA' │ 23827.995994742763 │   2.0916465751008    │ 25613.84595075334  │ 1785.8499560105781 │  0.11958379464288663  │         0          │ [ '0x00d7699b71290094ccb1a5884cd835bd65a78c17' ] │ [ '0x0804702a4e749d39a35fde73d1df0b1f1d6b8347' ] │  0  │
    │    8    │ '0x2741b846171d93b57713e8a61fD2825a55Fc55a7' │ 'Fantom' │ 'single-finance' │  'FTM'  │ 10742.831765236073 │  12.424102709400001  │ 16807.24172662096  │ 6064.409961384887  │   3.675961816656027   │         0          │ [ '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83' ] │                        []                        │  0  │
    │    9    │ '0xFbb0160a2CA6AD6b53564c03D96605C7493a2585' │ 'Fantom' │ 'single-finance' │ 'USDC'  │  9635.08882634627  │   10.2481062716016   │ 35436.125960817844 │ 25801.037134471575 │   6.118548399631866   │         0          │ [ '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75' ] │                        []                        │  0  │
    └─────────┴──────────────────────────────────────────────┴──────────┴──────────────────┴─────────┴────────────────────┴──────────────────────┴────────────────────┴────────────────────┴───────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by singlefinance** [comment]
@slasher125 henlo, updated accordingly. TY!

**Pull request merged**
