### PR TITLE
Vela: Implement new staking APR

### PR DESCRIPTION
**Pull request by michaelotis**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running vela-exchange adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 27 passed, 28 total
    Snapshots:   0 total
    Time:        0.287 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol │ poolMeta │       tvlUsd       │      apyBase       │                 underlyingTokens                 │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 5794689.916557631  │ 11.661704260651632 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │
    │    1    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │          │ 334069.8937433734  │  98.7323402010519  │ [ '0x088cd8f5eF3652623c22D48b1605DCfE860Cd704' ] │
    │    2    │   '0xc4abade3a15064f9e3596943c699032748b13352-base'   │   'Base'   │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 77289.50082737712  │ 36.39984756097561  │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    │    3    │   '0xc4abade3a15064f9e3596943c699032748b13352-base'   │   'Base'   │ 'vela-exchange' │ 'USDC' │          │ 11977.113308416485 │ 92.68236606060496  │ [ '0x5A76A56ad937335168b30dF3AA1327277421C6Ae' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────┴──────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    }

**Comment by llamatester** [comment]
The vela-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.257 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol │ poolMeta │       tvlUsd       │      apyBase       │                 underlyingTokens                 │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 5794689.916557631  │ 11.661704260651632 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │
    │    1    │ '0x60b8c145235a31f1949a831803768bf37d7ab7aa-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │          │ 334069.8937433734  │  98.7323402010519  │ [ '0x088cd8f5eF3652623c22D48b1605DCfE860Cd704' ] │
    │    2    │   '0xc4abade3a15064f9e3596943c699032748b13352-base'   │   'Base'   │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 77289.50082737712  │ 36.39984756097561  │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    │    3    │   '0x00b01710c2098b883c4f93dd093be8cf605a7bde-base'   │   'Base'   │ 'vela-exchange' │ 'USDC' │          │ 11977.113308416485 │ 92.68236606060496  │ [ '0x5A76A56ad937335168b30dF3AA1327277421C6Ae' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────┴──────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hi, can u share a link to the newly added pools?

**Comment by michaelotis** [comment]
> hi, can u share a link to the newly added pools?

https://app.vela.exchange/staking

**Comment by slasher125** [comment]
sry i still can't a usdc pool on that page? is it referreing to the esVELA? if so, then we need to update the symbol accordingly. also, poolMeta needs to include information about locked durations

**Comment by michaelotis** [comment]
> sry i still can't a usdc pool on that page? is it referreing to the esVELA? if so, then we need to update the symbol accordingly. also, poolMeta needs to include information about locked durations

Apologies, I've made some updates. Not sure what you recommend, the underlying token is Vela, however you must convert your tokens into an escrowed version esVela and stake that token to get the USDC rewards. However, there's no locking period to receive the rewards but to convert your esVela back to Vela, to receive 1:1 that is 6 months. Similar to how Grail does it with xGrail.

**Comment by llamatester** [comment]
The vela-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       30 passed, 30 total
    Snapshots:   0 total
    Time:        0.256 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬──────────┬────────────────────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │  symbol  │              poolMeta              │       tvlUsd       │      apyBase       │                 underlyingTokens                 │     apyReward     │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼──────────┼────────────────────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │  'USDC'  │               'VLP'                │ 5869456.821250766  │ 12.071330845771136 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │                   │                                                  │
    │    1    │ '0x60b8c145235a31f1949a831803768bf37d7ab7aa-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'esVELA' │ 'esVela vesting is up to 6 months' │ 370580.5462702619  │                    │ [ '0x088cd8f5eF3652623c22D48b1605DCfE860Cd704' ] │ 89.00494840316132 │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │
    │    2    │   '0xc4abade3a15064f9e3596943c699032748b13352-base'   │   'Base'   │ 'vela-exchange' │  'USDC'  │               'VLP'                │ 76941.76687209672  │ 35.90493939393939  │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │                   │                                                  │
    │    3    │   '0x00b01710c2098b883c4f93dd093be8cf605a7bde-base'   │   'Base'   │ 'vela-exchange' │ 'esVELA' │ 'esVela vesting is up to 6 months' │ 11587.825499513565 │                    │ [ '0x5A76A56ad937335168b30dF3AA1327277421C6Ae' ] │ 95.79598864744715 │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴──────────┴────────────────────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
