### PR TITLE
add liondex

### PR DESCRIPTION
**Pull request by LionDEXDev**

### CODE REVIEW

**Comment by llamatester** [comment]
The liondex adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.341 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────┬────────────┬───────────┬────────┬────────────────────┬────────────────────┐
    │ (index) │                      pool                      │   chain    │  project  │ symbol │       tvlUsd       │      apyBase       │
    ├─────────┼────────────────────────────────────────────────┼────────────┼───────────┼────────┼────────────────────┼────────────────────┤
    │    0    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-1' │ 'arbitrum' │ 'liondex' │  'LP'  │ 1896698.1192552901 │ 212.52374985315384 │
    │    1    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-0' │ 'arbitrum' │ 'liondex' │ 'LION' │ 1586062.0394054614 │     28.805157      │
    └─────────┴────────────────────────────────────────────────┴────────────┴───────────┴────────┴────────────────────┴────────────────────┘

**Comment by llamatester** [comment]
The liondex adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.384 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────┬────────────┬───────────┬────────┬────────────────────┬────────────────────┐
    │ (index) │                      pool                      │   chain    │  project  │ symbol │       tvlUsd       │      apyBase       │
    ├─────────┼────────────────────────────────────────────────┼────────────┼───────────┼────────┼────────────────────┼────────────────────┤
    │    0    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-1' │ 'arbitrum' │ 'liondex' │  'LP'  │ 2378608.7197464006 │ 175.13517956575552 │
    │    1    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-0' │ 'arbitrum' │ 'liondex' │ 'LION' │ 1699578.3852081592 │     25.699319      │
    └─────────┴────────────────────────────────────────────────┴────────────┴───────────┴────────┴────────────────────┴────────────────────┘

**Comment by LionDEXDev** [comment]
no, it's our platform's liquidity token, just similar to GMX's GLP, called LP on our platform @slasher125

**Comment by slasher125** [comment]
@LionDEXDev yes, but holding LP means i'm exposed to whatever assets are supplied for trading yes? so, in your case wbtc,etc,usdc. basically we do not show pool names on our dashboard but the underlying tokens of a specific pool.

pls don't forget the other 2 mentioned things

**Comment by LionDEXDev** [comment]
@slasher125  thanks for your replay.  
it's some different from regular lp. two typical examples that you have already approved are GMX's GLP pool (pool  symbol: GLP) and Metafault's MVLP pool (pool  symbol: MVLP), rather than symbols like WBTC-ETH-USDC.   in those case, LP token itself is underlying token.  

here is the example:
https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/gmx/index.js
https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/metavault.trade/index.js

I have a suggestion. If the LP symbol is too confusing, can I change it to LionDEX-LP？

**Comment by slasher125** [comment]
GLP, LP, MLVP etc are arbitrary names and to a newbie completely meaningless in terms of what token they are actually supplying for this pool until they check your UI. hence, why on our yield page we usually have symbol = pool assets, such that a user sees what he needs to provide/gets exposure to if a deposit is being made.
this will also help users search for pools based on specific tokens, eg someone searching for a btc pool will also find yours.

some adapters obviously slipped through this like gmx, which i'll update.
underlying tokens would then be the actual addresses of btc, eth, etc

**Comment by LionDEXDev** [comment]
@slasher125   Okay, got it. It has been modified in the latest commit. Could you please confirm it again?

**Comment by llamatester** [comment]
Error while running liondex adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 14 passed, 15 total
    Snapshots:   0 total
    Time:        0.52 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────┬────────────┬───────────┬─────────────────┬────────────────────┬────────────────────┬───────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                      pool                      │   chain    │  project  │     symbol      │       tvlUsd       │      apyBase       │     apyReward     │                                                               underlyingTokens                                                               │     poolMeta      │
    ├─────────┼────────────────────────────────────────────────┼────────────┼───────────┼─────────────────┼────────────────────┼────────────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────┤
    │    0    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-1' │ 'arbitrum' │ 'liondex' │ 'WBTC-ETH-USDC' │ 2000958.3360529998 │ 25.969065703188143 │ 171.5815126813002 │ [ '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 'LionDEX LP pool' │
    │    1    │ '0x154E2b1dBE9F493fF7938E5d686366138ddCE017-0' │ 'arbitrum' │ 'liondex' │     'LION'      │ 1673666.9443520706 │     22.542565      │                   │                                                                                                                                              │    'LION pool'    │
    └─────────┴────────────────────────────────────────────────┴────────────┴───────────┴─────────────────┴────────────────────┴────────────────────┴───────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────┘
    }

**Pull request merged**
