### PR TITLE
add optifi adapter

### PR DESCRIPTION
**Pull request by LeoOptiFi**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running optifi adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 13 passed, 14 total
    Snapshots:   0 total
    Time:        0.375 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────┬──────────┬──────────┬────────┬───────────────┬────────────────────┐
    │ (index) │                      pool                      │  chain   │ project  │ symbol │    tvlUsd     │        apy         │
    ├─────────┼────────────────────────────────────────────────┼──────────┼──────────┼────────┼───────────────┼────────────────────┤
    │    0    │ '8J7AfECijPQDUfj7k6pQk6YNTEqjSAjiZnsGNgRZmowz' │ 'Solana' │ 'optifi' │ 'USDC' │ 206317.509707 │ 7.609301545449565  │
    │    1    │ '4UoELNjSk36m3aqTS6PnxNoUSZYXKWa7hEn7i6BRHrUu' │ 'Solana' │ 'optifi' │ 'USDC' │ 206257.249643 │ -4.722695501655593 │
    └─────────┴────────────────────────────────────────────────┴──────────┴──────────┴────────┴───────────────┴────────────────────┘
    }

**Comment by vrtnd** [comment]
Hi, please add url to your pools.
Also I cant find these pools on your ui, can u send a link

**Comment by LeoOptiFi** [comment]
Hi, please add url to your pools-> what url? 
Also I cant find these pools on your ui, can u send a link->https://www.optifi.app/amm

**Comment by LeoOptiFi** [comment]
BTW, here is my test result , and all of them pass. Can you show the err msg?
image

**Comment by vrtnd** [comment]
Merge master branch locally and run tests again, u missing url to your pool` module.exports = {url:  ......, }`
And as i can see these pools are eth and btc options, so can u please add `poolMeta` field smth like `"BTC Option"/"ETH Option"`

**Pull request closed without merging**
