### PR TITLE
add pool2 for radiant

### PR DESCRIPTION
**Pull request by loyorf**

### CODE REVIEW

**Comment by slasher125** [comment]
I suggest changing `Pool2` to a more descriptive symbol like `RDNT-ETH`. if u want to keep the Pool2 name, then u could put it into `poolMeta` in addition to making the symbol change to `RDNT-ETH`

**Comment by slasher125** [comment]
also, please change the url to `https://app.radiant.capital/#/markets`, the current one doesn't work for me

**Comment by loyorf** [comment]
@slasher125 i updated it, pls check.

**Comment by llamatester** [comment]
The radiant adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.442 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────┬────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │  project  │   symbol   │       tvlUsd       │      apyBase       │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────┼────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x805ba50001779CeD4f59CfF63aea527D12B94829' │ 'Arbitrum' │ 'radiant' │   'USDC'   │   19658620.15897   │ 2.3855396288974644 │ 3.003290118243313  │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    │    1    │ '0xEf47CCC71EC8941B67DC679D1a5f78fACfD0ec3C' │ 'Arbitrum' │ 'radiant' │   'USDT'   │  17778792.308017   │ 2.3083884526477365 │ 3.0715696912860224 │ [ '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    │    2    │ '0x5293c6CA56b8941040b8D18f557dFA82cF520216' │ 'Arbitrum' │ 'radiant' │   'DAI'    │ 6813577.847680872  │ 2.6493418545450966 │ 3.176462756505126  │ [ '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    │    3    │ '0x15b53d277Af860f51c3E6843F8075007026BBb3a' │ 'Arbitrum' │ 'radiant' │   'WETH'   │ 6092043.626578668  │ 3.772670592478014  │ 4.350337403333801  │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    │    4    │ '0x4cD44E6fCfA68bf797c65889c74B26b8C2e5d4d3' │ 'Arbitrum' │ 'radiant' │   'WBTC'   │ 3219583.0696045216 │ 2.5214559609553775 │ 3.7760690369527596 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    │    5    │ '0xc963ef7d977ECb0Ab71d835C4cb1Bf737f28d010' │ 'Arbitrum' │ 'radiant' │ 'RDNT-ETH' │ 678264.5764019346  │     undefined      │ 142.64208204224994 │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │ [ '0x0c4681e6c0235179ec3d4f4fc4df3d14fdd96017' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────┴────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
