### PR TITLE
Fix polynomial apy

### PR DESCRIPTION
**Pull request by ArpitShukIa**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running polynomial-liquidity adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       4 failed, 20 passed, 24 total
    Snapshots:   0 total
    Time:        0.315 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬────────────────────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────┐
    │ (index) │    pool    │    chain     │        project         │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                        url                        │
    ├─────────┼────────────┼──────────────┼────────────────────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────┤
    │    0    │ '1-fxUSDC' │ 'polynomial' │ 'polynomial-liquidity' │  'USDC'  │   2511706.313047   │ 5.990473658662059  │ 26.710153696603438 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    1    │ '1-sUSDe'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sUSDe'  │ 213109.57215169567 │ 1.8991774523228435 │ 26.710153696603438 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    2    │ '1-usd0++' │ 'polynomial' │ 'polynomial-liquidity' │ 'usd0++' │ 183349.85902731097 │ 8.181113527011163  │ 26.710153696603438 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    3    │  '1-sDAI'  │ 'polynomial' │ 'polynomial-liquidity' │  'sDAI'  │ 67208.50546959642  │ 4.284468555897109  │ 26.710153696603438 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    └─────────┴────────────┴──────────────┴────────────────────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────┘
    }

**Comment by slasher125** [comment]
@ArpitShukIa u need to add the rewardTokens array, see local test output

**Comment by ArpitShukIa** [comment]
Hey @slasher125, can you point me to where I have to add this rewardTokens array?

**Comment by llamatester** [comment]
The polynomial-liquidity adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.271 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬────────────────────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────┐
    │ (index) │    pool    │    chain     │        project         │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                   rewardTokens                   │                        url                        │
    ├─────────┼────────────┼──────────────┼────────────────────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────┤
    │    0    │ '1-fxUSDC' │ 'polynomial' │ 'polynomial-liquidity' │  'USDC'  │   2511456.061884   │ 5.990473658662059  │ 27.047826502457756 │ [ '0x4200000000000000000000000000000000000042' ] │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    1    │ '1-sUSDe'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sUSDe'  │ 213159.23483645997 │ 1.8991774523228435 │ 27.047826502457756 │ [ '0x4200000000000000000000000000000000000042' ] │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    2    │ '1-usd0++' │ 'polynomial' │ 'polynomial-liquidity' │ 'usd0++' │ 183355.00299912467 │ 8.181113527011163  │ 27.047826502457756 │ [ '0x4200000000000000000000000000000000000042' ] │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    3    │  '1-sDAI'  │ 'polynomial' │ 'polynomial-liquidity' │  'sDAI'  │ 67268.79916651594  │ 4.284468555897109  │ 27.047826502457756 │ [ '0x4200000000000000000000000000000000000042' ] │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    └─────────┴────────────┴──────────────┴────────────────────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────┘

**Comment by ArpitShukIa** [comment]
@slasher125 
Added the reward tokens.
Can you review again?

**Comment by slasher125** [comment]
how is apyReward generated? can you give me an invite code

**Comment by ArpitShukIa** [comment]
You can join using: https://polynomial.fi/r/SR0BEX
We are giving 10k OP every week to stakers in the ratio of their contribution in the platform tvl. The rewards apr comes from that.

**Comment by slasher125** [comment]
hm the code seems to be invalid
shouldn't the reward apy be different based on the individual pool tvl?

**Comment by ArpitShukIa** [comment]
@slasher125 We are giving based on the usd value of collateral deposited. It doesn't depend which pool the user deposits in. So the reward apr is same for all pools

**Pull request merged**
