### PR TITLE
Add Vela Exchange VLP Yield

### PR DESCRIPTION
**Pull request by michaelotis**

### CODE REVIEW

**Comment by llamatester** [comment]
The vela-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.37 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────┬──────────┬───────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol │ poolMeta │      tvlUsd       │      apyBase       │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────┼──────────┼───────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 1111620.689601013 │ 15.605445412794797 │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────┴──────────┴───────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
henlo, ty for adding:
- rewardTokens only needs to be provided if apyReward is given
- apr should be calculated via on chain calls too
- apyBase is usually from fees/real yield. can u confirm thats the case here?

**Comment by slasher125** [comment]
we actually use a 1day period and scale that up to apr, so that should work then i guess

**Comment by michaelotis** [comment]
@slasher125 Is there anything we can do here?

**Comment by slasher125** [comment]
- can u explain how its calc on your end? 
- imo, even if negative apr over 1day, thats valuable info
- in addition to apyBase, we also got apyBase7d as an additional field which u can use optionally (should be computed over 7day window)

**Comment by michaelotis** [comment]
Similarly, it looks like Gains does the same, they calculate their own APR on their backend: https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/gains-network/index.js#L26

**Comment by michaelotis** [comment]
Here's the backend code to retrieve the APR, VLP_APR is the return result used

` async getVLPAPR(chainId: string): Promise<any> {
    try {
      if (!chainId || !SUPPORTED_CHAINS.includes(parseInt(chainId))) {
        return null;
      }
      const v = await this.cacheService.getItem(`vlp_apr_${chainId}`);
      if (v) {
        return v;
      }
      const provider = new ethers.providers.JsonRpcProvider(
        PREMIUM_RPCS[chainId],
      );
      const getArbitrumTokenDistance = async () => {
        let distance = await fetch(
          `https://coins.llama.fi/block/arbitrum/${Math.floor(
            new Date(new Date(Date.now() - 12096e5)).getTime() / 1000,
          )}`,
        )
          .then((response) => response.json())
          .then((data) => data.height);
        if (!distance)
          distance =
            Math.abs(parseInt((await provider.getBlockNumber()).toString())) -
            4335000; // Approximately 14 days

        return distance;
      };
      const TOKEN_DISTANCES = {
        [ChainId.ARBITRUM]: await getArbitrumTokenDistance(),
        [ChainId.ARBITRUM_GOERLI]:
          Math.abs(parseInt((await provider.getBlockNumber()).toString())) -
          1000,
      };

      const velaInfo = await this.getVelaInfo(chainId);
      const secondsPerYear = 31536000;
      const pastBlock =
        TOKEN_DISTANCES[chainId] > START_BLOCK[chainId]
          ? TOKEN_DISTANCES[chainId]
          : START_BLOCK[chainId]; // Approximately 14 days
      const vaultContract = new ethers.Contract(
        CONTRACT_ADDRESSES[chainId]['VaultProxy'],
        VAULT_ABI,
        provider,
      );
      const TOKENFARM_CONTRACT = new ethers.Contract(
        CONTRACT_ADDRESSES[chainId]['TokenFarmProxy'],
        TOKENFARM_ABI,
        provider,
      );
      const rewardsPerSecond =
        (
          await TOKENFARM_CONTRACT.poolRewardsPerSec(0)
        ).rewardsPerSec.toString() /
        10 ** 18;
      const poolTotal = (await TOKENFARM_CONTRACT.poolTotalLp(1)) / 10 ** 18;
      // adds the blockTag flag to query past balances
      const historical = parseFloat(
        ethers.utils.formatUnits(
          await vaultContract.getVLPPrice({
            blockTag: +pastBlock,
          }),
          5,
        ),
      );
      const current = parseFloat(
        ethers.utils.formatUnits(await vaultContract.getVLPPrice(), 5),
      );
      const diff = current - historical;
      /// APR Calculations ///
      const VLP_APR = 365 * (diff / historical / 14) * 100;
      let VELA_APR;
      if (poolTotal > 0) {
        VELA_APR =
          ((rewardsPerSecond * secondsPerYear * velaInfo.price) /
            (poolTotal * current)) *
          100;
      } else {
        VELA_APR = 0;
      }

      const res = {
        VLP_APR: VLP_APR,
        VELA_APR: VELA_APR,
        TOTAL_APR: VLP_APR + VELA_APR,
      };
      await this.cacheService.setItem(
        `vlp_apr_${chainId}`,
        res,
        60, // 1 minute
      );
      return res;
    } catch (err: any) {
      err.description = 'getVLPAPR Error';
      console.error(err);
      return Promise.reject('getVLPAPR Error');
    }
  }`

**Comment by michaelotis** [comment]
@slasher125 Can you let me know what we need to do to get this pushed through?

**Comment by slasher125** [comment]
@michaelotis  

still don't see why the 1day window wound't work, yes its more volatile for sure (even negative if traders are killing it)
but fundamentally there is nothing speaking against tracking the value over a 24h period? 
anyways, lets keep it as is. however, lets work on getting the actual calculation (the code u shared) into the adapter.

have u tried using our sdk ? that should work, u can pass historical blocks via `block` in the sdk call object

**Comment by michaelotis** [comment]
> @michaelotis
> 
> still don't see why the 1day window wound't work, yes its more volatile for sure (even negative if traders are killing it) but fundamentally there is nothing speaking against tracking the value over a 24h period? anyways, lets keep it as is. however, lets work on getting the actual calculation (the code u shared) into the adapter.
> 
> have u tried using our sdk ? that should work, u can pass historical blocks via `block` in the sdk call object

Yes, that was my initial logic path, however it throws a revert error if I attempt to do any sort of historical lookup

for example below, I only used a 1 day old block from now. The RPC used for Arbitrum (https://arb1.arbitrum.io/rpc) does do historical lookbacks.

`  const historicalVLPPrice = (await sdk.api.abi.call({
    target: VAULT_ADDRESS,
    abi: VaultABI.filter(({ name }) => name === "getVLPPrice")[0],
    chain: 'arbitrum',
    block: 120070494
  })).output`

> Error: Jest: Got error running globalSetup - /home/mlotis/yield-server/src/adaptors/beforeTests.js, reason: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0xC4ABADE3a15064F9E3596943c699032748b13352","data":"0x68817be0","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)

However, I was able to inject the alchemy RPC into the SDK and was able to return a value. So I've pushed the commit with the on-chain calculations

**Comment by llamatester** [comment]
The vela-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       10 passed, 10 total
    Snapshots:   0 total
    Time:        0.376 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol │ poolMeta │       tvlUsd       │      apyBase       │                 underlyingTokens                 │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 1198858.0590774608 │ 22.429089047411622 │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────┴──────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
