### PR TITLE
premia reward yield

### PR DESCRIPTION
**Pull request by KngZhi**
- feat: support reward apy
- refactor: remove useless code

### CODE REVIEW

**Comment by llamatester** [comment]
The premia adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       256 passed, 256 total
    Snapshots:   0 total
    Time:        0.46 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬───────────┬──────────────────────────────────────────────────┬────────────────────┬──────────┬──────────┬─────────────────────┐
    │ (index) │   chain    │                                             pool                                             │      poolMeta       │                 underlyingTokens                 │ apyReward │                   rewardTokens                   │       tvlUsd       │ project  │  symbol  │       apyBase       │
    ├─────────┼────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼───────────┼──────────────────────────────────────────────────┼────────────────────┼──────────┼──────────┼─────────────────────┤
    │    0    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f-PUT'  │  'WBTC/DAI - PUT'   │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │   51.46   │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 1097375.1321760362 │ 'premia' │  'WBTC'  │ -0.149104230466752  │
    │    1    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x82af49447d8a07e3bd95bd0d56f35241523fbab1-CALL' │  'WETH/DAI - CALL'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │   9.72    │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 610622.7247272456  │ 'premia' │  'WETH'  │ 17.877710688617952  │
    │    2    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-CALL' │  'WETH/DAI - CALL'  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │   4.01    │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 469508.1743311767  │ 'premia' │  'WETH'  │ 26.412338411359343  │
    │    3    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0xf97f4df75117a78c1a5a0dbb814af92458539fb4-CALL' │  'LINK/DAI - CALL'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │   0.99    │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 467006.3560362345  │ 'premia' │  'LINK'  │  19.27783390742467  │
    │    4    │ 'optimism' │ '0x7f5c764cbc14f9669b88837ca1490cca17c31607/0x4200000000000000000000000000000000000006-CALL' │ 'WETH/USDC - CALL'  │ [ '0x4200000000000000000000000000000000000006' ] │   49.07   │ [ '0x374ad0f47f4ca39c78e5cc54f1c9e426ff8f231a' ] │ 446158.87013136747 │ 'premia' │  'WETH'  │ 26.083502615232433  │
    │    5    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0x514910771af9ca656af840dff83e8264ecf986ca-CALL' │  'LINK/DAI - CALL'  │ [ '0x514910771af9ca656af840dff83e8264ecf986ca' ] │   0.02    │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 394335.8130687608  │ 'premia' │  'LINK'  │  7.140767470563456  │
    │    6    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x5979d7b546e38e414f7e9822514be443a4800529-CALL' │ 'wstETH/DAI - CALL' │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │   6.81    │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 352845.0873234026  │ 'premia' │ 'wstETH' │  96.36242502408984  │
    │    7    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-PUT'  │  'WETH/DAI - PUT'   │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │   40.54   │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 349436.97873734304 │ 'premia' │  'WETH'  │ -13.664541388346208 │
    │    8    │  'fantom'  │ '0x04068da6c83afcfa0e13ba15a6696662335d5b75/0x74b23882a30290451a17c44f4f05243b6b58c76d-CALL' │  'ETH/USDC - CALL'  │ [ '0x74b23882a30290451a17c44f4f05243b6b58c76d' ] │   46.52   │ [ '0x3028b4395f98777123c7da327010c40f3c7cc4ef' ] │ 308199.7967676239  │ 'premia' │  'ETH'   │ 14.532164418137327  │
    │    9    │  'fantom'  │ '0x04068da6c83afcfa0e13ba15a6696662335d5b75/0x74b23882a30290451a17c44f4f05243b6b58c76d-PUT'  │  'ETH/USDC - PUT'   │ [ '0x74b23882a30290451a17c44f4f05243b6b58c76d' ] │   40.83   │ [ '0x3028b4395f98777123c7da327010c40f3c7cc4ef' ] │ 287399.70246082963 │ 'premia' │  'ETH'   │ -19.87973733349483  │
    └─────────┴────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴───────────┴──────────────────────────────────────────────────┴────────────────────┴──────────┴──────────┴─────────────────────┘

**Comment by KngZhi** [comment]
Previously the Nb of pools wasn't correct. The result of the test is 36, however, on DefiLlama, it only shows 18 pools for that.

https://defillama.com/yields?project=premia

image

**Comment by 0xngmi** [comment]
do some pools have tvl <10k, we dont display those in defillama

**Comment by KngZhi** [comment]
> do some pools have tvl <10k, we dont display those in defillama

Besides, sometimes, the APY may become negative, is that allowed in the Yield category?

**Comment by slasher125** [comment]
we remove anything with apy < 0 on the server. so its either that or the tvl filter which is reducing the output.

**Pull request merged**
