### PR TITLE
Add Brinc-Finance APY Adaptor

### PR DESCRIPTION
**Pull request by Opyet**
### Contribution
APY information for current six(6) staking pools on the [Brinc.fi](https://app.brinc.fi/analytics) protocol.

### CODE REVIEW

**Comment by slasher125** [comment]
gm. I'm getting 0 Tvl for all pools:
```
Nb of pools: 6
 

Sample pools: [
  {
    pool: 'Pool0',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-30Days',
    tvlUsd: 0,
    apy: 122.40340428967862
  },
  {
    pool: 'Pool1',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-90Days',
    tvlUsd: 0,
    apy: 226.66762079622833
  },
  {
    pool: 'Pool2',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-180Days',
    tvlUsd: 0,
    apy: 465.2865092742704
  },
  {
    pool: 'Pool3',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-gBRC-30Days',
    tvlUsd: 0,
    apy: 1094.3976012286362
  },
  {
    pool: 'Pool4',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-gBRC-90Days',
    tvlUsd: 0,
    apy: 19784.267132844783
  },
  {
    pool: 'Pool5',
    chain: 'arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-gBRC-180Days',
    tvlUsd: 0,
    apy: 488204.2952354391
  }
]
```

**Comment by Opyet** [comment]
Can anyone kindly assist with this clarification?

There is a known [issue](https://github.com/Uniswap/v3-subgraph/issues/111) with the uniswap v3 arbitrum subgraph.
So, it's not a viable option to compute TVL. Can we introduce a new uniswap package to the package.json to help resolve this?

Here [uniswap smart order router](https://www.npmjs.com/package/@uniswap/smart-order-router)

**Comment by slasher125** [comment]
Hey Opyet, sorry i missed ur message from 3days ago. gonna checkout the package u mentioned and report back later today

**Comment by Opyet** [comment]
> Hey Opyet, sorry i missed ur message from 3days ago. gonna checkout the package u mentioned and report back later today

Great! Thank you.

**Comment by slasher125** [comment]
Go ahead and add the package sir :)

**Comment by slasher125** [comment]
cool, a few remaining smol things:

```
  {
    pool: 'Pool4',
    chain: 'Arbitrum',
    project: 'brinc-finance',
    symbol: 'BRC-gBRC-90Days',
    tvlUsd: 2020,
    apy: 1460.2180199824404,
    rewardTokens: [ '0x62C7e128e7c3205964429F58A0C6f63a776D10d1' ]
  },
```

- can you please add `brinc-finance` to the pool name as its not very distinct right now (as prefix or suffix)
- for the symbol lets move the duration into () like `BRC-gBRC (90Days)`
- lets add the `underlyingTokens` field which in the above example should be the token address of both BRC and gBRC
- you are getting a conflict because we recently made changes to the package.json. if you cant resolve then i suggest you remove the package.json and package-lock.json changes from your PR once you are done testing and i will add the required dependencies to master in the meantime

**Comment by Opyet** [comment]
Thanks @slasher125 .

Changes have been implemented. Merge conflict has also been resolved.
Feels like we're good to go.

**Comment by Opyet** [comment]
How soon can we finalize this PR, please? @slasher125

**Comment by slasher125** [comment]
In case you are wondering why its not showing up on UI. we are encountering an error when running the adaptor on the aws lambda env.

```
Error: invalid BigNumber value (argument="value", value="2.7305e+22", code=INVALID_ARGUMENT, version=bignumber/5.6.1)
...
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: H { s: 1, e: 22, c: [ 273050000 ] }
```

In case you have an idea what exactly is causing this error, feel free to post here and we will get in the fix. In the meantime I'm trying to identify why its crashing myself

**Comment by Opyet** [comment]
Does the error include the line number perhaps I can find a way to optimize?

**Comment by slasher125** [comment]
it doesn't. but i logged a few things and seems to me that this particular value was coming from the `brcStaked` variable

**Comment by Opyet** [comment]
Thanks @slasher125 , please find the new bug fix PR above.

**Comment by slasher125** [comment]
got fixed sir! #127 https://defillama.com/yields?project=brinc-finance
in case u wonder why only those 2 pools: we currently only display pools with tvl >=10k usd (but working on lowering this in the near future)

**Comment by Opyet** [comment]
Thanks a lot @slasher125 .
I'm wondering why the project nor token are not appearing in the search bar.

**Comment by slasher125** [comment]
gm. the search bar is quite limited atm and works only for top 1k tokens from coingecko. we have a new version in the making which will be much better.
Currently, for project search you'd need use to use the `Filter by Project` Dropdown

**Pull request merged**
