### PR TITLE
add merkl yield adapter

### PR DESCRIPTION
**Pull request by tutacrypto**
This is a pull request to add Merkl pools to DefiLlama yield dashboard. 
No data is available from The Graph, so all data is fetched from Angle's API which does all the data pipelining work itself. 
1 test is not passing the but test results seem fine. 

Let me know what you think @slasher125 !

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running merkl adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        0.371 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬──────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
    │ (index) │                     pool                     │   chain    │ project │    symbol    │       tvlUsd       │     apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │  Values   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼──────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
    │    0    │ '0xf44aCAa38be5E965c5Ddf374E7a2BA270e580684' │ 'Optimism' │ 'merkl' │ 'USDC-agEUR' │ 739018.7088001727  │ 22.860430342439212 │ [ '0x4200000000000000000000000000000000000042', '0x4200000000000000000000000000000000000042' ] │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607', '0x9485aca5bbBE1667AD97c7fE7C4531a624C8b1ED' ] │           │
    │    1    │ '0xFf5713FdbAD797b81539b5F9766859d4E050a6CC' │ 'Polygon'  │ 'merkl' │ 'SUSHI-WETH' │ 100.95034039158989 │         0          │                        [ '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a' ]                        │ [ '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a', '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │           │
    │    2    │                                              │            │         │              │                    │                    │                                                                                                │                                                                                                │ undefined │
    │    3    │                                              │            │         │              │                    │                    │                                                                                                │                                                                                                │ undefined │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴──────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by slasher125** [comment]
gm, not a fan of the api approach. we should at least pull tvl data from on chain
tests are failing cause there are 2 pools with no data...
also, `Values` field shouldn't be there

**Comment by tutacrypto** [comment]
Thanks for you quick comment. On it! 
I'll try to fetch TVL on-chain as well. 

I've fixed the error with the pools with no data, and now have the following one:   

```● Running merkl/index.js Test › Check project field is constant in all pools and if folder name and project field in pool objects matches the information in /protocols slug```
but `merkl` slug is in [api.llama.fi/protocols](https://api.llama.fi/protocols)

Any idea ?

**Comment by slasher125** [comment]
gm, just ran this locally. this is the output i get:

```
Nb of pools: 4
 

Sample pools: [
  {
    pool: '0xf44aCAa38be5E965c5Ddf374E7a2BA270e580684',
    chain: 'Optimism',
    project: 'merkl',
    symbol: 'USDC-agEUR',
    tvlUsd: 713606.4058001989,
    apyReward: 26.158877926846177,
    rewardTokens: [ '0x4200000000000000000000000000000000000042' ],
    underlyingTokens: [
      '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
      '0x9485aca5bbBE1667AD97c7fE7C4531a624C8b1ED'
    ]
  },
  {
    pool: '0xFf5713FdbAD797b81539b5F9766859d4E050a6CC',
    chain: 'Polygon',
    project: 'merkl',
    symbol: 'SUSHI-WETH',
    tvlUsd: 1183.8301612052655,
    apyReward: 194.4828542633871,
    rewardTokens: [
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a'
    ],
    underlyingTokens: [
      '0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a',
      '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619'
    ]
  },
  undefined,
  undefined
]```

- undefined for ethereum and arbitrum? is that intended? if so, u need to remove the undefined from the pool array
- also, rewardTokens contains duplicates

**Pull request merged**
