### PR TITLE
add yield adapter for sft protocol

### PR DESCRIPTION
**Pull request by Sunnight-wj**

### CODE REVIEW

**Comment by llamatester** [comment]
The sft-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────┬────────────────┬────────────┬────────┬────────┐
    │ (index) │                         pool                          │ symbol │    project     │   chain    │ tvlUsd │  apy   │
    ├─────────┼───────────────────────────────────────────────────────┼────────┼────────────────┼────────────┼────────┼────────┤
    │    0    │ '0xe86d3dbd8233f1bfa22679cb57fab3428e9654f7-filecoin' │ 'SFT'  │ 'sft-protocol' │ 'filecoin' │   0    │ 0.2551 │
    └─────────┴───────────────────────────────────────────────────────┴────────┴────────────────┴────────────┴────────┴────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hello, ty for adding. tvlUsd = 0?

**Comment by Sunnight-wj** [comment]
> hello, ty for adding. tvlUsd = 0?

the server was likely to be down that time, now it is work. please add it, thanks.

**Comment by llamatester** [comment]
The sft-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.462 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────┬────────────────┬────────────┬────────────────────┬────────┐
    │ (index) │                         pool                          │ symbol │    project     │   chain    │       tvlUsd       │  apy   │
    ├─────────┼───────────────────────────────────────────────────────┼────────┼────────────────┼────────────┼────────────────────┼────────┤
    │    0    │ '0xe86d3dbd8233f1bfa22679cb57fab3428e9654f7-filecoin' │ 'SFT'  │ 'sft-protocol' │ 'filecoin' │ 3286813.1241549994 │ 0.2681 │
    └─────────┴───────────────────────────────────────────────────────┴────────┴────────────────┴────────────┴────────────────────┴────────┘

**Comment by slasher125** [comment]
just checked your ui, a few things:
- seems we need to scale apy by * 100. 
- the 26.81% is only available for 3 and 12month fixed locks, in which case we need add `poolMeta` = '12 month lock` to the adapter.
- pls add the add the farm with no lock which has ~10% apy

**Comment by llamatester** [comment]
The sft-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.38 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────┬────────────────┬────────────┬───────────────┬───────┬─────────────────┐
    │ (index) │                         pool                          │ symbol │    project     │   chain    │    tvlUsd     │  apy  │    poolMeta     │
    ├─────────┼───────────────────────────────────────────────────────┼────────┼────────────────┼────────────┼───────────────┼───────┼─────────────────┤
    │    0    │ '0xe86d3dbd8233f1bfa22679cb57fab3428e9654f7-filecoin' │ 'SFT'  │ 'sft-protocol' │ 'filecoin' │ 3286918.41804 │ 26.81 │ '12 month lock' │
    └─────────┴───────────────────────────────────────────────────────┴────────┴────────────────┴────────────┴───────────────┴───────┴─────────────────┘

**Comment by Sunnight-wj** [comment]
> 

thanks for your suggestions.I scaled apy by 100 and added a poolMeta alreay.To ignore the farm with no lock is ok, i'm sure. thanks again.

**Pull request merged**
