### PR TITLE
feat: add arbitrove

### PR DESCRIPTION
**Pull request by deboguer-jng**

### CODE REVIEW

**Comment by slasher125** [comment]
him ty for adding
- tvl should be fetched from chain as well

**Comment by deboguer-jng** [comment]
> him ty for adding
> 
> * tvl should be fetched from chain as well

@slasher125 fixed.

**Comment by slasher125** [comment]
apy needs to be scaled to %. also on your ui u show 77%, here the scaled apr is 34%. can u explain the difference?

**Comment by deboguer-jng** [comment]
@slasher125 fixed the issue. the value from our dapp is hardcoded value.

**Pull request merged**
