### PR TITLE
feat: polynomial apy for pools

### PR DESCRIPTION
**Pull request by Aniket965**

### CODE REVIEW

**Comment by llamatester** [comment]
The polynomial-liquidity adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.263 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬────────────────────────┬─────────┬────────────────────┬───────────────────┬────────────────────────────────────────────────────────────────────────┐
    │ (index) │    pool    │    chain     │        project         │ symbol  │       tvlUsd       │      apyBase      │                                  url                                   │
    ├─────────┼────────────┼──────────────┼────────────────────────┼─────────┼────────────────────┼───────────────────┼────────────────────────────────────────────────────────────────────────┤
    │    0    │ '1-fxUSDC' │ 'polynomial' │ 'polynomial-liquidity' │ 'USDC'  │   1578941.369995   │ 12.11406664739747 │ 'https://perps-api-mainnet.polynomial.finance/vaults/all?chainId=8008' │
    │    1    │  '1-sDAI'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sDAI'  │ 135325.96064875834 │ 7.326735432974085 │ 'https://perps-api-mainnet.polynomial.finance/vaults/all?chainId=8008' │
    │    2    │ '1-sUSDe'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sUSDe' │ 126984.86515607352 │ 6.778091520234342 │ 'https://perps-api-mainnet.polynomial.finance/vaults/all?chainId=8008' │
    └─────────┴────────────┴──────────────┴────────────────────────┴─────────┴────────────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hi
- pls provide an invite code so i can check the values
- url should be a link to the pools ui, not the api

**Comment by Aniket965** [comment]
Hey @slasher125 we havent pool ui yet will you need that? 

invite code is ANIKET

**Comment by slasher125** [comment]
> Hey @slasher125 we dont have pool ui yet will you need that?

yes. u can ping me when its ready

**Comment by Aniket965** [comment]
Hey @slasher125 i have added url for liquidity and now we have a pool page https://polynomial.fi/en/mainnet/earn/liquidity
sorry for a delay was busy in some other stuff

**Comment by llamatester** [comment]
The polynomial-liquidity adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.267 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────┬────────────────────────┬─────────┬────────────────────┬────────────────────┬───────────────────────────────────────────────────┐
    │ (index) │    pool    │    chain     │        project         │ symbol  │       tvlUsd       │      apyBase       │                        url                        │
    ├─────────┼────────────┼──────────────┼────────────────────────┼─────────┼────────────────────┼────────────────────┼───────────────────────────────────────────────────┤
    │    0    │ '1-fxUSDC' │ 'polynomial' │ 'polynomial-liquidity' │ 'USDC'  │   1655059.492927   │ 12.003200517207912 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    1    │  '1-sDAI'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sDAI'  │ 139141.96493735598 │ 13.673809149149285 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    │    2    │ '1-sUSDe'  │ 'polynomial' │ 'polynomial-liquidity' │ 'sUSDe' │ 128334.34365299546 │ 5.1832060637362565 │ 'https://polynomial.fi/en/mainnet/earn/liquidity' │
    └─────────┴────────────┴──────────────┴────────────────────────┴─────────┴────────────────────┴────────────────────┴───────────────────────────────────────────────────┘

**Pull request merged**
