### PR TITLE
add xy-finance pools

### PR DESCRIPTION
**Pull request by xy-commit**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running xy-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       39 failed, 231 passed, 270 total
    Snapshots:   0 total
    Time:        0.779 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────┬─────────────────┬──────────────┬────────┬───────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                            pool                            │      chain      │   project    │ symbol │    apyBase    │                   rewardTokens                   │                 underlyingTokens                 │      tvlUsd       │
    ├─────────┼────────────────────────────────────────────────────────────┼─────────────────┼──────────────┼────────┼───────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼───────────────────┤
    │    0    │   '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ethereum'    │   'Ethereum'    │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780584.0829812475 │
    │    1    │    '0xe44fd7fcb2b1581822d0c862b68222998a0c299a-cronos'     │    'Cronos'     │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ 780584.0829812475 │
    │    2    │    '0x2170ed0880ac9a755fd29b2688956bd959f933f8-binance'    │    'Binance'    │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ 780584.0829812475 │
    │    3    │    '0x7ceb23fd6bc0add59e62ac25578270cff1b9f619-polygon'    │    'Polygon'    │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 780584.0829812475 │
    │    4    │    '0x74b23882a30290451a17c44f4f05243b6b58c76d-fantom'     │    'Fantom'     │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ 780584.0829812475 │
    │    5    │   '0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab-avalanche'   │   'Avalanche'   │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ 780584.0829812475 │
    │    6    │   '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-arbitrum'    │   'Arbitrum'    │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780584.0829812475 │
    │    7    │   '0x4200000000000000000000000000000000000006-optimism'    │   'Optimism'    │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0x4200000000000000000000000000000000000006' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 780584.0829812475 │
    │    8    │  '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-zksync era'   │  'zkSync Era'   │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780584.0829812475 │
    │    9    │ '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-polygon zkevm' │ 'Polygon zkEVM' │ 'xy-finance' │ 'ETH'  │ '14.24031366' │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780584.0829812475 │
    └─────────┴────────────────────────────────────────────────────────────┴─────────────────┴──────────────┴────────┴───────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴───────────────────┘
    }

**Comment by llamatester** [comment]
The xy-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       270 passed, 270 total
    Snapshots:   0 total
    Time:        0.411 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬───────────────────────────┬─────────────────┬──────────────┬────────┬─────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────┐
    │ (index) │           pool            │      chain      │   project    │ symbol │   apyBase   │                   rewardTokens                   │                 underlyingTokens                 │      tvlUsd      │
    ├─────────┼───────────────────────────┼─────────────────┼──────────────┼────────┼─────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────┤
    │    0    │   'ypool-eth-ethereum'    │   'Ethereum'    │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780452.956596689 │
    │    1    │    'ypool-eth-cronos'     │    'Cronos'     │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ 780452.956596689 │
    │    2    │    'ypool-eth-binance'    │    'Binance'    │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ 780452.956596689 │
    │    3    │    'ypool-eth-polygon'    │    'Polygon'    │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 780452.956596689 │
    │    4    │    'ypool-eth-fantom'     │    'Fantom'     │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ 780452.956596689 │
    │    5    │   'ypool-eth-avalanche'   │   'Avalanche'   │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ 780452.956596689 │
    │    6    │   'ypool-eth-arbitrum'    │   'Arbitrum'    │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780452.956596689 │
    │    7    │   'ypool-eth-optimism'    │   'Optimism'    │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0x4200000000000000000000000000000000000006' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 780452.956596689 │
    │    8    │  'ypool-eth-zksync era'   │  'zkSync Era'   │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780452.956596689 │
    │    9    │ 'ypool-eth-polygon zkevm' │ 'Polygon zkEVM' │ 'xy-finance' │ 'ETH'  │ 14.24031366 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 780452.956596689 │
    └─────────┴───────────────────────────┴─────────────────┴──────────────┴────────┴─────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────┘

**Comment by slasher125** [comment]
ty for adding, a few things:
- use on chain calls or subgraph to obtain tvl data (ideally apr values too, especially if they can be easily derived from volume) 
- use addresses for pool values (like u had in the initial commit)
- can u briefly explain how apy is identical among the different chains?
- rewardTokens is not required here
- tvlUsd we need to split into the actual deposited amount on the individual chain
- u could add the 7day apy too (apyBase7d)

**Comment by xy-commit** [comment]
Thanks for the quick review!

> ty for adding, a few things:
> 
> * use on chain calls or subgraph to obtain tvl data (ideally apr values too, especially if they can be easily derived from volume)
👍 
> * use addresses for pool values (like u had in the initial commit)
In that commit seems that there's error since duplicated pool id, is it okay I put address other than `ReceivedRewardToken` in the identifier?
> * can u briefly explain how apy is identical among the different chains?
Sure, the APY is a cross-chain settled value is our design, so for example, deposit either on Ethereum or on zkSync Era or whatever chain is the same case to our pool.
> * rewardTokens is not required here
👍 
> * tvlUsd we need to split into the actual deposited amount on the individual chain
👍 
> * u could add the 7day apy too (apyBase7d)
👍

**Comment by llamatester** [comment]
The xy-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       270 passed, 270 total
    Snapshots:   0 total
    Time:        0.424 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬───────────────────────────┬─────────────────┬──────────────┬────────┬─────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬───────────────────┐
    │ (index) │           pool            │      chain      │   project    │ symbol │   apyBase   │                   rewardTokens                   │                 underlyingTokens                 │      tvlUsd       │
    ├─────────┼───────────────────────────┼─────────────────┼──────────────┼────────┼─────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼───────────────────┤
    │    0    │   'ypool-eth-ethereum'    │   'Ethereum'    │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 810443.1090340287 │
    │    1    │    'ypool-eth-cronos'     │    'Cronos'     │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ [ '0xe44Fd7fCb2b1581822D0c862B68222998a0c299a' ] │ 810443.1090340287 │
    │    2    │    'ypool-eth-binance'    │    'Binance'    │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │ 810443.1090340287 │
    │    3    │    'ypool-eth-polygon'    │    'Polygon'    │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ [ '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619' ] │ 810443.1090340287 │
    │    4    │    'ypool-eth-fantom'     │    'Fantom'     │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ [ '0x74b23882a30290451A17c44f4F05243b6b58C76d' ] │ 810443.1090340287 │
    │    5    │   'ypool-eth-avalanche'   │   'Avalanche'   │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ [ '0x49D5c2BdFfac6CE2BFdB6640F4F80f226bc10bAB' ] │ 810443.1090340287 │
    │    6    │   'ypool-eth-arbitrum'    │   'Arbitrum'    │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 810443.1090340287 │
    │    7    │   'ypool-eth-optimism'    │   'Optimism'    │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0x4200000000000000000000000000000000000006' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 810443.1090340287 │
    │    8    │  'ypool-eth-zksync era'   │  'zkSync Era'   │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 810443.1090340287 │
    │    9    │ 'ypool-eth-polygon zkevm' │ 'Polygon zkEVM' │ 'xy-finance' │ 'ETH'  │ 15.08747447 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 810443.1090340287 │
    └─────────┴───────────────────────────┴─────────────────┴──────────────┴────────┴─────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴───────────────────┘

**Comment by llamatester** [comment]
The xy-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       232 passed, 232 total
    Snapshots:   0 total
    Time:        0.623 s
    Ran all test suites.
    
    Nb of pools: 38
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────────────────┬─────────────────┬──────────────┬────────┬─────────────┬─────────────┬──────────────────────────────────────────────────┬────────────────────┐
    │ (index) │                               pool                               │      chain      │   project    │ symbol │   apyBase   │  apyBase7d  │                 underlyingTokens                 │       tvlUsd       │
    ├─────────┼──────────────────────────────────────────────────────────────────┼─────────────────┼──────────────┼────────┼─────────────┼─────────────┼──────────────────────────────────────────────────┼────────────────────┤
    │    0    │  'ypool-0x935283a00fbf8e40fd2f8c432a488f6addc8db67-zksync era'   │  'zkSync Era'   │ 'xy-finance' │ 'ETH'  │ 16.23894192 │ 17.04234255 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 476213.7821240272  │
    │    1    │   'ypool-0x57ea46759fed1b47c200a9859e576239a941df76-ethereum'    │   'Ethereum'    │ 'xy-finance' │ 'ETH'  │ 16.23894192 │ 17.04234255 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 166667.39202297633 │
    │    2    │   'ypool-0x8e921191a9dc6832c1c360c7c7b019efb7c29b2d-ethereum'    │   'Ethereum'    │ 'xy-finance' │ 'USDT' │ 1.25517396  │ 0.94211662  │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ 141566.14377705797 │
    │    3    │   'ypool-0x680ab543acd0e52035e9d409014dd57861fa1edf-arbitrum'    │   'Arbitrum'    │ 'xy-finance' │ 'USDC' │ 2.00653517  │ 4.87788972  │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ 109522.89143224538 │
    │    4    │   'ypool-0x3d2d1ce29b8bc997733d318170b68e63150c6586-avalanche'   │   'Avalanche'   │ 'xy-finance' │ 'USDT' │ 1.25517396  │ 0.94211662  │ [ '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7' ] │ 106551.98333079298 │
    │    5    │    'ypool-0xf526efc174b512e66243cb52524c1be720144e8d-kucoin'     │    'Kucoin'     │ 'xy-finance' │ 'USDT' │ 1.25517396  │ 0.94211662  │ [ '0x0039f574eE5cC39bdD162E9A88e3EB1f111bAF48' ] │ 91038.62928133196  │
    │    6    │    'ypool-0xb238d4339a44f93abcf4071a9bb0f55d2403fd84-klaytn'     │    'Klaytn'     │ 'xy-finance' │ 'USDC' │ 2.00653517  │ 4.87788972  │ [ '0x754288077D0fF82AF7a5317C7CB8c444D421d103' ] │ 90511.24147645372  │
    │    7    │    'ypool-0x74a0eea77e342323aa463098e959612d3fe6e686-cronos'     │    'Cronos'     │ 'xy-finance' │ 'USDT' │ 1.25517396  │ 0.94211662  │ [ '0x66e428c3f67a68878562e79A0234c1F83c208770' ] │ 87054.67190620198  │
    │    8    │ 'ypool-0x9fe77412aa5c6ba67ff3095bbc534884f9a61a38-polygon zkevm' │ 'Polygon zkEVM' │ 'xy-finance' │ 'ETH'  │ 16.23894192 │ 17.04234255 │ [ '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' ] │ 67408.95477234687  │
    │    9    │    'ypool-0xf4137e5d07b476e5a30f907c3e31f9faab00716b-polygon'    │    'Polygon'    │ 'xy-finance' │ 'USDC' │ 2.00653517  │ 4.87788972  │ [ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174' ] │ 65514.886600033424 │
    └─────────┴──────────────────────────────────────────────────────────────────┴─────────────────┴──────────────┴────────┴─────────────┴─────────────┴──────────────────────────────────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
looking gud now. any reason for the `ypool` prefix? if not then i'd remove it

**Pull request merged**
