### PR TITLE
added ladex farms

### PR DESCRIPTION
**Pull request by kunalgoyal9**

### CODE REVIEW

**Comment by kunalgoyal9** [comment]
@vrtnd please review this PR

**Comment by llamatester** [comment]
The lachain-yield-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.517 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬──────┬───────────┬────────────────────────┬─────────────┬─────────────┬───────────────────┐
    │ (index) │ pool │   chain   │        project         │   symbol    │   tvlUsd    │        apy        │
    ├─────────┼──────┼───────────┼────────────────────────┼─────────────┼─────────────┼───────────────────┤
    │    0    │ '1'  │ 'lachain' │ 'lachain-yield-market' │ 'wUSDT/LA'  │ 3218.994187 │     162.8218      │
    │    1    │ '3'  │ 'lachain' │ 'lachain-yield-market' │  'LA/wBNB'  │ 2327.320981 │     450.4085      │
    │    2    │ '5'  │ 'lachain' │ 'lachain-yield-market' │  'LA/wETH'  │ 2233.680376 │     469.2906      │
    │    3    │ '4'  │ 'lachain' │ 'lachain-yield-market' │ 'LA/wMATIC' │ 1442.480472 │     726.6963      │
    │    4    │ '0'  │ 'lachain' │ 'lachain-yield-market' │  'LA/wFTM'  │ 1238.610479 │     846.3074      │
    │    5    │ '2'  │ 'lachain' │ 'lachain-yield-market' │ 'LA/wAVAX'  │ 1182.379393 │ 886.5557000000001 │
    └─────────┴──────┴───────────┴────────────────────────┴─────────────┴─────────────┴───────────────────┘

**Comment by vrtnd** [comment]
Hi, thanks for the PR.
I'll merg it, but it will not be visible until `tvl>10k`

**Comment by kunalgoyal9** [comment]
@vrtnd It is already greater than 10k. 
will it be visible?

**Comment by vrtnd** [comment]
As I can see it's not. Highest tvl is 3218$

**Pull request merged**
