### PR TITLE
Update Brinc Finance Staking Pools

### PR DESCRIPTION
**Pull request by Opyet**
### Changes
- Staking Pools Duration
30days -> 7days
90days -> 30days
180days -> 90days
- APY calculation (now week-based)
- Remove console logs and unnecessary check
- Minimise requests for essential on-chain elements

### CODE REVIEW

**Comment by slasher125** [comment]
is it on purpose that you have changed the pool id's?
right now we have:
```
  {
    "pool": "pool5-brinc-finance-staking",
    "chain": "Arbitrum",
    "project": "brinc-finance",
    "symbol": "BRC-gBRC(180Days)",
    "tvlUsd": 154125,
    "apy": 156511.4508085873,
    "rewardTokens": ["0x62C7e128e7c3205964429F58A0C6f63a776D10d1"],
    "underlyingTokens": [
      "0xB5de3f06aF62D8428a8BF7b4400Ea42aD2E0bc53",
      "0x62C7e128e7c3205964429F58A0C6f63a776D10d1"
    ]
  },
```

vs (the PR):
```
  {
    "pool": "pool6-brinc-finance-staking",
    "chain": "Arbitrum",
    "project": "brinc-finance",
    "symbol": "BRC-gBRC(90Days)",
    "tvlUsd": 154125,
    "apy": 4366.86912188429,
    "rewardTokens": ["0x62C7e128e7c3205964429F58A0C6f63a776D10d1"],
    "underlyingTokens": [
      "0xB5de3f06aF62D8428a8BF7b4400Ea42aD2E0bc53",
      "0x62C7e128e7c3205964429F58A0C6f63a776D10d1"
    ]
  },
```

given the large reduction in staking duration, i wonder if we want to display the old history?

**Comment by Opyet** [comment]
No specific purpose. It seemed starting from 1 was more intuitive than starting from 0. Please let me know if to revert to old numbering.

We should maintain the history if possible. The pool hasn't changed neither have the stakes in them. Only the duration has changed.

**Comment by slasher125** [comment]
ok. in that case, lets make sure that the pool id's match what we currently have in master

**Comment by Opyet** [comment]
Thanks @slasher125 . The pools' Ids have now been restored.

**Pull request merged**
