### PR TITLE
Add gmd-protocol

### PR DESCRIPTION
**Pull request by quantsimp**

### CODE REVIEW

**Comment by llamatester** [comment]
The gmd-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.36 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬───────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │    project     │  symbol   │       tvlUsd       │      apyBase       │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼───────────┼────────────────────┼────────────────────┤
    │    0    │ '0x4A723DE8aF2be96292dA3F824a96bfA053d4aF66' │ 'Arbitrum' │ 'gmd-protocol' │ 'gmdUSDC' │ 4234596.648835301  │ 18.437350000000002 │
    │    1    │ '0xc5182E92bf001baE7049c4496caD96662Db1A186' │ 'Arbitrum' │ 'gmd-protocol' │ 'gmdETH'  │ 2041580.5959767099 │ 18.437350000000002 │
    │    2    │ '0xEffaE8eB4cA7db99e954adc060B736Db78928467' │ 'Arbitrum' │ 'gmd-protocol' │ 'gmdBTC'  │ 1020870.0324985209 │ 18.437350000000002 │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴───────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
gm and ty for adding. 
- we no longer accept pure api based adapters so pls refactor to on chain calls/subgraph instead.
- change the symbol do the underlying symbol USDC, BTC etc (cause this is what will be deposited)

**Comment by llamatester** [comment]
The gmd-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.321 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │    project     │ symbol │       tvlUsd       │      apyBase       │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼────────┼────────────────────┼────────────────────┤
    │    0    │ '0x4A723DE8aF2be96292dA3F824a96bfA053d4aF66' │ 'Arbitrum' │ 'gmd-protocol' │ 'USDC' │ 3217724.510678475  │ 11.571850000000001 │
    │    1    │ '0xc5182E92bf001baE7049c4496caD96662Db1A186' │ 'Arbitrum' │ 'gmd-protocol' │ 'ETH'  │ 1879412.3698424404 │       9.3729       │
    │    2    │ '0xEffaE8eB4cA7db99e954adc060B736Db78928467' │ 'Arbitrum' │ 'gmd-protocol' │ 'BTC'  │ 934522.7481599683  │       9.3729       │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴────────┴────────────────────┴────────────────────┘

**Comment by quantsimp** [comment]
> gm and ty for adding.
> 
> * we no longer accept pure api based adapters so pls refactor to on chain calls/subgraph instead.
> * change the symbol do the underlying symbol USDC, BTC etc (cause this is what will be deposited)

Thanks for the helpful feedback! I have fixed the problems as you suggested, please take a look

**Comment by llamatester** [comment]
The gmd-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.462 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────┬────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │    project     │ symbol │       tvlUsd       │      apyBase       │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────┼────────┼────────────────────┼────────────────────┤
    │    0    │ '0x4A723DE8aF2be96292dA3F824a96bfA053d4aF66' │ 'Arbitrum' │ 'gmd-protocol' │ 'USDC' │ 2391380.707933835  │ 11.571850000000001 │
    │    1    │ '0xc5182E92bf001baE7049c4496caD96662Db1A186' │ 'Arbitrum' │ 'gmd-protocol' │ 'ETH'  │ 2181202.202209322  │       9.3729       │
    │    2    │ '0xEffaE8eB4cA7db99e954adc060B736Db78928467' │ 'Arbitrum' │ 'gmd-protocol' │ 'BTC'  │ 1112042.0943293532 │       9.3729       │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────┴────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
@quantsimp great, thank u! one last q: do these pools require a minimum lockup duration or can i withdraw at any time?

**Comment by quantsimp** [comment]
you can withdraw anytime

**Pull request merged**
