### PR TITLE
Added Aries Markets yield server.

### PR DESCRIPTION
**Pull request by leofisG**

### CODE REVIEW

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.267 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────┬────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apy         │      apyBase       │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────┼────────────────────┤
    │    0    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 11073958.678017551 │ 17.621073817185362 │ 17.621073817185362 │
    │    1    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 8459712.482407968  │ 17.988863295706388 │ 17.988863295706388 │
    │    2    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 7776982.654858634  │ 18.776044637315785 │ 18.776044637315785 │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────┴────────────────────┘

**Comment by leofisG** [comment]
@0xngmi please take a look and let me know your feedback.

**Comment by slasher125** [comment]
hi, ty for adding. 
- any reason the other pools aren't included?
- u can remove the apy field
- apyBase must be excluding rewards
- apyReward = ur aptos reward apy
- ideally you add the borrow fields too (see readme)

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       40 passed, 40 total
    Snapshots:   0 total
    Time:        0.275 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │  905000000.021338  │ 0.00015287285206002125 │         0          │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    1    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 12311775.886298671 │   3.5296815213112414   │ 11.87338864433694  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    2    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 9839953.054166554  │   3.2754540400750067   │ 11.554679110166772 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 7924955.008822491  │   3.125011731503792    │ 14.346769145493665 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    4    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2380000.008054196  │ 0.00008987029450877066 │         0          │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │ 1632807.351614164  │  0.013831157393278426  │ 19.89518234829474  │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.272 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │ 914957858.4707595  │ 0.00015288703102049232 │                    │                                  │
    │    1    │  'aries-markets-apt'  │ 'Aptos' │ 'aries-markets' │  'APT'  │ 21951321.669741496 │   0.2845578061187094   │                    │                                  │
    │    2    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 12330311.066596478 │   3.529993747440896    │ 11.908823646614776 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 9854810.508658804  │   3.2824494745994963   │ 11.58911172362494  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    4    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 7930898.501477469  │   3.1246967230989036   │  14.4004490763214  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2400000.008121878  │ 0.00008987029450877066 │                    │                                  │
    │    6    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │ 1647026.8143347374 │  0.013831157393278426  │ 19.812063602121878 │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.27 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │  'aries-markets-apt'  │ 'Aptos' │ 'aries-markets' │  'APT'  │ 21951322.055123325 │   0.2845642386096796   │                    │                                  │
    │    1    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 12330311.066596478 │   3.529993747440896    │ 11.908823646614776 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    2    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 9854810.508658804  │   3.2824494745994963   │ 11.58911172362494  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │ 9149578.584707595  │ 0.00015288703102049232 │                    │                                  │
    │    4    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 7930898.501477469  │   3.1246967230989036   │  14.4004490763214  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2400000.008121878  │ 0.00008987029450877066 │                    │                                  │
    │    6    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │ 1647026.8143347374 │  0.013831157393278426  │ 19.812063602121878 │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Comment by leofisG** [comment]
@slasher125 can you take another look?

I have:
- added more pools, some pools are not there because they are a lot smaller and also doesn't have reward so we don't want to promote them as much
- added `rewardapy`

For the borrow fields, it will be nice if we can add it later as we need to land this ASAP.

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.275 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │  'aries-markets-apt'  │ 'Aptos' │ 'aries-markets' │  'APT'  │ 21951322.994956225 │   0.2845643056206989   │                    │                                  │
    │    1    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 12330520.703057894 │   3.529993747440896    │ 11.908621179605554 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    2    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 9854989.504876928  │   3.282176166525534    │ 11.588901230537259 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │ 9129579.505833918  │ 0.00015288703102049232 │                    │                                  │
    │    4    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 7930898.501477469  │   3.1246967230989036   │  14.4004490763214  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2400000.008121878  │ 0.00008987029450877066 │                    │                                  │
    │    6    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │ 1646426.7619445617 │  0.013814177626841282  │ 19.819284254988773 │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Comment by slasher125** [comment]
tvlUsd = totalSupplyUsd - totalBorrowUsd

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.27 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │  'aries-markets-apt'  │ 'Aptos' │ 'aries-markets' │  'APT'  │ 17128369.606077287 │   0.2843117212028767   │                    │                                  │
    │    1    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │ 9007668.327928225  │ 0.00015306583536307513 │                    │                                  │
    │    2    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 4612674.448984511  │   3.5345847620970794   │ 11.857554839820029 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 3914045.576725002  │   3.2790645698906626   │ 11.540554613105744 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    4    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 3239148.6093397927 │   3.143964303482986    │ 14.38714917479453  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2412547.533225694  │ 0.00009483543172580292 │                    │                                  │
    │    6    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │  1596496.91237482  │  0.013702312622452547  │ 19.59767067665764  │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Comment by leofisG** [comment]
@slasher125 fixed, ser 🙇

**Comment by llamatester** [comment]
The aries-markets adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       43 passed, 43 total
    Snapshots:   0 total
    Time:        0.278 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬─────────┬─────────────────┬─────────┬────────────────────┬────────────────────────┬────────────────────┬──────────────────────────────────┐
    │ (index) │         pool          │  chain  │     project     │ symbol  │       tvlUsd       │        apyBase         │     apyReward      │           rewardTokens           │
    ├─────────┼───────────────────────┼─────────┼─────────────────┼─────────┼────────────────────┼────────────────────────┼────────────────────┼──────────────────────────────────┤
    │    0    │  'aries-markets-apt'  │ 'Aptos' │ 'aries-markets' │  'APT'  │ 17109167.47551898  │   0.2843117516589339   │                    │                                  │
    │    1    │ 'aries-markets-stApt' │ 'Aptos' │ 'aries-markets' │ 'STAPT' │ 9017871.673634702  │ 0.0001530581076055982  │                    │                                  │
    │    2    │ 'aries-markets-zusdc' │ 'Aptos' │ 'aries-markets' │ 'ZUSDC' │ 4608071.455813413  │   3.5345852987186794   │ 11.856091314841807 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    3    │ 'aries-markets-usdc'  │ 'Aptos' │ 'aries-markets' │ 'USDC'  │ 3910139.3436144977 │   3.2790645698906626   │ 11.539132872282172 │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    4    │ 'aries-markets-zusdt' │ 'Aptos' │ 'aries-markets' │ 'ZUSDT' │ 3239148.6093397927 │   3.143964303482986    │  14.3710200837914  │ [ '0x1::aptos_coin::AptosCoin' ] │
    │    5    │ 'aries-markets-cake'  │ 'Aptos' │ 'aries-markets' │ 'CAKE'  │ 2412547.533225694  │ 0.00009483543172580292 │                    │                                  │
    │    6    │ 'aries-markets-zweth' │ 'Aptos' │ 'aries-markets' │ 'ZWETH' │ 1597023.0778793322 │  0.013702312622452547  │ 19.569250657626476 │ [ '0x1::aptos_coin::AptosCoin' ] │
    └─────────┴───────────────────────┴─────────┴─────────────────┴─────────┴────────────────────┴────────────────────────┴────────────────────┴──────────────────────────────────┘

**Pull request merged**
