### PR TITLE
Track Curve lending markets

### PR DESCRIPTION
**Pull request by benber86**
Add Curve Lending markets from: https://lend.curve.fi/#/ethereum/markets?type=supply

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running curve-lending adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 110 passed, 111 total
    Snapshots:   0 total
    Time:        0.323 s
    Ran all test suites.
    
    Nb of pools: 17
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬──────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │     symbol      │       tvlUsd       │                 underlyingTokens                 │                                    url                                    │       apyBase        │   apyBaseBorrow    │   totalSupplyUsd   │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xCeA18a8752bb7e7817F9AE7565328FE415C0f2cA-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-CRV'   │ 29853159.491332944 │ [ '0xd533a949740bb3306d119cc777fa900ba034cd52' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-3/vault/deposit' │  38.75515721922342   │ 47.89226485394895  │ 29853159.491332944 │  2.04561006730621  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    1    │ '0x60D38b12d22BF423F28082bf396ff8F28cC506B1-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-WBTC'  │ 2388861.281438647  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-1/vault/deposit' │  10.265526711388784  │ 16.654681028981933 │ 2388861.281438647  │     undefined      │                    undefined                     │
    │    2    │ '0x49014A8eB1585cBee6A7a9A50C3b81017BF6Cc4d-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-WETH'  │ 2157359.438418412  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-0/vault/deposit' │  7.2341285346324335  │ 13.142961648760188 │ 2157359.438418412  │     undefined      │                    undefined                     │
    │    3    │ '0xeEaF2ccB73A01deb38Eca2947d963D64CfDe6A32-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-CRV'   │ 1767285.608808964  │ [ '0x11cdb42b0eb46d95f990bedd4695a6e3fa034978' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-4/vault/deposit' │  12.630113151940336  │ 23.067755273802604 │ 1767285.608808964  │     undefined      │                    undefined                     │
    │    4    │ '0x65592b1F12c07D434e95c7BF87F4f2f464e950e4-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-ARB'   │  1522598.4949328   │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-5/vault/deposit' │  0.9454926371637917  │ 7.236536799849613  │  1522598.4949328   │     undefined      │                    undefined                     │
    │    5    │ '0x8cf1DE26729cfB7137AF1A6B2a665e099EC319b5-ethereum' │ 'Ethereum' │ 'curve-lending' │ 'crvUSD-wstETH' │ 1143635.164867191  │ [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-0/vault/deposit' │  14.852748100576441  │ 18.54148038638477  │ 1143635.164867191  │ 11.931131820858692 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    6    │ '0xb2b23C87a4B6d1b03Ba603F7C3EB9A81fDC0AAC9-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-tBTC'  │ 911964.4621749324  │ [ '0x18084fba666a33d37592fa2633fd49a74dd93a88' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-2/vault/deposit' │  6.1248433775511035  │ 8.440202358655458  │ 911964.4621749324  │ 16.141438985958704 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    7    │ '0x5AE28c9197a4a6570216fC7e53E7e0221D7A0FEF-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-WETH'  │ 569649.3627803199  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-1/vault/deposit' │  11.691458728814563  │ 14.457652221890127 │ 569649.3627803199  │ 25.91112213525047  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    8    │ '0x52096539ed1391CB50C6b9e4Fd18aFd2438ED23b-ethereum' │ 'Ethereum' │ 'curve-lending' │ 'crvUSD-sUSDe'  │ 560253.2783972946  │ [ '0x9d39a5de30e57443bff2a8307a4256c8797a3497' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-7/vault/deposit' │  1.065147022161983   │ 2.9328756387603683 │ 560253.2783972946  │ 31.193146447351218 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    9    │ '0x99Cff9Dc26A44dc2496B4448ebE415b5E894bd30-ethereum' │ 'Ethereum' │ 'curve-lending' │  'tBTC-crvUSD'  │ 188437.4764223542  │ [ '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-6/vault/deposit' │ 2.958999711921706e-7 │ 0.5012498582754876 │ 188437.4764223542  │     undefined      │                    undefined                     │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┴──────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
Error while running curve-lending adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 110 passed, 111 total
    Snapshots:   0 total
    Time:        0.305 s
    Ran all test suites.
    
    Nb of pools: 17
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬──────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │     symbol      │       tvlUsd       │                 underlyingTokens                 │                                    url                                    │       apyBase        │   apyBaseBorrow    │   totalSupplyUsd   │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xCeA18a8752bb7e7817F9AE7565328FE415C0f2cA-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-CRV'   │ 29853450.18819578  │ [ '0xd533a949740bb3306d119cc777fa900ba034cd52' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-3/vault/deposit' │  38.75527968243433   │ 47.89226485394895  │ 29853450.18819578  │ 2.0402461255874513 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    1    │ '0x60D38b12d22BF423F28082bf396ff8F28cC506B1-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-WBTC'  │ 2388859.0661920873 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-1/vault/deposit' │  10.265558376828032  │ 16.654681028981933 │ 2388859.0661920873 │     undefined      │                    undefined                     │
    │    2    │ '0x49014A8eB1585cBee6A7a9A50C3b81017BF6Cc4d-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-WETH'  │ 2157354.3001666884 │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-0/vault/deposit' │  7.234149493166275   │ 13.142961648760188 │ 2157354.3001666884 │     undefined      │                    undefined                     │
    │    3    │ '0xeEaF2ccB73A01deb38Eca2947d963D64CfDe6A32-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-CRV'   │ 1767285.928286163  │ [ '0x11cdb42b0eb46d95f990bedd4695a6e3fa034978' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-4/vault/deposit' │  12.632463563934348  │ 23.07060556938385  │ 1767285.928286163  │     undefined      │                    undefined                     │
    │    4    │ '0x65592b1F12c07D434e95c7BF87F4f2f464e950e4-arbitrum' │ 'Arbitrum' │ 'curve-lending' │  'crvUSD-ARB'   │ 1522590.068236389  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-5/vault/deposit' │  0.9454956331037101  │ 7.236536799849613  │ 1522590.068236389  │     undefined      │                    undefined                     │
    │    5    │ '0x8cf1DE26729cfB7137AF1A6B2a665e099EC319b5-ethereum' │ 'Ethereum' │ 'curve-lending' │ 'crvUSD-wstETH' │ 1143637.1626296672 │ [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-0/vault/deposit' │  14.852769332764337  │ 18.54148038638477  │ 1143637.1626296672 │ 11.899965414020262 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    6    │ '0xb2b23C87a4B6d1b03Ba603F7C3EB9A81fDC0AAC9-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-tBTC'  │ 911963.0113099625  │ [ '0x18084fba666a33d37592fa2633fd49a74dd93a88' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-2/vault/deposit' │  6.124849126528331   │ 8.440202358655458  │ 911963.0113099625  │ 16.09934173945703  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    7    │ '0x5AE28c9197a4a6570216fC7e53E7e0221D7A0FEF-ethereum' │ 'Ethereum' │ 'curve-lending' │  'crvUSD-WETH'  │ 569649.6872541028  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-1/vault/deposit' │  11.691471491107563  │ 14.457652221890127 │ 569649.6872541028  │ 25.843475408652427 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    8    │ '0x52096539ed1391CB50C6b9e4Fd18aFd2438ED23b-ethereum' │ 'Ethereum' │ 'curve-lending' │ 'crvUSD-sUSDe'  │ 560251.2316261509  │ [ '0x9d39a5de30e57443bff2a8307a4256c8797a3497' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-7/vault/deposit' │  1.0651478503826528  │ 2.9328756387603683 │ 560251.2316261509  │ 31.11187434941828  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    9    │ '0x99Cff9Dc26A44dc2496B4448ebE415b5E894bd30-ethereum' │ 'Ethereum' │ 'curve-lending' │  'tBTC-crvUSD'  │ 188295.74748791818 │ [ '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-6/vault/deposit' │ 2.958999711921706e-7 │ 0.5012498582754876 │ 188295.74748791818 │     undefined      │                    undefined                     │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┴──────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by slasher125** [comment]
gm, we don't track a project called `curve-lending` but only `curve-llamalend`. guess that was pushed by mistake, pls remove the curve-lending adapter from the pr

**Comment by llamatester** [comment]
The curve-llamalend adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       117 passed, 117 total
    Snapshots:   0 total
    Time:        0.289 s
    Ran all test suites.
    
    Nb of pools: 18
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │      project      │     symbol      │       tvlUsd       │                 underlyingTokens                 │                                    url                                    │      apyBase       │   apyBaseBorrow    │   totalSupplyUsd   │     apyReward      │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xCeA18a8752bb7e7817F9AE7565328FE415C0f2cA-ethereum' │ 'Ethereum' │ 'curve-llamalend' │  'crvUSD-CRV'   │ 35419922.03391573  │ [ '0xd533a949740bb3306d119cc777fa900ba034cd52' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-3/vault/deposit' │ 28.457884550068368 │ 37.34645054662376  │ 35419922.03391573  │ 1.7506840395701186 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    1    │ '0x60D38b12d22BF423F28082bf396ff8F28cC506B1-arbitrum' │ 'Arbitrum' │ 'curve-llamalend' │  'crvUSD-WBTC'  │ 2174357.6793964463 │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-1/vault/deposit' │ 8.777831198354757  │ 14.962895265339071 │ 2174357.6793964463 │     undefined      │                    undefined                     │
    │    2    │ '0x49014A8eB1585cBee6A7a9A50C3b81017BF6Cc4d-arbitrum' │ 'Arbitrum' │ 'curve-llamalend' │  'crvUSD-WETH'  │ 2093044.6193311838 │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-0/vault/deposit' │  8.19775991367635  │ 14.287662531567724 │ 2093044.6193311838 │     undefined      │                    undefined                     │
    │    3    │ '0xeEaF2ccB73A01deb38Eca2947d963D64CfDe6A32-arbitrum' │ 'Arbitrum' │ 'curve-llamalend' │  'crvUSD-CRV'   │ 2040705.7636002165 │ [ '0x11cdb42b0eb46d95f990bedd4695a6e3fa034978' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-4/vault/deposit' │ 8.563526757506356  │ 18.320512281855628 │ 2040705.7636002165 │     undefined      │                    undefined                     │
    │    4    │ '0x7586C58bf6292B3C9DeFC8333fc757d6c5dA0f7E-ethereum' │ 'Ethereum' │ 'curve-llamalend' │  'crvUSD-UwU'   │ 1999270.8061535368 │ [ '0x55c08ca52497e2f1534b59e2917bf524d4765257' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-8/vault/deposit' │ 9.263077245831553  │ 13.896606060979199 │ 1999270.8061535368 │     undefined      │                    undefined                     │
    │    5    │ '0x65592b1F12c07D434e95c7BF87F4f2f464e950e4-arbitrum' │ 'Arbitrum' │ 'curve-llamalend' │  'crvUSD-ARB'   │ 1521131.002921069  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 'https://lend.curve.fi/#/arbitrum/markets/one-way-market-5/vault/deposit' │ 1.0479839847734596 │ 7.437306796818999  │ 1521131.002921069  │     undefined      │                    undefined                     │
    │    6    │ '0x8cf1DE26729cfB7137AF1A6B2a665e099EC319b5-ethereum' │ 'Ethereum' │ 'curve-llamalend' │ 'crvUSD-wstETH' │ 1190038.7610333099 │ [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-0/vault/deposit' │ 11.558251446796541 │ 14.991635595368225 │ 1190038.7610333099 │ 12.640992227470868 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    7    │ '0x5AE28c9197a4a6570216fC7e53E7e0221D7A0FEF-ethereum' │ 'Ethereum' │ 'curve-llamalend' │  'crvUSD-WETH'  │ 926674.5383344471  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-1/vault/deposit' │ 9.721234855704907  │ 12.385080664267534 │ 926674.5383344471  │ 16.331899245164646 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    8    │ '0xb2b23C87a4B6d1b03Ba603F7C3EB9A81fDC0AAC9-ethereum' │ 'Ethereum' │ 'curve-llamalend' │  'crvUSD-tBTC'  │ 912110.8949587048  │ [ '0x18084fba666a33d37592fa2633fd49a74dd93a88' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-2/vault/deposit' │ 7.001216337580551  │ 9.424889316405526  │ 912110.8949587048  │ 17.29303551795586  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    │    9    │ '0x52096539ed1391CB50C6b9e4Fd18aFd2438ED23b-ethereum' │ 'Ethereum' │ 'curve-llamalend' │ 'crvUSD-sUSDe'  │ 615747.2099333853  │ [ '0x9d39a5de30e57443bff2a8307a4256c8797a3497' ] │ 'https://lend.curve.fi/#/ethereum/markets/one-way-market-7/vault/deposit' │  6.02599567470079  │  9.97610985186055  │ 615747.2099333853  │ 30.309046597172284 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by benber86** [comment]
> @benber86 gm, we don't track a project called `curve-lending` but only `curve-llamalend`. guess that was pushed by mistake, pls remove the curve-lending adapter from the pr

apologies for the oversight

**Pull request merged**
