### PR TITLE
Add Clearpool Protocol

### PR DESCRIPTION
**Pull request by zolotokrylin**
🚀 
__________
_Orig issue: https://github.com/clearpool-finance/clearpool.finance/issues/31_

### CODE REVIEW

**Comment by llamatester** [comment]
The clearpool adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       74 passed, 74 total
    Snapshots:   0 total
    Time:        0.348 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────┬──────────────┬─────────────────┬──────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────┐
    │ (index) │                         pool                          │   chain    │   project   │    symbol    │     tvlUsd      │     apyBase      │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │  poolMeta   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────┼──────────────┼─────────────────┼──────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────┤
    │    0    │ '0xcb288b6d30738db7e3998159d192615769794b5b-ethereum' │ 'Ethereum' │ 'clearpool' │ 'cpWIN-USDC' │ 21949643.728075 │  7.892146158768  │ 2.526870983169664  │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V2 market' │
    │    1    │ '0x9f8e69786de448e6805c0f75eadbc9323502b194-polygon'  │ 'Polygon'  │ 'clearpool' │ 'cpWIN-USDC' │ 15922204.03984  │ 7.7890104080928  │ 2.6001279524098933 │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │ 'V2 market' │
    │    2    │ '0xe3d20a721522874d32548b4097d1afc6f024e45b-ethereum' │ 'Ethereum' │ 'clearpool' │ 'cpFOL-USDC' │ 10261168.998242 │  7.020733993272  │ 2.319764798361076  │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V2 market' │
    │    3    │ '0x3aeb3a8f0851249682a6a836525cdeee5aa2a153-ethereum' │ 'Ethereum' │ 'clearpool' │ 'cpAUR-USDC' │ 7127449.051791  │  7.008502393008  │ 2.223526425037062  │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V2 market' │
    │    4    │ '0xb254554636a3ff52e8b2d0f06203921c137e10d5-polygon'  │ 'Polygon'  │ 'clearpool' │ 'cpAUR-USDC' │ 6973518.726625  │ 7.2515758355568  │ 2.8436497647697845 │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │ 'V2 market' │
    │    5    │ '0x3f6e10b1ee2882c8278b3e471230e143414ccaa9-polygon'  │ 'Polygon'  │ 'clearpool' │ 'cpPAR-USDC' │ 5992334.577805  │ 7.4213477502624  │ 2.6351055965020858 │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │ 'V2 market' │
    │    6    │ '0x876057afb6f125d89f0b716ac815d79686b4f2fd-polygon'  │ 'Polygon'  │ 'clearpool' │ 'cpFOL-USDC' │ 5789993.254829  │ 7.4703121143552  │ 2.3946458224452307 │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │ 'V2 market' │
    │    7    │ '0x24b2d3746e39626d4352891ff909d4f3176be245-polygon'  │ 'Polygon'  │ 'clearpool' │ 'cpAMB-USDC' │  4293936.45203  │ 12.6020231196912 │ 1.8473486755287232 │ [ '0xb08b3603C5F2629eF83510E6049eDEeFdc3A2D91' ] │ [ '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ] │ 'V2 market' │
    │    8    │ '0x7b7e4ab1ecf7a69c1f15b186f9af11bb53e764cb-ethereum' │ 'Ethereum' │ 'clearpool' │ 'cpAMB-USDC' │ 3791028.496264  │ 7.3822390263504  │ 1.0390147869921946 │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V2 market' │
    │    9    │ '0xbc105b92f6350e02f230e58cd4240ea76d7d1dca-ethereum' │ 'Ethereum' │ 'clearpool' │ 'cpFBG-USDC' │    29.465807    │        0         │         0          │ [ '0x66761fa41377003622aee3c7675fc7b5c1c2fac5' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ 'V2 market' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────┴──────────────┴─────────────────┴──────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────┘

**Comment by vrtnd** [comment]
Hi, please change tvl usd to `totalSupply - totalBorrow` formula

**Comment by zolotokrylin** [comment]
hi @vrtnd , 
our loans are not based on collateral but based on credit rating. Meaning, that our value locked equals the total liquidity provided. These equation `totalSupply - totalBorrow` resolves into cash left in the pool, but not the value locked. Value locked in Clearpool case is `totalCash + totalBorrow`. A more detailed explanation can be found in our [Whitepaper](https://docs.clearpool.finance/clearpool/resources/whitepaper).

**Comment by vrtnd** [comment]
Okay, but i opened first `cpWIN-USDC` pool and it has $8.8m tvl not $21m from adapter output
https://etherscan.io/address/0xcb288b6d30738db7e3998159d192615769794b5b

**Comment by zolotokrylin** [comment]
@vrtnd thanks for the quick revert.
It is a correct value https://app.clearpool.finance/lend?market=mainnet
image

It is the total value of this pool. This is how much was lent into that pool. Basically, this is the amount up to which the borrower can withdraw. In other words, this is the value that is locked in that particular pool. It is [unsecured loan](https://www.investopedia.com/terms/u/unsecuredloan.asp#:~:text=An%20unsecured%20loan%20is%20a,student%20loans%2C%20and%20credit%20cards.), as I mentioned here https://github.com/DefiLlama/yield-server/pull/327#issuecomment-1250006805.

This amount (`23,869,400 USDC`) is the amount of USDC that is locked[ in the pool](https://app.clearpool.finance/pool/0xCb288b6d30738db7E3998159d192615769794B5b?market=mainnet).

**Comment by slasher125** [comment]
henlo @zolotokrylin 

i've read the messages here, checked the project too, and still I'm somewhat confused 🤔
Let me try to summarise by taking the wintermute pool as an example:
- there have been ~$24mil usdc deposits on ethereum (= total supply) for a pool which only wintermute can borrow from
- wintermute has borrowed ~15$mil usdc (= total borrowed) 
- that leaves them with a max additional $8mil usdc (= available liquidity) which they can borrow

The way we have approached this so far for every lending protocol is to use the available liquidity (total supply - total borrowed) as tvl. 

What I don't understand is why you see tvl = total supply in your case, independent if its collateral or credit rating based? 

My suggestion: lets stick to tvl = total_supply - total_borrowed to stay consistent among lending projects.
also, fyi: very soon we gonna give lending projects more love where we'll display total supplied and total borrowed as in your screenshot. that should then make things much clearer.

**Comment by slasher125** [comment]
One other thing: pls change the pool fields to `USDC` instead of `cpWIN-USDC`. instead put the `cpWIN` or `Wintermute` in the `metaPool` field. on the frontend it'd then read like: `USDC (cpWIN)` or `USDC (Wintermute)` respectively. 
otherwise we might incorrectly identify this as multi exposure

**Comment by zolotokrylin** [comment]
hello @slasher125 
We have implemented it as you have asked. Please review.

**Comment by zolotokrylin** [comment]
------
P.S. I understand your view, but our loans are uncollateralized. (see explainer above)
The bigger is the pool, the more liquidity was provided based on the agreement between Borrower and Lenders. Which is good. And this is the TVL in our protocol sense.

But when liquidity is drawn (borrowed) from the pool by borrower, what you call TVL will be decreased. The more pool is utilized (the more liquidity is borrowed), the better it is for the protocol and lenders. But in your case the way you asked to calculate it, you will display it not in a very positive manner. Because you will measure our protocol performance like you measure protocols, which are based on collateral. 

But anyway, let's proceed the way you enforce 👍 At least we will be present in the [Yield category](https://defillama.com/yields) of your platform.

**Comment by zolotokrylin** [comment]
Amazing, guys! Thanks! 🙏 
When shall we expect to see Clearpool in Yield section?

**Pull request merged**
