### PR TITLE
add oswap token rewards

### PR DESCRIPTION
**Pull request by Taump**

### CODE REVIEW

**Comment by llamatester** [comment]
The oswap-amm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       82 passed, 82 total
    Snapshots:   0 total
    Time:        0.471 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────┬───────────┬─────────┬──────────────┬──────────────────────────────────────────┬────────────────────┬──────────────┬─────────┬─────────────┐
    │ (index) │                            url                             │ apyReward │ apyBase │ rewardTokens │                   pool                   │       tvlUsd       │    symbol    │  chain  │   project   │
    ├─────────┼────────────────────────────────────────────────────────────┼───────────┼─────────┼──────────────┼──────────────────────────────────────────┼────────────────────┼──────────────┼─────────┼─────────────┤
    │    0    │ 'https://oswap.io/#/swap/MBTF5GG44S3ARJHIZH3DEAB4DGUCHCF6' │  1275.37  │  1.13   │ [ 'GBYTE' ]  │ 'mbtf5gg44s3arjhizh3deab4dguchcf6-obyte' │ 84125.35697350008  │ 'GBYTE-USDC' │ 'Obyte' │ 'oswap-amm' │
    │    1    │ 'https://oswap.io/#/swap/YDLB64237VRAYNOO4IPWQKM2CW3PYT3V' │  67397.4  │  1.98   │ [ 'GBYTE' ]  │ 'ydlb64237vraynoo4ipwqkm2cw3pyt3v-obyte' │ 67296.51111304908  │ 'GBYTE-ETH'  │ 'Obyte' │ 'oswap-amm' │
    │    2    │ 'https://oswap.io/#/swap/22AL2GJFGYK7ISFSNUJIX2OSR56HB6Y7' │  160956   │  3.81   │ [ 'GBYTE' ]  │ '22al2gjfgyk7isfsnujix2osr56hb6y7-obyte' │ 54417.66657023593  │ 'GBYTE-WBTC' │ 'Obyte' │ 'oswap-amm' │
    │    3    │ 'https://oswap.io/#/swap/VNTX5S6BVUOXZXCCK2LCWCH7S3SWEAVW' │   56.3    │    0    │ [ 'GBYTE' ]  │ 'vntx5s6bvuoxzxcck2lcwch7s3sweavw-obyte' │ 7598.770861813838  │  'OETH-ETH'  │ 'Obyte' │ 'oswap-amm' │
    │    4    │ 'https://oswap.io/#/swap/UR6IFUPLU4S7GGODTEUCF7PIPSNSW2PN' │  92.0299  │    0    │ [ 'GBYTE' ]  │ 'ur6ifuplu4s7ggodteucf7pipsnsw2pn-obyte' │ 6080.887856707601  │ 'OUSD-USDC'  │ 'Obyte' │ 'oswap-amm' │
    │    5    │ 'https://oswap.io/#/swap/KBQO4XLXGLKANN6ODC3FS7JBCINW62RU' │  196.867  │   0.1   │ [ 'GBYTE' ]  │ 'kbqo4xlxglkann6odc3fs7jbcinw62ru-obyte' │ 4271.6626152210765 │ 'OBIT-WBTC'  │ 'Obyte' │ 'oswap-amm' │
    │    6    │ 'https://oswap.io/#/swap/U36E2Z2ROBJTH6SBM5M2FU6NWGQARQSN' │     0     │    0    │ [ 'GBYTE' ]  │ 'u36e2z2robjth6sbm5m2fu6nwgqarqsn-obyte' │ 457.81251664349406 │ 'TONY-GBYTE' │ 'Obyte' │ 'oswap-amm' │
    │    7    │ 'https://oswap.io/#/swap/WOBHOLPRVZURRHP7V6NGQBSVEQGA5C54' │     0     │    0    │ [ 'GBYTE' ]  │ 'wobholprvzurrhp7v6ngqbsveqga5c54-obyte' │ 364.8603152308326  │ 'GBYTE-WBTC' │ 'Obyte' │ 'oswap-amm' │
    │    8    │ 'https://oswap.io/#/swap/3HE3AWRWIQDVXR5RSRXQKNMPT4INCHFR' │     0     │    0    │ [ 'GBYTE' ]  │ '3he3awrwiqdvxr5rsrxqknmpt4inchfr-obyte' │ 343.4091337507588  │  'OETH-ETH'  │ 'Obyte' │ 'oswap-amm' │
    │    9    │ 'https://oswap.io/#/swap/4NN3GFY42GSNKYOETG7HAQISULOLNYKK' │     0     │    0    │ [ 'GBYTE' ]  │ '4nn3gfy42gsnkyoetg7haqisulolnykk-obyte' │ 228.57205487715996 │ 'GBYTE-ETH'  │ 'Obyte' │ 'oswap-amm' │
    └─────────┴────────────────────────────────────────────────────────────┴───────────┴─────────┴──────────────┴──────────────────────────────────────────┴────────────────────┴──────────────┴─────────┴─────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, pls share a link where i can see that info on the ui, bit confused cause we already have rewards here. also the nbs seem really large

**Comment by tonyofbyteball** [comment]
The link is https://token.oswap.io/farming/all. Yes, the rewards are still high (got a bit lower since the PR was created). It's a new thing and still too little liquidity for the rewards that are distributed.

An older rewards program is still active and we choose the higher paying one for each pool.

**Comment by llamatester** [comment]
The oswap-amm adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       118 passed, 118 total
    Snapshots:   0 total
    Time:        0.339 s
    Ran all test suites.
    
    Nb of pools: 19
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────────┬───────────┬─────────┬──────────────┬──────────────────────────────────────────┬────────────────────┬───────────────┬─────────┬─────────────┐
    │ (index) │                            url                             │ apyReward │ apyBase │ rewardTokens │                   pool                   │       tvlUsd       │    symbol     │  chain  │   project   │
    ├─────────┼────────────────────────────────────────────────────────────┼───────────┼─────────┼──────────────┼──────────────────────────────────────────┼────────────────────┼───────────────┼─────────┼─────────────┤
    │    0    │ 'https://oswap.io/#/swap/MBTF5GG44S3ARJHIZH3DEAB4DGUCHCF6' │  1292.86  │  3.15   │ [ 'GBYTE' ]  │ 'mbtf5gg44s3arjhizh3deab4dguchcf6-obyte' │ 85662.72227789598  │ 'GBYTE-USDC'  │ 'Obyte' │ 'oswap-amm' │
    │    1    │ 'https://oswap.io/#/swap/YDLB64237VRAYNOO4IPWQKM2CW3PYT3V' │  15957.2  │  5.78   │ [ 'GBYTE' ]  │ 'ydlb64237vraynoo4ipwqkm2cw3pyt3v-obyte' │ 74056.13909653743  │  'GBYTE-ETH'  │ 'Obyte' │ 'oswap-amm' │
    │    2    │ 'https://oswap.io/#/swap/22AL2GJFGYK7ISFSNUJIX2OSR56HB6Y7' │  13792.5  │  8.08   │ [ 'GBYTE' ]  │ '22al2gjfgyk7isfsnujix2osr56hb6y7-obyte' │ 64908.27501972608  │ 'GBYTE-WBTC'  │ 'Obyte' │ 'oswap-amm' │
    │    3    │ 'https://oswap.io/#/swap/VNTX5S6BVUOXZXCCK2LCWCH7S3SWEAVW' │   56.23   │    0    │ [ 'GBYTE' ]  │ 'vntx5s6bvuoxzxcck2lcwch7s3sweavw-obyte' │ 7785.871809429522  │  'OETH-ETH'   │ 'Obyte' │ 'oswap-amm' │
    │    4    │ 'https://oswap.io/#/swap/UR6IFUPLU4S7GGODTEUCF7PIPSNSW2PN' │  94.9286  │    0    │ [ 'GBYTE' ]  │ 'ur6ifuplu4s7ggodteucf7pipsnsw2pn-obyte' │ 6011.907578052395  │  'OUSD-USDC'  │ 'Obyte' │ 'oswap-amm' │
    │    5    │ 'https://oswap.io/#/swap/KBQO4XLXGLKANN6ODC3FS7JBCINW62RU' │  188.665  │  9.08   │ [ 'GBYTE' ]  │ 'kbqo4xlxglkann6odc3fs7jbcinw62ru-obyte' │ 4459.704723373574  │  'OBIT-WBTC'  │ 'Obyte' │ 'oswap-amm' │
    │    6    │ 'https://oswap.io/#/swap/YJ3FVKBJRMZWGJNHYW5E2RRDAFWB6ZC2' │     0     │    0    │ [ 'GBYTE' ]  │ 'yj3fvkbjrmzwgjnhyw5e2rrdafwb6zc2-obyte' │ 546.8392020362763  │ 'GBYTE-OSWAP' │ 'Obyte' │ 'oswap-amm' │
    │    7    │ 'https://oswap.io/#/swap/U36E2Z2ROBJTH6SBM5M2FU6NWGQARQSN' │    NaN    │    0    │ [ 'GBYTE' ]  │ 'u36e2z2robjth6sbm5m2fu6nwgqarqsn-obyte' │ 469.65923987947997 │ 'TONY-GBYTE'  │ 'Obyte' │ 'oswap-amm' │
    │    8    │ 'https://oswap.io/#/swap/WOBHOLPRVZURRHP7V6NGQBSVEQGA5C54' │     0     │    0    │ [ 'GBYTE' ]  │ 'wobholprvzurrhp7v6ngqbsveqga5c54-obyte' │ 376.0502608425669  │ 'GBYTE-WBTC'  │ 'Obyte' │ 'oswap-amm' │
    │    9    │ 'https://oswap.io/#/swap/3HE3AWRWIQDVXR5RSRXQKNMPT4INCHFR' │     0     │  0.08   │ [ 'GBYTE' ]  │ '3he3awrwiqdvxr5rsrxqknmpt4inchfr-obyte' │ 352.54958092695097 │  'OETH-ETH'   │ 'Obyte' │ 'oswap-amm' │
    └─────────┴────────────────────────────────────────────────────────────┴───────────┴─────────┴──────────────┴──────────────────────────────────────────┴────────────────────┴───────────────┴─────────┴─────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
