### PR TITLE
update: add more chains

### PR DESCRIPTION
**Pull request by eriscrypt**

### CODE REVIEW

**Comment by slasher125** [comment]
pls change the import to `const sdk = require('@defillama/sdk5');`

**Comment by eriscrypt** [comment]
all tests pass on my local machine

**Comment by slasher125** [comment]
how can the tests pass if it fails for inEVM?
i need to update the sdk, for now, pls comment out the inEVM parts. i'll update this later

**Comment by eriscrypt** [comment]
Screenshot 2024-04-03 at 13 17 45

**Comment by slasher125** [comment]
i just ran this locally, its failing. if u check what it says above the output you should see the specific error
u got duplicated pool values

**Comment by eriscrypt** [comment]
we have same addresses on each network ...

**Comment by slasher125** [comment]
as mentioned in the readme, the pool values need to be unique, you can just add a chain suffix

**Pull request merged**
