### PR TITLE
Feat/fenix standard pools

### PR DESCRIPTION
**Pull request by starketh25**

### CODE REVIEW

**Comment by llamatester** [comment]
The fenix-standard-pools adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       95 passed, 95 total
    Snapshots:   0 total
    Time:        0.28 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────────────────────┬──────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │        project         │    symbol    │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────────────────────┼──────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xcb0e3bd2adc621489dfef404821b5b11f840fa58' │ 'Blast' │ 'fenix-standard-pools' │ 'DETH-WETH'  │ 4565537.8091317285 │ 40.18757628227543  │ [ '0x1da40c742f32bbee81694051c0ee07485fc630f6', '0x4300000000000000000000000000000000000004' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    1    │ '0x031e673c2cbbc1ede15b6595f55e917d16680658' │ 'Blast' │ 'fenix-standard-pools' │ 'WETH-fBOMB' │ 513467.19794272154 │ 58.17976796524752  │ [ '0x4300000000000000000000000000000000000004', '0x5c09a9ce08c4b332ef1cc5f7cadb1158c32767ce' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    2    │ '0x94d3a9fe1265e3eb1d89849c325d931924cec88f' │ 'Blast' │ 'fenix-standard-pools' │ 'PREON-STAR' │ 265664.1669264451  │ 79.94313694161079  │ [ '0x135f9b3d5dec9d73c042cf380adfff95f4fe9e35', '0xc19669a405067927865b40ea045a2baabbbe57f5' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    3    │ '0x4a5eb8fa9f2ce583b47c804b28f80e89ec146760' │ 'Blast' │ 'fenix-standard-pools' │ 'fDAO-WETH'  │ 223145.11821811667 │ 127.08980030425833 │ [ '0x3b0cffda9a5ab64135c227638e777ceec0c243a8', '0x4300000000000000000000000000000000000004' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    4    │ '0x8c22d23ec102c9e098c8e0b9ed4ea01aa0b4be35' │ 'Blast' │ 'fenix-standard-pools' │ 'WETH-IBEX'  │ 175260.67953853903 │ 14.993404039771146 │ [ '0x4300000000000000000000000000000000000004', '0x9f04b6cefd5bcd67d76ab708f17553ce40188e6a' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    5    │ '0xd49ad1dd6c5eae53abdafeaed1866330c42ccae4' │ 'Blast' │ 'fenix-standard-pools' │ 'USDB-DOLA'  │ 117023.99645993888 │ 62.621370906544925 │ [ '0x4300000000000000000000000000000000000003', '0x8e38179d361402f6a94767757e807146609e9b3d' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    6    │ '0xb485fdabb73274ee573700aaf37e92b6273a82c2' │ 'Blast' │ 'fenix-standard-pools' │  'WETH-SDK'  │ 71464.46941620253  │  295.684475949905  │ [ '0x4300000000000000000000000000000000000004', '0xae24f36ba2f8a109b913e55b78597b8ba7f7b8ff' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    7    │ '0x31819ac7e73ebff4e5413bdb2884d985ed3a6a2c' │ 'Blast' │ 'fenix-standard-pools' │  'FNX-BLND'  │ 42766.49068040542  │ 847.9698467199502  │ [ '0x52f847356b38720b55ee18cb3e094ca11c85a192', '0xb85836b0c8faefebae6f9f4600df7a49faad8882' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    8    │ '0xbfcfb64ba6ff6e2ca4ff5a3523468ddf50631f30' │ 'Blast' │ 'fenix-standard-pools' │  'WETH-FNX'  │ 39828.384061093384 │ 129.40689999778155 │ [ '0x4300000000000000000000000000000000000004', '0x52f847356b38720b55ee18cb3e094ca11c85a192' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    9    │ '0xaaff182d62cd62140c9f453f9eb35ba98a90eae8' │ 'Blast' │ 'fenix-standard-pools' │ 'USDB-STAR'  │  26552.6548648791  │ 52.19527883301841  │ [ '0x4300000000000000000000000000000000000003', '0xc19669a405067927865b40ea045a2baabbbe57f5' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────────────────────┴──────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
@starketh25 same issue here as in the other PR

**Comment by llamatester** [comment]
The fenix-standard-pools adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       95 passed, 95 total
    Snapshots:   0 total
    Time:        0.279 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────┬────────────────────────┬──────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │  chain  │        project         │    symbol    │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────┼────────────────────────┼──────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xcb0e3bd2adc621489dfef404821b5b11f840fa58' │ 'Blast' │ 'fenix-standard-pools' │ 'DETH-WETH'  │ 1186646.6398403568 │  39.9122109662497  │ [ '0x1da40c742f32bbee81694051c0ee07485fc630f6', '0x4300000000000000000000000000000000000004' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    1    │ '0x031e673c2cbbc1ede15b6595f55e917d16680658' │ 'Blast' │ 'fenix-standard-pools' │ 'WETH-fBOMB' │ 517853.44915337604 │ 58.443564323237105 │ [ '0x4300000000000000000000000000000000000004', '0x5c09a9ce08c4b332ef1cc5f7cadb1158c32767ce' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    2    │ '0x94d3a9fe1265e3eb1d89849c325d931924cec88f' │ 'Blast' │ 'fenix-standard-pools' │ 'PREON-STAR' │ 265664.1669264451  │ 80.99161595923108  │ [ '0x135f9b3d5dec9d73c042cf380adfff95f4fe9e35', '0xc19669a405067927865b40ea045a2baabbbe57f5' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    3    │ '0x4a5eb8fa9f2ce583b47c804b28f80e89ec146760' │ 'Blast' │ 'fenix-standard-pools' │ 'fDAO-WETH'  │ 228856.1200041895  │ 125.5435586849671  │ [ '0x3b0cffda9a5ab64135c227638e777ceec0c243a8', '0x4300000000000000000000000000000000000004' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    4    │ '0x8c22d23ec102c9e098c8e0b9ed4ea01aa0b4be35' │ 'Blast' │ 'fenix-standard-pools' │ 'WETH-IBEX'  │  184837.707352217  │ 14.47017509316181  │ [ '0x4300000000000000000000000000000000000004', '0x9f04b6cefd5bcd67d76ab708f17553ce40188e6a' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    5    │ '0xd49ad1dd6c5eae53abdafeaed1866330c42ccae4' │ 'Blast' │ 'fenix-standard-pools' │ 'USDB-DOLA'  │ 124441.46003386968 │ 59.661102818704634 │ [ '0x4300000000000000000000000000000000000003', '0x8e38179d361402f6a94767757e807146609e9b3d' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    6    │ '0xb485fdabb73274ee573700aaf37e92b6273a82c2' │ 'Blast' │ 'fenix-standard-pools' │  'WETH-SDK'  │ 66892.03173050702  │ 320.0392092374864  │ [ '0x4300000000000000000000000000000000000004', '0xae24f36ba2f8a109b913e55b78597b8ba7f7b8ff' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    7    │ '0x31819ac7e73ebff4e5413bdb2884d985ed3a6a2c' │ 'Blast' │ 'fenix-standard-pools' │  'FNX-BLND'  │ 48258.88300404853  │  761.317191124508  │ [ '0x52f847356b38720b55ee18cb3e094ca11c85a192', '0xb85836b0c8faefebae6f9f4600df7a49faad8882' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    8    │ '0xbfcfb64ba6ff6e2ca4ff5a3523468ddf50631f30' │ 'Blast' │ 'fenix-standard-pools' │  'WETH-FNX'  │ 32988.70585937755  │ 158.12398426139754 │ [ '0x4300000000000000000000000000000000000004', '0x52f847356b38720b55ee18cb3e094ca11c85a192' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    │    9    │ '0xaaff182d62cd62140c9f453f9eb35ba98a90eae8' │ 'Blast' │ 'fenix-standard-pools' │ 'USDB-STAR'  │ 26556.475159544934 │ 52.87222903713034  │ [ '0x4300000000000000000000000000000000000003', '0xc19669a405067927865b40ea045a2baabbbe57f5' ] │ [ '0x52f847356b38720B55ee18Cb3e094ca11C85A192' ] │
    └─────────┴──────────────────────────────────────────────┴─────────┴────────────────────────┴──────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by starketh25** [comment]
fixed here ser @slasher125

**Pull request merged**
