### PR TITLE
remove pool filter add apyReward for new bdAMM emissions

### PR DESCRIPTION
**Pull request by sbbutler**

### CODE REVIEW

**Comment by llamatester** [comment]
The damm-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       291 passed, 291 total
    Snapshots:   0 total
    Time:        0.396 s
    Ran all test suites.
    
    Nb of pools: 41
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬────────────────────┬──────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project     │  symbol  │       tvlUsd       │       apyBase        │     apyReward      │                 underlyingTokens                 │                   rewardTokens                   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼────────────────────┼──────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xa3006250a22e1ca3c3f19fd1fb080c5dc65992c5-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dUSDC'  │   1399140.249631   │  1.9862113512312003  │ 34.57330817862515  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    1    │ '0xbf0852a95ec76e87f7431fa505b27937c9836372-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dUSDT'  │   656630.836017    │ 0.047949963713999996 │ 26.717808731582583 │ [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    2    │ '0x474a023313092ab7b69bc387e952f2e9616d0eaa-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dAUSDT' │   560651.644636    │          0           │ 41.22050226198838  │ [ '0x3Ed3B47Dd13EC9a98b44e6204A523E766B225811' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    3    │ '0xd8821e68d0c16b1e3fa2ba8dfc1013d245e06f77-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dCDAI'  │ 556471.5383916426  │          0           │ 37.21383767766039  │ [ '0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    4    │ '0xf1667d8fa2a9d4a00717cb4f74cc698546acf602-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dFRAX'  │ 541344.4690299587  │ 0.11048359268520001  │ 13.852394025215528 │ [ '0x853d955aCEf822Db058eb8505911ED77F175b99e' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    5    │ '0x68fcd092fa88cb1972815de8afaaf318ef7d80ea-ethereum' │ 'Ethereum' │ 'damm-finance' │  'dDAI'  │ 511670.7541274817  │   0.0198773778456    │ 20.90841904399081  │ [ '0x6B175474E89094C44Da98b954EedeAC495271d0F' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    6    │ '0x4b2ea02cfeac47ac1b33504900daa983aaaf5f9f-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dADAI'  │ 496763.9605493663  │          0           │ 41.13163907712987  │ [ '0x028171bCA77440897B824Ca71D1c56caC55b68A3' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    7    │ '0x4e6991d54a39092b76063bd26aad9d24b7a3c132-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dAUSDC' │   420866.234104    │          0           │ 36.098029425167525 │ [ '0xBcca60bB61934080951369a648Fb03DF4F96263C' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    8    │ '0x1aa712bc9b16737ef98f15eeb841fc33b680901f-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dCUSDT' │ 304798.61758212943 │          0           │ 37.23451332933227  │ [ '0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    │    9    │ '0x5714eb15a226059202cdfa1bf304167e36752862-ethereum' │ 'Ethereum' │ 'damm-finance' │ 'dCUSDC' │ 296310.07863133977 │          0           │ 36.067161841639766 │ [ '0x39AA39c021dfbaE8faC545936693aC917d5E7563' ] │ [ '0xfa372fF1547fa1a283B5112a4685F1358CE5574d' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴────────────────────┴──────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
great ty. i'm gonna merge this one. would u mind extending the new borrow fields for this adapter? 😎

**Comment by sbbutler** [comment]
to be more concise
apyRewardBorrow - lemme find out if dey earn rewards if not should i jus omit?
ltv - if 0 should i omit?

**Comment by sbbutler** [comment]
henlo slasher!
borrowers n lenders both receive bdamm rewards
ai ai :salute~1:

**Pull request merged**
