### PR TITLE
Add RociFi v2 apy data

### PR DESCRIPTION
**Pull request by katamarinaki**

### CODE REVIEW

**Comment by llamatester** [comment]
The rocifi-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.305 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬──────────┬─────────────────┬─────────────────────┬──────────────────────────────────────────────────┬────────────────────────────┬────────────────┬─────────────────┐
    │ (index) │                         pool                         │   chain   │   project   │  symbol  │     tvlUsd      │       apyBase       │                 underlyingTokens                 │          poolMeta          │ totalBorrowUsd │ totalSupplyUsd  │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼──────────┼─────────────────┼─────────────────────┼──────────────────────────────────────────────────┼────────────────────────────┼────────────────┼─────────────────┤
    │    0    │ '0x94C29F381A65344d65baB80f321660A75C237815-polygon' │ 'polygon' │ 'rocifi-v2' │ 'rUSDT1' │ 25688.815773621 │ 1.4204506230998564  │ [ '0xc2132d05d31c914a87c6611c10748aeb04b58e8f' ] │ 'RociFi USDT lending pool' │ 2680.876816618 │ 28369.692590239 │
    │    1    │ '0x4eBB81605f91C02827426E37001d402bF46a170d-polygon' │ 'polygon' │ 'rocifi-v2' │ 'rUSDC1' │ 16958.379704266 │ 0.05224470515949138 │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174' ] │ 'RociFi USDC lending pool' │ 5897.522844213 │ 22855.902548479 │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴──────────┴─────────────────┴─────────────────────┴──────────────────────────────────────────────────┴────────────────────────────┴────────────────┴─────────────────┘

**Comment by slasher125** [comment]
hi sir, ty for adding. can u pls add the `ltv` field, that way we can also list the project on borrow related pages

**Comment by konstantin-roci** [comment]
Hi @slasher125!

Listing on borrow related pages would be excellent, thanks.

1. RociFi's unique selling proposition is offering under-collateralised loans. i.e. loans with LTV>1. The best LTV that we offer for USDT and USDC is 1.30. Could we somehow reflect this on DeFiLlama? This is very important for us. 

The average LTV that we offer is 1.07.

2. apyBaseBorrow: 1.55 

Can be seen here: https://roci.fi/app/markets

**Comment by llamatester** [comment]
The rocifi-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.329 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────┬──────────┬─────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────┬────────────────┬─────────────────┬───────────────┬─────┐
    │ (index) │                         pool                         │   chain   │   project   │  symbol  │     tvlUsd      │      apyBase       │                 underlyingTokens                 │          poolMeta          │ totalBorrowUsd │ totalSupplyUsd  │ apyBaseBorrow │ ltv │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────┼──────────┼─────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────┼────────────────┼─────────────────┼───────────────┼─────┤
    │    0    │ '0x94C29F381A65344d65baB80f321660A75C237815-polygon' │ 'polygon' │ 'rocifi-v2' │ 'rUSDT1' │ 25197.097594669 │ 1.4204506230998564 │ [ '0xc2132d05d31c914a87c6611c10748aeb04b58e8f' ] │ 'RociFi USDT lending pool' │ 3172.59499557  │ 28369.692590239 │     1.55      │ 1.3 │
    │    1    │ '0x4eBB81605f91C02827426E37001d402bF46a170d-polygon' │ 'polygon' │ 'rocifi-v2' │ 'rUSDC1' │ 17986.663582116 │ 1.677403741820895  │ [ '0x2791bca1f2de4661ed88a30c99a7a9449aa84174' ] │ 'RociFi USDC lending pool' │ 4896.163875186 │ 22882.827457302 │     1.55      │ 1.3 │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────┴──────────┴─────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────┴────────────────┴─────────────────┴───────────────┴─────┘

**Comment by katamarinaki** [comment]
Hey @slasher125, I just updated the PR, now it matches your requirements. As @konstantin-roci said above, our LTV is higher than one, I hope this is not an obstacle to listing our protocol. Thank you!

**Comment by slasher125** [comment]
understood. still, we should set it to the lower bound cause not everyone will get the highest credit score and thus max ltv.

**Comment by katamarinaki** [comment]
@slasher125 done, thanks for pointing it out.

**Pull request merged**
