### PR TITLE
feat: premia adaptor

### PR DESCRIPTION
**Pull request by KngZhi**
- feat: arbitrum pools
- feat: whole pools for arb op fantom eth

### CODE REVIEW

**Comment by llamatester** [comment]
The premia adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       256 passed, 256 total
    Snapshots:   0 total
    Time:        0.442 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────┬──────────┬───────────────────────────────────┬─────────────────────┐
    │ (index) │   chain    │                                             pool                                             │      poolMeta       │                 underlyingTokens                 │                   rewardTokens                   │       tvlUsd       │   totalSupplyUsd   │ totalBorrowUsd │ project  │              symbol               │       apyBase       │
    ├─────────┼────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────┼──────────┼───────────────────────────────────┼─────────────────────┤
    │    0    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f-PUT'  │  'WBTC/DAI - PUT'   │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 1039871.5717735934 │ 1039871.5717735934 │   833345.55    │ 'premia' │           'Wrapped BTC'           │ -0.8490731209717937 │
    │    1    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x82af49447d8a07e3bd95bd0d56f35241523fbab1-CALL' │  'WETH/DAI - CALL'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 626954.2933004969  │ 626954.2933004969  │     99.35      │ 'premia' │          'Wrapped Ether'          │ 18.329764321171503  │
    │    2    │ 'optimism' │ '0x7f5c764cbc14f9669b88837ca1490cca17c31607/0x4200000000000000000000000000000000000006-CALL' │ 'WETH/USDC - CALL'  │ [ '0x4200000000000000000000000000000000000006' ] │ [ '0x374ad0f47f4ca39c78e5cc54f1c9e426ff8f231a' ] │ 481820.5513470189  │ 481820.5513470189  │    203.222     │ 'premia' │          'Wrapped Ether'          │  10.08293106890651  │
    │    3    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0xf97f4df75117a78c1a5a0dbb814af92458539fb4-CALL' │  'LINK/DAI - CALL'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 478098.69164767093 │ 478098.69164767093 │     31382      │ 'premia' │         'ChainLink Token'         │  20.56060046528689  │
    │    4    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-CALL' │  'WETH/DAI - CALL'  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 447082.8783904692  │ 447082.8783904692  │     230.5      │ 'premia' │          'Wrapped Ether'          │ 28.893712821251864  │
    │    5    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-PUT'  │  'WETH/DAI - PUT'   │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │  426624.80444575   │  426624.80444575   │    298874.2    │ 'premia' │          'Wrapped Ether'          │ -13.496539401394926 │
    │    6    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0x514910771af9ca656af840dff83e8264ecf986ca-CALL' │  'LINK/DAI - CALL'  │ [ '0x514910771af9ca656af840dff83e8264ecf986ca' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 404861.3647640261  │ 404861.3647640261  │     11500      │ 'premia' │         'ChainLink Token'         │  8.656635743232979  │
    │    7    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x5979d7b546e38e414f7e9822514be443a4800529-CALL' │ 'wstETH/DAI - CALL' │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 367135.08955208596 │ 367135.08955208596 │     154.02     │ 'premia' │ 'Wrapped liquid staked Ether 2.0' │ 10.333881799303642  │
    │    8    │  'fantom'  │ '0x04068da6c83afcfa0e13ba15a6696662335d5b75/0x74b23882a30290451a17c44f4f05243b6b58c76d-CALL' │  'ETH/USDC - CALL'  │ [ '0x74b23882a30290451a17c44f4f05243b6b58c76d' ] │ [ '0x3028b4395f98777123c7da327010c40f3c7cc4ef' ] │ 322148.0669465712  │ 322148.0669465712  │     211.37     │ 'premia' │            'Ethereum'             │  11.32331971650272  │
    │    9    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f-CALL' │  'WBTC/DAI - CALL'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │  292303.808994214  │  292303.808994214  │   8.775e-10    │ 'premia' │           'Wrapped BTC'           │      30.322465      │
    └─────────┴────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────┴──────────┴───────────────────────────────────┴─────────────────────┘

**Comment by slasher125** [comment]
gm looking gud. couple of things:
- please use WBTC instead of Wrapped BTC, LINK instead of ChainLink Token etc.
- u can remove totalSupplyUsd and totalBorrowUsd, these are fields we only use in the context of lending protocols.

**Comment by llamatester** [comment]
The premia adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       256 passed, 256 total
    Snapshots:   0 total
    Time:        0.435 s
    Ran all test suites.
    
    Nb of pools: 36
     
    
    Sample pools:
    ┌─────────┬────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬──────────┬──────────┬─────────────────────┐
    │ (index) │   chain    │                                             pool                                             │      poolMeta       │                 underlyingTokens                 │                   rewardTokens                   │       tvlUsd       │ project  │  symbol  │       apyBase       │
    ├─────────┼────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼──────────┼──────────┼─────────────────────┤
    │    0    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f-PUT'  │  'WBTC/DAI - PUT'   │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 1042798.5678616847 │ 'premia' │  'WBTC'  │ -0.8488097004474763 │
    │    1    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x82af49447d8a07e3bd95bd0d56f35241523fbab1-CALL' │  'WETH/DAI - CALL'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 619949.4379319027  │ 'premia' │  'WETH'  │ 18.345598378178476  │
    │    2    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0xf97f4df75117a78c1a5a0dbb814af92458539fb4-CALL' │  'LINK/DAI - CALL'  │ [ '0xf97f4df75117a78c1a5a0dbb814af92458539fb4' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 492583.47626397014 │ 'premia' │  'LINK'  │ 20.579348379537088  │
    │    3    │ 'optimism' │ '0x7f5c764cbc14f9669b88837ca1490cca17c31607/0x4200000000000000000000000000000000000006-CALL' │ 'WETH/USDC - CALL'  │ [ '0x4200000000000000000000000000000000000006' ] │ [ '0x374ad0f47f4ca39c78e5cc54f1c9e426ff8f231a' ] │ 468513.01236763305 │ 'premia' │  'WETH'  │ 10.284678136310717  │
    │    4    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-CALL' │  'WETH/DAI - CALL'  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 468103.9258437608  │ 'premia' │  'WETH'  │ 28.890801694396995  │
    │    5    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0x514910771af9ca656af840dff83e8264ecf986ca-CALL' │  'LINK/DAI - CALL'  │ [ '0x514910771af9ca656af840dff83e8264ecf986ca' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │ 404861.3647640261  │ 'premia' │  'LINK'  │  8.656635743232979  │
    │    6    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x5979d7b546e38e414f7e9822514be443a4800529-CALL' │ 'wstETH/DAI - CALL' │ [ '0x5979d7b546e38e414f7e9822514be443a4800529' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 369957.1817299599  │ 'premia' │ 'wstETH' │ 10.267709769275319  │
    │    7    │ 'ethereum' │ '0x6b175474e89094c44da98b954eedeac495271d0f/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-PUT'  │  'WETH/DAI - PUT'   │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x6399C842dD2bE3dE30BF99Bc7D1bBF6Fa3650E70' ] │  349388.314296119  │ 'premia' │  'WETH'  │ -14.946790650687502 │
    │    8    │  'fantom'  │ '0x04068da6c83afcfa0e13ba15a6696662335d5b75/0x74b23882a30290451a17c44f4f05243b6b58c76d-CALL' │  'ETH/USDC - CALL'  │ [ '0x74b23882a30290451a17c44f4f05243b6b58c76d' ] │ [ '0x3028b4395f98777123c7da327010c40f3c7cc4ef' ] │ 322148.0669465712  │ 'premia' │  'ETH'   │  11.32331971650272  │
    │    9    │ 'arbitrum' │ '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f-CALL' │  'WBTC/DAI - CALL'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ [ '0x51fc0f6660482ea73330e414efd7808811a57fa2' ] │ 292588.4593886912  │ 'premia' │  'WBTC'  │      30.336442      │
    └─────────┴────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴──────────┴──────────┴─────────────────────┘

**Comment by slasher125** [comment]
one more thing which i forgot to address: u provide the rewardToken array but there is no `apyReward` field.
Do the liquidity provides earn `Premia` incentive rewards? if so then we need to split out that component into `apyReward`. 
in the end apy should be = apyBase + apyReward.
(note: you do not need to provide the sum of them, we calc that server side)

**Comment by KngZhi** [comment]
> one more thing which i forgot to address: u provide the rewardToken array but there is no `apyReward` field. Do the liquidity provides earn `Premia` incentive rewards? if so then we need to split out that component into `apyReward`. in the end apy should be = apyBase + apyReward. (note: you do not need to provide the sum of them, we calc that server side)

Yes. But currently, I can not get apyReward from the graphql, I am contacting with PREMIA team, but it is unresponsive.

Maybe after I submit the code of that part, I will `@` you, so we can merge this PR.

**Pull request merged**
