### PR TITLE
Update adapter with new contracts, functions, and APR calcs

### PR DESCRIPTION
**Pull request by rogue-hacker**

### CODE REVIEW

**Comment by llamatester** [comment]
The mycelium-perpetual-swaps adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       18 passed, 18 total
    Snapshots:   0 total
    Time:        0.475 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────────────────────┬────────┬────────────────────┬────────────────────┬───────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │          project           │ symbol │       tvlUsd       │      apyBase       │ apyReward │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────────────────────┼────────┼────────────────────┼────────────────────┼───────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xF7Bd2ed13BEf9C27a2188f541Dc5ED85C5325306' │ 'Arbitrum' │ 'mycelium-perpetual-swaps' │ 'MLP'  │ 11065699.850955535 │ 28.539092960302682 │     0     │ [ '0xc74fe4c715510ec2f8c61d70d397b32043f55abe' ] │ [ '0x752b746426b6D0c3188bb530660374f92FD9cf7c' ] │
    │    1    │ '0xF9B003Ee160dA9677115Ad3c5bd6BB6dADcB2F93' │ 'Arbitrum' │ 'mycelium-perpetual-swaps' │ 'MYC'  │ 1638351.7474538789 │ 30.719961516674754 │           │ [ '0xc74fe4c715510ec2f8c61d70d397b32043f55abe' ] │ [ '0x752b746426b6D0c3188bb530660374f92FD9cf7c' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────────────────────┴────────┴────────────────────┴────────────────────┴───────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
Hey just noticed that the MYC is a new address. is this on purpose? the previous pool value was `0x9B225FF56C48671d4D04786De068Ed8b88b672d6`

**Comment by rogue-hacker** [comment]
Yes, the staking contracts were updated to allow for continuous staking in place of cycles.

We made a blog post about it here:

https://mycelium.xyz/blog/myc-staking-eth-rewards

**Comment by slasher125** [comment]
ok, just to confirm: do you want to keep this updated MYC pool linked to the current history we got for this?
basically what happens on our backend is if we update pool address we loose any linkage to the current history.

just let me know how to proceed. i can update the DB to the new address if you want to keep all historical datapoints intact

**Comment by rogue-hacker** [comment]
If the historical data points could be kept intact that would be great, thank you

**Comment by slasher125** [comment]
got it

**Pull request merged**
