### PR TITLE
Add capsa pool

### PR DESCRIPTION
**Pull request by t0mm4rx**
Hello,
I would like to add the capsa.finance yield-bearing token to the DefiLlama Yield dashboard.

Here is the implemented and tested connector.

### CODE REVIEW

**Comment by slasher125** [comment]
henlo t0mm4rx. ty for adding!
We are mostly using 24h periods when calculating fees/rewards which we scale up to a year. In your case, looking at the api response, I'd prefer if we use `last_week_performance` and scale that to a year instead of `projected_apy` which takes into account the last 3 months.

**Comment by t0mm4rx** [comment]
Thank you for your quick feedback.
Ok, so I'll change to last_week_performance times 52.14.

**Comment by slasher125** [comment]
great! * 52 is good enough :)

**Comment by t0mm4rx** [comment]
Just tested and committed "last_week_performance" * 52 instead of "projected_apy".

**Comment by slasher125** [comment]
can you pls remove the yarn.lock from the PR?

**Comment by t0mm4rx** [comment]
Sure, done. Could be good to add it into the .gitignore btw.

**Comment by slasher125** [comment]
> 

good call. will add that!

**Pull request merged**
