### PR TITLE
Add C3 Exchange Yields

### PR DESCRIPTION
**Pull request by MatHermida**

### CODE REVIEW

**Comment by llamatester** [comment]
The c3-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       64 passed, 64 total
    Snapshots:   0 total
    Time:        0.283 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────────┬──────────────────────┬────────────────┬────────────────┬─────────────────────────────────┐
    │ (index) │         pool          │   chain    │    project    │ symbol │ tvlUsd │   apyBase    │ underlyingTokens │    apyBaseBorrow     │ totalSupplyUsd │ totalBorrowUsd │               url               │
    ├─────────┼───────────────────────┼────────────┼───────────────┼────────┼────────┼──────────────┼──────────────────┼──────────────────────┼────────────────┼────────────────┼─────────────────────────────────┤
    │    0    │ '1058926737-algorand' │ 'Bitcoin'  │ 'c3-exchange' │ 'BTC'  │ 581935 │      0       │ [ '1058926737' ] │     0.0031536473     │     582329     │      394       │ 'https://c3.io/trade/BTC-USDC'  │
    │    1    │ '1007352535-algorand' │   'Avax'   │ 'c3-exchange' │ 'USDC' │ 200915 │ 0.5153596829 │ [ '1007352535' ] │     2.1579384158     │     265078     │     64163      │            undefined            │
    │    2    │ '1703994770-algorand' │  'Solana'  │ 'c3-exchange' │  'W'   │ 73467  │      0       │ [ '1703994770' ] │          0           │     73467      │       0        │  'https://c3.io/trade/W-USDC'   │
    │    3    │ '1684682524-algorand' │  'Solana'  │ 'c3-exchange' │ 'PYTH' │ 71744  │      0       │ [ '1684682524' ] │     0.0694032143     │     72048      │      304       │ 'https://c3.io/trade/PYTH-USDC' │
    │    4    │ '893309613-algorand'  │   'Avax'   │ 'c3-exchange' │ 'AVAX' │ 59774  │      0       │ [ '893309613' ]  │ 0.17675742600000002  │     60733      │      959       │ 'https://c3.io/trade/AVAX-USDC' │
    │    5    │ '1221549217-algorand' │ 'Arbitrum' │ 'c3-exchange' │ 'ARB'  │ 44664  │      0       │ [ '1221549217' ] │     0.053625518      │     44852      │      188       │ 'https://c3.io/trade/ARB-USDC'  │
    │    6    │ '887406851-algorand'  │ 'Ethereum' │ 'c3-exchange' │ 'ETH'  │ 42632  │      0       │ [ '887406851' ]  │ 0.012615185800000001 │     42698      │       66       │ 'https://c3.io/trade/ETH-USDC'  │
    │    7    │     '0-algorand'      │ 'Algorand' │ 'c3-exchange' │ 'ALGO' │  9221  │      0       │     [ '0' ]      │ 0.012615185800000001 │      9230      │       9        │ 'https://c3.io/trade/ALGO-USDC' │
    │    8    │ '887648583-algorand'  │  'Solana'  │ 'c3-exchange' │ 'SOL'  │  6421  │ 0.0031536473 │ [ '887648583' ]  │     0.2209956537     │      6546      │      125       │ 'https://c3.io/trade/SOL-USDC'  │
    │    9    │ '891648844-algorand'  │ 'Binance'  │ 'c3-exchange' │ 'BNB'  │   41   │      0       │ [ '891648844' ]  │          0           │       41       │       0        │            undefined            │
    └─────────┴───────────────────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────────┴──────────────────────┴────────────────┴────────────────┴─────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ty for adding:
-underlyingTokens -> should be addresses,
-no need to round tvl related values, we do that server side

**Comment by llamatester** [comment]
The c3-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       64 passed, 64 total
    Snapshots:   0 total
    Time:        0.28 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────────┬────────────┬───────────────┬────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────┬──────────────────────┬────────────────────┬────────────────────┬─────────────────────────────────┐
    │ (index) │         pool          │   chain    │    project    │ symbol │       tvlUsd       │      apyBase       │                  underlyingTokens                  │    apyBaseBorrow     │   totalSupplyUsd   │   totalBorrowUsd   │               url               │
    ├─────────┼───────────────────────┼────────────┼───────────────┼────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼────────────────────┼─────────────────────────────────┤
    │    0    │ '1007352535-algorand' │   'Avax'   │ 'c3-exchange' │ 'USDC' │ 192253.91477829654 │ 0.5407215624999999 │  [ '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E' ]  │     2.2094987515     │ 255633.67696646124 │ 63379.762188164685 │            undefined            │
    │    1    │ '1058926737-algorand' │ 'Bitcoin'  │ 'c3-exchange' │ 'BTC'  │ 70450.31539172056  │         0          │  [ '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599' ]  │          0           │ 70460.92366978848  │   10.60827806792   │ 'https://c3.io/trade/BTC-USDC'  │
    │    2    │ '1703994770-algorand' │  'Solana'  │ 'c3-exchange' │  'W'   │ 66474.42172645275  │         0          │ [ '85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ' ] │          0           │ 66474.43343904286  │    0.0117125901    │  'https://c3.io/trade/W-USDC'   │
    │    3    │ '1684682524-algorand' │  'Solana'  │ 'c3-exchange' │ 'PYTH' │ 65979.54843136512  │         0          │ [ 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3' ] │     0.0694032143     │ 66250.97081244986  │  271.422381084736  │ 'https://c3.io/trade/PYTH-USDC' │
    │    4    │ '893309613-algorand'  │   'Avax'   │ 'c3-exchange' │ 'AVAX' │ 55084.830105918845 │         0          │  [ '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7' ]  │     0.1009660559     │ 55586.35912676126  │  501.529020842412  │ 'https://c3.io/trade/AVAX-USDC' │
    │    5    │ '1221549217-algorand' │ 'Arbitrum' │ 'c3-exchange' │ 'ARB'  │ 43341.709192304595 │         0          │  [ '0x912CE59144191C1204E64559FE8253a0e49E6548' ]  │ 0.050470291800000004 │ 43517.70370010559  │  175.994507800992  │ 'https://c3.io/trade/ARB-USDC'  │
    │    6    │ '887406851-algorand'  │ 'Ethereum' │ 'c3-exchange' │ 'ETH'  │ 38457.23948441235  │         0          │  [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ]  │ 0.012615185800000001 │ 38514.21895953485  │   56.9794751225    │ 'https://c3.io/trade/ETH-USDC'  │
    │    7    │ '887648583-algorand'  │  'Solana'  │ 'c3-exchange' │ 'SOL'  │ 9958.482106689888  │         0          │ [ 'So11111111111111111111111111111111111111112' ]  │     0.0757149622     │ 10025.061930627877 │   66.57982393799   │ 'https://c3.io/trade/SOL-USDC'  │
    │    8    │     '0-algorand'      │ 'Algorand' │ 'c3-exchange' │ 'ALGO' │  8463.3434508744   │         0          │                      [ '0' ]                       │ 0.012615185800000001 │  8471.8433767968   │    8.4999259224    │ 'https://c3.io/trade/ALGO-USDC' │
    │    9    │ '891648844-algorand'  │ 'Binance'  │ 'c3-exchange' │ 'BNB'  │     37.9049175     │         0          │  [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ]  │          0           │     37.9049175     │         0          │            undefined            │
    └─────────┴───────────────────────┴────────────┴───────────────┴────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────┴──────────────────────┴────────────────────┴────────────────────┴─────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by MatHermida** [comment]
Thanks for the merge!

**Pull request merged**
