### PR TITLE
feat: add Extra Finance adapter

### PR DESCRIPTION
**Pull request by KarmanMax**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running extra adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       2 failed, 98 passed, 100 total
    Snapshots:   0 total
    Time:        0.372 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────┬──────────┬──────────────────────────────────────────────────┬───────────────────────┬────────────────────┬───────────────────────┐
    │ (index) │                         pool                          │   chain    │ project │  symbol  │                 underlyingTokens                 │       poolMeta        │       tvlUsd       │        apyBase        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────┼──────────┼──────────────────────────────────────────────────┼───────────────────────┼────────────────────┼───────────────────────┤
    │    0    │ '0x4200000000000000000000000000000000000006-optimism' │ 'Optimism' │ 'extra' │  'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │  'WETH lending pool'  │ 33436.64941315362  │  0.7157408590195757   │
    │    1    │ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05-optimism' │ 'Optimism' │ 'extra' │  'VELO'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05' ] │  'VELO lending pool'  │ 32855.01426871266  │   6.207975556530343   │
    │    2    │ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb-optimism' │ 'Optimism' │ 'extra' │ 'wstETH' │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ] │ 'wstETH lending pool' │ 28538.562784796934 │  0.4045850605555179   │
    │    3    │ '0x8ae125e8653821e851f12a49f7765db9a9ce7384-optimism' │ 'Optimism' │ 'extra' │  'DOLA'  │ [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │  'DOLA lending pool'  │ 22998.22889102134  │   8.951214788984906   │
    │    4    │ '0x4200000000000000000000000000000000000042-optimism' │ 'Optimism' │ 'extra' │   'OP'   │ [ '0x4200000000000000000000000000000000000042' ] │   'OP lending pool'   │ 18578.880430852576 │  13.400055555095825   │
    │    5    │ '0xdfa46478f9e5ea86d57387849598dbfb2e964b02-optimism' │ 'Optimism' │ 'extra' │  'MAI'   │ [ '0xdfa46478f9e5ea86d57387849598dbfb2e964b02' ] │  'MAI lending pool'   │ 10806.410033119773 │  2.6317213248795657   │
    │    6    │ '0x6806411765af15bddd26f8f544a34cc40cb9838b-optimism' │ 'Optimism' │ 'extra' │ 'frxETH' │ [ '0x6806411765af15bddd26f8f544a34cc40cb9838b' ] │ 'frxETH lending pool' │ 3588.263867970959  │  1.5985361663437114   │
    │    7    │ '0x296f55f8fb28e498b858d0bcda06d955b2cb3f97-optimism' │ 'Optimism' │ 'extra' │  'STG'   │ [ '0x296f55f8fb28e498b858d0bcda06d955b2cb3f97' ] │  'STG lending pool'   │ 2445.2978833949737 │   5.873538043109394   │
    │    8    │ '0x8700daec35af8ff88c16bdf0418774cb3d7599b4-optimism' │ 'Optimism' │ 'extra' │  'SNX'   │ [ '0x8700daec35af8ff88c16bdf0418774cb3d7599b4' ] │  'SNX lending pool'   │ 1269.5190852908613 │  1.4179676092494153   │
    │    9    │ '0xbfd291da8a403daaf7e5e9dc1ec0aceacd4848b9-optimism' │ 'Optimism' │ 'extra' │  'USX'   │ [ '0xbfd291da8a403daaf7e5e9dc1ec0aceacd4848b9' ] │  'USX lending pool'   │ 1103.4646205054437 │ 0.0025392130747814434 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────┴──────────┴──────────────────────────────────────────────────┴───────────────────────┴────────────────────┴───────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
Error while running extra adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 99 passed, 100 total
    Snapshots:   0 total
    Time:        0.363 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────┬──────────┬──────────────────────────────────────────────────┬───────────────────────┬────────────────────┬───────────────────────┐
    │ (index) │                         pool                          │   chain    │ project │  symbol  │                 underlyingTokens                 │       poolMeta        │       tvlUsd       │        apyBase        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────┼──────────┼──────────────────────────────────────────────────┼───────────────────────┼────────────────────┼───────────────────────┤
    │    0    │ '0x3dc60be8092c851c3f512edbfe3b61fc40d33bb9-optimism' │ 'Optimism' │ 'extra' │  'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │  'WETH lending pool'  │ 33432.76848689328  │  0.7157408590195757   │
    │    1    │ '0xeeadaf138006063a0002baa9490a564412e19656-optimism' │ 'Optimism' │ 'extra' │  'VELO'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05' ] │  'VELO lending pool'  │ 32690.54726404373  │   6.207975556530343   │
    │    2    │ '0x1edf5941f5e52a811dbf5823b497c92a2691d1a4-optimism' │ 'Optimism' │ 'extra' │ 'wstETH' │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ] │ 'wstETH lending pool' │ 28536.156204783787 │  0.4045850605555179   │
    │    3    │ '0x4fb952278a7e01e924d14309bdab38a3235b66a5-optimism' │ 'Optimism' │ 'extra' │  'DOLA'  │ [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │  'DOLA lending pool'  │ 22994.628985233154 │   8.951214788984906   │
    │    4    │ '0x1de04dcd405b2e5e5ecd9cb9875b764416c1c055-optimism' │ 'Optimism' │ 'extra' │   'OP'   │ [ '0x4200000000000000000000000000000000000042' ] │   'OP lending pool'   │ 18578.880430852576 │  13.400055555095825   │
    │    5    │ '0x2ea3f5cfd52cd44404b12957ed4aaabf81986528-optimism' │ 'Optimism' │ 'extra' │  'MAI'   │ [ '0xdfa46478f9e5ea86d57387849598dbfb2e964b02' ] │  'MAI lending pool'   │ 10802.20765493943  │  2.6317213248795657   │
    │    6    │ '0x0b74e5333003eb22fc70a5e7ad3419ecea2bf586-optimism' │ 'Optimism' │ 'extra' │ 'frxETH' │ [ '0x6806411765af15bddd26f8f544a34cc40cb9838b' ] │ 'frxETH lending pool' │ 3588.263867970959  │  1.5985361663437114   │
    │    7    │ '0x78c8b197f964aa664ce997ad706f8a4587c7ffb6-optimism' │ 'Optimism' │ 'extra' │  'STG'   │ [ '0x296f55f8fb28e498b858d0bcda06d955b2cb3f97' ] │  'STG lending pool'   │ 2444.718192819957  │   5.873538043109394   │
    │    8    │ '0x5a57b5bd972d232b9e269afa686a54849f8e4613-optimism' │ 'Optimism' │ 'extra' │  'SNX'   │ [ '0x8700daec35af8ff88c16bdf0418774cb3d7599b4' ] │  'SNX lending pool'   │ 1269.5190852908613 │  1.4179676092494153   │
    │    9    │ '0x300f9ead07d92d222493409d87ed784b873b24a2-optimism' │ 'Optimism' │ 'extra' │  'USX'   │ [ '0xbfd291da8a403daaf7e5e9dc1ec0aceacd4848b9' ] │  'USX lending pool'   │ 1103.4646205054437 │ 0.0025392130747814434 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────┴──────────┴──────────────────────────────────────────────────┴───────────────────────┴────────────────────┴───────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
The extra-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       100 passed, 100 total
    Snapshots:   0 total
    Time:        0.42 s
    Ran all test suites.
    
    Nb of pools: 16
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬──────────┬──────────────────────────────────────────────────┬───────────────────────┬────────────────────┬───────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │  symbol  │                 underlyingTokens                 │       poolMeta        │       tvlUsd       │        apyBase        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼──────────┼──────────────────────────────────────────────────┼───────────────────────┼────────────────────┼───────────────────────┤
    │    0    │ '0x3dc60be8092c851c3f512edbfe3b61fc40d33bb9-optimism' │ 'Optimism' │ 'extra-finance' │  'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │  'WETH lending pool'  │ 33417.950404808355 │  0.7157408590195757   │
    │    1    │ '0xeeadaf138006063a0002baa9490a564412e19656-optimism' │ 'Optimism' │ 'extra-finance' │  'VELO'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05' ] │  'VELO lending pool'  │ 32591.602325621174 │   6.207975556530343   │
    │    2    │ '0x1edf5941f5e52a811dbf5823b497c92a2691d1a4-optimism' │ 'Optimism' │ 'extra-finance' │ 'wstETH' │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ] │ 'wstETH lending pool' │ 28534.55181810835  │  0.4045850605555179   │
    │    3    │ '0x4fb952278a7e01e924d14309bdab38a3235b66a5-optimism' │ 'Optimism' │ 'extra-finance' │  'DOLA'  │ [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │  'DOLA lending pool'  │ 22985.536915486067 │   8.951214788984906   │
    │    4    │ '0x1de04dcd405b2e5e5ecd9cb9875b764416c1c055-optimism' │ 'Optimism' │ 'extra-finance' │   'OP'   │ [ '0x4200000000000000000000000000000000000042' ] │   'OP lending pool'   │ 18580.380430852576 │  13.400040308554239   │
    │    5    │ '0x2ea3f5cfd52cd44404b12957ed4aaabf81986528-optimism' │ 'Optimism' │ 'extra-finance' │  'MAI'   │ [ '0xdfa46478f9e5ea86d57387849598dbfb2e964b02' ] │  'MAI lending pool'   │ 10801.596399931379 │  2.6317213248795657   │
    │    6    │ '0x0b74e5333003eb22fc70a5e7ad3419ecea2bf586-optimism' │ 'Optimism' │ 'extra-finance' │ 'frxETH' │ [ '0x6806411765af15bddd26f8f544a34cc40cb9838b' ] │ 'frxETH lending pool' │ 3566.731345918393  │  1.5985361663437114   │
    │    7    │ '0x78c8b197f964aa664ce997ad706f8a4587c7ffb6-optimism' │ 'Optimism' │ 'extra-finance' │  'STG'   │ [ '0x296f55f8fb28e498b858d0bcda06d955b2cb3f97' ] │  'STG lending pool'   │  2444.29791715307  │   5.873538043109394   │
    │    8    │ '0x5a57b5bd972d232b9e269afa686a54849f8e4613-optimism' │ 'Optimism' │ 'extra-finance' │  'SNX'   │ [ '0x8700daec35af8ff88c16bdf0418774cb3d7599b4' ] │  'SNX lending pool'   │ 1269.5190852908613 │  1.4179676092494153   │
    │    9    │ '0x300f9ead07d92d222493409d87ed784b873b24a2-optimism' │ 'Optimism' │ 'extra-finance' │  'USX'   │ [ '0xbfd291da8a403daaf7e5e9dc1ec0aceacd4848b9' ] │  'USX lending pool'   │ 1102.3622582471967 │ 0.0025392130747814434 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴──────────┴──────────────────────────────────────────────────┴───────────────────────┴────────────────────┴───────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The extra-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       202 passed, 202 total
    Snapshots:   0 total
    Time:        0.577 s
    Ran all test suites.
    
    Nb of pools: 33
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │    symbol    │                                        underlyingTokens                                        │         poolMeta          │       tvlUsd       │      apyBase       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x48dce63bacf1c7c839cfa7d4f871ad17c0d30d38-optimism' │ 'Optimism' │ 'extra-finance' │ 'wUSDR-USDC' │ [ '0x340fe1d898eccaad394e2ba0fc1f93d27c7b717a', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 866398.1273628148  │ 114.58810348501184 │
    │    1    │ '0xe8537b6ff1039cb9ed0b71713f697ddbadbb717d-optimism' │ 'Optimism' │ 'extra-finance' │ 'VELO-USDC'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │  165829.125270676  │ 154.97974455245156 │
    │    2    │ '0x47029bc8f5cbe3b464004e87ef9c9419a48018cd-optimism' │ 'Optimism' │ 'extra-finance' │  'OP-USDC'   │ [ '0x4200000000000000000000000000000000000042', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 95523.45109584792  │ 60.24312541359999  │
    │    3    │ '0xa99817d2d286c894f8f3888096a5616d06f20d46-optimism' │ 'Optimism' │ 'extra-finance' │ 'USD+-DOLA'  │ [ '0x73cb180bf0521828d8849bc8cf2b920918e23032', '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │ 'Leveraged Yield Farming' │ 81450.40468145546  │ 109.86518341856777 │
    │    4    │ '0xdee1856d7b75abf4c1bdf986da4e1c6c7864d640-optimism' │ 'Optimism' │ 'extra-finance' │ 'LYRA-USDC'  │ [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 44753.384466753196 │ 203.68584494939415 │
    │    5    │ '0xeeadaf138006063a0002baa9490a564412e19656-optimism' │ 'Optimism' │ 'extra-finance' │    'VELO'    │                        [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05' ]                        │      'Lending Pool'       │ 36633.96643957635  │ 4.823718050942993  │
    │    6    │ '0x3dc60be8092c851c3f512edbfe3b61fc40d33bb9-optimism' │ 'Optimism' │ 'extra-finance' │    'WETH'    │                        [ '0x4200000000000000000000000000000000000006' ]                        │      'Lending Pool'       │ 33736.783257923365 │ 0.7111649413946486 │
    │    7    │ '0x1edf5941f5e52a811dbf5823b497c92a2691d1a4-optimism' │ 'Optimism' │ 'extra-finance' │   'wstETH'   │                        [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ]                        │      'Lending Pool'       │ 28699.268850119322 │ 0.4045850605555179 │
    │    8    │ '0x4fb952278a7e01e924d14309bdab38a3235b66a5-optimism' │ 'Optimism' │ 'extra-finance' │    'DOLA'    │                        [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ]                        │      'Lending Pool'       │ 23002.313399511782 │ 8.951214788984906  │
    │    9    │ '0x3905870e647c97cb9c8d99db24384f480531b5b9-optimism' │ 'Optimism' │ 'extra-finance' │ 'wstETH-OP'  │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb', '0x4200000000000000000000000000000000000042' ] │ 'Leveraged Yield Farming' │ 19818.209370594097 │ 86.83971725343989  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The extra-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       202 passed, 202 total
    Snapshots:   0 total
    Time:        0.459 s
    Ran all test suites.
    
    Nb of pools: 33
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │    symbol    │                                        underlyingTokens                                        │         poolMeta          │       tvlUsd       │      apyBase       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x48dce63bacf1c7c839cfa7d4f871ad17c0d30d38-optimism' │ 'Optimism' │ 'extra-finance' │ 'wUSDR-USDC' │ [ '0x340fe1d898eccaad394e2ba0fc1f93d27c7b717a', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 870164.0287367936  │ 110.67471729608725 │
    │    1    │ '0xe8537b6ff1039cb9ed0b71713f697ddbadbb717d-optimism' │ 'Optimism' │ 'extra-finance' │ 'VELO-USDC'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 179727.71464393532 │ 136.2254142294887  │
    │    2    │ '0x47029bc8f5cbe3b464004e87ef9c9419a48018cd-optimism' │ 'Optimism' │ 'extra-finance' │  'OP-USDC'   │ [ '0x4200000000000000000000000000000000000042', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 94014.02853403037  │ 66.82561081553513  │
    │    3    │ '0xa99817d2d286c894f8f3888096a5616d06f20d46-optimism' │ 'Optimism' │ 'extra-finance' │ 'USD+-DOLA'  │ [ '0x73cb180bf0521828d8849bc8cf2b920918e23032', '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │ 'Leveraged Yield Farming' │ 81522.92460956385  │ 107.91832909718235 │
    │    4    │ '0xdee1856d7b75abf4c1bdf986da4e1c6c7864d640-optimism' │ 'Optimism' │ 'extra-finance' │ 'LYRA-USDC'  │ [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 45084.24966057417  │ 197.5139128574377  │
    │    5    │ '0x3dc60be8092c851c3f512edbfe3b61fc40d33bb9-optimism' │ 'Optimism' │ 'extra-finance' │    'WETH'    │                        [ '0x4200000000000000000000000000000000000006' ]                        │      'Lending Pool'       │ 29281.76050091667  │ 1.8915648796696383 │
    │    6    │ '0x1edf5941f5e52a811dbf5823b497c92a2691d1a4-optimism' │ 'Optimism' │ 'extra-finance' │   'wstETH'   │                        [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ]                        │      'Lending Pool'       │ 28158.05574494042  │ 0.4045850605555179 │
    │    7    │ '0x4fb952278a7e01e924d14309bdab38a3235b66a5-optimism' │ 'Optimism' │ 'extra-finance' │    'DOLA'    │                        [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ]                        │      'Lending Pool'       │ 23038.035541563786 │ 8.951214788984906  │
    │    8    │ '0x3905870e647c97cb9c8d99db24384f480531b5b9-optimism' │ 'Optimism' │ 'extra-finance' │ 'wstETH-OP'  │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb', '0x4200000000000000000000000000000000000042' ] │ 'Leveraged Yield Farming' │ 19242.129884898164 │ 86.09940536454398  │
    │    9    │ '0x1de04dcd405b2e5e5ecd9cb9875b764416c1c055-optimism' │ 'Optimism' │ 'extra-finance' │     'OP'     │                        [ '0x4200000000000000000000000000000000000042' ]                        │      'Lending Pool'       │ 17803.235172308094 │ 13.499929800508204 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi and ty for adding. we only display lower bound values on our end, thats means for the leveraged yield farms we need use the apy values without any leverage

**Comment by llamatester** [comment]
The extra-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       202 passed, 202 total
    Snapshots:   0 total
    Time:        0.371 s
    Ran all test suites.
    
    Nb of pools: 33
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────┬────────────────────┬─────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │    symbol    │                                        underlyingTokens                                        │         poolMeta          │       tvlUsd       │         apyBase         │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────┼────────────────────┼─────────────────────────┤
    │    0    │ '0x48dce63bacf1c7c839cfa7d4f871ad17c0d30d38-optimism' │ 'Optimism' │ 'extra-finance' │ 'wUSDR-USDC' │ [ '0x340fe1d898eccaad394e2ba0fc1f93d27c7b717a', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 875850.7011944908  │   36.150738841519356    │
    │    1    │ '0xe8537b6ff1039cb9ed0b71713f697ddbadbb717d-optimism' │ 'Optimism' │ 'extra-finance' │ 'VELO-USDC'  │ [ '0x3c8b650257cfb5f272f799f5e2b4e65093a11a05', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 179567.0147190146  │    57.30405334916515    │
    │    2    │ '0x47029bc8f5cbe3b464004e87ef9c9419a48018cd-optimism' │ 'Optimism' │ 'extra-finance' │  'OP-USDC'   │ [ '0x4200000000000000000000000000000000000042', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 94087.47558089439  │    33.95072209195094    │
    │    3    │ '0xa99817d2d286c894f8f3888096a5616d06f20d46-optimism' │ 'Optimism' │ 'extra-finance' │ 'USD+-DOLA'  │ [ '0x73cb180bf0521828d8849bc8cf2b920918e23032', '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ] │ 'Leveraged Yield Farming' │ 81469.27447834249  │   21.512894382753124    │
    │    4    │ '0xdee1856d7b75abf4c1bdf986da4e1c6c7864d640-optimism' │ 'Optimism' │ 'extra-finance' │ 'LYRA-USDC'  │ [ '0x50c5725949a6f0c72e6c4a641f24049a917db0cb', '0x7f5c764cbc14f9669b88837ca1490cca17c31607' ] │ 'Leveraged Yield Farming' │ 45121.530819745756 │    68.9041625662242     │
    │    5    │ '0x3dc60be8092c851c3f512edbfe3b61fc40d33bb9-optimism' │ 'Optimism' │ 'extra-finance' │    'WETH'    │                        [ '0x4200000000000000000000000000000000000006' ]                        │      'Lending Pool'       │  29411.4756128152  │   1.8548551706464522    │
    │    6    │ '0x1edf5941f5e52a811dbf5823b497c92a2691d1a4-optimism' │ 'Optimism' │ 'extra-finance' │   'wstETH'   │                        [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb' ]                        │      'Lending Pool'       │ 28292.271163578214 │   0.3851410062216676    │
    │    7    │ '0x4fb952278a7e01e924d14309bdab38a3235b66a5-optimism' │ 'Optimism' │ 'extra-finance' │    'DOLA'    │                        [ '0x8ae125e8653821e851f12a49f7765db9a9ce7384' ]                        │      'Lending Pool'       │ 22989.159897593407 │    8.951214788984906    │
    │    8    │ '0x300f9ead07d92d222493409d87ed784b873b24a2-optimism' │ 'Optimism' │ 'extra-finance' │    'USX'     │                        [ '0xbfd291da8a403daaf7e5e9dc1ec0aceacd4848b9' ]                        │      'Lending Pool'       │ 21109.46618005805  │ 0.000007060144380233169 │
    │    9    │ '0x3905870e647c97cb9c8d99db24384f480531b5b9-optimism' │ 'Optimism' │ 'extra-finance' │ 'wstETH-OP'  │ [ '0x1f32b1c2345538c0c6f582fcb022739c4a194ebb', '0x4200000000000000000000000000000000000042' ] │ 'Leveraged Yield Farming' │ 19120.35067247102  │    30.69438160030873    │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────┴────────────────────┴─────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by KarmanMax** [comment]
> hi and ty for adding. we only display lower bound values on our end, thats means for the leveraged yield farms we need use the apy values without any leverage

well, it's been updated to baseApy without leverage now.

**Pull request merged**
