### PR TITLE
Add RAMSES yields

### PR DESCRIPTION
**Pull request by keccakdog**
image

### CODE REVIEW

**Comment by llamatester** [comment]
The ramses-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       1026 passed, 1026 total
    Snapshots:   0 total
    Time:        0.688 s
    Ran all test suites.
    
    Nb of pools: 146
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │      project      │    symbol     │       tvlUsd       │     apyReward      │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x3932192de4f17dfb94be031a8458e215a44bf560' │ 'Arbitrum' │ 'ramses-exchange' │ 'frxETH-WETH' │ 2524712.378788924  │ 6.565121955014996  │ [ '0x178412e79c25968a32e89b11f63b33f733770c2a', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    1    │ '0x1850e96550d6716d43ba4d7df815ffc32bd0d03e' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-DOLA'  │ 2018523.357661482  │ 13.304111843875551 │ [ '0x17fc002b466eec40dae837fc4be5c67993ddbd6f', '0x6a7661795c374c0bfc635934efaddff3a7ee23b6' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    2    │ '0x5513a48f3692df1d9c793eeab1349146b2140386' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-USDC'  │ 1447939.9540475048 │  9.68649248132766  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    3    │ '0xdd8b120ddae0f19b922324012816f2f3ce529bf8' │ 'Arbitrum' │ 'ramses-exchange' │  'DOLA-USDC'  │ 1261431.9553593711 │ 3.8554273190493107 │ [ '0x6a7661795c374c0bfc635934efaddff3a7ee23b6', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    4    │ '0x275f7112e3900fdf3c9532d749dd4985790e7933' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-ARB'   │ 1002373.8134162236 │ 10.805836143330492 │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    5    │ '0x6eb34b55cb7bcafa374028d20a1fceab00406a32' │ 'Arbitrum' │ 'ramses-exchange' │ 'cbETH-WETH'  │ 984278.7938940004  │ 5.954103273770434  │ [ '0x1debd73e752beaf79865fd6446b0c970eae7732f', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    6    │ '0xeb9153afbaa3a6cfbd4fce39988cea786d3f62bb' │ 'Arbitrum' │ 'ramses-exchange' │  'USD+-DAI+'  │ 966915.6925561628  │ 9.331090548031565  │ [ '0xe80772eaf6e2e18b651f160bc9158b2a5cafca65', '0xeb8e93a0c7504bffd8a8ffa56cd754c63aaebfe8' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    7    │ '0x3c6ef5ed8ad5df0d5e3d05c6e607c60f987fb735' │ 'Arbitrum' │ 'ramses-exchange' │  'MAI-USDC'   │  886268.589481715  │ 6.840492522884607  │ [ '0x3f56e0c36d275367b8c502090edf38289b3dea0d', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    8    │ '0xba9f17ca67d1c8416bb9b132d50232191e27b45e' │ 'Arbitrum' │ 'ramses-exchange' │  'ARB-USDC'   │ 806853.9453429591  │ 13.428547437571742 │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548', '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    │    9    │ '0x8ac36fbce743b632d228f9c2ea5e3bb8603141c7' │ 'Arbitrum' │ 'ramses-exchange' │ 'TAROT-WETH'  │ 780125.5145124107  │ 72.65179428465959  │ [ '0x6688b00f0c23a4a546beaae51a7c90c439895d48', '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ [ '0xaaa6c1e32c55a7bfa8066a6fae9b42650f262418' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, ty for adding. sir no longer accept pure adapters. pls refactor to on chain calls/subgraph instead

**Comment by llamatester** [comment]
The ramses-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       694 passed, 694 total
    Snapshots:   0 total
    Time:        0.502 s
    Ran all test suites.
    
    Nb of pools: 115
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────┬───────────────┬────────────────────┬───────────┬──────────────┐
    │ (index) │                     pool                     │   chain    │      project      │    symbol     │       tvlUsd       │ apyReward │ rewardTokens │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────┼───────────────┼────────────────────┼───────────┼──────────────┤
    │    0    │ '0x3932192dE4f17DFB94Be031a8458E215A44BF560' │ 'Arbitrum' │ 'ramses-exchange' │ 'FRXETH-WETH' │ 3057343.893861262  │     0     │      []      │
    │    1    │ '0x5513a48F3692Df1d9C793eeaB1349146B2140386' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-USDC'  │ 1722641.7403018204 │     0     │      []      │
    │    2    │ '0xeb9153afBAa3A6cFbd4fcE39988Cea786d3F62bb' │ 'Arbitrum' │ 'ramses-exchange' │  'USD+-DAI+'  │ 1719697.2561677436 │     0     │      []      │
    │    3    │ '0x1850e96550d6716d43bA4d7DF815FfC32bD0d03e' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-DOLA'  │ 1633830.103775503  │     0     │      []      │
    │    4    │ '0x275F7112e3900FdF3c9532d749Dd4985790e7933' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-ARB'   │ 1149669.2859623022 │     0     │      []      │
    │    5    │ '0x3c6eF5Ed8ad5DF0d5e3D05C6e607c60F987fB735' │ 'Arbitrum' │ 'ramses-exchange' │  'MAI-USDC'   │ 941542.4037551879  │     0     │      []      │
    │    6    │ '0xDd8b120DdaE0F19b922324012816F2F3Ce529BF8' │ 'Arbitrum' │ 'ramses-exchange' │  'DOLA-USDC'  │ 790467.1728577189  │     0     │      []      │
    │    7    │ '0x218fdEE44e8e923b500895e324Af6c0a2e07195d' │ 'Arbitrum' │ 'ramses-exchange' │  'YFX-USDC'   │ 775221.3220157493  │     0     │      []      │
    │    8    │ '0x8aC36fBCe743b632d228F9c2EA5E3BB8603141C7' │ 'Arbitrum' │ 'ramses-exchange' │ 'TAROT-WETH'  │ 759004.6607703597  │     0     │      []      │
    │    9    │ '0xba9f17ca67d1C8416Bb9b132D50232191e27B45e' │ 'Arbitrum' │ 'ramses-exchange' │  'ARB-USDC'   │ 671367.5859501194  │     0     │      []      │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────┴───────────────┴────────────────────┴───────────┴──────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by keccakdog** [comment]
@slasher125 ser we are the ready. send it

**Comment by llamatester** [comment]
The ramses-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       784 passed, 784 total
    Snapshots:   0 total
    Time:        0.508 s
    Ran all test suites.
    
    Nb of pools: 130
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │      project      │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x3932192dE4f17DFB94Be031a8458E215A44BF560' │ 'Arbitrum' │ 'ramses-exchange' │ 'FRXETH-WETH' │ 3068552.4881300367 │ 9.594744718263854  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    1    │ '0xeb9153afBAa3A6cFbd4fcE39988Cea786d3F62bb' │ 'Arbitrum' │ 'ramses-exchange' │  'USD+-DAI+'  │ 1740619.0581223017 │ 9.156455104797136  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    2    │ '0x1850e96550d6716d43bA4d7DF815FfC32bD0d03e' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-DOLA'  │ 1669919.2229231927 │ 24.880145806245466 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    3    │ '0x5513a48F3692Df1d9C793eeaB1349146B2140386' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-USDC'  │ 1396378.986344158  │ 16.52608746777492  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    4    │ '0x275F7112e3900FdF3c9532d749Dd4985790e7933' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-ARB'   │ 1035769.6998541927 │ 15.092641379702398 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    5    │ '0x3c6eF5Ed8ad5DF0d5e3D05C6e607c60F987fB735' │ 'Arbitrum' │ 'ramses-exchange' │  'MAI-USDC'   │ 1027568.9750392828 │  9.14825983198221  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    6    │ '0xDd8b120DdaE0F19b922324012816F2F3Ce529BF8' │ 'Arbitrum' │ 'ramses-exchange' │  'DOLA-USDC'  │ 791034.4160241743  │ 23.906107392048973 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    7    │ '0x218fdEE44e8e923b500895e324Af6c0a2e07195d' │ 'Arbitrum' │ 'ramses-exchange' │  'YFX-USDC'   │ 783000.4487816973  │ 61.90209525755629  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    8    │ '0xba9f17ca67d1C8416Bb9b132D50232191e27B45e' │ 'Arbitrum' │ 'ramses-exchange' │  'ARB-USDC'   │ 674572.1449543624  │ 18.49084926939645  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    9    │ '0x3F6253767208aAf70071d563403C8023809d52FF' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-MAI'   │ 664876.3911551763  │ 11.493233136621916 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
apy values seem to be larger than lower bound on ui. pls make sure that these are unboosted/lower bound

**Comment by keccakdog** [comment]
> great. one thing: apy values seem to be larger than lower bound on ui. pls make sure that these are unboosted/lower bound

Hey, we saw this too but doublechecked our code and there is nothing that would be giving the non-correct APR for this script output. Our frontend/api is probably just off. This on-chain call method for getting APRs has no alternative calculations, it's the same as other solidly forks submitted.

**Comment by slasher125** [comment]
are there any fees that need u aren't considered here? i mean the yields here are 1.3x whats on your ui.

**Comment by keccakdog** [comment]
there's no fees, which is why it's strange. I genuinely can't find what the error/issue is, can you? Struggling out here 😢 @slasher125

**Comment by slasher125** [comment]
haha, unfortunately no to api calls (most problems i encounter when running backend comes from centralised apis...).

so given the delta is rather large i don't feel comfortable pushing it as is. can u check in with ur team and see how lower bound values are calculated from your api response? pretty sure it must be something simple...things that come to mind are: tvl is wrong; or rewardRate needs to be scaled?

**Comment by llamatester** [comment]
The ramses-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       430 passed, 430 total
    Snapshots:   0 total
    Time:        0.557 s
    Ran all test suites.
    
    Nb of pools: 71
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────────────┬───────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │      project      │    symbol     │       tvlUsd       │     apyReward      │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────────────┼───────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x3932192dE4f17DFB94Be031a8458E215A44BF560' │ 'Arbitrum' │ 'ramses-exchange' │ 'FRXETH-WETH' │ 3020659.098223911  │ 7.0391463198352655 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    1    │ '0xeb9153afBAa3A6cFbd4fcE39988Cea786d3F62bb' │ 'Arbitrum' │ 'ramses-exchange' │  'USD+-DAI+'  │ 1738733.4045595275 │ 6.723981102407295  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    2    │ '0x1850e96550d6716d43bA4d7DF815FfC32bD0d03e' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-DOLA'  │ 1670722.2393990867 │ 18.12457523361388  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    3    │ '0x5513a48F3692Df1d9C793eeaB1349146B2140386' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-USDC'  │ 1397413.1318235332 │ 12.194206115355998 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    4    │ '0x3c6eF5Ed8ad5DF0d5e3D05C6e607c60F987fB735' │ 'Arbitrum' │ 'ramses-exchange' │  'MAI-USDC'   │ 1027133.6366008199 │ 6.701045774239709  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    5    │ '0x275F7112e3900FdF3c9532d749Dd4985790e7933' │ 'Arbitrum' │ 'ramses-exchange' │  'WETH-ARB'   │ 1025503.6707641993 │ 11.19716977074847  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    6    │ '0xDd8b120DdaE0F19b922324012816F2F3Ce529BF8' │ 'Arbitrum' │ 'ramses-exchange' │  'DOLA-USDC'  │ 791015.7356258233  │ 17.41678532736179  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    7    │ '0x218fdEE44e8e923b500895e324Af6c0a2e07195d' │ 'Arbitrum' │ 'ramses-exchange' │  'YFX-USDC'   │ 781600.1586422058  │ 44.290503692935275 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    8    │ '0xba9f17ca67d1C8416Bb9b132D50232191e27B45e' │ 'Arbitrum' │ 'ramses-exchange' │  'ARB-USDC'   │ 674615.0742206634  │ 13.721439007279091 │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    │    9    │ '0x3F6253767208aAf70071d563403C8023809d52FF' │ 'Arbitrum' │ 'ramses-exchange' │  'FRAX-MAI'   │ 664909.8858404462  │ 8.376108739088654  │ [ '0xAAA6C1E32C55A7Bfa8066A6FAE9b42650F262418' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────────────┴───────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
excellente 🙏

**Pull request merged**
