### PR TITLE
feat: add hydt yield adapter

### PR DESCRIPTION
**Pull request by hydtdev**

### CODE REVIEW

**Comment by llamatester** [comment]
The hydt-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.396 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────────┬─────────────┬──────────────────────────────────────────┬────────────────────┬───────────────────┬───────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────┬─────────────┐
    │ (index) │                         pool                         │   chain   │     project     │   symbol    │                   url                    │       tvlUsd       │      apyBase      │ apyBase7d │ apyReward │                                          rewardTokens                                          │                 underlyingTokens                 │ volumeUsd1d │ volumeUsd7d │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────────┼─────────────┼──────────────────────────────────────────┼────────────────────┼───────────────────┼───────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────┼─────────────┤
    │    0    │ '0xbb8ae522f812e9e65239a0e5db87a9d738ce957a-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-WBNB' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 11027.336780018763 │ 768.4309918033389 │     0     │     0     │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0xBB8ae522F812E9E65239A0e5db87a9D738ce957a' ] │      0      │      0      │
    │    1    │ '0x03fed6ecf872a827c07eab63106e8f04aef79f0d-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-USDT' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 7069.111828921095  │ 1198.700422894928 │     0     │     0     │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0x03feD6eCF872a827C07EAb63106E8f04AeF79f0d' ] │      0      │      0      │
    │    2    │ '0xe0e9bbc7ae8ebe4d74065f6ebd710665da285a0b-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-HYGT' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 6243.254100031736  │ 678.6322647652753 │     0     │     0     │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0xE0e9bBc7aE8EBE4D74065F6EBD710665DA285a0B' ] │      0      │      0      │
    │    3    │ '0x9810512be701801954449408966c630595d0cd51-binance' │ 'Binance' │ 'hydt-protocol' │   'HYDT'    │ 'https://app.hydtprotocol.com/HYDT/earn' │ 4544.450654030875  │ 4414.503669182733 │     0     │     0     │ [ '0x9810512Be701801954449408966c630595D0cD51', '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ] │ [ '0x9810512Be701801954449408966c630595D0cD51' ] │      0      │      0      │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────────┴─────────────┴──────────────────────────────────────────┴────────────────────┴───────────────────┴───────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────┴─────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding.
apyBase = fee
apyReward = incentives

it seems like you are adding up all components under apyBase?
also, can u share a url to the a pools apy on our ui? its not loading any details even after connecting. ty

**Comment by hydtdev** [comment]
Hi @slasher125, thank you for the response.

If I understand correctly, any tokens being cut as fees and then being redistributed to the users as rewards would go to apyBase and if not then they go to apyReward. If that is the case then there is a slight error on my part. All of our rewards are minted directly to the user as incentives and hence should go to apyRewards. Should I submit a new PR or can you make the changes by swapping the values for apyBase and apyReward at Line#275 and Line#356 (kindly change the variable name as well from "baseAPY" to "rewardAPY" declared at Line#344)?

The front end is having issues right now and is not showing any APY. I'm currently looking into that as well.

**Comment by slasher125** [comment]
hey, yes exactly. yes, just commit the changes to this pr

**Comment by hydtdev** [comment]
@slasher125 Changes committed. Kindly have a look if the commit is done correctly or not.

**Comment by llamatester** [comment]
The hydt-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.422 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────────────┬─────────────┬──────────────────────────────────────────┬────────────────────┬─────────┬───────────┬───────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────┬─────────────┐
    │ (index) │                         pool                         │   chain   │     project     │   symbol    │                   url                    │       tvlUsd       │ apyBase │ apyBase7d │     apyReward     │                                          rewardTokens                                          │                 underlyingTokens                 │ volumeUsd1d │ volumeUsd7d │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────────────┼─────────────┼──────────────────────────────────────────┼────────────────────┼─────────┼───────────┼───────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────┼─────────────┤
    │    0    │ '0xbb8ae522f812e9e65239a0e5db87a9d738ce957a-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-WBNB' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 11318.440463596635 │    0    │     0     │ 759.1470284810624 │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0xBB8ae522F812E9E65239A0e5db87a9D738ce957a' ] │      0      │      0      │
    │    1    │ '0x03fed6ecf872a827c07eab63106e8f04aef79f0d-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-USDT' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 7124.385241336605  │    0    │     0     │ 1206.049385864933 │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0x03feD6eCF872a827C07EAb63106E8f04AeF79f0d' ] │      0      │      0      │
    │    2    │ '0xe0e9bbc7ae8ebe4d74065f6ebd710665da285a0b-binance' │ 'Binance' │ 'hydt-protocol' │ 'HYDT-HYGT' │ 'https://app.hydtprotocol.com/HYDT/farm' │ 6335.718128584596  │    0    │     0     │ 678.0889135687246 │                        [ '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ]                        │ [ '0xE0e9bBc7aE8EBE4D74065F6EBD710665DA285a0B' ] │      0      │      0      │
    │    3    │ '0x9810512be701801954449408966c630595d0cd51-binance' │ 'Binance' │ 'hydt-protocol' │   'HYDT'    │ 'https://app.hydtprotocol.com/HYDT/earn' │ 4648.810654259835  │    0    │     0     │ 4394.754040858167 │ [ '0x9810512Be701801954449408966c630595D0cD51', '0x100995a7e5fFd8Ee60cc18A10C75CEe8C572c59b' ] │ [ '0x9810512Be701801954449408966c630595D0cD51' ] │      0      │      0      │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────────────┴─────────────┴──────────────────────────────────────────┴────────────────────┴─────────┴───────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────┴─────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by christianlantin** [comment]
Master

**Pull request merged**
