### PR TITLE
GoGoPool: Add ggAVAX Yields for the GoGoPool LST Protocol

### PR DESCRIPTION
**Pull request by ThomasPiXX**
This pull request adds yields for the ggAVAX Liquid Staking Token (LST) using the official GoGoPool API.

Key Changes:

Integration of ggAVAX Yields:

Implemented fetching of yield data for ggAVAX using the GoGoPool official API.
Ensured the TVL (Total Value Locked) is calculated accurately based on on-chain data.
TVL Calculation:

TVL is now fetched directly from on-chain sources as requested, providing more accurate and reliable data.
Revisions:

This pull request addresses issues with the previous fork/branch.
The implementation has been revised and tested to ensure it meets the requirements.

### CODE REVIEW

**Comment by llamatester** [comment]
The gogopool adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.253 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────┬─────────────┬────────────┬────────┬────────────────────┬─────────────┬───────────┬──────────────┬──────────────────┐
    │ (index) │   pool   │    chain    │  project   │ symbol │       tvlUsd       │   apyBase   │ apyReward │ rewardTokens │ underlyingTokens │
    ├─────────┼──────────┼─────────────┼────────────┼────────┼────────────────────┼─────────────┼───────────┼──────────────┼──────────────────┤
    │    0    │ 'ggAVAX' │ 'Avalanche' │ 'gogopool' │ 'GGP'  │ 18496648.585960917 │ 6.946615381 │     0     │      []      │   [ 'wavax' ]    │
    └─────────┴──────────┴─────────────┴────────────┴────────┴────────────────────┴─────────────┴───────────┴──────────────┴──────────────────┘

**Comment by slasher125** [comment]
- underlyingTokens -> should be an address
- please remove the main.then() block
- pool should be an address

**Comment by llamatester** [comment]
The gogopool adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       11 passed, 11 total
    Snapshots:   0 total
    Time:        0.304 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬────────────┬────────┬───────────────────┬─────────────┬───────────┬──────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │    chain    │  project   │ symbol │      tvlUsd       │   apyBase   │ apyReward │ rewardTokens │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼────────────┼────────┼───────────────────┼─────────────┼───────────┼──────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xA25EaF2906FA1a3a13EdAc9B9657108Af7B703e3' │ 'Avalanche' │ 'gogopool' │ 'GGP'  │ 16782301.34295996 │ 6.611913666 │     0     │      []      │ [ '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7' ] │
    └─────────┴──────────────────────────────────────────────┴─────────────┴────────────┴────────┴───────────────────┴─────────────┴───────────┴──────────────┴──────────────────────────────────────────────────┘

**Comment by ThomasPiXX** [comment]
GM

underlying token is now an address 
main().then has been remove 
pool is now an address

**Pull request merged**
