### PR TITLE
solidly-v2 eth integration

### PR DESCRIPTION
**Pull request by Armax**

### CODE REVIEW

**Comment by llamatester** [comment]
The solidly-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       340 passed, 340 total
    Snapshots:   0 total
    Time:        0.486 s
    Ran all test suites.
    
    Nb of pools: 48
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │    symbol     │       tvlUsd       │ apyReward │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x63A65a174Cc725824188940255aD41c371F28F28' │ 'Ethereum' │ 'solidly-v2' │  'USDC-USDT'  │ 13378535.517388802 │  15.4282  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    1    │ '0xcD452c162dA7761f08F656B8e5eDe3A385981378' │ 'Ethereum' │ 'solidly-v2' │  'USDC-WETH'  │ 8433640.261290133  │  33.4421  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    2    │ '0x97F088b0175A7319059d8e705286aA035077d624' │ 'Ethereum' │ 'solidly-v2' │  'FRAX-USDT'  │ 7432912.848936842  │  15.9402  │ [ '0x853d955aCEf822Db058eb8505911ED77F175b99e', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    3    │ '0x4E30fc7ccD2dF3ddCA39a69d2085334Ee63b9c96' │ 'Ethereum' │ 'solidly-v2' │ 'frxETH-WETH' │ 7118829.677199099  │  16.7422  │ [ '0x5E8422345238F34275888049021821E8E08CAa1f', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    4    │ '0xc7ed724499946C8d12F57330c0d2D25Af219AdF8' │ 'Ethereum' │ 'solidly-v2' │  'USDC-DEI'   │ 6356843.226282673  │  16.7072  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xDE1E704dae0B4051e80DAbB26ab6ad6c12262DA0' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    5    │ '0x4EF3fF9dadBa30cff48133f5Dc780A28fc48693F' │ 'Ethereum' │ 'solidly-v2' │ 'xDEUS-DEUS'  │ 4338315.640423991  │  22.7451  │ [ '0x953Cd009a490176FcEB3a26b9753e6F01645ff28', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    6    │ '0xed82dE5C52b2CdeB3FeEd2a4a7f87d60300E19b5' │ 'Ethereum' │ 'solidly-v2' │  'WETH-DEI'   │ 2011345.0905598176 │  37.8863  │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xDE1E704dae0B4051e80DAbB26ab6ad6c12262DA0' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    7    │ '0xEb9dC7087607be7D7C3Ccbb4544347dE1354720c' │ 'Ethereum' │ 'solidly-v2' │  'MIM-USDC'   │ 1997830.258487098  │  17.6465  │ [ '0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    8    │ '0x6D7824C5B5B385D1DD8D56c543A0be2EAF140974' │ 'Ethereum' │ 'solidly-v2' │  'LUSD-WETH'  │ 1249162.0068575083 │  39.8778  │ [ '0x5f98805A4E8be255a32880FDeC7F6728C6568bA0', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    9    │ '0x642431623AE5d73C19fC931aAeA0d4677303880c' │ 'Ethereum' │ 'solidly-v2' │ 'SOLID-WETH'  │ 1228026.778584883  │ 560.1191  │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────┴────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi sir. ty for adding. we no longer accept api adapters, pls refactor using on chain calls instead

**Comment by Armax** [comment]
> hi sir. ty for adding. we no longer accept api adapters, pls refactor using on chain calls/subgraphs instead

I checked the repo and currently there aren't solidly forks that use on chain calls, only api adapters since calculating it on chain requires a lot of calls, can we proceed with the api adapter while we rework the adapter trying to do it on chain?

**Comment by slasher125** [comment]
at min we need to pull tvl from on chain which is easy

**Comment by Armax** [comment]
> at min we need to pull tvl from on chain which is easy

Yes we can do this, however I think that this could lead to wrong data, since you are asking the TVL in usd and not the token amount, if a path to calculate the price of a specific token in usdc change we need to update the adapter to handle it or fetch the correct pricing path from an external api (and we have the same problem).

**Comment by slasher125** [comment]
u can just use our price api for that. lmk if unclear

**Comment by Armax** [comment]
> u can just use our price api for that. lmk if unclear

Already tried with your pricing api but it doesn't return data for our LPs that's why I switched to our api

**Comment by slasher125** [comment]
I'd just pull the prices using the underlying token addresses, pretty sure we got them convered

**Comment by Armax** [comment]
@slasher125 moved everything to subgraph except the APRs

**Comment by slasher125** [comment]
great. one more thing: we do not! show boosted apr values, but lower bound values instead (see readme). 
it seems the values here are all assuming max boost via veSOLID. 

pls update the apr values to lower bound/unboosted values

**Comment by Armax** [comment]
@slasher125 now we are pausing the boosting programs in 7 hours from now so everything is "boosted" after that. No need to change the pull request once the boost is paused

**Comment by llamatester** [comment]
The solidly-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       375 passed, 375 total
    Snapshots:   0 total
    Time:        0.453 s
    Ran all test suites.
    
    Nb of pools: 53
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │    symbol     │       tvlUsd       │ apyReward │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xeb9dc7087607be7d7c3ccbb4544347de1354720c' │ 'Ethereum' │ 'solidly-v2' │  'MIM-USDC'   │ 291630444.63956946 │  0.6891   │ [ '0x99d8a9c45b2eca8864373a26d1459e3dff1e17f3', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    1    │ '0x4ef3ff9dadba30cff48133f5dc780a28fc48693f' │ 'Ethereum' │ 'solidly-v2' │ 'xDEUS-DEUS'  │ 4324421.616024032  │  0.1239   │ [ '0x953cd009a490176fceb3a26b9753e6f01645ff28', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    2    │ '0xc7ed724499946c8d12f57330c0d2d25af219adf8' │ 'Ethereum' │ 'solidly-v2' │  'USDC-DEI'   │  4310936.06301591  │  7.8507   │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xde1e704dae0b4051e80dabb26ab6ad6c12262da0' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    3    │ '0x4e30fc7ccd2df3ddca39a69d2085334ee63b9c96' │ 'Ethereum' │ 'solidly-v2' │ 'frxETH-WETH' │ 3270773.294698349  │  20.8846  │ [ '0x5e8422345238f34275888049021821e8e08caa1f', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    4    │ '0xcd452c162da7761f08f656b8e5ede3a385981378' │ 'Ethereum' │ 'solidly-v2' │  'USDC-WETH'  │   2917528.517584   │  54.6012  │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    5    │ '0x6d7824c5b5b385d1dd8d56c543a0be2eaf140974' │ 'Ethereum' │ 'solidly-v2' │  'LUSD-WETH'  │ 919137.7007669621  │  68.3575  │ [ '0x5f98805a4e8be255a32880fdec7f6728c6568ba0', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    6    │ '0x97f088b0175a7319059d8e705286aa035077d624' │ 'Ethereum' │ 'solidly-v2' │  'FRAX-USDT'  │ 826487.3713534031  │  37.9451  │ [ '0x853d955acef822db058eb8505911ed77f175b99e', '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    7    │ '0x0df99e55fd9f829a2a57097da4469925e90ab8c3' │ 'Ethereum' │ 'solidly-v2' │  'WETH-DEUS'  │ 807004.1108063161  │  92.2576  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    8    │ '0x63a65a174cc725824188940255ad41c371f28f28' │ 'Ethereum' │ 'solidly-v2' │  'USDC-USDT'  │ 804410.2403714578  │  37.2794  │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    9    │ '0x642431623ae5d73c19fc931aaea0d4677303880c' │ 'Ethereum' │ 'solidly-v2' │ 'SOLID-WETH'  │ 704469.1328823299  │ 499.9822  │ [ '0x777172d858dc1599914a1c4c6c9fc48c99a60990', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────┴────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
@Armax ok got it. pls check mim-usdc and xdeus-deus pool tvls, they seem to be wrong (at least when comparing it to the UI)

**Comment by llamatester** [comment]
The solidly-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       375 passed, 375 total
    Snapshots:   0 total
    Time:        0.544 s
    Ran all test suites.
    
    Nb of pools: 53
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────────┬───────────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project    │    symbol     │       tvlUsd       │ apyReward │                                        underlyingTokens                                        │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────────┼───────────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xc7ed724499946c8d12f57330c0d2d25af219adf8' │ 'Ethereum' │ 'solidly-v2' │  'USDC-DEI'   │  4348704.15820215  │  6.3681   │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xde1e704dae0b4051e80dabb26ab6ad6c12262da0' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    1    │ '0x4e30fc7ccd2df3ddca39a69d2085334ee63b9c96' │ 'Ethereum' │ 'solidly-v2' │ 'frxETH-WETH' │ 3175190.5418715742 │  16.0559  │ [ '0x5e8422345238f34275888049021821e8e08caa1f', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    2    │ '0xcd452c162da7761f08f656b8e5ede3a385981378' │ 'Ethereum' │ 'solidly-v2' │  'USDC-WETH'  │ 3014257.5263557937 │  39.0024  │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    3    │ '0x4ef3ff9dadba30cff48133f5dc780a28fc48693f' │ 'Ethereum' │ 'solidly-v2' │ 'xDEUS-DEUS'  │ 2938717.3580374047 │  0.1047   │ [ '0x953cd009a490176fceb3a26b9753e6f01645ff28', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    4    │ '0x97f088b0175a7319059d8e705286aa035077d624' │ 'Ethereum' │ 'solidly-v2' │  'FRAX-USDT'  │ 1927390.0253752205 │  14.9915  │ [ '0x853d955acef822db058eb8505911ed77f175b99e', '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    5    │ '0x63a65a174cc725824188940255ad41c371f28f28' │ 'Ethereum' │ 'solidly-v2' │  'USDC-USDT'  │ 1854178.6449024957 │  13.4112  │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    6    │ '0x6d7824c5b5b385d1dd8d56c543a0be2eaf140974' │ 'Ethereum' │ 'solidly-v2' │  'LUSD-WETH'  │ 1171017.133843561  │  43.5245  │ [ '0x5f98805a4e8be255a32880fdec7f6728c6568ba0', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    7    │ '0x0df99e55fd9f829a2a57097da4469925e90ab8c3' │ 'Ethereum' │ 'solidly-v2' │  'WETH-DEUS'  │ 801256.0752201672  │  75.8183  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xde5ed76e7c05ec5e4572cfc88d1acea165109e44' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    8    │ '0x642431623ae5d73c19fc931aaea0d4677303880c' │ 'Ethereum' │ 'solidly-v2' │ 'SOLID-WETH'  │ 675364.9900900634  │ 441.9322  │ [ '0x777172d858dc1599914a1c4c6c9fc48c99a60990', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    │    9    │ '0xed82de5c52b2cdeb3feed2a4a7f87d60300e19b5' │ 'Ethereum' │ 'solidly-v2' │  'WETH-DEI'   │ 604417.6133794453  │  44.5155  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xde1e704dae0b4051e80dabb26ab6ad6c12262da0' ] │ [ '0x777172D858dC1599914a1C4c6c9fC48c99a60990' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────────┴───────────────┴────────────────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by Armax** [comment]
@slasher125 since some data in the graph have pricing errors from low liquidity pair, I updated the adapter to use defillama prices, if some price are not found (only 5 pairs atm) it will fallback to graph, this should handle all the cases

**Pull request merged**
