### PR TITLE
Add PsyFinance as part of the adapters

### PR DESCRIPTION
**Pull request by gilbertzhuo**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running psyfinance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 53 passed, 54 total
    Snapshots:   0 total
    Time:        0.356 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────┬──────────┬──────────────┬───────────────────┬────────────┬────────────────────┬────────────────────┐
    │ (index) │       pool        │  chain   │   project    │      symbol       │  poolMeta  │       tvlUsd       │      apyBase       │
    ├─────────┼───────────────────┼──────────┼──────────────┼───────────────────┼────────────┼────────────────────┼────────────────────┤
    │    0    │     'btc-put'     │ 'Solana' │ 'psyfinance' │     'btc-put'     │ 'vault-v2' │ 370686.2793378533  │ 36.05706713820788  │
    │    1    │    'srm-call'     │ 'Solana' │ 'psyfinance' │    'srm-call'     │ 'vault-v2' │ 228693.57202460355 │ 4.963191901106345  │
    │    2    │     'sol-put'     │ 'Solana' │ 'psyfinance' │     'sol-put'     │ 'vault-v2' │ 51848.839326766196 │ 21.215862299297882 │
    │    3    │    'dust-call'    │ 'Solana' │ 'psyfinance' │    'dust-call'    │ 'vault-v2' │ 20048.68937621072  │ 33.82303597277274  │
    │    4    │ 'scnsol-sol-call' │ 'Solana' │ 'psyfinance' │ 'scnsol-sol-call' │ 'vault-v2' │ 13449.137964440637 │ 11.02216868502679  │
    │    5    │    'sol-call'     │ 'Solana' │ 'psyfinance' │    'sol-call'     │ 'vault-v2' │ 8130.1505433738175 │ 34.827289589596816 │
    │    6    │   'stsol-call'    │ 'Solana' │ 'psyfinance' │   'stsol-call'    │ 'vault-v2' │ 3536.4508418846617 │ 35.67235252230718  │
    │    7    │    'ftt-call'     │ 'Solana' │ 'psyfinance' │    'ftt-call'     │ 'vault-v2' │   1049.87241753    │         25         │
    │    8    │    'eth-call'     │ 'Solana' │ 'psyfinance' │    'eth-call'     │ 'vault-v2' │ 148.69770110545036 │ 33.916381881374406 │
    │    9    │    'btc-call'     │ 'Solana' │ 'psyfinance' │    'btc-call'     │ 'vault-v2' │ 8.836106594310476  │ 34.04257076385106  │
    └─────────┴───────────────────┴──────────┴──────────────┴───────────────────┴────────────┴────────────────────┴────────────────────┘
    }

**Comment by gilbertzhuo** [comment]
Ser updated the files

**Comment by llamatester** [comment]
The psyoptions adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       54 passed, 54 total
    Snapshots:   0 total
    Time:        0.425 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────┬──────────┬──────────────┬───────────────────┬────────────┬────────────────────┬────────────────────┐
    │ (index) │       pool        │  chain   │   project    │      symbol       │  poolMeta  │       tvlUsd       │      apyBase       │
    ├─────────┼───────────────────┼──────────┼──────────────┼───────────────────┼────────────┼────────────────────┼────────────────────┤
    │    0    │     'btc-put'     │ 'Solana' │ 'psyoptions' │     'btc-put'     │ 'vault-v2' │ 370686.2793378533  │ 36.49922107448486  │
    │    1    │    'srm-call'     │ 'Solana' │ 'psyoptions' │    'srm-call'     │ 'vault-v2' │ 228693.57202460355 │ 4.963191901106345  │
    │    2    │     'sol-put'     │ 'Solana' │ 'psyoptions' │     'sol-put'     │ 'vault-v2' │ 51848.839326766196 │ 21.215862299297882 │
    │    3    │    'dust-call'    │ 'Solana' │ 'psyoptions' │    'dust-call'    │ 'vault-v2' │ 20048.68937621072  │ 33.82303597277274  │
    │    4    │ 'scnsol-sol-call' │ 'Solana' │ 'psyoptions' │ 'scnsol-sol-call' │ 'vault-v2' │ 13449.137964440637 │ 11.02216868502679  │
    │    5    │    'sol-call'     │ 'Solana' │ 'psyoptions' │    'sol-call'     │ 'vault-v2' │ 8130.1505433738175 │ 34.91783972386193  │
    │    6    │   'stsol-call'    │ 'Solana' │ 'psyoptions' │   'stsol-call'    │ 'vault-v2' │ 3536.4508418846617 │ 35.70874389444609  │
    │    7    │    'ftt-call'     │ 'Solana' │ 'psyoptions' │    'ftt-call'     │ 'vault-v2' │   1049.87241753    │         25         │
    │    8    │    'eth-call'     │ 'Solana' │ 'psyoptions' │    'eth-call'     │ 'vault-v2' │ 148.69770110545036 │ 33.93084605965399  │
    │    9    │    'btc-call'     │ 'Solana' │ 'psyoptions' │    'btc-call'     │ 'vault-v2' │ 8.836106594310476  │ 34.06694725702532  │
    └─────────┴───────────────────┴──────────┴──────────────┴───────────────────┴────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
hey, great ty for adding. a couple of things:
- pls change symbol from `btc-put` to just `btc` and set `poolMeta = 'put'`
- re baseApy: this should just be the apy from the option strategy and apyReward I'd set to the serum rewards. also, please use no lockup period instead of the max. eg like here:

Screenshot 2022-09-19 at 15 08 03

so, `apyBase = ~6` and `apyReward = 12`

**Comment by gilbertzhuo** [comment]
> hey, great ty for adding. a couple of things:
> 
> * pls change symbol from `btc-put` to just `btc` and set `poolMeta = 'put'`
> * re baseApy: this should just be the apy from the option strategy and apyReward I'd set to the serum rewards. also, please use no lockup period instead of the max. eg like here:
> 
> Screenshot 2022-09-19 at 15 08 03
> 
> so, `apyBase = ~6` and `apyReward = 12`
Updated the code ser

**Comment by llamatester** [comment]
The psyoptions adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       59 passed, 59 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬───────────────────┬──────────┬──────────────┬──────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬──────────────┐
    │ (index) │       pool        │  chain   │   project    │  symbol  │ poolMeta │       tvlUsd       │      apyBase       │     apyReward      │ rewardTokens │
    ├─────────┼───────────────────┼──────────┼──────────────┼──────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼──────────────┤
    │    0    │ 'scnsol-sol-call' │ 'Solana' │ 'psyoptions' │ 'SCNSOL' │  'call'  │ 444220.06251521903 │ 11.02216868502679  │                    │              │
    │    1    │     'btc-put'     │ 'Solana' │ 'psyoptions' │  'USDC'  │  'put'   │ 417102.29680619494 │ 5.8429779506238955 │ 13.08262472527392  │  [ 'SRM' ]   │
    │    2    │    'sol-call'     │ 'Solana' │ 'psyoptions' │  'SOL'   │  'call'  │ 249236.98407274822 │ 11.970434109639804 │ 9.519036126392376  │  [ 'SRM' ]   │
    │    3    │    'eth-call'     │ 'Solana' │ 'psyoptions' │  'ETH'   │  'call'  │  215011.30550069   │ 7.037255117314811  │ 11.168117164234843 │  [ 'SRM' ]   │
    │    4    │    'srm-call'     │ 'Solana' │ 'psyoptions' │  'SRM'   │  'call'  │ 173428.58368900666 │ 4.963191901106345  │                    │              │
    │    5    │    'btc-call'     │ 'Solana' │ 'psyoptions' │  'BTC'   │  'call'  │ 167813.04173800003 │ 4.200686552957222  │ 12.367901125545282 │  [ 'SRM' ]   │
    │    6    │   'stsol-call'    │ 'Solana' │ 'psyoptions' │ 'STSOL'  │  'call'  │ 116129.10480581936 │ 10.633654474916776 │ 10.391678455326227 │  [ 'SRM' ]   │
    │    7    │     'sol-put'     │ 'Solana' │ 'psyoptions' │  'USDC'  │  'put'   │ 51310.87430268799  │ 21.215862299297882 │                    │              │
    │    8    │    'dust-call'    │ 'Solana' │ 'psyoptions' │  'DUST'  │  'call'  │ 31821.84306923712  │ 33.82303597277274  │                    │              │
    │    9    │    'ftt-call'     │ 'Solana' │ 'psyoptions' │  'FTT'   │  'call'  │  25217.9354690706  │         25         │                    │              │
    └─────────┴───────────────────┴──────────┴──────────────┴──────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴──────────────┘

**Pull request merged**
