### PR TITLE
feat: Add across yield adaptor

### PR DESCRIPTION
**Pull request by nicholaspai**
User can LP funds here to earn a base APY proportional to volume on Across, a cross-chain bridge optimistically secured by UMA. 

- [Across](https://across.to/pool)
- [Docs with smart contract audit link](https://docs.across.to/v2/how-does-across-work/overview)

Signed-off-by: nicholaspai <npai.nyc@gmail.com>

### CODE REVIEW

**Comment by nicholaspai** [comment]
I'm not sure why but when I ran `npm i` I produced a `package-lock.json` diff, is this expected? Happy to remove but I did run `npm i ` from a fresh fork and clone, so maybe the diff is valid

**Comment by llamatester** [comment]
The across adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       23 passed, 23 total
    Snapshots:   0 total
    Time:        0.52 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────┬────────────────────┬─────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │ symbol │       tvlUsd       │       apyBase       │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────┼────────────────────┼─────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' │ 'Ethereum' │ 'across' │ 'USDC' │ 9109713.684363235  │ 0.09265070929903849 │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    1    │ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' │ 'Ethereum' │ 'across' │ 'WETH' │ 5046057.160077452  │ 0.0882186777222444  │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    │    2    │ '0x6b175474e89094c44da98b954eedeac495271d0f' │ 'Ethereum' │ 'across' │ 'DAI'  │ 343080.63702382136 │ 0.05893769411586792 │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │
    │    3    │ '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599' │ 'Ethereum' │ 'across' │ 'WBTC' │  245623.23354096   │ 0.08439165087506711 │ [ '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────┴────────────────────┴─────────────────────┴──────────────────────────────────────────────────┘

**Comment by glebskr** [comment]
Hi, thx for your pr.
1) Please remove package.lock. (if u want to install dependencies without rewriting lock file just use `npm ci`)
2) Apy should be percentage value

**Comment by nicholaspai** [comment]
> Hi, thx for your pr.
> 
> 1. Please remove package.lock. (if u want to install dependencies without rewriting lock file just use `npm ci`)
> 2. Apy should be percentage value

Thanks for the quick response @glebskr ! Resolved your comments

**Comment by llamatester** [comment]
The across adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       23 passed, 23 total
    Snapshots:   0 total
    Time:        0.451 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬────────┬────────────────────┬───────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │ symbol │       tvlUsd       │      apyBase      │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼────────┼────────────────────┼───────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' │ 'Ethereum' │ 'across' │ 'USDC' │  11677543.286082   │ 8.019858601486513 │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    1    │ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' │ 'Ethereum' │ 'across' │ 'WETH' │ 4740472.120467434  │ 8.158236277531032 │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    │    2    │ '0x6b175474e89094c44da98b954eedeac495271d0f' │ 'Ethereum' │ 'across' │ 'DAI'  │ 289988.72096306324 │ 6.485895337900752 │ [ '0x6b175474e89094c44da98b954eedeac495271d0f' ] │
    │    3    │ '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599' │ 'Ethereum' │ 'across' │ 'WBTC' │  232778.87920408   │  8.4363035667822  │ [ '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴────────┴────────────────────┴───────────────────┴──────────────────────────────────────────────────┘

**Pull request merged**
