### PR TITLE
Adding Zircon To Yield Server

### PR DESCRIPTION
**Pull request by VittoriDavide**

### CODE REVIEW

**Comment by slasher125** [comment]
gm, ty for adding. we longer accept api adapters, pls rewrite to on chain instead

**Comment by VittoriDavide** [comment]
I don't see that indication in the readme of the yield server, (btw the example is an API Adapter)

**Comment by slasher125** [comment]
subgraph is ok yes! sry for the old example in there. gonna replace

**Comment by slasher125** [comment]
> I don't see that indication in the readme of the yield server, (btw the example is an API Adapter)

https://github.com/DefiLlama/yield-server#data-sources

**Comment by slasher125** [comment]
looking gud. one thing: pls move the prefix in the symbol such as `S-WMOVR` into the `poolMeta` field

**Comment by VittoriDavide** [comment]
The thing is that is important for us the S/F Tag, cause our AMM is single-sided liquidity. so to get those APY you'll actually provide only one liquidity to the pool. 
And if we move the symbol as you said we'd get twice the same symbol, so it'll be a bit confusing

**Comment by slasher125** [comment]
oh. so taking this pool as an example `'S-WMOVR ZRG-WMOVR' `:
that basically means supplying `WMOVR` as the stable token for the `ZRG-WMOVR` pair yes? And this is only single sided exposure without IL?

If so, then we'll do it the other way around: `poolMeta: Stable ZRG-WMOVR` (or something like that)
Make sure to keep remove the S or F in `S-WMOVR` otherwise we might misclassify to multi exposure & IL

**Comment by VittoriDavide** [comment]
Yes exactly that means supplying `WMOVR` as the stable, do you think it'll be fine `symbol: WMOVR (ZRG-WMOVR)` and `poolMeta: Stable`

**Comment by slasher125** [comment]
that would lead to -> `WMOVR (ZRG-WMOVR) (Stable)` on the UI. hence the recommendation above which would result in: `WMOVR (Stable ZRG-WMOVR)`. the content/structure inside poolMeta is completely up to

**Comment by llamatester** [comment]
Error while running zircon-gamma adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 10 passed, 11 total
    Snapshots:   0 total
    Time:        0.36 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────┬─────────────┬────────────────┬────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┐
    │ (index) │                          pool                          │    chain    │    project     │ symbol │       tvlUsd       │      apyBase       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │     poolMeta     │
    ├─────────┼────────────────────────────────────────────────────────┼─────────────┼────────────────┼────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┤
    │    0    │ '0xc50a53dc95e3875640f5f9c3c65643b984918c66-moonriver' │ 'moonriver' │ 'Zircon-Gamma' │ 'ETH'  │ 64989.330834795845 │ 11.348074092211364 │ 367.74180751209514 │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055' ] │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C' ] │ 'Stable ZRG-ETH' │
    └─────────┴────────────────────────────────────────────────────────┴─────────────┴────────────────┴────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┘
    }

**Comment by llamatester** [comment]
The zircon-gamma adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       130 passed, 130 total
    Snapshots:   0 total
    Time:        0.53 s
    Ran all test suites.
    
    Nb of pools: 18
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────┬─────────────┬────────────────┬─────────┬────────────────────┬──────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┐
    │ (index) │                          pool                          │    chain    │    project     │ symbol  │       tvlUsd       │       apyBase        │     apyReward      │                                          rewardTokens                                          │                                        underlyingTokens                                        │      poolMeta       │
    ├─────────┼────────────────────────────────────────────────────────┼─────────────┼────────────────┼─────────┼────────────────────┼──────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┤
    │    0    │ '0x770aa7074297e465e823bf2f45194e926af0d05d-moonriver' │ 'moonriver' │ 'zircon-gamma' │  'ZRG'  │ 162327.7546273439  │  50.77611851467978   │ 653.7036499974265  │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │  'Float ZRG-WMOVR'  │
    │    1    │ '0xbb57187c7883d25a64a08640905376f4cef6c1ef-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'WMOVR' │ 162248.64543682756 │  1.8179385485198363  │ 402.6963281502135  │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ 'Stable ZRG-WMOVR'  │
    │    2    │ '0x61dbb475dbb84be23a0d555fa269754eda88f5d1-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'USDC'  │ 125379.19018864374 │    8.093645883885    │ 251.64223258963688 │                        [ '0x4545E94974AdACb82FC56BCf136B07943e152055' ]                        │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D' ] │  'Stable ZRG-USDC'  │
    │    3    │ '0xc3722e72a64c4cab0308d72067bc07c7689b4f2f-moonriver' │ 'moonriver' │ 'zircon-gamma' │  'ZRG'  │ 125379.19018864374 │  17.114090911901005  │ 857.1888669559161  │                        [ '0x4545E94974AdACb82FC56BCf136B07943e152055' ]                        │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D' ] │  'Float ZRG-USDC'   │
    │    4    │ '0x72c46b87135ee3a1133522392bd8ee318cf3b9b2-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'xcKSM' │ 110888.45732495715 │  11.02856411360016   │ 622.7046086394796  │                        [ '0x4545E94974AdACb82FC56BCf136B07943e152055' ]                        │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080' ] │ 'Stable ZRG-xcKSM'  │
    │    5    │ '0x8170b304bddbc58ab6bf8b728a1aafd39abe2d89-moonriver' │ 'moonriver' │ 'zircon-gamma' │  'ZRG'  │ 110809.48372536304 │  8.106301751505999   │  592.689354182856  │                        [ '0x4545E94974AdACb82FC56BCf136B07943e152055' ]                        │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080' ] │  'Float ZRG-xcKSM'  │
    │    6    │ '0x17bd5a512ac2906c89c37b3b863d69e418fbdaaa-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'USDC'  │ 103039.52831741312 │  14.470813604757488  │ 137.88298125439616 │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x98878B06940aE243284CA214f92Bb71a2b032B8A', '0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D' ] │ 'Stable WMOVR-USDC' │
    │    7    │ '0x6e9685c324cdf126e5bf08f54573120a9c19e061-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'WMOVR' │ 103039.52831741312 │ 0.010691256328384784 │ 384.3918195787702  │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x98878B06940aE243284CA214f92Bb71a2b032B8A', '0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D' ] │ 'Float WMOVR-USDC'  │
    │    8    │ '0x45614680bd415d2b52b599210fe837b6df0945cf-moonriver' │ 'moonriver' │ 'zircon-gamma' │ 'WMOVR' │ 94636.70010998947  │ 0.08541268853342159  │ 402.72438464767293 │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │  'Float WMOVR-ETH'  │
    │    9    │ '0xb62d77084d5621053c4e04c1c64588f102738088-moonriver' │ 'moonriver' │ 'zircon-gamma' │  'ETH'  │ 94636.70010998947  │  2.0675960867751395  │ 326.28336268483577 │ [ '0x4545E94974AdACb82FC56BCf136B07943e152055', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ [ '0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C', '0x98878B06940aE243284CA214f92Bb71a2b032B8A' ] │ 'Stable WMOVR-ETH'  │
    └─────────┴────────────────────────────────────────────────────────┴─────────────┴────────────────┴─────────┴────────────────────┴──────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┘

**Comment by slasher125** [comment]
ty sir

**Pull request merged**
