### PR TITLE
Add Lyra vault APYs

### PR DESCRIPTION
**Pull request by paulvaden**

### CODE REVIEW

**Comment by paulvaden** [comment]
Links:
[Vaults page](https://app.lyra.finance/vaults)
[Historical performance](https://stats.lyra.finance/d/CvWXi2snk2/3-vault-view?orgId=1&viewPanel=60)

**Comment by llamatester** [comment]
The lyra adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       5 passed, 5 total
    Snapshots:   0 total
    Time:        0.319 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────────────────┬───────────────────┬───────────────────┐
    │ (index) │                     pool                     │   chain    │ project │       symbol       │        apy        │      tvlUsd       │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────────────────┼───────────────────┼───────────────────┤
    │    0    │ '0x5db73886c4730dbf3c562ebf8044e19e8c93843e' │ 'optimism' │ 'Lyra'  │ 'sUSD(sETH-Vault)' │ 48.58960534442309 │ 3082181.060181074 │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────────────────┴───────────────────┴───────────────────┘

**Comment by slasher125** [comment]
gm sir, ty for adding. test passed, though i have a few requests 🤓

- we recently started splitting out apy details, any chance we can be more specific by using `apyBase` and/or `apyReward` instead? seems like in lyra's case the yield is coming purely from trading fees no, if that is correct then best to use `apyBase` instead of `apy`?
- lets include the `underlyingToken` field too, in your case the sUSD address on optimism.

**Comment by paulvaden** [comment]
gm

Added in underlyingToken and switched to apyBase

ty!

**Comment by llamatester** [comment]
The lyra adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       5 passed, 5 total
    Snapshots:   0 total
    Time:        0.373 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────┬────────────────────┬───────────────────┬───────────────────┬──────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project │       symbol       │      apyBase      │      tvlUsd       │               underlyingToken                │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────┼────────────────────┼───────────────────┼───────────────────┼──────────────────────────────────────────────┤
    │    0    │ '0x5db73886c4730dbf3c562ebf8044e19e8c93843e' │ 'optimism' │ 'Lyra'  │ 'sUSD(sETH-Vault)' │ 48.58960534442309 │ 3082181.060181074 │ '0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9' │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────┴────────────────────┴───────────────────┴───────────────────┴──────────────────────────────────────────────┘

**Pull request merged**
