### PR TITLE
feat(adaptors): adds liquidswap farms

### PR DESCRIPTION
**Pull request by Parzival11l**
Hi! We made an adapter for Liquidswap farms (slug: liquidswap) and we will be glad to receive your review.
Thank you in advance 🙂

- Created auxiliary methods for basic calculations (utils.js)
- Created APR calculation
- Created TVL calculation
- Added calculation of the intermediate variable involved in APR calculations

### CODE REVIEW

**Comment by Parzival11l** [comment]
@slasher125, Hello there, I'm continuing from where Artyom left off in your conversation. Could you please explain what you meant when you said the results were too high? As I understand it, you were expecting to see, for example, a 77% result, but instead, you're seeing a much higher number. 

PR from Artyom: https://github.com/DefiLlama/yield-server/pull/1188

**Comment by llamatester** [comment]
The liquidswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.278 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬──────────────┬─────────────────┬────────────────────┬───────────────────┐
    │ (index) │                                             pool                                              │  chain  │   project    │     symbol      │       tvlUsd       │        apy        │
    ├─────────┼───────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼──────────────┼─────────────────┼────────────────────┼───────────────────┤
    │    0    │  '0x2835e9b12c3da7aad249f63f3bd3cc38b561e6c20f7881972686e2b8cc0023b7-APT-stAPT-UNCORRELATED'  │ 'Aptos' │ 'liquidswap' │  'APT-amStApt'  │ 30392.401513451798 │ 1429.808626102266 │
    │    1    │ '0x2835e9b12c3da7aad249f63f3bd3cc38b561e6c20f7881972686e2b8cc0023b7-zUSDC-stAPT-UNCORRELATED' │ 'Aptos' │ 'liquidswap' │ 'zUSDC-amStApt' │  4639.0925932143   │ 21838.82925648963 │
    └─────────┴───────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴──────────────┴─────────────────┴────────────────────┴───────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
gm, can u share a link to the url where i can see these pool values, i can't find them

**Comment by Parzival11l** [comment]
If I understood you correctly, https://farms.liquidswap.com/#/stakes
Or would you like to see something more specific?

**Comment by llamatester** [comment]
The liquidswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.276 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬──────────────┬─────────────────┬───────────────────┬────────────────────┐
    │ (index) │                                              pool                                               │  chain  │   project    │     symbol      │      tvlUsd       │        apy         │
    ├─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼──────────────┼─────────────────┼───────────────────┼────────────────────┤
    │    0    │  '0x2835e9b12c3da7aad249f63f3bd3cc38b561e6c20f7881972686e2b8cc0023b7-APT-amStApt-UNCORRELATED'  │ 'Aptos' │ 'liquidswap' │  'APT-amStApt'  │ 30210.6227682707  │ 1429.1243228911492 │
    │    1    │ '0x2835e9b12c3da7aad249f63f3bd3cc38b561e6c20f7881972686e2b8cc0023b7-zUSDC-amStApt-UNCORRELATED' │ 'Aptos' │ 'liquidswap' │ 'zUSDC-amStApt' │ 4626.721848649128 │ 21755.840189493625 │
    └─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴──────────────┴─────────────────┴───────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
> If I understood you correctly, https://farms.liquidswap.com/#/stakes Or would you like to see something more specific?

ty. the nbs here are completely different to the adapter output?

**Comment by Parzival11l** [comment]
@slasher125 Please explain what `nbs` is

**Comment by slasher125** [comment]
> @slasher125 Please explain what `nbs` is

i mean the numbers from the adapter output. `tvlUsd` of 30210.6227682707 and an apy of `1429.1243228911492`
when the values on the ui are totally different.
liquidswap

**Comment by llamatester** [comment]
The liquidswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.261 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬──────────────┬─────────────────┬───────────────────┬────────────────────┐
    │ (index) │                                              pool                                               │  chain  │   project    │     symbol      │      tvlUsd       │        apy         │
    ├─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼──────────────┼─────────────────┼───────────────────┼────────────────────┤
    │    0    │  '0xe2ce66f7dbfc0237fd7cf97dc18ded12129b04bfa5498ec991c8731274de2389-APT-amStApt-UNCORRELATED'  │ 'Aptos' │ 'liquidswap' │  'APT-amStApt'  │ 2318140.526407047 │ 51.640690616244804 │
    │    1    │ '0xe2ce66f7dbfc0237fd7cf97dc18ded12129b04bfa5498ec991c8731274de2389-zUSDC-amStApt-UNCORRELATED' │ 'Aptos' │ 'liquidswap' │ 'zUSDC-amStApt' │ 1463051.607752053 │ 65.31479977399367  │
    └─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴──────────────┴─────────────────┴───────────────────┴────────────────────┘

**Comment by llamatester** [comment]
The liquidswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.288 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬──────────────┬─────────────────┬───────────────────┬────────────────────┐
    │ (index) │                                              pool                                               │  chain  │   project    │     symbol      │      tvlUsd       │        apy         │
    ├─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼──────────────┼─────────────────┼───────────────────┼────────────────────┤
    │    0    │  '0xe5d1cbab351261717d7b44787596033c691e4dd80cc3dede9a8682a6ec52214f-APT-amStApt-UNCORRELATED'  │ 'Aptos' │ 'liquidswap' │  'APT-amStApt'  │ 2357281.528232655 │ 23.033209093340922 │
    │    1    │ '0x07abf560d050c0249a610f9b78513dd8253b85dd14b9e7bedb86f8c6bb96cf64-zUSDC-amStApt-UNCORRELATED' │ 'Aptos' │ 'liquidswap' │ 'zUSDC-amStApt' │ 2053657.038949782 │ 62.27896322714333  │
    └─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴──────────────┴─────────────────┴───────────────────┴────────────────────┘

**Comment by Parzival11l** [comment]
@slasher125 Is that all that is required of me? 
If so, could you please let me know when I can expect to have available for production?

**Pull request merged**
