### PR TITLE
add sensay

### PR DESCRIPTION
**Pull request by apostgit**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running sensay adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 28 passed, 29 total
    Snapshots:   0 total
    Time:        0.291 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬────────┬──────────┬─────┐
    │ (index) │                         pool                          │   chain    │ project  │ symbol │  tvlUsd  │ apy │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼────────┼──────────┼─────┤
    │    0    │ '0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 37109502 │ 500 │
    │    1    │ '0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 26547073 │ 500 │
    │    2    │ '0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 23875468 │ 180 │
    │    3    │ '0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 23587154 │ 120 │
    │    4    │ '0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 2336880  │ 250 │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴────────┴──────────┴─────┘
    }

**Comment by llamatester** [comment]
The sensay adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.261 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬─────────────────────────────────────────────────────────┬────────────┬──────────┬────────┬──────────┬─────┐
    │ (index) │                          pool                           │   chain    │ project  │ symbol │  tvlUsd  │ apy │
    ├─────────┼─────────────────────────────────────────────────────────┼────────────┼──────────┼────────┼──────────┼─────┤
    │    0    │ '0-0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 37109502 │ 500 │
    │    1    │ '4-0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 26547073 │ 500 │
    │    2    │ '2-0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 23875468 │ 180 │
    │    3    │ '1-0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 23587154 │ 120 │
    │    4    │ '3-0x382c70620e42c2EF2b303b97bad1d9439Bf48ef9-ethereum' │ 'Ethereum' │ 'sensay' │ 'SNSY' │ 2336880  │ 250 │
    └─────────┴─────────────────────────────────────────────────────────┴────────────┴──────────┴────────┴──────────┴─────┘

**Comment by slasher125** [comment]
gm
- refactor to on chain calls
- values for tvlUsd seem to be completely wrong, we need $ values, not token values
- apy values do not match ui
- add poolMeta which specifies the differences btw the different pools + mentions the lockup periods

**Comment by apostgit** [comment]
> gm
> 
> * refactor to on chain calls
> * values for tvlUsd seem to be completely wrong, we need $ values, not token values
> * apy values do not match ui
> * add poolMeta which specifies the differences btw the different pools + mentions the lockup periods

APY values are a bit different because on the site we round them. The rest I will update.

**Comment by slasher125** [comment]
@apostgit are u still on this sir? :)

**Comment by slasher125** [comment]
closing this, feel free to reopen with a fix

**Pull request closed without merging**
