### PR TITLE
vaultcraft: add vault yields

### PR DESCRIPTION
**Pull request by 0xruhum**

### CODE REVIEW

**Comment by 0xruhum** [comment]
runs fine without the RPC calls. Not sure what the issue is

**Comment by slasher125** [comment]
sample output doesn't look gud:
```
  {
    pool: '0x5d344226578DC100b2001DA251A4b154df58194f-ethereum',
    chain: 'Ethereum',
    project: 'vaultcraft',
    symbol: { output: 'pop-DAI' },
    tvlUsd: NaN,
    apyBase: 3.084377625925949,
    underlyingTokens: [ '0x6B175474E89094C44Da98b954EedeAC495271d0F' ]
  },
```

**Comment by 0xruhum** [comment]
had to add `.output` to the rpc calls.

They still fail locally and in the GitHub action. Any idea how to fix that?

**Comment by slasher125** [comment]
yeah its something with the default rpc that is breaking it. do this to test it locally:
in root, add a config.env and place and `ETHEREUM_RPC=` inside, pick an rpc that hopefully works. run it again,
make sure to run it inside src/adaptors (see readme). that should work (it did for me)

**Comment by 0xruhum** [comment]
Thanks, that worked. Ready for another review.

**Comment by slasher125** [comment]
sample output: 
```
  {
    pool: '0xe1489Af32c45c51f94Acdb3F36B7032A82F6f55D-ethereum',
    chain: 'Ethereum',
    project: 'vaultcraft',
    symbol: 'pop-WETH',
    tvlUsd: 117170.1356022752,
    apyBase: 13.036975124746395,
    underlyingTokens: [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ],
    apyReward: 1.40795810226683,
    rewardTokens: [ '0xaFa52E3860b4371ab9d8F08E801E9EA1027C0CA2' ]
  }
```
for reference:
Screenshot 2024-01-18 at 11 05 23

questions: 
- what is `pop` in the symbol?
- should apyReward = minBoost? (keep in mind we only display apr values on the lower bound and only rewards which can be claimed/sold immediately)

also, lets add poolMeta = 'sommelier'

**Comment by 0xruhum** [comment]
vaultcraft was named popcorn previously. So `pop` was used in both the vault's name & symbol.

apyReward is minBoost yeah

**Comment by slasher125** [comment]
pls remove `pop` the idea is that symbol = the underlying. the screenshot i shared shows different minBoost, which is not whats being reported by the adapter (see above)

**Comment by 0xruhum** [comment]
@slasher125 removed `pop` from the symbol. Also fixed an issue on the frontend. The min boost should be correct now.

**Pull request merged**
