### PR TITLE
Nabla Finance

### PR DESCRIPTION
**Pull request by yellowBirdy**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running nabla adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 45 passed, 46 total
    Snapshots:   0 total
    Time:        0.299 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────┬─────────┬──────────────────────────────────────────────────┬────────────────────┬──────────────────────┐
    │ (index) │                         pool                          │   chain    │ project │ symbol  │                 underlyingTokens                 │       tvlUsd       │       apyBase        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────┼─────────┼──────────────────────────────────────────────────┼────────────────────┼──────────────────────┤
    │    0    │ '0x272df896f4d0c97f65e787f861bb6e882776a155-arbitrum' │ 'Arbitrum' │ 'nabla' │ 'WETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 60347.23690788952  │ 0.12431148716615281  │
    │    1    │ '0x411ef79fe9df8ba82a09c7e93fde85af5732bf12-arbitrum' │ 'Arbitrum' │ 'nabla' │ 'WBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │   33309.18327978   │ 0.19111053644798615  │
    │    2    │ '0xe70292d6054b753214d555930e0f11cd7206efeb-arbitrum' │ 'Arbitrum' │ 'nabla' │  'ARB'  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 20322.837551826644 │ 0.01752720916174777  │
    │    3    │ '0x058a0875db2168af97bbf01043c3e8f751ccd9a8-arbitrum' │ 'Arbitrum' │ 'nabla' │ 'USDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │    15019.115284    │  0.082000335853041   │
    │    4    │   '0xa83a20f4dcab1a63a9118e9e432932c8beb39b85-base'   │   'Base'   │ 'nabla' │ 'CBBTC' │ [ '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf' ] │ 11240.814040149173 │ 0.056265955151348246 │
    │    5    │   '0x123456c6c27bb57013f4b943a0f032a0ab9c12eb-base'   │   'Base'   │ 'nabla' │ 'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │ 9848.048410463114  │ 0.06123517180138238  │
    │    6    │ '0xcc5544c63392952b6f94a695f8f9e153f4284a87-arbitrum' │ 'Arbitrum' │ 'nabla' │ 'USDT'  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │ 101.22849736999999 │          0           │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────┴─────────┴──────────────────────────────────────────────────┴────────────────────┴──────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by yellowBirdy** [comment]
There is one failing test which is strange, namely

```
Check project field is constant in all pools and if folder name and project field in pool objects matches the information in /protocols slug
```
protocols endpoint returns:
```
{"id":"5309","name":"Nabla Finance", ...
``` 
Test fails with following directory/project names
`nabla`
`Nabla Finance`
`Nabla`

**Comment by slasher125** [comment]
gm. 

its all in the test output...you need to use the project slug, not the project name. the slug is `nabla-finance`

**Comment by llamatester** [comment]
The nabla-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.278 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬─────────┬──────────────────────────────────────────────────┬────────────────────┬──────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol  │                 underlyingTokens                 │       tvlUsd       │       apyBase        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼─────────┼──────────────────────────────────────────────────┼────────────────────┼──────────────────────┤
    │    0    │ '0x272df896f4d0c97f65e787f861bb6e882776a155-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'WETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 64406.77663741875  │ 0.16097845262283395  │
    │    1    │ '0x411ef79fe9df8ba82a09c7e93fde85af5732bf12-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'WBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │   35022.11460696   │  0.2326042993082913  │
    │    2    │ '0xe70292d6054b753214d555930e0f11cd7206efeb-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │  'ARB'  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 21740.122912697545 │ 0.017078573848027245 │
    │    3    │ '0x058a0875db2168af97bbf01043c3e8f751ccd9a8-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'USDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │    15032.788968    │ 0.13524326248011875  │
    │    4    │   '0xa83a20f4dcab1a63a9118e9e432932c8beb39b85-base'   │   'Base'   │ 'nabla-finance' │ 'CBBTC' │ [ '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf' ] │ 11848.45353658413  │ 0.060525350747127504 │
    │    5    │   '0x123456c6c27bb57013f4b943a0f032a0ab9c12eb-base'   │   'Base'   │ 'nabla-finance' │ 'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │ 10503.552181138213 │ 0.06374961955936431  │
    │    6    │ '0xcc5544c63392952b6f94a695f8f9e153f4284a87-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'USDT'  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │ 101.05718760522001 │          0           │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴─────────┴──────────────────────────────────────────────────┴────────────────────┴──────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by yellowBirdy** [comment]
@slasher125 thank you, fixed

**Comment by llamatester** [comment]
The nabla-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.306 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬─────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol  │                 underlyingTokens                 │       tvlUsd       │      apyBase       │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼─────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x272df896f4d0c97f65e787f861bb6e882776a155-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'WETH'  │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 65316.78169532619  │ 16.919496782334733 │
    │    1    │ '0x411ef79fe9df8ba82a09c7e93fde85af5732bf12-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'WBTC'  │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │   35419.7882136    │ 23.299073227909762 │
    │    2    │ '0xe70292d6054b753214d555930e0f11cd7206efeb-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │  'ARB'  │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ 21670.090358042187 │ 2.3541832145752117 │
    │    3    │ '0x058a0875db2168af97bbf01043c3e8f751ccd9a8-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'USDC'  │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 15034.365583439072 │ 15.464584834234296 │
    │    4    │   '0xa83a20f4dcab1a63a9118e9e432932c8beb39b85-base'   │   'Base'   │ 'nabla-finance' │ 'CBBTC' │ [ '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf' ] │ 11934.357377475868 │ 5.514609139907156  │
    │    5    │   '0x123456c6c27bb57013f4b943a0f032a0ab9c12eb-base'   │   'Base'   │ 'nabla-finance' │ 'WETH'  │ [ '0x4200000000000000000000000000000000000006' ] │ 10650.242654351332 │ 5.8678936577151175 │
    │    6    │ '0xcc5544c63392952b6f94a695f8f9e153f4284a87-arbitrum' │ 'Arbitrum' │ 'nabla-finance' │ 'USDT'  │ [ '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9' ] │  101.10825692707   │         0          │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴─────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
can u pls also give a brief summary where the yield is coming from?

**Comment by yellowBirdy** [comment]
@slasher125 Fees, at the moment all yields come from swap fees. 
`Pool` interface didn't seemed to  have a meta/description/source fields.

**Pull request merged**
