### PR TITLE
Sommelier: Add Turbo stETH vault

### PR DESCRIPTION
**Pull request by philipjames44**

### CODE REVIEW

**Comment by philipjames44** [comment]
Errors in test seem like global RPC setup steps failing

**Comment by slasher125** [comment]
hi, params are hardcoded to 0?

**Comment by philipjames44** [comment]
> hi, params are hardcoded to 0?

The initial starting values are, same as all of the other vaults in this adaptor.

**Comment by philipjames44** [comment]
Just for additional context, if necessary, all of the final data is populated from on chain data via RPC in the index.js file https://github.com/DefiLlama/yield-server/blob/master/src/adaptors/sommelier/index.js

**Pull request merged**
