### PR TITLE
feat: add base apy for spice finance

### PR DESCRIPTION
**Pull request by 0xm00neth**

### CODE REVIEW

**Comment by llamatester** [comment]
The spice-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.471 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬────────┬───────────────────┬───────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol │      tvlUsd       │        apy        │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼────────┼───────────────────┼───────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'WETH' │ 869250.9099476069 │ 26.07785100210109 │
    └─────────┴────────────────────────┴────────────┴─────────────────┴────────┴───────────────────┴───────────────────┘

**Comment by slasher125** [comment]
hi, just to confirm. the reporting apy does not come from any incentives yes?
if so, all you need to do is to remove `apy` and add `apyBase` instead (inside here:
```
    {
      pool: `Spice-Prologue-Vault`,
      chain: 'Ethereum',
      project: 'spice-finance',
      symbol: 'WETH',
      tvlUsd,
      apy,
    },
```

**Comment by 0xm00neth** [comment]
@slasher125 I added `apyBase` in the code already

**Comment by slasher125** [comment]
gm. it can't be exported like that. apyBase is a field in the pools array. also, can u confirm that apy is not based on any token incentives?

**Comment by 0xm00neth** [comment]
@slasher125 how can I export `apyBase`?
yes, the apy is not based on any token incentives.

**Comment by llamatester** [comment]
Error while running spice-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 8 passed, 9 total
    Snapshots:   0 total
    Time:        0.564 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬────────┬───────────────────┬──────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol │      tvlUsd       │       apyBase        │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼────────┼───────────────────┼──────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'WETH' │ 917268.6301535971 │ [AsyncFunction: apr] │
    └─────────┴────────────────────────┴────────────┴─────────────────┴────────┴───────────────────┴──────────────────────┘
    }

**Comment by llamatester** [comment]
The spice-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.449 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬────────┬───────────────────┬────────────────────┬──────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol │      tvlUsd       │        apy         │       apyBase        │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼────────┼───────────────────┼────────────────────┼──────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'WETH' │ 917268.7341274023 │ 26.961485672462942 │ [AsyncFunction: apr] │
    └─────────┴────────────────────────┴────────────┴─────────────────┴────────┴───────────────────┴────────────────────┴──────────────────────┘

**Comment by slasher125** [comment]
seeer: the only thing that is required is to change the field from `apy` -> `apyBase`:
```
    {
      pool: `Spice-Prologue-Vault`,
      chain: 'Ethereum',
      project: 'spice-finance',
      symbol: 'WETH',
      tvlUsd,
      apyBase: "...apy value"
    },
```
anything else will break.

**Comment by 0xm00neth** [comment]
@slasher125 if we just change `apy` to `apyBase`, the tests fail

**Comment by llamatester** [comment]
The spice-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       9 passed, 9 total
    Snapshots:   0 total
    Time:        0.435 s
    Ran all test suites.
    
    Nb of pools: 1
     
    
    Sample pools:
    ┌─────────┬────────────────────────┬────────────┬─────────────────┬────────┬───────────────────┬────────────────────┬────────────────────┐
    │ (index) │          pool          │   chain    │     project     │ symbol │      tvlUsd       │        apy         │      apyBase       │
    ├─────────┼────────────────────────┼────────────┼─────────────────┼────────┼───────────────────┼────────────────────┼────────────────────┤
    │    0    │ 'Spice-Prologue-Vault' │ 'Ethereum' │ 'spice-finance' │ 'WETH' │ 917101.2129105476 │ 26.961485672462942 │ 26.961485672462942 │
    └─────────┴────────────────────────┴────────────┴─────────────────┴────────┴───────────────────┴────────────────────┴────────────────────┘

**Pull request merged**
