### PR TITLE
Create return-finance adapter

### PR DESCRIPTION
**Pull request by Joro-Popov**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running return-finance adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 28 passed, 29 total
    Snapshots:   0 total
    Time:        0.289 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────────┬─────────────┬─────────┬─────────┐
    │ (index) │                     pool                     │    chain    │     project      │   symbol    │ tvlUsd  │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────────┼─────────────┼─────────┼─────────┤
    │    0    │ '0x3B6385493a1d4603809dDbaE647200eF8baA53F5' │  'Polygon'  │ 'return-finance' │   'USDC'    │ 5.62196 │   12    │
    │    1    │ '0x3B6385493a1d4603809dDbaE647200eF8baA53F5' │ 'Avalanche' │ 'return-finance' │   'USDC'    │ 5.04398 │   8.1   │
    │    2    │ '0xFD360A096E4a4c3C424fc3aCd85da8010D0Db9a5' │ 'Ethereum'  │ 'return-finance' │ 'MIM-3CRV'  │    0    │  33.7   │
    │    3    │ '0x3B6385493a1d4603809dDbaE647200eF8baA53F5' │   'Base'    │ 'return-finance' │   'USDC'    │    0    │   7.9   │
    │    4    │ '0x201254227f9fE57296C257397Be6c617389a8cCb' │ 'Ethereum'  │ 'return-finance' │ 'DAI (DSR)' │    0    │   15    │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────────┴─────────────┴─────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by Joro-Popov** [comment]
> sir we have a tvl lower limit on our yields dashboard of $10k. anything below we don't display

Thank you for delineating this limitation. Our team is diligently addressing it to ensure that we fulfill all requirements for listing. I have a question regarding a specific issue: it has come to my attention that one unit test is currently failing due to a duplication of pool addresses across different chains. If we meet the 10k limit requirement, will our listing be unaffected by this failing test?

**Comment by slasher125** [comment]
u need to make sure that the values in `pool` are unique, if there are duplicates the tests will fail

**Comment by Joro-Popov** [comment]
> u need to make sure that the values in `pool` are unique, if there are duplicates the tests will fail

Yes, I understand that, but does that mean they won't be listed if the test is failing? We checked the addresses and they're the correct ones. Yes, there're duplicates, but they're on different chain

**Comment by slasher125** [comment]
you need to change the pool values then, u can just use the chain as a suffix and the test will pass

**Comment by Joro-Popov** [comment]
> you need to change the pool values then, u can just use the chain as a suffix and the test will pass

Oh, yes! Thank you for this. I will apply the changes and push the changes

**Comment by llamatester** [comment]
The return-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.263 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬────────────────────────────────────────────────────────┬─────────────┬──────────────────┬─────────────┬──────────┬─────────┐
    │ (index) │                          pool                          │    chain    │     project      │   symbol    │  tvlUsd  │ apyBase │
    ├─────────┼────────────────────────────────────────────────────────┼─────────────┼──────────────────┼─────────────┼──────────┼─────────┤
    │    0    │  '0x3B6385493a1d4603809dDbaE647200eF8baA53F5-polygon'  │  'Polygon'  │ 'return-finance' │   'USDC'    │ 5.622803 │   4.8   │
    │    1    │ '0x3B6385493a1d4603809dDbaE647200eF8baA53F5-avalanche' │ 'Avalanche' │ 'return-finance' │   'USDC'    │ 5.044307 │   4.7   │
    │    2    │ '0xFD360A096E4a4c3C424fc3aCd85da8010D0Db9a5-ethereum'  │ 'Ethereum'  │ 'return-finance' │ 'MIM-3CRV'  │    0     │  35.6   │
    │    3    │   '0x3B6385493a1d4603809dDbaE647200eF8baA53F5-base'    │   'Base'    │ 'return-finance' │   'USDC'    │    0     │   9.2   │
    │    4    │ '0x201254227f9fE57296C257397Be6c617389a8cCb-ethereum'  │ 'Ethereum'  │ 'return-finance' │ 'DAI (DSR)' │    0     │   15    │
    └─────────┴────────────────────────────────────────────────────────┴─────────────┴──────────────────┴─────────────┴──────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
- do you have a url to the actual deposit page?
- how is the apy generated?
- we don not accept centralised apis in the adapter, needs to be refactored to fetch data from the chain using our sdk or a subgraph (at minimum we want the tvl values from sdk)

**Comment by llamatester** [comment]
The moonwell adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       109 passed, 109 total
    Snapshots:   0 total
    Time:        0.293 s
    Ran all test suites.
    
    Nb of pools: 15
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬────────────┬──────────┬────────────────────┬──────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────┬──────┐
    │ (index) │                     pool                     │   chain    │  project   │  symbol  │       tvlUsd       │       apyBase        │     apyReward      │                 underlyingTokens                 │                                          rewardTokens                                          │   totalSupplyUsd   │   totalBorrowUsd   │   apyBaseBorrow    │ apyRewardBorrow │ ltv  │
    ├─────────┼──────────────────────────────────────────────┼────────────┼────────────┼──────────┼────────────────────┼──────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────┼──────┤
    │    0    │ '0x628ff693426583d9a7fb391e54366292f509d457' │   'Base'   │ 'moonwell' │  'ETH'   │ 22626889.863601625 │  1.0925760144526286  │ 7.1571469193561414 │ [ '0x4200000000000000000000000000000000000006' ] │                        [ '0xA88594D404727625A9437C3f886C7643872296AE' ]                        │ 69171616.49451478  │ 46544726.63091315  │ 2.1765251053378787 │        0        │ 0.81 │
    │    1    │ '0x3bf93770f2d4a794c3d9ebefbaebae2a8f09a5e5' │   'Base'   │ 'moonwell' │ 'cbETH'  │ 15155229.734333415 │ 0.25322101106153294  │  6.51426495069508  │ [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22' ] │                        [ '0xA88594D404727625A9437C3f886C7643872296AE' ]                        │ 20726740.42614089  │ 5571510.691807476  │ 1.3530870165569198 │        0        │ 0.78 │
    │    2    │ '0xd22da948c0ab3a27f5570b604f3adef5f68211c3' │ 'Moonbeam' │ 'moonwell' │ 'xcDOT'  │ 9896128.787091572  │  0.3112574110432975  │ 7.528199448894067  │ [ '0xffffffff1fcacbd218edc0eba20fc2308c778080' ] │ [ '0x511ab53f793683763e5a8829738301368a2411e3', '0x0000000000000000000000000000000000000000' ] │ 11149428.165756525 │ 1253299.3786649543 │ 3.754758163009031  │        0        │ 0.55 │
    │    3    │ '0x627fe393bc6edda28e99ae648fd6ff362514304b' │   'Base'   │ 'moonwell' │ 'wstETH' │ 9534020.141749807  │ 0.21779603376264056  │ 7.451849071617948  │ [ '0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452' ] │                        [ '0xA88594D404727625A9437C3f886C7643872296AE' ]                        │ 12079281.925199492 │ 2545261.783449686  │ 1.4858924576352406 │        0        │ 0.78 │
    │    4    │ '0xaaa20c5a584a9fecdfedd71e46da7858b774a9ce' │ 'Moonbeam' │ 'moonwell' │  'WBTC'  │ 8681599.659408571  │ 0.002013622196050946 │ 8.582499870066734  │ [ '0xe57ebd2d67b462e9926e04a8e33f01cd0d64346d' ] │ [ '0x511ab53f793683763e5a8829738301368a2411e3', '0x0000000000000000000000000000000000000000' ] │ 8693154.182596724  │ 11554.523188153502 │ 2.0404190339984307 │        0        │ 0.35 │
    │    5    │ '0x091608f4e4a15335145be0a279483c0f8e4c7955' │ 'Moonbeam' │ 'moonwell' │  'GLMR'  │   7364456.318047   │  0.9158108569309542  │ 8.068459826565086  │ [ '0xAcc15dC74880C9944775448304B263D191c6077F' ] │ [ '0x511ab53f793683763e5a8829738301368a2411e3', '0x0000000000000000000000000000000000000000' ] │ 9632284.775941078  │ 2267828.457894077  │ 5.687015951239016  │        0        │ 0.57 │
    │    6    │ '0xedc817a28e8b93b03976fbd4a3ddbc9f7d176c22' │   'Base'   │ 'moonwell' │  'USDC'  │ 3600930.4978370704 │  4.445475788343867   │ 7.322398790284173  │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │ [ '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', '0xA88594D404727625A9437C3f886C7643872296AE' ] │ 28567061.041706394 │ 24966130.543869324 │ 6.029781974594184  │    0.000126     │ 0.83 │
    │    7    │ '0xcb1dacd30638ae38f2b94ea64f066045b7d45f44' │   'Base'   │ 'moonwell' │  'rETH'  │  2102295.77856658  │  0.2163717019195044  │  9.99990840235559  │ [ '0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c' ] │                        [ '0xA88594D404727625A9437C3f886C7643872296AE' ]                        │ 2700414.309162242  │  598118.530595662  │ 1.4809953220328076 │        0        │ 0.78 │
    │    8    │ '0x1c55649f73cda2f72cef3dd6c5ca3d49efcf484c' │ 'Moonbeam' │ 'moonwell' │  'FRAX'  │ 1240172.8185653726 │ 0.010733703824739038 │ 19.103684659410103 │ [ '0x322e86852e492a7ee17f28a78c663da38fb33bfb' ] │ [ '0x511ab53f793683763e5a8829738301368a2411e3', '0x0000000000000000000000000000000000000000' ] │ 1301825.5548213576 │ 61652.73625598491  │ 0.2669841480950508 │        0        │ 0.56 │
    │    9    │ '0xb6c94b3a378537300387b57ab1cc0d2083f9aeac' │ 'Moonbeam' │ 'moonwell' │  'WETH'  │ 857723.7883885727  │  0.9905527429210359  │ 11.355335255078378 │ [ '0xab3f0245b83feb11d15aaffefd7ad465a59817ed' ] │ [ '0x511ab53f793683763e5a8829738301368a2411e3', '0x0000000000000000000000000000000000000000' ] │ 1095065.1972052744 │ 237341.4088167016  │ 6.250911019738337  │        0        │ 0.52 │
    └─────────┴──────────────────────────────────────────────┴────────────┴────────────┴──────────┴────────────────────┴──────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────────────────┴──────┘

**Comment by Joro-Popov** [comment]
> @Joro-Popov make sure to revert the changes on the moonwell adapter, otherwise we won't see the output from yours here
> 
> as for the rpc issue, switch to `const sdk = require('@defillama/sdk5')`

Thank you. This worked

**Pull request closed without merging**
