### PR TITLE
fix: Synapse: add avax ETH pool, rename pools to Stable and ETH

### PR DESCRIPTION
**Pull request by WardenJakx**

### CODE REVIEW

**Comment by llamatester** [comment]
The synapse adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       70 passed, 70 total
    Snapshots:   0 total
    Time:        0.394 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬─────────────┬──────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │    chain    │  symbol  │  project  │                                                                       underlyingTokens                                                                        │       tvlUsd       │        apy         │
    ├─────────┼───────────────────────────────────────────────────────┼─────────────┼──────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xd70a52248e546a3b260849386410c7170c7bd1e9-arbitrum' │ 'Arbitrum'  │  'ETH'   │ 'synapse' │                                [ '0x3ea9B0ab55F34Fb188824Ee288CeaEfC63cf908e', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                                 │ 10174353.702887183 │ 6.819027726578075  │
    │    1    │ '0xcfd72be67ee69a0dd7cf0f846fc0d98c33d60f16-arbitrum' │ 'Arbitrum'  │ 'Stable' │ 'synapse' │         [ '0x2913E812Cf0dcCA30FB28E6Cac3d2DCFF4497688', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8', '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ]          │ 9558894.836846976  │ 10.887116322155013 │
    │    2    │   '0xca87bf3ec55372d9540437d7a86a7750b42c02f4-avax'   │ 'Avalanche' │ 'Stable' │ 'synapse' │ [ '0xCFc37A6AB183dd4aED08C204D1c2773c0b1BDf46', '0xd586E7F844cEa2F87f50152665BCbc2C279D8d70', '0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664', ... 1 more item ] │ 8073492.708980366  │ 13.020387060370062 │
    │    3    │   '0x5df1db940dd8fee0e0eb0c8917cb50b4dfadf98c-avax'   │ 'Avalanche' │  'ETH'   │ 'synapse' │                                [ '0x19E1ae0eE35c0404f835521146206595d37981ae', '0x53f7c5869a859F0AeC3D334ee8B4Cf01E3492f21' ]                                 │ 6337181.809779981  │ 8.293907540870256  │
    │    4    │ '0x7479e1bc2f2473f9e78c89b4210eb6d55d33b645-polygon'  │  'Polygon'  │ 'Stable' │ 'synapse' │ [ '0xB6c473756050dE474286bED418B77Aeac39B02aF', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', ... 1 more item ] │  6095047.58364179  │ 12.935091796755607 │
    │    5    │  '0x2dc777ff99058a12844a33d9b1ae6c8ab4701f66-fantom'  │  'Fantom'   │ 'Stable' │ 'synapse' │         [ '0xED2a7edd7413021d440b09D654f3b87712abAB66', '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x049d68029688eAbF473097a2fC38ef61633A3C7A' ]          │ 4333414.583672394  │  18.1935050242034  │
    │    6    │ '0x4619a06ddd3b8f0f951354ec5e75c09cd1cd1aef-optimism' │ 'Optimism'  │  'ETH'   │ 'synapse' │                                [ '0x809DC529f07651bD43A172e8dB6f4a7a0d771036', '0x121ab82b49B2BC4c7901CA46B8277962b4350204' ]                                 │ 3858537.104907824  │ 6.810871396460964  │
    │    7    │ '0x2c6d91accc5aa38c84653f28a80aec69325bdd12-optimism' │ 'Optimism'  │ 'Stable' │ 'synapse' │                                [ '0x67C10C397dD0Ba417329543c1a40eb48AAa7cd00', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ]                                 │ 3591997.392073225  │ 10.24276912928504  │
    │    8    │  '0x464d121d3ca63ceefd390d76f19364d3bd024cd2-fantom'  │  'Fantom'   │ 'Stable' │ 'synapse' │ [ '0xED2a7edd7413021d440b09D654f3b87712abAB66', '0x82f0B8B456c1A451378467398982d4834b6829c1', '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', ... 1 more item ] │ 659942.7423393339  │         0          │
    │    9    │ '0xadeac0343c2ac62dfe5a5f51e896aefff5ab513e-arbitrum' │ 'Arbitrum'  │ 'Stable' │ 'synapse' │ [ '0x2913E812Cf0dcCA30FB28E6Cac3d2DCFF4497688', '0xFEa7a6a0B346362BF88A9e4A88416B77a57D6c2A', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8', ... 1 more item ] │ 630813.3073017533  │         0          │
    └─────────┴───────────────────────────────────────────────────────┴─────────────┴──────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
hi, we usually use the underlying tokens for symbols. so `Stable` is not good. we got a an attribute filter on our end which will `Stablecoins` -> this should filter to the USD pools only. 
tbh, ideally we'd change symbol to the underlyingTokens, so something like `ETH-nETH` and `DAI-USDC-USDT` for the Ethereum Stableswap Pool etc.

**Comment by WardenJakx** [comment]
@slasher125 Thank you for your feedback. I have implemented your suggestion so we should be good to go!

**Comment by llamatester** [comment]
The synapse adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       70 passed, 70 total
    Snapshots:   0 total
    Time:        0.485 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬─────────────┬────────────────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │    chain    │           symbol           │  project  │                                                                       underlyingTokens                                                                        │       tvlUsd       │        apy         │
    ├─────────┼───────────────────────────────────────────────────────┼─────────────┼────────────────────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xd70a52248e546a3b260849386410c7170c7bd1e9-arbitrum' │ 'Arbitrum'  │        'nETH-WETH'         │ 'synapse' │                                [ '0x3ea9B0ab55F34Fb188824Ee288CeaEfC63cf908e', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                                 │ 8740844.807633135  │ 7.937356345626123  │
    │    1    │ '0xcfd72be67ee69a0dd7cf0f846fc0d98c33d60f16-arbitrum' │ 'Arbitrum'  │      'nUSD-USDC-USDT'      │ 'synapse' │         [ '0x2913E812Cf0dcCA30FB28E6Cac3d2DCFF4497688', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8', '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9' ]          │ 8205560.788138412  │ 12.682716353821563 │
    │    2    │   '0xca87bf3ec55372d9540437d7a86a7750b42c02f4-avax'   │ 'Avalanche' │ 'nUSD-DAI.e-USDC.e-USDT.e' │ 'synapse' │ [ '0xCFc37A6AB183dd4aED08C204D1c2773c0b1BDf46', '0xd586E7F844cEa2F87f50152665BCbc2C279D8d70', '0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664', ... 1 more item ] │ 7106070.658526182  │ 14.79298546994777  │
    │    3    │ '0x7479e1bc2f2473f9e78c89b4210eb6d55d33b645-polygon'  │  'Polygon'  │    'nUSD-DAI-USDC-USDT'    │ 'synapse' │ [ '0xB6c473756050dE474286bED418B77Aeac39B02aF', '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', ... 1 more item ] │ 5459831.671817193  │ 14.44000561536721  │
    │    4    │   '0x5df1db940dd8fee0e0eb0c8917cb50b4dfadf98c-avax'   │ 'Avalanche' │       'nETH-avWETH'        │ 'synapse' │                                [ '0x19E1ae0eE35c0404f835521146206595d37981ae', '0x53f7c5869a859F0AeC3D334ee8B4Cf01E3492f21' ]                                 │ 5449181.647615501  │ 9.645485028563812  │
    │    5    │  '0x2dc777ff99058a12844a33d9b1ae6c8ab4701f66-fantom'  │  'Fantom'   │     'nUSD-USDC-fUSDT'      │ 'synapse' │         [ '0xED2a7edd7413021d440b09D654f3b87712abAB66', '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', '0x049d68029688eAbF473097a2fC38ef61633A3C7A' ]          │ 3808512.0693810503 │ 20.700997808000352 │
    │    6    │ '0x4619a06ddd3b8f0f951354ec5e75c09cd1cd1aef-optimism' │ 'Optimism'  │        'nETH-WETH'         │ 'synapse' │                                [ '0x809DC529f07651bD43A172e8dB6f4a7a0d771036', '0x121ab82b49B2BC4c7901CA46B8277962b4350204' ]                                 │ 3323081.2224857905 │ 7.908323101516479  │
    │    7    │ '0x2c6d91accc5aa38c84653f28a80aec69325bdd12-optimism' │ 'Optimism'  │        'nUSD-USDC'         │ 'synapse' │                                [ '0x67C10C397dD0Ba417329543c1a40eb48AAa7cd00', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ]                                 │ 3176098.982324922  │ 11.584021847161722 │
    │    8    │  '0x464d121d3ca63ceefd390d76f19364d3bd024cd2-fantom'  │  'Fantom'   │   'nUSD-MIM-USDC-fUSDT'    │ 'synapse' │ [ '0xED2a7edd7413021d440b09D654f3b87712abAB66', '0x82f0B8B456c1A451378467398982d4834b6829c1', '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', ... 1 more item ] │ 582168.9104544471  │         0          │
    │    9    │ '0xadeac0343c2ac62dfe5a5f51e896aefff5ab513e-arbitrum' │ 'Arbitrum'  │    'nUSD-MIM-USDC-USDT'    │ 'synapse' │ [ '0x2913E812Cf0dcCA30FB28E6Cac3d2DCFF4497688', '0xFEa7a6a0B346362BF88A9e4A88416B77a57D6c2A', '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8', ... 1 more item ] │ 556357.8123425039  │         0          │
    └─────────┴───────────────────────────────────────────────────────┴─────────────┴────────────────────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┘

**Pull request merged**
