### PR TITLE
feat: add davos protocol

### PR DESCRIPTION
**Pull request by dvsxyz**

### CODE REVIEW

**Comment by llamatester** [comment]
The davos-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.395 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────────────┬─────────┬───────────┬────────────────────┬───────────────────┬────────────────────┬───────────────────┬────────────────────┬──────┬────────────┐
    │ (index) │                     pool                     │     project      │ symbol  │   chain   │        apy         │      tvlUsd       │   apyBaseBorrow    │  totalSupplyUsd   │   totalBorrowUsd   │ ltv  │ mintedCoin │
    ├─────────┼──────────────────────────────────────────────┼──────────────────┼─────────┼───────────┼────────────────────┼───────────────────┼────────────────────┼───────────────────┼────────────────────┼──────┼────────────┤
    │    0    │ '0xa6aE8F29e0031340eA5dBE11c2DA4466cDe34464' │ 'davos-protocol' │ 'MATIC' │ 'polygon' │         0          │ 580321.3732717363 │ 1.9999999999966873 │ 580321.3732717363 │ 134679.09786005062 │ 0.66 │  'DAVOS'   │
    │    1    │ '0xE69a1876bdACfa7A7a4F6D531BE2FDE843D2165C' │ 'davos-protocol' │ 'DAVOS' │ 'polygon' │ 109.80701331859197 │ 30284.29218802203 │                    │                   │                    │      │            │
    └─────────┴──────────────────────────────────────────────┴──────────────────┴─────────┴───────────┴────────────────────┴───────────────────┴────────────────────┴───────────────────┴────────────────────┴──────┴────────────┘

**Comment by slasher125** [comment]
hi ty for adding.
- totalSupplyUsd for matic collateral is ~$300k  according to your UI, can u explain the delta ?
- the apy for davos is reporting as ~40% on the ui?

**Comment by dvsxyz** [comment]
Hi, I've re-run the test the APY is showing approximately at 40% which isn't the same as the test report being shown in here.

For the differences in the TVL, the reason is that our frontend chart is taking data from smart contract events which monitoring unstake events. During the unstake occurs it will take sometime before assets are being removed from the vault.

@slasher125

**Comment by llamatester** [comment]
The davos-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       14 passed, 14 total
    Snapshots:   0 total
    Time:        0.303 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────────────┬─────────┬───────────┬───────────────────┬───────────────────┬────────────────────┬───────────────────┬────────────────────┬──────┬────────────┐
    │ (index) │                     pool                     │     project      │ symbol  │   chain   │        apy        │      tvlUsd       │   apyBaseBorrow    │  totalSupplyUsd   │   totalBorrowUsd   │ ltv  │ mintedCoin │
    ├─────────┼──────────────────────────────────────────────┼──────────────────┼─────────┼───────────┼───────────────────┼───────────────────┼────────────────────┼───────────────────┼────────────────────┼──────┼────────────┤
    │    0    │ '0xa6aE8F29e0031340eA5dBE11c2DA4466cDe34464' │ 'davos-protocol' │ 'MATIC' │ 'polygon' │         0         │ 568768.6807850149 │ 1.9999999999966873 │ 568768.6807850149 │ 138935.23577237694 │ 0.66 │  'DAVOS'   │
    │    1    │ '0xE69a1876bdACfa7A7a4F6D531BE2FDE843D2165C' │ 'davos-protocol' │ 'DAVOS' │ 'polygon' │ 41.21188979892533 │ 31391.46338592627 │                    │                   │                    │      │            │
    └─────────┴──────────────────────────────────────────────┴──────────────────┴─────────┴───────────┴───────────────────┴───────────────────┴────────────────────┴───────────────────┴────────────────────┴──────┴────────────┘

**Pull request merged**
