### PR TITLE
Use data from completed day to calculate daily APY

### PR DESCRIPTION
**Pull request by sandbochs**
Previously we were using the last 48 hours of data to calculate the daily APY. The team would like to only use data from a fully completed day, aka using the yield from the previous day.

There is also a `backfill.js` script that utilizes the fn that implements this methodology. I can remove it once you are done with the data fix. @slasher125. Just run `node src/adapters/sommelier/backfill.js` to get an output of all the APYs of the Real Yield USD cellar since inception.

Here are the dates we'd like to correct:
```bash
2023-01-27T00:00:00.000Z 6.993695306389211
2023-01-28T00:00:00.000Z 6.811426985205848
2023-01-29T00:00:00.000Z 14.587111171508859
2023-01-30T00:00:00.000Z 5.748332288613453
2023-01-31T00:00:00.000Z 5.249104084084564
2023-02-01T00:00:00.000Z 9.714383171887867
```

### CODE REVIEW

**Comment by sandbochs** [comment]
<not ready for merge until I remove backfill.js>

**Comment by llamatester** [comment]
The sommelier adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.364 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────┬─────────────────┬────────────────────────────────────┬────────────────────┬─────────────────────┬───────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────┬───────────────────┐
    │ (index) │                         pool                          │   chain    │   project   │     symbol      │              poolMeta              │       tvlUsd       │       apyBase       │     apyReward     │                   rewardTokens                   │                                                               underlyingTokens                                                               │                             url                             │     apyBase7d     │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────┼─────────────────┼────────────────────────────────────┼────────────────────┼─────────────────────┼───────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────┼───────────────────┤
    │    0    │ '0x97e6e0a40a3d02f12d1cec30ebfbae04e37c119e-ethereum' │ 'ethereum' │ 'sommelier' │ 'USDC-USDT-DAI' │ 'RealYieldUSD - 3day Bonding Lock' │ 11646856.818866154 │  5.445711346122424  │ 18.74341732803883 │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x6B175474E89094C44Da98b954EedeAC495271d0F', '0xdAC17F958D2ee523a2206206994597C13D831ec7' ] │  'https://app.sommelier.finance/strategies/Real-Yield-USD'  │ 5.407431778980847 │
    │    1    │ '0x7bad5df5e11151dc5ee1a648800057c5c934c0d5-ethereum' │ 'ethereum' │ 'sommelier' │     'USDC'      │           'aave2-CLR-S'            │  378080.240684146  │ 3.6644098485506356  │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                                               [ '0xdAC17F958D2ee523a2206206994597C13D831ec7' ]                                               │   'https://app.sommelier.finance/strategies/AAVE/manage'    │                   │
    │    2    │ '0x6b7f87279982d919bbf85182ddeab179b366d8f2-ethereum' │ 'ethereum' │ 'sommelier' │    'ETH-BTC'    │           'ETHBTCTrend'            │ 134745.0333724594  │ -22.36229513524053  │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │  'https://app.sommelier.finance/strategies/ETH-BTC-Trend'   │                   │
    │    3    │ '0x6e2dac3b9e9adc0cbbae2d0b9fd81952a8d33872-ethereum' │ 'ethereum' │ 'sommelier' │    'ETH-BTC'    │            'ETHBTCMom'             │ 95989.74491872052  │ -30.084632807151117 │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ] │ 'https://app.sommelier.finance/strategies/ETH-BTC-Momentum' │                   │
    │    4    │ '0x6f069f711281618467dae7873541ecc082761b33-ethereum' │ 'ethereum' │ 'sommelier' │      'UNI'      │            'SteadyUNI'             │ 47145.64417930682  │       -3.1692       │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984' ]                        │    'https://app.sommelier.finance/strategies/Steady-UNI'    │                   │
    │    5    │ '0x05641a27c82799aaf22b436f20a3110410f29652-ethereum' │ 'ethereum' │ 'sommelier' │     'MATIC'     │           'SteadyMATIC'            │ 45161.60738573408  │ -3.1686133926097133 │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0' ]                        │   'https://app.sommelier.finance/strategies/Steady-MATIC'   │                   │
    │    6    │ '0x3f07a84ecdf494310d397d24c1c78b041d2fa622-ethereum' │ 'ethereum' │ 'sommelier' │      'ETH'      │            'SteadyETH'             │ 40366.31106918848  │ -10.23643826825841  │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ]                        │    'https://app.sommelier.finance/strategies/Steady-ETH'    │                   │
    │    7    │ '0x4986fd36b6b16f49b43282ee2e24c5cf90ed166d-ethereum' │ 'ethereum' │ 'sommelier' │      'BTC'      │            'SteadyBTC'             │ 31682.38765647487  │  -24.2471117703374  │         0         │ [ '0xa670d7237398238de01267472c6f13e5b8010fd1' ] │                        [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599' ]                        │    'https://app.sommelier.finance/strategies/Steady-BTC'    │                   │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────┴─────────────────┴────────────────────────────────────┴────────────────────┴─────────────────────┴───────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
@sandbochs to confirm, the pool which needs to be updated is `'0x97e6e0a40a3d02f12d1cec30ebfbae04e37c119e-ethereum'`?

**Comment by sandbochs** [comment]
@slasher125 that is the correct pool. The team would like to fix a few more dates as well, hope it is not too much.

```
2023-01-27T00:00:00.000Z 6.993695306389211
2023-01-28T00:00:00.000Z 6.811426985205848
2023-01-29T00:00:00.000Z 14.587111171508859
2023-01-30T00:00:00.000Z 5.748332288613453
2023-01-31T00:00:00.000Z 5.249104084084564
2023-02-01T00:00:00.000Z 9.714383171887867

2023-02-02T00:00:00.000Z 15.435608905326053
2023-02-03T00:00:00.000Z 0.26717028653846886
2023-02-04T00:00:00.000Z 10.094712504168267
```

TYVM

**Comment by sandbochs** [comment]
Also, do you know why we dropped off the stablecoin yield list even though our tvl is 11.5m?

**Comment by slasher125** [comment]
hey sir, we have another filter (no outliers) which is applied as default. hence why its not showing up on that yields/stablecoins page. if u'd filter filter your project on /yields and set enable the `No outliers` filter that specific pool won't show up. 
we define outliers if the geometric mean or standard deviation are > +/- 1.5 * IQR

**Comment by slasher125** [comment]
@sandbochs have updated the values in the db. should be live with next ui refresh

**Comment by sandbochs** [comment]
That is awesome @slasher125 appreciate the reply to my teammate on Discord as well!

**Pull request merged**
