### PR TITLE
Update Cellana pools

### PR DESCRIPTION
**Pull request by Centure2222**
i updated Cellana's pool.
Lp: https://app.cellana.finance/liquidity
votesPool : https://app.cellana.finance/vote

### CODE REVIEW

**Comment by llamatester** [comment]
The cellana-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       112 passed, 112 total
    Snapshots:   0 total
    Time:        0.274 s
    Ran all test suites.
    
    Nb of pools: 18
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────┬─────────┬───────────────────┬───────────────────┬────────────────────┬─────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────┐
    │ (index) │               pool                │  chain  │      project      │      symbol       │       tvlUsd       │ apyBase │     apyReward      │                               rewardTokens                               │
    ├─────────┼───────────────────────────────────┼─────────┼───────────────────┼───────────────────┼────────────────────┼─────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────┤
    │    0    │    'cellana-finance-AMAPT-APT'    │ 'Aptos' │ 'cellana-finance' │    'AMAPT-APT'    │ 2688545.0107626356 │    0    │ 21.34394825886704  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    1    │ 'cellana-finance-CELL(USDC-APT)'  │ 'Aptos' │ 'cellana-finance' │ 'CELL(USDC-APT)'  │ 1345087.7992255164 │    0    │ 81.48869052309742  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    2    │ 'cellana-finance-CELL(AMAPT-APT)' │ 'Aptos' │ 'cellana-finance' │ 'CELL(AMAPT-APT)' │ 859130.4079515102  │    0    │ 166.2945045985265  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    3    │ 'cellana-finance-CELL(USDC-USDT)' │ 'Aptos' │ 'cellana-finance' │ 'CELL(USDC-USDT)' │ 722938.3169484612  │    0    │ 98.64147971624077  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    4    │    'cellana-finance-STAPT-APT'    │ 'Aptos' │ 'cellana-finance' │    'STAPT-APT'    │  690187.546240126  │    0    │ 34.63596655101612  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    5    │    'cellana-finance-USDC-USDT'    │ 'Aptos' │ 'cellana-finance' │    'USDC-USDT'    │ 654592.2040027322  │    0    │ 61.556519126832534 │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    6    │ 'cellana-finance-CELL(CELL-APT)'  │ 'Aptos' │ 'cellana-finance' │ 'CELL(CELL-APT)'  │  618500.93529914   │    0    │ 302.6830390225296  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    7    │    'cellana-finance-CELL-APT'     │ 'Aptos' │ 'cellana-finance' │    'CELL-APT'     │ 593686.4952829266  │    0    │ 143.65718136611022 │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    8    │    'cellana-finance-USDC-APT'     │ 'Aptos' │ 'cellana-finance' │    'USDC-APT'     │ 559704.7005977108  │    0    │ 80.27211846262432  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    │    9    │   'cellana-finance-STAPT-USDC'    │ 'Aptos' │ 'cellana-finance' │   'STAPT-USDC'    │ 313968.8724769578  │    0    │ 76.16568857558188  │ [ '0x2ebb2ccac5e027a87fa0e2e5f656a3a4238d6a48d93ec9b610d570fc0aa0df12' ] │
    └─────────┴───────────────────────────────────┴─────────┴───────────────────┴───────────────────┴────────────────────┴─────────┴────────────────────┴──────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, what are the new pools u added? keep in mind we do not display any pools which require additional tokens (eg ve tokens)

**Comment by Centure2222** [comment]
> hi, what are the new pools u added? keep in mind we do not display any pools which require additional tokens (eg ve tokens)

i know it, eg: pool 'cellana-finance-CELL(USDC-APT)'  : user stakes Cell to receive transaction fees on pair USDC-APT and bonus reward. I named the pool like that to represent the difference in rewards received between pairs. thank sir

**Comment by Centure2222** [comment]
> just to confirm, you are saying you can stake cell (and they won't be locked) in addition to the LP token and you are going to receive aiddtional bonus rewards in the form of non! ve tokens? pls share a link to your ui
> 
> edit: anyways, we do not list pools which require extra tokens to be locked (here cell). so we aren't going to merge this pr.

ok sir, i will remove vcell stake pool from list soon, thank about that

**Pull request closed without merging**
