### PR TITLE
IndigoProtocol/ Add Yields for Indigo Stability Pools

### PR DESCRIPTION
**Pull request by adacapo21**
- create appropriate functionality to get APY for each Stability Pool
- fetch Prices/APR/AssetAnalytics/ADA price to USD
- calculate TVL
- return APY

### CODE REVIEW

**Comment by llamatester** [comment]
The indigo adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       25 passed, 25 total
    Snapshots:   0 total
    Time:        0.283 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬────────┬───────────┬──────────┬────────┬─────────┬───────────┬───────────────────┬──────────────────┬────────────────────┐
    │ (index) │  pool  │   chain   │ project  │ symbol │ apyBase │ apyReward │   rewardTokens    │ underlyingTokens │       tvlUsd       │
    ├─────────┼────────┼───────────┼──────────┼────────┼─────────┼───────────┼───────────────────┼──────────────────┼────────────────────┤
    │    0    │ 'iUSD' │ 'Cardano' │ 'indigo' │ 'iUSD' │  17.2   │   20.8    │ [ 'ADA', 'INDY' ] │    [ 'iUSD' ]    │ 15165908.164463142 │
    │    1    │ 'iBTC' │ 'Cardano' │ 'indigo' │ 'iBTC' │  7.62   │   14.27   │ [ 'ADA', 'INDY' ] │    [ 'iBTC' ]    │  4255198.13002695  │
    │    2    │ 'iETH' │ 'Cardano' │ 'indigo' │ 'iETH' │  3.47   │   18.9    │ [ 'ADA', 'INDY' ] │    [ 'iETH' ]    │ 2748464.5721772388 │
    └─────────┴────────┴───────────┴──────────┴────────┴─────────┴───────────┴───────────────────┴──────────────────┴────────────────────┘

**Comment by slasher125** [comment]
gm, looks to me that apyBase here are the ADA rewards? if so then this needs to be added to the indy apyReward
the idea is: apyBase = from fees/real yield. apyReward: token incentives

**Comment by adacapo21** [comment]
> @adacapo21 gm, looks to me that apyBase here are the ADA rewards? if so then this needs to be added to the indy apyReward
> the idea is: apyBase = from fees/real yield. apyReward: token incentives

Ok will check that again to be sure about the results and will update it.

**Comment by llamatester** [comment]
The indigo adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       25 passed, 25 total
    Snapshots:   0 total
    Time:        0.287 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬────────┬───────────┬──────────┬────────┬─────────┬────────────────────┬───────────────────┬──────────────────┬───────────────────┐
    │ (index) │  pool  │   chain   │ project  │ symbol │ apyBase │     apyReward      │   rewardTokens    │ underlyingTokens │      tvlUsd       │
    ├─────────┼────────┼───────────┼──────────┼────────┼─────────┼────────────────────┼───────────────────┼──────────────────┼───────────────────┤
    │    0    │ 'iUSD' │ 'Cardano' │ 'indigo' │ 'iUSD' │  17.2   │         38         │ [ 'ADA', 'INDY' ] │    [ 'iUSD' ]    │ 49580219.60459863 │
    │    1    │ 'iBTC' │ 'Cardano' │ 'indigo' │ 'iBTC' │  7.62   │       21.89        │ [ 'ADA', 'INDY' ] │    [ 'iBTC' ]    │ 7549346.489169142 │
    │    2    │ 'iETH' │ 'Cardano' │ 'indigo' │ 'iETH' │  3.47   │ 22.369999999999997 │ [ 'ADA', 'INDY' ] │    [ 'iETH' ]    │ 5983289.196623774 │
    └─────────┴────────┴───────────┴──────────┴────────┴─────────┴────────────────────┴───────────────────┴──────────────────┴───────────────────┘

**Comment by slasher125** [comment]
don't forget to remove `apyBase` from the aadapter. in your case, all apy components are `apyReward`

**Comment by llamatester** [comment]
The indigo adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       25 passed, 25 total
    Snapshots:   0 total
    Time:        0.299 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬────────┬───────────┬──────────┬────────┬────────────────────┬───────────────────┬──────────────────┬────────────────────┐
    │ (index) │  pool  │   chain   │ project  │ symbol │     apyReward      │   rewardTokens    │ underlyingTokens │       tvlUsd       │
    ├─────────┼────────┼───────────┼──────────┼────────┼────────────────────┼───────────────────┼──────────────────┼────────────────────┤
    │    0    │ 'iUSD' │ 'Cardano' │ 'indigo' │ 'iUSD' │         38         │ [ 'ADA', 'INDY' ] │    [ 'iUSD' ]    │ 49577043.618273266 │
    │    1    │ 'iBTC' │ 'Cardano' │ 'indigo' │ 'iBTC' │       21.89        │ [ 'ADA', 'INDY' ] │    [ 'iBTC' ]    │ 7552902.864762419  │
    │    2    │ 'iETH' │ 'Cardano' │ 'indigo' │ 'iETH' │ 22.369999999999997 │ [ 'ADA', 'INDY' ] │    [ 'iETH' ]    │ 5976725.693775349  │
    └─────────┴────────┴───────────┴──────────┴────────┴────────────────────┴───────────────────┴──────────────────┴────────────────────┘

**Pull request merged**
