### PR TITLE
Feat: yield for teahouse managed

### PR DESCRIPTION
**Pull request by daiwanwei**
- Get TVL from the on-chain data.
- Get APY from the centralized API (which combines APY from many protocols).

### CODE REVIEW

**Comment by llamatester** [comment]
The teahouse-managed adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.345 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬──────────┬───────────┬──────────────────────────────────────────────────┬──────────────┬──────────┐
    │ (index) │                         pool                          │   chain    │                   symbol                    │                                         url                                          │      project       │       tvlUsd       │ apyBase  │ apyReward │                 underlyingTokens                 │ rewardTokens │ poolMeta │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼──────────┼───────────┼──────────────────────────────────────────────────┼──────────────┼──────────┤
    │    0    │ '0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677-ethereum' │ 'ethereum' │            'Teahouse ETH Vault'             │ 'https://vault.teahouse.finance/ethereum/0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677' │ 'teahouse-managed' │ 1659742.8420419404 │  3.1116  │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │    ''    │
    │    1    │ '0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b-arbitrum' │ 'arbitrum' │          'Beta+ Momentum Strategy'          │ 'https://vault.teahouse.finance/arbitrum/0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b' │ 'teahouse-managed' │  242935.56518231   │ -6.8648  │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │      []      │    ''    │
    │    2    │ '0xb54E2764bEF6994245527f75Eb8f180c484C404d-ethereum' │ 'ethereum' │       'Stablecoin Portfolio Strategy'       │ 'https://vault.teahouse.finance/ethereum/0xb54E2764bEF6994245527f75Eb8f180c484C404d' │ 'teahouse-managed' │   142249.972936    │   4.32   │     0     │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      []      │    ''    │
    │    3    │ '0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d-ethereum' │ 'ethereum' │          'ETH Amplifier Strategy'           │ 'https://vault.teahouse.finance/ethereum/0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d' │ 'teahouse-managed' │ 87328.86555803622  │ -79.4346 │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │    ''    │
    │    4    │ '0x478aFa95F40bf5504cff32796c20bfD0B4e38330-ethereum' │ 'ethereum' │ 'Pseudo Market-Neutral Liquidity Provision' │ 'https://vault.teahouse.finance/ethereum/0x478aFa95F40bf5504cff32796c20bfD0B4e38330' │ 'teahouse-managed' │    44438.636132    │  5.8667  │     0     │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      []      │    ''    │
    │    5    │ '0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af-optimism' │ 'optimism' │            'ETH Options Trading'            │ 'https://vault.teahouse.finance/optimism/0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af' │ 'teahouse-managed' │  35357.362128088   │ -31.9058 │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │    ''    │
    │    6    │ '0xee1E02609a480BDC9D9651C200D90222b6691f03-optimism' │ 'optimism' │      'Perpetual Protocol LP Strategy'       │ 'https://vault.teahouse.finance/optimism/0xee1E02609a480BDC9D9651C200D90222b6691f03' │ 'teahouse-managed' │   23226.46894568   │ 35.7058  │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │    ''    │
    │    7    │ '0x9ed9c1C0F1c68666668A7aeDec5feC95abc7F943-ethereum' │ 'ethereum' │     'Concentrated Liquidity Provision'      │ 'https://vault.teahouse.finance/ethereum/0x9ed9c1C0F1c68666668A7aeDec5feC95abc7F943' │ 'teahouse-managed' │    4672.978019     │  1.032   │     0     │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      []      │    ''    │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴──────────┴───────────┴──────────────────────────────────────────────────┴──────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding. symbol match the deposit tokens, eg eth, eth-wbtc etc

**Comment by llamatester** [comment]
The teahouse-managed adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.335 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬──────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬──────────┬───────────┬──────────────────────────────────────────────────┬──────────────┬──────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │  symbol  │                                         url                                          │      project       │       tvlUsd       │ apyBase  │ apyReward │                 underlyingTokens                 │ rewardTokens │             poolMeta             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼──────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼──────────┼───────────┼──────────────────────────────────────────────────┼──────────────┼──────────────────────────────────┤
    │    0    │ '0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677-ethereum' │ 'ethereum' │  'ETH'   │ 'https://vault.teahouse.finance/ethereum/0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677' │ 'teahouse-managed' │  1693939.17368607  │  3.0992  │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │       'Teahouse ETH Vault'       │
    │    1    │ '0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b-arbitrum' │ 'arbitrum' │ 'USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b' │ 'teahouse-managed' │ 231914.82063591838 │ -7.4632  │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │      []      │    'Beta+ Momentum Strategy'     │
    │    2    │ '0xb54E2764bEF6994245527f75Eb8f180c484C404d-ethereum' │ 'ethereum' │  'USDC'  │ 'https://vault.teahouse.finance/ethereum/0xb54E2764bEF6994245527f75Eb8f180c484C404d' │ 'teahouse-managed' │   142249.972936    │   4.32   │     0     │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      []      │ 'Stablecoin Portfolio Strategy'  │
    │    3    │ '0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d-ethereum' │ 'ethereum' │  'ETH'   │ 'https://vault.teahouse.finance/ethereum/0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d' │ 'teahouse-managed' │ 134922.2790618254  │ -12.5311 │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │     'ETH Amplifier Strategy'     │
    │    4    │ '0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af-optimism' │ 'optimism' │ 'USDC.e' │ 'https://vault.teahouse.finance/optimism/0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af' │ 'teahouse-managed' │ 35304.59100019653  │ -31.9058 │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │      'ETH Options Trading'       │
    │    5    │ '0xee1E02609a480BDC9D9651C200D90222b6691f03-optimism' │ 'optimism' │  'USDC'  │ 'https://vault.teahouse.finance/optimism/0xee1E02609a480BDC9D9651C200D90222b6691f03' │ 'teahouse-managed' │ 13099.983842534099 │ 34.9744  │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │ 'Perpetual Protocol LP Strategy' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴──────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴──────────┴───────────┴──────────────────────────────────────────────────┴──────────────┴──────────────────────────────────┘

**Comment by llamatester** [comment]
The teahouse-managed adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       46 passed, 46 total
    Snapshots:   0 total
    Time:        0.381 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────┬──────────────────────────────────────────────────────────────────────────────────────┬────────────────────┬────────────────────┬──────────┬───────────┬──────────────────────────────────────────────────┬──────────────┬──────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │  symbol  │                                         url                                          │      project       │       tvlUsd       │ apyBase  │ apyReward │                 underlyingTokens                 │ rewardTokens │             poolMeta             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────┼──────────────────────────────────────────────────────────────────────────────────────┼────────────────────┼────────────────────┼──────────┼───────────┼──────────────────────────────────────────────────┼──────────────┼──────────────────────────────────┤
    │    0    │ '0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677-ethereum' │ 'ethereum' │  'ETH'   │ 'https://vault.teahouse.finance/ethereum/0xE1B3c128c0d0a9e41aB3fF8f0984e5d5bEf81677' │ 'teahouse-managed' │ 1906903.0275219064 │  3.1035  │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │       'Teahouse ETH Vault'       │
    │    1    │ '0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b-arbitrum' │ 'arbitrum' │ 'USDC.e' │ 'https://vault.teahouse.finance/arbitrum/0x9f4FfF022ebFF0cBFA3FAF702911d0F658a4ba9b' │ 'teahouse-managed' │ 237579.43013366038 │ -3.4817  │     0     │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │      []      │    'Beta+ Momentum Strategy'     │
    │    2    │ '0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d-ethereum' │ 'ethereum' │  'ETH'   │ 'https://vault.teahouse.finance/ethereum/0x4599E4F3Eea04BADD41501bF79183e67f6Cf569d' │ 'teahouse-managed' │ 158863.0162190309  │ 62.3209  │     0     │ [ '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2' ] │      []      │     'ETH Amplifier Strategy'     │
    │    3    │ '0xb54E2764bEF6994245527f75Eb8f180c484C404d-ethereum' │ 'ethereum' │  'USDC'  │ 'https://vault.teahouse.finance/ethereum/0xb54E2764bEF6994245527f75Eb8f180c484C404d' │ 'teahouse-managed' │  157357.487714427  │  4.1695  │     0     │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' ] │      []      │ 'Stablecoin Portfolio Strategy'  │
    │    4    │ '0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af-optimism' │ 'optimism' │ 'USDC.e' │ 'https://vault.teahouse.finance/optimism/0x9ae039F9de94542f6f1b3FBA60223E6aA4f411Af' │ 'teahouse-managed' │    33448.955549    │ -37.4885 │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │      'ETH Options Trading'       │
    │    5    │ '0xee1E02609a480BDC9D9651C200D90222b6691f03-optimism' │ 'optimism' │  'USDC'  │ 'https://vault.teahouse.finance/optimism/0xee1E02609a480BDC9D9651C200D90222b6691f03' │ 'teahouse-managed' │    12142.140198    │ 30.2766  │     0     │ [ '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │      []      │ 'Perpetual Protocol LP Strategy' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────┴──────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴────────────────────┴──────────┴───────────┴──────────────────────────────────────────────────┴──────────────┴──────────────────────────────────┘

**Pull request merged**
