### PR TITLE
Fixed an issue where the APRs were not being calculated properly with ZeroLend.

### PR DESCRIPTION
**Pull request by zerolend**
Hello team,

We fixed a bug where the APRs were scaled down by a factor of 10. Updated the code to reflect the fix. PFA a screenshot of the APRs as shown in our UI.

image 

Taken from: https://app.zerolend.xyz/markets/

Thanks team

### CODE REVIEW

**Comment by llamatester** [comment]
The zerolend adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       53 passed, 53 total
    Snapshots:   0 total
    Time:        0.476 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬──────────────┬────────────┬────────┬─────────────────────┬───────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┐
    │ (index) │                       pool                       │    chain     │  project   │ symbol │       tvlUsd        │        apyBase        │     apyReward      │                                          rewardTokens                                          │                 underlyingTokens                 │   totalSupplyUsd    │   totalBorrowUsd   │   apyBaseBorrow    │  apyRewardBorrow   │ ltv  │                                                                                            url                                                                                             │ borrowable │
    ├─────────┼──────────────────────────────────────────────────┼──────────────┼────────────┼────────┼─────────────────────┼───────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────┤
    │    0    │ '0x9002ecb8a06060e3b56669c6b8f18e1c3b119914-era' │ 'zkSync Era' │ 'zerolend' │ 'WETH' │  44540.87038529123  │  0.6265365269526476   │ 241.35855295955588 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91' ] │  56488.63830519367  │ 11947.767919902442 │ 3.2907486065900193 │  31.673865992125   │ 0.8  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x5aea5775959fbc2557cc8789bc1bf90a239d9a91&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    1    │ '0x7c65e6ec6feceb333092e6fe69672a3475c591fb-era' │ 'zkSync Era' │ 'zerolend' │ 'WBTC' │    17301.5531088    │ 0.0027476243038878005 │ 123.89983348568066 │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0xbbeb516fb02a01611cbbe0453fe3c580d7281011' ] │    17562.4449104    │ 260.8918016000025  │ 0.2311407106746072 │        null        │ 0.7  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xbbeb516fb02a01611cbbe0453fe3c580d7281011&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    2    │ '0x016341e6da8da66b33fd32189328c102f32da7cc-era' │ 'zkSync Era' │ 'zerolend' │ 'USDC' │     16954.65456     │   1.604628033833969   │ 293.8590025518538  │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4' ] │    46217.879929     │ 29263.225369000003 │ 2.8142056905186568 │ 12.931998958696193 │ 0.8  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    3    │ '0x9ca4806fa54984bf5da4e280b7aa8bb821d21505-era' │ 'zkSync Era' │ 'zerolend' │ 'USDT' │  5489.137809194337  │  1.9560154589107668   │ 376.0725608849439  │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x493257fd37edb34451f62edf8d2a0c418852ba4c' ] │ 18252.786323587643  │ 12763.648514393306 │ 3.1079471680772404 │ 29.64920254371232  │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x493257fd37edb34451f62edf8d2a0c418852ba4c&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    4    │ '0xb727f8e11bc417c90d4dcaf82eda06cf590533b5-era' │ 'zkSync Era' │ 'zerolend' │ 'BUSD' │  3367.067234757651  │  2.8515133495256366   │  556.582043966475  │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x2039bb4116b4efc145ec4f0e2ea75012d6c0f181' ] │ 16506.892558953412  │ 13139.825324195761 │ 3.980168442503154  │ 28.80038285616726  │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x2039bb4116b4efc145ec4f0e2ea75012d6c0f181&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    5    │ '0xd97ac0ce99329ee19b97d03e099eb42d7aa19ddb-era' │ 'zkSync Era' │ 'zerolend' │ 'LUSD' │ 1316.0590268435362  │  0.17552734187333713  │ 230.8131018558278  │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0x503234f203fc7eb888eec8513210612a43cf6115' ] │ 1639.5603064005397  │ 323.5012795570035  │ 0.9874977971096024 │        null        │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x503234f203fc7eb888eec8513210612a43cf6115&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    6    │ '0x54330d2333adbf715eb449aad38153378601cf67-era' │ 'zkSync Era' │ 'zerolend' │ 'PEPE' │ 0.00251856000000972 │           0           │         0          │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0xfd282f16a64c6d304ac05d1a58da15bed0467c71' ] │ 0.00251856000000972 │         0          │         0          │        null        │ 0.2  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xfd282f16a64c6d304ac05d1a58da15bed0467c71&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │   false    │
    └─────────┴──────────────────────────────────────────────────┴──────────────┴────────────┴────────┴─────────────────────┴───────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
ty. why is the price for zerolend fixed? is the token not tradeable yet?

**Comment by zerolend** [comment]
Yes ser . It's a pre-mine token at the early bird valuation. Once the token is live we will would stop this token and take the price from CG/CMC.

**Comment by slasher125** [comment]
hey, we do not list pre-minde rewards (see readme). closing this, but please reopen once the token is live

**Comment by slasher125** [comment]
crap, forgot that u still have the fix in there for the apr. can u pls update the pr by removing the apyReward so we can still get in the other change

**Comment by llamatester** [comment]
The zerolend adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       53 passed, 53 total
    Snapshots:   0 total
    Time:        0.33 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬──────────────┬────────────┬────────┬───────────────────────┬───────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬───────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┐
    │ (index) │                       pool                       │    chain     │  project   │ symbol │        tvlUsd         │        apyBase        │     apyReward      │                                          rewardTokens                                          │                 underlyingTokens                 │    totalSupplyUsd     │   totalBorrowUsd   │   apyBaseBorrow    │  apyRewardBorrow   │ ltv  │                                                                                            url                                                                                             │ borrowable │
    ├─────────┼──────────────────────────────────────────────────┼──────────────┼────────────┼────────┼───────────────────────┼───────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼───────────────────────┼────────────────────┼────────────────────┼────────────────────┼──────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────┤
    │    0    │ '0x9002ecb8a06060e3b56669c6b8f18e1c3b119914-era' │ 'zkSync Era' │ 'zerolend' │ 'WETH' │   57455.66703946082   │  0.5685952335791158   │ 189.49262047860438 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91' ] │   71953.92182323414   │ 14498.254783773315 │ 3.1348958417153936 │ 26.101900238609915 │ 0.8  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x5aea5775959fbc2557cc8789bc1bf90a239d9a91&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    1    │ '0x016341e6da8da66b33fd32189328c102f32da7cc-era' │ 'zkSync Era' │ 'zerolend' │ 'USDC' │      18806.47862      │   1.548157329083642   │ 273.05167645943015 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4' ] │     49741.762954      │ 30935.284333999996 │ 2.764256327376617  │ 12.233021552805878 │ 0.8  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    2    │ '0x7c65e6ec6feceb333092e6fe69672a3475c591fb-era' │ 'zkSync Era' │ 'zerolend' │ 'WBTC' │    17550.32927505     │ 0.0027476243038878005 │ 122.14353345158497 │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0xbbeb516fb02a01611cbbe0453fe3c580d7281011' ] │    17814.97504215     │ 264.6457670999989  │ 0.2311407106746072 │        null        │ 0.7  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xbbeb516fb02a01611cbbe0453fe3c580d7281011&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    3    │ '0x9ca4806fa54984bf5da4e280b7aa8bb821d21505-era' │ 'zkSync Era' │ 'zerolend' │ 'USDT' │   5816.018445072125   │   2.170469802432209   │ 318.52173683321263 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x493257fd37edb34451f62edf8d2a0c418852ba4c' ] │   21552.3870769044    │ 15736.368631832276 │ 3.245153579222823  │ 24.048241932671157 │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x493257fd37edb34451f62edf8d2a0c418852ba4c&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    4    │ '0xb727f8e11bc417c90d4dcaf82eda06cf590533b5-era' │ 'zkSync Era' │ 'zerolend' │ 'BUSD' │    5480.5702493669    │  2.6849230965423785   │ 381.53857403738425 │ [ '0x5aea5775959fbc2557cc8789bc1bf90a239d9a91', '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ] │ [ '0x2039bb4116b4efc145ec4f0e2ea75012d6c0f181' ] │  24081.867012211962   │ 18601.296762845064 │ 3.862154764536946  │ 20.344388072765682 │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x2039bb4116b4efc145ec4f0e2ea75012d6c0f181&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    5    │ '0xd97ac0ce99329ee19b97d03e099eb42d7aa19ddb-era' │ 'zkSync Era' │ 'zerolend' │ 'LUSD' │  1317.2579554672814   │  0.1756695139157778   │ 230.5815968365116  │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0x503234f203fc7eb888eec8513210612a43cf6115' ] │  1641.2064327419773   │ 323.94847727469596 │ 0.987897638410247  │        null        │ 0.75 │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x503234f203fc7eb888eec8513210612a43cf6115&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │    true    │
    │    6    │ '0x54330d2333adbf715eb449aad38153378601cf67-era' │ 'zkSync Era' │ 'zerolend' │ 'PEPE' │ 0.0025840960064754176 │           0           │         0          │                        [ '0x9793eac2fecef55248efa039bec78e82ac01cb2f' ]                        │ [ '0xfd282f16a64c6d304ac05d1a58da15bed0467c71' ] │ 0.0025840960064754176 │         0          │         0          │        null        │ 0.2  │ 'https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xfd282f16a64c6d304ac05d1a58da15bed0467c71&marketName=undefined&utm_source=defillama&utm_medium=listing&utm_campaign=external' │   false    │
    └─────────┴──────────────────────────────────────────────────┴──────────────┴────────────┴────────┴───────────────────────┴───────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴───────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by zerolend** [comment]
Okay, sure! This might take some time so I'll close the PR for now. We'll get back once our token is live or the price is not going to be hardcoded anymore.

**Pull request closed without merging**
