### PR TITLE
BLOC-1844

### PR DESCRIPTION
**Pull request by ajalalniya**

### CODE REVIEW

**Comment by llamatester** [comment]
The crowdswap adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       54 passed, 54 total
    Snapshots:   0 total
    Time:        0.429 s
    Ran all test suites.
    
    Nb of pools: 10
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────────┬─────────────┬───────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │    chain     │   project   │    symbol     │       tvlUsd       │        apy         │
    ├─────────┼──────────────────────────────────────────────┼──────────────┼─────────────┼───────────────┼────────────────────┼────────────────────┤
    │    0    │ '0x1901b3133b5797f4A5a9d0A07dd57f718596ca4d' │  'polygon'   │ 'crowdswap' │ 'MATIC/CROWD' │ 198591.14160089652 │ 84.00099237263335  │
    │    1    │ '0xDC311A12D70Ab2Fae9A34AD2d577edf95c747cDe' │  'polygon'   │ 'crowdswap' │ 'USDT/CROWD'  │ 183435.18141377528 │ 24.640716070903057 │
    │    2    │ '0x2a45D84824759c9171F15AE7F514f96ccA8F471c' │  'polygon'   │ 'crowdswap' │ 'USDC/CROWD'  │   174428.465878    │ 100.18924905925526 │
    │    3    │ '0xA319fC1D39F8f8834a29908B0a19ccB644cE1e30' │    'bsc'     │ 'crowdswap' │   'BNB/WSI'   │  91147.6951759203  │ 143.0392581482049  │
    │    4    │ '0xf360109D07785c6718fC31B5f1303bBEd757e857' │ 'avalanche'  │ 'crowdswap' │ 'AVAX/CROWD'  │ 62760.55779882557  │ 695.4830541438378  │
    │    5    │ '0x6Bfc439005f37C53148e84007392eE1D7a8D01CB' │ 'zkSync Era' │ 'crowdswap' │  'ETH/CROWD'  │ 45920.229710857115 │ 335.9970516893525  │
    │    6    │ '0x42c633DFD2D04fEFd64e717FFF1aEaBC1B735C46' │  'polygon'   │ 'crowdswap' │ 'MATIC/USDC'  │ 38783.86922030045  │ 114.0794672925336  │
    │    7    │ '0xA1157eb747Ebf867369989F5488E8d21b6BF371C' │  'arbitrum'  │ 'crowdswap' │  'ARB/CROWD'  │ 36636.49984608672  │ 89.43037208000919  │
    │    8    │ '0x422AF8a12373b1f9c0BD0540E50c474C63b50Bad' │  'arbitrum'  │ 'crowdswap' │   'ETH/ARB'   │ 30468.503275152438 │ 159.94558392082268 │
    │    9    │ '0xf35a69232Af34d5ad1B02e76A47e6c7D306bFA02' │  'polygon'   │ 'crowdswap' │  'USDC/EDAT'  │    23819.580628    │ 302.8244027855856  │
    └─────────┴──────────────────────────────────────────────┴──────────────┴─────────────┴───────────────┴────────────────────┴────────────────────┘

**Comment by slasher125** [comment]
hey sir, ty for adding.
- we no longer accept api adapters, so pls refactor and use on chain calls/subgraphs
- ideally split apy into apyBase and apyReward

**Comment by slasher125** [comment]
yes, that a example should be replace. i will update this. however, there is a section in the readme which says no more centralised apis. (for older adapters we didn't have that restriction)

as for examples: the repo is full of adapters with on chain calls, aave-v2 for example. 
u can use our price api for pulling price data

**Comment by ajalalniya** [comment]
Your price service doesn't support crowd token on other networks except polygon. So, I had to comment some of our farms.

**Comment by slasher125** [comment]
can u explain the duration and end date shown on the ui?

**Comment by ajalalniya** [comment]
> can u explain the duration and end date shown on the ui?

The duration and end date are related to the period of the farm. We have two types of long term and short term farms and extend short term farms by the end of the duration. For example, we extended ARB/ETH and USDC/MATIC  for 11 days yesterday.

**Comment by slasher125** [comment]
does this mean depositing requires locking of funds?

**Comment by ajalalniya** [comment]
> 

No, we don't lock the funds of users. They can withdraw their LP token and/or their rewards whenever they want. It just means we consider a certain amount of reward for a certain duration and after that we might extend the farm or just announce to finish it.

**Pull request merged**
