### PR TITLE
Clipper APY - Add Arbitrum

### PR DESCRIPTION
**Pull request by EdoAPP**
- Updates Clipper adaptor to use Comparable APY. For more info related to Comparable APY: https://docs.clipper.exchange/faq#on-the-clipper-data-page-what-is-comparable-apy-how-does-it-relate-to-impermanent-loss-il
- Adds Arbitrum to the list of pools.

Test cases ran successfully 
image

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running clipper adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 23 passed, 24 total
    Snapshots:   0 total
    Time:        0.665 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────┬──────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                     pool                     │   chain    │  project  │              symbol              │       tvlUsd       │        apy         │
    ├─────────┼──────────────────────────────────────────────┼────────────┼───────────┼──────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │ '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c' │ 'Ethereum' │ 'clipper' │     'WBTC-USDC-USDT-DAI-ETH'     │ 8029985.348134616  │ 19.830462790453826 │
    │    1    │ '0x5130f6cE257B8F9bF7fac0A0b519Bd588120ed40' │ 'Optimism' │ 'clipper' │ 'ETH-USDC-USDT-WBTC-DAI-LINK-OP' │ 778590.3000395044  │ 43.560327176090205 │
    │    2    │ '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c' │ 'Arbitrum' │ 'clipper' │     'USDC-ETH-USDT-DAI-WBTC'     │ 581382.7961046917  │ 17.326780067929796 │
    │    3    │ '0x6Bfce69d1Df30FD2B2C8e478EDEC9dAa643Ae3B8' │ 'Polygon'  │ 'clipper' │  'USDC-ETH-USDT-MATIC-DAI-WBTC'  │ 241557.17500655478 │ 18.032085686863617 │
    └─────────┴──────────────────────────────────────────────┴────────────┴───────────┴──────────────────────────────────┴────────────────────┴────────────────────┘
    }

**Comment by EdoAPP** [comment]
> Error while running clipper adapter:
> 
> Test Suites: 1 failed, 1 total Tests: 1 failed, 23 passed, 24 total Snapshots: 0 total Time: 0.665 s Ran all test suites.
> 
> ```
> Nb of pools: 4
>  
> 
> Sample pools:
> ┌─────────┬──────────────────────────────────────────────┬────────────┬───────────┬──────────────────────────────────┬────────────────────┬────────────────────┐
> │ (index) │                     pool                     │   chain    │  project  │              symbol              │       tvlUsd       │        apy         │
> ├─────────┼──────────────────────────────────────────────┼────────────┼───────────┼──────────────────────────────────┼────────────────────┼────────────────────┤
> │    0    │ '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c' │ 'Ethereum' │ 'clipper' │     'WBTC-USDC-USDT-DAI-ETH'     │ 8029985.348134616  │ 19.830462790453826 │
> │    1    │ '0x5130f6cE257B8F9bF7fac0A0b519Bd588120ed40' │ 'Optimism' │ 'clipper' │ 'ETH-USDC-USDT-WBTC-DAI-LINK-OP' │ 778590.3000395044  │ 43.560327176090205 │
> │    2    │ '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c' │ 'Arbitrum' │ 'clipper' │     'USDC-ETH-USDT-DAI-WBTC'     │ 581382.7961046917  │ 17.326780067929796 │
> │    3    │ '0x6Bfce69d1Df30FD2B2C8e478EDEC9dAa643Ae3B8' │ 'Polygon'  │ 'clipper' │  'USDC-ETH-USDT-MATIC-DAI-WBTC'  │ 241557.17500655478 │ 18.032085686863617 │
> └─────────┴──────────────────────────────────────────────┴────────────┴───────────┴──────────────────────────────────┴────────────────────┴────────────────────┘
> }
> ```

Both Ethereum and Arbitrum pool addresses happen to be the same
- https://etherscan.io/address/0xe7b0ce0526fbe3969035a145c9e9691d4d9d216c
- https://arbiscan.io/address/0xe7b0ce0526fbe3969035a145c9e9691d4d9d216c

**Comment by slasher125** [comment]
@EdoAPP henlo sir. if there are clashes for pool fields, then we need to add a suffix, I suggest using the chain string eg: `0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c-ethereum` etc

**Comment by llamatester** [comment]
The clipper adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       24 passed, 24 total
    Snapshots:   0 total
    Time:        0.408 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────┬──────────────────────────────────┬────────────────────┬────────────────────┐
    │ (index) │                         pool                          │   chain    │  project  │              symbol              │       tvlUsd       │        apy         │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────┼──────────────────────────────────┼────────────────────┼────────────────────┤
    │    0    │     '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c'      │ 'Ethereum' │ 'clipper' │     'WBTC-USDC-USDT-DAI-ETH'     │ 8018608.415230097  │ 16.25689232423771  │
    │    1    │     '0x5130f6cE257B8F9bF7fac0A0b519Bd588120ed40'      │ 'Optimism' │ 'clipper' │ 'ETH-USDC-USDT-WBTC-DAI-LINK-OP' │ 768420.7687487588  │ 38.62699433145194  │
    │    2    │ '0xE7b0CE0526fbE3969035a145C9e9691d4d9D216c-arbitrum' │ 'Arbitrum' │ 'clipper' │     'USDC-ETH-USDT-DAI-WBTC'     │ 580575.0344774817  │ 15.075660393088064 │
    │    3    │     '0x6Bfce69d1Df30FD2B2C8e478EDEC9dAa643Ae3B8'      │ 'Polygon'  │ 'clipper' │  'USDC-ETH-USDT-MATIC-DAI-WBTC'  │ 241498.90136214547 │ 16.19709690572296  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────┴──────────────────────────────────┴────────────────────┴────────────────────┘

**Comment by EdoAPP** [comment]
Thanks for your comment @slasher125. I've just pushed the update to include the suffix

**Comment by slasher125** [comment]
@EdoAPP great. one q: why is the "comparable apy" which is taking IL into account so much larger then what we currently have in master?

**Comment by EdoAPP** [comment]
@slasher125 Since Clipper's FMM design allows LPs to avoid impermanent loss, this metric includes it to make it comparable with the APYs reported by most other dexes (e.g Uniswap, Sushiswap). See https://docs.clipper.exchange/faq#on-the-clipper-data-page-what-is-comparable-apy-how-does-it-relate-to-impermanent-loss-il for more detailed information.

You can also look into this https://clipper.exchange/api/apy?chain=1 to see how much impermanent loss we're avoiding and including in this metric to make it comparable (see `avoidedImpermanentLossInUsd`).

You can look into this notion page for detailed information on how we calculate the comparable APY https://shipyardsoftware.notion.site/Clipper-df85e71ee6de41d7a381c8f1c2694c96 in the `Comparable Fees` section.

**Comment by slasher125** [comment]
so basically the avoided IL is added to the clipper apr and thats the comparable apy?

**Comment by EdoAPP** [comment]
You got it @slasher125 ! That's correct :). It's just a way to compare apples to apples.

**Comment by slasher125** [comment]
my only issue with this is that from a users perspective they now see a ~16% apr for `'WBTC-USDC-USDT-DAI-ETH'` but actually will earn only a fraction of that given that the majority of it is "just" avoided IL which they don't earn.

I understand where you are coming from given u have a mechanism for minimising IL and that u want to highlight that with higher apr. i just don't think its the right approach for our page.
also, everyone knows uniswap pools have IL...we also display 7day IL values to provide a more realistic figure for our users.

anyways, I'd suggest the following:
- lets add arbitrum
- keep the current apy values from the master branch
- we will add a tooltip on our UI indicating that these pools have no IL

**Comment by EdoAPP** [comment]
Thanks for your comment @slasher125. Sounds good to us. I've just pushed the changes

**Pull request merged**
