### PR TITLE
Umami: support for wbtc and usdc(wbtc) vault

### PR DESCRIPTION
**Pull request by Clonescody**
Add yield support for wBTC vault & the second USDC vault.

### CODE REVIEW

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.274 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────┬───────────┬─────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  apy  │ apyReward │     symbol      │                                          rewardTokens                                          │                 underlyingTokens                 │                   url                    │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────┼───────────┼─────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 3550292.6810906925 │  27.66  │ 27.66 │   236.2   │    'gmWETH'     │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0xcd8011aab161a75058eab24e0965bab0b918af29' │ 3358210.1154427202 │  15.17  │ 15.17 │ 222438.96 │    'gmWBTC'     │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/gm/gmwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 2058301.304293337  │  13.89  │       │           │    'mUMAMI'     │                        [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 1799124.9734217182 │  28.73  │ 28.73 │  543.59   │    'gmUSDC'     │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1492928.5540105205 │  14.89  │       │           │    'cmUMAMI'    │                        [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0x5f851f67d24419982ecd7b7765defd64fbb50a97' │ 1472166.3783930123 │  15.17  │ 15.17 │   8.96    │ 'gmUSDC (wBTC)' │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │   85222.72441816   │  74.26  │       │           │    'glpWBTC'    │                        [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ]                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 70541.56690540808  │  14.65  │       │           │    'glpUSDC'    │                        [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ]                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 66162.51873540047  │  18.01  │       │           │    'glpWETH'    │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 30004.216438765314 │  10.78  │       │           │    'glpUNI'     │                        [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ]                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────┴───────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by Clonescody** [comment]
No merge blz validating smth

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.382 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────┬───────────┬─────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  apy  │ apyReward │     symbol      │                                          rewardTokens                                          │                 underlyingTokens                 │                   url                    │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────┼───────────┼─────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 3542144.490872296  │  25.49  │ 25.49 │  238.23   │    'gmWETH'     │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0xcd8011aab161a75058eab24e0965bab0b918af29' │ 3373730.4803144503 │  15.34  │ 15.34 │  522.18   │    'gmWBTC'     │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/gm/gmwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 2083040.5026622473 │  13.72  │       │           │    'mUMAMI'     │                        [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 1795934.873530502  │  28.91  │ 28.91 │  547.93   │    'gmUSDC'     │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1510872.4068231469 │  14.7   │       │           │    'cmUMAMI'    │                        [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ]                        │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0x5f851f67d24419982ecd7b7765defd64fbb50a97' │ 1502467.7783214974 │  15.34  │ 15.34 │  1443.27  │ 'gmUSDC (wBTC)' │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831', '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │ 85610.99627660999  │  74.26  │       │           │    'glpWBTC'    │                        [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ]                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 70681.55529034599  │  14.65  │       │           │    'glpUSDC'    │                        [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ]                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 65212.41983862255  │  18.01  │       │           │    'glpWETH'    │                        [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ]                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 30478.50010172512  │  10.78  │       │           │    'glpUNI'     │                        [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ]                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────┴───────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
> No merge blz validating smth

sure, ping me when its ready for review

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.307 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────┬───────────┬─────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  apy  │ apyReward │     symbol      │                   rewardTokens                   │                 underlyingTokens                 │                   url                    │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────┼───────────┼─────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 3543237.1803219467 │  25.55  │ 25.55 │  238.16   │    'gmWETH'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0xcd8011aab161a75058eab24e0965bab0b918af29' │  3379007.10722158  │  15.28  │ 15.28 │  521.36   │    'gmWBTC'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/gm/gmwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 2073144.8233146835 │  13.76  │       │           │    'mUMAMI'     │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 1795387.5156720786 │  28.97  │ 28.97 │  548.09   │    'gmUSDC'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x5f851f67d24419982ecd7b7765defd64fbb50a97' │ 1502491.5363608634 │  15.28  │ 15.28 │  1440.71  │ 'gmUSDC (wBTC)' │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1497315.2129378908 │  14.74  │       │           │    'cmUMAMI'    │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │ 85746.23027576001  │  74.26  │       │           │    'glpWBTC'    │                        []                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │    70610.916144    │  14.65  │       │           │    'glpUSDC'    │                        []                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 65258.679867809136 │  18.01  │       │           │    'glpWETH'    │                        []                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 30431.087271070257 │  10.78  │       │           │    'glpUNI'     │                        []                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────┴───────────┴─────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The umami-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       81 passed, 81 total
    Snapshots:   0 total
    Time:        0.276 s
    Ran all test suites.
    
    Nb of pools: 11
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────────────┬─────────┬───────┬───────────┬─────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────┬────────────┬─────────────────┐
    │ (index) │                     pool                     │       tvlUsd       │ apyBase │  apy  │ apyReward │     symbol      │                   rewardTokens                   │                 underlyingTokens                 │                   url                    │   chain    │     project     │
    ├─────────┼──────────────────────────────────────────────┼────────────────────┼─────────┼───────┼───────────┼─────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────┼────────────┼─────────────────┤
    │    0    │ '0x4bca8d73561aaeee2d3a584b9f4665310de1dd69' │ 3476972.8592827916 │  30.11  │ 30.11 │   13.35   │    'gmWETH'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │ 'https://umami.finance/vaults/gm/gmweth' │ 'Arbitrum' │ 'umami-finance' │
    │    1    │ '0xcd8011aab161a75058eab24e0965bab0b918af29' │  3436429.77686997  │  15.87  │ 15.87 │   28.08   │    'gmWBTC'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │ 'https://umami.finance/vaults/gm/gmwbtc' │ 'Arbitrum' │ 'umami-finance' │
    │    2    │ '0x2adabd6e8ce3e82f52d9998a7f64a90d294a92a4' │ 2140324.8274696274 │  12.94  │       │           │    'mUMAMI'     │ [ '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    3    │ '0x959f3807f0aa7921e18c78b00b2819ba91e52fef' │ 1714935.4452693164 │  34.44  │ 34.44 │   31.09   │    'gmUSDC'     │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    4    │ '0x1922c36f3bc762ca300b4a46bb2102f84b1684ab' │ 1540292.4873644966 │  13.81  │       │           │    'cmUMAMI'    │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │ [ '0x1622bf67e6e5747b81866fe0b85178a93c7f86e3' ] │     'https://umami.finance/marinate'     │ 'Arbitrum' │ 'umami-finance' │
    │    5    │ '0x5f851f67d24419982ecd7b7765defd64fbb50a97' │ 1190345.8195429095 │  15.87  │ 15.87 │  109.56   │ 'gmUSDC (wBTC)' │ [ '0x912ce59144191c1204e64559fe8253a0e49e6548' ] │ [ '0xaf88d065e77c8cc2239327c5edb3a432268e5831' ] │ 'https://umami.finance/vaults/gm/gmusdc' │ 'Arbitrum' │ 'umami-finance' │
    │    6    │ '0x727ed4ef04bb2a96ec77e44c1a91dbb01b605e42' │ 70045.75104065459  │  19.47  │       │           │    'glpUSDC'    │                        []                        │ [ '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' ] │  'https://umami.finance/vaults/glpusdc'  │ 'Arbitrum' │ 'umami-finance' │
    │    7    │ '0xbb84d79159d6bbe1de148dc82640caa677e06126' │ 66492.00284886447  │  26.19  │       │           │    'glpWETH'    │                        []                        │ [ '0x82af49447d8a07e3bd95bd0d56f35241523fbab1' ] │  'https://umami.finance/vaults/glpweth'  │ 'Arbitrum' │ 'umami-finance' │
    │    8    │ '0x6a89faf99587a12e6bb0351f2fa9006c6cd12257' │ 65361.340518690005 │  75.04  │       │           │    'glpWBTC'    │                        []                        │ [ '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f' ] │  'https://umami.finance/vaults/glpwbtc'  │ 'Arbitrum' │ 'umami-finance' │
    │    9    │ '0x37c0705a65948ea5e0ae1add13552bcad7711a23' │ 30226.776023178256 │  12.36  │       │           │    'glpUNI'     │                        []                        │ [ '0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0' ] │  'https://umami.finance/vaults/glpuni'   │ 'Arbitrum' │ 'umami-finance' │
    └─────────┴──────────────────────────────────────────────┴────────────────────┴─────────┴───────┴───────────┴─────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────┴────────────┴─────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
sir, you can remove the `apy` field, we compute this server side

**Comment by slasher125** [comment]
gmweth
values from adapter don't seem to match ur ui

**Comment by Clonescody** [comment]
@slasher125 Hey ser, sorry for the delay had a lot to deal with.
I removed the ARB calculations part, there is no incentives right now anyways I'll come back to it when they're added back.
Tests are failing tho but I'm not sure why I asked in the discord

**Comment by Clonescody** [comment]
All fixed @slasher125 🫡 sorry for delay. 
I removed both the $UMAMI token yield part ([migrated to Bonsai](https://www.bonsaidao.xyz/)) and the GLP vaults as they have been deprecated in favor of the GM ones based on GMX v2.

Above error was on GLP vaults side so all good now

**Pull request merged**
