### PR TITLE
Add adapters for TrueFi pools

### PR DESCRIPTION
**Pull request by HubertNastaly**

### CODE REVIEW

**Review by JustynaBroniszewska — APPROVED** [review]

**Review by JustynaBroniszewska — APPROVED** [review]

**Comment by nezouse** [comment]
Hey @vrtnd, isn't it a problem with the repo? The error comes from `/yield-server/beforeTests.js` so it occurs even before any of our code runs.

**Comment by vrtnd** [comment]
beforeTests.js is a file where adapter imports and run.
Just use public rpc https://cloudflare-eth.com instead of .env
I'll check whats wrong with env rpcs later

**Comment by llamatester** [comment]
The truefi adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.397 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬──────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │ project  │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                   rewardTokens                   │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼──────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x6002b1dcb26e7b1aa797a17551c6f487923299d7' │ 'Ethereum' │ 'truefi' │ 'tfUSDT' │ 166313189.00692695 │ 8.729964921039826  │ 2.4433171978538315 │ [ '0x4c19596f5aaff459fa38b0f7ed92f11ae6543784' ] │ [ '0xdac17f958d2ee523a2206206994597c13d831ec7' ] │
    │    1    │ '0xa991356d261fbaf194463af6df8f0464f8f1c742' │ 'Ethereum' │ 'truefi' │ 'tfUSDC' │ 55814415.630354375 │ 9.230808300485743  │ 9.600396688514676  │ [ '0x4c19596f5aaff459fa38b0f7ed92f11ae6543784' ] │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' ] │
    │    2    │ '0x1ed460d149d48fa7d91703bf4890f97220c09437' │ 'Ethereum' │ 'truefi' │ 'tfBUSD' │ 30033267.629947636 │ 7.7133454325889685 │ 4.874681766081833  │ [ '0x4c19596f5aaff459fa38b0f7ed92f11ae6543784' ] │ [ '0x4fabb145d64652a948d72533023f6e7a623c7c53' ] │
    │    3    │ '0x97ce06c3e3d027715b2d6c22e67d5096000072e5' │ 'Ethereum' │ 'truefi' │ 'tfTUSD' │ 10970817.918406753 │ 8.651882586553441  │ 9.115644208341145  │ [ '0x4c19596f5aaff459fa38b0f7ed92f11ae6543784' ] │ [ '0x0000000000085d4780b73119b644ae5ecd22b376' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴──────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by vrtnd** [comment]
1) Please change symbols from tfUSDT -> USDT because deposit token is USDT/BUSD etc
2) formula for tvlUsd `tvlUsd = totalSupplyUsd - totalBorrowsUsd` ([USDT](https://etherscan.io/address/0x6002b1dcB26E7B1AA797A17551C6F487923299d7) $2.2m, [USDC](https://etherscan.io/address/0xA991356d261fbaF194463aF6DF8f0464F8f1c742) $320k etc)

**Pull request merged**
