### PR TITLE
List perp yield

### PR DESCRIPTION
**Pull request by opass**
Hi Defillama, please help review this PR. we want to list 4 pools on your yield tab.

### CODE REVIEW

**Comment by llamatester** [comment]
The perpetual-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.324 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────────┬───────────────┬────────────────────┬─────────────────────┬───────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │       project        │    symbol     │       tvlUsd       │       apyBase       │ apyReward │ rewardTokens │                                        underlyingTokens                                        │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────────┼───────────────┼────────────────────┼─────────────────────┼───────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x83d6675fe072928132c1b98ca3647de2fa9c8d84-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-ETH-USDC' │ 617141.6677052515  │ -1.1670639396171745 │   null    │     null     │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    1    │ '0xf2c886623309c93b56537c8c4d4321813ef78439-optimism' │ 'Optimism' │ 'perpetual-protocol' │   'HT-ETH'    │ 324972.2132245355  │  30.9319061534427   │   null    │     null     │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    2    │ '0x0a8c0b205549589feadfb954282fbd187e541d83-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-OP-USDC'  │ 99108.80331333831  │ -18.27387282695998  │   null    │     null     │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    3    │ '0xef9d827408c52c0f87278e1068ef652ad7274356-optimism' │ 'Optimism' │ 'perpetual-protocol' │    'HT-OP'    │ 55270.172866223074 │ -8.051170002477514  │   null    │     null     │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────────┴───────────────┴────────────────────┴─────────────────────┴───────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by opass** [comment]
Hi @slasher125, thanks for reviewing.

1. when checking the url it seems like there are 2 pools each on mainnet and optimism, instead of 4 on optimism
=> No, all of 4 pools are on optimism. (the underlying tokens are ETH/USDC and OP/USDC on Optimism)

2. if apyReward is null u can also emit it from the adapter (together with rewardTokens)
=> got it, I'll fix it.

3. can u confirm the negative apr is correct? 
=> 
Yes, when calculation interval is too small (said 1 day), the APY could be negative. The APY should be more stable when the interval is 7 days or 30 days. So I will add apyBase7d later.

4. u could add apyBase7d, apyBaseInception fields (especially as the 24h apy is negative for some of the pools)
=> 
Thanks, I didn't see these columns on the README document.
I'll add apyBase7d. Could you explain what's apyBaseInception field means (or is there any documentation)?

**Comment by llamatester** [comment]
The perpetual-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.385 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────────┬───────────────┬───────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │       project        │    symbol     │      tvlUsd       │      apyBase       │     apyBase7d      │                                        underlyingTokens                                        │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────────┼───────────────┼───────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x83d6675fe072928132c1b98ca3647de2fa9c8d84-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-ETH-USDC' │ 614791.778568968  │ 6.078342972987172  │ 34.54227485079693  │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    1    │ '0xf2c886623309c93b56537c8c4d4321813ef78439-optimism' │ 'Optimism' │ 'perpetual-protocol' │   'HT-ETH'    │ 341065.5555207401 │ -5.925470185827653 │ 23.419220188954437 │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    2    │ '0x0a8c0b205549589feadfb954282fbd187e541d83-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-OP-USDC'  │  99858.740418437  │ 172.36238317936105 │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    3    │ '0xef9d827408c52c0f87278e1068ef652ad7274356-optimism' │ 'Optimism' │ 'perpetual-protocol' │    'HT-OP'    │ 63918.2207079571  │ 31.72127323922225  │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────────┴───────────────┴───────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by opass** [comment]
Note: The NaN in apyBase7d on pools 2,3 is normal. Because we put it online several days ago. Should be fine after a week.

**Comment by llamatester** [comment]
The perpetual-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.333 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────────┬───────────────┬───────────────────┬─────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │       project        │    symbol     │      tvlUsd       │       apyBase       │     apyBase7d      │                                        underlyingTokens                                        │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────────┼───────────────┼───────────────────┼─────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x83d6675fe072928132c1b98ca3647de2fa9c8d84-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-ETH-USDC' │   588174.003043   │ 18.189025461803453  │ 7.302180779014988  │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    1    │ '0xf2c886623309c93b56537c8c4d4321813ef78439-optimism' │ 'Optimism' │ 'perpetual-protocol' │   'HT-ETH'    │ 359616.7117944795 │ -9.732211185600459  │ 1.1057199214194346 │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    2    │ '0x0a8c0b205549589feadfb954282fbd187e541d83-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-OP-USDC'  │   100272.846279   │ -51.839042557250096 │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    3    │ '0xef9d827408c52c0f87278e1068ef652ad7274356-optimism' │ 'Optimism' │ 'perpetual-protocol' │    'HT-OP'    │ 76186.88784608856 │ 120.70679931297428  │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────────┴───────────────┴───────────────────┴─────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Comment by slasher125** [comment]
>u could add apyBase7d, apyBaseInception fields (especially as the 24h apy is negative for some of the pools)
=>
Thanks, I didn't see these columns on the README document.
I'll add apyBase7d. Could you explain what's apyBaseInception field means (or is there any documentation)?

`apyBaseInception` = apy since pool beginning

**Comment by llamatester** [comment]
The perpetual-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.33 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────────────┬───────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
    │ (index) │                         pool                          │   chain    │       project        │    symbol     │       tvlUsd       │      apyBase       │     apyBase7d      │                                        underlyingTokens                                        │            url             │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────────────┼───────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
    │    0    │ '0x83d6675fe072928132c1b98ca3647de2fa9c8d84-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-ETH-USDC' │ 588026.3505736853  │ 5.348374327476457  │ 5.5809695334226195 │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    1    │ '0xf2c886623309c93b56537c8c4d4321813ef78439-optimism' │ 'Optimism' │ 'perpetual-protocol' │   'HT-ETH'    │ 360556.57144542155 │ 6.802663055533076  │ 1.3428691345722221 │ [ '0x4200000000000000000000000000000000000006', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    2    │ '0x0a8c0b205549589feadfb954282fbd187e541d83-optimism' │ 'Optimism' │ 'perpetual-protocol' │ 'HT-OP-USDC'  │ 100183.14341669195 │ -43.11801157530648 │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    │    3    │ '0xef9d827408c52c0f87278e1068ef652ad7274356-optimism' │ 'Optimism' │ 'perpetual-protocol' │    'HT-OP'    │ 85042.22673877636  │ 102.90002333775013 │        NaN         │ [ '0x4200000000000000000000000000000000000042', '0x7F5c764cBc14f9669B88837ca1490cCa17c31607' ] │ 'https://vaults.perp.com/' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────────────┴───────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┘

**Pull request merged**
