### PR TITLE
feat: added flashstake adapter

### PR DESCRIPTION
**Pull request by umarsa**
There is no way to retrieve the APR/APY on-chain or via subgraph

I have included some commented code which allows historical data to be obtained. I have included this as per conversations with slasher125 on discord.

You can swap out the export handler to use the historical version. This will return a ton of data and should not be used frequently

### CODE REVIEW

**Comment by llamatester** [comment]
The flashstake adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.462 s
    Ran all test suites.
    
    Nb of pools: 7
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────┬─────────┬────────────────────┬────────────────────┬──────────┐
    │ (index) │                         pool                          │   chain    │   project    │ symbol  │       tvlUsd       │        apy         │ poolMeta │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────┼─────────┼────────────────────┼────────────────────┼──────────┤
    │    0    │ 'ethereum:0xb8c60a5c9d73c0406ff279c65e31496a40f0dc5a' │ 'ethereum' │ 'flashstake' │ 'stETH' │ 402223.5424902729  │ 8.833081317728105  │ [Object] │
    │    1    │ 'ethereum:0x8373dd2efcaea8174136e9d5f729219e47ee94ca' │ 'ethereum' │ 'flashstake' │ 'WETH'  │ 161175.88769957435 │ 3.692905354384145  │ [Object] │
    │    2    │ 'ethereum:0x6e5ed1a5901e81f6bc008023d766454d831b6617' │ 'ethereum' │ 'flashstake' │ 'USDC'  │       82174        │ 5.5986141403985465 │ [Object] │
    │    3    │ 'optimism:0x28b413f9f09fba829a4c0b43783541373ee3f6c3' │ 'optimism' │ 'flashstake' │ 'sUSD'  │ 81478.31338959832  │ 4.604639422909215  │ [Object] │
    │    4    │ 'ethereum:0xa3f8115f38356a78898d0d3d50fae356a83ac13d' │ 'ethereum' │ 'flashstake' │  'CRV'  │  64140.4290567893  │ 2.3259447759710286 │ [Object] │
    │    5    │ 'ethereum:0x543134ec56ee444403461519c1ec8590c7475897' │ 'ethereum' │ 'flashstake' │  'SNX'  │ 12987.337320290213 │  4.3021226751963   │ [Object] │
    │    6    │ 'ethereum:0x15c32f81df9b00b97b68148b6bdeb72d57f24845' │ 'ethereum' │ 'flashstake' │ 'USDC'  │    11428.579985    │ 1.8746776793372717 │ [Object] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────┴─────────┴────────────────────┴────────────────────┴──────────┘

**Comment by slasher125** [comment]
what staking period is being used here for all these pools? `poolMeta` should be something like `7day lock` etc. 
pls comment the current poolMeta field and add the lock duration instead

**Comment by umarsa** [comment]
Did you want me to remove all the other attributes within the poolMeta object? If so, how would we compute historical data?

Regarding the staking period, the maximum duration is used for each strategy. The rates presented by the adapter are the worst case. You can currently stake down to the minute on the protocol and get a similar rate. Here are some examples of stake amounts, durations and the associated rates from app.flashstake.io:

Here are some examples:
Staking 10 stETH for 1 minute = 9.15%
Staking 10 stETH for 24 hours = 9.14%
Staking 10 stETH for 7 days = 9.11%
Staking 10 stETH for 180 days (approx 6 months) = 8.35%

The adapter returns ~8.83%

I can modify the adapter to show the maximum staking duration as the "lock" but it may not be accurate since you can get the same or very similar rates with lower lock durations

Please let me know how to move forward :)

**Comment by slasher125** [comment]
hey:
- re staking durations: lets use the minimum possible one and set that info to `poolMeta`
- re `poolMeta`: the adapter should be build for the current data, in your case (API_Latest). what u currently use for `poolMeta` is just for me so i can run insert cmd on the db for historical run (only required once)
so best to comment out the current poolMeta and replace it with the minimum staking period

clear? :)

**Comment by llamatester** [comment]
The flashstake adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       34 passed, 34 total
    Snapshots:   0 total
    Time:        0.345 s
    Ran all test suites.
    
    Nb of pools: 6
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬──────────────┬─────────┬────────────────────┬────────────────────┬─────────────┐
    │ (index) │                         pool                          │   chain    │   project    │ symbol  │       tvlUsd       │        apy         │  poolMeta   │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼──────────────┼─────────┼────────────────────┼────────────────────┼─────────────┤
    │    0    │ 'ethereum:0xb8c60a5c9d73c0406ff279c65e31496a40f0dc5a' │ 'ethereum' │ 'flashstake' │ 'stETH' │ 531995.2908236955  │ 14.52665500296504  │ '1min lock' │
    │    1    │ 'ethereum:0x8373dd2efcaea8174136e9d5f729219e47ee94ca' │ 'ethereum' │ 'flashstake' │ 'WETH'  │ 160103.26961914595 │ 3.6581753137428072 │ '1min lock' │
    │    2    │ 'ethereum:0x6e5ed1a5901e81f6bc008023d766454d831b6617' │ 'ethereum' │ 'flashstake' │ 'USDC'  │       82174        │ 5.628927329748499  │ '1min lock' │
    │    3    │ 'optimism:0x28b413f9f09fba829a4c0b43783541373ee3f6c3' │ 'optimism' │ 'flashstake' │ 'sUSD'  │ 81528.04683849415  │ 4.6397318597530415 │ '1min lock' │
    │    4    │ 'ethereum:0xa3f8115f38356a78898d0d3d50fae356a83ac13d' │ 'ethereum' │ 'flashstake' │  'CRV'  │ 58917.10509705338  │ 4.909557624105588  │ '1min lock' │
    │    5    │ 'ethereum:0x543134ec56ee444403461519c1ec8590c7475897' │ 'ethereum' │ 'flashstake' │  'SNX'  │ 13465.181501736282 │  6.81052476626089  │ '1min lock' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴──────────────┴─────────┴────────────────────┴────────────────────┴─────────────┘

**Comment by umarsa** [comment]
I have made the changes you requested:
1. We are now using the minimum staking duration.
2. poolMeta now returns "1 min lock"
3. Added some comments to help assist with additional data that may be needed for historical data

**Pull request merged**
