### PR TITLE
add tetu

### PR DESCRIPTION
**Pull request by dtmkeng**
url: https://api.tetu.io/api/v1/reader/vaultInfos?network=MATIC
```json
{
   "addr":"0x5b13cb93af007bd3493d0ef4c7a0e03bb108aee0",
   "name":"TETU_SWAP_WBTC_WETH",
   "symbol":"xTETU_SWAP_WBTC_WETH",
   "created":"1634941390",
   "active":true,
   "tvl":"46202189465",
   "tvlUsdc":"13115050999053212200693",
   "decimals":"18",
   "underlying":"0x6ee1488ea68d93b81fc255c166e21739c71588ce",
   "rewardTokens":[
      "0x225084d30cc297f3b177d9f93f5c3ab8fb6a1454"
   ],
   "rewardTokensBal":[
      "72103916313941325012753"
   ],
   "rewardTokensBalUsdc":[
      "778131286775671832951"
   ],
   "duration":"2419200",
   "rewardsApr":[
      "3531685573571400849"
   ],
   "ppfsApr":"185876891628885377",
   "ppfsAprMonth":"410952581682297036",
   "ppfsAprYear":"232998250428043979",
   "users":"6",
   "strategy":"0xd2bf2ed911ba0179000bd38e43bae425b6fb95e3",
   "strategyCreated":"1650184262",
   "platform":"12",
   "assets":[
      "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6",
      "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
   ],
   "strategyRewards":[
      "0x225084d30cc297f3b177d9f93f5c3ab8fb6a1454",
      "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6",
      "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
   ],
   "strategyOnPause":false,
   "earned":"185834075536446632987",
   "buyBackRatio":"1000",
   "ppfs":"1001684422121864338",
   "underlyingVaultsAddresses":[
      "0xd051605e07c2b526ed9406a555601aa4db8490d9",
      "0x6781e4a6e6082186633130f08246a7af3a7b8b40"
   ],
   "underlyingVaults":[
      
   ],
   "swapFeesAprDaily":"0",
   "swapFeesAprMonthly":"0.008723408851510562",
   "swapFeesAprYearly":"0",
   "subStrategies":[
      
   ],
   "network":"MATIC"
}
```

### CODE REVIEW

**Comment by dtmkeng** [comment]
```
Test Suites: 1 passed, 1 total
Tests:       466 passed, 466 total
Snapshots:   0 total
Time:        1.106 s
Ran all test suites.

Nb of pools: 77


Sample pools: [
  {
    pool: '0x0a4ed882fd66b2c4eec49fb16c56c9fe2b97b9e7',
    chain: 'Fantom',
    project: 'tetu',
    symbol: '',
    tvlUsd: 5375781.003732864,
    apyBase: 0,
    apyReward: 2.181190544675893,
    rewardTokens: [ '0x65c9d9d080714cda7b5d58989dc27f897f165179' ]
  },
]
```

**Comment by vrtnd** [comment]
Cloudflare protection 😢 
https://github.com/DefiLlama/yield-server/runs/7818740171?check_suite_focus=true

**Comment by dtmkeng** [comment]
Do I have to change the method?

**Comment by vrtnd** [comment]
I think the best way is to move adapter to rpc calls.
Because their api is protected by cloudflare and we can't fetch it on ci and probably AWS lambda wouldn't work too

**Comment by dtmkeng** [comment]
ok, i will try, thank you

**Comment by llamatester** [comment]
The tetu adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       466 passed, 466 total
    Snapshots:   0 total
    Time:        0.47 s
    Ran all test suites.
    
    Nb of pools: 77
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────┬─────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                         │   chain   │ project │ symbol  │       tvlUsd       │     apyReward      │                                          rewardTokens                                          │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────┼─────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0a4Ed882FD66B2C4eEC49FB16C56C9fe2b97b9E7-fantom'  │ 'Fantom'  │ 'tetu'  │ 'WFTM'  │ 5215243.169599148  │ 9.668857558568433  │                        [ '0x65c9d9d080714cDa7b5d58989Dc27f897F165179' ]                        │
    │    1    │ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454-polygon' │ 'Polygon' │ 'tetu'  │ 'TETU'  │ 1368775.3550593723 │ 42.464696782916576 │                        [ '0x255707B70BF90aa112006E1b07B9AeA6De021424' ]                        │
    │    2    │ '0xAcEE7Bd17E7B04F7e48b29c0C91aF67758394f0f-polygon' │ 'Polygon' │ 'tetu'  │ 'xTETU' │ 1005028.8476719017 │ 2.639133736000132  │                        [ '0xAcEE7Bd17E7B04F7e48b29c0C91aF67758394f0f' ]                        │
    │    3    │ '0xb4607D4B8EcFafd063b3A3563C02801c4C7366B2-polygon' │ 'Polygon' │ 'tetu'  │  'DAI'  │ 581131.6136302404  │ 4.201122883755293  │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    4    │ '0xeE3B4Ce32A6229ae15903CDa0A5Da92E739685f7-polygon' │ 'Polygon' │ 'tetu'  │ 'USDC'  │   554342.852184    │ 6.682671974401555  │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    5    │ '0x3dD66000a5CD4De6Bc74074dc7b776a6AFE78295-polygon' │ 'Polygon' │ 'tetu'  │ 'LINK'  │ 435831.80322995555 │         0          │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    6    │ '0x6c5e2E7dF0372f834B7F40D16Ff4333Cf49Af235-polygon' │ 'Polygon' │ 'tetu'  │ 'LINK'  │ 435806.6202548694  │         0          │                        [ '0x255707B70BF90aa112006E1b07B9AeA6De021424' ]                        │
    │    7    │ '0x4Cd44ced63d9a6FEF595f6AD3F7CED13fCEAc768-polygon' │ 'Polygon' │ 'tetu'  │  'QI'   │ 407520.2784903246  │ 14.529463891452776 │ [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454', '0x4Cd44ced63d9a6FEF595f6AD3F7CED13fCEAc768' ] │
    │    8    │ '0x65Be5bd1745A9871a5f042385dB869e78e9A1693-fantom'  │ 'Fantom'  │ 'tetu'  │ 'USDC'  │   214726.352944    │ 5.936389357620309  │                        [ '0x65c9d9d080714cDa7b5d58989Dc27f897F165179' ]                        │
    │    9    │ '0xE680e0317402ad3CB37D5ed9fc642702658Ef57F-polygon' │ 'Polygon' │ 'tetu'  │ 'USDT'  │ 194704.89202379333 │ 11.05561405495743  │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────┴─────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by dtmkeng** [comment]
@vrtnd  done! but i don't know how cal baseApy

**Comment by vrtnd** [comment]
As far as I understand ppfsApr is apr from compounding so your deposit will increase in the same token => it is apyBase.

**Comment by dtmkeng** [comment]
Should I change the field name?

**Comment by vrtnd** [comment]
Yes, just split rewardApy and change ppfsApy  apyBase.

**Comment by dtmkeng** [comment]
done!

**Comment by llamatester** [comment]
The tetu adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       466 passed, 466 total
    Snapshots:   0 total
    Time:        0.601 s
    Ran all test suites.
    
    Nb of pools: 77
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────────┬───────────┬─────────┬─────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                         │   chain   │ project │ symbol  │       tvlUsd       │      apyReward      │       apyBase        │                                          rewardTokens                                          │
    ├─────────┼──────────────────────────────────────────────────────┼───────────┼─────────┼─────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x0a4Ed882FD66B2C4eEC49FB16C56C9fe2b97b9E7-fantom'  │ 'Fantom'  │ 'tetu'  │ 'WFTM'  │  5242147.66802663  │ 0.04864625610797391 │  9.180560035576567   │                        [ '0x65c9d9d080714cDa7b5d58989Dc27f897F165179' ]                        │
    │    1    │ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454-polygon' │ 'Polygon' │ 'tetu'  │ 'TETU'  │ 1368859.3683561855 │          0          │  35.40658020968509   │                        [ '0x255707B70BF90aa112006E1b07B9AeA6De021424' ]                        │
    │    2    │ '0xAcEE7Bd17E7B04F7e48b29c0C91aF67758394f0f-polygon' │ 'Polygon' │ 'tetu'  │ 'xTETU' │ 1005090.7095821959 │ 2.6050024005097843  │          0           │                        [ '0xAcEE7Bd17E7B04F7e48b29c0C91aF67758394f0f' ]                        │
    │    3    │ '0xb4607D4B8EcFafd063b3A3563C02801c4C7366B2-polygon' │ 'Polygon' │ 'tetu'  │  'DAI'  │ 579951.1936991075  │  4.12404027115682   │ 0.000093913874244564 │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    4    │ '0xeE3B4Ce32A6229ae15903CDa0A5Da92E739685f7-polygon' │ 'Polygon' │ 'tetu'  │ 'USDC'  │    553678.89799    │  6.477585853022998  │          0           │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    5    │ '0x3dD66000a5CD4De6Bc74074dc7b776a6AFE78295-polygon' │ 'Polygon' │ 'tetu'  │ 'LINK'  │ 435321.2018734619  │          0          │          0           │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    │    6    │ '0x6c5e2E7dF0372f834B7F40D16Ff4333Cf49Af235-polygon' │ 'Polygon' │ 'tetu'  │ 'LINK'  │ 435296.04840164084 │          0          │          0           │                        [ '0x255707B70BF90aa112006E1b07B9AeA6De021424' ]                        │
    │    7    │ '0x4Cd44ced63d9a6FEF595f6AD3F7CED13fCEAc768-polygon' │ 'Polygon' │ 'tetu'  │  'QI'   │ 411514.28018231626 │ 13.387696511825427  │  0.1722801315776041  │ [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454', '0x4Cd44ced63d9a6FEF595f6AD3F7CED13fCEAc768' ] │
    │    8    │ '0x65Be5bd1745A9871a5f042385dB869e78e9A1693-fantom'  │ 'Fantom'  │ 'tetu'  │ 'USDC'  │   214726.352944    │ 0.10634735449468252 │       5.660209       │                        [ '0x65c9d9d080714cDa7b5d58989Dc27f897F165179' ]                        │
    │    9    │ '0xE680e0317402ad3CB37D5ed9fc642702658Ef57F-polygon' │ 'Polygon' │ 'tetu'  │ 'USDT'  │ 194473.89252830256 │ 10.500701813367705  │          0           │                        [ '0x225084D30cc297F3b177d9f93f5C3Ab8fb6a1454' ]                        │
    └─────────┴──────────────────────────────────────────────────────┴───────────┴─────────┴─────────┴────────────────────┴─────────────────────┴──────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Pull request merged**
