### PR TITLE
feat: seamless protocol ilms update

### PR DESCRIPTION
**Pull request by kitanovicd**
Implemented dynamic fetching of ILM from `ILMRegistry` smart contract. Now all ILMs should be shown into DefiLlama. I added ILMRegistry abi in file called _ilm-registry-abi.json_ in order to follow standard for previously named _loop-strategy-abi.json_. Inside `ilmApys` function we fetch addresses of all ILMs and we send list of ILMs into `getLpPrices` function. I tried to do as less changes as possible in order to make review easier. Logic for calculating base apy and 7 day apy didn't change.

Also inside function `calculateApy` there is incorrect formatting from `bigint` to `number`. It should be on 8 decimals and not on 18. This does not effect end result.

I noticed that esSEAM is not included in calculation on DefiLlama for both ILMs and Lending markets. I fixed that by taking SEAM price. 

We are getting reward token for ILMs from subgraph. Subgraph gives us opportunity to filter but not by asset. I noticed that id of reward element is in this format `reward_token_address:asset:incentives_controller`. I did filtering based on second address which corresponds to address of strategy LP tokens.

### CODE REVIEW

**Comment by llamatester** [comment]
The seamless-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       95 passed, 95 total
    Snapshots:   0 total
    Time:        0.276 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────┬────────┬─────────────────────┬─────────────────────────┬────────────────────┬──────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────┬────────────────────┬──────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬───────────────────┐
    │ (index) │                       pool                        │ chain  │       project       │         symbol          │       tvlUsd       │       apyBase        │     apyReward      │                                          rewardTokens                                          │                 underlyingTokens                 │   totalSupplyUsd   │   totalBorrowUsd   │    apyBaseBorrow    │  apyRewardBorrow   │ ltv  │                                                                     url                                                                     │ borrowable │     apyBase7d     │
    ├─────────┼───────────────────────────────────────────────────┼────────┼─────────────────────┼─────────────────────────┼────────────────────┼──────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────┼────────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────┼───────────────────┤
    │    0    │ '0x67368df7734aee0bc65a845ac6d73974626b7a34-base' │ 'Base' │ 'seamless-protocol' │         'SEAM'          │ 11783194.859198973 │          0           │ 0.0396329608039549 │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85' ] │ 11783194.859198973 │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85&marketName=proto_base_v3' │   false    │                   │
    │    1    │ '0x53e240c0f985175da046a62f26d490d1e259036e-base' │ 'Base' │ 'seamless-protocol' │         'USDC'          │ 10645223.42048365  │  4.447333122388667   │ 6.660898734592206  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │ 47455064.91565339  │ 36809841.495169744 │ 6.0341457102314715  │        null        │ 0.77 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x833589fcd6edb6e08f4c7c32d4f71b54bda02913&marketName=proto_base_v3' │    true    │                   │
    │    2    │ '0x48bf8fcd44e2977c8a9a744658431a8e6c0d866c-base' │ 'Base' │ 'seamless-protocol' │         'WETH'          │ 4865627.434798371  │  1.320067631789567   │ 4.319005637604006  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 15446731.328419866 │ 10581103.893621495 │  2.140926940821661  │ 0.9457586187548798 │ 0.75 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4200000000000000000000000000000000000006&marketName=proto_base_v3' │    true    │                   │
    │    3    │ '0x258730e23cf2f25887cb962d32bd10b878ea8a4e-base' │ 'Base' │ 'seamless-protocol' │ 'ilm-wstETH/ETH-3xloop' │  1172016.73985501  │   6.95118941967503   │ 89.21444246004134  │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │                    │                    │                     │                    │      │                                                                                                                                             │            │ 8.805120587546234 │
    │    4    │ '0xce335056a7b3be1b0b23ea4df1fd0969328c7c0c-base' │ 'Base' │ 'seamless-protocol' │         'BRETT'         │ 1095224.7168233306 │          0           │ 51.078588647218496 │                        [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ]                        │ [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ] │ 1095224.7168233306 │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x532f27101965dd16442e59d40670faf5ebb142e4&marketName=proto_base_v3' │   false    │                   │
    │    5    │ '0x70c75d336a84060afb393a69273cfd9e8103f2f3-base' │ 'Base' │ 'seamless-protocol' │         'AERO'          │ 808689.6039456114  │  7.079276706226638   │ 22.03563241615952  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x940181a94a35a4569e4529a3cdfb74e38fd98631' ] │ 1513786.7678747126 │ 705097.1639291012  │ 18.902109933615012  │ 3.311620893478437  │ 0.3  │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x940181a94a35a4569e4529a3cdfb74e38fd98631&marketName=proto_base_v3' │    true    │                   │
    │    6    │ '0x2c159a183d9056e29649ce7e56e59ca833d32624-base' │ 'Base' │ 'seamless-protocol' │         'cbETH'         │ 652926.1372787182  │ 0.030601584871272146 │ 2.3379453597073594 │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22' ] │ 684849.2587812579  │ 31923.121502539725 │ 0.7272663072944403  │        null        │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22&marketName=proto_base_v3' │    true    │                   │
    │    7    │ '0xfa48a40dad139e9b1af8dc82f37da58cc3ca2867-base' │ 'Base' │ 'seamless-protocol' │        'wstETH'         │ 398785.97252346884 │ 0.002211271373444712 │ 8.094886241000713  │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452' ] │ 403837.7072481099  │ 5051.734724641079  │ 0.19549809518261824 │        null        │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452&marketName=proto_base_v3' │    true    │                   │
    │    8    │ '0x39c0926455682a2afb5680045f309848c350de34-base' │ 'Base' │ 'seamless-protocol' │         'DEGEN'         │ 198277.05082678242 │          0           │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x4ed4e862860bed51a9570b96d89af5e1b0efefed' ] │ 198277.05082678242 │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4ed4e862860bed51a9570b96d89af5e1b0efefed&marketName=proto_base_v3' │   false    │                   │
    │    9    │ '0x13a13869b814be8f13b86e9875ab51bda882e391-base' │ 'Base' │ 'seamless-protocol' │         'USDbC'         │ 171108.54094061852 │  3.939710530188124   │        null        │                                               []                                               │ [ '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca' ] │ 746270.7636652311  │ 575162.2227246126  │  6.004135144908274  │        null        │ 0.77 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca&marketName=proto_base_v3' │    true    │                   │
    └─────────┴───────────────────────────────────────────────────┴────────┴─────────────────────┴─────────────────────────┴────────────────────┴──────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────┴────────────────────┴──────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴───────────────────┘

**Comment by llamatester** [comment]
The seamless-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       95 passed, 95 total
    Snapshots:   0 total
    Time:        0.273 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────┬────────┬─────────────────────┬─────────────────────────┬────────────────────┬──────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────┬────────────────────┬──────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬──────────────────┐
    │ (index) │                       pool                        │ chain  │       project       │         symbol          │       tvlUsd       │       apyBase        │     apyReward      │                                          rewardTokens                                          │                 underlyingTokens                 │   totalSupplyUsd   │   totalBorrowUsd   │    apyBaseBorrow    │  apyRewardBorrow   │ ltv  │                                                                     url                                                                     │ borrowable │    apyBase7d     │
    ├─────────┼───────────────────────────────────────────────────┼────────┼─────────────────────┼─────────────────────────┼────────────────────┼──────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────┼────────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────┼──────────────────┤
    │    0    │ '0x67368df7734aee0bc65a845ac6d73974626b7a34-base' │ 'Base' │ 'seamless-protocol' │         'SEAM'          │ 11847937.68809567  │          0           │ 0.0396329608039549 │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85' ] │ 11847937.68809567  │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85&marketName=proto_base_v3' │   false    │                  │
    │    1    │ '0x53e240c0f985175da046a62f26d490d1e259036e-base' │ 'Base' │ 'seamless-protocol' │         'USDC'          │ 8225244.469910467  │  4.954001577019571   │ 7.005569244985923  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │ 45368213.139493234 │ 37142968.66958277  │  6.368600885497278  │        null        │ 0.77 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x833589fcd6edb6e08f4c7c32d4f71b54bda02913&marketName=proto_base_v3' │    true    │                  │
    │    2    │ '0x48bf8fcd44e2977c8a9a744658431a8e6c0d866c-base' │ 'Base' │ 'seamless-protocol' │         'WETH'          │ 5016155.7189660845 │  1.2744636311908202  │ 4.372108711886793  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 15342958.605448497 │ 10326802.886482414 │ 2.1036209120549243  │ 0.9743726849063012 │ 0.75 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4200000000000000000000000000000000000006&marketName=proto_base_v3' │    true    │                  │
    │    3    │ '0xce335056a7b3be1b0b23ea4df1fd0969328c7c0c-base' │ 'Base' │ 'seamless-protocol' │         'BRETT'         │ 1210545.9555449854 │          0           │ 47.60209583635468  │                        [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ]                        │ [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ] │ 1210545.9555449854 │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x532f27101965dd16442e59d40670faf5ebb142e4&marketName=proto_base_v3' │   false    │                  │
    │    4    │ '0x258730e23cf2f25887cb962d32bd10b878ea8a4e-base' │ 'Base' │ 'seamless-protocol' │ 'ilm-wstETH/ETH-3xloop' │  1181249.3093758   │  6.777699180586638   │ 89.00350600463508  │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │                    │                    │                     │                    │      │                                                                                                                                             │            │ 8.77772789930804 │
    │    5    │ '0x70c75d336a84060afb393a69273cfd9e8103f2f3-base' │ 'Base' │ 'seamless-protocol' │         'AERO'          │ 800703.6405501424  │  8.998073505977997   │ 22.01654430189791  │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x940181a94a35a4569e4529a3cdfb74e38fd98631' ] │ 1523423.9261203543 │ 722720.2855702119  │  23.59211288076464  │ 3.2486209352039976 │ 0.3  │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x940181a94a35a4569e4529a3cdfb74e38fd98631&marketName=proto_base_v3' │    true    │                  │
    │    6    │ '0x2c159a183d9056e29649ce7e56e59ca833d32624-base' │ 'Base' │ 'seamless-protocol' │         'cbETH'         │ 660675.0609927594  │ 0.029097565581019044 │ 2.326054170579723  │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22' ] │  692132.470671891  │ 31457.409679131582 │ 0.7091691523081883  │        null        │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22&marketName=proto_base_v3' │    true    │                  │
    │    7    │ '0xfa48a40dad139e9b1af8dc82f37da58cc3ca2867-base' │ 'Base' │ 'seamless-protocol' │        'wstETH'         │ 394517.95761023596 │ 0.00219693235089891  │ 8.227756199392793  │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452' ] │ 399499.19155876024 │ 4981.233948524285  │ 0.19486320910436197 │        null        │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452&marketName=proto_base_v3' │    true    │                  │
    │    8    │ '0x5ed6167232b937b0a5c84b49031139f405c09c8a-base' │ 'Base' │ 'seamless-protocol' │  'ilm-ETH/USDC-3xloop'  │  205100.99398387   │   55276691690.733    │ 172.85222124065226 │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x4200000000000000000000000000000000000006' ] │                    │                    │                     │                    │      │                                                                                                                                             │            │       -100       │
    │    9    │ '0x39c0926455682a2afb5680045f309848c350de34-base' │ 'Base' │ 'seamless-protocol' │         'DEGEN'         │ 204020.34396211297 │          0           │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x4ed4e862860bed51a9570b96d89af5e1b0efefed' ] │ 204020.34396211297 │         0          │          0          │        null        │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4ed4e862860bed51a9570b96d89af5e1b0efefed&marketName=proto_base_v3' │   false    │                  │
    └─────────┴───────────────────────────────────────────────────┴────────┴─────────────────────┴─────────────────────────┴────────────────────┴──────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────┴────────────────────┴──────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴──────────────────┘

**Comment by slasher125** [comment]
sir we don't display escrowed apy rewards on our end

**Comment by llamatester** [comment]
The seamless-protocol adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       95 passed, 95 total
    Snapshots:   0 total
    Time:        0.285 s
    Ran all test suites.
    
    Nb of pools: 13
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────┬────────┬─────────────────────┬─────────────────────────┬────────────────────┬───────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────┬──────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬───────────────────┐
    │ (index) │                       pool                        │ chain  │       project       │         symbol          │       tvlUsd       │        apyBase        │     apyReward      │                                          rewardTokens                                          │                 underlyingTokens                 │   totalSupplyUsd   │   totalBorrowUsd   │   apyBaseBorrow    │ apyRewardBorrow │ ltv  │                                                                     url                                                                     │ borrowable │     apyBase7d     │
    ├─────────┼───────────────────────────────────────────────────┼────────┼─────────────────────┼─────────────────────────┼────────────────────┼───────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────┼───────────────────┤
    │    0    │ '0x67368df7734aee0bc65a845ac6d73974626b7a34-base' │ 'Base' │ 'seamless-protocol' │         'SEAM'          │ 11330061.334568366 │           0           │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85' ] │ 11330061.334568366 │         0          │         0          │      null       │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85&marketName=proto_base_v3' │   false    │                   │
    │    1    │ '0x53e240c0f985175da046a62f26d490d1e259036e-base' │ 'Base' │ 'seamless-protocol' │         'USDC'          │   8258072.536454   │   4.954648466142834   │ 0.1731745074445888 │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913' ] │  45562513.500193   │  37304440.963739   │ 6.369016675046263  │      null       │ 0.77 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x833589fcd6edb6e08f4c7c32d4f71b54bda02913&marketName=proto_base_v3' │    true    │                   │
    │    2    │ '0x48bf8fcd44e2977c8a9a744658431a8e6c0d866c-base' │ 'Base' │ 'seamless-protocol' │         'WETH'          │ 5159661.003337673  │  1.1959901704466358   │        null        │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x4200000000000000000000000000000000000006' ] │ 14826742.686387029 │ 9667081.683049355  │ 2.037828169248858  │      null       │ 0.75 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4200000000000000000000000000000000000006&marketName=proto_base_v3' │    true    │                   │
    │    3    │ '0x258730e23cf2f25887cb962d32bd10b878ea8a4e-base' │ 'Base' │ 'seamless-protocol' │ 'ilm-wstETH/ETH-3xloop' │  1149494.88360051  │   5.060531108944422   │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' ] │                    │                    │                    │                 │      │                                                                                                                                             │            │ 8.735905175043722 │
    │    4    │ '0xce335056a7b3be1b0b23ea4df1fd0969328c7c0c-base' │ 'Base' │ 'seamless-protocol' │         'BRETT'         │ 1139061.3962589332 │           0           │ 47.381936218265764 │                        [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ]                        │ [ '0x532f27101965dd16442e59d40670faf5ebb142e4' ] │ 1139061.3962589332 │         0          │         0          │      null       │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x532f27101965dd16442e59d40670faf5ebb142e4&marketName=proto_base_v3' │   false    │                   │
    │    5    │ '0x70c75d336a84060afb393a69273cfd9e8103f2f3-base' │ 'Base' │ 'seamless-protocol' │         'AERO'          │ 843043.6643459073  │   3.246115067109391   │ 1.0086841920588125 │ [ '0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85', '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ] │ [ '0x940181a94a35a4569e4529a3cdfb74e38fd98631' ] │ 1526303.1238657176 │ 683259.4595198103  │ 9.016384441004451  │      null       │ 0.3  │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x940181a94a35a4569e4529a3cdfb74e38fd98631&marketName=proto_base_v3' │    true    │                   │
    │    6    │ '0x2c159a183d9056e29649ce7e56e59ca833d32624-base' │ 'Base' │ 'seamless-protocol' │         'cbETH'         │ 635257.4421298684  │ 0.029898045633578237  │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22' ] │ 665937.9925688489  │ 30680.550438980456 │ 0.7188576662205587 │      null       │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22&marketName=proto_base_v3' │    true    │                   │
    │    7    │ '0xfa48a40dad139e9b1af8dc82f37da58cc3ca2867-base' │ 'Base' │ 'seamless-protocol' │        'wstETH'         │ 378971.8335286758  │ 0.0059635910078528614 │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452' ] │ 386935.4632067578  │ 7963.629678082012  │ 0.3210520401452192 │      null       │ 0.65 │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0xc1cba3fcea344f92d9239c08c0568f6f2f0ee452&marketName=proto_base_v3' │    true    │                   │
    │    8    │ '0x39c0926455682a2afb5680045f309848c350de34-base' │ 'Base' │ 'seamless-protocol' │         'DEGEN'         │ 208363.0930309436  │           0           │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x4ed4e862860bed51a9570b96d89af5e1b0efefed' ] │ 208363.0930309436  │         0          │         0          │      null       │  0   │ 'https://legacy.seamlessprotocol.com/reserve-overview/?underlyingAsset=0x4ed4e862860bed51a9570b96d89af5e1b0efefed&marketName=proto_base_v3' │   false    │                   │
    │    9    │ '0x5ed6167232b937b0a5c84b49031139f405c09c8a-base' │ 'Base' │ 'seamless-protocol' │  'ilm-ETH/USDC-3xloop'  │  186533.55004305   │   -99.9998597125131   │        null        │                        [ '0x998e44232bef4f8b033e5a5175bdc97f2b10d5e5' ]                        │ [ '0x4200000000000000000000000000000000000006' ] │                    │                    │                    │                 │      │                                                                                                                                             │            │       -100        │
    └─────────┴───────────────────────────────────────────────────┴────────┴─────────────────────┴─────────────────────────┴────────────────────┴───────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴─────────────────┴──────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴───────────────────┘

**Pull request merged**
