### PR TITLE
sTLOS Yield %

### PR DESCRIPTION
**Pull request by nathanduft44**
Script for pulling the sTLOS yield percentage from https://api.telos.net/v1/apy/evm

### CODE REVIEW

**Comment by nathanduft44** [comment]
sTLOS yield should be good to merge into the yield-server. Please tag me here if there needs to be any adjustments. Thanks in advance!

**Comment by slasher125** [comment]
@nathanduft44 pls have a look at the readme. on yield-server we require more info than just a single value for apy. also, we are moving away from centralised api's. please refactor to call from either contracts or subgraph

**Comment by nathanduft44** [comment]
Hey, @slasher125 appreciate the feedback!

The whole adaptor is included in this PR. 

FYI given the structure of our liquid staking protocol -> It would be best as of now if we could use the Telos API for retrieving the sTLOS APY value, see in the code :). 

We are also going to integrate a few of our Dexes and future yield opps within our Defi Ecosystem.

**Comment by slasher125** [comment]
gm, pls run the tests locally via `npm run test --adapter=stlos`

**Comment by slasher125** [comment]
@nathanduft44 ser can we wrap tings up here? :)

**Comment by slasher125** [comment]
k, added this via e71c7c1f23168fbcf1fa8ad430bd5bac9b251105
closing this

**Pull request closed without merging**
