### PR TITLE
add meme-dollar

### PR DESCRIPTION
**Pull request by wdashi-hk**
add meme-dollar

### CODE REVIEW

**Comment by slasher125** [comment]
symbols are wrong: instead of PINA -> `PINA-MEME` `PINDA-USDC` etc. it needs to consist of the underlying token symbols

**Comment by llamatester** [comment]
The meme-dollar adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.333 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────┬────────────────────┬────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │   symbol    │       tvlUsd       │    apy     │                   rewardTokens                   │                                                                                              poolMeta                                                                                              │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────┼────────────────────┼────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x02814F435dD04e254Be7ae69F61FCa19881a780D-ethereum' │ 'Ethereum' │ 'meme-dollar' │   'PINA'    │ 104275.87233944343 │ 4535.11916 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │  'Forge Pool, Staking events on this pool will restart the lockup timer（exit lockup: 20 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily. '   │
    │    1    │ '0x713afA49478f1A33c3194Ff65dbf3c8058406670-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-MEME' │ 63635.10757820145  │ 1279.92798 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'PINA-MEME Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.' │
    │    2    │ '0x58624E7a53700cb39772E0267ca0AC70f064078B-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-USDC' │  45437.1226589355  │ 6914.1293  │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'PINA-USDC Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.' │
    │    3    │ '0xb892A4b35F227F27e4B58cc20691B3C671D0beC8-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'MEME-ETH'  │ 9931.512042468794  │ 7029.43572 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'MEME-ETH Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.'  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────┴────────────────────┴────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by wdashi-hk** [comment]
> * symbols are wrong: instead of PINA -> `PINA-MEME` `PINDA-USDC` etc. it needs to consist of the underlying token symbols
> * `Staking events will restart the lockup timer (exit lockup: 12 epochs)` -> how do you define an epoch? we need to make sure that info is present via `poolMeta`

**Comment by llamatester** [comment]
The meme-dollar adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.313 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────┬────────────────────┬────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │   symbol    │       tvlUsd       │    apy     │                   rewardTokens                   │                                                                                              poolMeta                                                                                              │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────┼────────────────────┼────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x02814F435dD04e254Be7ae69F61FCa19881a780D-ethereum' │ 'Ethereum' │ 'meme-dollar' │   'PINA'    │ 104275.87233944343 │ 4535.11916 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │  'Forge Pool, Staking events on this pool will restart the lockup timer（exit lockup: 20 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily. '   │
    │    1    │ '0x713afA49478f1A33c3194Ff65dbf3c8058406670-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-MEME' │ 63635.10757820145  │ 1279.92798 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'PINA-MEME Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.' │
    │    2    │ '0x58624E7a53700cb39772E0267ca0AC70f064078B-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-USDC' │  45437.1226589355  │ 6914.1293  │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'PINA-USDC Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.' │
    │    3    │ '0xb892A4b35F227F27e4B58cc20691B3C671D0beC8-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'MEME-ETH'  │ 9931.512042468794  │ 7029.43572 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'MEME-ETH Pool, Staking events on this pool will restart the lockup timer（exit lockup: 12 epochs, an epoch defines a period within the Meme Dollar ecosystem, 1 epoch equals 6 hours, 4x daily.'  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────┴────────────────────┴────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
nice, we need to make poolMeta shorter. the pool info is not necessary cause that can be seen from the symbol.
lets change poolMeta to -> `exit lockup: 3days`

**Comment by llamatester** [comment]
The meme-dollar adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       28 passed, 28 total
    Snapshots:   0 total
    Time:        0.329 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬───────────────┬─────────────┬────────────────────┬────────────┬──────────────────────────────────────────────────┬───────────────────────┐
    │ (index) │                         pool                          │   chain    │    project    │   symbol    │       tvlUsd       │    apy     │                   rewardTokens                   │       poolMeta        │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼───────────────┼─────────────┼────────────────────┼────────────┼──────────────────────────────────────────────────┼───────────────────────┤
    │    0    │ '0x02814F435dD04e254Be7ae69F61FCa19881a780D-ethereum' │ 'Ethereum' │ 'meme-dollar' │   'PINA'    │ 104275.87233944343 │ 4535.11916 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'Exit lockup: 5days ' │
    │    1    │ '0x713afA49478f1A33c3194Ff65dbf3c8058406670-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-MEME' │ 63635.10757820145  │ 1279.92798 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'Exit lockup: 3days'  │
    │    2    │ '0x58624E7a53700cb39772E0267ca0AC70f064078B-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'PINA-USDC' │  45437.1226589355  │ 6914.1293  │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'Exit lockup: 3days'  │
    │    3    │ '0xb892A4b35F227F27e4B58cc20691B3C671D0beC8-ethereum' │ 'Ethereum' │ 'meme-dollar' │ 'MEME-ETH'  │ 9952.488223161012  │ 7014.61964 │ [ '0x02814F435dD04e254Be7ae69F61FCa19881a780D' ] │ 'Exit lockup: 3days'  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴───────────────┴─────────────┴────────────────────┴────────────┴──────────────────────────────────────────────────┴───────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Pull request merged**
