### PR TITLE
add Sovryn pools

### PR DESCRIPTION
**Pull request by aZ2394**

### CODE REVIEW

**Comment by llamatester** [comment]
The sovryn-dex adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       76 passed, 76 total
    Snapshots:   0 total
    Time:        0.392 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────┬────────────────────┬─────────────┬─────────┬───────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │    chain    │   project    │       tvlUsd       │   symbol    │ apyBase │ apyReward │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────┼────────────────────┼─────────────┼─────────┼───────────┼──────────────────────────────────────────────────┤
    │    0    │ '0xe81373285eb8cdee2e0108e98c5aa022948da9d2' │ 'Rootstock' │ 'sovryn-dex' │     4892133.87     │ 'DLLR-RBTC' │  10.09  │   9.39    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    1    │ '0xe76ea314b32fcf641c6c57f14110c5baa1e45ff4' │ 'Rootstock' │ 'sovryn-dex' │     2335279.38     │ 'SOV-RBTC'  │  10.85  │    9.7    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    2    │ '0xa9c3d9681215ef7623dc28ea6b75bf87fdf285d9' │ 'Rootstock' │ 'sovryn-dex' │     2093495.52     │ 'XUSD-RBTC' │  7.16   │   5.47    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    3    │ '0x65528e06371635a338ca804cd65958a11cb11009' │ 'Rootstock' │ 'sovryn-dex' │ 1700282.9500000002 │ 'RIF-RBTC'  │  5.14   │     0     │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    4    │ '0xa57ec11497f45fe86eca50f4f1c9e75c8016a1af' │ 'Rootstock' │ 'sovryn-dex' │ 1555935.6099999999 │ 'ETH-RBTC'  │    0    │     0     │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    5    │ '0x448c2474b255576554eed36c24430ccfac131ce3' │ 'Rootstock' │ 'sovryn-dex' │     1272536.01     │ 'USDT-RBTC' │  1.08   │     0     │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    6    │ '0x1684b871ec5f93de142e79a670b541d75be07ead' │ 'Rootstock' │ 'sovryn-dex' │     547184.44      │ 'BNB-RBTC'  │  1.02   │     0     │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    7    │ '0xd715192612f03d20bae53a5054af530c9bb0fa3f' │ 'Rootstock' │ 'sovryn-dex' │     194402.68      │ 'DOC-RBTC'  │  3.05   │   0.01    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    8    │ '0xe321442dc4793c17f41fe3fb192a856a4864ceaf' │ 'Rootstock' │ 'sovryn-dex' │     179701.62      │ 'MOC-RBTC'  │  0.02   │   0.01    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    9    │ '0x3a18e61d9c9f1546dea013478dd653c793098f17' │ 'Rootstock' │ 'sovryn-dex' │ 126705.45999999999 │ 'MYNT-RBTC' │  0.02   │   0.02    │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────┴────────────────────┴─────────────┴─────────┴───────────┴──────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
henlo, ty for adding.
pls refactor to use subgraph/on chain calls instead of using your api. i can see u got this subgraph `https://subgraph.sovryn.app/subgraphs/name/DistributedCollective/sovryn-subgraph` which i think contains everything required to calculate tvl + apy base (derived from 24h rolling window usd volume) [take a look at the uniswap v2 adapter]

for rewards apy: here too, it'd be better if u call the reward contract directly

**Comment by aZ2394** [comment]
Hi, @slasher125 thanks for reviewing PR and your response.
Both of the services that we using to collect data in this adapter are in public repo’s and they calculate this data from our subgraph. 
 https://github.com/DistributedCollective/sovryn-amm-apy
https://github.com/DistributedCollective/Sovryn-graph-wrapper
 We developed it for such kind of integrations and our FE using it as well.
The calculations being done to get amm apy are not practical to do on the graph, but are documented in the amm apy repo.Also, the amm apy endpoint splits out yield from liquidity mining and yield from fees. So, how important is it for you to load this data directly from the subgraph? We would be very grateful if it were possible to avoid developing the calculation logic also in the adapter.
Thanks in advance!

**Comment by slasher125** [comment]
sry for late reply. 
q: incentive (apyReward) can be withdrawn immediately with no lockup and are unboosted?

**Comment by slasher125** [comment]
k, in that case we need to remove it, we do not show any locked rewards but only those which can be claimed immediately. 
for reference pls include the above github link in the adapter

**Comment by llamatester** [comment]
The sovryn-dex adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       76 passed, 76 total
    Snapshots:   0 total
    Time:        0.389 s
    Ran all test suites.
    
    Nb of pools: 12
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬─────────────┬──────────────┬────────────────────┬─────────────┬──────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │    chain    │   project    │       tvlUsd       │   symbol    │ apy  │                   rewardTokens                   │
    ├─────────┼──────────────────────────────────────────────┼─────────────┼──────────────┼────────────────────┼─────────────┼──────┼──────────────────────────────────────────────────┤
    │    0    │ '0xe81373285eb8cdee2e0108e98c5aa022948da9d2' │ 'Rootstock' │ 'sovryn-dex' │     4845872.65     │ 'DLLR-RBTC' │ 9.03 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    1    │ '0xe76ea314b32fcf641c6c57f14110c5baa1e45ff4' │ 'Rootstock' │ 'sovryn-dex' │ 2210952.1399999997 │ 'SOV-RBTC'  │ 9.77 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    2    │ '0xa9c3d9681215ef7623dc28ea6b75bf87fdf285d9' │ 'Rootstock' │ 'sovryn-dex' │ 2053433.0899999999 │ 'XUSD-RBTC' │ 6.81 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    3    │ '0x65528e06371635a338ca804cd65958a11cb11009' │ 'Rootstock' │ 'sovryn-dex' │     1518137.73     │ 'RIF-RBTC'  │ 2.15 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    4    │ '0xa57ec11497f45fe86eca50f4f1c9e75c8016a1af' │ 'Rootstock' │ 'sovryn-dex' │     1515358.99     │ 'ETH-RBTC'  │ 0.06 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    5    │ '0x448c2474b255576554eed36c24430ccfac131ce3' │ 'Rootstock' │ 'sovryn-dex' │     1266074.79     │ 'USDT-RBTC' │ 1.66 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    6    │ '0x1684b871ec5f93de142e79a670b541d75be07ead' │ 'Rootstock' │ 'sovryn-dex' │     524134.73      │ 'BNB-RBTC'  │ 1.93 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    7    │ '0xe321442dc4793c17f41fe3fb192a856a4864ceaf' │ 'Rootstock' │ 'sovryn-dex' │     197668.06      │ 'MOC-RBTC'  │ 0.01 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    8    │ '0xd715192612f03d20bae53a5054af530c9bb0fa3f' │ 'Rootstock' │ 'sovryn-dex' │     192494.18      │ 'DOC-RBTC'  │ 1.28 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    │    9    │ '0x3a18e61d9c9f1546dea013478dd653c793098f17' │ 'Rootstock' │ 'sovryn-dex' │     124508.88      │ 'MYNT-RBTC' │ 0.02 │ [ '0xefc78fc7d48b64958315949279ba181c2114abbd' ] │
    └─────────┴──────────────────────────────────────────────┴─────────────┴──────────────┴────────────────────┴─────────────┴──────┴──────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by aZ2394** [comment]
@slasher125 ok, thanks!
it's ready

**Pull request merged**
