### PR TITLE
azuro adapter added

### PR DESCRIPTION
**Pull request by cxxnm**

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running azuro adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 28 passed, 29 total
    Snapshots:   0 total
    Time:        0.297 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬─────────┬─────────┬───────────────────┬─────────┐
    │ (index) │                     pool                     │  chain   │ project │ symbol  │      tvlUsd       │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼──────────┼─────────┼─────────┼───────────────────┼─────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'matic'  │ 'azuro' │ 'USDT'  │  8074382.657581   │  20.02  │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 624060.773371897  │  10.44  │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │  'celo'  │ 'azuro' │ 'WCHZ'  │       7905        │  null   │
    │    3    │ '0x2a838ab9b037db117576db8d0dcc3b686748ef7c' │ 'matic'  │ 'azuro' │ 'USDC'  │    7513.276237    │  20.02  │
    │    4    │ '0xac004b512c33d029cf23abf04513f1f380b3fd0a' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 4134.267158731044 │  10.44  │
    └─────────┴──────────────────────────────────────────────┴──────────┴─────────┴─────────┴───────────────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
Error while running azuro adapter: 
        
 
 Test Suites: 1 failed, 1 total
    Tests:       1 failed, 28 passed, 29 total
    Snapshots:   0 total
    Time:        0.292 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬─────────┬─────────┬───────────────────┬─────────┐
    │ (index) │                     pool                     │  chain   │ project │ symbol  │      tvlUsd       │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼──────────┼─────────┼─────────┼───────────────────┼─────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'matic'  │ 'azuro' │ 'USDT'  │  8023511.239555   │  20.02  │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 624060.773371897  │  10.44  │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │  'celo'  │ 'azuro' │ 'WCHZ'  │       7905        │   '0'   │
    │    3    │ '0x2a838ab9b037db117576db8d0dcc3b686748ef7c' │ 'matic'  │ 'azuro' │ 'USDC'  │    7513.276237    │  20.02  │
    │    4    │ '0xac004b512c33d029cf23abf04513f1f380b3fd0a' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 4134.267158731044 │  10.44  │
    └─────────┴──────────────────────────────────────────────┴──────────┴─────────┴─────────┴───────────────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama
    }

**Comment by llamatester** [comment]
The azuro adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.268 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬──────────┬─────────┬─────────┬───────────────────┬─────────┐
    │ (index) │                     pool                     │  chain   │ project │ symbol  │      tvlUsd       │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼──────────┼─────────┼─────────┼───────────────────┼─────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'matic'  │ 'azuro' │ 'USDT'  │  8023511.239555   │  20.02  │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 624060.773371897  │  10.44  │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │  'celo'  │ 'azuro' │ 'WCHZ'  │       7905        │    0    │
    │    3    │ '0x2a838ab9b037db117576db8d0dcc3b686748ef7c' │ 'matic'  │ 'azuro' │ 'USDC'  │    7513.276237    │  20.02  │
    │    4    │ '0xac004b512c33d029cf23abf04513f1f380b3fd0a' │ 'gnosis' │ 'azuro' │ 'WXDAI' │ 4134.267158731044 │  10.44  │
    └─────────┴──────────────────────────────────────────────┴──────────┴─────────┴─────────┴───────────────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The azuro adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.279 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────┬─────────┬───────────────────┬─────────┐
    │ (index) │                     pool                     │   chain   │ project │ symbol  │      tvlUsd       │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────┼─────────┼───────────────────┼─────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'polygon' │ 'azuro' │ 'USDT'  │  7960260.205705   │  19.78  │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis'  │ 'azuro' │ 'WXDAI' │ 620416.7489664025 │  10.51  │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │ 'chiliz'  │ 'azuro' │ 'WCHZ'  │       7905        │    0    │
    │    3    │ '0x2a838ab9b037db117576db8d0dcc3b686748ef7c' │ 'polygon' │ 'azuro' │ 'USDC'  │    7513.276237    │  19.78  │
    │    4    │ '0xac004b512c33d029cf23abf04513f1f380b3fd0a' │ 'gnosis'  │ 'azuro' │ 'WXDAI' │ 4134.267158731044 │  10.51  │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────┴─────────┴───────────────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hi, ty for adding.
the apr is based since inception, can u add a version which is based on a much smaller window, ideally 24h

**Comment by cxxnm** [comment]
@slasher125 it’s possible but makes no sense
scaling one-day return to the whole year will be too volatile

**Comment by slasher125** [comment]
problem with inception apy is that its not informative of recent performance. on our end we provide historical values and averages of daily apy values instead to smooth out short term volatility

**Comment by llamatester** [comment]
The azuro adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       29 passed, 29 total
    Snapshots:   0 total
    Time:        0.273 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────┬─────────┬───────────────────┬─────────┐
    │ (index) │                     pool                     │   chain   │ project │ symbol  │      tvlUsd       │ apyBase │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────┼─────────┼───────────────────┼─────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'polygon' │ 'azuro' │ 'USDT'  │  7846098.556232   │  24.23  │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis'  │ 'azuro' │ 'WXDAI' │ 618007.0847005178 │  0.01   │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │ 'chiliz'  │ 'azuro' │ 'WCHZ'  │       7905        │    0    │
    │    3    │ '0x2a838ab9b037db117576db8d0dcc3b686748ef7c' │ 'polygon' │ 'azuro' │ 'USDC'  │    7501.501424    │  24.23  │
    │    4    │ '0xac004b512c33d029cf23abf04513f1f380b3fd0a' │ 'gnosis'  │ 'azuro' │ 'WXDAI' │ 4134.267158731044 │  0.01   │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────┴─────────┴───────────────────┴─────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by cxxnm** [comment]
@slasher125 hi, we added apr based on the profitability for the last day. it should be good now

**Comment by slasher125** [comment]
- how come eg usdc pool has the exact same apr as the usdt one?
- briefly checked the docs, seems like there is a min lockup of 7days, this info needs to be added to `poolMeta`

**Comment by llamatester** [comment]
The azuro adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       19 passed, 19 total
    Snapshots:   0 total
    Time:        0.267 s
    Ran all test suites.
    
    Nb of pools: 3
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬─────────┬─────────┬───────────────────┬─────────┬────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │ project │ symbol  │      tvlUsd       │ apyBase │                              poolMeta                              │
    ├─────────┼──────────────────────────────────────────────┼───────────┼─────────┼─────────┼───────────────────┼─────────┼────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x7043e4e1c4045424858ecbced80989feafc11b36' │ 'polygon' │ 'azuro' │ 'USDT'  │  7868667.498327   │  24.23  │ 'There is a lockup period of 7 days after liquidity is deposited.' │
    │    1    │ '0x204e7371ade792c5c006fb52711c50a7efc843ed' │ 'gnosis'  │ 'azuro' │ 'WXDAI' │ 618007.0847005178 │  0.01   │ 'There is a lockup period of 7 days after liquidity is deposited.' │
    │    2    │ '0x6909ead2a1da7b632d5993d329def4d2dbbc8261' │ 'chiliz'  │ 'azuro' │ 'WCHZ'  │       7905        │    0    │ 'There is a lockup period of 7 days after liquidity is deposited.' │
    └─────────┴──────────────────────────────────────────────┴───────────┴─────────┴─────────┴───────────────────┴─────────┴────────────────────────────────────────────────────────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by cxxnm** [comment]
actually those two pools are "deprecated" i so i excluded it. 
poolMeta added
let me know if something else is needed

**Pull request merged**
