### PR TITLE
blue planet yield listing

### PR DESCRIPTION
**Pull request by defininja**
Please accept pull request to list yields from blue planet.

### CODE REVIEW

**Comment by llamatester** [comment]
The blue-planet adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       39 passed, 39 total
    Snapshots:   0 total
    Time:        0.45 s
    Ran all test suites.
    
    Nb of pools: 5
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬───────────┬───────────────┬──────────────┬────────────────────┬─────────────────────┬────────────────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain   │    project    │    symbol    │       tvlUsd       │       apyBase       │     apyReward      │                   rewardTokens                   │                                        underlyingTokens                                        │
    ├─────────┼──────────────────────────────────────────────┼───────────┼───────────────┼──────────────┼────────────────────┼─────────────────────┼────────────────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0x89fd5dcf5d7c9feba8c8106a5abc09325fc2a39e' │ 'Binance' │ 'blue-planet' │ 'WBNB-BUSD'  │ 199403.92825054255 │ 1.7839048098095889  │ 25.857177215159368 │ [ '0xb3Cb6d2f8f2FDe203a022201C81a96c167607F15' ] │ [ '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', '0xe9e7cea3dedca5984780bafc599bd69add087d56' ] │
    │    1    │ '0x7cde1a8ee90e7b03fbd554dfea9c341326719f0f' │ 'Binance' │ 'blue-planet' │ 'GAMMA-WBNB' │ 191309.06752978094 │  3.01341734323044   │ 114.26561402379525 │ [ '0xb3Cb6d2f8f2FDe203a022201C81a96c167607F15' ] │ [ '0xb3cb6d2f8f2fde203a022201c81a96c167607f15', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │
    │    2    │ '0x03028d2f8b275695a1c6afb69a4765e3666e36d9' │ 'Binance' │ 'blue-planet' │ 'AQUA-WBNB'  │ 131475.80478881212 │  1.87136806050614   │ 166.19629255467535 │ [ '0xb3Cb6d2f8f2FDe203a022201C81a96c167607F15' ] │ [ '0x72b7d61e8fc8cf971960dd9cfa59b8c829d91991', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │
    │    3    │ '0x4c4f18da91063f1c34a9396b2d97e95b163f2b0c' │ 'Binance' │ 'blue-planet' │ 'BTCB-WBNB'  │  75965.4970882408  │ 0.1859250411847091  │ 75.16121245537678  │ [ '0xb3Cb6d2f8f2FDe203a022201C81a96c167607F15' ] │ [ '0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │
    │    4    │ '0x1820e39d1be8bf90fe45b097503613e557f5dfdf' │ 'Binance' │ 'blue-planet' │  'ETH-WBNB'  │ 55939.87894563871  │ 0.37058312428561724 │ 108.55685307429096 │ [ '0xb3Cb6d2f8f2FDe203a022201C81a96c167607F15' ] │ [ '0x2170ed0880ac9a755fd29b2688956bd959f933f8', '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' ] │
    └─────────┴──────────────────────────────────────────────┴───────────┴───────────────┴──────────────┴────────────────────┴─────────────────────┴────────────────────┴──────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
ty for the PR. i think `apyReward` values need to be scaled by `/ 2` . then the nbs of blue planets UI seem to match

**Comment by defininja** [comment]
Hi @slasher125 ,

Our gamma rewards to pool is based on alloc points assigned to pool.
Half of the rewards are directly distributed between pool contributors based their shares. We call this "Gamma Apy"
Rest half is distributed among users who have their gamma staked in inifnity pool, pool id 0 in our farm 0x9EBce8B8d535247b2a0dfC0494Bc8aeEd7640cF9. We call this "Boost APY"

So minimum gamma apy will be half of the calculated apy and maximum will be full calculated apy.

So current calculation of the apy is correct.

Gamma Apy + Boost APY = Reward Apy

**Comment by defininja** [comment]
@slasher125  The boost APY is also coming from alloc point. So it should be calculated.

**Comment by slasher125** [comment]
sir, checking in with u again. are there any outstanding questions? i just checked blue planet, you also got lots of other products, like lending and vaults. would be great if u can add those too.

**Comment by defininja** [comment]
@slasher125 - when these pools will be listed. 

We will soon be working on listing tokens from lending and borrowing.

**Comment by slasher125** [comment]
k. reward apy still needs to be scaled by 2 as discussed above

**Pull request merged**
