### PR TITLE
Add Struct Finance

### PR DESCRIPTION
**Pull request by AntwuanDixon**

### CODE REVIEW

**Comment by llamatester** [comment]
The struct-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.418 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────┬─────────┬────────┬──────────────────────────────────────────────────┬─────────┬────────────────────────────────────────────────────────┬───────────────────┐
    │ (index) │     project      │ symbol  │ chain  │                 underlyingTokens                 │   apy   │                          pool                          │      tvlUsd       │
    ├─────────┼──────────────────┼─────────┼────────┼──────────────────────────────────────────────────┼─────────┼────────────────────────────────────────────────────────┼───────────────────┤
    │    0    │ 'struct-finance' │ 'USDC'  │ 'Avax' │ [ '0x9e295B5B976a184B14aD8cd72413aD846C299660' ] │ 11.1742 │ '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e-avalanche' │   104517.211557   │
    │    1    │ 'struct-finance' │ 'BTC.b' │ 'Avax' │ [ '0x9e295B5B976a184B14aD8cd72413aD846C299660' ] │   10    │ '0x152b9d0fdc40c096757f570a51e494bd4b943e50-avalanche' │ 75324.01323941999 │
    └─────────┴──────────────────┴─────────┴────────┴──────────────────────────────────────────────────┴─────────┴────────────────────────────────────────────────────────┴───────────────────┘

**Comment by slasher125** [comment]
pls lmk once ui is ok and i will take a look

**Comment by hirako2000** [comment]
> pls lmk once ui is ok and i will take a look

We pushed a patch, are you able to see the UI fine now?

**Comment by llamatester** [comment]
The struct-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       16 passed, 16 total
    Snapshots:   0 total
    Time:        0.468 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬──────────────────┬─────────┬────────┬──────────────────────────────────────────────────┬────────┬────────────────────────────────────────────────────────┬───────────────────┐
    │ (index) │     project      │ symbol  │ chain  │                 underlyingTokens                 │  apy   │                          pool                          │      tvlUsd       │
    ├─────────┼──────────────────┼─────────┼────────┼──────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────────┼───────────────────┤
    │    0    │ 'struct-finance' │ 'BTC.b' │ 'Avax' │ [ '0x9e295B5B976a184B14aD8cd72413aD846C299660' ] │   10   │ '0x152b9d0fdc40c096757f570a51e494bd4b943e50-avalanche' │ 83146.11842249999 │
    │    1    │ 'struct-finance' │ 'USDC'  │ 'Avax' │ [ '0x9e295B5B976a184B14aD8cd72413aD846C299660' ] │ 6.1424 │ '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e-avalanche' │    999.8389739    │
    └─────────┴──────────────────┴─────────┴────────┴──────────────────────────────────────────────────┴────────┴────────────────────────────────────────────────────────┴───────────────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by hirako2000** [comment]
> <10k TVL, these pools won't be shown in DefiLlama
good to know.


thanks the review and accepting this adapter @slasher125

**Pull request merged**
