### PR TITLE
added harbor-market reward yields

### PR DESCRIPTION
**Pull request by Deantoshi**
oHBR is an oToken that can be exercised at any time to HBR. The yields take into account the 50% premium users would need to pay to exercise. Calculated yields are post-exercise yields.

Thank you for working through these reward APY updates with me!

### CODE REVIEW

**Comment by llamatester** [comment]
The harbor-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.259 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬─────────┬─────────────────┬───────┬────────────────────┬──────────────────────┬────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬────────────────────┬────────────────────┬──────────────────────┬─────────────────┬──────────────────────────────────────────────────┬──────┬────────────┬──────────┐
    │ (index) │                       pool                       │ symbol  │     project     │ chain │       tvlUsd       │       apyBase        │ apyReward  │                 underlyingTokens                 │                  url                  │   totalSupplyUsd   │   totalBorrowUsd   │    apyBaseBorrow     │ apyRewardBorrow │                   rewardTokens                   │ ltv  │ borrowable │ poolMeta │
    ├─────────┼──────────────────────────────────────────────────┼─────────┼─────────────────┼───────┼────────────────────┼──────────────────────┼────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼────────────────────┼────────────────────┼──────────────────────┼─────────────────┼──────────────────────────────────────────────────┼──────┼────────────┼──────────┤
    │    0    │ '0x641a8edaec2921e904f910f063b474574bca1cb2-bsc' │  'ETH'  │ 'harbor-market' │ 'bsc' │ 126730.80536587206 │  1.4699131962459417  │ 1.39687978 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │  'https://harbor.market/markets/eth'  │ 224212.00155517965 │  97481.1961893076  │  6.762442811003726   │   12.83701123   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    1    │ '0xd85e24a4eca78d060c0cdc7a903bac108b3fb5bc-bsc' │ 'BTCB'  │ 'harbor-market' │ 'bsc' │ 85942.83956025256  │ 4.775754176962307e-8 │     0      │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ 'https://harbor.market/markets/btcb'  │  85949.574550409   │ 6.7349901564504435 │ 0.001218929935799541 │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    2    │ '0x275c55d05c3550432c03902d42d7f6318b91d099-bsc' │ 'WBNB'  │ 'harbor-market' │ 'bsc' │ 56897.59965942232  │  1.5342960216035424  │ 1.29381417 │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ 'https://harbor.market/markets/wbnb'  │ 102365.92162052183 │ 45468.32196109951  │  6.908954624647895   │   11.64432757   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    3    │ '0x686c55c8344e902cd8143cf4bdf2c5089be273c5-bsc' │ 'USDT'  │ 'harbor-market' │ 'bsc' │ 13907.838321220224 │  12.82504647198594   │ 2.92145353 │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ 'https://harbor.market/markets/usdt'  │ 105529.12295142186 │ 91621.28463020163  │  29.546570944046838  │   13.45601928   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    4    │ '0xca0ec956e829d999cd75c4e972beb73ceda823d5-bsc' │ 'USDC'  │ 'harbor-market' │ 'bsc' │  9546.22838123563  │  11.722448107621998  │ 1.91281238 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ 'https://harbor.market/markets/usdc'  │ 69152.08385051055  │ 59605.855469274924 │  27.20227190512256   │   8.87393495    │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    5    │ '0x78efdcfd2e5b5b35116710ffb00c3c08fb71bceb-bsc' │ 'DOGE'  │ 'harbor-market' │ 'bsc' │ 6.823013496530851  │ 0.09894854384006528  │     0      │ [ '0xbA2aE424d960c26247Dd6c32edC70B295c744C43' ] │ 'https://harbor.market/markets/doge'  │ 7.9869390228139405 │  1.16392552628309  │  2.265097180288637   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.5  │    true    │   null   │
    │    6    │ '0x5e421cfb49977780ddef9ee321030a101a9d717e-bsc' │ 'FDUSD' │ 'harbor-market' │ 'bsc' │ 6.2128405496529755 │ 0.09287832046884067  │     0      │ [ '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409' ] │ 'https://harbor.market/markets/fdusd' │ 8.271987277695905  │ 2.0591467280429296 │   1.2441752319565    │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.7  │    true    │   null   │
    │    7    │ '0xc2fcc39431ff974e21ee7228d21565b3add74f7a-bsc' │ 'Cake'  │ 'harbor-market' │ 'bsc' │ 3.399406275248757  │  3.3692977124801926  │     0      │ [ '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82' ] │ 'https://harbor.market/markets/cake'  │ 6.539461160999128  │ 3.1400548857503705 │  23.39509018561884   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.65 │    true    │   null   │
    └─────────┴──────────────────────────────────────────────────┴─────────┴─────────────────┴───────┴────────────────────┴──────────────────────┴────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴────────────────────┴────────────────────┴──────────────────────┴─────────────────┴──────────────────────────────────────────────────┴──────┴────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
i realize i missed some details in your previous updates. if i supply ETH and want to receive the reward APR, I would still need to pay with BNB to convert oHBR to HBR, right?

on our yield server, we only track rewards that can be claimed immediately and don’t require buying any additional tokens. In this case, since users would need to pay to convert oHBR into actual liquid rewards, it doesn’t quite fit.

we could add a poolMeta field to provide extra info about rewards being option tokens, but it wouldn’t be fair to other projects where we don’t show reward APRs for similar reasons. while I might relax this rule in the future, it’s something that would need to be changed across multiple adapters. for now, I just want to keep things consistent.

sorry again for any confusion or wasted time :(

**Comment by Deantoshi** [comment]
Gotcha, no worries! Just let me know what the best course of action from my part would be to stay kosher.

**Comment by slasher125** [comment]
i suggest we update the other 2 adapters that u have modified by just commenting out the apyReward and rewardToken fields from the pool object. u can leave the rest of the code as is given we might use this after all at some point in the future

**Comment by llamatester** [comment]
The harbor-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.261 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬─────────┬─────────────────┬───────┬────────────────────┬───────────────────────┬────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬────────────────────┬────────────────────┬───────────────────────┬─────────────────┬──────────────────────────────────────────────────┬──────┬────────────┬──────────┐
    │ (index) │                       pool                       │ symbol  │     project     │ chain │       tvlUsd       │        apyBase        │ apyReward  │                 underlyingTokens                 │                  url                  │   totalSupplyUsd   │   totalBorrowUsd   │     apyBaseBorrow     │ apyRewardBorrow │                   rewardTokens                   │ ltv  │ borrowable │ poolMeta │
    ├─────────┼──────────────────────────────────────────────────┼─────────┼─────────────────┼───────┼────────────────────┼───────────────────────┼────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼────────────────────┼────────────────────┼───────────────────────┼─────────────────┼──────────────────────────────────────────────────┼──────┼────────────┼──────────┤
    │    0    │ '0x641a8edaec2921e904f910f063b474574bca1cb2-bsc' │  'ETH'  │ 'harbor-market' │ 'bsc' │ 123074.91860461739 │  1.5491989503442751   │ 2.08348707 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │  'https://harbor.market/markets/eth'  │ 222277.28943244176 │ 99202.37082782437  │   6.942427578115414   │   18.69626547   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    1    │ '0xd85e24a4eca78d060c0cdc7a903bac108b3fb5bc-bsc' │ 'BTCB'  │ 'harbor-market' │ 'bsc' │ 78998.05427822133  │ 5.9178320026347514e-8 │     0      │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ 'https://harbor.market/markets/btcb'  │ 79004.94568448617  │  6.89140626484716  │ 0.0013568726136629736 │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    2    │ '0x275c55d05c3550432c03902d42d7f6318b91d099-bsc' │ 'WBNB'  │ 'harbor-market' │ 'bsc' │ 61615.286809031335 │   1.249250793051286   │ 1.92105561 │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ 'https://harbor.market/markets/wbnb'  │ 102824.57194340727 │ 41209.28513437593  │   6.234226514032212   │   19.32355943   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    3    │ '0x686c55c8344e902cd8143cf4bdf2c5089be273c5-bsc' │ 'USDT'  │ 'harbor-market' │ 'bsc' │ 14065.801785107578 │  12.755773403639747   │ 4.33672689 │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ 'https://harbor.market/markets/usdt'  │ 106478.39186187496 │ 92412.59007676737  │  29.400197442758813   │   19.97559666   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    4    │ '0xca0ec956e829d999cd75c4e972beb73ceda823d5-bsc' │ 'USDC'  │ 'harbor-market' │ 'bsc' │ 13370.069538193995 │  1.8192696024805464   │ 2.93490449 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ 'https://harbor.market/markets/usdc'  │ 67344.91331394971  │ 53974.84377575571  │   4.540001972795352   │   14.64611367   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    5    │ '0x78efdcfd2e5b5b35116710ffb00c3c08fb71bceb-bsc' │ 'DOGE'  │ 'harbor-market' │ 'bsc' │  7.60618643261085  │  0.09894854384006528  │     0      │ [ '0xbA2aE424d960c26247Dd6c32edC70B295c744C43' ] │ 'https://harbor.market/markets/doge'  │  8.90386869863302  │  1.29768226602217  │   2.265097180288637   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.5  │    true    │   null   │
    │    6    │ '0x5e421cfb49977780ddef9ee321030a101a9d717e-bsc' │ 'FDUSD' │ 'harbor-market' │ 'bsc' │ 6.215681471200507  │  0.09287832046884067  │     0      │ [ '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409' ] │ 'https://harbor.market/markets/fdusd' │ 8.275906419283483  │ 2.0602249480829764 │    1.2441752319565    │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.7  │    true    │   null   │
    │    7    │ '0xc2fcc39431ff974e21ee7228d21565b3add74f7a-bsc' │ 'Cake'  │ 'harbor-market' │ 'bsc' │ 3.399406275248757  │  3.3692977124801926   │     0      │ [ '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82' ] │ 'https://harbor.market/markets/cake'  │  6.54337979994963  │ 3.143973524700873  │   23.39509018561884   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.65 │    true    │   null   │
    └─────────┴──────────────────────────────────────────────────┴─────────┴─────────────────┴───────┴────────────────────┴───────────────────────┴────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴────────────────────┴────────────────────┴───────────────────────┴─────────────────┴──────────────────────────────────────────────────┴──────┴────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The harbor-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.266 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬─────────┬─────────────────┬───────┬────────────────────┬───────────────────────┬────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬────────────────────┬───────────────────┬───────────────────────┬─────────────────┬──────────────────────────────────────────────────┬──────┬────────────┬──────────┐
    │ (index) │                       pool                       │ symbol  │     project     │ chain │       tvlUsd       │        apyBase        │ apyReward  │                 underlyingTokens                 │                  url                  │   totalSupplyUsd   │  totalBorrowUsd   │     apyBaseBorrow     │ apyRewardBorrow │                   rewardTokens                   │ ltv  │ borrowable │ poolMeta │
    ├─────────┼──────────────────────────────────────────────────┼─────────┼─────────────────┼───────┼────────────────────┼───────────────────────┼────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼────────────────────┼───────────────────┼───────────────────────┼─────────────────┼──────────────────────────────────────────────────┼──────┼────────────┼──────────┤
    │    0    │ '0x641a8edaec2921e904f910f063b474574bca1cb2-bsc' │  'ETH'  │ 'harbor-market' │ 'bsc' │ 123074.91860461739 │  1.5491989503442751   │ 2.08354521 │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │  'https://harbor.market/markets/eth'  │ 222277.3071217911  │ 99202.3885171737  │   6.942427578115414   │   18.6967872    │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    1    │ '0xd85e24a4eca78d060c0cdc7a903bac108b3fb5bc-bsc' │ 'BTCB'  │ 'harbor-market' │ 'bsc' │ 78998.05427822133  │ 5.9178320026347514e-8 │     0      │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ 'https://harbor.market/markets/btcb'  │ 79004.94568448642  │ 6.891406265087323 │ 0.0013568726136629736 │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    2    │ '0x275c55d05c3550432c03902d42d7f6318b91d099-bsc' │ 'WBNB'  │ 'harbor-market' │ 'bsc' │ 61615.286809031335 │   1.249250793051286   │ 1.92105561 │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ 'https://harbor.market/markets/wbnb'  │ 102824.57854207263 │ 41209.2917330413  │   6.234226514032212   │   19.32355943   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    3    │ '0x686c55c8344e902cd8143cf4bdf2c5089be273c5-bsc' │ 'USDT'  │ 'harbor-market' │ 'bsc' │ 14065.801785107578 │  12.755773403639747   │ 4.33768321 │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ 'https://harbor.market/markets/usdt'  │ 106478.46164653433 │ 92412.65986142676 │  29.400197442758813   │   19.98000161   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    4    │ '0xca0ec956e829d999cd75c4e972beb73ceda823d5-bsc' │ 'USDC'  │ 'harbor-market' │ 'bsc' │ 13370.069538193995 │  1.8192696024805464   │ 2.93555168 │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ 'https://harbor.market/markets/usdc'  │ 67344.91960793716  │ 53974.85006974316 │   4.540001972795352   │   14.64934338   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    5    │ '0x78efdcfd2e5b5b35116710ffb00c3c08fb71bceb-bsc' │ 'DOGE'  │ 'harbor-market' │ 'bsc' │  7.60618643261085  │  0.09894854384006528  │     0      │ [ '0xbA2aE424d960c26247Dd6c32edC70B295c744C43' ] │ 'https://harbor.market/markets/doge'  │  8.90386877415364  │ 1.29768234154279  │   2.265097180288637   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.5  │    true    │   null   │
    │    6    │ '0x5e421cfb49977780ddef9ee321030a101a9d717e-bsc' │ 'FDUSD' │ 'harbor-market' │ 'bsc' │ 6.216458528516572  │  0.09287832046884067  │     0      │ [ '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409' ] │ 'https://harbor.market/markets/fdusd' │ 8.276941102759013  │ 2.06048257424244  │    1.2441752319565    │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.7  │    true    │   null   │
    │    7    │ '0xc2fcc39431ff974e21ee7228d21565b3add74f7a-bsc' │ 'Cake'  │ 'harbor-market' │ 'bsc' │ 3.399406275248757  │  3.3692977124801926   │     0      │ [ '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82' ] │ 'https://harbor.market/markets/cake'  │ 6.543381689167931  │ 3.143975413919174 │   23.39509018561884   │        0        │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.65 │    true    │   null   │
    └─────────┴──────────────────────────────────────────────────┴─────────┴─────────────────┴───────┴────────────────────┴───────────────────────┴────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴────────────────────┴───────────────────┴───────────────────────┴─────────────────┴──────────────────────────────────────────────────┴──────┴────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by llamatester** [comment]
The harbor-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       60 passed, 60 total
    Snapshots:   0 total
    Time:        0.256 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬─────────┬─────────────────┬───────┬────────────────────┬───────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬────────────────────┬────────────────────┬───────────────────────┬──────────────────────────────────────────────────┬──────┬────────────┬──────────┐
    │ (index) │                       pool                       │ symbol  │     project     │ chain │       tvlUsd       │        apyBase        │                 underlyingTokens                 │                  url                  │   totalSupplyUsd   │   totalBorrowUsd   │     apyBaseBorrow     │                   rewardTokens                   │ ltv  │ borrowable │ poolMeta │
    ├─────────┼──────────────────────────────────────────────────┼─────────┼─────────────────┼───────┼────────────────────┼───────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼────────────────────┼────────────────────┼───────────────────────┼──────────────────────────────────────────────────┼──────┼────────────┼──────────┤
    │    0    │ '0x641a8edaec2921e904f910f063b474574bca1cb2-bsc' │  'ETH'  │ 'harbor-market' │ 'bsc' │ 123074.91860461739 │  1.5491989503442751   │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │  'https://harbor.market/markets/eth'  │ 222277.33005243388 │ 99202.41144781648  │   6.942427578115414   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    1    │ '0xd85e24a4eca78d060c0cdc7a903bac108b3fb5bc-bsc' │ 'BTCB'  │ 'harbor-market' │ 'bsc' │ 78998.05427822133  │ 5.9178320026347514e-8 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ 'https://harbor.market/markets/btcb'  │ 79004.94568448672  │ 6.891406265398667  │ 0.0013568726136629736 │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    2    │ '0x275c55d05c3550432c03902d42d7f6318b91d099-bsc' │ 'WBNB'  │ 'harbor-market' │ 'bsc' │ 61615.286809031335 │   1.249250793051286   │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ 'https://harbor.market/markets/wbnb'  │ 102824.58709589968 │ 41209.30028686835  │   6.234226514032212   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    3    │ '0x686c55c8344e902cd8143cf4bdf2c5089be273c5-bsc' │ 'USDT'  │ 'harbor-market' │ 'bsc' │ 14065.801785107578 │  12.755773403639747   │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ 'https://harbor.market/markets/usdt'  │ 106478.55210820827 │ 92412.75032310068  │  29.400197442758813   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    4    │ '0xca0ec956e829d999cd75c4e972beb73ceda823d5-bsc' │ 'USDC'  │ 'harbor-market' │ 'bsc' │ 13370.069538193995 │  1.8192696024805464   │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ 'https://harbor.market/markets/usdc'  │ 67344.92776681087  │ 53974.85822861687  │   4.540001972795352   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.8  │    true    │   null   │
    │    5    │ '0x78efdcfd2e5b5b35116710ffb00c3c08fb71bceb-bsc' │ 'DOGE'  │ 'harbor-market' │ 'bsc' │  7.60618643261085  │  0.09894854384006528  │ [ '0xbA2aE424d960c26247Dd6c32edC70B295c744C43' ] │ 'https://harbor.market/markets/doge'  │  8.90386887205074  │  1.29768243943989  │   2.265097180288637   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.5  │    true    │   null   │
    │    6    │ '0x5e421cfb49977780ddef9ee321030a101a9d717e-bsc' │ 'FDUSD' │ 'harbor-market' │ 'bsc' │ 6.214270335114534  │  0.09287832046884067  │ [ '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409' ] │ 'https://harbor.market/markets/fdusd' │ 8.274027704816614  │ 2.059757369702079  │    1.2441752319565    │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.7  │    true    │   null   │
    │    7    │ '0xc2fcc39431ff974e21ee7228d21565b3add74f7a-bsc' │ 'Cake'  │ 'harbor-market' │ 'bsc' │ 3.399406275248757  │  3.3692977124801926   │ [ '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82' ] │ 'https://harbor.market/markets/cake'  │ 6.5433841381563065 │ 3.1439778629075494 │   23.39509018561884   │ [ '0x45c19a3068642b98f5aef1dede023443cd1fbfad' ] │ 0.65 │    true    │   null   │
    └─────────┴──────────────────────────────────────────────────┴─────────┴─────────────────┴───────┴────────────────────┴───────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴────────────────────┴────────────────────┴───────────────────────┴──────────────────────────────────────────────────┴──────┴────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by Deantoshi** [comment]
Sounds good. Let me know if those new commits do the trick, or if I need to take another stab at them. Thank you!

**Comment by slasher125** [comment]
@Deantoshi ty. lets also comment out the rewardTokens field

**Comment by llamatester** [comment]
The harbor-market adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       52 passed, 52 total
    Snapshots:   0 total
    Time:        0.259 s
    Ran all test suites.
    
    Nb of pools: 8
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────────┬─────────┬─────────────────┬───────┬────────────────────┬───────────────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬────────────────────┬────────────────────┬───────────────────────┬──────┬────────────┬──────────┐
    │ (index) │                       pool                       │ symbol  │     project     │ chain │       tvlUsd       │        apyBase        │                 underlyingTokens                 │                  url                  │   totalSupplyUsd   │   totalBorrowUsd   │     apyBaseBorrow     │ ltv  │ borrowable │ poolMeta │
    ├─────────┼──────────────────────────────────────────────────┼─────────┼─────────────────┼───────┼────────────────────┼───────────────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼────────────────────┼────────────────────┼───────────────────────┼──────┼────────────┼──────────┤
    │    0    │ '0x641a8edaec2921e904f910f063b474574bca1cb2-bsc' │  'ETH'  │ 'harbor-market' │ 'bsc' │ 124000.62122411082 │  1.5491989503442751   │ [ '0x2170Ed0880ac9A755fd29B2688956BD959F933F8' ] │  'https://harbor.market/markets/eth'  │ 224006.94561162835 │ 100006.32438751752 │   6.942427578115414   │ 0.8  │    true    │   null   │
    │    1    │ '0x275c55d05c3550432c03902d42d7f6318b91d099-bsc' │ 'WBNB'  │ 'harbor-market' │ 'bsc' │ 56281.69574611446  │  1.3829605395114064   │ [ '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c' ] │ 'https://harbor.market/markets/wbnb'  │  97326.689858454   │ 41044.99411233954  │   6.559377943602696   │ 0.8  │    true    │   null   │
    │    2    │ '0xd85e24a4eca78d060c0cdc7a903bac108b3fb5bc-bsc' │ 'BTCB'  │ 'harbor-market' │ 'bsc' │  53549.8410078536  │ 1.2324864337977868e-7 │ [ '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c' ] │ 'https://harbor.market/markets/btcb'  │ 53556.582813229594 │ 6.741805375990771  │ 0.0019581629754650155 │ 0.8  │    true    │   null   │
    │    3    │ '0x686c55c8344e902cd8143cf4bdf2c5089be273c5-bsc' │ 'USDT'  │ 'harbor-market' │ 'bsc' │ 28814.60940066254  │  1.5621764414746893   │ [ '0x55d398326f99059fF775485246999027B3197955' ] │ 'https://harbor.market/markets/usdt'  │ 137545.03956853665 │ 108730.4301678741  │  3.9524377812619504   │ 0.8  │    true    │   null   │
    │    4    │ '0xca0ec956e829d999cd75c4e972beb73ceda823d5-bsc' │ 'USDC'  │ 'harbor-market' │ 'bsc' │ 12396.71707541031  │   3.697174522553726   │ [ '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d' ] │ 'https://harbor.market/markets/usdc'  │  66509.4060232762  │ 54112.68894786589  │   9.08876755489329    │ 0.8  │    true    │   null   │
    │    5    │ '0x78efdcfd2e5b5b35116710ffb00c3c08fb71bceb-bsc' │ 'DOGE'  │ 'harbor-market' │ 'bsc' │  7.70843401037685  │  0.09894854384006528  │ [ '0xbA2aE424d960c26247Dd6c32edC70B295c744C43' ] │ 'https://harbor.market/markets/doge'  │  9.02380873399401  │  1.31537472361716  │   2.265097180288637   │ 0.5  │    true    │   null   │
    │    6    │ '0x5e421cfb49977780ddef9ee321030a101a9d717e-bsc' │ 'FDUSD' │ 'harbor-market' │ 'bsc' │ 6.2141895211536635 │  0.09287832046884067  │ [ '0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409' ] │ 'https://harbor.market/markets/fdusd' │ 8.274133397211806  │ 2.059943876058141  │    1.2441752319565    │ 0.7  │    true    │   null   │
    │    7    │ '0xc2fcc39431ff974e21ee7228d21565b3add74f7a-bsc' │ 'Cake'  │ 'harbor-market' │ 'bsc' │ 3.5273409200161834 │  3.3692977124801926   │ [ '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82' ] │ 'https://harbor.market/markets/cake'  │ 6.795998711926783  │ 3.2686577919105995 │   23.39509018561884   │ 0.65 │    true    │   null   │
    └─────────┴──────────────────────────────────────────────────┴─────────┴─────────────────┴───────┴────────────────────┴───────────────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴────────────────────┴────────────────────┴───────────────────────┴──────┴────────────┴──────────┘
    This adapter contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by Deantoshi** [comment]
Gotcha, they should be updated now. Let me know if anything else comes up!

**Pull request merged**
