### PR TITLE
Add Magik Farm to Adapter

### PR DESCRIPTION
**Pull request by kfukue**
Hello, I picked up this request from the link below : 
https://github.com/DefiLlama/DefiLlama-Adapters/projects/2#card-84509930
Magik Farm(yield aggregator), requested via twitter
https://magik.farm/

I am not affiliated with this project but I looked into their code and found these pools (some are empty pools but I created them as placeholders since they existed in their source code).

Please review my PR when you have the chance. Thanks!

### CODE REVIEW

**Comment by dtmkeng** [comment]
Why don't you use multi-call from SDK

**Comment by kfukue** [comment]
@dtmkeng thanks yea that is better. I updated my code to use the sdk and I reverted the package.json related changes.

**Comment by llamatester** [comment]
The magik-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       323 passed, 323 total
    Snapshots:   0 total
    Time:        0.494 s
    Ran all test suites.
    
    Nb of pools: 64
     
    
    Sample pools:
    ┌─────────┬─────────────────────┬─────────────┬─────────────────┬───────────────┬────────────────────┬────────────────────┐
    │ (index) │        pool         │    chain    │     project     │    symbol     │       tvlUsd       │        apy         │
    ├─────────┼─────────────────────┼─────────────┼─────────────────┼───────────────┼────────────────────┼────────────────────┤
    │    0    │    'emp-emp-eth'    │  'Binance'  │ 'magik-finance' │   'EMP-ETH'   │ 1179664.034332478  │ 69.59384068827661  │
    │    1    │   'joe-wlrs-usdc'   │ 'Avalanche' │ 'magik-finance' │  'WLRS-USDC'  │ 682976.6242786385  │ 653.6123921421322  │
    │    2    │  'joe-wshare-usdc'  │ 'Avalanche' │ 'magik-finance' │ 'WSHARE-USDC' │ 357960.10700841405 │ 1046.8366888201879 │
    │    3    │  'emp-eshare-wbnb'  │  'Binance'  │ 'magik-finance' │ 'ESHARE-BNB'  │ 240773.44095370118 │ 610.8315625774857  │
    │    4    │ 'dibs-usdibs-busd'  │  'Binance'  │ 'magik-finance' │ 'USDIBS-BUSD' │ 195352.68061894586 │ 239.4464800614325  │
    │    5    │  'grape-grape-mim'  │ 'Avalanche' │ 'magik-finance' │  'GRAPE-MIM'  │ 133659.82191839992 │  180.055318360982  │
    │    6    │ 'spirit-ftm-magik'  │  'Fantom'   │ 'magik-finance' │  'MAGIK-FTM'  │ 120042.4733119962  │ 403.4350728085468  │
    │    7    │ 'grape-grapesp-mim' │ 'Avalanche' │ 'magik-finance' │  'GRAPE-MIM'  │ 89378.78680352581  │ 169.35503950084535 │
    │    8    │   'joe-nrwl-yusd'   │ 'Avalanche' │ 'magik-finance' │  'NRWL-YUSD'  │  79079.1560816352  │ 2129.072898248269  │
    │    9    │  'cham-avic-usdc'   │ 'Avalanche' │ 'magik-finance' │  'AVIC-USDC'  │  72838.9285974188  │ 361574.19170068356 │
    └─────────┴─────────────────────┴─────────────┴─────────────────┴───────────────┴────────────────────┴────────────────────┘

**Comment by vrtnd** [comment]
Would you mind updating the magik-finance adapter https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/magik-finance/index.js, because it is currently [showing](https://defillama.com/protocol/magik-finance?) 400k tvl (only tomb part) 
Anyway, thanks for the PR

**Comment by kfukue** [comment]
@vrtnd np! O ok yea I'll take a look at that repo and will send another PR.

**Comment by vrtnd** [comment]
@kfukue I just now noticed that you are not on the magik finance team. I'm sorry for asking.

**Comment by kfukue** [comment]
@vrtnd It's good! I'll take a look at it still.  I can add the part above to be included in the tvl and will group them by each chain.

**Pull request merged**
