### PR TITLE
Add new field rewardMeta to Vela Exchange and update project to include rewardMeta

### PR DESCRIPTION
**Pull request by michaelotis**
Added rewardMeta to the yield page on the defillama-app repo, updating documentation and corresponding files to indicate rewardMeta and it's use

### CODE REVIEW

**Comment by llamatester** [comment]
The vela-exchange adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       18 passed, 18 total
    Snapshots:   0 total
    Time:        0.365 s
    Ran all test suites.
    
    Nb of pools: 2
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬─────────────────┬────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │     project     │ symbol │ poolMeta │       tvlUsd       │      apyBase       │                 underlyingTokens                 │                   rewardTokens                   │     apyReward      │                                                                                                                           rewardMeta                                                                                                                           │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼─────────────────┼────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xc4abade3a15064f9e3596943c699032748b13352-arbitrum' │ 'Arbitrum' │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 10299444.567976695 │ 6.548553487328998  │ [ '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8' ] │ [ '0x088cd8f5eF3652623c22D48b1605DCfE860Cd704' ] │ 1.5245355503000741 │ 'Reward tokens are issued after staking VLP and rewards are in $esVela. Users can deposit $esVELA into the vesting contract in order to claim the same amount of $VELA. This is unlocked continuously throughout a one year (365 days) linear vesting period.' │
    │    1    │   '0xc4abade3a15064f9e3596943c699032748b13352-base'   │   'Base'   │ 'vela-exchange' │ 'USDC' │  'VLP'   │ 1479420.4858265037 │ 23.323622365258558 │ [ '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' ] │ [ '0x5A76A56ad937335168b30dF3AA1327277421C6Ae' ] │ 8.664504874785269  │ 'Reward tokens are issued after staking VLP and rewards are in $esVela. Users can deposit $esVELA into the vesting contract in order to claim the same amount of $VELA. This is unlocked continuously throughout a one year (365 days) linear vesting period.' │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴─────────────────┴────────┴──────────┴────────────────────┴────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by slasher125** [comment]
hi, i dont see the relevance off adding this given we do not show vested rewards on our page anyways. in that case we need to update the PR to exclude rewardApy from the adapter

**Comment by michaelotis** [comment]
> hi, i dont see the relevance off adding this given we do not show vested rewards on our page anyways. in that case we need to update the PR to exclude rewardApy from the adapter

I don't understand, changes were merged into the main app with that assumption. That some rewards are escrowed or even come with special circumstances that need to be conveyed for transparency.

**Comment by michaelotis** [comment]
> hi, i dont see the relevance off adding this given we do not show vested rewards on our page anyways. in that case we need to update the PR to exclude rewardApy from the adapter

@slasher125 Can you see my previous comment? Can we please get this pushed through?

**Comment by slasher125** [comment]
hi @michaelotis so, as mentioned previously we only show rewards which can be claimed without vesting.
the previous PR should not have been committed.

To confirm: apyReward on our page is what a user can get without any lockups/boosts/pre-mined etc

**Pull request closed without merging**
