### PR TITLE
Add Sturdy V2

### PR DESCRIPTION
**Pull request by atozICT20**

### CODE REVIEW

**Comment by slasher125** [comment]
hi, ty for adding.

the output for the usdt silo is:
```
Sample pools: [
  {
    pool: '0x26fe402A57D52c8a323bb6e09f06489C8216aC88',
    project: 'sturdy-v2',
    symbol: 'yvCurve-USDT-crvUSD-f',
    chain: 'ethereum',
    apyBase: 5.0064455888352,
    tvlUsd: 445294.26416639384,
    apyBaseBorrow: 5.0064455888352,
    totalSupplyUsd: 445294.26416639384,
    totalBorrowUsd: 352717.75382349314,
    debtCeilingUsd: 2285951.2607312337,
    mintedCoin: 'crvUSD',
    ltv: 0.9,
    underlyingTokens: [ '0x241AdD131B9aaa7527132b752252b99420937ADc' ]
  },
```

vs:
usdt_silo

**Comment by llamatester** [comment]
The sturdy-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.265 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                                          rewardTokens                                          │                                             url                                             │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ 'ethereum' │ 'sturdy-v2' │ 'CRVUSD' │ 3784191.2778396173 │ 0.7757208018108778 │ 42.939529038533344 │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ [ '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e' ] │
    │    1    │ '0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ 'ethereum' │ 'sturdy-v2' │ 'PXETH'  │ 1504228.1906667014 │ 1.7931440158820173 │ 26.994656265911793 │ [ '0xc55126051B22eBb829D00368f4B12Bde432de5Da', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ [ '0x04c154b66cb340f3ae24111cc767e0184ed00cc6' ] │
    │    2    │ '0xbd564bfe6f2366336ecd707862eda79b97bce383' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 745244.5896809602  │         0          │ 27.243487248881298 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xbd564bfe6f2366336ecd707862eda79b97bce383' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    │    3    │ '0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 273822.1614631909  │ 0.8401760807871016 │ 5.334163923947217  │ [ '0xa670d7237398238DE01267472C6f13e5B8010FD1', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by atozICT20** [comment]
@slasher125  Hi, We updated pools.

**Comment by slasher125** [comment]
gm, your intial approach of using the sdk is much better, so lets stick to that. it just that you need to make sure the output actually matches your ui

**Comment by atozICT20** [comment]
Hi, I know your recommendation is using the sdk. 
But, in my case, it's some difficult to do so.
As you can see, the current request includes the different pools than the initial approach, it's reward logic is off-chain, and has specified parameters.

**Comment by slasher125** [comment]
sir we don't accept centralised apis anymore, you should use what you had before (contract calls/subgraphs).

sturdy is an aave fork so should be easy to use on chain calls. if apyReward and apyRewardBorrow can't be obtained on chain, then ok to fetch these numbers (only these!) from a centralised api

**Comment by llamatester** [comment]
The sturdy-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.265 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                                          rewardTokens                                          │                                             url                                             │                 underlyingTokens                 │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┤
    │    0    │ '0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ 'ethereum' │ 'sturdy-v2' │ 'CRVUSD' │ 3679019.372881614  │ 0.9031054893289838 │ 44.56785308308031  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ [ '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e' ] │
    │    1    │ '0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ 'ethereum' │ 'sturdy-v2' │ 'PXETH'  │ 1538199.8962867493 │ 1.7931440158820173 │ 26.416698980005886 │ [ '0xc55126051B22eBb829D00368f4B12Bde432de5Da', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ [ '0x04c154b66cb340f3ae24111cc767e0184ed00cc6' ] │
    │    2    │ '0xbd564bfe6f2366336ecd707862eda79b97bce383' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 764944.3711089863  │         0          │  26.7793081868531  │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xbd564bfe6f2366336ecd707862eda79b97bce383' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    │    3    │ '0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 281060.3713149173  │ 0.8401760807871016 │ 5.2395365623734795 │ [ '0xa670d7237398238DE01267472C6f13e5B8010FD1', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

**Comment by atozICT20** [comment]
@slasher125 updated code to fetch pools from subgraph.

**Comment by slasher125** [comment]
@atozICT20 great. one final thing:
add `poolMeta` to distinguish btw the weth pools, so poolMeta would be `Swell aggregator` etc

**Comment by llamatester** [comment]
The sturdy-v2 adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       32 passed, 32 total
    Snapshots:   0 total
    Time:        0.274 s
    Ran all test suites.
    
    Nb of pools: 4
     
    
    Sample pools:
    ┌─────────┬──────────────────────────────────────────────┬────────────┬─────────────┬──────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────┬──────────────────────────────┐
    │ (index) │                     pool                     │   chain    │   project   │  symbol  │       tvlUsd       │      apyBase       │     apyReward      │                                          rewardTokens                                          │                                             url                                             │                 underlyingTokens                 │           poolMeta           │
    ├─────────┼──────────────────────────────────────────────┼────────────┼─────────────┼──────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────┼──────────────────────────────┤
    │    0    │ '0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ 'ethereum' │ 'sturdy-v2' │ 'CRVUSD' │ 3682510.9645047975 │ 0.9031054893289838 │ 45.01934202880899  │ [ '0xD533a949740bb3306d119CC777fa900bA034cd52', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x73e4c11b670ef9c025a030a20b72cb9150e54523' │ [ '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e' ] │ 'Sturdy Aggregator - crvUSD' │
    │    1    │ '0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ 'ethereum' │ 'sturdy-v2' │ 'PXETH'  │ 1556279.3560912416 │ 1.7931440158820173 │ 26.38562783457003  │ [ '0xc55126051B22eBb829D00368f4B12Bde432de5Da', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xcfb23d05f32ea0be0dbb5078d189cca89688945e' │ [ '0x04c154b66cb340f3ae24111cc767e0184ed00cc6' ] │ 'Redacted pxETH aggregator'  │
    │    2    │ '0xbd564bfe6f2366336ecd707862eda79b97bce383' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 762324.8979562655  │         0          │ 26.605668259862757 │ [ '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0xbd564bfe6f2366336ecd707862eda79b97bce383' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │      'Swell aggregator'      │
    │    3    │ '0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ 'ethereum' │ 'sturdy-v2' │  'WETH'  │ 280097.9090434637  │ 0.8401760807871016 │ 5.2395365623734795 │ [ '0xa670d7237398238DE01267472C6f13e5B8010FD1', '0xaeB3607eC434454ceB308f5Cd540875efb54309A' ] │ 'https://v2.sturdy.finance/aggregators/ethereum/0x2ca52c78d7932e285f2ea5928fb7251baec3f166' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' ] │    'Sommelier aggregator'    │
    └─────────┴──────────────────────────────────────────────┴────────────┴─────────────┴──────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────┘

**Comment by atozICT20** [comment]
@slasher125 Added `poolMeta` information.

**Pull request merged**
