### PR TITLE
adaptor for polytrade yield :tada:

### PR DESCRIPTION
**Pull request by rohitpoly**

### CODE REVIEW

**Comment by slasher125** [comment]
hi and ty for adding. a few things:
- please make use of on chain calls/subgraphs cause we are moving away from centralised api (see data sources in readme)
- are u guys listed on the main tvl dashboard yet?
- its generally advised to use apyBase and or apyReward instead of the high level apy field (we calculate the sum server side) so a user knows where the apy is coming from

**Comment by karthik-polytrade** [comment]
@slasher125 Thanks for suggestions.

- Will go with this for now and will change to direct calls later. 
- We are live on mainnet, But we are not listed in defillama. 
- We have different calculation for the apy. So, that's the reason we gave totalApy and totalTvl.

**Comment by slasher125** [comment]
you need to be listed on the tvl page first before listing on yields

**Comment by rohitpoly** [comment]
@slasher125 how do I do that? Couldn't find anything to guide me.

**Comment by slasher125** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters#defillama-adapters

**Pull request closed without merging**
