### PR TITLE
Add CompX yield farms

### PR DESCRIPTION
**Pull request by garrett-vorce-compx**

### CODE REVIEW

**Comment by garrett-vorce-compx** [comment]
@slasher125 I've ran the tests locally and everything passes, can you help advise why the ci/cd tests are failing?

Screenshot 2024-11-14 at 11 58 21 AM

**Comment by slasher125** [comment]
@garrett-vorce-compx
seems the api call breaks from server side returning a Forbidden error

**Comment by garrett-vorce-compx** [comment]
@slasher125 Our API is publicly accessible and I've checked that we're not whitelisting any domains. I've also included endpoint caching as it can take some time to fetch on-chain data.

Can you look into why it's throwing forbidden errors in your CI/CD?

**Comment by slasher125** [comment]
@garrett-vorce-compx 
i tested locally, works. one thing though: apy needs to be in %

**Comment by garrett-vorce-compx** [comment]
Thanks for your help @slasher125, I've fixed and updated our `apyBase` formatting 👍

**Comment by slasher125** [comment]
for ref:
```
Sample pools: [
  {
    pool: 'GX2RAYAGFF6G46645F2TM4OO53H3QDSGFQ5IWJP6IFWV3W4UYBO3OD2TUA-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'ALGO-gALGO',
    tvlUsd: 3926050.044755,
    apyBase: 7.2798,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'TBOOS5PQDECS22YRG4OTLGHNVODRIC2R2U24ITYIL6YYD7NTKSKCPZCOC4-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'goBTC-WBTC',
    tvlUsd: 1839688.487829,
    apyBase: 2.8259,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'W7QITGWCMOAIAV6EX3JDSHDL37LSF76M3LHTL6QD2WYMM7SGAGR3IUSLR4-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'goETH-WETH',
    tvlUsd: 1051197.120677,
    apyBase: 4.6399,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'JWOUUZ7YJJ42EHPRGW2NG64LZNUHNMWK7D5TE36GF6P6P2FXHGPZ42V2AE-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'ALGO-USDC',
    tvlUsd: 941460.009494,
    apyBase: 63.17999999999999,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: '4CVPOAFRKOPRHSSGGR5LDNUBWODU5YNZ6UFTIZTKAVALYDC5HHOISXV77M-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'fALGO-fUSDC',
    tvlUsd: 913683.478672,
    apyBase: 76.9712,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: '5PPKFCWVHW5E7CLFUHZXLXNMBYLFOZ2SBKRMMQP3O3F4UAMQ626ICBGIZE-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'fUSDC-fEURS',
    tvlUsd: 698551.630196,
    apyBase: 50.76350000000001,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'UA5STOUUVGT3ARYUCBQKXBE6L3XONZL3MOP7AC3VXP5AQA6NI5OUBRJ6UU-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'ALGO-mALGO',
    tvlUsd: 433947.285118,
    apyBase: 15.945300000000001,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'AEZ4K2FW3LSOZCZ642PZS6L5BOW226KZUDBSSPZPS7EUBU37WKE7DPB27I-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'fALGO-fgoBTC',
    tvlUsd: 260257.281725,
    apyBase: 34.788,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'SQ22EQCNX3ZTUNIHZNXIVOUJT6AF75726YEOJLEJZ5IGUJCJUK7YXAPMG4-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'fALGO-fWBTC',
    tvlUsd: 248376.391687,
    apyBase: 35.6076,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  },
  {
    pool: 'OAXOVTHYCC7OP7KMEPSFTI7LT5S7R4UPECFIT43B4HXFVY2UOUINUHNG7I-algorand',
    chain: 'Algorand',
    project: 'compx',
    symbol: 'USDC-mALGO',
    tvlUsd: 197497.992089,
    apyBase: 59.4604,
    poolMeta: 'Live Farm',
    url: 'https://app.compx.io/farms'
  }
]
```

**Pull request merged**
