### PR TITLE
feat(silo-finance/index): include more pool info in symbols

### PR DESCRIPTION
**Pull request by JayWelsh**
Includes symbols in pool names, e.g. `CVX-ETH-XAI` instead of just `CVX`

### CODE REVIEW

**Comment by llamatester** [comment]
The silo-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       124 passed, 124 total
    Snapshots:   0 total
    Time:        0.362 s
    Ran all test suites.
    
    Nb of pools: 20
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬──────────────────┬────────────────────┬────────────────────┬──────────────────┬────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ (index) │                         pool                          │   chain    │    project     │      symbol      │       tvlUsd       │      apyBase       │  apyBaseBorrow   │                                    url                                     │                                                               underlyingTokens                                                               │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼──────────────────┼────────────────────┼────────────────────┼──────────────────┼────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │    0    │ '0xc8cd77d4cd9511f2822f24ad14fe9e3c97c57836-ethereum' │ 'Ethereum' │ 'silo-finance' │    'XAI-ETH'     │ 10454314.903156452 │ 0.0037726340504185 │ 0.1000000000512  │ 'https://app.silo.finance/silo/0xc8cd77d4cd9511f2822f24ad14fe9e3c97c57836' │                        [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ]                        │
    │    1    │ '0xfccc27aabd0ab7a0b2ad2b7760037b1eab61616b-ethereum' │ 'Ethereum' │ 'silo-finance' │  'USDC-ETH-XAI'  │ 5631503.970954714  │   2.026723407e-7   │ 0.0010067300352  │ 'https://app.silo.finance/silo/0xfccc27aabd0ab7a0b2ad2b7760037b1eab61616b' │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    2    │ '0x2eaf84b425822edf450fc5fdeec085f2e5ada98b-ethereum' │ 'Ethereum' │ 'silo-finance' │ 'CBETH-ETH-XAI'  │ 497976.7941888509  │   6.94372028e-8    │ 0.0003726577584  │ 'https://app.silo.finance/silo/0x2eaf84b425822edf450fc5fdeec085f2e5ada98b' │ [ '0xbe9895146f7af43049ca1c1ae358b0541ea49704', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    3    │ '0x58f93cb4ef4e3428066c848ec4d054edd68441af-ethereum' │ 'Ethereum' │ 'silo-finance' │  'DYDX-ETH-XAI'  │ 457893.32411079644 │         0          │        0         │ 'https://app.silo.finance/silo/0x58f93cb4ef4e3428066c848ec4d054edd68441af' │ [ '0x92d6c1e31e14520e676a687f0a93788b716beff5', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    4    │ '0x92e7e77163ffed918421e3cb6e0a22f2fe8b37fa-ethereum' │ 'Ethereum' │ 'silo-finance' │  'BAL-ETH-XAI'   │ 249624.33683401524 │  7.21728343546045  │ 13.5966858761088 │ 'https://app.silo.finance/silo/0x92e7e77163ffed918421e3cb6e0a22f2fe8b37fa' │ [ '0xba100000625a3754423978a60c9317c58a424e3d', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    5    │ '0x4f5717f1efdec78a960f08871903b394e7ea95ed-ethereum' │ 'Ethereum' │ 'silo-finance' │ 'WSTETH-ETH-XAI' │ 199999.59002875653 │         0          │        0         │ 'https://app.silo.finance/silo/0x4f5717f1efdec78a960f08871903b394e7ea95ed' │ [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    6    │ '0x67b2d089c39c59a49f8fbdea43f5878b3a3f65c3-ethereum' │ 'Ethereum' │ 'silo-finance' │  'AURA-ETH-XAI'  │ 157644.2209751403  │ 7.927513405418104  │ 15.5834126301744 │ 'https://app.silo.finance/silo/0x67b2d089c39c59a49f8fbdea43f5878b3a3f65c3' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xc0c293ce456ff0ed870add98a0828dd4d2903dbf', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    7    │ '0xa104f14aeeb9b7246367d6a6e1f4e2c61a70e5d3-ethereum' │ 'Ethereum' │ 'silo-finance' │  'CVX-ETH-XAI'   │ 99686.74416685433  │         0          │        0         │ 'https://app.silo.finance/silo/0xa104f14aeeb9b7246367d6a6e1f4e2c61a70e5d3' │ [ '0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    8    │ '0xaa7103f98e57c63e1bc7a9479c8c025adff9f71d-ethereum' │ 'Ethereum' │ 'silo-finance' │  'CRV-ETH-XAI'   │ 65347.20171074706  │         0          │        0         │ 'https://app.silo.finance/silo/0xaa7103f98e57c63e1bc7a9479c8c025adff9f71d' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd533a949740bb3306d119cc777fa900ba034cd52', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    │    9    │ '0x6543ee07cf5dd7ad17aeecf22ba75860ef3bbaaa-ethereum' │ 'Ethereum' │ 'silo-finance' │  'FARM-ETH-XAI'  │ 52488.684161946156 │         0          │        0         │ 'https://app.silo.finance/silo/0x6543ee07cf5dd7ad17aeecf22ba75860ef3bbaaa' │ [ '0xa0246c9032bc3a600820415ae600c6388619a14d', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴──────────────────┴────────────────────┴────────────────────┴──────────────────┴────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    This adapters contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by slasher125** [comment]
hey, ty for updating. pls add the updated symbol into `poolMeta` and lets revert the change and keep `symbol` as is (we are deriving features from the symbol...)

**Comment by llamatester** [comment]
The silo-finance adapter exports pools: 
        
 
 Test Suites: 1 passed, 1 total
    Tests:       124 passed, 124 total
    Snapshots:   0 total
    Time:        0.36 s
    Ran all test suites.
    
    Nb of pools: 20
     
    
    Sample pools:
    ┌─────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬────────────────────┬────────────────────┬─────────────────┬────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┐
    │ (index) │                         pool                          │   chain    │    project     │  symbol  │       tvlUsd       │      apyBase       │  apyBaseBorrow  │                                    url                                     │                                                               underlyingTokens                                                               │     poolMeta     │
    ├─────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼────────────────────┼────────────────────┼─────────────────┼────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┤
    │    0    │ '0xc8cd77d4cd9511f2822f24ad14fe9e3c97c57836-ethereum' │ 'Ethereum' │ 'silo-finance' │  'XAI'   │ 10465513.724885369 │ 0.0037726340504185 │ 0.1000000000512 │ 'https://app.silo.finance/silo/0xc8cd77d4cd9511f2822f24ad14fe9e3c97c57836' │                        [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ]                        │    'XAI-ETH'     │
    │    1    │ '0xfccc27aabd0ab7a0b2ad2b7760037b1eab61616b-ethereum' │ 'Ethereum' │ 'silo-finance' │  'USDC'  │ 5634863.195869319  │   2.026723402e-7   │ 0.0010067300352 │ 'https://app.silo.finance/silo/0xfccc27aabd0ab7a0b2ad2b7760037b1eab61616b' │ [ '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'USDC-ETH-XAI'  │
    │    2    │ '0x2eaf84b425822edf450fc5fdeec085f2e5ada98b-ethereum' │ 'Ethereum' │ 'silo-finance' │ 'CBETH'  │ 495798.2713438343  │   6.94372028e-8    │ 0.0003726577584 │ 'https://app.silo.finance/silo/0x2eaf84b425822edf450fc5fdeec085f2e5ada98b' │ [ '0xbe9895146f7af43049ca1c1ae358b0541ea49704', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │ 'CBETH-ETH-XAI'  │
    │    3    │ '0x58f93cb4ef4e3428066c848ec4d054edd68441af-ethereum' │ 'Ethereum' │ 'silo-finance' │  'DYDX'  │ 458426.66981655493 │         0          │        0        │ 'https://app.silo.finance/silo/0x58f93cb4ef4e3428066c848ec4d054edd68441af' │ [ '0x92d6c1e31e14520e676a687f0a93788b716beff5', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'DYDX-ETH-XAI'  │
    │    4    │ '0x92e7e77163ffed918421e3cb6e0a22f2fe8b37fa-ethereum' │ 'Ethereum' │ 'silo-finance' │  'BAL'   │ 249740.71735417822 │ 7.267803450856706  │ 13.691860852392 │ 'https://app.silo.finance/silo/0x92e7e77163ffed918421e3cb6e0a22f2fe8b37fa' │ [ '0xba100000625a3754423978a60c9317c58a424e3d', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'BAL-ETH-XAI'   │
    │    5    │ '0x4f5717f1efdec78a960f08871903b394e7ea95ed-ethereum' │ 'Ethereum' │ 'silo-finance' │ 'WSTETH' │ 200038.5536278371  │         0          │        0        │ 'https://app.silo.finance/silo/0x4f5717f1efdec78a960f08871903b394e7ea95ed' │ [ '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │ 'WSTETH-ETH-XAI' │
    │    6    │ '0x67b2d089c39c59a49f8fbdea43f5878b3a3f65c3-ethereum' │ 'Ethereum' │ 'silo-finance' │  'AURA'  │ 157433.8180643194  │  7.94120764016887  │ 15.61033190484  │ 'https://app.silo.finance/silo/0x67b2d089c39c59a49f8fbdea43f5878b3a3f65c3' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xc0c293ce456ff0ed870add98a0828dd4d2903dbf', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'AURA-ETH-XAI'  │
    │    7    │ '0xa104f14aeeb9b7246367d6a6e1f4e2c61a70e5d3-ethereum' │ 'Ethereum' │ 'silo-finance' │  'CVX'   │  99726.3129353352  │         0          │        0        │ 'https://app.silo.finance/silo/0xa104f14aeeb9b7246367d6a6e1f4e2c61a70e5d3' │ [ '0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'CVX-ETH-XAI'   │
    │    8    │ '0xaa7103f98e57c63e1bc7a9479c8c025adff9f71d-ethereum' │ 'Ethereum' │ 'silo-finance' │  'CRV'   │ 65422.84788578401  │         0          │        0        │ 'https://app.silo.finance/silo/0xaa7103f98e57c63e1bc7a9479c8c025adff9f71d' │ [ '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd533a949740bb3306d119cc777fa900ba034cd52', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'CRV-ETH-XAI'   │
    │    9    │ '0x6543ee07cf5dd7ad17aeecf22ba75860ef3bbaaa-ethereum' │ 'Ethereum' │ 'silo-finance' │  'FARM'  │ 52506.140971570065 │         0          │        0        │ 'https://app.silo.finance/silo/0x6543ee07cf5dd7ad17aeecf22ba75860ef3bbaaa' │ [ '0xa0246c9032bc3a600820415ae600c6388619a14d', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', '0xd7c9f0e536dc865ae858b0c0453fe76d13c3beac' ] │  'FARM-ETH-XAI'  │
    └─────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴────────────────────┴────────────────────┴─────────────────┴────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┘
    This adapters contains some pools with <10k TVL, these pools won't be shown in DefiLlama

**Comment by JayWelsh** [comment]
> hey, ty for updating. pls add the updated symbol into `poolMeta` and lets revert the change and keep `symbol` as is (we are deriving features from the symbol...)

Thanks a lot @slasher125 , I've made the suggested adjustment :)

**Pull request merged**
